### ISSUE TITLE
On the latest master unable to spin up drupal 8 apps.

### ISSUE THREAD

**Issue by serundeputy** [lando/lando#1032]
on latest master trying to start RMC drupal8 app also on default example/drupal8 app:

```
geoff@yep tooling-gonzo exit code: [0] $ lando.dev start
error: Cannot create property 'name' on boolean 'true'```
verbose:
```

verbose: 

```
Loading cli task platform
error: TypeError: Cannot create property 'name' on boolean 'true'
    at _.forEach (/Users/geoff/code/lando/lib/cli.js:176:47)
    at /Users/geoff/code/lando/node_modules/lodash/lodash.js:4917:15
    at baseForOwn (/Users/geoff/code/lando/node_modules/lodash/lodash.js:3002:24)
    at /Users/geoff/code/lando/node_modules/lodash/lodash.js:4886:18
    at Function.forEach (/Users/geoff/code/lando/node_modules/lodash/lodash.js:9334:14)
    at Cli.parseToYargs (/Users/geoff/code/lando/lib/cli.js:175:7)
    at _.forEach.task (/Users/geoff/code/lando/bin/lando.js:102:31)
    at arrayEach (/Users/geoff/code/lando/node_modules/lodash/lodash.js:508:11)
    at Function.forEach (/Users/geoff/code/lando/node_modules/lodash/lodash.js:9334:14)
    at Promise.try.then.then.then (/Users/geoff/code/lando/bin/lando.js:100:7)
From previous event:
    at bootstrap.then.lando (/Users/geoff/code/lando/bin/lando.js:85:4)
```

checking out `v3.0.0-beta.47` solves the problem.   I think we have a bug.

**Comment by pirog** [comment]
@serundeputy @dustinleblanc i cant replicate this on examples/drupal8, its possible its been fixed and pushed to master already

**Comment by pirog** [comment]
@serundeputy @dustinleblanc lets eventually add this to our `lando-tooling` test card. What we want to do is check in `lando-tooling` whether our custom commands are objects or not.
