### ISSUE TITLE
MongoDB service doesn't work

### ISSUE THREAD

**Issue by hussainweb** [lando/lando#1086]
Bug Report
==========

**Tell us about your setup**

What is your lando version and operating system? **(note that the older your version the less likely we are to reply)**

v3.0.0-beta47 on MacOS High Sierra

**Tell us about your `.lando.yml`**

```yml
name: laravel-app
recipe: laravel

services:
  database:
    type: mongo:3.4

config:
  php: 7.2
  webroot: public
  xdebug: true

tooling:
  mongo:
    service: database
    description: Drop into the mongo shell
```

**Tell us about the command you were running**

Paste in a series of commands that caused the bug.

```bash
lando start
```

**Tell us about the error you got**

Rerun the command that produced your error in `verbose` mode. Paste in the error and the ~100 lines that proceeded it.

*Example:*

```bash
lando start -- -vvvv
info: Bootstraping...
verbose: Emitting event pre-bootstrap
verbose: Loading event post-bootstrap priority 1
verbose: Loading event post-bootstrap priority 2
verbose: Loading event post-bootstrap priority 5
verbose: Loading event post-instantiate-app priority 1
verbose: Loading event post-instantiate-app priority 9
verbose: Loading event post-bootstrap priority 5
verbose: Loading event post-bootstrap priority 1
verbose: Loading event post-bootstrap priority 2
verbose: Loading event post-bootstrap priority 2
verbose: Loading event post-instantiate-app priority 1
verbose: Loading event post-bootstrap priority 2
verbose: Loading event post-bootstrap priority 5
verbose: Loading event post-bootstrap priority 9
verbose: Loading event post-bootstrap priority 5
verbose: Loading event pre-engine-start priority 1
verbose: Loading event pre-engine-start priority 2
verbose: Loading event pre-engine-start priority 2
verbose: Loading event post-instantiate-app priority 1
verbose: Loading event post-instantiate-app priority 5
verbose: Loading event post-bootstrap priority 1
verbose: Loading event poweroff priority 5
verbose: Loading event post-instantiate-app priority 5
verbose: Loading event post-bootstrap priority 2
verbose: Loading event post-bootstrap priority 5
verbose: Loading event post-bootstrap priority 8
verbose: Loading event post-instantiate-app priority 2
verbose: Loading event post-bootstrap priority 1
verbose: Loading event post-bootstrap priority 2
verbose: Loading event post-bootstrap priority 5
verbose: Loading event post-bootstrap priority 9
verbose: Loading event task-rebuild-run priority 5
verbose: Loading event post-instantiate-app priority 3
verbose: Loading event post-instantiate-app priority 5
verbose: Loading event post-instantiate-app priority 8
verbose: Loading event post-bootstrap priority 2
verbose: Loading event pre-cli-load priority 5
verbose: Plugin lando-app loaded from /snapshot/lando/build/cli/plugins/lando-app/index.js
verbose: Plugin lando-core loaded from /snapshot/lando/build/cli/plugins/lando-core/index.js
verbose: Plugin lando-engine loaded from /snapshot/lando/build/cli/plugins/lando-engine/index.js
verbose: Plugin lando-events loaded from /snapshot/lando/build/cli/plugins/lando-events/index.js
verbose: Plugin lando-init loaded from /snapshot/lando/build/cli/plugins/lando-init/index.js
verbose: Plugin lando-networking loaded from /snapshot/lando/build/cli/plugins/lando-networking/index.js
verbose: Plugin lando-proxy loaded from /snapshot/lando/build/cli/plugins/lando-proxy/index.js
verbose: Plugin lando-recipes loaded from /snapshot/lando/build/cli/plugins/lando-recipes/index.js
verbose: Plugin lando-services loaded from /snapshot/lando/build/cli/plugins/lando-services/index.js
verbose: Plugin lando-tooling loaded from /snapshot/lando/build/cli/plugins/lando-tooling/index.js
verbose: Emitting event post-bootstrap
info: Configuring app plugin
verbose: App plugin configured with {"appConfigFilename":".lando.yml","appsRoot":"/Users/hw/Lando","appRegistry":"registry","configFilename":"config.yml","configSources":["/snapshot/lando/build/cli/config.yml","/Users/hw/.lando/config.yml"],"env":{"Apple_PubSub_Socket_Render":"/private/tmp/com.apple.launchd.bJtHj0wCUh/Render","COLORFGBG":"12;8","COLORTERM":"truecolor","COMMAND_MODE":"unix2003","HOME":"/Users/hw","ITERM_PROFILE":"Default","ITERM_SESSION_ID":"w0t4p0:8F8D5A14-B69C-43EB-8CE0-1A6CF998DF5E","LC_CTYPE":"UTF-8","LOGNAME":"hw","OMF_CONFIG":"/Users/hw/.config/omf","OMF_PATH":"/Users/hw/.local/share/omf","PATH":"/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet","PWD":"/Users/hw/work/laravelapp/laravelapp","SECURITYSESSIONID":"186a8","SHELL":"/usr/local/bin/fish","SHLVL":"1","SSH_AUTH_SOCK":"/private/tmp/com.apple.launchd.q5LWJz1BM6/Listeners","TERM":"xterm-256color","TERM_PROGRAM":"iTerm.app","TERM_PROGRAM_VERSION":"3.1.7","TERM_SESSION_ID":"w0t4p0:8F8D5A14-B69C-43EB-8CE0-1A6CF998DF5E","TMPDIR":"/var/folders/q8/l8cgd4_x14d5_5ptsmsc9c5m0000gn/T/","USER":"hw","XPC_FLAGS":"0x0","XPC_SERVICE_NAME":"0","__CF_USER_TEXT_ENCODING":"0x1F5:0x0:0x0"},"home":"/Users/hw","logLevel":"debug","logLevelConsole":3,"node":"v8.9.0","os":{"type":"Darwin","platform":"darwin","release":"17.6.0","arch":"x64"},"pluginDirs":["/snapshot/lando/build/cli","/Users/hw/.lando"],"product":"lando","process":"node","srcRoot":"/snapshot/lando/build/cli","userConfRoot":"/Users/hw/.lando","envPrefix":"LANDO","logDir":"/Users/hw/.lando/logs","mode":"cli","version":"3.0.0-beta.47","plugins":["lando-app","lando-core","lando-engine","lando-events","lando-init","lando-networking","lando-proxy","lando-recipes","lando-services","lando-tooling"],"stats":[{"report":true,"url":"https://metrics.devwithlando.io"}],"id":"ad82e2f1353b4345608647b584b705352c6ea4df"}
info: Configuring engine plugin
verbose: Engine plugin configured with {"composeBin":"/Applications/Docker.app/Contents/Resources/bin/docker-compose","composeVersion":"3.2","containerGlobalEnv":{},"dockerBin":"/Applications/Docker.app/Contents/Resources/bin/docker","dockerBinDir":"/Applications/Docker.app/Contents/Resources/bin","engineId":"501","engineGid":"20","engineScriptsDir":"/Users/hw/.lando/engine/scripts","appConfigFilename":".lando.yml","appsRoot":"/Users/hw/Lando","appRegistry":"registry","configFilename":"config.yml","configSources":["/snapshot/lando/build/cli/config.yml","/Users/hw/.lando/config.yml"],"env":{"Apple_PubSub_Socket_Render":"/private/tmp/com.apple.launchd.bJtHj0wCUh/Render","COLORFGBG":"12;8","COLORTERM":"truecolor","COMMAND_MODE":"unix2003","HOME":"/Users/hw","ITERM_PROFILE":"Default","ITERM_SESSION_ID":"w0t4p0:8F8D5A14-B69C-43EB-8CE0-1A6CF998DF5E","LC_CTYPE":"UTF-8","LOGNAME":"hw","OMF_CONFIG":"/Users/hw/.config/omf","OMF_PATH":"/Users/hw/.local/share/omf","PATH":"/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet","PWD":"/Users/hw/work/laravelapp/laravelapp","SECURITYSESSIONID":"186a8","SHELL":"/usr/local/bin/fish","SHLVL":"1","SSH_AUTH_SOCK":"/private/tmp/com.apple.launchd.q5LWJz1BM6/Listeners","TERM":"xterm-256color","TERM_PROGRAM":"iTerm.app","TERM_PROGRAM_VERSION":"3.1.7","TERM_SESSION_ID":"w0t4p0:8F8D5A14-B69C-43EB-8CE0-1A6CF998DF5E","TMPDIR":"/var/folders/q8/l8cgd4_x14d5_5ptsmsc9c5m0000gn/T/","USER":"hw","XPC_FLAGS":"0x0","XPC_SERVICE_NAME":"0","__CF_USER_TEXT_ENCODING":"0x1F5:0x0:0x0","LANDO_ENGINE_CONF":"/Users/hw/.lando","LANDO_ENGINE_ID":"501","LANDO_ENGINE_GID":"20","LANDO_ENGINE_HOME":"/Users/hw","LANDO_ENGINE_IP":"127.0.0.1","LANDO_ENGINE_REMOTE_IP":"host.docker.internal","LANDO_ENGINE_SCRIPTS_DIR":"/Users/hw/.lando/engine/scripts"},"home":"/Users/hw","logLevel":"debug","logLevelConsole":3,"node":"v8.9.0","os":{"type":"Darwin","platform":"darwin","release":"17.6.0","arch":"x64"},"pluginDirs":["/snapshot/lando/build/cli","/Users/hw/.lando"],"product":"lando","process":"node","srcRoot":"/snapshot/lando/build/cli","userConfRoot":"/Users/hw/.lando","envPrefix":"LANDO","logDir":"/Users/hw/.lando/logs","mode":"cli","version":"3.0.0-beta.47","plugins":["lando-app","lando-core","lando-engine","lando-events","lando-init","lando-networking","lando-proxy","lando-recipes","lando-services","lando-tooling"],"stats":[{"report":true,"url":"https://metrics.devwithlando.io"}],"id":"ad82e2f1353b4345608647b584b705352c6ea4df","engineConfig":{"socketPath":"/var/run/docker.sock","host":"127.0.0.1","port":2376}}
verbose: Copying config from /snapshot/lando/build/cli/plugins/lando-engine/scripts to /Users/hw/.lando/engine/scripts
info: Configuring proxy plugin
verbose: Proxy plugin configured with {"proxy":"ON","proxyDomain":"lndo.site","proxyDash":"58086","proxyHttpPort":"80","proxyHttpsPort":"443","proxyHttpFallbacks":["8000","8080","8888","8008"],"proxyHttpsFallbacks":["444","4433","4444","4443"],"proxyNet":"landoproxyhyperion5000gandalfedition_edge","proxyRunner":{"compose":["/Users/hw/.lando/proxy/proxy.yml","/Users/hw/.lando/proxy/ports.yml"],"project":"landoproxyhyperion5000gandalfedition","opts":{"services":["proxy"]}},"composeBin":"/Applications/Docker.app/Contents/Resources/bin/docker-compose","composeVersion":"3.2","containerGlobalEnv":{},"dockerBin":"/Applications/Docker.app/Contents/Resources/bin/docker","dockerBinDir":"/Applications/Docker.app/Contents/Resources/bin","engineId":"501","engineGid":"20","engineScriptsDir":"/Users/hw/.lando/engine/scripts","appConfigFilename":".lando.yml","appsRoot":"/Users/hw/Lando","appRegistry":"registry","configFilename":"config.yml","configSources":["/snapshot/lando/build/cli/config.yml","/Users/hw/.lando/config.yml"],"env":{"Apple_PubSub_Socket_Render":"/private/tmp/com.apple.launchd.bJtHj0wCUh/Render","COLORFGBG":"12;8","COLORTERM":"truecolor","COMMAND_MODE":"unix2003","HOME":"/Users/hw","ITERM_PROFILE":"Default","ITERM_SESSION_ID":"w0t4p0:8F8D5A14-B69C-43EB-8CE0-1A6CF998DF5E","LC_CTYPE":"UTF-8","LOGNAME":"hw","OMF_CONFIG":"/Users/hw/.config/omf","OMF_PATH":"/Users/hw/.local/share/omf","PATH":"/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet","PWD":"/Users/hw/work/laravelapp/laravelapp","SECURITYSESSIONID":"186a8","SHELL":"/usr/local/bin/fish","SHLVL":"1","SSH_AUTH_SOCK":"/private/tmp/com.apple.launchd.q5LWJz1BM6/Listeners","TERM":"xterm-256color","TERM_PROGRAM":"iTerm.app","TERM_PROGRAM_VERSION":"3.1.7","TERM_SESSION_ID":"w0t4p0:8F8D5A14-B69C-43EB-8CE0-1A6CF998DF5E","TMPDIR":"/var/folders/q8/l8cgd4_x14d5_5ptsmsc9c5m0000gn/T/","USER":"hw","XPC_FLAGS":"0x0","XPC_SERVICE_NAME":"0","__CF_USER_TEXT_ENCODING":"0x1F5:0x0:0x0","LANDO_ENGINE_CONF":"/Users/hw/.lando","LANDO_ENGINE_ID":"501","LANDO_ENGINE_GID":"20","LANDO_ENGINE_HOME":"/Users/hw","LANDO_ENGINE_IP":"127.0.0.1","LANDO_ENGINE_REMOTE_IP":"host.docker.internal","LANDO_ENGINE_SCRIPTS_DIR":"/Users/hw/.lando/engine/scripts"},"home":"/Users/hw","logLevel":"debug","logLevelConsole":3,"node":"v8.9.0","os":{"type":"Darwin","platform":"darwin","release":"17.6.0","arch":"x64"},"pluginDirs":["/snapshot/lando/build/cli","/Users/hw/.lando"],"product":"lando","process":"node","srcRoot":"/snapshot/lando/build/cli","userConfRoot":"/Users/hw/.lando","envPrefix":"LANDO","logDir":"/Users/hw/.lando/logs","mode":"cli","version":"3.0.0-beta.47","plugins":["lando-app","lando-core","lando-engine","lando-events","lando-init","lando-networking","lando-proxy","lando-recipes","lando-services","lando-tooling"],"stats":[{"report":true,"url":"https://metrics.devwithlando.io"}],"id":"ad82e2f1353b4345608647b584b705352c6ea4df","engineConfig":{"socketPath":"/var/run/docker.sock","host":"127.0.0.1","port":2376},"proxyHttpPorts":["80","8000","8080","8888","8008"],"proxyHttpsPorts":["443","444","4433","4444","4443"]}
info: Initializing proxy plugin
info: Configuring services plugin
verbose: Services plugin configured with {"servicesConfigDir":"/Users/hw/.lando/services/config","servicesHelpersDir":"/Users/hw/.lando/services/helpers","loadPassphraseProtectedKeys":false,"proxy":"ON","proxyDomain":"lndo.site","proxyDash":"58086","proxyHttpPort":"80","proxyHttpsPort":"443","proxyHttpFallbacks":["8000","8080","8888","8008"],"proxyHttpsFallbacks":["444","4433","4444","4443"],"proxyNet":"landoproxyhyperion5000gandalfedition_edge","proxyRunner":{"compose":["/Users/hw/.lando/proxy/proxy.yml","/Users/hw/.lando/proxy/ports.yml"],"project":"landoproxyhyperion5000gandalfedition","opts":{"services":["proxy"]}},"composeBin":"/Applications/Docker.app/Contents/Resources/bin/docker-compose","composeVersion":"3.2","containerGlobalEnv":{},"dockerBin":"/Applications/Docker.app/Contents/Resources/bin/docker","dockerBinDir":"/Applications/Docker.app/Contents/Resources/bin","engineId":"501","engineGid":"20","engineScriptsDir":"/Users/hw/.lando/engine/scripts","appConfigFilename":".lando.yml","appsRoot":"/Users/hw/Lando","appRegistry":"registry","configFilename":"config.yml","configSources":["/snapshot/lando/build/cli/config.yml","/Users/hw/.lando/config.yml"],"env":{"Apple_PubSub_Socket_Render":"/private/tmp/com.apple.launchd.bJtHj0wCUh/Render","COLORFGBG":"12;8","COLORTERM":"truecolor","COMMAND_MODE":"unix2003","HOME":"/Users/hw","ITERM_PROFILE":"Default","ITERM_SESSION_ID":"w0t4p0:8F8D5A14-B69C-43EB-8CE0-1A6CF998DF5E","LC_CTYPE":"UTF-8","LOGNAME":"hw","OMF_CONFIG":"/Users/hw/.config/omf","OMF_PATH":"/Users/hw/.local/share/omf","PATH":"/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet","PWD":"/Users/hw/work/laravelapp/laravelapp","SECURITYSESSIONID":"186a8","SHELL":"/usr/local/bin/fish","SHLVL":"1","SSH_AUTH_SOCK":"/private/tmp/com.apple.launchd.q5LWJz1BM6/Listeners","TERM":"xterm-256color","TERM_PROGRAM":"iTerm.app","TERM_PROGRAM_VERSION":"3.1.7","TERM_SESSION_ID":"w0t4p0:8F8D5A14-B69C-43EB-8CE0-1A6CF998DF5E","TMPDIR":"/var/folders/q8/l8cgd4_x14d5_5ptsmsc9c5m0000gn/T/","USER":"hw","XPC_FLAGS":"0x0","XPC_SERVICE_NAME":"0","__CF_USER_TEXT_ENCODING":"0x1F5:0x0:0x0","LANDO_ENGINE_CONF":"/Users/hw/.lando","LANDO_ENGINE_ID":"501","LANDO_ENGINE_GID":"20","LANDO_ENGINE_HOME":"/Users/hw","LANDO_ENGINE_IP":"127.0.0.1","LANDO_ENGINE_REMOTE_IP":"host.docker.internal","LANDO_ENGINE_SCRIPTS_DIR":"/Users/hw/.lando/engine/scripts"},"home":"/Users/hw","logLevel":"debug","logLevelConsole":3,"node":"v8.9.0","os":{"type":"Darwin","platform":"darwin","release":"17.6.0","arch":"x64"},"pluginDirs":["/snapshot/lando/build/cli","/Users/hw/.lando"],"product":"lando","process":"node","srcRoot":"/snapshot/lando/build/cli","userConfRoot":"/Users/hw/.lando","envPrefix":"LANDO","logDir":"/Users/hw/.lando/logs","mode":"cli","version":"3.0.0-beta.47","plugins":["lando-app","lando-core","lando-engine","lando-events","lando-init","lando-networking","lando-proxy","lando-recipes","lando-services","lando-tooling"],"stats":[{"report":true,"url":"https://metrics.devwithlando.io"}],"id":"ad82e2f1353b4345608647b584b705352c6ea4df","engineConfig":{"socketPath":"/var/run/docker.sock","host":"127.0.0.1","port":2376},"proxyHttpPorts":["80","8000","8080","8888","8008"],"proxyHttpsPorts":["443","444","4433","4444","4443"]}
info: Initializing app plugin
info: Initializing engine plugin
info: Initializing events
info: Initializing init framework
info: Initializing recipes plugin
info: Initializing services
verbose: Copying config from /snapshot/lando/build/cli/plugins/lando-services/helpers to /Users/hw/.lando/services/helpers
info: Initializing tooling plugin
info: Initializing core plugin
verbose: Loading event task-init-answers priority 5
verbose: Loading event task-init-run priority 5
info: Configuring networking plugin
verbose: Networking plugin configured with {"caCertDir":"/Users/hw/.lando/certs","caCert":"/Users/hw/.lando/certs/lando.pem","caService":"/Users/hw/.lando/certs/ca-setup.yml","caProject":"landocasetupkenobi38ahsokaad82e2f1353b4345608647b584b705352c6ea4df","networkBridge":"lando_bridge_network","servicesConfigDir":"/Users/hw/.lando/services/config","servicesHelpersDir":"/Users/hw/.lando/services/helpers","loadPassphraseProtectedKeys":false,"proxy":"ON","proxyDomain":"lndo.site","proxyDash":"58086","proxyHttpPort":"80","proxyHttpsPort":"443","proxyHttpFallbacks":["8000","8080","8888","8008"],"proxyHttpsFallbacks":["444","4433","4444","4443"],"proxyNet":"landoproxyhyperion5000gandalfedition_edge","proxyRunner":{"compose":["/Users/hw/.lando/proxy/proxy.yml","/Users/hw/.lando/proxy/ports.yml"],"project":"landoproxyhyperion5000gandalfedition","opts":{"services":["proxy"]}},"composeBin":"/Applications/Docker.app/Contents/Resources/bin/docker-compose","composeVersion":"3.2","containerGlobalEnv":{},"dockerBin":"/Applications/Docker.app/Contents/Resources/bin/docker","dockerBinDir":"/Applications/Docker.app/Contents/Resources/bin","engineId":"501","engineGid":"20","engineScriptsDir":"/Users/hw/.lando/engine/scripts","appConfigFilename":".lando.yml","appsRoot":"/Users/hw/Lando","appRegistry":"registry","configFilename":"config.yml","configSources":["/snapshot/lando/build/cli/config.yml","/Users/hw/.lando/config.yml"],"env":{"Apple_PubSub_Socket_Render":"/private/tmp/com.apple.launchd.bJtHj0wCUh/Render","COLORFGBG":"12;8","COLORTERM":"truecolor","COMMAND_MODE":"unix2003","HOME":"/Users/hw","ITERM_PROFILE":"Default","ITERM_SESSION_ID":"w0t4p0:8F8D5A14-B69C-43EB-8CE0-1A6CF998DF5E","LC_CTYPE":"UTF-8","LOGNAME":"hw","OMF_CONFIG":"/Users/hw/.config/omf","OMF_PATH":"/Users/hw/.local/share/omf","PATH":"/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet","PWD":"/Users/hw/work/laravelapp/laravelapp","SECURITYSESSIONID":"186a8","SHELL":"/usr/local/bin/fish","SHLVL":"1","SSH_AUTH_SOCK":"/private/tmp/com.apple.launchd.q5LWJz1BM6/Listeners","TERM":"xterm-256color","TERM_PROGRAM":"iTerm.app","TERM_PROGRAM_VERSION":"3.1.7","TERM_SESSION_ID":"w0t4p0:8F8D5A14-B69C-43EB-8CE0-1A6CF998DF5E","TMPDIR":"/var/folders/q8/l8cgd4_x14d5_5ptsmsc9c5m0000gn/T/","USER":"hw","XPC_FLAGS":"0x0","XPC_SERVICE_NAME":"0","__CF_USER_TEXT_ENCODING":"0x1F5:0x0:0x0","LANDO_ENGINE_CONF":"/Users/hw/.lando","LANDO_ENGINE_ID":"501","LANDO_ENGINE_GID":"20","LANDO_ENGINE_HOME":"/Users/hw","LANDO_ENGINE_IP":"127.0.0.1","LANDO_ENGINE_REMOTE_IP":"host.docker.internal","LANDO_ENGINE_SCRIPTS_DIR":"/Users/hw/.lando/engine/scripts"},"home":"/Users/hw","logLevel":"debug","logLevelConsole":3,"node":"v8.9.0","os":{"type":"Darwin","platform":"darwin","release":"17.6.0","arch":"x64"},"pluginDirs":["/snapshot/lando/build/cli","/Users/hw/.lando"],"product":"lando","process":"node","srcRoot":"/snapshot/lando/build/cli","userConfRoot":"/Users/hw/.lando","envPrefix":"LANDO","logDir":"/Users/hw/.lando/logs","mode":"cli","version":"3.0.0-beta.47","plugins":["lando-app","lando-core","lando-engine","lando-events","lando-init","lando-networking","lando-proxy","lando-recipes","lando-services","lando-tooling"],"stats":[{"report":true,"url":"https://metrics.devwithlando.io"}],"id":"ad82e2f1353b4345608647b584b705352c6ea4df","engineConfig":{"socketPath":"/var/run/docker.sock","host":"127.0.0.1","port":2376},"proxyHttpPorts":["80","8000","8080","8888","8008"],"proxyHttpsPorts":["443","444","4433","4444","4443"]}
verbose: Copying config from /snapshot/lando/build/cli/plugins/lando-networking/scripts to /Users/hw/.lando/engine/scripts
verbose: Loading event task-init-answers priority 5
verbose: Loading event task-init-run priority 1
verbose: Loading event post-instantiate-app priority 5
verbose: Recipe custom loaded
verbose: Recipe backdrop loaded
verbose: Recipe drupal6 loaded
verbose: Recipe drupal7 loaded
verbose: Recipe drupal8 loaded
verbose: Recipe joomla loaded
verbose: Recipe laravel loaded
verbose: Recipe lamp loaded
verbose: Recipe lemp loaded
verbose: Recipe mean loaded
verbose: Recipe pantheon loaded
verbose: Recipe wordpress loaded
verbose: Init method github loaded
verbose: Init method pantheon loaded
verbose: Service apache loaded
verbose: Service compose loaded
verbose: Service dotnet loaded
verbose: Service elasticsearch loaded
verbose: Service go loaded
verbose: Service nginx loaded
verbose: Service node loaded
verbose: Service mailhog loaded
verbose: Service mariadb loaded
verbose: Service memcached loaded
verbose: Service mssql loaded
verbose: Service mongo loaded
verbose: Service mysql loaded
verbose: Service postgres loaded
verbose: Service php loaded
verbose: Service phpmyadmin loaded
verbose: Service python loaded
verbose: Service redis loaded
verbose: Service ruby loaded
verbose: Service solr loaded
verbose: Service tomcat loaded
verbose: Service varnish loaded
info: Bootstrap completed.
info: Initializing cli
verbose: Emitting event pre-cli-load
verbose: Checking for app config at /Users/hw/work/laravelapp/laravelapp/.lando.yml
verbose: Getting app laravelapp from /Users/hw/work/laravelapp/laravelapp
verbose: Emitting event pre-instantiate-app
verbose: Emitting event post-instantiate-app
verbose: Loading event post-start priority 1
verbose: Building laravel for laravelapp
verbose: Building lamp for laravelapp
verbose: Building php 7.2 ad appserver
verbose: Building mongo 3.4 ad database
error: TypeError: undefined is not a function
    at exports.buildVolume (/snapshot/lando/build/cli/plugins/lando-services/lib/utils.js:0:0)
    at Object.services (/snapshot/lando/build/cli/plugins/lando-services/services/mongo/mongo.js:0:0)
    at Object.build (/snapshot/lando/build/cli/plugins/lando-services/services.js:0:0)
    at /snapshot/lando/build/cli/plugins/lando-services/index.js:0:0
    at isBind (/snapshot/lando/build/cli/node_modules/lodash/lodash.js:4917:15)
    at baseForOwn (/snapshot/lando/build/cli/node_modules/lodash/lodash.js:3002:24)
    at index (/snapshot/lando/build/cli/node_modules/lodash/lodash.js:4886:18)
    at Function.forEach (/snapshot/lando/build/cli/node_modules/lodash/lodash.js:9334:14)
    at AsyncEvents.<anonymous> (/snapshot/lando/build/cli/plugins/lando-services/index.js:0:0)
    at AsyncEvents.handle (/snapshot/lando/build/cli/lib/events.js:0:0)
    at /snapshot/lando/build/cli/lib/events.js:0:0
From previous event:
    at AsyncEvents.emit (/snapshot/lando/build/cli/lib/events.js:0:0)
From previous event:
    at instantiate (/snapshot/lando/build/cli/plugins/lando-app/app.js:0:0)
    at /snapshot/lando/build/cli/plugins/lando-app/app.js:0:0
From previous event:
    at Object.get (/snapshot/lando/build/cli/plugins/lando-app/app.js:0:0)
    at AsyncEvents.<anonymous> (/snapshot/lando/build/cli/plugins/lando-tooling/index.js:0:0)
    at AsyncEvents.handle (/snapshot/lando/build/cli/lib/events.js:0:0)
    at /snapshot/lando/build/cli/lib/events.js:0:0
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at AsyncEvents.emit (/snapshot/lando/build/cli/lib/events.js:0:0)
    at bootstrap.then.lando (/snapshot/lando/build/cli/bin/lando.js:0:0)
From previous event:
    at Object.<anonymous> (/snapshot/lando/build/cli/bin/lando.js:0:0)
    at Module._compile (pkg/prelude/bootstrap.js:1243:22)
    at Object.Module._extensions..js (module.js:644:10)
    at Module.load (module.js:552:32)
    at tryModuleLoad (module.js:495:12)
    at Function.Module._load (module.js:487:3)
    at Function.Module.runMain (pkg/prelude/bootstrap.js:1298:12)
    at startup (bootstrap_node.js:223:16)
    at bootstrap_node.js:644:3
```

**Tell us generally about your bug**

I just started off a Laravel recipe and added the mongo service in the lando.yml file. Without the Mongo service, the command works properly.

*Example:*

```bash
1. Run lando init and select Laravel.
2. Run lando start. It should work.
3. Add mongo service as per documentation (see .lando.yml above).
4. Run lando start. It should fail with an error: `error: undefined is not a function`
```

**Tell us more**

Could better documentation have prevented this issue? if so what should we change?

The errors seems to be in the mongo driver.

Does this bug prevent you from using lando?

Yes

**Comment by hussainweb** [comment]
I think the problem is with this: https://github.com/lando/lando/blob/master/plugins/lando-services/services/mongo/mongo.js#L67

Other services have code similar to the following:
```js
    // Handle custom config directory
    _.forEach(configFiles, function(file, type) {
      if (_.has(config, 'config.' + type)) {
        var local = config.config[type];
        var customConfig = buildVolume(local, file, '$LANDO_APP_ROOT_BIND');
        mysql.volumes = addConfig(customConfig, mysql.volumes);
      }
    });
```

In mongo.js, it is just:
```js
      // Mount the config file
      var local = config.config;
      var customConfig = buildVolume(local, remote, '$LANDO_APP_ROOT_BIND');
```

**Comment by hussainweb** [comment]
I dug deeper into this and found that the problem is that `config` option for MongoDB service is required, even though it is marked as optional. For some reason, the condition `if (_.has(config, 'config'))` always returns `TRUE` even though it is `undefined`. This passes in `undefined` to `buildVolume` method and hence the error.

I was able to fix it by setting the `config` property to a config file.

**Comment by pirog** [comment]
This is fixed in RC2 and has a test
https://github.com/lando/lando/tree/master/examples/mongo
