### ISSUE TITLE
Cannot start service ca: network not found

### ISSUE THREAD

**Issue by eleftrik** [lando/lando#1187]
Lando _3.0.0-rc.1_ on Windows 10 Pro

My .lando.yml:

```
name: test
recipe: laravel
config:
        php: '7.2'
        webroot: public
        via: nginx

```

`lando start` fails, complaining about service ca - network not found.
I tried `lando rebuild`, but no success.

Output of `lando rebuild`:

```
? Are you sure you want to rebuild? (y/N) y
? Are you sure you want to rebuild? Yes
No stopped containers
Pulling appserver ... done
Pulling nginx     ... done
Pulling database  ... done
appserver uses an image, skipping
nginx uses an image, skipping
database uses an image, skipping
Starting landocasetupkenobi38ahsokacc5a44bc262fac8f9bb1dd3a1526580ba71307e0_ca_1                                              Starting landocasetupkenobi38ahsokacc5a44bc262fac8f9bb1dd3a1526580ba71307e0_ca_1                                               ... error

ERROR: for landocasetupkenobi38ahsokacc5a44bc262fac8f9bb1dd3a1526580ba71307e0_ca                                              _1  Cannot start service ca: network 6d63cbcb74e861d6c157f4f64f310e365e42733ab00                                              bb68007ba372fb6cfddaf not found

ERROR: for ca  Cannot start service ca: network 6d63cbcb74e861d6c157f4f64f310e36                                              5e42733ab00bb68007ba372fb6cfddaf not found
Encountered errors while bringing up the project.
Starting landocasetupkenobi38ahsokacc5a44bc262fac8f9bb1dd3a1526580ba71307e0_ca_1                                              Starting landocasetupkenobi38ahsokacc5a44bc262fac8f9bb1dd3a1526580ba71307e0_ca_1                                               ... error
ERROR: for landocasetupkenobi38ahsokacc5a44bc262fac8f9bb1dd3a1526580ba71307e0_ca                                              _1  Cannot start service ca: network 6d63cbcb74e861d6c157f4f64f310e365e42733ab00                                              bb68007ba372fb6cfddaf not found

... [omitted] ...

warn: Something is wrong with the proxy! Error: Failed after 5 retries with back                                              off 500 and error Error
    at module.exports.sh.Promise.try.then (C:\snapshot\lando\build\cli\lib\shell                                              .js:0:0)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
From previous event:
    at Shell.sh (C:\snapshot\lando\build\cli\lib\shell.js:0:0)
    at dc (C:\snapshot\lando\build\cli\plugins\lando-engine\engine.js:0:0)
    at compose (C:\snapshot\lando\build\cli\plugins\lando-engine\engine.js:0:0)
    at exports.start.datum (C:\snapshot\lando\build\cli\plugins\lando-engine\lib                                              \router.js:0:0)
    at Promise.each.Promise.retry (C:\snapshot\lando\build\cli\plugins\lando-eng                                              ine\lib\router.js:0:0)
    at Promise.resolve.then.Promise.try (C:\snapshot\lando\build\cli\lib\promise                                              .js:0:0)
    at rec (C:\snapshot\lando\build\cli\lib\promise.js:0:0)
    at Promise.resolve.then.Promise.try.fn.catch.Promise.delay.then (C:\snapshot                                              \lando\build\cli\lib\promise.js:0:0)
    at ontimeout (timers.js:427:11)
    at tryOnTimeout (timers.js:289:5)
warn: Trying to take corrective action...
error: Failed after 5 retries with backoff 500 and error Error: Failed after 5 r                                              etries with backoff 500 and error Error: Error: (HTTP code 404) no such containe                                              r - No such container: landoproxyhyperion5000gandalfedition_proxy_1
    at module.exports.remove.getContainer.remove.catch.err (C:\snapshot\lando\bu                                              ild\cli\plugins\lando-engine\lib\docker.js:0:0)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
From previous event:
    at Landerode.remove (C:\snapshot\lando\build\cli\plugins\lando-engine\lib\do                                              cker.js:0:0)
    at exports.destroy.datum (C:\snapshot\lando\build\cli\plugins\lando-engine\l                                              ib\router.js:0:0)
    at Promise.each.Promise.retry (C:\snapshot\lando\build\cli\plugins\lando-eng                                              ine\lib\router.js:0:0)
    at Promise.resolve.then.Promise.try (C:\snapshot\lando\build\cli\lib\promise                                              .js:0:0)
From previous event:
    at rec (C:\snapshot\lando\build\cli\lib\promise.js:0:0)
    at Promise.resolve.then.Promise.try.fn.catch.Promise.delay.then (C:\snapshot                                              \lando\build\cli\lib\promise.js:0:0)
    at ontimeout (timers.js:427:11)
    at tryOnTimeout (timers.js:289:5)
    at listOnTimeout (timers.js:252:5)
    at Timer.processTimers (timers.js:212:10)
    at module.exports.remove.getContainer.remove.catch.err (C:\snapshot\lando\bu                                              ild\cli\plugins\lando-engine\lib\docker.js:0:0)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
    at Landerode.remove (C:\snapshot\lando\build\cli\plugins\lando-engine\lib\do                                              cker.js:0:0)
    at exports.destroy.datum (C:\snapshot\lando\build\cli\plugins\lando-engine\l                                              ib\router.js:0:0)
    at Promise.each.Promise.retry (C:\snapshot\lando\build\cli\plugins\lando-eng                                              ine\lib\router.js:0:0)
    at Promise.resolve.then.Promise.try (C:\snapshot\lando\build\cli\lib\promise                                              .js:0:0)
    at rec (C:\snapshot\lando\build\cli\lib\promise.js:0:0)
    at Promise.resolve.then.Promise.try.fn.catch.Promise.delay.then (C:\snapshot                                              \lando\build\cli\lib\promise.js:0:0)
    at ontimeout (timers.js:427:11)
    at tryOnTimeout (timers.js:289:5)
    at listOnTimeout (timers.js:252:5)
    at Timer.processTimers (timers.js:212:10)
    at Promise.resolve.then.Promise.try.fn.catch.err (C:\snapshot\lando\build\cl                                              i\lib\promise.js:0:0)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
From previous event:
    at Promise.resolve.then.Promise.try (C:\snapshot\lando\build\cli\lib\promise                                              .js:0:0)
From previous event:
    at rec (C:\snapshot\lando\build\cli\lib\promise.js:0:0)
    at Promise.resolve.then.Promise.try.fn.catch.Promise.delay.then (C:\snapshot                                              \lando\build\cli\lib\promise.js:0:0)
    at ontimeout (timers.js:427:11)
    at tryOnTimeout (timers.js:289:5)
    at listOnTimeout (timers.js:252:5)
    at Timer.processTimers (timers.js:212:10)


```

Thanks

**Comment by eleftrik** [comment]
Anyone experiencing this issue on Windows? I'm stuck :-(
I tried to uninstall and reinstall Lando, tried with different recipes, but I always got the same errors.
The same recipes works like a charm on Mac OS.

Thanks

**Comment by serundeputy** [comment]
@eleftrik i'd try:

`docker rm landocasetupkenobi38ahsokacc5a44bc262fac8f9bb1dd3a1526580ba71307e0_ca` or whatever the container name is to force it to rebuild that container.

If that does not get you anywhere you might try `docker network prune`, but in each case make an effort to back up your data if you need to.

**Comment by eleftrik** [comment]
@serundeputy THANK YOU so much! `docker rm` did the trick!
