### ISSUE TITLE
Failing to create a php.ini specific configuration

### ISSUE THREAD

**Issue by thistehneisen** [lando/lando#1272]
```
nils at nilsdigital in ~/P/some.technology
» cat .lando.yml
name: some-technology
recipe: wordpress
config:
  webroot: /some
  conf: php.ini
nils at nilsdigital in ~/P/some.technology
» lando start
error: TypeError: Cannot create property 'php' on string 'php.ini'
    at Object.resetConfig (/snapshot/lando/build/cli/plugins/lando-recipes/recipes/lamp/lamp.js:0:0)
    at Object.build (/snapshot/lando/build/cli/plugins/lando-recipes/recipes/wordpress/wordpress.js:0:0)
    at Object.build (/snapshot/lando/build/cli/plugins/lando-recipes/recipes.js:0:0)
    at AsyncEvents.module.exports.lando.events.on.app (/snapshot/lando/build/cli/plugins/lando-recipes/index.js:0:0)
    at AsyncEvents.handle (/snapshot/lando/build/cli/lib/events.js:0:0)
    at emit.Promise.each.fn (/snapshot/lando/build/cli/lib/events.js:0:0)
From previous event:
    at AsyncEvents.emit (/snapshot/lando/build/cli/lib/events.js:0:0)
    at module.exports.lando.events.emit.then.tap.app (/snapshot/lando/build/cli/plugins/lando-app/app.js:0:0)
From previous event:
    at instantiate (/snapshot/lando/build/cli/plugins/lando-app/app.js:0:0)
    at module.exports.lando.Promise.try.then.then.then.files (/snapshot/lando/build/cli/plugins/lando-app/app.js:0:0)
From previous event:
    at Object.get (/snapshot/lando/build/cli/plugins/lando-app/app.js:0:0)
    at AsyncEvents.module.exports.lando.events.on.tasks (/snapshot/lando/build/cli/plugins/lando-tooling/index.js:0:0)
    at AsyncEvents.handle (/snapshot/lando/build/cli/lib/events.js:0:0)
    at emit.Promise.each.fn (/snapshot/lando/build/cli/lib/events.js:0:0)
From previous event:
    at AsyncEvents.emit (/snapshot/lando/build/cli/lib/events.js:0:0)
    at bootstrap.then.Promise.try.then.then (/snapshot/lando/build/cli/bin/lando.js:0:0)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
From previous event:
    at bootstrap.then.lando (/snapshot/lando/build/cli/bin/lando.js:0:0)
From previous event:
    at Object.<anonymous> (/snapshot/lando/build/cli/bin/lando.js:0:0)
    at Module._compile (pkg/prelude/bootstrap.js:1252:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:711:10)
    at Module.load (internal/modules/cjs/loader.js:610:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:549:12)
    at Function.Module._load (internal/modules/cjs/loader.js:541:3)
    at Function.Module.runMain (pkg/prelude/bootstrap.js:1307:12)
    at startup (internal/bootstrap/node.js:274:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:608:3)
```

**Comment by pirog** [comment]
@thistehneisen check out the documentation because this is not a valid setting for `conf`
