### ISSUE TITLE
Pantheon run auth:login to authenticate returns blank response and does not work

### ISSUE THREAD

**Issue by smthomas** [lando/lando#1284]
Lando Version: v3.0.0-rc.1
Operating System: Ubuntu 18.10

.lando.yml
```yml
name: learncreatebuild
recipe: pantheon
config:
  framework: drupal8
  site: learncreatebuild
  id: XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX
  webroot: web
  xdebug: true
  drush: path:/app/vendor/bin/drush
tooling:
  drupal:
    cmd:
      - "/app/vendor/bin/drupal"
```
pantheon.yml
```yml
api_version: 1
web_docroot: true
php_version: 7.2
workflows:
  deploy_product:
    after:
      -
        type: webphp
        description: 'Run composer prepare-for-pantheon'
        script: private/scripts/deploy_product/prepare-for-pantheon.php
      -
        type: webphp
        description: 'Run composer install & drupal-scaffold'
        script: private/scripts/deploy_product/composer-install.php
  sync_code:
    after:
      - type: webphp
        description: Push changes back to GitHub if needed
        script: private/scripts/quicksilver/quicksilver-pushback/push-back-to-github.php
```
Steps to reproduce the problem:

1. Cloned Git repo containing Pantheon website
2. Ran the following commands:

```bash
lando init
lando start
lando pull
```

Here is the error I receive stating I am not logged in (although I was able to initialize the site without any authentication problems)

```bash
debug: Emitting event task-pull-run
debug: Event task-pull-run has 0 listeners
debug: Emitting event pre-pull
debug: Event pre-pull has 0 listeners
debug: Emitting event pre-engine-up
debug: Event pre-engine-up has 0 listeners
debug: Trying to retrieve from file cache with key engineup
debug: File cache miss with key engineup
debug: Engine is up.
debug: Cached true with key engineup for {"persist":false,"ttl":5}
debug: Emitting event post-engine-up
debug: Event post-engine-up has 0 listeners
debug: Emitting event pre-engine-run
debug: Event pre-engine-run has 0 listeners
Verifying that you are logged in and authenticated by getting info about mysite...
PHP Recoverable fatal error:  PHP Startup: Cannot set 'user' save handler by ini_set() or session_module_name() in Unknown on line 0
 [error]  You are not logged in. Run `auth:login` to authenticate or `help auth:login` for more info. 
 [notice] A new Terminus version v1.9.0 is available.
You are currently using version v1.8.1. 
You can update Terminus by running `composer update` or using the Terminus installer:
curl -O https://raw.githubusercontent.com/pantheon-systems/terminus-installer/master/builds/installer.phar && php installer.phar update
debug: Logging metrics data {"devMode":false,"nodeVersion":"v10.4.1","mode":"cli","os":{"type":"Linux","platform":"linux","release":"4.18.0-10-generic","arch":"x64"},"product":"lando","version":"3.0.0-rc.1","message":"Verifying that you are logged in and authenticated by getting info about mysite...\r\nPHP Recoverable fatal error:  PHP Startup: Cannot set 'user' save handler by ini_set() or session_module_name() in Unknown on line 0\r\n \u001b[37;41;1m[error]\u001b[39;49;22m \u001b[37;41;1m You are not logged in. Run `auth:login` to authenticate or `help auth:login` for more info. \u001b[39;49;22m\r\n \u001b[37;46;1m[notice]\u001b[39;49;22m \u001b[38;5;33mA new Terminus version v\u001b[32m\u001b[38;5;45m1.9.0\u001b[39m\u001b[38;5;33m is available.\r\nYou are currently using version v\u001b[32m\u001b[38;5;45m1.8.1\u001b[39m\u001b[38;5;33m. \r\nYou can update Terminus by running `composer update` or using the Terminus installer:\r\n\u001b[32m\u001b[38;5;45mcurl -O https://raw.githubusercontent.com/pantheon-systems/terminus-installer/master/builds/installer.phar && php installer.phar update\u001b[39m\u001b[38;5;33m\u001b[0m\r\n","action":"error","created":"2018-11-07T22:21:43.186Z"}
```

I followed that up by trying to re-authenticate. This produced a blank response.
```bash
lando terminus auth:login --machine-token=?
```
Here is the verbose output:
```bash
verbose: Additional tooling detected for app mysite
verbose: Adding app cli task composer
verbose: Adding app cli task db-import [file]
verbose: Adding app cli task db-export [file]
verbose: Adding app cli task php
verbose: Adding app cli task mysql
verbose: Adding app cli task drush
verbose: Adding app cli task drupal
verbose: Adding app cli task redis-cli
verbose: Adding app cli task varnishadm
verbose: Adding app cli task terminus
verbose: Adding app cli task pull
verbose: Adding app cli task push
verbose: Adding app cli task switch <env>
verbose: App tooling loaded.
info: Initializing cli
debug: Trying to retrieve from file cache with key updates
verbose: Loading cli task composer
verbose: Loading cli task config
verbose: Loading cli task db-export
verbose: Loading cli task db-import
verbose: Loading cli task destroy
verbose: Loading cli task drupal
verbose: Loading cli task drush
verbose: Loading cli task info
verbose: Loading cli task init
verbose: Loading cli task list
verbose: Loading cli task logs
verbose: Loading cli task mysql
verbose: Loading cli task php
verbose: Loading cli task poweroff
verbose: Loading cli task pull
verbose: Loading cli task push
verbose: Loading cli task rebuild
verbose: Loading cli task redis-cli
verbose: Loading cli task restart
verbose: Loading cli task share
verbose: Loading cli task ssh
verbose: Loading cli task start
verbose: Loading cli task stop
verbose: Loading cli task switch
verbose: Loading cli task terminus
verbose: Loading cli task varnishadm
verbose: Loading cli task version
debug: Emitting event task-terminus-answers
debug: Event task-terminus-answers has 0 listeners
debug: CLI args _=[terminus, auth:login, -vvvv], machine-token=????, machineToken=????, $0=/usr/share/lando/bin/lando /snapshot/lando/build/cli/bin/lando.js
debug: Emitting event task-terminus-run
debug: Event task-terminus-run has 0 listeners
debug: Emitting event pre-terminus
debug: Event pre-terminus has 1 listeners
debug: Trying to retrieve from file cache with key site.meta.mysite
debug: Trying to retrieve from file cache with key site.meta.mysite
debug: Logging metrics data {"devMode":false,"nodeVersion":"v10.4.1","mode":"cli","os":{"type":"Linux","platform":"linux","release":"4.18.0-10-generic","arch":"x64"},"product":"lando","version":"3.0.0-rc.1","message":"Assignment to constant variable.","stack":"TypeError: Assignment to constant variable.\n    at AsyncEvents.module.exports.lando.events.on.app.events.on (/snapshot/lando/build/cli/plugins/lando-recipes/recipes/pantheon/pantheon.js:0:0)\n    at AsyncEvents.handle (/snapshot/lando/build/cli/lib/events.js:0:0)\n    at emit.Promise.each.fn (/snapshot/lando/build/cli/lib/events.js:0:0)\n    at runCallback (timers.js:696:18)\n    at tryOnImmediate (timers.js:667:5)\n    at processImmediate (timers.js:649:5)\nFrom previous event:\n    at AsyncEvents.emit (/snapshot/lando/build/cli/lib/events.js:0:0)\n    at Object.exports.runCommands (/snapshot/lando/build/cli/plugins/lando-tooling/lib/utils.js:0:0)\n    at run (/snapshot/lando/build/cli/plugins/lando-tooling/tooling.js:0:0)\n    at module.exports.parseToYargs.events.emit.then.then.events.emit.then (/snapshot/lando/build/cli/lib/cli.js:0:0)\nFrom previous event:\n    at module.exports.parseToYargs.events.emit.then.then.answers (/snapshot/lando/build/cli/lib/cli.js:0:0)\n    at runCallback (timers.js:696:18)\n    at tryOnImmediate (timers.js:667:5)\n    at processImmediate (timers.js:649:5)\nFrom previous event:\n    at Object.handler (/snapshot/lando/build/cli/lib/cli.js:0:0)\n    at Object.module.exports.self.runCommand (/snapshot/lando/build/cli/node_modules/yargs/lib/command.js:170:22)\n    at parseArgs (/snapshot/lando/build/cli/node_modules/yargs/yargs.js:920:28)\n    at Object.get [as argv] (/snapshot/lando/build/cli/node_modules/yargs/yargs.js:860:16)\n    at bootstrap.then.Promise.try.then.then.then (/snapshot/lando/build/cli/bin/lando.js:0:0)\nFrom previous event:\n    at bootstrap.then.lando (/snapshot/lando/build/cli/bin/lando.js:0:0)\nFrom previous event:\n    at Object.<anonymous> (/snapshot/lando/build/cli/bin/lando.js:0:0)\n    at Module._compile (pkg/prelude/bootstrap.js:1252:22)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:711:10)\n    at Module.load (internal/modules/cjs/loader.js:610:32)\n    at tryModuleLoad (internal/modules/cjs/loader.js:549:12)\n    at Function.Module._load (internal/modules/cjs/loader.js:541:3)\n    at Function.Module.runMain (pkg/prelude/bootstrap.js:1307:12)\n    at startup (internal/bootstrap/node.js:274:19)\n    at bootstrapNodeJSCore (internal/bootstrap/node.js:608:3)","action":"error","created":"2018-11-07T22:29:03.471Z"}
```
I solved it by running `lando ssh` first, then running the terminus command from within the container. I was then able to exit out of the container and run the `lando pull` command without error.

**Comment by elliottpost** [comment]
Having the same issue on MacOS 10.14.1 (Mojave) with Lando v3.0.0-rc.1. Only on some of my lando containers, for some reason. Tried rebuilding, it did not work; however, @smthomas's solution did:

> I solved it by running `lando ssh` first, then running the terminus command from within the container. I was then able to exit out of the container and run the `lando pull` command without error.

**Comment by arosboro** [comment]
I destroyed recently and this cropped up, I had to additionally supply --database --code and --files parameters to lando pull, the prompt was saying I had not authenticated after ssh'ing into the container and running terminus auth:login successfully.

**Comment by DaveLak** [comment]
I'm having this same issue on Mac os 10.14.1 as well. Every time I `lando pull` I have to first `lando ssh` and `terminus auth:login --machine-token=TOKEN` with a new machine token. It does appear I remain authenticated for some amount of time and it does persist between start and stops however I need to add a new machine token at-least once a week.

It's worth noting I also see the following error as my `$SITE_appserver_1` is starting during every `lando start`:

```
 [notice] Logging in via machine token.
 [error]  Client error: `POST https://terminus.pantheon.io/api/authorize/machine-token` resulted in a `401 Unauthorized` response:
"Authorization failed. Please check that your machine token is valid."
error: Looks like one of your build steps failed with [object Object]
warn: This **MAY** prevent your app from working
warn: Check for errors above, fix them, and try again
```

**Comment by nikanderson** [comment]
Closing this seems premature if such improved auth handling may or may not fix the issue. How forthcoming is rc2, incidentally?

**Comment by pirog** [comment]
It’s not premature regardless of whether it fixes or doesn’t fix the issue
because it’s not going to be fixed for the version that the person who open
this was using.

If there are further or similar issues with rc2 then a new issue should be
opened

**Comment by dwking2000** [comment]
I found a solution but I still get similar errors to some of the others above, but my pulls work now.
 I had the same problem, was not able to pull.

- I'm running on a Mac Mojave 10.14.2 (18C54)
- Docker Version 2.0.0.0-mac81 (29211), Engine 18.09.0
- Drush Commandline Tool 9.5.2
- PHP 7.1.19 (cli)
- lando v3.0.0-rc.1


lando.yml
name: my-demo-01
recipe: pantheon
config:
  framework: drupal8
  site: my-demo-01
  id: bf82dbff-492a-95ad-3003af4504
  webroot: .

My solution was to:

- lando destroy
- **restart docker**
- lando start
- lando terminus auth:login --machine-token=MYTOKEN

at this point I get back:

PHP Recoverable fatal error:  PHP Startup: Cannot set 'user' save handler by ini_set() or session_module_name() in Unknown on line 0
 [notice] Logging in via machine token.

However, I am logged in now and I can continue on and do:
- lando pull 
this is now successfully but in the process I am getting:

PHP Recoverable fatal error:  PHP Startup: Cannot set 'user' save handler by ini_set() or session_module_name() in Unknown on line 0

So I am able to work around this and do a pull, but not sure where the PHP Startup errors are coming from or if I should be concerned about them. 

This process is **not** successful if I don't restart docker.

**Comment by nikanderson** [comment]
@dwking2000 When you say you "restart docker" can you be more specific about this step?

The `ini_set()` related errors you mention are unrelated to this issue and are being discussed in #747 

Does your procedure work around this error permanently or do you need to do this repeatedly? I am concerned that it is the latter because I'd like to use `lando terminus` commands without destroying and rebuilding my lando-based environment each time. I'm working with a site that has a compressed database dump around 1.4GB in size, so being required to regularly `lando destroy` is a non-starter to me.

**Comment by dwking2000** [comment]
@nikanderson On my Mac I restart the docker engine from the docker menu. This just stops and starts the docker daemon. Any containers that are still running will be shut down.

I can't say how often I need to do this. It seems that one time is enough. I have done several pulls and pushes now and it seems to be fine.

**Comment by merlinpatt** [comment]
I had this same issue and this solved it for me

> I solved it by running lando ssh first, then running the terminus command from within the container. I was then able to exit out of the container and run the lando pull command without error.

Thanks!
