### ISSUE TITLE
wordpress_network framework for pantheon recipes is a problem

### ISSUE THREAD

**Issue by wilirius** [lando/lando#1425]
lando version: lando v3.0.0-rc.7
docker -v: Docker version 18.09.1, build 4c52b90
Windows 10 Pro, Hyper V enabled.

**.lando.yml:**

```name: merceredu
recipe: pantheon
config:
  framework: wordpress_network
  site: merceredu
  id: 48a9745a-0ffc-4b84-be57-cd2bc957f7ef
  # disable SOLR
  index: false
  # disable varnish
  edge: false
  # disable redis
  cache: false
```
**pantheon.yml:**

```# Put overrides to your pantheon.upstream.yml file here.
# For more information, see: https://pantheon.io/docs/pantheon-yml/
api_version: 1
```

**Tell us about the command you were running**
```bash
lando start
```

**Paste in a series of commands that caused the bug.**

```bash
lando init
# follow prompts, choosing pantheon, machine token, choose site
lando start
# Edited my lando.yml as above
lando rebuild -y
# Errors "is not connected to the network lando_bridge_network
docker ps -a
lando poweroff
docker ps -a
lando rebuild -y
```
```
Killing merceredu_appserver_1 ... done
Starting merceredu_appserver_1 ... done
Creating merceredu_database_1        ... done
Creating merceredu_appserver_nginx_1 ... done
Waiting until appserver_nginx service is ready...
Waiting until database service is ready...
Waiting until appserver service is ready...
Starting merceredu_appserver_1 ... done
Starting merceredu_appserver_nginx_1 ... done
Error response from daemon: Container d8d068cb2a64afeb9da8e2c489dd4e87f5224c426a022449267cf6a7ea9024fa is not running
error: Looks like appserver_nginx is not running! It should be so this is a problem.
warn: Try running `lando logs -s appserver_nginx` to help locate the problem!

BOOMSHAKALAKA!!!
```

```bash
lando logs -s appserver_nginx
```
```
Attaching to merceredu_appserver_nginx_1
appserver_nginx_1  | This is a debian container
appserver_nginx_1  | user-perms.sh kicking off as user uid=0(root) gid=0(root) groups=0(root)
appserver_nginx_1  | Lando ENVVARS set at
appserver_nginx_1  | LANDO_WEBROOT_USER: www-data
appserver_nginx_1  | LANDO_WEBROOT_GROUP: www-data
appserver_nginx_1  | LANDO_WEBROOT_UID: 33
appserver_nginx_1  | LANDO_WEBROOT_GID: 33
appserver_nginx_1  | LANDO_HOST_UID: 1000
appserver_nginx_1  | LANDO_HOST_GID: 1000
appserver_nginx_1  | Making sure correct user:group (www-data:www-data) exists...
appserver_nginx_1  | And here. we. go.
appserver_nginx_1  | Cert creation kicking off
appserver_nginx_1  | LANDO_CA_CERT: /lando/certs/lndo.site.pem
appserver_nginx_1  | LANDO_CA_KEY: /lando/certs/lndo.site.key
appserver_nginx_1  | CA_DIR: /usr/share/ca-certificates
appserver_nginx_1  | CA_CERT_FILENAME: lndo.site.pem
appserver_nginx_1  | CA_CERT_CONTAINER: /usr/share/ca-certificates/lndo.site.pem
appserver_nginx_1  | Generating certs...
appserver_nginx_1  | Generating RSA private key, 2048 bit long modulus
appserver_nginx_1  | ...................................................................................................................................................................................+++++
appserver_nginx_1  | .....................................................+++++
appserver_nginx_1  | e is 65537 (0x010001)
appserver_nginx_1  | Signature ok
appserver_nginx_1  | subject=C = US, ST = California, L = San Francisco, O = Lando, OU = Bespin, CN = *.lndo.site
appserver_nginx_1  | Getting CA Private Key
appserver_nginx_1  | /usr/share/ca-certificates/lndo.site.pem not found... copying /lando/certs/lndo.site.pem over
appserver_nginx_1  | Creating a special not-mounted key directory for Windows
appserver_nginx_1  | Scanning /lando_keys for keys...
appserver_nginx_1  | Using the following keys:
appserver_nginx_1  | Running command /bin/bash -c mkdir -p /opt/bitnami/nginx/conf/vhosts && render-template /opt/bitnami/extra/nginx/templates/default.conf.tpl > /opt/bitnami/nginx/conf/vhosts/lando.conf && /entrypoint.sh /run.sh
appserver_nginx_1  | Running with exec!
appserver_nginx_1  | cannot parse template: read /opt/bitnami/extra/nginx/templates/default.conf.tpl: is a directory
appserver_nginx_1  | This is a debian container
appserver_nginx_1  | user-perms.sh kicking off as user uid=0(root) gid=0(root) groups=0(root)
appserver_nginx_1  | Lando ENVVARS set at
appserver_nginx_1  | LANDO_WEBROOT_USER: www-data
appserver_nginx_1  | LANDO_WEBROOT_GROUP: www-data
appserver_nginx_1  | LANDO_WEBROOT_UID: 33
appserver_nginx_1  | LANDO_WEBROOT_GID: 33
appserver_nginx_1  | LANDO_HOST_UID: 1000
appserver_nginx_1  | LANDO_HOST_GID: 1000
appserver_nginx_1  | Making sure correct user:group (www-data:www-data) exists...
appserver_nginx_1  | And here. we. go.
appserver_nginx_1  | Creating a special not-mounted key directory for Windows
appserver_nginx_1  | Scanning /lando_keys for keys...
appserver_nginx_1  | Using the following keys:
appserver_nginx_1  | Running command /bin/bash -c mkdir -p /opt/bitnami/nginx/conf/vhosts && render-template /opt/bitnami/extra/nginx/templates/default.conf.tpl > /opt/bitnami/nginx/conf/vhosts/lando.conf && /entrypoint.sh /run.sh
appserver_nginx_1  | Running with exec!
appserver_nginx_1  | cannot parse template: read /opt/bitnami/extra/nginx/templates/default.conf.tpl: is a directory
```

```bash
lando start -vvv
```

```
...
info: Checking to see if http://merceredu.lndo.site is ready.
verbose: http://merceredu.lndo.site not currently accessible
verbose: http://merceredu.lndo.site not currently accessible
info: Checking to see if https://merceredu.lndo.site is ready.
verbose: https://merceredu.lndo.site not currently accessible
verbose: https://merceredu.lndo.site not currently accessible
debug: URL scan results url=http://merceredu.lndo.site, status=false, color=red, url=https://merceredu.lndo.site, status=false, color=red
debug: Emitting event pre-engine-up
debug: Event pre-engine-up has 0 listeners
debug: Engine is up.
debug: Emitting event post-engine-up
debug: Event post-engine-up has 0 listeners
debug: Emitting event pre-engine-run
debug: Event pre-engine-run has 0 listeners
verbose: Running ["C:\\Program Files\\Docker\\Docker\\resources\\bin\\docker-compose.exe","--project-name","merceredu","--file","C:\\Users\\Will Hawthorne\\.lando\\compose\\merceredu\\globals-0.yml","--file","C:\\Users\\Will Hawthorne\\.lando\\compose\\merceredu\\appserver-0.yml","--file","C:\\Users\\Will Hawthorne\\.lando\\compose\\merceredu\\appserver-1.yml","--file","C:\\Users\\Will Hawthorne\\.lando\\compose\\merceredu\\appserver-2.yml","--file","C:\\Users\\Will Hawthorne\\.lando\\compose\\merceredu\\appserver-3.yml","--file","C:\\Users\\Will Hawthorne\\.lando\\compose\\merceredu\\appserver-4.yml","--file","C:\\Users\\Will Hawthorne\\.lando\\compose\\merceredu\\appserver-5.yml","--file","C:\\Users\\Will Hawthorne\\.lando\\compose\\merceredu\\appserver-6.yml","--file","C:\\Users\\Will Hawthorne\\.lando\\compose\\merceredu\\appserver-7.yml","--file","C:\\Users\\Will Hawthorne\\.lando\\compose\\merceredu\\appserver-8.yml","--file","C:\\Users\\Will Hawthorne\\.lando\\compose\\merceredu\\database-0.yml","--file","C:\\Users\\Will Hawthorne\\.lando\\compose\\merceredu\\database-1.yml","--file","C:\\Users\\Will Hawthorne\\.lando\\compose\\merceredu\\database-2.yml","--file","C:\\Users\\Will Hawthorne\\.lando\\compose\\merceredu\\database-3.yml","--file","C:\\Users\\Will Hawthorne\\.lando\\compose\\merceredu\\database-4.yml","--file","C:\\Users\\Will Hawthorne\\.lando\\compose\\merceredu\\database-5.yml","--file","C:\\Users\\Will Hawthorne\\.lando\\compose\\merceredu\\proxy-0.yml","up","--detach","--no-recreate","--remove-orphans","appserver_nginx"] in C:\Users\Will Hawthorne\Documents\Projects\Mercer\dev-mercer-edu\lando with options {"mode":"collect","detached":false}
debug: With stdio=[Circular], mode=collect, detached=false
Starting merceredu_appserver_1 ... done
Starting merceredu_appserver_nginx_1 ... done
verbose: C:\Program Files\Docker\Docker\resources\bin\docker-compose.exe,--project-name,merceredu,--file,C:\Users\Will Hawthorne\.lando\compose\merceredu\globals-0.yml,--file,C:\Users\Will Hawthorne\.lando\compose\merceredu\appserver-0.yml,--file,C:\Users\Will Hawthorne\.lando\compose\merceredu\appserver-1.yml,--file,C:\Users\Will Hawthorne\.lando\compose\merceredu\appserver-2.yml,--file,C:\Users\Will Hawthorne\.lando\compose\merceredu\appserver-3.yml,--file,C:\Users\Will Hawthorne\.lando\compose\merceredu\appserver-4.yml,--file,C:\Users\Will Hawthorne\.lando\compose\merceredu\appserver-5.yml,--file,C:\Users\Will Hawthorne\.lando\compose\merceredu\appserver-6.yml,--file,C:\Users\Will Hawthorne\.lando\compose\merceredu\appserver-7.yml,--file,C:\Users\Will Hawthorne\.lando\compose\merceredu\appserver-8.yml,--file,C:\Users\Will Hawthorne\.lando\compose\merceredu\database-0.yml,--file,C:\Users\Will Hawthorne\.lando\compose\merceredu\database-1.yml,--file,C:\Users\Will Hawthorne\.lando\compose\merceredu\database-2.yml,--file,C:\Users\Will Hawthorne\.lando\compose\merceredu\database-3.yml,--file,C:\Users\Will Hawthorne\.lando\compose\merceredu\database-4.yml,--file,C:\Users\Will Hawthorne\.lando\compose\merceredu\database-5.yml,--file,C:\Users\Will Hawthorne\.lando\compose\merceredu\proxy-0.yml,up,--detach,--no-recreate,--remove-orphans,appserver_nginx finished with code 0
verbose: Running ["C:\\Program Files\\Docker\\Docker\\resources\\bin\\docker-compose.exe","--project-name","merceredu","--file","C:\\Users\\Will Hawthorne\\.lando\\compose\\merceredu\\globals-0.yml","--file","C:\\Users\\Will Hawthorne\\.lando\\compose\\merceredu\\appserver-0.yml","--file","C:\\Users\\Will Hawthorne\\.lando\\compose\\merceredu\\appserver-1.yml","--file","C:\\Users\\Will Hawthorne\\.lando\\compose\\merceredu\\appserver-2.yml","--file","C:\\Users\\Will Hawthorne\\.lando\\compose\\merceredu\\appserver-3.yml","--file","C:\\Users\\Will Hawthorne\\.lando\\compose\\merceredu\\appserver-4.yml","--file","C:\\Users\\Will Hawthorne\\.lando\\compose\\merceredu\\appserver-5.yml","--file","C:\\Users\\Will Hawthorne\\.lando\\compose\\merceredu\\appserver-6.yml","--file","C:\\Users\\Will Hawthorne\\.lando\\compose\\merceredu\\appserver-7.yml","--file","C:\\Users\\Will Hawthorne\\.lando\\compose\\merceredu\\appserver-8.yml","--file","C:\\Users\\Will Hawthorne\\.lando\\compose\\merceredu\\database-0.yml","--file","C:\\Users\\Will Hawthorne\\.lando\\compose\\merceredu\\database-1.yml","--file","C:\\Users\\Will Hawthorne\\.lando\\compose\\merceredu\\database-2.yml","--file","C:\\Users\\Will Hawthorne\\.lando\\compose\\merceredu\\database-3.yml","--file","C:\\Users\\Will Hawthorne\\.lando\\compose\\merceredu\\database-4.yml","--file","C:\\Users\\Will Hawthorne\\.lando\\compose\\merceredu\\database-5.yml","--file","C:\\Users\\Will Hawthorne\\.lando\\compose\\merceredu\\proxy-0.yml","exec","--detach","--env","PHP_MEMORY_LIMIT=-1","--user","root","appserver_nginx","/bin/sh","-c","/helpers/refresh-certs.sh > /cert-log.txt"] in C:\Users\Will Hawthorne\Documents\Projects\Mercer\dev-mercer-edu\lando with options {"mode":"attach","detached":false}
debug: With stdio={"stdio":"inherit"}, mode=attach, detached=false
Error response from daemon: Container d8d068cb2a64afeb9da8e2c489dd4e87f5224c426a022449267cf6a7ea9024fa is not running
verbose: C:\Program Files\Docker\Docker\resources\bin\docker-compose.exe,--project-name,merceredu,--file,C:\Users\Will Hawthorne\.lando\compose\merceredu\globals-0.yml,--file,C:\Users\Will Hawthorne\.lando\compose\merceredu\appserver-0.yml,--file,C:\Users\Will Hawthorne\.lando\compose\merceredu\appserver-1.yml,--file,C:\Users\Will Hawthorne\.lando\compose\merceredu\appserver-2.yml,--file,C:\Users\Will Hawthorne\.lando\compose\merceredu\appserver-3.yml,--file,C:\Users\Will Hawthorne\.lando\compose\merceredu\appserver-4.yml,--file,C:\Users\Will Hawthorne\.lando\compose\merceredu\appserver-5.yml,--file,C:\Users\Will Hawthorne\.lando\compose\merceredu\appserver-6.yml,--file,C:\Users\Will Hawthorne\.lando\compose\merceredu\appserver-7.yml,--file,C:\Users\Will Hawthorne\.lando\compose\merceredu\appserver-8.yml,--file,C:\Users\Will Hawthorne\.lando\compose\merceredu\database-0.yml,--file,C:\Users\Will Hawthorne\.lando\compose\merceredu\database-1.yml,--file,C:\Users\Will Hawthorne\.lando\compose\merceredu\database-2.yml,--file,C:\Users\Will Hawthorne\.lando\compose\merceredu\database-3.yml,--file,C:\Users\Will Hawthorne\.lando\compose\merceredu\database-4.yml,--file,C:\Users\Will Hawthorne\.lando\compose\merceredu\database-5.yml,--file,C:\Users\Will Hawthorne\.lando\compose\merceredu\proxy-0.yml,exec,--detach,--env,PHP_MEMORY_LIMIT=-1,--user,root,appserver_nginx,/bin/sh,-c,/helpers/refresh-certs.sh > /cert-log.txt finished with code 1
error: Looks like appserver_nginx is not running! It should be so this is a problem.
warn: Try running `lando logs -s appserver_nginx` to help locate the problem!
debug: Error
    at module.exports.sh.Promise.try.then (C:\snapshot\lando\build\cli\lib\shell.js:0:0)
From previous event:
    at Shell.sh (C:\snapshot\lando\build\cli\lib\shell.js:0:0)
    at Object.exports.dc (C:\snapshot\lando\build\cli\lib\bootstrap.js:0:0)
    at compose (C:\snapshot\lando\build\cli\lib\bootstrap.js:0:0)
    at exports.run.Promise.each.docker.isRunning.then.then (C:\snapshot\lando\build\cli\lib\router.js:0:0)
From previous event:
    at exports.run.Promise.each.datum (C:\snapshot\lando\build\cli\lib\router.js:0:0)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
From previous event:
    at Object.exports.run (C:\snapshot\lando\build\cli\lib\router.js:0:0)
    at run (C:\snapshot\lando\build\cli\lib\engine.js:0:0)
    at exports.eventWrapper.daemon.up.then.then (C:\snapshot\lando\build\cli\lib\router.js:0:0)
From previous event:
    at Object.exports.eventWrapper (C:\snapshot\lando\build\cli\lib\router.js:0:0)
    at Engine.module.exports.constructor.engineCmd (C:\snapshot\lando\build\cli\lib\engine.js:0:0)
    at Engine.run (C:\snapshot\lando\build\cli\lib\engine.js:0:0)
    at module.exports.app.events.on.app.events.on.lando.Promise.each.service (C:\snapshot\lando\build\cli\plugins\lando-core\app.js:0:0)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
From previous event:
    at AsyncEvents.module.exports.app.events.on.app.events.on (C:\snapshot\lando\build\cli\plugins\lando-core\app.js:0:0)
    at AsyncEvents.handle (C:\snapshot\lando\build\cli\lib\events.js:0:0)
    at emit.Promise.each.fn (C:\snapshot\lando\build\cli\lib\events.js:0:0)
From previous event:
    at AsyncEvents.emit (C:\snapshot\lando\build\cli\lib\events.js:0:0)
    at module.exports.start.initAndReport.then.then.then (C:\snapshot\lando\build\cli\lib\app.js:0:0)
From previous event:
    at App.start (C:\snapshot\lando\build\cli\lib\app.js:0:0)
    at Object.exports.appToggle (C:\snapshot\lando\build\cli\plugins\lando-core\lib\utils.js:0:0)
    at Object.run (C:\snapshot\lando\build\cli\plugins\lando-core\tasks\start.js:0:0)
    at module.exports.parseToYargs.checkForUpdates.then.lando.bootstrap.then.lando.events.emit.then.then.then.then.then (C:\snapshot\lando\build\cli\lib\cli.js:0:0)
From previous event:
    at module.exports.parseToYargs.checkForUpdates.then.lando.bootstrap.then.lando (C:\snapshot\lando\build\cli\lib\cli.js:0:0)
From previous event:
    at module.exports.parseToYargs.checkForUpdates.then (C:\snapshot\lando\build\cli\lib\cli.js:0:0)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
From previous event:
    at Object.handler (C:\snapshot\lando\build\cli\lib\cli.js:0:0)
    at Object.runCommand (C:\snapshot\lando\build\cli\node_modules\yargs\lib\command.js:238:44)
    at Object.parseArgs [as _parseArgs] (C:\snapshot\lando\build\cli\node_modules\yargs\yargs.js:1063:30)
    at Function.get [as argv] (C:\snapshot\lando\build\cli\node_modules\yargs\yargs.js:1004:21)
    at Cli.run (C:\snapshot\lando\build\cli\lib\cli.js:0:0)
    at Object.<anonymous> (C:\snapshot\lando\build\cli\bin\lando.js:0:0)
    at Module._compile (pkg/prelude/bootstrap.js:1252:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:711:10)
    at Module.load (internal/modules/cjs/loader.js:610:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:549:12)
    at Function.Module._load (internal/modules/cjs/loader.js:541:3)
    at Function.Module.runMain (pkg/prelude/bootstrap.js:1307:12)
    at startup (internal/bootstrap/node.js:274:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:608:3)
debug: Emitting event pre-engine-up
debug: Event pre-engine-up has 0 listeners
debug: Engine is up.
debug: Emitting event post-engine-up
debug: Event post-engine-up has 0 listeners
debug: Emitting event pre-engine-run
debug: Event pre-engine-run has 0 listeners
verbose: Running ["C:\\Program Files\\Docker\\Docker\\resources\\bin\\docker-compose.exe","--project-name","merceredu","--file","C:\\Users\\Will Hawthorne\\.lando\\compose\\merceredu\\globals-0.yml","--file","C:\\Users\\Will Hawthorne\\.lando\\compose\\merceredu\\appserver-0.yml","--file","C:\\Users\\Will Hawthorne\\.lando\\compose\\merceredu\\appserver-1.yml","--file","C:\\Users\\Will Hawthorne\\.lando\\compose\\merceredu\\appserver-2.yml","--file","C:\\Users\\Will Hawthorne\\.lando\\compose\\merceredu\\appserver-3.yml","--file","C:\\Users\\Will Hawthorne\\.lando\\compose\\merceredu\\appserver-4.yml","--file","C:\\Users\\Will Hawthorne\\.lando\\compose\\merceredu\\appserver-5.yml","--file","C:\\Users\\Will Hawthorne\\.lando\\compose\\merceredu\\appserver-6.yml","--file","C:\\Users\\Will Hawthorne\\.lando\\compose\\merceredu\\appserver-7.yml","--file","C:\\Users\\Will Hawthorne\\.lando\\compose\\merceredu\\appserver-8.yml","--file","C:\\Users\\Will Hawthorne\\.lando\\compose\\merceredu\\database-0.yml","--file","C:\\Users\\Will Hawthorne\\.lando\\compose\\merceredu\\database-1.yml","--file","C:\\Users\\Will Hawthorne\\.lando\\compose\\merceredu\\database-2.yml","--file","C:\\Users\\Will Hawthorne\\.lando\\compose\\merceredu\\database-3.yml","--file","C:\\Users\\Will Hawthorne\\.lando\\compose\\merceredu\\database-4.yml","--file","C:\\Users\\Will Hawthorne\\.lando\\compose\\merceredu\\database-5.yml","--file","C:\\Users\\Will Hawthorne\\.lando\\compose\\merceredu\\proxy-0.yml","exec","--detach","--env","PHP_MEMORY_LIMIT=-1","--user","root","appserver","/bin/sh","-c","/helpers/refresh-certs.sh > /cert-log.txt"] in C:\Users\Will Hawthorne\Documents\Projects\Mercer\dev-mercer-edu\lando with options {"mode":"attach","detached":false}
debug: With stdio={"stdio":"inherit"}, mode=attach, detached=false
verbose: C:\Program Files\Docker\Docker\resources\bin\docker-compose.exe,--project-name,merceredu,--file,C:\Users\Will Hawthorne\.lando\compose\merceredu\globals-0.yml,--file,C:\Users\Will Hawthorne\.lando\compose\merceredu\appserver-0.yml,--file,C:\Users\Will Hawthorne\.lando\compose\merceredu\appserver-1.yml,--file,C:\Users\Will Hawthorne\.lando\compose\merceredu\appserver-2.yml,--file,C:\Users\Will Hawthorne\.lando\compose\merceredu\appserver-3.yml,--file,C:\Users\Will Hawthorne\.lando\compose\merceredu\appserver-4.yml,--file,C:\Users\Will Hawthorne\.lando\compose\merceredu\appserver-5.yml,--file,C:\Users\Will Hawthorne\.lando\compose\merceredu\appserver-6.yml,--file,C:\Users\Will Hawthorne\.lando\compose\merceredu\appserver-7.yml,--file,C:\Users\Will Hawthorne\.lando\compose\merceredu\appserver-8.yml,--file,C:\Users\Will Hawthorne\.lando\compose\merceredu\database-0.yml,--file,C:\Users\Will Hawthorne\.lando\compose\merceredu\database-1.yml,--file,C:\Users\Will Hawthorne\.lando\compose\merceredu\database-2.yml,--file,C:\Users\Will Hawthorne\.lando\compose\merceredu\database-3.yml,--file,C:\Users\Will Hawthorne\.lando\compose\merceredu\database-4.yml,--file,C:\Users\Will Hawthorne\.lando\compose\merceredu\database-5.yml,--file,C:\Users\Will Hawthorne\.lando\compose\merceredu\proxy-0.yml,exec,--detach,--env,PHP_MEMORY_LIMIT=-1,--user,root,appserver,/bin/sh,-c,/helpers/refresh-certs.sh > /cert-log.txt finished with code 0
debug: Emitting event post-engine-run
debug: Event post-engine-run has 0 listeners
debug: Emitting event pre-engine-up
debug: Event pre-engine-up has 0 listeners
debug: Emitting event post-engine-up
debug: Event post-engine-up has 0 listeners
debug: Emitting event pre-engine-run
debug: Event pre-engine-run has 0 listeners
verbose: Running ["C:\\Program Files\\Docker\\Docker\\resources\\bin\\docker-compose.exe","--project-name","merceredu","--file","C:\\Users\\Will Hawthorne\\.lando\\compose\\merceredu\\globals-0.yml","--file","C:\\Users\\Will Hawthorne\\.lando\\compose\\merceredu\\appserver-0.yml","--file","C:\\Users\\Will Hawthorne\\.lando\\compose\\merceredu\\appserver-1.yml","--file","C:\\Users\\Will Hawthorne\\.lando\\compose\\merceredu\\appserver-2.yml","--file","C:\\Users\\Will Hawthorne\\.lando\\compose\\merceredu\\appserver-3.yml","--file","C:\\Users\\Will Hawthorne\\.lando\\compose\\merceredu\\appserver-4.yml","--file","C:\\Users\\Will Hawthorne\\.lando\\compose\\merceredu\\appserver-5.yml","--file","C:\\Users\\Will Hawthorne\\.lando\\compose\\merceredu\\appserver-6.yml","--file","C:\\Users\\Will Hawthorne\\.lando\\compose\\merceredu\\appserver-7.yml","--file","C:\\Users\\Will Hawthorne\\.lando\\compose\\merceredu\\appserver-8.yml","--file","C:\\Users\\Will Hawthorne\\.lando\\compose\\merceredu\\database-0.yml","--file","C:\\Users\\Will Hawthorne\\.lando\\compose\\merceredu\\database-1.yml","--file","C:\\Users\\Will Hawthorne\\.lando\\compose\\merceredu\\database-2.yml","--file","C:\\Users\\Will Hawthorne\\.lando\\compose\\merceredu\\database-3.yml","--file","C:\\Users\\Will Hawthorne\\.lando\\compose\\merceredu\\database-4.yml","--file","C:\\Users\\Will Hawthorne\\.lando\\compose\\merceredu\\database-5.yml","--file","C:\\Users\\Will Hawthorne\\.lando\\compose\\merceredu\\proxy-0.yml","exec","--detach","--env","PHP_MEMORY_LIMIT=-1","--user","root","database","/bin/sh","-c","/helpers/refresh-certs.sh > /cert-log.txt"] in C:\Users\Will Hawthorne\Documents\Projects\Mercer\dev-mercer-edu\lando with options {"mode":"attach","detached":false}
debug: With stdio={"stdio":"inherit"}, mode=attach, detached=false
verbose: C:\Program Files\Docker\Docker\resources\bin\docker-compose.exe,--project-name,merceredu,--file,C:\Users\Will Hawthorne\.lando\compose\merceredu\globals-0.yml,--file,C:\Users\Will Hawthorne\.lando\compose\merceredu\appserver-0.yml,--file,C:\Users\Will Hawthorne\.lando\compose\merceredu\appserver-1.yml,--file,C:\Users\Will Hawthorne\.lando\compose\merceredu\appserver-2.yml,--file,C:\Users\Will Hawthorne\.lando\compose\merceredu\appserver-3.yml,--file,C:\Users\Will Hawthorne\.lando\compose\merceredu\appserver-4.yml,--file,C:\Users\Will Hawthorne\.lando\compose\merceredu\appserver-5.yml,--file,C:\Users\Will Hawthorne\.lando\compose\merceredu\appserver-6.yml,--file,C:\Users\Will Hawthorne\.lando\compose\merceredu\appserver-7.yml,--file,C:\Users\Will Hawthorne\.lando\compose\merceredu\appserver-8.yml,--file,C:\Users\Will Hawthorne\.lando\compose\merceredu\database-0.yml,--file,C:\Users\Will Hawthorne\.lando\compose\merceredu\database-1.yml,--file,C:\Users\Will Hawthorne\.lando\compose\merceredu\database-2.yml,--file,C:\Users\Will Hawthorne\.lando\compose\merceredu\database-3.yml,--file,C:\Users\Will Hawthorne\.lando\compose\merceredu\database-4.yml,--file,C:\Users\Will Hawthorne\.lando\compose\merceredu\database-5.yml,--file,C:\Users\Will Hawthorne\.lando\compose\merceredu\proxy-0.yml,exec,--detach,--env,PHP_MEMORY_LIMIT=-1,--user,root,database,/bin/sh,-c,/helpers/refresh-certs.sh > /cert-log.txt finished with code 0
debug: Emitting event post-engine-run
debug: Event post-engine-run has 0 listeners

BOOMSHAKALAKA!!!
```

**Tell us generally about your bug**

merceredu.lndo.site shows a 404, seems like server isn't running properly. The "info: Checking to see if http://merceredu.lndo.site is ready." lines repeat themselves a lot (never working) before getting to the part I have pasted above.

I am just getting lando setup for a pantheon install. Have been through a number of installs/reinstalls. This is the farthest I've been able to get without finding something that helps me get further.

**Comment by pirog** [comment]
The problem line is 

```
cannot parse template: read /opt/bitnami/extra/nginx/templates/default.conf.tpl: is a directory
```

We don't currently support the `wordpress_network` framework so  *im guessing* that might be why this happens

**Comment by wilirius** [comment]
OK - so that makes sense. I also would expect there might be a slightly different configuration for a subdomain multisite vs subdirectory multisite install. I'll try it out directly.

**Comment by dustinleblanc** [comment]
@pirog wordpress_network is for using Wordpress as a site-network. It is a royal PITA. Check out the Pantheon docs on it: https://pantheon.io/docs/guides/multisite/

In regards to changes to the actual infrastructure on Pantheon's end, I don't recall if anything changes other than the number of tooling annoyances a site network introduces. On our end, it would break lando pull and lando push at least, as well as anything that depended on wp-cli commands. Site Networks require adding some flags to WP-CLI commands to work properly.

All that said, I think we *should* support site networks to ensure Pantheon parity for Pantheon customers who use them.

**Comment by pirog** [comment]
@dustinleblanc got it. Sounds SUPER FUN

Agreed we *should* support it but not sure how or when we can do that right now.

In the meantime maybe we should just throw a warning/error if someone is using this framework with a link here? Ill ask JoshK about this next time i talk to him.

**Comment by dustinleblanc** [comment]
I just asked my secret favorite Pantheon ninja too

**Comment by pirog** [comment]
UNSTALE!

**Comment by pirog** [comment]
unstale

**Comment by kmkelmor** [comment]
Greetings -- I too am having the same difficulty. Would love to see wordpress_network supported. I'm at a loss for creating a local site without it.

**Comment by theblockmonkey** [comment]
Has there been any update on this?

**Comment by jpkarvonen** [comment]
My team and I are having this issue as well! Any progress?
