### ISSUE TITLE
TypeError: Assignment to constant variable.

### ISSUE THREAD

**Issue by runofthemill** [lando/lando#1431]
macOS Mojave 10.14.3 18D109

```
➜ lando version
v3.0.0-rc.8

➜ node --version
v10.14.1

➜ docker --version
Docker version 18.09.1, build 4c52b90

➜ docker-machine --version
docker-machine version 0.16.1, build cce350d7

➜ docker-compose --version
docker-compose version 1.23.2, build 1110ad01

# Docker Desktop info.json
{
  "id": "FC3AE122-551A-4298-85B8-55CFF56E14A3",
  "date": "2019-02-08 00:42:55.424874352 +0000 UTC",
  "os": "macOS 10.14.3",
  "os_label": "osx/10.14.x",
  "app_version": "2.0.0.2",
  "app_channel": "stable",
  "engine_version": "18.09.1",
  "compose_version": "1.23.2",
  "kubernetes_version": "v1.10.11",
  "credhelper_version": "0.6.0",
  "notary_version": "0.6.1",
  "vpnkit_version": "83b469a79cfa7a272057dc41d3d97e7d1f16e4a5",
  "hyperkit_version": "v0.20180403-17-g3e954c"
}
```

**Tell us about your `.lando.yml`**
N/A

**Tell us about the command you were running**
Any command, aside from `lando version`, returns this error:

```
➜ lando info
error: TypeError: Assignment to constant variable.
    at Object.exports.toLandoContainer (/snapshot/lando/build/cli/lib/utils.js:0:0)
    at module.exports.list.listContainers.filter.filter.map.container (/snapshot/lando/build/cli/lib/docker.js:0:0)
From previous event:
    at Landerode.list (/snapshot/lando/build/cli/lib/docker.js:0:0)
    at module.exports.list.engineCmd.options (/snapshot/lando/build/cli/lib/engine.js:0:0)
    at exports.eventWrapper.daemon.up.then.then (/snapshot/lando/build/cli/lib/router.js:0:0)
From previous event:
    at Object.exports.eventWrapper (/snapshot/lando/build/cli/lib/router.js:0:0)
    at Engine.module.exports.constructor.engineCmd (/snapshot/lando/build/cli/lib/engine.js:0:0)
    at Engine.list (/snapshot/lando/build/cli/lib/engine.js:0:0)
    at AsyncEvents.module.exports._.forEach.app.events.on (/snapshot/lando/build/cli/plugins/lando-core/app.js:0:0)
    at AsyncEvents.handle (/snapshot/lando/build/cli/lib/events.js:0:0)
    at emit.Promise.each.fn (/snapshot/lando/build/cli/lib/events.js:0:0)
    at runCallback (timers.js:696:18)
From previous event:
    at AsyncEvents.emit (/snapshot/lando/build/cli/lib/events.js:0:0)
    at module.exports.init.loadPlugins.then.then.then (/snapshot/lando/build/cli/lib/app.js:0:0)
From previous event:
    at App.init (/snapshot/lando/build/cli/lib/app.js:0:0)
    at Object.run (/snapshot/lando/build/cli/plugins/lando-core/tasks/info.js:0:0)
    at module.exports.parseToYargs.checkForUpdates.then.lando.bootstrap.then.lando.events.emit.then.then.then.then.then (/snapshot/lando/build/cli/lib/cli.js:0:0)
From previous event:
    at module.exports.parseToYargs.checkForUpdates.then.lando.bootstrap.then.lando (/snapshot/lando/build/cli/lib/cli.js:0:0)
From previous event:
    at module.exports.parseToYargs.checkForUpdates.then (/snapshot/lando/build/cli/lib/cli.js:0:0)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
From previous event:
    at Object.handler (/snapshot/lando/build/cli/lib/cli.js:0:0)
    at Object.runCommand (/snapshot/lando/build/cli/node_modules/yargs/lib/command.js:238:44)
    at Object.parseArgs [as _parseArgs] (/snapshot/lando/build/cli/node_modules/yargs/yargs.js:1063:30)
    at Function.get [as argv] (/snapshot/lando/build/cli/node_modules/yargs/yargs.js:1004:21)
    at Cli.run (/snapshot/lando/build/cli/lib/cli.js:0:0)
    at Object.<anonymous> (/snapshot/lando/build/cli/bin/lando.js:0:0)
    at Module._compile (pkg/prelude/bootstrap.js:1252:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:711:10)
    at Module.load (internal/modules/cjs/loader.js:610:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:549:12)
    at Function.Module._load (internal/modules/cjs/loader.js:541:3)
    at Function.Module.runMain (pkg/prelude/bootstrap.js:1307:12)
    at startup (internal/bootstrap/node.js:274:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:608:3)
```
Different commands have marginally different stack traces, but overall the same:

```
➜ lando start
Unhandled rejection TypeError: Assignment to constant variable.
    at Object.exports.toLandoContainer (/snapshot/lando/build/cli/lib/utils.js:0:0)
    at module.exports.list.listContainers.filter.filter.map.container (/snapshot/lando/build/cli/lib/docker.js:0:0)
From previous event:
    at Landerode.list (/snapshot/lando/build/cli/lib/docker.js:0:0)
    at module.exports.list.engineCmd.options (/snapshot/lando/build/cli/lib/engine.js:0:0)
    at exports.eventWrapper.daemon.up.then.then (/snapshot/lando/build/cli/lib/router.js:0:0)
From previous event:
    at Object.exports.eventWrapper (/snapshot/lando/build/cli/lib/router.js:0:0)
    at Engine.module.exports.constructor.engineCmd (/snapshot/lando/build/cli/lib/engine.js:0:0)
    at Engine.list (/snapshot/lando/build/cli/lib/engine.js:0:0)
    at AsyncEvents.module.exports._.forEach.app.events.on (/snapshot/lando/build/cli/plugins/lando-core/app.js:0:0)
    at AsyncEvents.handle (/snapshot/lando/build/cli/lib/events.js:0:0)
    at emit.Promise.each.fn (/snapshot/lando/build/cli/lib/events.js:0:0)
    at runCallback (timers.js:696:18)
From previous event:
    at AsyncEvents.emit (/snapshot/lando/build/cli/lib/events.js:0:0)
    at module.exports.init.loadPlugins.then.then.then (/snapshot/lando/build/cli/lib/app.js:0:0)
From previous event:
    at App.init (/snapshot/lando/build/cli/lib/app.js:0:0)
    at lando.bootstrap.then.lando (/snapshot/lando/build/cli/bin/lando.js:0:0)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
From previous event:
    at Object.<anonymous> (/snapshot/lando/build/cli/bin/lando.js:0:0)
    at Module._compile (pkg/prelude/bootstrap.js:1252:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:711:10)
    at Module.load (internal/modules/cjs/loader.js:610:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:549:12)
    at Function.Module._load (internal/modules/cjs/loader.js:541:3)
    at Function.Module.runMain (pkg/prelude/bootstrap.js:1307:12)
    at startup (internal/bootstrap/node.js:274:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:608:3)
```

Diff of two commands:
<img width="1723" alt="screen shot 2019-02-07 at 5 07 14 pm" src="https://user-images.githubusercontent.com/8418440/52453136-daa5cb80-2afa-11e9-9d2d-9fc43e331723.png">

**Tell us about the error you got**

Rerun the command that produced your error in `debug` mode. Note that `debug` mode is run like this `lando command -vvv`. Paste in the error and the `~100` lines that proceeded it.

```bash
➜ lando list -vvv
info: Bootstraping...
info: config bootstrap beginning...
debug: Emitting event pre-bootstrap-config
debug: Event pre-bootstrap-config has 0 listeners
verbose: Loading event pre-engine-start priority 2
verbose: Plugin lando-core loaded from /snapshot/lando/build/cli/plugins/lando-core/index.js
debug: Plugin lando-core has {"config":{"appEnv":{"COLUMNS":256,"LANDO":"ON","LANDO_WEBROOT_USER":"www-data","LANDO_WEBROOT_GROUP":"www-data","LANDO_WEBROOT_UID":"33","LANDO_WEBROOT_GID":"33","TERM":"xterm","LANDO_HOST_UID":"501","LANDO_HOST_GID":"20","LANDO_HOST_USER":"jeremy","LANDO_CA_CERT":"/lando/certs/lndo.site.pem","LANDO_CA_KEY":"/lando/certs/lndo.site.key","LANDO_CONFIG_DIR":"/Users/jeremy/.lando","LANDO_DOMAIN":"lndo.site","LANDO_HOST_HOME":"/Users/jeremy","LANDO_HOST_OS":"darwin","LANDO_HOST_IP":"host.docker.internal","LANDO_MOUNT":"/app"},"appLabels":{"io.lando.container":"TRUE","io.lando.id":"7250393431112564e2cc3a30a2557e3b82e5530b"},"gid":"20","uid":"501","username":"jeremy","caCert":"/Users/jeremy/.lando/certs/lndo.site.pem","caDomain":"lndo.site","caKey":"/Users/jeremy/.lando/certs/lndo.site.key","caProject":"landocasetupkenobi38ahsoka7250393431112564e2cc3a30a2557e3b82e5530b"}}
verbose: Plugin lando-events loaded from /snapshot/lando/build/cli/plugins/lando-events/index.js
debug: Plugin lando-events has undefined
verbose: Loading event pre-engine-start priority 1
verbose: Loading event pre-engine-start priority 2
verbose: Plugin lando-networking loaded from /snapshot/lando/build/cli/plugins/lando-networking/index.js
debug: Plugin lando-networking has {"config":{"networkBridge":"lando_bridge_network"}}
verbose: Plugin lando-pantheon loaded from /snapshot/lando/build/cli/plugins/lando-pantheon/index.js
debug: Plugin lando-pantheon has undefined
verbose: Loading event post-bootstrap-config priority 5
verbose: Plugin lando-proxy loaded from /snapshot/lando/build/cli/plugins/lando-proxy/index.js
debug: Plugin lando-proxy has {"config":{"proxy":"ON","proxyCert":"/certs/cert.crt","proxyKey":"/certs/cert.key","proxyName":"landoproxyhyperion5000gandalfedition","proxyDash":"58087","proxyCache":"proxyCache","proxyHttpPort":"80","proxyHttpsPort":"443","proxyHttpFallbacks":["8000","8080","8888","8008"],"proxyHttpsFallbacks":["444","4433","4444","4443"],"proxyDomain":"lndo.site","proxyIp":"127.0.0.1"}}
verbose: Plugin lando-recipes loaded from /snapshot/lando/build/cli/plugins/lando-recipes/index.js
debug: Plugin lando-recipes has undefined
verbose: Plugin lando-services loaded from /snapshot/lando/build/cli/plugins/lando-services/index.js
debug: Plugin lando-services has undefined
verbose: Plugin lando-test loaded from /snapshot/lando/build/cli/plugins/lando-test/index.js
debug: Plugin lando-test has {"plugin-test":true}
verbose: Plugin lando-tooling loaded from /snapshot/lando/build/cli/plugins/lando-tooling/index.js
debug: Plugin lando-tooling has undefined
debug: Emitting event post-bootstrap-config
debug: Event post-bootstrap-config has 1 listeners
info: config bootstrap completed.
info: tasks bootstrap beginning...
debug: Emitting event pre-bootstrap-tasks
debug: Event pre-bootstrap-tasks has 0 listeners
debug: Autoloaded task config
debug: Autoloaded task destroy
debug: Autoloaded task info
debug: Autoloaded task list
debug: Autoloaded task logs
debug: Autoloaded task poweroff
debug: Autoloaded task rebuild
debug: Autoloaded task restart
debug: Autoloaded task share
debug: Autoloaded task start
debug: Autoloaded task stop
debug: Autoloaded task version
debug: Autoloaded task init
debug: Autoloaded task ssh
debug: Emitting event post-bootstrap-tasks
debug: Event post-bootstrap-tasks has 0 listeners
info: tasks bootstrap completed.
info: engine bootstrap beginning...
debug: Emitting event pre-bootstrap-engine
debug: Event pre-bootstrap-engine has 0 listeners
debug: Automoved scripts from /snapshot/lando/build/cli/plugins/lando-core/scripts to /Users/jeremy/.lando/scripts and setting 755
debug: Automoved scripts from /snapshot/lando/build/cli/plugins/lando-pantheon/scripts to /Users/jeremy/.lando/scripts and setting 755
debug: Automoved scripts from /snapshot/lando/build/cli/plugins/lando-recipes/scripts to /Users/jeremy/.lando/scripts and setting 755
debug: Automoved scripts from /snapshot/lando/build/cli/plugins/lando-services/scripts to /Users/jeremy/.lando/scripts and setting 755
debug: Emitting event post-bootstrap-engine
debug: Event post-bootstrap-engine has 0 listeners
info: engine bootstrap completed.
info: Bootstrap completed.
debug: Emitting event cli-answers
debug: Event cli-answers has 0 listeners
debug: Emitting event cli-list-answers
debug: Event cli-list-answers has 0 listeners
debug: Emitting event cli-run
debug: Event cli-run has 0 listeners
debug: Emitting event cli-list-run
debug: Event cli-list-run has 0 listeners
debug: Emitting event pre-engine-up
debug: Event pre-engine-up has 0 listeners
debug: Engine is up.
debug: Emitting event post-engine-up
debug: Event post-engine-up has 0 listeners
debug: Emitting event pre-engine-list
debug: Event pre-engine-list has 0 listeners
error: TypeError: Assignment to constant variable.
    at Object.exports.toLandoContainer (/snapshot/lando/build/cli/lib/utils.js:0:0)
    at module.exports.list.listContainers.filter.filter.map.container (/snapshot/lando/build/cli/lib/docker.js:0:0)
From previous event:
    at Landerode.list (/snapshot/lando/build/cli/lib/docker.js:0:0)
    at module.exports.list.engineCmd.options (/snapshot/lando/build/cli/lib/engine.js:0:0)
    at exports.eventWrapper.daemon.up.then.then (/snapshot/lando/build/cli/lib/router.js:0:0)
From previous event:
    at Object.exports.eventWrapper (/snapshot/lando/build/cli/lib/router.js:0:0)
    at Engine.module.exports.constructor.engineCmd (/snapshot/lando/build/cli/lib/engine.js:0:0)
    at Engine.list (/snapshot/lando/build/cli/lib/engine.js:0:0)
    at Object.run (/snapshot/lando/build/cli/plugins/lando-core/tasks/list.js:0:0)
    at module.exports.parseToYargs.checkForUpdates.then.lando.bootstrap.then.lando.events.emit.then.then.then.then.then (/snapshot/lando/build/cli/lib/cli.js:0:0)
From previous event:
    at module.exports.parseToYargs.checkForUpdates.then.lando.bootstrap.then.lando (/snapshot/lando/build/cli/lib/cli.js:0:0)
From previous event:
    at module.exports.parseToYargs.checkForUpdates.then (/snapshot/lando/build/cli/lib/cli.js:0:0)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
From previous event:
    at Object.handler (/snapshot/lando/build/cli/lib/cli.js:0:0)
    at Object.runCommand (/snapshot/lando/build/cli/node_modules/yargs/lib/command.js:238:44)
    at Object.parseArgs [as _parseArgs] (/snapshot/lando/build/cli/node_modules/yargs/yargs.js:1063:30)
    at Function.get [as argv] (/snapshot/lando/build/cli/node_modules/yargs/yargs.js:1004:21)
    at Cli.run (/snapshot/lando/build/cli/lib/cli.js:0:0)
    at Object.<anonymous> (/snapshot/lando/build/cli/bin/lando.js:0:0)
    at Module._compile (pkg/prelude/bootstrap.js:1252:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:711:10)
    at Module.load (internal/modules/cjs/loader.js:610:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:549:12)
    at Function.Module._load (internal/modules/cjs/loader.js:541:3)
    at Function.Module.runMain (pkg/prelude/bootstrap.js:1307:12)
    at startup (internal/bootstrap/node.js:274:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:608:3)
debug: Logging metrics data {"context":"local","devMode":false,"nodeVersion":"v10.4.1","mode":"cli","os":{"type":"Darwin","platform":"darwin","release":"18.2.0","arch":"x64"},"product":"lando","version":"3.0.0-rc.8","message":"Assignment to constant variable.","stack":"TypeError: Assignment to constant variable.\n    at Object.exports.toLandoContainer (/snapshot/lando/build/cli/lib/utils.js:0:0)\n    at module.exports.list.listContainers.filter.filter.map.container (/snapshot/lando/build/cli/lib/docker.js:0:0)\nFrom previous event:\n    at Landerode.list (/snapshot/lando/build/cli/lib/docker.js:0:0)\n    at module.exports.list.engineCmd.options (/snapshot/lando/build/cli/lib/engine.js:0:0)\n    at exports.eventWrapper.daemon.up.then.then (/snapshot/lando/build/cli/lib/router.js:0:0)\nFrom previous event:\n    at Object.exports.eventWrapper (/snapshot/lando/build/cli/lib/router.js:0:0)\n    at Engine.module.exports.constructor.engineCmd (/snapshot/lando/build/cli/lib/engine.js:0:0)\n    at Engine.list (/snapshot/lando/build/cli/lib/engine.js:0:0)\n    at Object.run (/snapshot/lando/build/cli/plugins/lando-core/tasks/list.js:0:0)\n    at module.exports.parseToYargs.checkForUpdates.then.lando.bootstrap.then.lando.events.emit.then.then.then.then.then (/snapshot/lando/build/cli/lib/cli.js:0:0)\nFrom previous event:\n    at module.exports.parseToYargs.checkForUpdates.then.lando.bootstrap.then.lando (/snapshot/lando/build/cli/lib/cli.js:0:0)\nFrom previous event:\n    at module.exports.parseToYargs.checkForUpdates.then (/snapshot/lando/build/cli/lib/cli.js:0:0)\n    at runCallback (timers.js:696:18)\n    at tryOnImmediate (timers.js:667:5)\n    at processImmediate (timers.js:649:5)\nFrom previous event:\n    at Object.handler (/snapshot/lando/build/cli/lib/cli.js:0:0)\n    at Object.runCommand (/snapshot/lando/build/cli/node_modules/yargs/lib/command.js:238:44)\n    at Object.parseArgs [as _parseArgs] (/snapshot/lando/build/cli/node_modules/yargs/yargs.js:1063:30)\n    at Function.get [as argv] (/snapshot/lando/build/cli/node_modules/yargs/yargs.js:1004:21)\n    at Cli.run (/snapshot/lando/build/cli/lib/cli.js:0:0)\n    at Object.<anonymous> (/snapshot/lando/build/cli/bin/lando.js:0:0)\n    at Module._compile (pkg/prelude/bootstrap.js:1252:22)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:711:10)\n    at Module.load (internal/modules/cjs/loader.js:610:32)\n    at tryModuleLoad (internal/modules/cjs/loader.js:549:12)\n    at Function.Module._load (internal/modules/cjs/loader.js:541:3)\n    at Function.Module.runMain (pkg/prelude/bootstrap.js:1307:12)\n    at startup (internal/bootstrap/node.js:274:19)\n    at bootstrapNodeJSCore (internal/bootstrap/node.js:608:3)","action":"error","created":"2019-02-08T00:54:47.955Z"}
```

**Tell us generally about your bug**

Lando worked fine last time I used it (1-2 months ago?) on macOS 10.13.x. Docker works fine with other apps. If I create a new directory, I can run `init` fine, but nothing beyond that:

```
~/Projects
➜ mkdir lando2

~/Projects
➜ cd lando2

~/Projects/lando2
➜ lando init \
  --source remote \
  --remote-url https://wordpress.org/latest.tar.gz \
  --recipe wordpress \
  --webroot wordpress \
  --name my-first-wordpress-app
Creating landoinitmyfirstwordpressapp_init_1 ... done
Detected that https://wordpress.org/latest.tar.gz is a tar archive
Downloading https://wordpress.org/latest.tar.gz...
Downloaded to /tmp/source/latest.tar.gz
wordpress/
wordpress/xmlrpc.php
wordpress/wp-blog-header.php
wordpress/readme.html
wordpress/wp-signup.php
wordpress/index.php
wordpress/wp-cron.php
wordpress/wp-config-sample.php
wordpress/wp-login.php
wordpress/wp-settings.php
wordpress/license.txt
wordpress/wp-content/
[...] # I removed list of WP files to keep this shorter
wordpress/wp-comments-post.php
Extracted /tmp/source/latest.tar.gz to /app
Killing landoinitmyfirstwordpressapp_init_1 ... done
Removing landoinitmyfirstwordpressapp_init_1 ... done
Going to remove landoinitmyfirstwordpressapp_init_1

NOW WE'RE COOKING WITH FIRE!!!
Your app has been initialized!

Go to the directory where your app was initialized and run `lando start` to get rolling.
Check the LOCATION printed below if you are unsure where to go.

Oh... and here are some vitals:

 NAME      my-first-wordpress-app
 LOCATION  /Users/jeremy/Projects/lando2
 RECIPE    wordpress
 DOCS      https://docs.devwithlando.io/tutorials/wordpress.html

~/Projects/lando2
➜ pwd
/Users/jeremy/Projects/lando2

~/Projects/lando2
➜ lando start
Let's get this party started! Starting app..
error: TypeError: Assignment to constant variable.
    at Object.exports.toLandoContainer (/snapshot/lando/build/cli/lib/utils.js:0:0)
    at module.exports.list.listContainers.filter.filter.map.container (/snapshot/lando/build/cli/lib/docker.js:0:0)
From previous event:
    at Landerode.list (/snapshot/lando/build/cli/lib/docker.js:0:0)
    at module.exports.list.engineCmd.options (/snapshot/lando/build/cli/lib/engine.js:0:0)
    at exports.eventWrapper.daemon.up.then.then (/snapshot/lando/build/cli/lib/router.js:0:0)
From previous event:
    at Object.exports.eventWrapper (/snapshot/lando/build/cli/lib/router.js:0:0)
    at Engine.module.exports.constructor.engineCmd (/snapshot/lando/build/cli/lib/engine.js:0:0)
    at Engine.list (/snapshot/lando/build/cli/lib/engine.js:0:0)
    at AsyncEvents.module.exports._.forEach.app.events.on (/snapshot/lando/build/cli/plugins/lando-core/app.js:0:0)
    at AsyncEvents.handle (/snapshot/lando/build/cli/lib/events.js:0:0)
    at emit.Promise.each.fn (/snapshot/lando/build/cli/lib/events.js:0:0)
    at runCallback (timers.js:696:18)
From previous event:
    at AsyncEvents.emit (/snapshot/lando/build/cli/lib/events.js:0:0)
    at module.exports.init.loadPlugins.then.then.then (/snapshot/lando/build/cli/lib/app.js:0:0)
From previous event:
    at App.init (/snapshot/lando/build/cli/lib/app.js:0:0)
    at initAndReport (/snapshot/lando/build/cli/lib/app.js:0:0)
    at App.start (/snapshot/lando/build/cli/lib/app.js:0:0)
    at Object.exports.appToggle (/snapshot/lando/build/cli/plugins/lando-core/lib/utils.js:0:0)
    at Object.run (/snapshot/lando/build/cli/plugins/lando-core/tasks/start.js:0:0)
    at module.exports.parseToYargs.checkForUpdates.then.lando.bootstrap.then.lando.events.emit.then.then.then.then.then (/snapshot/lando/build/cli/lib/cli.js:0:0)
From previous event:
    at module.exports.parseToYargs.checkForUpdates.then.lando.bootstrap.then.lando (/snapshot/lando/build/cli/lib/cli.js:0:0)
From previous event:
    at module.exports.parseToYargs.checkForUpdates.then (/snapshot/lando/build/cli/lib/cli.js:0:0)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
From previous event:
    at Object.handler (/snapshot/lando/build/cli/lib/cli.js:0:0)
    at Object.runCommand (/snapshot/lando/build/cli/node_modules/yargs/lib/command.js:238:44)
    at Object.parseArgs [as _parseArgs] (/snapshot/lando/build/cli/node_modules/yargs/yargs.js:1063:30)
    at Function.get [as argv] (/snapshot/lando/build/cli/node_modules/yargs/yargs.js:1004:21)
    at Cli.run (/snapshot/lando/build/cli/lib/cli.js:0:0)
    at Object.<anonymous> (/snapshot/lando/build/cli/bin/lando.js:0:0)
    at Module._compile (pkg/prelude/bootstrap.js:1252:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:711:10)
    at Module.load (internal/modules/cjs/loader.js:610:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:549:12)
    at Function.Module._load (internal/modules/cjs/loader.js:541:3)
    at Function.Module.runMain (pkg/prelude/bootstrap.js:1307:12)
    at startup (internal/bootstrap/node.js:274:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:608:3)
```

**Comment by pirog** [comment]
@runofthemill nice, thanks for this.

looks like some legacy code we dont need anymore, this should only trip if youve got a non-lando container running that you spun up using `docker-compose run`.

**Comment by runofthemill** [comment]
Yep, I've got a separate project that uses `docker`/`docker-compose`.

Thank you for the quick response & fix! I'll leave this open until 0aa6c57 gets merged, or feel free to close this before then if you'd prefer.

**Comment by pirog** [comment]
@runofthemill thanks for the report!

**Comment by pirog** [comment]
ok this should be fixed in https://github.com/lando/lando/releases/tag/v3.0.0-rc.9
