### ISSUE TITLE
Following documentation leads to TypeError: Invalid version: 7.0

### ISSUE THREAD

**Issue by f1rf1n** [lando/lando#1525]
**Link to the page that needs to be updated or changed.**
https://docs.devwithlando.io/tutorials/drupal8.html#choosing-a-php-version
https://docs.devwithlando.io/tutorials/drupal7.html#choosing-a-php-version
These are the only two pages in the recipes section that use a .0 version for PHP. I did not check other requirements or settings.

**Describe the change you'd like**
In the choosing php version section the following is incorrect `php: 7.0` This leads to the version being interepreted as 7, leading to many errors in lando (see below). It should be `php: '7.0'`
 PRs coming up.

```lando restart
Stopping your app... just so we can start it up again ¯\_(ツ)_/¯
error: TypeError: Invalid Version: 7.0
    at new SemVer (/snapshot/lando/build/cli/node_modules/semver/semver.js:312:11)
    at compare (/snapshot/lando/build/cli/node_modules/semver/semver.js:585:10)
    at Function.gt (/snapshot/lando/build/cli/node_modules/semver/semver.js:614:10)
    at new LandoPhp (/snapshot/lando/build/cli/plugins/lando-services/services/php/builder.js:0:0)
    at module.exports.app.events.on._.forEach.service (/snapshot/lando/build/cli/plugins/lando-services/app.js:0:0)
    at arrayEach (/snapshot/lando/build/cli/node_modules/lodash/lodash.js:516:11)
    at Function.forEach (/snapshot/lando/build/cli/node_modules/lodash/lodash.js:9344:14)
    at AsyncEvents.module.exports.app.events.on (/snapshot/lando/build/cli/plugins/lando-services/app.js:0:0)
    at AsyncEvents.handle (/snapshot/lando/build/cli/lib/events.js:0:0)
    at emit.Promise.each.fn (/snapshot/lando/build/cli/lib/events.js:0:0)
From previous event:
    at AsyncEvents.emit (/snapshot/lando/build/cli/lib/events.js:0:0)
    at module.exports.init.loadPlugins.then (/snapshot/lando/build/cli/lib/app.js:0:0)
From previous event:
    at App.init (/snapshot/lando/build/cli/lib/app.js:0:0)
    at initAndReport (/snapshot/lando/build/cli/lib/app.js:0:0)
    at App.stop (/snapshot/lando/build/cli/lib/app.js:0:0)
    at App.restart (/snapshot/lando/build/cli/lib/app.js:0:0)
    at Object.exports.appToggle (/snapshot/lando/build/cli/plugins/lando-core/lib/utils.js:0:0)
    at Object.run (/snapshot/lando/build/cli/plugins/lando-core/tasks/restart.js:0:0)
    at module.exports.parseToYargs.checkForUpdates.then.lando.bootstrap.then.lando.events.emit.then.then.then.then.then (/snapshot/lando/build/cli/lib/cli.js:0:0)
From previous event:
    at module.exports.parseToYargs.checkForUpdates.then.lando.bootstrap.then.lando (/snapshot/lando/build/cli/lib/cli.js:0:0)
From previous event:
    at module.exports.parseToYargs.checkForUpdates.then (/snapshot/lando/build/cli/lib/cli.js:0:0)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
From previous event:
    at Object.handler (/snapshot/lando/build/cli/lib/cli.js:0:0)
    at Object.runCommand (/snapshot/lando/build/cli/node_modules/yargs/lib/command.js:238:44)
    at Object.parseArgs [as _parseArgs] (/snapshot/lando/build/cli/node_modules/yargs/yargs.js:1063:30)
    at Function.get [as argv] (/snapshot/lando/build/cli/node_modules/yargs/yargs.js:1004:21)
    at Cli.run (/snapshot/lando/build/cli/lib/cli.js:0:0)
    at Object.<anonymous> (/snapshot/lando/build/cli/bin/lando.js:0:0)
    at Module._compile (pkg/prelude/bootstrap.js:1252:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:711:10)
    at Module.load (internal/modules/cjs/loader.js:610:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:549:12)
    at Function.Module._load (internal/modules/cjs/loader.js:541:3)
    at Function.Module.runMain (pkg/prelude/bootstrap.js:1307:12)
    at startup (internal/bootstrap/node.js:274:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:608:3)
```

**Comment by f1rf1n** [comment]
PR here #https://github.com/lando/lando/pull/1527

**Comment by pirog** [comment]
@f1rf1n thanks! 

would be good to get all version strings wrapped in quotes eventually but this is a great start on the most important ones

**Comment by pirog** [comment]
Should be fixed in the main docz now
