### ISSUE TITLE
custom is not a supported recipe type 

### ISSUE THREAD

**Issue by danielrojas08** [lando/lando#1539]
I have a problem that started out weird and now my lando won't work. I have had this problem for about a month now and i am getting frustrated. The issue is:
warn: custom is not a supported recipe type.
Unhandled rejection TypeError: Cannot read property 'builder' of undefined
    at Factory.get (/snapshot/lando/build/cli/lib/factory.js:0:0)
    at AsyncEvents.module.exports.app.events.on (/snapshot/lando/build/cli/plugins/lando-recipes/app.js:0:0)
    at AsyncEvents.handle (/snapshot/lando/build/cli/lib/events.js:0:0)
    at emit.Promise.each.fn (/snapshot/lando/build/cli/lib/events.js:0:0)
    at runCallback (timers.js:696:18)
From previous event:
    at AsyncEvents.emit (/snapshot/lando/build/cli/lib/events.js:0:0)
    at module.exports.init.loadPlugins.then (/snapshot/lando/build/cli/lib/app.js:0:0)
From previous event:
    at App.init (/snapshot/lando/build/cli/lib/app.js:0:0)
    at lando.bootstrap.then.lando (/snapshot/lando/build/cli/bin/lando.js:0:0)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
From previous event:
    at Object.<anonymous> (/snapshot/lando/build/cli/bin/lando.js:0:0)
    at Module._compile (pkg/prelude/bootstrap.js:1252:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:711:10)
    at Module.load (internal/modules/cjs/loader.js:610:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:549:12)
    at Function.Module._load (internal/modules/cjs/loader.js:541:3)
    at Function.Module.runMain (pkg/prelude/bootstrap.js:1307:12)
    at startup (internal/bootstrap/node.js:274:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:608:3)

**Comment by danielrojas08** [comment]
Can you help. If you can please help, and if you have the same problem reach out so we can help fix it.

**Comment by pirog** [comment]
@danielrojas08 custom isn’t and never has been a valid recipe type so this is the expected behavior. 

Just remove the line and consult the docs in the future for a list of valid recipes

**Comment by danielrojas08** [comment]
Can you be more specific about removing the line? Thanks

**Comment by pirog** [comment]
I honestly don’t think that I can. Literally remove the line where you set
the recipe as custom.

**Comment by danielrojas08** [comment]
I did not set the line at custom. Whenever I start lando it gives me the problem to be more specific. Any ideas?

**Comment by osopolar** [comment]
@danielrojas08 may you please provide the details you where asked for on creating new issues. You can find them here https://github.com/lando/lando/issues/new?labels=bug&template=bug_report.md, especially:

> **Tell us about your `.lando.yml`**
>
> Paste in the contents of your `.lando.yml` this is **SUPER HELPFUL** for us.
