### ISSUE TITLE
[UnexpectedValueException]   Could not parse version constraint composer: Invalid version string "composer"

### ISSUE THREAD

**Issue by RishiKulshreshtha** [lando/lando#1540]
**Tell us about your setup**
```text
v3.0.0-rc.13 on macOS Mojave (version 10.14)
```

**Tell us about your `.lando.yml`**

```yaml
name: myapp
recipe: drupal8
config:
  php: '7.2'
  via: nginx
  webroot: docroot
  drush: composer
  xdebug: true
proxy:
  pma:
    - pma.myapp.lndo.site
  mailhog:
    - mail.myapp.lndo.site
services:
  pma:
    type: phpmyadmin
    hosts:
      - database
  mailhog:
    type: mailhog
    hogfrom:
      - appserver
  node:
    type: node:10
    globals:
      gulp-cli: "latest"
      bower: "latest"
      webpack: "latest"
      npm: "latest"
  database:
    type: mysql:5.7
    creds:
      user: myapp
      password: myapp
      database: myapp
tooling:
  gulp:
    service: node
  yarn:
    service: node
  npm:
    service: node
  node:
    service: node
```

**Tell us about the command you were running**
```text
lando start
```

**Tell us about the error you got**

```text
Changed current directory to /var/www/.composer
    1/11: http://repo.packagist.org/p/provider-latest$185a60df8c2ab63daea2cb739a8ccd8fd4bfa91c4c55e8ef7420941e8ef728ed.json
    2/11: http://repo.packagist.org/p/provider-2018-04$c4ef508c033f673f81c433b8cf021b447a42f3a44ff8d050d023cd81ff1bc945.json
    3/11: http://repo.packagist.org/p/provider-2013$126533e2be8c87d8baf81084e46a0410f6b04ce008a7283a64351c64baa8f7b0.json
    4/11: http://repo.packagist.org/p/provider-2018$e0560e97c11667890303ac3531f407629c291a854a6bc472fd4c16dd67a77df8.json
    5/11: http://repo.packagist.org/p/provider-2018-07$15bcdf2b9cd377d38f28c04654124917c197f1396b81a150cc331a895409a25f.json
    6/11: http://repo.packagist.org/p/provider-2018-10$4ca61e9d95416263c0656a01f4192ee123ba5d005aeb9444d51103c4d69a0b91.json
    7/11: http://repo.packagist.org/p/provider-2014$d3603b134ff3cd8fd14a7df21dd46fdb4df266608b9ed507d5e8c9dc33f77bfc.json
    8/11: http://repo.packagist.org/p/provider-2016$fd206ed45ba893681fa7bb04329204a9ad36b0454ad5bfc8f252bc4c408f55d8.json
    9/11: http://repo.packagist.org/p/provider-2019-01$752987847c12a5894ae73a571891e6e7631b9f971de3df9f0e94424c386ce033.json
    10/11:  http://repo.packagist.org/p/provider-2015$16424ce6d9a59df7ed3162bf19ba62ab106ad5ea455e61953b22f9c4d5638add.json
    11/11:  http://repo.packagist.org/p/provider-2017$ecd04f451cc84e1d893b9a78b4601dbf2491ad9c7432035715860717e5ccf15d.json
    Finished: success: 11, skipped: 0, failure: 0, total: 11


  [UnexpectedValueException]
  Could not parse version constraint composer: Invalid version string "composer"


require [--dev] [--prefer-source] [--prefer-dist] [--no-progress] [--no-suggest] [--no-update] [--no-scripts] [--update-no-dev] [--update-with-dependencies] [--update-with-all-dependencies] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--] [<packages>]...

error: Looks like one of your build steps failed! with Error
    at module.exports.sh.Promise.try.then (/snapshot/lando/build/cli/lib/shell.js:0:0)
From previous event:
    at Shell.sh (/snapshot/lando/build/cli/lib/shell.js:0:0)
    at Object.exports.dc (/snapshot/lando/build/cli/lib/bootstrap.js:0:0)
    at compose (/snapshot/lando/build/cli/lib/bootstrap.js:0:0)
    at exports.run.Promise.each.docker.isRunning.then.then (/snapshot/lando/build/cli/lib/router.js:0:0)
From previous event:
    at exports.run.Promise.each.datum (/snapshot/lando/build/cli/lib/router.js:0:0)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
From previous event:
    at Object.exports.run (/snapshot/lando/build/cli/lib/router.js:0:0)
    at run (/snapshot/lando/build/cli/lib/engine.js:0:0)
    at exports.eventWrapper.daemon.up.then.then (/snapshot/lando/build/cli/lib/router.js:0:0)
From previous event:
    at Object.exports.eventWrapper (/snapshot/lando/build/cli/lib/router.js:0:0)
    at Engine.module.exports.constructor.engineCmd (/snapshot/lando/build/cli/lib/engine.js:0:0)
    at Engine.run (/snapshot/lando/build/cli/lib/engine.js:0:0)
    at Object.exports.runBuild (/snapshot/lando/build/cli/plugins/lando-services/lib/utils.js:0:0)
    at AsyncEvents.module.exports.app.events.on.app.events.on (/snapshot/lando/build/cli/plugins/lando-services/app.js:0:0)
    at AsyncEvents.handle (/snapshot/lando/build/cli/lib/events.js:0:0)
    at emit.Promise.each.fn (/snapshot/lando/build/cli/lib/events.js:0:0)
From previous event:
    at AsyncEvents.emit (/snapshot/lando/build/cli/lib/events.js:0:0)
    at module.exports.start.initAndReport.then (/snapshot/lando/build/cli/lib/app.js:0:0)
From previous event:
    at App.start (/snapshot/lando/build/cli/lib/app.js:0:0)
    at module.exports.rebuild.events.emit.then.then.then.then (/snapshot/lando/build/cli/lib/app.js:0:0)
From previous event:
    at App.rebuild (/snapshot/lando/build/cli/lib/app.js:0:0)
    at Object.exports.appToggle (/snapshot/lando/build/cli/plugins/lando-core/lib/utils.js:0:0)
    at Object.run (/snapshot/lando/build/cli/plugins/lando-core/tasks/rebuild.js:0:0)
    at module.exports.parseToYargs.checkForUpdates.then.lando.bootstrap.then.lando.events.emit.then.then.then.then.then (/snapshot/lando/build/cli/lib/cli.js:0:0)
From previous event:
    at module.exports.parseToYargs.checkForUpdates.then.lando.bootstrap.then.lando (/snapshot/lando/build/cli/lib/cli.js:0:0)
From previous event:
    at module.exports.parseToYargs.checkForUpdates.then (/snapshot/lando/build/cli/lib/cli.js:0:0)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
From previous event:
    at Object.handler (/snapshot/lando/build/cli/lib/cli.js:0:0)
    at Object.runCommand (/snapshot/lando/build/cli/node_modules/yargs/lib/command.js:238:44)
    at Object.parseArgs [as _parseArgs] (/snapshot/lando/build/cli/node_modules/yargs/yargs.js:1063:30)
    at Function.get [as argv] (/snapshot/lando/build/cli/node_modules/yargs/yargs.js:1004:21)
    at Cli.run (/snapshot/lando/build/cli/lib/cli.js:0:0)
    at Object.<anonymous> (/snapshot/lando/build/cli/bin/lando.js:0:0)
    at Module._compile (pkg/prelude/bootstrap.js:1252:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:711:10)
    at Module.load (internal/modules/cjs/loader.js:610:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:549:12)
    at Function.Module._load (internal/modules/cjs/loader.js:541:3)
    at Function.Module.runMain (pkg/prelude/bootstrap.js:1307:12)
    at startup (internal/bootstrap/node.js:274:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:608:3)
warn: This **MAY** prevent your app from working
warn: Check for errors above, fix them, and try again

```

**Tell us generally about your bug**

I've tried `lando start` & `lando rebuild` as well, in both the cases I'm receiving the same error.

**Comment by pirog** [comment]
@RishiKulshreshtha check out the docs, `composer` is no longer a supported value. You likely just need to remove the entire `drush` line from your recipe `config`

**Comment by RishiKulshreshtha** [comment]
Thanks, @pirog. After making the required changes in my `.lando.yml` it worked as expected!
