### ISSUE TITLE
Lando init produces: Error at module.exports.sh.Promise.try.then

### ISSUE THREAD

**Issue by aaronlsilber** [lando/lando#1570]
**Tell us about your setup**

What is your lando version and operating system?
Lando v3.0.0-rc.14 on Windows 10 Professional 1803

**Tell us about your `.lando.yml`**

Breaks on lando init -> Pantheon

**Tell us about the command you were running**

Paste in a series of commands that caused the bug.

E:\Projects\lifetreerx.com\pantheon [master ≡ +0 ~1 -0 !]> lando init
? From where should we get your app's codebase? pantheon
? Select a Pantheon account aaron@myemail.com
? Which site? mysite

**Tell us about the error you got**

```bash
debug: Emitting event pre-engine-up
debug: Event pre-engine-up has 0 listeners
debug: Engine is up.
debug: Emitting event post-engine-up
debug: Event post-engine-up has 0 listeners
debug: Emitting event pre-engine-stop
debug: Event pre-engine-stop has 0 listeners
verbose: Running ["C:\\Program Files\\Docker\\Docker\\resources\\bin\\docker-compose.exe","--project-name","landoinitlifetreerx","--file","C:\\Users\\aaron.silber\\.lando\\init\\lifetreerx\\init-0.yml","--file","C:\\Users\\aaron.silber\\.lando\\init\\lifetreerx\\init-1.yml","--file","C:\\Users\\aaron.silber\\.lando\\init\\lifetreerx\\init-2.yml","kill"] in E:\Projects\lifetreerx.com\pantheon with options {"mode":"collect","detached":false}
debug: With stdio={"stdio":"inherit"}, mode=collect, detached=false, cwd=E:\Projects\lifetreerx.com\pantheon
Killing landoinitlifetreerx_init_1 ... done
verbose: C:\Program Files\Docker\Docker\resources\bin\docker-compose.exe,--project-name,landoinitlifetreerx,--file,C:\Users\aaron.silber\.lando\init\lifetreerx\init-0.yml,--file,C:\Users\aaron.silber\.lando\init\lifetreerx\init-1.yml,--file,C:\Users\aaron.silber\.lando\init\lifetreerx\init-2.yml,kill finished with code 0
debug: Emitting event post-engine-stop
debug: Event post-engine-stop has 0 listeners
debug: Emitting event pre-engine-up
debug: Event pre-engine-up has 0 listeners
debug: Emitting event post-engine-up
debug: Event post-engine-up has 0 listeners
debug: Emitting event pre-engine-destroy
debug: Event pre-engine-destroy has 0 listeners
verbose: Running ["C:\\Program Files\\Docker\\Docker\\resources\\bin\\docker-compose.exe","--project-name","landoinitlifetreerx","--file","C:\\Users\\aaron.silber\\.lando\\init\\lifetreerx\\init-0.yml","--file","C:\\Users\\aaron.silber\\.lando\\init\\lifetreerx\\init-1.yml","--file","C:\\Users\\aaron.silber\\.lando\\init\\lifetreerx\\init-2.yml","down","--remove-orphans","-v"] in E:\Projects\lifetreerx.com\pantheon with options {"mode":"collect","detached":false}
debug: With stdio={"stdio":"inherit"}, mode=collect, detached=false, cwd=E:\Projects\lifetreerx.com\pantheon
Removing landoinitlifetreerx_init_1 ... done
Removing network landoinitlifetreerx_default
Removing volume landoinitlifetreerx_data_init
Removing volume landoinitlifetreerx_home_init
verbose: C:\Program Files\Docker\Docker\resources\bin\docker-compose.exe,--project-name,landoinitlifetreerx,--file,C:\Users\aaron.silber\.lando\init\lifetreerx\init-0.yml,--file,C:\Users\aaron.silber\.lando\init\lifetreerx\init-1.yml,--file,C:\Users\aaron.silber\.lando\init\lifetreerx\init-2.yml,down,--remove-orphans,-v finished with code 0
debug: Emitting event post-engine-destroy
debug: Event post-engine-destroy has 0 listeners
error: Error
    at module.exports.sh.Promise.try.then (C:\snapshot\lando\build\cli\lib\shell.js:0:0)
From previous event:
    at Shell.sh (C:\snapshot\lando\build\cli\lib\shell.js:0:0)
    at Object.exports.dc (C:\snapshot\lando\build\cli\lib\bootstrap.js:0:0)
    at compose (C:\snapshot\lando\build\cli\lib\bootstrap.js:0:0)
    at exports.run.Promise.each.docker.isRunning.then.then (C:\snapshot\lando\build\cli\lib\router.js:0:0)
From previous event:
    at exports.run.Promise.each.datum (C:\snapshot\lando\build\cli\lib\router.js:0:0)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
From previous event:
    at Object.exports.run (C:\snapshot\lando\build\cli\lib\router.js:0:0)
    at run (C:\snapshot\lando\build\cli\lib\engine.js:0:0)
    at exports.eventWrapper.daemon.up.then.then (C:\snapshot\lando\build\cli\lib\router.js:0:0)
From previous event:
    at Object.exports.eventWrapper (C:\snapshot\lando\build\cli\lib\router.js:0:0)
    at Engine.module.exports.constructor.engineCmd (C:\snapshot\lando\build\cli\lib\engine.js:0:0)
    at Engine.run (C:\snapshot\lando\build\cli\lib\engine.js:0:0)
    at Object.exports.run (C:\snapshot\lando\build\cli\plugins\lando-recipes\lib\build.js:0:0)
    at lando.Promise.each.step (C:\snapshot\lando\build\cli\plugins\lando-recipes\tasks\init.js:0:0)
From previous event:
    at runBuild (C:\snapshot\lando\build\cli\plugins\lando-recipes\tasks\init.js:0:0)
    at module.exports.lando.run.lando.events.emit.then (C:\snapshot\lando\build\cli\plugins\lando-recipes\tasks\init.js:0:0)
From previous event:
    at Object.run (C:\snapshot\lando\build\cli\plugins\lando-recipes\tasks\init.js:0:0)
    at module.exports.parseToYargs.checkForUpdates.then.lando.bootstrap.then.lando.events.emit.then.then.then.then.then (C:\snapshot\lando\build\cli\lib\cli.js:0:0)
From previous event:
    at module.exports.parseToYargs.checkForUpdates.then.lando.bootstrap.then.lando (C:\snapshot\lando\build\cli\lib\cli.js:0:0)
From previous event:
    at module.exports.parseToYargs.checkForUpdates.then (C:\snapshot\lando\build\cli\lib\cli.js:0:0)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
From previous event:
    at Object.handler (C:\snapshot\lando\build\cli\lib\cli.js:0:0)
    at Object.runCommand (C:\snapshot\lando\build\cli\node_modules\yargs\lib\command.js:238:44)
    at Object.parseArgs [as _parseArgs] (C:\snapshot\lando\build\cli\node_modules\yargs\yargs.js:1063:30)
    at Function.get [as argv] (C:\snapshot\lando\build\cli\node_modules\yargs\yargs.js:1004:21)
    at Cli.run (C:\snapshot\lando\build\cli\lib\cli.js:0:0)
    at Object.<anonymous> (C:\snapshot\lando\build\cli\bin\lando.js:0:0)
    at Module._compile (pkg/prelude/bootstrap.js:1254:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:711:10)
    at Module.load (internal/modules/cjs/loader.js:610:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:549:12)
    at Function.Module._load (internal/modules/cjs/loader.js:541:3)
    at Function.Module.runMain (pkg/prelude/bootstrap.js:1309:12)
    at startup (internal/bootstrap/node.js:274:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:608:3)
```

**Tell us generally about your bug**

```bash
1. I upgraded to newest Lando release, uninstalling Docker and Lando before installing the new stack.
2. When I run lando init and try to spin up an environment, it explodes.

I should note that If I spin up a plain Drupal 8 recipe, I'm able to get through.
```

Pretty lost here. 😭

**Comment by aaronlsilber** [comment]
I revisited this issue today and decided to look at my Docker config. I bumped up my memory allocation, restarted Docker, removed my .git directory, removed the existing .lando file, ran `lando destroy` for good measure and ran through `lando init` with a pantheon recipe again. It worked!
