### ISSUE TITLE
[v3.0.0-rc.14] `composer` and `drush` suddenly fail suddenly

### ISSUE THREAD

**Issue by Clindbergh** [lando/lando#1583]
`.lando.yml`:

```yml
name: you-are-beautiful-too
recipe: drupal8
config:
  webroot: docroot
  xdebug: false
  drush: ^9
  conf:
    php: php.ini
```

`composer` and `drush` commands such as `composer require require drupal/devel:2.0.0` and ` lando drush dis webprofiler` suddenly fail _silently_. A `lando rebuild --clear` or `lando destory` and `lando start` don't help. 

Running the composer and drush commands with `-vvvv` reveal the error (after some waiting):

```
debug: Logging metrics data {"context":"local","devMode":false,"nodeVersion":"v10.4.1","mode":"cli","os":{"type":"Windows_NT","platform":"win32","release":"10.0.17134","arch":"x64"},"product":"lando","version":"3.0.0-rc.13","message":"","stack":"Error
at module.exports.sh.Promise.try.then (C:\snapshot\lando\build\cli\lib\shell.js:0:0)
From previous event:
at Shell.sh (C:\snapshot\lando\build\cli\lib\shell.js:0:0)
at Object.exports.dockerExec (C:\snapshot\lando\build\cli\plugins\lando-tooling\lib\utils.js:0:0)
at module.exports.lando.Promise.try.then.then.map.each.runner (C:\snapshot\lando\build\cli\plugins\lando-tooling\lib\build.js:0:0)
at runCallback (timers.js:696:18)
at tryOnImmediate (timers.js:667:5)
at processImmediate (timers.js:649:5)
From previous event:
at Object.run (C:\snapshot\lando\build\cli\plugins\lando-tooling\lib\build.js:0:0)
at engineRunner (C:\snapshot\lando\build\cli\lib\bootstrap.js:0:0)
at module.exports.parseToYargs.checkForUpdates.then.lando.bootstrap.then.lando.events.emit.then.then.then.then.then (C:\snapshot\lando\build\cli\lib\cli.js:0:0)
From previous event:
at module.exports.parseToYargs.checkForUpdates.then.lando.bootstrap.then.lando (C:\snapshot\lando\build\cli\lib\cli.js:0:0)
From previous event:
at module.exports.parseToYargs.checkForUpdates.then (C:\snapshot\lando\build\cli\lib\cli.js:0:0)
at runCallback (timers.js:696:18)
at tryOnImmediate (timers.js:667:5)
at processImmediate (timers.js:649:5)
From previous event:
at Object.handler (C:\snapshot\lando\build\cli\lib\cli.js:0:0)
at Object.runCommand (C:\snapshot\lando\build\cli\
ode_modules\yargs\lib\command.js:238:44)
at Object.parseArgs [as _parseArgs] (C:\snapshot\lando\build\cli\
ode_modules\yargs\yargs.js:1063:30)
at Function.get [as argv] (C:\snapshot\lando\build\cli\
ode_modules\yargs\yargs.js:1004:21)
at Cli.run (C:\snapshot\lando\build\cli\lib\cli.js:0:0)
at Object.<anonymous> (C:\snapshot\lando\build\cli\bin\lando.js:0:0)
at Module._compile (pkg/prelude/bootstrap.js:1252:22)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:711:10)
at Module.load (internal/modules/cjs/loader.js:610:32)
at tryModuleLoad (internal/modules/cjs/loader.js:549:12)
at Function.Module._load (internal/modules/cjs/loader.js:541:3)
at Function.Module.runMain (pkg/prelude/bootstrap.js:1307:12)
at startup (internal/bootstrap/node.js:274:19)
at bootstrapNodeJSCore (internal/bootstrap/node.js:608:3)","action":"error","created":"2019-04-11T23:23:54.840Z"}

```

Error is consistently the same, even after computer and docker restart.

**Comment by Clindbergh** [comment]
I reinstalled lando and I'm now unable to reproduce the issue. Thus I'm closing this. If you experience the same errors, feel free to reopen.
