### ISSUE TITLE
Lando <command> Error

### ISSUE THREAD

**Issue by jdprime** [lando/lando#1597]
Before you submit an issue make sure you have [downloaded](https://github.com/lando/lando/releases) the latest version of Lando and checked to see if the latest version resolves your issue!

**If you submit an issue against an older release of Lando there is a good chance your issues will not be addressed.** This is especially true if that issue is for 3.0.0-rc.1 or lower.

Please complete the following steps.

**The more steps you complete the more likely we are to address your issue!**

1.  Update to the [latest version](https://github.com/lando/lando/releases) of Lando and make sure the issue isn't fixed already.
2.  Please review the [current list of issues](https://github.com/lando/lando/issues) to make sure you are not submitting a duplicate.

The **FASTEST** way for us to verify and resolve your bug if for you to [write a functional test that breaks](https://docs.devwithlando.io/dev/testing.html#functional-tests), submit it as a pull request and link to that pull request here.

If you are not sure how to do that then please complete as much of the below section as possible

**Tell us about your setup**

What is your lando version and operating system? **(note that the older your version the less likely we are to reply)**
Lando Version: v3.0.0-rc.15
Operating System: OSX 10.14.4

**Tell us about your `.lando.yml`**

Paste in the contents of your `.lando.yml` this is **SUPER HELPFUL** for us.

```name: firstapp
recipe: lamp
config:
  webroot: web
  php: 7.3
  database:
    mysql: 8.0
  xdebug: true
 
```

It is also helpful to include other relevant config files. For example, include `pantheon.yml` for a `pantheon` recipe if applicable. Include `php.ini` or `mysql.cnf` if you are overriding our defualt config.

**Tell us about the command you were running**
tried running lando build
lando start
lando version
etc...

Paste in a series of commands that caused the bug.
```bash
lando start
```

**Tell us about the error you got**

Rerun the command that produced your error in `debug` mode. Note that `debug` mode is run like this `lando command -vvv`. Paste in the error and the `~100` lines that proceeded it.

*Example:*

```bash
Unhandled rejection TypeError: undefined is not a function
    at getConfigDefaults (/snapshot/lando/build/cli/plugins/lando-recipes/types/laemp/builder.js:0:0)
    at new LandoLaemp (/snapshot/lando/build/cli/plugins/lando-recipes/types/laemp/builder.js:0:0)
    at new LandoLamp (/snapshot/lando/build/cli/plugins/lando-recipes/lib/utils.js:0:0)
    at AsyncEvents.module.exports.app.events.on (/snapshot/lando/build/cli/plugins/lando-recipes/app.js:0:0)
    at AsyncEvents.handle (/snapshot/lando/build/cli/lib/events.js:0:0)
    at emit.Promise.each.fn (/snapshot/lando/build/cli/lib/events.js:0:0)
From previous event:
    at AsyncEvents.emit (/snapshot/lando/build/cli/lib/events.js:0:0)
    at module.exports.init.loadPlugins.then (/snapshot/lando/build/cli/lib/app.js:0:0)
From previous event:
    at App.init (/snapshot/lando/build/cli/lib/app.js:0:0)
    at lando.bootstrap.then.lando (/snapshot/lando/build/cli/bin/lando.js:0:0)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
From previous event:
    at Object.<anonymous> (/snapshot/lando/build/cli/bin/lando.js:0:0)
    at Module._compile (pkg/prelude/bootstrap.js:1254:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:711:10)
    at Module.load (internal/modules/cjs/loader.js:610:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:549:12)
    at Function.Module._load (internal/modules/cjs/loader.js:541:3)
    at Function.Module.runMain (pkg/prelude/bootstrap.js:1309:12)
    at startup (internal/bootstrap/node.js:274:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:608:3)
```

**Tell us generally about your bug**
New computer, just installed latest version of lando, needed to start a brand new project and I got as far as lando init (set up my .lando.yml file) and I cannot move forward from there.

Please detail the steps we can take to replicate this bug. Be as detailed as possible.

```bash
Try running any lando command (?)
```

**Tell us more**
The error seems to be like they are JS errors. Could it be that I have  node's version v11.14.0 and npm -v 6.7.0 (?) - I know

Could better documentation have prevented this issue? if so what should we change?
Does this bug prevent you from using lando?
Yes, I can't do anything.

**Comment by pirog** [comment]
@jdprime probably not a huge surprise that i can't replicate this and FWIW I have not seen anything like this reported elsewhere so nothing immediately helpful comes to mind.

For more background if you are installing lando via the package on github then we also package in the node version to prevent node version mismatches. If you are installing lando from source then its going to rely on your system version. More details on that over here
https://docs.devwithlando.io/installation/source.html#from-source

**Comment by andy-lcm** [comment]
I hit this or a similar issue today. Seems to be due simply to an invalid `.lando.yml `- Here's one way to reproduce it. This with Lando v3.6.0:

Initial .lando.yml config:

```
name: lcmtools
recipe: mean

```
Run `lando rebuild`. Everything works, e.g. `lando info`.

Now add to config:

```
services:
  appserver:
    type: php

```

Now `lando info` produces: `ERROR ==> undefined is not a function`

In my case, the invalid config was being up via a separate shared Lando file which was getting included via `postLandoFiles` in `~/.lando/config.yml`

So, not a bug, but perhaps this situation could be detected and a more helpful error message produced?
