### ISSUE TITLE
Unable to run lando init

### ISSUE THREAD

**Issue by cainaru** [lando/lando#1598]
**Tell us about your setup**

What is your lando version and operating system? **(note that the older your version the less likely we are to reply)**

v3.0.0-rc.15 on macOS High Sierra 10.13.6

**Tell us about your `.lando.yml`**
None; was trying to run `lando init` to setup a .lando.yml

It is also helpful to include other relevant config files. For example, include `pantheon.yml` for a `pantheon` recipe if applicable. Include `php.ini` or `mysql.cnf` if you are overriding our defualt config.

**Tell us about the command you were running**

```bash
lando init
```

**Tell us about the error you got**

```bash
lando init
? From where should we get your app's codebase? github
? Enter a GitHub personal access token [hidden]
Getting your GitHub repos... this may take a moment if you have a lot
? Which repo? cainaru/d8-digital-stlawu
? What recipe do you want to use? pantheon
? Enter a Pantheon machine token [hidden]
? Which site? d8-digital-stlawu
Creating network "landoinitd8digitalstlawu_default" with the default driver
Creating volume "landoinitd8digitalstlawu_data_init" with default driver
Creating volume "landoinitd8digitalstlawu_home_init" with default driver
Pulling init (devwithlando/util:2)...
2: Pulling from devwithlando/util
bf295113f40d: Pull complete
4e9b4ea92a1d: Pull complete
Creating landoinitd8digitalstlawu_init_1 ... done
github.lando.id_rsa does not yet exist, generating one...
Generating public/private rsa key pair.
Your identification has been saved in /lando/keys/github.lando.id_rsa.
Your public key has been saved in /lando/keys/github.lando.id_rsa.pub.
The key fingerprint is:
[REDACTED]
The key's randomart image is:
+---[RSA 2048]----+
|      .          |
|   . . .         |
|. o +   .        |
| + . . .         |
|  .   . S o      |
|   o   + = .     |
|  o . . . o E    |
| .....   . o .   |
| .==        +.   |
+-----------------+
Killing landoinitd8digitalstlawu_init_1 ... done
Starting landoinitd8digitalstlawu_init_1 ... done
Scanning /lando/keys for keys...
Scanning /user/.ssh for keys...
Scanning /var/www/.ssh for keys...
Using the following keys: 
Killing landoinitd8digitalstlawu_init_1 ... done
Starting landoinitd8digitalstlawu_init_1 ... done
Detected that git@github.com:cainaru/d8-digital-stlawu.git is a tar archive
Downloading git@github.com:cainaru/d8-digital-stlawu.git...
curl: (22) The requested URL returned error: 404 Not Found
Killing landoinitd8digitalstlawu_init_1 ... done
Removing landoinitd8digitalstlawu_init_1 ... done
Removing network landoinitd8digitalstlawu_default
Removing volume landoinitd8digitalstlawu_data_init
Removing volume landoinitd8digitalstlawu_home_init
error: Error
    at module.exports.sh.Promise.try.then (/snapshot/lando/build/cli/lib/shell.js:0:0)
From previous event:
    at Shell.sh (/snapshot/lando/build/cli/lib/shell.js:0:0)
    at Object.exports.dc (/snapshot/lando/build/cli/lib/bootstrap.js:0:0)
    at compose (/snapshot/lando/build/cli/lib/bootstrap.js:0:0)
    at exports.run.Promise.each.docker.isRunning.then.then (/snapshot/lando/build/cli/lib/router.js:0:0)
From previous event:
    at exports.run.Promise.each.datum (/snapshot/lando/build/cli/lib/router.js:0:0)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
From previous event:
    at Object.exports.run (/snapshot/lando/build/cli/lib/router.js:0:0)
    at run (/snapshot/lando/build/cli/lib/engine.js:0:0)
    at exports.eventWrapper.daemon.up.then.then (/snapshot/lando/build/cli/lib/router.js:0:0)
From previous event:
    at Object.exports.eventWrapper (/snapshot/lando/build/cli/lib/router.js:0:0)
    at Engine.module.exports.constructor.engineCmd (/snapshot/lando/build/cli/lib/engine.js:0:0)
    at Engine.run (/snapshot/lando/build/cli/lib/engine.js:0:0)
    at Object.exports.run (/snapshot/lando/build/cli/plugins/lando-recipes/lib/build.js:0:0)
    at lando.Promise.each.step (/snapshot/lando/build/cli/plugins/lando-recipes/tasks/init.js:0:0)
From previous event:
    at runBuild (/snapshot/lando/build/cli/plugins/lando-recipes/tasks/init.js:0:0)
    at module.exports.lando.run.lando.events.emit.then (/snapshot/lando/build/cli/plugins/lando-recipes/tasks/init.js:0:0)
From previous event:
    at Object.run (/snapshot/lando/build/cli/plugins/lando-recipes/tasks/init.js:0:0)
    at module.exports.parseToYargs.checkForUpdates.then.lando.bootstrap.then.lando.events.emit.then.then.then.then.then (/snapshot/lando/build/cli/lib/cli.js:0:0)
From previous event:
    at module.exports.parseToYargs.checkForUpdates.then.lando.bootstrap.then.lando (/snapshot/lando/build/cli/lib/cli.js:0:0)
From previous event:
    at module.exports.parseToYargs.checkForUpdates.then (/snapshot/lando/build/cli/lib/cli.js:0:0)
From previous event:
    at Object.handler (/snapshot/lando/build/cli/lib/cli.js:0:0)
    at Object.runCommand (/snapshot/lando/build/cli/node_modules/yargs/lib/command.js:238:44)
    at Object.parseArgs [as _parseArgs] (/snapshot/lando/build/cli/node_modules/yargs/yargs.js:1063:30)
    at Function.get [as argv] (/snapshot/lando/build/cli/node_modules/yargs/yargs.js:1004:21)
    at Cli.run (/snapshot/lando/build/cli/lib/cli.js:0:0)
    at lando.bootstrap.then.lando (/snapshot/lando/build/cli/bin/lando.js:0:0)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
From previous event:
    at Object.<anonymous> (/snapshot/lando/build/cli/bin/lando.js:0:0)
    at Module._compile (pkg/prelude/bootstrap.js:1254:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:711:10)
    at Module.load (internal/modules/cjs/loader.js:610:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:549:12)
    at Function.Module._load (internal/modules/cjs/loader.js:541:3)
    at Function.Module.runMain (pkg/prelude/bootstrap.js:1309:12)
    at startup (internal/bootstrap/node.js:274:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:608:3)
```

Rerun the command that produced your error in `debug` mode. Note that `debug` mode is run like this `lando command -vvv`. Paste in the error and the `~100` lines that proceeded it.

```bash
Scanning /lando/keys for keys...
Scanning /user/.ssh for keys...
Scanning /var/www/.ssh for keys...
Using the following keys: 
verbose: /Applications/Docker.app/Contents/Resources/bin/docker-compose,--project-name,landoinitd8digitalstlawu,--file,/Users/ncainaru/.lando/init/d8-digital-stlawu/init-0.yml,--file,/Users/ncainaru/.lando/init/d8-digital-stlawu/init-1.yml,--file,/Users/ncainaru/.lando/init/d8-digital-stlawu/init-2.yml,exec,--env,PHP_MEMORY_LIMIT=-1,--user,root,init,/helpers/load-keys.sh finished with code 0
verbose: Running ["/Applications/Docker.app/Contents/Resources/bin/docker-compose","--project-name","landoinitd8digitalstlawu","--file","/Users/ncainaru/.lando/init/d8-digital-stlawu/init-0.yml","--file","/Users/ncainaru/.lando/init/d8-digital-stlawu/init-1.yml","--file","/Users/ncainaru/.lando/init/d8-digital-stlawu/init-2.yml","kill","init"] in /Users/ncainaru/Sites/lando/digital-initiatives/d8-digital-stlawu with options {"mode":"collect","detached":false}
debug: With stdio={"stdio":"inherit"}, mode=collect, detached=false, cwd=/Users/ncainaru/Sites/lando/digital-initiatives/d8-digital-stlawu
Killing landoinitd8digitalstlawu_init_1 ... done
verbose: /Applications/Docker.app/Contents/Resources/bin/docker-compose,--project-name,landoinitd8digitalstlawu,--file,/Users/ncainaru/.lando/init/d8-digital-stlawu/init-0.yml,--file,/Users/ncainaru/.lando/init/d8-digital-stlawu/init-1.yml,--file,/Users/ncainaru/.lando/init/d8-digital-stlawu/init-2.yml,kill,init finished with code 0
debug: Emitting event post-engine-run
debug: Event post-engine-run has 0 listeners
debug: Emitting event pre-engine-up
debug: Event pre-engine-up has 0 listeners
debug: Engine is up.
debug: Emitting event post-engine-up
debug: Event post-engine-up has 0 listeners
debug: Emitting event pre-engine-run
debug: Event pre-engine-run has 0 listeners
verbose: Running ["/Applications/Docker.app/Contents/Resources/bin/docker-compose","--project-name","landoinitd8digitalstlawu","--file","/Users/ncainaru/.lando/init/d8-digital-stlawu/init-0.yml","--file","/Users/ncainaru/.lando/init/d8-digital-stlawu/init-1.yml","--file","/Users/ncainaru/.lando/init/d8-digital-stlawu/init-2.yml","up","--detach","--no-recreate","--remove-orphans","init"] in /Users/ncainaru/Sites/lando/digital-initiatives/d8-digital-stlawu with options {"mode":"collect","detached":false}
debug: With stdio={"stdio":"inherit"}, mode=collect, detached=false, cwd=/Users/ncainaru/Sites/lando/digital-initiatives/d8-digital-stlawu
Starting landoinitd8digitalstlawu_init_1 ... done
verbose: /Applications/Docker.app/Contents/Resources/bin/docker-compose,--project-name,landoinitd8digitalstlawu,--file,/Users/ncainaru/.lando/init/d8-digital-stlawu/init-0.yml,--file,/Users/ncainaru/.lando/init/d8-digital-stlawu/init-1.yml,--file,/Users/ncainaru/.lando/init/d8-digital-stlawu/init-2.yml,up,--detach,--no-recreate,--remove-orphans,init finished with code 0
verbose: Running ["/Applications/Docker.app/Contents/Resources/bin/docker-compose","--project-name","landoinitd8digitalstlawu","--file","/Users/ncainaru/.lando/init/d8-digital-stlawu/init-0.yml","--file","/Users/ncainaru/.lando/init/d8-digital-stlawu/init-1.yml","--file","/Users/ncainaru/.lando/init/d8-digital-stlawu/init-2.yml","exec","--env","PHP_MEMORY_LIMIT=-1","--user","www-data","init","/helpers/get-remote-url.sh","git@github.com:cainaru/d8-digital-stlawu.git"] in /Users/ncainaru/Sites/lando/digital-initiatives/d8-digital-stlawu with options {"mode":"attach","detached":false}
debug: With stdio={"stdio":"inherit"}, mode=attach, detached=false, cwd=/Users/ncainaru/Sites/lando/digital-initiatives/d8-digital-stlawu
Detected that git@github.com:cainaru/d8-digital-stlawu.git is a tar archive
Downloading git@github.com:cainaru/d8-digital-stlawu.git...
curl: (22) The requested URL returned error: 404 Not Found
verbose: /Applications/Docker.app/Contents/Resources/bin/docker-compose,--project-name,landoinitd8digitalstlawu,--file,/Users/ncainaru/.lando/init/d8-digital-stlawu/init-0.yml,--file,/Users/ncainaru/.lando/init/d8-digital-stlawu/init-1.yml,--file,/Users/ncainaru/.lando/init/d8-digital-stlawu/init-2.yml,exec,--env,PHP_MEMORY_LIMIT=-1,--user,www-data,init,/helpers/get-remote-url.sh,git@github.com:cainaru/d8-digital-stlawu.git finished with code 22
debug: Emitting event pre-engine-up
debug: Event pre-engine-up has 0 listeners
debug: Emitting event post-engine-up
debug: Event post-engine-up has 0 listeners
debug: Emitting event pre-engine-stop
debug: Event pre-engine-stop has 0 listeners
verbose: Running ["/Applications/Docker.app/Contents/Resources/bin/docker-compose","--project-name","landoinitd8digitalstlawu","--file","/Users/ncainaru/.lando/init/d8-digital-stlawu/init-0.yml","--file","/Users/ncainaru/.lando/init/d8-digital-stlawu/init-1.yml","--file","/Users/ncainaru/.lando/init/d8-digital-stlawu/init-2.yml","kill"] in /Users/ncainaru/Sites/lando/digital-initiatives/d8-digital-stlawu with options {"mode":"collect","detached":false}
debug: With stdio={"stdio":"inherit"}, mode=collect, detached=false, cwd=/Users/ncainaru/Sites/lando/digital-initiatives/d8-digital-stlawu
Killing landoinitd8digitalstlawu_init_1 ... done
verbose: /Applications/Docker.app/Contents/Resources/bin/docker-compose,--project-name,landoinitd8digitalstlawu,--file,/Users/ncainaru/.lando/init/d8-digital-stlawu/init-0.yml,--file,/Users/ncainaru/.lando/init/d8-digital-stlawu/init-1.yml,--file,/Users/ncainaru/.lando/init/d8-digital-stlawu/init-2.yml,kill finished with code 0
debug: Emitting event post-engine-stop
debug: Event post-engine-stop has 0 listeners
debug: Emitting event pre-engine-up
debug: Event pre-engine-up has 0 listeners
debug: Emitting event post-engine-up
debug: Event post-engine-up has 0 listeners
debug: Emitting event pre-engine-destroy
debug: Event pre-engine-destroy has 0 listeners
verbose: Running ["/Applications/Docker.app/Contents/Resources/bin/docker-compose","--project-name","landoinitd8digitalstlawu","--file","/Users/ncainaru/.lando/init/d8-digital-stlawu/init-0.yml","--file","/Users/ncainaru/.lando/init/d8-digital-stlawu/init-1.yml","--file","/Users/ncainaru/.lando/init/d8-digital-stlawu/init-2.yml","down","--remove-orphans","-v"] in /Users/ncainaru/Sites/lando/digital-initiatives/d8-digital-stlawu with options {"mode":"collect","detached":false}
debug: With stdio={"stdio":"inherit"}, mode=collect, detached=false, cwd=/Users/ncainaru/Sites/lando/digital-initiatives/d8-digital-stlawu
Removing landoinitd8digitalstlawu_init_1 ... done
Removing network landoinitd8digitalstlawu_default
Removing volume landoinitd8digitalstlawu_data_init
Removing volume landoinitd8digitalstlawu_home_init
verbose: /Applications/Docker.app/Contents/Resources/bin/docker-compose,--project-name,landoinitd8digitalstlawu,--file,/Users/ncainaru/.lando/init/d8-digital-stlawu/init-0.yml,--file,/Users/ncainaru/.lando/init/d8-digital-stlawu/init-1.yml,--file,/Users/ncainaru/.lando/init/d8-digital-stlawu/init-2.yml,down,--remove-orphans,-v finished with code 0
debug: Emitting event post-engine-destroy
debug: Event post-engine-destroy has 0 listeners
error: Error
    at module.exports.sh.Promise.try.then (/snapshot/lando/build/cli/lib/shell.js:0:0)
From previous event:
    at Shell.sh (/snapshot/lando/build/cli/lib/shell.js:0:0)
    at Object.exports.dc (/snapshot/lando/build/cli/lib/bootstrap.js:0:0)
    at compose (/snapshot/lando/build/cli/lib/bootstrap.js:0:0)
    at exports.run.Promise.each.docker.isRunning.then.then (/snapshot/lando/build/cli/lib/router.js:0:0)
From previous event:
    at exports.run.Promise.each.datum (/snapshot/lando/build/cli/lib/router.js:0:0)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
From previous event:
    at Object.exports.run (/snapshot/lando/build/cli/lib/router.js:0:0)
    at run (/snapshot/lando/build/cli/lib/engine.js:0:0)
    at exports.eventWrapper.daemon.up.then.then (/snapshot/lando/build/cli/lib/router.js:0:0)
From previous event:
    at Object.exports.eventWrapper (/snapshot/lando/build/cli/lib/router.js:0:0)
    at Engine.module.exports.constructor.engineCmd (/snapshot/lando/build/cli/lib/engine.js:0:0)
    at Engine.run (/snapshot/lando/build/cli/lib/engine.js:0:0)
    at Object.exports.run (/snapshot/lando/build/cli/plugins/lando-recipes/lib/build.js:0:0)
    at lando.Promise.each.step (/snapshot/lando/build/cli/plugins/lando-recipes/tasks/init.js:0:0)
From previous event:
    at runBuild (/snapshot/lando/build/cli/plugins/lando-recipes/tasks/init.js:0:0)
    at module.exports.lando.run.lando.events.emit.then (/snapshot/lando/build/cli/plugins/lando-recipes/tasks/init.js:0:0)
From previous event:
    at Object.run (/snapshot/lando/build/cli/plugins/lando-recipes/tasks/init.js:0:0)
    at module.exports.parseToYargs.checkForUpdates.then.lando.bootstrap.then.lando.events.emit.then.then.then.then.then (/snapshot/lando/build/cli/lib/cli.js:0:0)
From previous event:
    at module.exports.parseToYargs.checkForUpdates.then.lando.bootstrap.then.lando (/snapshot/lando/build/cli/lib/cli.js:0:0)
From previous event:
    at module.exports.parseToYargs.checkForUpdates.then (/snapshot/lando/build/cli/lib/cli.js:0:0)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
From previous event:
    at Object.handler (/snapshot/lando/build/cli/lib/cli.js:0:0)
    at Object.runCommand (/snapshot/lando/build/cli/node_modules/yargs/lib/command.js:238:44)
    at Object.parseArgs [as _parseArgs] (/snapshot/lando/build/cli/node_modules/yargs/yargs.js:1063:30)
    at Function.get [as argv] (/snapshot/lando/build/cli/node_modules/yargs/yargs.js:1004:21)
    at Cli.run (/snapshot/lando/build/cli/lib/cli.js:0:0)
    at Object.<anonymous> (/snapshot/lando/build/cli/bin/lando.js:0:0)
    at Module._compile (pkg/prelude/bootstrap.js:1254:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:711:10)
    at Module.load (internal/modules/cjs/loader.js:610:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:549:12)
    at Function.Module._load (internal/modules/cjs/loader.js:541:3)
    at Function.Module.runMain (pkg/prelude/bootstrap.js:1309:12)
    at startup (internal/bootstrap/node.js:274:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:608:3)
debug: Logging metrics data {"context":"local","devMode":false,"nodeVersion":"v10.4.1","mode":"cli","os":{"type":"Darwin","platform":"darwin","release":"17.7.0","arch":"x64"},"product":"lando","version":"3.0.0-rc.15","message":"","stack":"Error\n    at module.exports.sh.Promise.try.then (/snapshot/lando/build/cli/lib/shell.js:0:0)\nFrom previous event:\n    at Shell.sh (/snapshot/lando/build/cli/lib/shell.js:0:0)\n    at Object.exports.dc (/snapshot/lando/build/cli/lib/bootstrap.js:0:0)\n    at compose (/snapshot/lando/build/cli/lib/bootstrap.js:0:0)\n    at exports.run.Promise.each.docker.isRunning.then.then (/snapshot/lando/build/cli/lib/router.js:0:0)\nFrom previous event:\n    at exports.run.Promise.each.datum (/snapshot/lando/build/cli/lib/router.js:0:0)\n    at runCallback (timers.js:696:18)\n    at tryOnImmediate (timers.js:667:5)\n    at processImmediate (timers.js:649:5)\nFrom previous event:\n    at Object.exports.run (/snapshot/lando/build/cli/lib/router.js:0:0)\n    at run (/snapshot/lando/build/cli/lib/engine.js:0:0)\n    at exports.eventWrapper.daemon.up.then.then (/snapshot/lando/build/cli/lib/router.js:0:0)\nFrom previous event:\n    at Object.exports.eventWrapper (/snapshot/lando/build/cli/lib/router.js:0:0)\n    at Engine.module.exports.constructor.engineCmd (/snapshot/lando/build/cli/lib/engine.js:0:0)\n    at Engine.run (/snapshot/lando/build/cli/lib/engine.js:0:0)\n    at Object.exports.run (/snapshot/lando/build/cli/plugins/lando-recipes/lib/build.js:0:0)\n    at lando.Promise.each.step (/snapshot/lando/build/cli/plugins/lando-recipes/tasks/init.js:0:0)\nFrom previous event:\n    at runBuild (/snapshot/lando/build/cli/plugins/lando-recipes/tasks/init.js:0:0)\n    at module.exports.lando.run.lando.events.emit.then (/snapshot/lando/build/cli/plugins/lando-recipes/tasks/init.js:0:0)\nFrom previous event:\n    at Object.run (/snapshot/lando/build/cli/plugins/lando-recipes/tasks/init.js:0:0)\n    at module.exports.parseToYargs.checkForUpdates.then.lando.bootstrap.then.lando.events.emit.then.then.then.then.then (/snapshot/lando/build/cli/lib/cli.js:0:0)\nFrom previous event:\n    at module.exports.parseToYargs.checkForUpdates.then.lando.bootstrap.then.lando (/snapshot/lando/build/cli/lib/cli.js:0:0)\nFrom previous event:\n    at module.exports.parseToYargs.checkForUpdates.then (/snapshot/lando/build/cli/lib/cli.js:0:0)\n    at runCallback (timers.js:696:18)\n    at tryOnImmediate (timers.js:667:5)\n    at processImmediate (timers.js:649:5)\nFrom previous event:\n    at Object.handler (/snapshot/lando/build/cli/lib/cli.js:0:0)\n    at Object.runCommand (/snapshot/lando/build/cli/node_modules/yargs/lib/command.js:238:44)\n    at Object.parseArgs [as _parseArgs] (/snapshot/lando/build/cli/node_modules/yargs/yargs.js:1063:30)\n    at Function.get [as argv] (/snapshot/lando/build/cli/node_modules/yargs/yargs.js:1004:21)\n    at Cli.run (/snapshot/lando/build/cli/lib/cli.js:0:0)\n    at Object.<anonymous> (/snapshot/lando/build/cli/bin/lando.js:0:0)\n    at Module._compile (pkg/prelude/bootstrap.js:1254:22)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:711:10)\n    at Module.load (internal/modules/cjs/loader.js:610:32)\n    at tryModuleLoad (internal/modules/cjs/loader.js:549:12)\n    at Function.Module._load (internal/modules/cjs/loader.js:541:3)\n    at Function.Module.runMain (pkg/prelude/bootstrap.js:1309:12)\n    at startup (internal/bootstrap/node.js:274:19)\n    at bootstrapNodeJSCore (internal/bootstrap/node.js:608:3)","action":"error","created":"2019-04-26T14:25:47.882Z"}
```

**Tell us generally about your bug**

I tried to pull down code from Github and create a `.lando.yml` as per the steps outlined in the Github section on https://docs.devwithlando.io/cli/init.html. 

Please detail the steps we can take to replicate this bug. Be as detailed as possible.

1. Ran `lando init`
2. Selected `github` when asked `From where should we get your app's codebase?`
3. Created a personal access token and assigned it the `repo`, `admin:public_key` and `user` scopes
4. Copied the personal access token & pasted it when asked `Enter a GitHub personal access token`
5. Selected the github repo I wanted to use from the list
6. Selected `pantheon` in response to `Which recipe do you want to use?`
7. Created a Pantheon machine token and pasted it when asked `Enter a Pantheon machine token`
8. Selected the pantheon site I wanted to use
9. Crossed fingers hoping all would go well

**Tell us more**

Could better documentation have prevented this issue? if so what should we change?
Does this bug prevent you from using lando?

Yes, this issue is currently preventing me from using lando, sadly. All was well with lando until yesterday morning when I upgraded from RC12 to RC15. I'm just trying to figure out if I'm missing something on my end or what. Thank you in advance for any help or insight!

**Comment by rudietuesdays** [comment]
Not sure why this was moved to `wontfix` because I'm getting this error on version `3.0.0-rc.16`

**Comment by michalsen** [comment]
Same error, with the same process ...

**Comment by mishac** [comment]
Same issue here, trying to init from a github repo.
