### ISSUE TITLE
latest postgres docker image update fails

### ISSUE THREAD

**Issue by JorisVanEijden** [lando/lando#1612]
Bitnami changed the config of their postgres container: https://github.com/bitnami/bitnami-docker-postgresql#notable-changes

This makes postgres installs fail.

```yml
name: test
recipe: lamp
config:
  php: '7.2'
  database: postgres
```

It will fail to start and the logs show a failure to start the entrypoint.

Remove any existing postgres images to ensure lando downloads the latest container.
`docker images -f reference=bitnami/postgresql -q | xargs docker rmi -f`

Attempted start:

```bash
$ lando start
...
Starting test_database_1 ... done
ERROR: No container found for database_1
error: Looks like database is not running! It should be so this is a problem.
warn: Try running `lando logs -s database` to help locate the problem!
```

The log:

```bash
$ lando logs -s database
Attaching to test_database_1
database_1   | mkdir: cannot create directory ‘/etc/ssh’: Permission denied
database_1   | Running command /app-entrypoint.sh /run.sh
database_1   | Running with exec!
database_1   | /lando-entrypoint.sh: 26: exec: /app-entrypoint.sh: not found
database_1   | mkdir: cannot create directory ‘/etc/ssh’: Permission denied
database_1   | Running command /app-entrypoint.sh /run.sh
database_1   | Running with exec!
database_1   | /lando-entrypoint.sh: 26: exec: /app-entrypoint.sh: not found
```

Workaround:
Use a tagged postgresql image from before r70:
```yml
name: test
recipe: lamp
config:
  php: '7.2'
  database: postgres:10.6.0-r68 
```

**Comment by mrweiner** [comment]
I'm seeing the same, although the workaround doesn't appear to work with the following .lando.yml for 3.0.0-rc.16 on windows 10 when defining the database as a service.
```name: st
recipe: drupal8
services:
  appserver:
    xdebug: true
  database:
    type: postgres:10.7.0-r68
    portforward: 3307
config:
  webroot: st_project/web
  php: 7.2
```
 It throws 
```
error: Error: postgres version 10.7.0-r68 is not supported
    at new LandoService (C:\snapshot\lando\build\cli\plugins\lando-core\compose\lando\builder.js:0:0)
    at new LandoService (C:\snapshot\lando\build\cli\plugins\lando-core\types\service\builder.js:0:0)
    at new LandoPostgres (C:\snapshot\lando\build\cli\plugins\lando-services\services\postgres\builder.js:0:0)
    at module.exports.app.events.on._.forEach.service (C:\snapshot\lando\build\cli\plugins\lando-services\app.js:0:0)    
    at arrayEach (C:\snapshot\lando\build\cli\node_modules\lodash\lodash.js:516:11)
    at Function.forEach (C:\snapshot\lando\build\cli\node_modules\lodash\lodash.js:9344:14)
    at AsyncEvents.module.exports.app.events.on (C:\snapshot\lando\build\cli\plugins\lando-services\app.js:0:0)
    at AsyncEvents.handle (C:\snapshot\lando\build\cli\lib\events.js:0:0)
    at emit.Promise.each.fn (C:\snapshot\lando\build\cli\lib\events.js:0:0)
From previous event:
    at AsyncEvents.emit (C:\snapshot\lando\build\cli\lib\events.js:0:0)
    at module.exports.init.loadPlugins.then (C:\snapshot\lando\build\cli\lib\app.js:0:0)
From previous event:
    at App.init (C:\snapshot\lando\build\cli\lib\app.js:0:0)
    at lando.Promise.try (C:\snapshot\lando\build\cli\lib\cli.js:0:0)
From previous event:
    at handleInteractive (C:\snapshot\lando\build\cli\lib\cli.js:0:0)
    at module.exports.parseToYargs.checkForUpdates.then.lando.bootstrap.then.lando.events.emit.then.then (C:\snapshot\lan
do\build\cli\lib\cli.js:0:0)
From previous event:
    at module.exports.parseToYargs.checkForUpdates.then.lando.bootstrap.then.lando (C:\snapshot\lando\build\cli\lib\cli.j
s:0:0)
From previous event:
    at module.exports.parseToYargs.checkForUpdates.then (C:\snapshot\lando\build\cli\lib\cli.js:0:0)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
From previous event:
    at Object.handler (C:\snapshot\lando\build\cli\lib\cli.js:0:0)
    at Object.runCommand (C:\snapshot\lando\build\cli\node_modules\yargs\lib\command.js:238:44)
    at Object.parseArgs [as _parseArgs] (C:\snapshot\lando\build\cli\node_modules\yargs\yargs.js:1063:30)
    at Function.get [as argv] (C:\snapshot\lando\build\cli\node_modules\yargs\yargs.js:1004:21)
    at Cli.run (C:\snapshot\lando\build\cli\lib\cli.js:0:0)
    at Object.<anonymous> (C:\snapshot\lando\build\cli\bin\lando.js:0:0)
    at Module._compile (pkg/prelude/bootstrap.js:1254:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:711:10)
    at Module.load (internal/modules/cjs/loader.js:610:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:549:12)
    at Function.Module._load (internal/modules/cjs/loader.js:541:3)
    at Function.Module.runMain (pkg/prelude/bootstrap.js:1309:12)
    at startup (internal/bootstrap/node.js:274:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:608:3)
```

**Comment by JorisVanEijden** [comment]
Bitnami is right now releasing new versions of their image that contains a fix for config file loading.
https://github.com/bitnami/bitnami-docker-postgresql/pull/132
https://hub.docker.com/r/bitnami/postgresql/tags
Let's see if that helps.

**Comment by JorisVanEijden** [comment]
Looks like that release doesn't help.
I'm running on `database: postgres:9.6.12-r68` which is fine.
perhaps there is a 10.x tag that also still works?

**Comment by mrweiner** [comment]
Are you getting this at all?
```
warn: Service database is unhealthy
warn: Run "lando logs -s database"
```
I see that instead of `ERROR: No container found for database_1` for 9.6.12-r68 and 10.6.0. This is my first app using postgres so maybe this is a normal thing to see.

**Comment by mrweiner** [comment]
Actually I think that may have to do with the "services" .lando.yml syntax recommended in the docs. I get that issue when using
```
name: st
recipe: drupal8
services:
  appserver:
    xdebug: true
  database:
    type: postgres:10.6.0
    portforward: 3307
config:
  webroot: st_project/web
  php: 7.2
```
but not when using
```
name: st
recipe: drupal8
config:
  webroot: st_project/web
  php: 7.2
  database: postgres:10.6.0
  portforward: 3307
  xdebug: true
```

Think it warrants a separate issue?

**Comment by pirog** [comment]
@mrweiner if the syntax you use is not supported i dont think you should expect it to work. 

`portforward` is not part of the recipe config because it is `service` specific and we dont really want to try to guess what service's ports you want to foward.

**Comment by pirog** [comment]
i think the lowest common denominator workaround that is probably going to work regardless of other choices youve made in your landofile(s) is _something_ like this

```yaml
name: myapp
services:
  database:
    type: postgres:custom
    overrides:
      image: bitnami/postgres:9.6.12-r68
```

**Comment by jcandan** [comment]
That seems to have worked @pirog, thanks! However, note that the correct path is `bitnami/postgresql`, not just `bitnami/postgres`

Also note, that I had to still specify `postgres` for my `drupal7` recipe. Otherwise `mysql` was default, and the `database` override was failing to supply a `psql` command.

End result: this workaround worked for me:

```
name: myapp
recipe: drupal7
config:
  webroot: .
  database: postgres
services:
  database:
    type: postgres:custom
    overrides:
      image: bitnami/postgresql:10.7.0-r68
```

**Comment by mrweiner** [comment]
@pirog I didn't expect portforward to work, just wanted to note that it didn't. Didn't realize it was service specific but that makes. By "Think it warrants a separate issue?" I was referring to the issue with the service syntax not working with @JorisVanEijden workaround. I see now that that wasn't at all clear.

Can confirm that @jcandan .lando.yml worked for me as well. Thanks everybody!

**Comment by thursdaybw** [comment]
When I apply the workaround in here https://github.com/lando/lando/issues/1612#issuecomment-491909162

I get this issue:

```
$ lando rebuild
? Are you sure you want to rebuild? Yes
Rising anew like a fire phoenix from the ashes! Rebuilding app...
No stopped containers
Pulling database      ... error
Pulling elasticsearch ... done

ERROR: for database  pull access denied for bitnami/postgres, repository does not exist or may require 'docker login'
ERROR: pull access denied for bitnami/postgres, repository does not exist or may require 'docker login'
Pulling database      ... error
```

**Comment by thursdaybw** [comment]
I've logged into my dockerhub account using `docker login`, same issue.

**Comment by pirog** [comment]
@thursdaybw note that `bitnami/postgres` is not a valid image so that error mesage makes sense

**Comment by thursdaybw** [comment]
@pirog Thank you so much for putting those commits in to fix the postgres issue.
I was never able to get postgres version 9 working.. but now, having installed the dev lando from source I can again.

**Comment by thursdaybw** [comment]
I'm still having this issue, well at least, again i'm having this issue.

lando logs:
```
database_1   | chmod: changing permissions of '/helpers/add-cert.sh': Operation not permitted
database_1   | chmod: changing permissions of '/helpers/auth.sh': Operation not permitted
database_1   | chmod: changing permissions of '/helpers/binding.sh': Operation not permitted
database_1   | chmod: changing permissions of '/helpers/generate-key.sh': Operation not permitted
database_1   | chmod: changing permissions of '/helpers/get-remote-url.sh': Operation not permitted
database_1   | chmod: changing permissions of '/helpers/lando-entrypoint.sh': Operation not permitted
database_1   | chmod: changing permissions of '/helpers/load-keys.sh': Operation not permitted
database_1   | chmod: changing permissions of '/helpers/mounter.sh': Operation not permitted
database_1   | chmod: changing permissions of '/helpers/pantheon.sh': Operation not permitted
database_1   | chmod: changing permissions of '/helpers/pull.sh': Operation not permitted
database_1   | chmod: changing permissions of '/helpers/push.sh': Operation not permitted
database_1   | chmod: changing permissions of '/helpers/refresh-certs.sh': Operation not permitted
database_1   | chmod: changing permissions of '/helpers/setup-ca.sh': Operation not permitted
database_1   | chmod: changing permissions of '/helpers/sql-export.sh': Operation not permitted
database_1   | chmod: changing permissions of '/helpers/sql-import.sh': Operation not permitted
database_1   | chmod: changing permissions of '/helpers/switch.sh': Operation not permitted
database_1   | chmod: changing permissions of '/helpers/user-perm-helpers.sh': Operation not permitted
database_1   | chmod: changing permissions of '/helpers/user-perms.sh': Operation not permitted
database_1   | chmod: changing permissions of '/helpers/user-perms.sh': Operation not permitted
database_1   | chmod: changing permissions of '/scripts/load-keys.sh': Operation not permitted
database_1   | mkdir: cannot create directory ‘/etc/ssh’: Permission denied
database_1   | Running command /app-entrypoint.sh /run.sh
database_1   | Running with exec!
database_1   | /lando-entrypoint.sh: 26: exec: /app-entrypoint.sh: not found
```

.lando.yml
```
name: myproject
recipe: drupal7
config:
  webroot: .
  database: postgres:9.6
```

```
lando version
v3.0.0-rc.19
```

I've done all the usual, deltee ~/.lando .. lando destroy, deleted all the docker images, restarted docker, rebooted etc..... this issue just wont' seem to go away, and I don't understand it well enough to do anything but guess.

**Comment by thursdaybw** [comment]
Here's a simpler example with just postgres and no recipes.

.lando.yml
```
name: postgres
services:
  my-service:
    type: postgres:9.6
```
lando logs -f
```
 lando logs -f
Attaching to postgres_my-service_1
my-service_1  | chmod: changing permissions of '/helpers/add-cert.sh': Operation not permitted
my-service_1  | chmod: changing permissions of '/helpers/auth.sh': Operation not permitted
my-service_1  | chmod: changing permissions of '/helpers/binding.sh': Operation not permitted
my-service_1  | chmod: changing permissions of '/helpers/generate-key.sh': Operation not permitted
my-service_1  | chmod: changing permissions of '/helpers/get-remote-url.sh': Operation not permitted
my-service_1  | chmod: changing permissions of '/helpers/lando-entrypoint.sh': Operation not permitted
my-service_1  | chmod: changing permissions of '/helpers/load-keys.sh': Operation not permitted
my-service_1  | chmod: changing permissions of '/helpers/mounter.sh': Operation not permitted
my-service_1  | chmod: changing permissions of '/helpers/pantheon.sh': Operation not permitted
my-service_1  | chmod: changing permissions of '/helpers/pull.sh': Operation not permitted
my-service_1  | chmod: changing permissions of '/helpers/push.sh': Operation not permitted
my-service_1  | chmod: changing permissions of '/helpers/refresh-certs.sh': Operation not permitted
my-service_1  | chmod: changing permissions of '/helpers/setup-ca.sh': Operation not permitted
my-service_1  | chmod: changing permissions of '/helpers/sql-export.sh': Operation not permitted
my-service_1  | chmod: changing permissions of '/helpers/sql-import.sh': Operation not permitted
my-service_1  | chmod: changing permissions of '/helpers/switch.sh': Operation not permitted
my-service_1  | chmod: changing permissions of '/helpers/user-perm-helpers.sh': Operation not permitted
my-service_1  | chmod: changing permissions of '/helpers/user-perms.sh': Operation not permitted
my-service_1  | chmod: changing permissions of '/helpers/user-perms.sh': Operation not permitted
my-service_1  | chmod: changing permissions of '/scripts/load-keys.sh': Operation not permitted
my-service_1  | mkdir: cannot create directory ‘/etc/ssh’: Permission denied
my-service_1  | Running command /app-entrypoint.sh /run.sh
my-service_1  | Running with exec!
my-service_1  | /lando-entrypoint.sh: 26: exec: /app-entrypoint.sh: not found
postgres_my-service_1 exited with code 127
```

**Comment by thursdaybw** [comment]
OK.. well appears the previously described workaround (pasted here with the correct image name), works again in rc19.

```
name: postgres
services:
  my-service:
    type: postgres:custom
    overrides:
      image: bitnami/postgresql:9.6.12-r68
```

**Comment by thursdaybw** [comment]
I may have some details wrong.. 
Trying all sorts of things.
Finally i've reverted to v3.0.0-rc.16 and use the previously mentioned workaround..
Although I'm using the drupal7 recipe, and if I specify database as the service name it fails.
so i'm running mysql AND postgres.

I'm fairly certain at this point that the cause of the rc19 issue is the upstream bitnami images has changed it's user from root to 1001.. I'm not entirely sure and havent' got my head around docker-compose and particulary translatin the relevant parts postgres/builder.js

**Comment by IOIIOOIO** [comment]
Hi, I'm really stuck. I'm having the same errors but my setup is using mysql.

My lando.yml:

name: mysite
recipe: wordpress
config:
  webroot: .
  php: 7.3
  via: apache:2.4
  database: mysql:5.7
  xdebug: false
proxy:
  mailhog:
    - mail.mysite.lndo.site
  pma:
    - db.mysite.lndo.site
services:
  pma:
    type: phpmyadmin
    hosts:
      - database
  mailhog:
    type: mailhog
    hogfrom:
      - appserver

**Comment by pirog** [comment]
@IOIIOOIO your best bet is to update to the latest version of Lando and do a `lando rebuild`. You may also want to check out this thread
https://github.com/lando/lando/issues/2057

**Comment by thursdaybw** [comment]
I had this issue show up in mysql when I switched projects... the fix is as pirog suggested, upgarde lndo.. that resolved both postgres and mysql rendering my above work around redundant.

**Comment by rick02840** [comment]
I had this error:
```
Starting mysite_database_1 ... done
ERROR: No container found for database_1
```
Reinstalled Lando from lando-v3.0.0-rrc.1.dmg https://github.com/lando/lando/releases/tag/v3.0.0-rrc.1 
then did lando rebuild  
fixed
