### ISSUE TITLE
build commands fail with literal command

### ISSUE THREAD

**Issue by tenken** [lando/lando#1661]
1.  Update to the [latest version](https://github.com/lando/lando/releases) of Lando and make sure the issue isn't fixed already.

`Done!`

2.  Please review the [current list of issues](https://github.com/lando/lando/issues) to make sure you are not submitting a duplicate.

`Done!`

**Tell us about your setup**

What is your lando version and operating system? **(note that the older your version the less likely we are to reply)**

```
lando version
v3.0.0-rc.16
```

```
sudo docker version
[sudo] password for dgurba: 
Client:
 Version:           18.09.6
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        481bc77
 Built:             Sat May  4 02:35:27 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.6
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       481bc77
  Built:            Sat May  4 01:59:36 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

```
cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.2 LTS"
```

**Tell us about your `.lando.yml`**

Paste in the contents of your `.lando.yml` this is **SUPER HELPFUL** for us.

*This Example seems to cause an error*

```yml
name: id-ucsb-edu-v-01
recipe: pantheon
config:
  framework: drupal8
  site: id-ucsb-edu-v01
  id: xxxxxxxxxxxxxxxxxxxxxxxxxxxxx

services:
  appserver:
    build:
      cmd:
        - "mkdir -p /var/www/.terminus/plugins"
        - "cd /var/www/.terminus/plugins"
        - "git clone https://github.com/pantheon-systems/terminus-aliases-plugin.git"
        - "cd terminus-aliases-plugin"
        - "composer install --no-dev"
```

**Tell us about the error you got**

Example erorrs:

```txt
OCI runtime exec failed: exec failed: container_linux.go:345: starting container process caused "exec: \"mkdir -p /var/www/.terminus/plugins\": stat mkdir -p /var/www/.terminus/plugins: no such file or directory": unknown
error: Looks like one of your build steps failed! with Error
    at module.exports.sh.Promise.try.then (/snapshot/lando/build/cli/lib/shell.js:0:0)
From previous event:
    at Shell.sh (/snapshot/lando/build/cli/lib/shell.js:0:0)
    at Object.exports.dc (/snapshot/lando/build/cli/lib/bootstrap.js:0:0)
    at compose (/snapshot/lando/build/cli/lib/bootstrap.js:0:0)
    at exports.run.Promise.each.docker.isRunning.then.then (/snapshot/lando/build/cli/lib/router.js:0:0)
From previous event:
    at exports.run.Promise.each.datum (/snapshot/lando/build/cli/lib/router.js:0:0)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
From previous event:
    at Object.exports.run (/snapshot/lando/build/cli/lib/router.js:0:0)
    at run (/snapshot/lando/build/cli/lib/engine.js:0:0)
    at exports.eventWrapper.daemon.up.then.then (/snapshot/lando/build/cli/lib/router.js:0:0)
From previous event:
    at Object.exports.eventWrapper (/snapshot/lando/build/cli/lib/router.js:0:0)
    at Engine.module.exports.constructor.engineCmd (/snapshot/lando/build/cli/lib/engine.js:0:0)
    at Engine.run (/snapshot/lando/build/cli/lib/engine.js:0:0)
    at Object.exports.runBuild (/snapshot/lando/build/cli/plugins/lando-services/lib/utils.js:0:0)
    at AsyncEvents.module.exports.app.events.on.app.events.on (/snapshot/lando/build/cli/plugins/lando-services/app.js:0:0)
    at AsyncEvents.handle (/snapshot/lando/build/cli/lib/events.js:0:0)
    at emit.Promise.each.fn (/snapshot/lando/build/cli/lib/events.js:0:0)
From previous event:
    at AsyncEvents.emit (/snapshot/lando/build/cli/lib/events.js:0:0)
    at module.exports.start.initAndReport.then (/snapshot/lando/build/cli/lib/app.js:0:0)
From previous event:
    at App.start (/snapshot/lando/build/cli/lib/app.js:0:0)
    at module.exports.rebuild.initAndReport.then.then.then.then.then (/snapshot/lando/build/cli/lib/app.js:0:0)
From previous event:
    at App.rebuild (/snapshot/lando/build/cli/lib/app.js:0:0)
    at Object.exports.appToggle (/snapshot/lando/build/cli/plugins/lando-core/lib/utils.js:0:0)
    at Object.run (/snapshot/lando/build/cli/plugins/lando-core/tasks/rebuild.js:0:0)
    at module.exports.parseToYargs.checkForUpdates.then.lando.bootstrap.then.lando.events.emit.then.then.then.then.then (/snapshot/lando/build/cli/lib/cli.js:0:0)
From previous event:
    at module.exports.parseToYargs.checkForUpdates.then.lando.bootstrap.then.lando (/snapshot/lando/build/cli/lib/cli.js:0:0)
From previous event:
    at module.exports.parseToYargs.checkForUpdates.then (/snapshot/lando/build/cli/lib/cli.js:0:0)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
From previous event:
    at Object.handler (/snapshot/lando/build/cli/lib/cli.js:0:0)
    at Object.runCommand (/snapshot/lando/build/cli/node_modules/yargs/lib/command.js:238:44)
    at Object.parseArgs [as _parseArgs] (/snapshot/lando/build/cli/node_modules/yargs/yargs.js:1063:30)
    at Function.get [as argv] (/snapshot/lando/build/cli/node_modules/yargs/yargs.js:1004:21)
    at Cli.run (/snapshot/lando/build/cli/lib/cli.js:0:0)
    at lando.bootstrap.then.lando.getApp.init.then (/snapshot/lando/build/cli/bin/lando.js:0:0)
From previous event:
    at lando.bootstrap.then.lando (/snapshot/lando/build/cli/bin/lando.js:0:0)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
From previous event:
    at Object.<anonymous> (/snapshot/lando/build/cli/bin/lando.js:0:0)
    at Module._compile (pkg/prelude/bootstrap.js:1254:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:711:10)
    at Module.load (internal/modules/cjs/loader.js:610:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:549:12)
    at Function.Module._load (internal/modules/cjs/loader.js:541:3)
    at Function.Module.runMain (pkg/prelude/bootstrap.js:1309:12)
    at startup (internal/bootstrap/node.js:274:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:608:3)
warn: This **MAY** prevent your app from working
warn: Check for errors above, fix them, and try again
```

and also:

```txt
OCI runtime exec failed: exec failed: container_linux.go:345: starting container process caused "exec: \"cd\": executable file not found in $PATH": unknown
```

**Tell us more**

What appears to work is to supply the `cmd` expressions in a bash script with a shebang. Otherwise the commands seem to never process in a subshell.

```yml
services:
  appserver:
    build:
      cmd:
        - ./scripts/lando_helpers/terminus_aliases_plugin.sh
```

**Comment by tenken** [comment]
I have also tried quoting and unquoting command entries as seen on https://docs.devwithlando.io/config/tooling.html

**Comment by tenken** [comment]
Ah, this is documented here https://docs.devwithlando.io/config/services.html#using-scripty-things

The literal approach now only works if a shell is specified, or a script as I noted is preferred after https://docs.devwithlando.io/guides/updating-to-rc2.html#build-steps
