### ISSUE TITLE
Decouple apache from our apache-php service so the versions of both are configurable just like our php/nginx implementation

### ISSUE THREAD

**Issue by cainaru** [lando/lando#1671]
**Tell us about your setup**
What is your lando version and operating system?
v3.0.0-rc.17 on macOS Mojave 10.14.5

**Tell us about your `.lando.yml`**
For attempting to use a patch version of apache:
```yml
name: d8-gardenshare
recipe: drupal8
config:
  php: '7.2'
  via: apache
  webroot: web
  database: mariadb
services:
 appserver:
    type: apache:2.4.39
  database:
    type: mariadb:10.3.15
```

**Tell us about the command you were running**
I was attempting to use Apache 2.4.39 instead of 2.4.25 by using the below snippet that is provided in the docs at https://docs.devwithlando.io/tutorials/apache.html#patch-versions as guidance:
```yml
services:
 my-service:
    type: apache:2.4.33
```

After running `lando start`, I received the following error:
```
lando start
Let's get this party started! Starting app..
landoproxyhyperion5000gandalfedition_proxy_1 is up-to-date
Creating network "d8gardenshare_default" with the default driver
Creating volume "d8gardenshare_data_appserver" with default driver
Creating volume "d8gardenshare_home_appserver" with default driver
Creating volume "d8gardenshare_data_database" with default driver
Creating volume "d8gardenshare_home_database" with default driver
Creating d8gardenshare_appserver_1 ... done
Killing d8gardenshare_appserver_1 ... done
Starting d8gardenshare_appserver_1 ... done
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   599    0   599    0     0   1972      0 --:--:-- --:--:-- --:--:--  1976
100 4673k  100 4673k    0     0  4665k      0  0:00:01  0:00:01 --:--:-- 11.1M
/usr/bin/env: 'php': No such file or directory
error: Looks like one of your build steps failed! with Error
    at module.exports.sh.Promise.try.then (/snapshot/lando/build/cli/lib/shell.js:0:0)
From previous event:
    at Shell.sh (/snapshot/lando/build/cli/lib/shell.js:0:0)
    at Object.exports.dc (/snapshot/lando/build/cli/lib/bootstrap.js:0:0)
    at compose (/snapshot/lando/build/cli/lib/bootstrap.js:0:0)
    at exports.run.Promise.each.docker.isRunning.then.then (/snapshot/lando/build/cli/lib/router.js:0:0)
From previous event:
    at exports.run.Promise.each.datum (/snapshot/lando/build/cli/lib/router.js:0:0)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
From previous event:
    at Object.exports.run (/snapshot/lando/build/cli/lib/router.js:0:0)
    at run (/snapshot/lando/build/cli/lib/engine.js:0:0)
    at exports.eventWrapper.daemon.up.then.then (/snapshot/lando/build/cli/lib/router.js:0:0)
From previous event:
    at Object.exports.eventWrapper (/snapshot/lando/build/cli/lib/router.js:0:0)
    at Engine.module.exports.constructor.engineCmd (/snapshot/lando/build/cli/lib/engine.js:0:0)
    at Engine.run (/snapshot/lando/build/cli/lib/engine.js:0:0)
    at Object.exports.runBuild (/snapshot/lando/build/cli/plugins/lando-services/lib/utils.js:0:0)
    at AsyncEvents.module.exports.app.events.on.app.events.on (/snapshot/lando/build/cli/plugins/lando-services/app.js:0:0)
    at AsyncEvents.handle (/snapshot/lando/build/cli/lib/events.js:0:0)
    at emit.Promise.each.fn (/snapshot/lando/build/cli/lib/events.js:0:0)
From previous event:
    at AsyncEvents.emit (/snapshot/lando/build/cli/lib/events.js:0:0)
    at module.exports.start.initAndReport.then (/snapshot/lando/build/cli/lib/app.js:0:0)
From previous event:
    at App.start (/snapshot/lando/build/cli/lib/app.js:0:0)
    at Object.exports.appToggle (/snapshot/lando/build/cli/plugins/lando-core/lib/utils.js:0:0)
    at Object.run (/snapshot/lando/build/cli/plugins/lando-core/tasks/start.js:0:0)
    at module.exports.parseToYargs.checkForUpdates.then.lando.bootstrap.then.lando.events.emit.then.then.then.then.then (/snapshot/lando/build/cli/lib/cli.js:0:0)
From previous event:
    at module.exports.parseToYargs.checkForUpdates.then.lando.bootstrap.then.lando (/snapshot/lando/build/cli/lib/cli.js:0:0)
From previous event:
    at module.exports.parseToYargs.checkForUpdates.then (/snapshot/lando/build/cli/lib/cli.js:0:0)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
From previous event:
    at Object.handler (/snapshot/lando/build/cli/lib/cli.js:0:0)
    at Object.runCommand (/snapshot/lando/build/cli/node_modules/yargs/lib/command.js:238:44)
    at Object.parseArgs [as _parseArgs] (/snapshot/lando/build/cli/node_modules/yargs/yargs.js:1063:30)
    at Function.get [as argv] (/snapshot/lando/build/cli/node_modules/yargs/yargs.js:1004:21)
    at Cli.run (/snapshot/lando/build/cli/lib/cli.js:0:0)
    at lando.bootstrap.then.lando.getApp.init.then (/snapshot/lando/build/cli/bin/lando.js:0:0)
From previous event:
    at lando.bootstrap.then.lando (/snapshot/lando/build/cli/bin/lando.js:0:0)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
From previous event:
    at Object.<anonymous> (/snapshot/lando/build/cli/bin/lando.js:0:0)
    at Module._compile (pkg/prelude/bootstrap.js:1254:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:711:10)
    at Module.load (internal/modules/cjs/loader.js:610:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:549:12)
    at Function.Module._load (internal/modules/cjs/loader.js:541:3)
    at Function.Module.runMain (pkg/prelude/bootstrap.js:1309:12)
    at startup (internal/bootstrap/node.js:274:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:608:3)
warn: This **MAY** prevent your app from working
warn: Check for errors above, fix them, and try again
Starting d8gardenshare_appserver_1 ... done
Creating d8gardenshare_database_1  ... done
Waiting until database service is ready...
Waiting until appserver service is ready...
Waiting until database service is ready...
Waiting until database service is ready...
Waiting until database service is ready...
Waiting until database service is ready...
Waiting until database service is ready...

BOOMSHAKALAKA!!!

Your app has started up correctly.
Here are some vitals:

 NAME            d8-gardenshare                                              
 LOCATION        /Users/ncainaru/Sites/lando/sandbox/d8-gardenshare
 SERVICES        appserver, database                                                    
 APPSERVER URLS  https://localhost:33265                                                
                 http://localhost:33266                                                 
                 http://d8-gardenshare.lndo.site                              
                 https://d8-gardenshare.lndo.site
```

Running `lando ssh -s appserver -c "apachectl -V | grep 2.4."` does at least show `Server version: Apache/2.4.39 (Unix)` though.

**Tell us more**
Could better documentation have prevented this issue? if so what should we change?
It might be helpful to change the section regarding patch versions at https://docs.devwithlando.io/tutorials/apache.html#patch-versions? Maybe the syntax worked well before rc2 came out, but doesn't anymore? 

Does this bug prevent you from using lando?
No, it doesn't prevent me from using lando.

**Comment by pirog** [comment]
@cainaru so looking at this a bit more i think you actually are getting the "expected" behavior but totally agreed that it is a bit confusing. fundamentally the problem here is the underlying image we use to serve php via apache is a single image. this means that both php and apache are installed in the same container and each container "floats" based on the php version while the apache version is "baked in". 

This stand in contrast to how we deliver php via nginx which uses a separate php and nginx service and by extension allows the versions of both to float. This is compounded by the fact that we also offer a standalone apache service, eg one that is just a vanilla webserver with no ability to serve php by default which is configurable by version.

So i think what is happening in the Landofile below is "replace my php 7.2 container that is powered by apache with a vanilla apache server running apache 2.4.39." Totally makes sense you'd get a `php not found` error since there is no `php` in our vanilla service.

 ```yaml
name: d8-gardenshare
recipe: drupal8
config:
  php: '7.2'
  via: apache
  webroot: web
  database: mariadb
services:
 appserver:
    type: apache:2.4.39
  database:
    type: mariadb:10.3.15
```

So i think the ideal thing do here is convert this to a feature request to see if we can get apache/php decoupled the same way nginx/php is and have a single way we handle this. Not sure if this is possible based on the images we are using so that would be the first thing to figure out.

**Comment by dustinleblanc** [comment]
unstale

**Comment by pirog** [comment]
thank you @dustinleblanc
