### ISSUE TITLE
Issue when I launch lando

### ISSUE THREAD

**Issue by bianqui149** [lando/lando#1710]
Hi every time that I want to run lando (lando start, lando pull) I get this error:
at new LandoService (/snapshot/lando/build/cli/plugins/lando-core/compose/lando/builder.js:0:0)
    at new LandoAppserver (/snapshot/lando/build/cli/plugins/lando-core/types/appserver/builder.js:0:0)
    at new LandoPhp (/snapshot/lando/build/cli/plugins/lando-services/services/php/builder.js:0:0)
    at module.exports.app.events.on._.forEach.service (/snapshot/lando/build/cli/plugins/lando-services/app.js:0:0)
    at arrayEach (/snapshot/lando/build/cli/node_modules/lodash/lodash.js:516:11)
    at Function.forEach (/snapshot/lando/build/cli/node_modules/lodash/lodash.js:9344:14)
    at AsyncEvents.module.exports.app.events.on (/snapshot/lando/build/cli/plugins/lando-services/app.js:0:0)
    at AsyncEvents.handle (/snapshot/lando/build/cli/lib/events.js:0:0)
    at emit.Promise.each.fn (/snapshot/lando/build/cli/lib/events.js:0:0)
From previous event:
    at AsyncEvents.emit (/snapshot/lando/build/cli/lib/events.js:0:0)
    at module.exports.init.loadPlugins.then (/snapshot/lando/build/cli/lib/app.js:0:0)
From previous event:
    at App.init (/snapshot/lando/build/cli/lib/app.js:0:0)
    at lando.Promise.try (/snapshot/lando/build/cli/lib/cli.js:0:0)
From previous event:
    at handleInteractive (/snapshot/lando/build/cli/lib/cli.js:0:0)
    at module.exports.parseToYargs.checkForUpdates.then.lando.bootstrap.then.lando.events.emit.then.then (/snapshot/lando/build/cli/lib/cli.js:0:0)
From previous event:
    at module.exports.parseToYargs.checkForUpdates.then.lando.bootstrap.then.lando (/snapshot/lando/build/cli/lib/cli.js:0:0)
From previous event:
    at module.exports.parseToYargs.checkForUpdates.then (/snapshot/lando/build/cli/lib/cli.js:0:0)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
From previous event:
    at Object.handler (/snapshot/lando/build/cli/lib/cli.js:0:0)
    at Object.runCommand (/snapshot/lando/build/cli/node_modules/yargs/lib/command.js:238:44)
    at Object.parseArgs [as _parseArgs] (/snapshot/lando/build/cli/node_modules/yargs/yargs.js:1063:30)
    at Function.get [as argv] (/snapshot/lando/build/cli/node_modules/yargs/yargs.js:1004:21)
    at Cli.run (/snapshot/lando/build/cli/lib/cli.js:0:0)
    at Object.<anonymous> (/snapshot/lando/build/cli/bin/lando.js:0:0)
    at Module._compile (pkg/prelude/bootstrap.js:1252:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:711:10)
    at Module.load (internal/modules/cjs/loader.js:610:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:549:12)
    at Function.Module._load (internal/modules/cjs/loader.js:541:3)
    at Function.Module.runMain (pkg/prelude/bootstrap.js:1307:12)
    at startup (internal/bootstrap/node.js:274:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:608:3)

**Comment by pirog** [comment]
@bianqui149 you are going to need to provide a more detailed error report with clear steps to replicate. This works as expected for me and given the lack of comments: probably mostly everyone else. Try to think of things that might be unique to your system
