### ISSUE TITLE
Can't init from pantheon

### ISSUE THREAD

**Issue by hades200082** [lando/lando#1745]
**Tell us about your setup**

What is your lando version and operating system? 

**Lando v3.0.0-rc.20 on Windows 10 Professional**

**Tell us about your `.lando.yml`**

I don't have one yet - lando init is failing.

**Tell us about the command you were running**

I've tried to init for a pantheon site using the following commands:

`lando init` -> Select "Patheon" -> Enter machine token.

`lando init --source pantheon --pantheon-auth "<my machine token>" --pantheon-site "<my site name>"`

`lando init --source pantheon --pantheon-auth "<my machine token>"` -> select the site

**Tell us about the error you got**

The first command listed above results in the error `error: POST request to https://terminus.pantheon.io/api/authorize/machine-token failed with code 500: Internal Server Error. The server responded with the message Authorization failed. Please check that your machine token is valid..`

I've tried this with 3 different tokens created under different pantheon accounts with the same result every time.

Both of the last two commands above result in an error:

```
Creating network "landoinitngcharteredsurveyors_default" with the default driver
Creating volume "landoinitngcharteredsurveyors_data_init" with default driver
Creating volume "landoinitngcharteredsurveyors_home_init" with default driver
Creating landoinitngcharteredsurveyors_init_1 ... done
Stopping landoinitngcharteredsurveyors_init_1 ... done
Starting landoinitngcharteredsurveyors_init_1 ... done
Creating a special not-mounted key directory for Windows
Copying /lando/keys/pantheon.lando.id_rsa from /lando/keys to /lando_keys
Copying /lando/keys/pantheon.lando.id_rsa.pub from /lando/keys to /lando_keys
Scanning /lando_keys for keys...
Found keys /lando_keys/pantheon.lando.id_rsa
Ensuring permissions and ownership of /lando_keys/pantheon.lando.id_rsa...
Checking whether /lando_keys/pantheon.lando.id_rsa is a private key...
Checking whether /lando_keys/pantheon.lando.id_rsa is formatted correctly...
Using the following keys: /lando_keys/pantheon.lando.id_rsa
Stopping landoinitngcharteredsurveyors_init_1 ... done
Starting landoinitngcharteredsurveyors_init_1 ... done
Detected that ssh://codeserver.dev.c822bd0b-1cdf-4d31-b5b4-3d40dbb5f4e0@codeserver.dev.c822bd0b-1cdf-4d31-b5b4-3d40dbb5f4e0.drush.in:2222/~/repository.git is a tar archive
Downloading ssh://codeserver.dev.c822bd0b-1cdf-4d31-b5b4-3d40dbb5f4e0@codeserver.dev.c822bd0b-1cdf-4d31-b5b4-3d40dbb5f4e0.drush.in:2222/~/repository.git...
curl: (1) Protocol "ssh" not supported or disabled in libcurl
Stopping landoinitngcharteredsurveyors_init_1 ... done
Removing landoinitngcharteredsurveyors_init_1 ... done
Removing network landoinitngcharteredsurveyors_default
Removing volume landoinitngcharteredsurveyors_data_init
Removing volume landoinitngcharteredsurveyors_home_init
error: Error
    at module.exports.sh.Promise.try.then (C:\snapshot\lando\build\cli\lib\shell.js:0:0)
From previous event:
    at Shell.sh (C:\snapshot\lando\build\cli\lib\shell.js:0:0)
    at Object.exports.dc (C:\snapshot\lando\build\cli\lib\bootstrap.js:0:0)
    at compose (C:\snapshot\lando\build\cli\lib\bootstrap.js:0:0)
    at exports.run.Promise.each.docker.isRunning.then.then (C:\snapshot\lando\build\cli\lib\router.js:0:0)
From previous event:
    at exports.run.Promise.each.datum (C:\snapshot\lando\build\cli\lib\router.js:0:0)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
From previous event:
    at Object.exports.run (C:\snapshot\lando\build\cli\lib\router.js:0:0)
    at run (C:\snapshot\lando\build\cli\lib\engine.js:0:0)
    at exports.eventWrapper.daemon.up.then.then (C:\snapshot\lando\build\cli\lib\router.js:0:0)
From previous event:
    at Object.exports.eventWrapper (C:\snapshot\lando\build\cli\lib\router.js:0:0)
    at Engine.module.exports.constructor.engineCmd (C:\snapshot\lando\build\cli\lib\engine.js:0:0)
    at Engine.run (C:\snapshot\lando\build\cli\lib\engine.js:0:0)
    at Object.exports.run (C:\snapshot\lando\build\cli\plugins\lando-recipes\lib\build.js:0:0)
    at lando.Promise.each.step (C:\snapshot\lando\build\cli\plugins\lando-recipes\tasks\init.js:0:0)
From previous event:
    at runBuild (C:\snapshot\lando\build\cli\plugins\lando-recipes\tasks\init.js:0:0)
    at module.exports.lando.run.lando.events.emit.then (C:\snapshot\lando\build\cli\plugins\lando-recipes\tasks\init.js:0:0)
From previous event:
    at Object.run (C:\snapshot\lando\build\cli\plugins\lando-recipes\tasks\init.js:0:0)
    at module.exports.parseToYargs.checkForUpdates.then.lando.bootstrap.then.lando.events.emit.then.then.then.then.then (C:\snapshot\lando\build\cli\lib\cli.js:0:0)
From previous event:
    at module.exports.parseToYargs.checkForUpdates.then.lando.bootstrap.then.lando (C:\snapshot\lando\build\cli\lib\cli.js:0:0)
From previous event:
    at module.exports.parseToYargs.checkForUpdates.then (C:\snapshot\lando\build\cli\lib\cli.js:0:0)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
From previous event:
    at Object.handler (C:\snapshot\lando\build\cli\lib\cli.js:0:0)
    at Object.runCommand (C:\snapshot\lando\build\cli\node_modules\yargs\lib\command.js:238:44)
    at Object.parseArgs [as _parseArgs] (C:\snapshot\lando\build\cli\node_modules\yargs\yargs.js:1063:30)
    at Function.get [as argv] (C:\snapshot\lando\build\cli\node_modules\yargs\yargs.js:1004:21)
    at Cli.run (C:\snapshot\lando\build\cli\lib\cli.js:0:0)
    at Object.<anonymous> (C:\snapshot\lando\build\cli\bin\lando.js:0:0)
    at Module._compile (pkg/prelude/bootstrap.js:1254:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:711:10)
    at Module.load (internal/modules/cjs/loader.js:610:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:549:12)
    at Function.Module._load (internal/modules/cjs/loader.js:541:3)
    at Function.Module.runMain (pkg/prelude/bootstrap.js:1309:12)
    at startup (internal/bootstrap/node.js:274:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:608:3)
```

**Tell us generally about your bug**

Brand new pantheon account with a Wordpress site imported from an existing site using their plugin.

Brand new install of Lando.

I'm just trying to get the site down locally to develop against. From what I gather this is a fairly straight-forward use-case.

**Comment by hades200082** [comment]
So after a lot of digging it seems that this is due to a blocked port 2222.

Maybe there should be something in Lando that checks this and reports a more useful error message?

**Comment by pirog** [comment]
@hades200082 we spit back the message pantheon gives us so this might be something pantheon can do better

**Comment by hades200082** [comment]
For the simple `lando init` command that makes sense ... do Pantheon return that huge stack-trace as well?  That was caused by the port blockage too.

**Comment by pirog** [comment]
Stack trace is from Lando, if you scroll up you can see at least some sort of error that is reported in `curl: (1) Protocol "ssh" not supported or disabled in libcurl`. 

However, if that is not printed to `stderr` we generally cannot capture it. 

If that is the actual error then it's failing before Pantheon could hypothetically respond.

**Comment by hades200082** [comment]
Made sure port 2222 was open in my office firewall.

**Comment by reynoldsalec** [comment]
Sounds like the solution for the original issue was port blockage causing an upstream issue with Pantheon. There may be some things we can do in the future to simplify error reporting, but I feel that route may be fraught with peril (trying to predict errors from upstream providers like Pantheon could get tricky, since we can't guarantee stability). Closing for now.

**Comment by hades200082** [comment]
How about, if you can't connect to pantheon showing a friendlier error message than a stack trace?

If port 2222 is blocked then you can't get as far as Pantheon in the first place so it's a network connection error, not a Pantheon error. Therefore a message that better indicates what the problem might be would help other users avoid spending hours trying to get help or debug a stack trace that in the end is nothing to do with the actual problem.

**Comment by lquessenberry** [comment]
I am getting the same error, but I am pretty sure port 2222 is open.

**Comment by cballenar** [comment]
I wanted to report that I ran into the same error (minus the stack trace)

```
Detected that ssh://RANDOMADDRESS@RANDOMADDRESS.drush.in:2222/~/repository.git is a tar archive
Downloading ssh://RANDOMADDRESS@RANDOMADDRESS.drush.in:2222/~/repository.git...
curl: (1) Protocol "ssh" not supported or disabled in libcurl
Killing landoinitmyrepo_init_1 ... done
Removing landoinitmyrepo_init_1 ... done
```

After finding this issue, I tested port 2222 in my machine and in a different docker VM and everything checked out. So I ran the command just in case and it worked without any hiccups 🤔 weird right?

**Comment by cam-spacebar** [comment]
yup, I'm having some issue. but on intel 12th gen 12700H, not m1

**Comment by michaelprflores** [comment]
Hello, I am experiencing this issue via M1 but only for one repo.

**Comment by michaelprflores** [comment]
My solution SSH related. I needed to make sure that my SSH keys were recognized by the repo.
