### ISSUE TITLE
[rc.20] Cannot start service proxy on Windows

### ISSUE THREAD

**Issue by rabauss** [lando/lando#1754]
*v3.0.0-rc.20 on Windows 10 Professional*
Docker 2.1.0.1

Since Docker 2.1 and I think rc.18 or later sometimes I cannot start the proxy.
Then I need to do a full windows reboot and traefik will start afterwards correctly - just docker app restart isn't enough.
removing just the traefik image + container didn't help, too.

Here is the output of the last tries of starting - perhabs you can find out the issue:

```bash
ERROR: for proxy  Cannot start service proxy: driver failed programming external connectivity on endpoint landoproxyhyperion5000gandalfedition_proxy_1 (78ad61ea00b73e6a2b06c9a7356eda3f15fa8e593ed4f7968d0c405db8c1e761): Error starting userland proxy: /forwards/expose/port returned unexpected status: 500
ERROR: Encountered errors while bringing up the project.
warn: Something is wrong with the proxy! Error
warn: Trying to take corrective action...
lando.exe start

Starts your app

Options:
  --clear        Clears the lando tasks cache
                    [boolean]
  --help         Shows lando or delegated command help if applicable
                    [boolean]
  --verbose, -v  Runs with extra verbosity
                      [count]

TypeError: Cannot set property 'verbose' of undefined
    at Cli.module.exports.constructor.handleError (C:\snapshot\lando\build\cli\lib\cli.js:0:0)
    at module.exports.parseToYargs.checkForUpdates.then.lando.bootstrap.then.lando.events.emit.then.then.then.then.then.catch.error (C:\snapshot\lando\build\cli\lib\cli.js:0:0)
From previous event:
    at module.exports.parseToYargs.checkForUpdates.then.lando.bootstrap.then.lando (C:\snapshot\lando\build\cli\lib\cli.js:0:0)
From previous event:
    at module.exports.parseToYargs.checkForUpdates.then (C:\snapshot\lando\build\cli\lib\cli.js:0:0)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
From previous event:
    at Object.handler (C:\snapshot\lando\build\cli\lib\cli.js:0:0)
    at Object.runCommand (C:\snapshot\lando\build\cli\node_modules\yargs\lib\command.js:238:44)
    at Object.parseArgs [as _parseArgs] (C:\snapshot\lando\build\cli\node_modules\yargs\yargs.js:1063:30)
    at Function.get [as argv] (C:\snapshot\lando\build\cli\node_modules\yargs\yargs.js:1004:21)
    at Cli.run (C:\snapshot\lando\build\cli\lib\cli.js:0:0)
    at Object.<anonymous> (C:\snapshot\lando\build\cli\bin\lando.js:0:0)
    at Module._compile (pkg/prelude/bootstrap.js:1254:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:711:10)
    at Module.load (internal/modules/cjs/loader.js:610:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:549:12)
    at Function.Module._load (internal/modules/cjs/loader.js:541:3)
    at Function.Module.runMain (pkg/prelude/bootstrap.js:1309:12)
    at startup (internal/bootstrap/node.js:274:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:608:3)
```

**Comment by rabauss** [comment]
seems to be related to: https://github.com/docker/for-win/issues/2722

**Comment by clessg** [comment]
I've been having this issue on rc.22, Docker for Mac 2.1.4.0

**Comment by rabauss** [comment]
For me the solution is to stop docker desktop + service and then launch docker desktop again 
(see: https://stackoverflow.com/a/57324735)
