### ISSUE TITLE
Unhandled rejection Error: problem parsing null.tooling.cache. Ensure it is valid JSON!

### ISSUE THREAD

**Issue by klonos** [lando/lando#1767]
I was facing some issues with my drush for Backdrop, so I have upgraded from RC17 to RC20, and then `.lndo.site` domains stoped working (#1490). So I removed the `~/.lando` directory, as per suggestion in that issue and also in https://docs.lando.dev/guides/updating-to-rc2.html#removing-lando

Now, things work (`lando start`, `lando stop`, `lando destroy` etc.), but I get this error when running commands like `lando list` and `lando version`:

```bash
Unhandled rejection Error: There was a problem with parsing /Users/name/.lando/cache/null.tooling.cache. Ensure it is valid JSON! Error: ENOENT: no such file or directory, open '/Users/name/.lando/cache/null.tooling.cache'
    at loadCacheFile (/snapshot/lando/build/cli/lib/bootstrap.js:0:0)
    at Object.exports.getTasks (/snapshot/lando/build/cli/lib/bootstrap.js:0:0)
    at lando.bootstrap.then.lando.getApp.init.then (/snapshot/lando/build/cli/bin/lando.js:0:0)
From previous event:
    at lando.bootstrap.then.lando (/snapshot/lando/build/cli/bin/lando.js:0:0)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
From previous event:
    at Object.<anonymous> (/snapshot/lando/build/cli/bin/lando.js:0:0)
    at Module._compile (pkg/prelude/bootstrap.js:1254:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:711:10)
    at Module.load (internal/modules/cjs/loader.js:610:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:549:12)
    at Function.Module._load (internal/modules/cjs/loader.js:541:3)
    at Function.Module.runMain (pkg/prelude/bootstrap.js:1309:12)
    at startup (internal/bootstrap/node.js:274:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:608:3)
```

...heres a listing of my `.lando/cache` directory:

```bash
total 80
drwxr-xr-x@ 11 greg  staff   352  1 Sep 23:43 .
drwxr-xr-x@ 10 greg  staff   320  1 Sep 00:27 ..
-rw-r--r--@  1 greg  staff  1532  1 Sep 23:43 .compose.cache
-rw-r--r--@  1 greg  staff  1112  1 Sep 23:43 .tooling.cache
-rw-r--r--@  1 greg  staff    21  1 Sep 00:42 2382.build.lock
-rw-r--r--@  1 greg  staff  1735  1 Sep 07:05 2382.compose.cache
-rw-r--r--@  1 greg  staff  1112  1 Sep 07:05 2382.tooling.cache
-rw-r--r--   1 greg  staff  7138  1 Sep 23:43 _.tasks.cache
-rw-r--r--@  1 greg  staff    39  1 Sep 00:24 id
-rw-r--r--@  1 greg  staff    28  1 Sep 23:33 proxyCache
```

**Tell us about your setup**

v3.0.0-rc.20 on Mac OS 10.14.6

**Tell us about your `.lando.yml`**

N/A ...happens with commands like `lando version`.

**Tell us about the command you were running**

`lando list`, `lando version`

**Comment by klonos** [comment]
...I am suspecting that something went wrong with the installation of RC20 over RC17. Is there an easy fix to this? I mean, this `null.tooling.cache` that lando expects to find is obviously not there. Should I create a blank JSON file there?

**Comment by klonos** [comment]
...OK, here's what I have tried:

```bash
cd ~/.lando/cache
cp .tooling.cache null.tooling.cache
lando version
v3.0.0-rc.20
```

So `lando version` does not throw the error any more; but obviously I get nothing useful out of `lando list`:

```bash
lando list
{
  _global_: [
    {
      service: 'proxy',
      name: 'landoproxyhyperion5000gandalfedition_proxy_1',
      app: '_global_',
      src: 'unknown',
      kind: 'service',
      status: 'Up 24 hours'
    }
  ]
}
```

After that, I run `lando --clear`, which got me back to the initial situation with the error I reported:

```bash
lando --clear
Lando has cleared the tasks cache!

lando list
Unhandled rejection Error: There was a problem with parsing /Users/name/.lando/cache/null.tooling.cache. Ensure it is valid JSON! Error: ENOENT: no such file or directory, open '/Users/name/.lando/cache/null.tooling.cache'
    at loadCacheFile (/snapshot/lando/build/cli/lib/bootstrap.js:0:0)
    at Object.exports.getTasks (/snapshot/lando/build/cli/lib/bootstrap.js:0:0)
    at lando.bootstrap.then.lando.getApp.init.then (/snapshot/lando/build/cli/bin/lando.js:0:0)
From previous event:
    at lando.bootstrap.then.lando (/snapshot/lando/build/cli/bin/lando.js:0:0)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
From previous event:
    at Object.<anonymous> (/snapshot/lando/build/cli/bin/lando.js:0:0)
    at Module._compile (pkg/prelude/bootstrap.js:1254:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:711:10)
    at Module.load (internal/modules/cjs/loader.js:610:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:549:12)
    at Function.Module._load (internal/modules/cjs/loader.js:541:3)
    at Function.Module.runMain (pkg/prelude/bootstrap.js:1309:12)
    at startup (internal/bootstrap/node.js:274:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:608:3)
```

...so this time I tried with an empty file, instead of copying `.tooling.cache`:

```bash
touch null.tooling.cache

lando list
pkg/prelude/bootstrap.js:1254
      return wrapper.apply(this.exports, args);
                     ^

Error: There was a problem with parsing /Users/greg/.lando/cache/null.tooling.cache. Ensure it is valid JSON! SyntaxError: Unexpected end of JSON input
    at loadCacheFile (/snapshot/lando/build/cli/lib/bootstrap.js:0:0)
    at Object.exports.getTasks (/snapshot/lando/build/cli/lib/bootstrap.js:0:0)
    at Object.<anonymous> (/snapshot/lando/build/cli/bin/lando.js:0:0)
    at Module._compile (pkg/prelude/bootstrap.js:1254:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:711:10)
    at Module.load (internal/modules/cjs/loader.js:610:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:549:12)
    at Function.Module._load (internal/modules/cjs/loader.js:541:3)
    at Function.Module.runMain (pkg/prelude/bootstrap.js:1309:12)
    at startup (internal/bootstrap/node.js:274:19)
```

**Comment by jonacornejo** [comment]
Hi, I had the same issue just now and apparently I only missed adding the **name** on my `.lando.yml` file.

I started out the file like:
```
recipe: wordpress
config:
  webroot: web
```

And changed it to
```
name: projectname
recipe: wordpress
config:
  webroot: web
```

**Comment by pirog** [comment]
@klonos i think the likely problem here is what @jonacornejo has flagged

**Comment by drupov** [comment]
I am getting the same error as @klonos and I do have the `name` key in all my lando-files correctly though.

There is no `null.tooling.cache` file in `~/.lando/cache`. Very similar to the comments of @klonos.

I am on Ubuntu 19.04., v3.0.0-rc.22

What's strange is that if a do a simple `lando version` outside of a lando project it throws the error. Once I execute that same command in a folder where a `.lando.yml` file is present (or above) it behaves normally.

**Comment by remyjimjim** [comment]
I did the following to fix this on my mac:
-  Since it looks like the all the 'tooling.cache' files are the same boilerplate json, I just copied an old one over to the name of the one it was saying was missing, as in:
    -  cp "/Users/human/.lando/cache/my-new-site.tooling.cache" "/Users/human/.lando/cache/Social Icon Test.tooling.cache"

Lando was complaining about the "Social Icon Test.tooling.cache" file being non existent so I copied another file and renamed it as the command above indicates.  Hope this helps.  Cheers

**Comment by remyjimjim** [comment]
Whoops, I misspoke, the above comment resolved the error message but the site stopped launching and long story short was that the "name: Social Icon Test" should not have spaces, so I renamed it "name: social-icon-test" and created a database named social_icon_test" (apparently one can't have dashes in the db name".  This worked to the point that I could run lando start by then during the Drupal install Drupal couldn't find "Fatal error: Class 'Drupal\image\PathProcessor\PathProcessorImageStyles' not found in /app/web/modules/contrib/wwu_clean_file_urls/src/PathProcessor/CleanPathProcessorImageStyles.php on line 8".  So I'm still screwed.  All this was after reinstalling lando.  Not good, not good at all.  Has anybody heard good things about Grav?   Are they true?  I'll take my answer off the air.  Cheers

**Comment by greatbeliever** [comment]
Thanks, @remyjimjim, for flagging that space characters in the .lando.yml 'name' variable are a problem.

I had a name like this in .lando.yml:

name: 'ABC XYZ'

... and this had worked for a while, but suddenly started to cause the tooling/cache error listed here.

Not sure why this is suddenly a problem, but I'm still running the same versions of Lando and Docker as before. (I.e. the version of Docker that comes with my current version of Lando)

Anyway, I remove the blank space from the name, then rebuilt lando, and now the local site is working again.

**Comment by pjoulot** [comment]
I had that name "STARTER" and it was failing too but it was good after changing it to "starter". Uppercase might be a problem as well.

**Comment by pirog** [comment]
should be a fix for this in next release!

**Comment by tebb** [comment]
Doesn't seem to like any capitals, eg this 'S' either:

`name: liveSitename`

v3.0.23

**Comment by 11121A0441** [comment]
> I did the following to fix this on my mac:
> 
> * Since it looks like the all the 'tooling.cache' files are the same boilerplate json, I just copied an old one over to the name of the one it was saying was missing, as in:
>   
>   * cp "/Users/human/.lando/cache/my-new-site.tooling.cache" "/Users/human/.lando/cache/Social Icon Test.tooling.cache"
> 
> Lando was complaining about the "Social Icon Test.tooling.cache" file being non existent so I copied another file and renamed it as the command above indicates. Hope this helps. Cheers

I fixed by replacing  the C:\Users\human\.lando\cache\_.tasks.cache with one of my friends file which is having 10KB in size, previously it was showing 0KB.

**Comment by lquessenberry** [comment]
Here from DrupalLand! Hello. I would like to confirm that having an all lowercase name for my lando name solved this for me. I am building a Drupal Repo for the public to test and this was the final brick in the wall. So thanks Google for landing me here in Lando's issue queue. I thought this was a gitpod issue initially and I will update there as well.

https://community.gitpod.io/t/lando-wont-start/3908/3

![bitmoji](https://sdk.bitmoji.com/render/panel/7e3bc453-64fb-4a34-bcaa-481724e5d3d9-c550f9f8-a8fd-487f-9609-bc173830b1e9-v1.png?transparent=1&palette=1&width=246)![bitmoji](https://sdk.bitmoji.com/render/panel/7e3bc453-64fb-4a34-bcaa-481724e5d3d9-c550f9f8-a8fd-487f-9609-bc173830b1e9-v1.png?transparent=1&palette=1&width=246)

**Comment by jonpugh** [comment]
FWIW:

I found this issue after googling, I was getting an error like this for every call to `lando` even after `lando --clear` and removing `~/.lando` dir.

Here's what happened:

- I was setting up a new project. I hit `lando start` and immediately CTRL-C because I made a typo in the app `name`.
- I changed the `.lando.yml` `name` property. Then ran `lando start` again to the huge error below. `lando ANYTHING` also returned the error 
- Outside my project folder, `lando`  worked. `lando --clear` worked. But go back into the project and still errors.
- I change the `name` back to what it was when I ran `lando start` and everything started working again. I ran `lando destroy` to clear out the original name'd containers and then `lando start` again on the new name and everything is fine.

Here's the error for future googleers:

```
Unhandled rejection Error: There was a problem with parsing /home/jon/.lando/cache/UNHCRGF.tooling.cache. Ensure it is valid JSON! Error: ENOENT: no such file or directory, open '/home/jon/.lando/cache/UNHCRGF.tooling.cache'
    at loadCacheFile (/snapshot/cli/node_modules/@lando/core/lib/bootstrap.js)
    at Object.getTasks (/snapshot/cli/node_modules/@lando/core/lib/bootstrap.js)
From previous event:
    at /snapshot/cli/bin/lando.js
    at processImmediate (node:internal/timers:466:21)
From previous event:
    at Object.<anonymous> (/snapshot/cli/bin/lando.js)
    at Module._compile (pkg/prelude/bootstrap.js:1887:22)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.runMain (pkg/prelude/bootstrap.js:1940:12)
    at node:internal/main/run_main_module:17:47
```

**Comment by afeijo** [comment]
I just faced this problem after copying .lando.yml from another project, the problem was that I renamed the name: oldproject to **name: new project** (with space)

removing the space fixed the problem
