### ISSUE TITLE
404 on lando pull

### ISSUE THREAD

**Issue by merlinpatt** [lando/lando#1769]
**Tell us about your setup**

What is your lando version and operating system? **(note that the older your version the less likely we are to reply)**

*v3.0.0-rc.20 on MacOS Mojave 10.14.5*

**Tell us about your `.lando.yml`**

Paste in the contents of your `.lando.yml` this is **SUPER HELPFUL** for us.

```yml
name: some-name
recipe: pantheon
config:
  framework: wordpress
  site: somesite
  id: 437a28ac-10fb-4cab-8652-637b2d924250
```

`pantheon.yml`

```yml
api_version: 1
php_version: 7.2
```

**Tell us about the command you were running**

```bash
lando pull
```

**Tell us about the error you got**

Rerun the command that produced your error in `debug` mode. Note that `debug` mode is run like this `lando command -vvv`. Paste in the error and the `~100` lines that proceeded it.

*Short Error*

```bash 
Error: GET request to https://terminus.pantheon.io/api/sites/437a28ac-10fb-4cab-8652-637b2d924250/environments failed with code 404: Not Found. The server responded with the message Not found.
.
    at Promise.retry.request.(anonymous function).then.catch.err (/snapshot/lando/build/cli/plugins/lando-pantheon/lib/client.js:0:0)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

*Long Error*

```bash
debug: Emitting event ready
debug: Event ready has 2 listeners
debug: Emitting event pre-engine-up
debug: Event pre-engine-up has 0 listeners
debug: Emitting event post-engine-up
debug: Event post-engine-up has 0 listeners
debug: Emitting event pre-engine-list
debug: Event pre-engine-list has 0 listeners
debug: Emitting event post-engine-list
debug: Event post-engine-list has 0 listeners
debug: Emitting event pre-engine-up
debug: Event pre-engine-up has 0 listeners
debug: Emitting event pre-engine-up
debug: Event pre-engine-up has 0 listeners
debug: Emitting event pre-engine-up
debug: Event pre-engine-up has 0 listeners
debug: Emitting event post-engine-up
debug: Event post-engine-up has 0 listeners
debug: Emitting event post-engine-up
debug: Event post-engine-up has 0 listeners
debug: Emitting event post-engine-up
debug: Event post-engine-up has 0 listeners
debug: Emitting event pre-engine-scan
debug: Event pre-engine-scan has 0 listeners
debug: Emitting event pre-engine-scan
debug: Event pre-engine-scan has 0 listeners
debug: Emitting event pre-engine-scan
debug: Event pre-engine-scan has 0 listeners
debug: Emitting event post-engine-scan
debug: Event post-engine-scan has 0 listeners
debug: Emitting event post-engine-scan
debug: Event post-engine-scan has 0 listeners
debug: Emitting event post-engine-scan
debug: Event post-engine-scan has 0 listeners
info: Making post request to authorize,machine-token
debug: Request data: {"machine_token":"hQMixMEtEpa198qOOV5ppPVL-94RlEJhPJ7s9PTAlyhVW","client":"terminus"}
debug: Request options: {"headers":{"User-Agent":"Terminus/Lando"}}.
verbose: Response received: {"session":"5671dacb-cc4a-42d2-ae77-8dbae358c2e8:af1598c2-cd81-11e9-a545-42010a8001a4:syCJCcNMs6EQwIDySJmHv","expires_at":1569848448,"user_id":"5671dacb-cc4a-42d2-ae77-8dbae358c2e8"}.
info: Making get request to sites,437a28ac-10fb-4cab-8652-637b2d924250,environments
debug: Request data: {}
debug: Request options: {}.
error: Error: GET request to https://terminus.pantheon.io/api/sites/437a28ac-10fb-4cab-8652-637b2d924250/environments failed with code 404: Not Found. The server responded with the message Not found.
.
    at Promise.retry.request.(anonymous function).then.catch.err (/snapshot/lando/build/cli/plugins/lando-pantheon/lib/client.js:0:0)
    at process._tickCallback (internal/process/next_tick.js:68:7)
debug: Logging metrics data {"context":"local","devMode":false,"instance":"3b9a23326334970129199f3ab54196fe77410e22","nodeVersion":"v10.4.1","mode":"cli","os":{"type":"Darwin","platform":"darwin","release":"18.6.0","arch":"x64"},"product":"lando","version":"3.0.0-rc.20","message":"GET request to https://terminus.pantheon.io/api/sites/437a28ac-10fb-4cab-8652-637b2d924250/environments failed with code 404: Not Found. The server responded with the message Not found.\n.","stack":"Error: GET request to https://terminus.pantheon.io/api/sites/437a28ac-10fb-4cab-8652-637b2d924250/environments failed with code 404: Not Found. The server responded with the message Not found.\n.\n    at Promise.retry.request.(anonymous function).then.catch.err (/snapshot/lando/build/cli/plugins/lando-pantheon/lib/client.js:0:0)\n    at process._tickCallback (internal/process/next_tick.js:68:7)","action":"error","created":"2019-09-02T13:00:50.635Z"}
```

**Tell us generally about your bug**

I tried `lando pull` and hit this immediately even after uninstalling lando, restarting my computer, and installing lando again.

Please detail the steps we can take to replicate this bug. Be as detailed as possible.

*Example:*

```bash
1. lando pull
```

**Tell us more**

This bug prevents me from aligning my local version's DB with a remote version's DB which makes development more difficult.

**Comment by pirog** [comment]
@merlinpatt this is an error that is being thrown by pantheon, lando is just reporting it back to you.

**Comment by GabyC0** [comment]
Hello, I've been receiving this error and was wondering if anyone was able to resolve it and how you went about doing it?
