### ISSUE TITLE
Renaming container causes error on rebuild, start, etc.

### ISSUE THREAD

**Issue by kcolwell** [lando/lando#1791]
**Tell us about your setup**

What is your lando version and operating system? **(note that the older your version the less likely we are to reply)**

Lando version: v3.0.0-rc.20
Macintosh: 10.14.6 (Darwin Kernel Version 18.7.0)

**Tell us about your `.lando.yml`**

```
name: dr
recipe: drupal8
config:
  webroot: htdocs
services:
  node_service:
    type: node
    build:
      - npm install
    port: 3000 
    globals:
      node: latest
      npm: latest               
      nodemon: latest
      react: latest
    command: npm start --prefix app/src/        
  express_service:
    type: node
    build:
      - npm install
    port: 8080
    globals:
      node: latest
      npm: latest               
      express: latest     
      nodemon: latest    
    command: node app/src/server.js 
proxy:
  node_service:
    - node.lndo.site:3000
  express_service:
    - express.lndo.site:8080    
tooling:
  npm:
    service: node_service
  node:
    service: express_service     
  npx:
    service: node_service       
  express:
    service: express_service
    
```
```
Changed name of services in .lando.yml
lando restart or lando rebuild -y

```

**Tell us about the error you got**

```
info: Starting app name dr!
debug: Engine is up.
debug: Emitting event post-engine-up
debug: Event post-engine-up has 0 listeners
debug: Emitting event pre-engine-list
debug: Event pre-engine-list has 0 listeners
debug: Emitting event post-engine-list
debug: Event post-engine-list has 0 listeners
debug: Logging metrics data {"context":"local","devMode":false,"instance":"3b3d9eaf0028bcd8b613231c24e711fad0b98893","nodeVersion":"v10.4.1","mode":"cli","os":{"type":"Darwin","platform":"darwin","release":"18.7.0","arch":"x64"},"product":"lando","version":"3.0.0-rc.20","app":"e735cc076ffbf2dd24765376f432cd2448924718","type":"drupal8","services":["php:7.2","mysql","node","node"],"action":"start","created":"2019-09-16T13:24:30.047Z"}
debug: Emitting event pre-start
debug: Event pre-start has 2 listeners
debug: Emitting event pre-engine-up
debug: Event pre-engine-up has 0 listeners
debug: Emitting event post-engine-up
debug: Event post-engine-up has 0 listeners
debug: Emitting event pre-engine-list
debug: Event pre-engine-list has 0 listeners
debug: Emitting event post-engine-list
debug: Event post-engine-list has 0 listeners
debug: Emitting event pre-engine-up
debug: Event pre-engine-up has 0 listeners
debug: Emitting event post-engine-up
debug: Event post-engine-up has 0 listeners
debug: Emitting event pre-engine-start
debug: Event pre-engine-start has 4 listeners
verbose: Running ["/Applications/Docker.app/Contents/Resources/bin/docker-compose","--project-name","landoproxyhyperion5000gandalfedition","--file","/Users/ken.colwell/.lando/proxy/proxy-0.yml","--file","/Users/ken.colwell/.lando/proxy/proxy-1.yml","--file","/Users/ken.colwell/.lando/proxy/proxy-2.yml","--file","/Users/ken.colwell/.lando/proxy/proxy-3.yml","--file","/Users/ken.colwell/.lando/proxy/proxy-4.yml","up","--detach","--remove-orphans","proxy"] in /Users/ken.colwell/Documents/websites/d8 with options {"mode":"collect","detached":false}
debug: With stdio={"stdio":"inherit"}, mode=collect, detached=false, cwd=/Users/ken.colwell/Documents/websites/d8
landoproxyhyperion5000gandalfedition_proxy_1 is up-to-date
verbose: /Applications/Docker.app/Contents/Resources/bin/docker-compose,--project-name,landoproxyhyperion5000gandalfedition,--file,/Users/ken.colwell/.lando/proxy/proxy-0.yml,--file,/Users/ken.colwell/.lando/proxy/proxy-1.yml,--file,/Users/ken.colwell/.lando/proxy/proxy-2.yml,--file,/Users/ken.colwell/.lando/proxy/proxy-3.yml,--file,/Users/ken.colwell/.lando/proxy/proxy-4.yml,up,--detach,--remove-orphans,proxy finished with code 0
debug: Emitting event post-engine-start
debug: Event post-engine-start has 0 listeners
verbose: App dr has proxy compose files ["/Users/ken.colwell/.lando/compose/dr/proxy-0.yml","/Users/ken.colwell/.lando/compose/dr/proxy-1.yml","/Users/ken.colwell/.lando/compose/dr/proxy-2.yml"]
debug: Emitting event pre-engine-up
debug: Event pre-engine-up has 0 listeners
debug: Emitting event post-engine-up
debug: Event post-engine-up has 0 listeners
debug: Emitting event pre-engine-run
debug: Event pre-engine-run has 0 listeners
verbose: Running ["/Applications/Docker.app/Contents/Resources/bin/docker-compose","--project-name","dr","--file","/Users/ken.colwell/.lando/compose/dr/globals-0.yml","--file","/Users/ken.colwell/.lando/compose/dr/appserver-0.yml","--file","/Users/ken.colwell/.lando/compose/dr/appserver-1.yml","--file","/Users/ken.colwell/.lando/compose/dr/appserver-2.yml","--file","/Users/ken.colwell/.lando/compose/dr/appserver-3.yml","--file","/Users/ken.colwell/.lando/compose/dr/database-0.yml","--file","/Users/ken.colwell/.lando/compose/dr/database-1.yml","--file","/Users/ken.colwell/.lando/compose/dr/database-2.yml","--file","/Users/ken.colwell/.lando/compose/dr/database-3.yml","--file","/Users/ken.colwell/.lando/compose/dr/database-4.yml","--file","/Users/ken.colwell/.lando/compose/dr/database-5.yml","--file","/Users/ken.colwell/.lando/compose/dr/node_service-0.yml","--file","/Users/ken.colwell/.lando/compose/dr/node_service-1.yml","--file","/Users/ken.colwell/.lando/compose/dr/node_service-2.yml","--file","/Users/ken.colwell/.lando/compose/dr/node_service-3.yml","--file","/Users/ken.colwell/.lando/compose/dr/express_service-0.yml","--file","/Users/ken.colwell/.lando/compose/dr/express_service-1.yml","--file","/Users/ken.colwell/.lando/compose/dr/express_service-2.yml","--file","/Users/ken.colwell/.lando/compose/dr/express_service-3.yml","--file","/Users/ken.colwell/.lando/compose/dr/proxy-0.yml","--file","/Users/ken.colwell/.lando/compose/dr/proxy-1.yml","--file","/Users/ken.colwell/.lando/compose/dr/proxy-2.yml","up","--detach","--no-recreate","--remove-orphans","express"] in /Users/ken.colwell/Documents/websites/d8 with options {"mode":"collect","detached":false}
debug: With stdio={"stdio":"inherit"}, mode=collect, detached=false, cwd=/Users/ken.colwell/Documents/websites/d8
ERROR: No such service: express
verbose: /Applications/Docker.app/Contents/Resources/bin/docker-compose,--project-name,dr,--file,/Users/ken.colwell/.lando/compose/dr/globals-0.yml,--file,/Users/ken.colwell/.lando/compose/dr/appserver-0.yml,--file,/Users/ken.colwell/.lando/compose/dr/appserver-1.yml,--file,/Users/ken.colwell/.lando/compose/dr/appserver-2.yml,--file,/Users/ken.colwell/.lando/compose/dr/appserver-3.yml,--file,/Users/ken.colwell/.lando/compose/dr/database-0.yml,--file,/Users/ken.colwell/.lando/compose/dr/database-1.yml,--file,/Users/ken.colwell/.lando/compose/dr/database-2.yml,--file,/Users/ken.colwell/.lando/compose/dr/database-3.yml,--file,/Users/ken.colwell/.lando/compose/dr/database-4.yml,--file,/Users/ken.colwell/.lando/compose/dr/database-5.yml,--file,/Users/ken.colwell/.lando/compose/dr/node_service-0.yml,--file,/Users/ken.colwell/.lando/compose/dr/node_service-1.yml,--file,/Users/ken.colwell/.lando/compose/dr/node_service-2.yml,--file,/Users/ken.colwell/.lando/compose/dr/node_service-3.yml,--file,/Users/ken.colwell/.lando/compose/dr/express_service-0.yml,--file,/Users/ken.colwell/.lando/compose/dr/express_service-1.yml,--file,/Users/ken.colwell/.lando/compose/dr/express_service-2.yml,--file,/Users/ken.colwell/.lando/compose/dr/express_service-3.yml,--file,/Users/ken.colwell/.lando/compose/dr/proxy-0.yml,--file,/Users/ken.colwell/.lando/compose/dr/proxy-1.yml,--file,/Users/ken.colwell/.lando/compose/dr/proxy-2.yml,up,--detach,--no-recreate,--remove-orphans,express finished with code 1
verbose: Running ["/Applications/Docker.app/Contents/Resources/bin/docker-compose","--project-name","dr","--file","/Users/ken.colwell/.lando/compose/dr/globals-0.yml","--file","/Users/ken.colwell/.lando/compose/dr/appserver-0.yml","--file","/Users/ken.colwell/.lando/compose/dr/appserver-1.yml","--file","/Users/ken.colwell/.lando/compose/dr/appserver-2.yml","--file","/Users/ken.colwell/.lando/compose/dr/appserver-3.yml","--file","/Users/ken.colwell/.lando/compose/dr/database-0.yml","--file","/Users/ken.colwell/.lando/compose/dr/database-1.yml","--file","/Users/ken.colwell/.lando/compose/dr/database-2.yml","--file","/Users/ken.colwell/.lando/compose/dr/database-3.yml","--file","/Users/ken.colwell/.lando/compose/dr/database-4.yml","--file","/Users/ken.colwell/.lando/compose/dr/database-5.yml","--file","/Users/ken.colwell/.lando/compose/dr/node_service-0.yml","--file","/Users/ken.colwell/.lando/compose/dr/node_service-1.yml","--file","/Users/ken.colwell/.lando/compose/dr/node_service-2.yml","--file","/Users/ken.colwell/.lando/compose/dr/node_service-3.yml","--file","/Users/ken.colwell/.lando/compose/dr/express_service-0.yml","--file","/Users/ken.colwell/.lando/compose/dr/express_service-1.yml","--file","/Users/ken.colwell/.lando/compose/dr/express_service-2.yml","--file","/Users/ken.colwell/.lando/compose/dr/express_service-3.yml","--file","/Users/ken.colwell/.lando/compose/dr/proxy-0.yml","--file","/Users/ken.colwell/.lando/compose/dr/proxy-1.yml","--file","/Users/ken.colwell/.lando/compose/dr/proxy-2.yml","up","--detach","--no-recreate","--remove-orphans","express"] in /Users/ken.colwell/Documents/websites/d8 with options {"mode":"collect","detached":false}
debug: With stdio={"stdio":"inherit"}, mode=collect, detached=false, cwd=/Users/ken.colwell/Documents/websites/d8
ERROR: No such service: express
verbose: /Applications/Docker.app/Contents/Resources/bin/docker-compose,--project-name,dr,--file,/Users/ken.colwell/.lando/compose/dr/globals-0.yml,--file,/Users/ken.colwell/.lando/compose/dr/appserver-0.yml,--file,/Users/ken.colwell/.lando/compose/dr/appserver-1.yml,--file,/Users/ken.colwell/.lando/compose/dr/appserver-2.yml,--file,/Users/ken.colwell/.lando/compose/dr/appserver-3.yml,--file,/Users/ken.colwell/.lando/compose/dr/database-0.yml,--file,/Users/ken.colwell/.lando/compose/dr/database-1.yml,--file,/Users/ken.colwell/.lando/compose/dr/database-2.yml,--file,/Users/ken.colwell/.lando/compose/dr/database-3.yml,--file,/Users/ken.colwell/.lando/compose/dr/database-4.yml,--file,/Users/ken.colwell/.lando/compose/dr/database-5.yml,--file,/Users/ken.colwell/.lando/compose/dr/node_service-0.yml,--file,/Users/ken.colwell/.lando/compose/dr/node_service-1.yml,--file,/Users/ken.colwell/.lando/compose/dr/node_service-2.yml,--file,/Users/ken.colwell/.lando/compose/dr/node_service-3.yml,--file,/Users/ken.colwell/.lando/compose/dr/express_service-0.yml,--file,/Users/ken.colwell/.lando/compose/dr/express_service-1.yml,--file,/Users/ken.colwell/.lando/compose/dr/express_service-2.yml,--file,/Users/ken.colwell/.lando/compose/dr/express_service-3.yml,--file,/Users/ken.colwell/.lando/compose/dr/proxy-0.yml,--file,/Users/ken.colwell/.lando/compose/dr/proxy-1.yml,--file,/Users/ken.colwell/.lando/compose/dr/proxy-2.yml,up,--detach,--no-recreate,--remove-orphans,express finished with code 1
verbose: Running ["/Applications/Docker.app/Contents/Resources/bin/docker-compose","--project-name","dr","--file","/Users/ken.colwell/.lando/compose/dr/globals-0.yml","--file","/Users/ken.colwell/.lando/compose/dr/appserver-0.yml","--file","/Users/ken.colwell/.lando/compose/dr/appserver-1.yml","--file","/Users/ken.colwell/.lando/compose/dr/appserver-2.yml","--file","/Users/ken.colwell/.lando/compose/dr/appserver-3.yml","--file","/Users/ken.colwell/.lando/compose/dr/database-0.yml","--file","/Users/ken.colwell/.lando/compose/dr/database-1.yml","--file","/Users/ken.colwell/.lando/compose/dr/database-2.yml","--file","/Users/ken.colwell/.lando/compose/dr/database-3.yml","--file","/Users/ken.colwell/.lando/compose/dr/database-4.yml","--file","/Users/ken.colwell/.lando/compose/dr/database-5.yml","--file","/Users/ken.colwell/.lando/compose/dr/node_service-0.yml","--file","/Users/ken.colwell/.lando/compose/dr/node_service-1.yml","--file","/Users/ken.colwell/.lando/compose/dr/node_service-2.yml","--file","/Users/ken.colwell/.lando/compose/dr/node_service-3.yml","--file","/Users/ken.colwell/.lando/compose/dr/express_service-0.yml","--file","/Users/ken.colwell/.lando/compose/dr/express_service-1.yml","--file","/Users/ken.colwell/.lando/compose/dr/express_service-2.yml","--file","/Users/ken.colwell/.lando/compose/dr/express_service-3.yml","--file","/Users/ken.colwell/.lando/compose/dr/proxy-0.yml","--file","/Users/ken.colwell/.lando/compose/dr/proxy-1.yml","--file","/Users/ken.colwell/.lando/compose/dr/proxy-2.yml","up","--detach","--no-recreate","--remove-orphans","express"] in /Users/ken.colwell/Documents/websites/d8 with options {"mode":"collect","detached":false}
debug: With stdio={"stdio":"inherit"}, mode=collect, detached=false, cwd=/Users/ken.colwell/Documents/websites/d8
ERROR: No such service: express
verbose: /Applications/Docker.app/Contents/Resources/bin/docker-compose,--project-name,dr,--file,/Users/ken.colwell/.lando/compose/dr/globals-0.yml,--file,/Users/ken.colwell/.lando/compose/dr/appserver-0.yml,--file,/Users/ken.colwell/.lando/compose/dr/appserver-1.yml,--file,/Users/ken.colwell/.lando/compose/dr/appserver-2.yml,--file,/Users/ken.colwell/.lando/compose/dr/appserver-3.yml,--file,/Users/ken.colwell/.lando/compose/dr/database-0.yml,--file,/Users/ken.colwell/.lando/compose/dr/database-1.yml,--file,/Users/ken.colwell/.lando/compose/dr/database-2.yml,--file,/Users/ken.colwell/.lando/compose/dr/database-3.yml,--file,/Users/ken.colwell/.lando/compose/dr/database-4.yml,--file,/Users/ken.colwell/.lando/compose/dr/database-5.yml,--file,/Users/ken.colwell/.lando/compose/dr/node_service-0.yml,--file,/Users/ken.colwell/.lando/compose/dr/node_service-1.yml,--file,/Users/ken.colwell/.lando/compose/dr/node_service-2.yml,--file,/Users/ken.colwell/.lando/compose/dr/node_service-3.yml,--file,/Users/ken.colwell/.lando/compose/dr/express_service-0.yml,--file,/Users/ken.colwell/.lando/compose/dr/express_service-1.yml,--file,/Users/ken.colwell/.lando/compose/dr/express_service-2.yml,--file,/Users/ken.colwell/.lando/compose/dr/express_service-3.yml,--file,/Users/ken.colwell/.lando/compose/dr/proxy-0.yml,--file,/Users/ken.colwell/.lando/compose/dr/proxy-1.yml,--file,/Users/ken.colwell/.lando/compose/dr/proxy-2.yml,up,--detach,--no-recreate,--remove-orphans,express finished with code 1
verbose: Running ["/Applications/Docker.app/Contents/Resources/bin/docker-compose","--project-name","dr","--file","/Users/ken.colwell/.lando/compose/dr/globals-0.yml","--file","/Users/ken.colwell/.lando/compose/dr/appserver-0.yml","--file","/Users/ken.colwell/.lando/compose/dr/appserver-1.yml","--file","/Users/ken.colwell/.lando/compose/dr/appserver-2.yml","--file","/Users/ken.colwell/.lando/compose/dr/appserver-3.yml","--file","/Users/ken.colwell/.lando/compose/dr/database-0.yml","--file","/Users/ken.colwell/.lando/compose/dr/database-1.yml","--file","/Users/ken.colwell/.lando/compose/dr/database-2.yml","--file","/Users/ken.colwell/.lando/compose/dr/database-3.yml","--file","/Users/ken.colwell/.lando/compose/dr/database-4.yml","--file","/Users/ken.colwell/.lando/compose/dr/database-5.yml","--file","/Users/ken.colwell/.lando/compose/dr/node_service-0.yml","--file","/Users/ken.colwell/.lando/compose/dr/node_service-1.yml","--file","/Users/ken.colwell/.lando/compose/dr/node_service-2.yml","--file","/Users/ken.colwell/.lando/compose/dr/node_service-3.yml","--file","/Users/ken.colwell/.lando/compose/dr/express_service-0.yml","--file","/Users/ken.colwell/.lando/compose/dr/express_service-1.yml","--file","/Users/ken.colwell/.lando/compose/dr/express_service-2.yml","--file","/Users/ken.colwell/.lando/compose/dr/express_service-3.yml","--file","/Users/ken.colwell/.lando/compose/dr/proxy-0.yml","--file","/Users/ken.colwell/.lando/compose/dr/proxy-1.yml","--file","/Users/ken.colwell/.lando/compose/dr/proxy-2.yml","up","--detach","--no-recreate","--remove-orphans","express"] in /Users/ken.colwell/Documents/websites/d8 with options {"mode":"collect","detached":false}
debug: With stdio={"stdio":"inherit"}, mode=collect, detached=false, cwd=/Users/ken.colwell/Documents/websites/d8
ERROR: No such service: express
verbose: /Applications/Docker.app/Contents/Resources/bin/docker-compose,--project-name,dr,--file,/Users/ken.colwell/.lando/compose/dr/globals-0.yml,--file,/Users/ken.colwell/.lando/compose/dr/appserver-0.yml,--file,/Users/ken.colwell/.lando/compose/dr/appserver-1.yml,--file,/Users/ken.colwell/.lando/compose/dr/appserver-2.yml,--file,/Users/ken.colwell/.lando/compose/dr/appserver-3.yml,--file,/Users/ken.colwell/.lando/compose/dr/database-0.yml,--file,/Users/ken.colwell/.lando/compose/dr/database-1.yml,--file,/Users/ken.colwell/.lando/compose/dr/database-2.yml,--file,/Users/ken.colwell/.lando/compose/dr/database-3.yml,--file,/Users/ken.colwell/.lando/compose/dr/database-4.yml,--file,/Users/ken.colwell/.lando/compose/dr/database-5.yml,--file,/Users/ken.colwell/.lando/compose/dr/node_service-0.yml,--file,/Users/ken.colwell/.lando/compose/dr/node_service-1.yml,--file,/Users/ken.colwell/.lando/compose/dr/node_service-2.yml,--file,/Users/ken.colwell/.lando/compose/dr/node_service-3.yml,--file,/Users/ken.colwell/.lando/compose/dr/express_service-0.yml,--file,/Users/ken.colwell/.lando/compose/dr/express_service-1.yml,--file,/Users/ken.colwell/.lando/compose/dr/express_service-2.yml,--file,/Users/ken.colwell/.lando/compose/dr/express_service-3.yml,--file,/Users/ken.colwell/.lando/compose/dr/proxy-0.yml,--file,/Users/ken.colwell/.lando/compose/dr/proxy-1.yml,--file,/Users/ken.colwell/.lando/compose/dr/proxy-2.yml,up,--detach,--no-recreate,--remove-orphans,express finished with code 1
verbose: Running ["/Applications/Docker.app/Contents/Resources/bin/docker-compose","--project-name","dr","--file","/Users/ken.colwell/.lando/compose/dr/globals-0.yml","--file","/Users/ken.colwell/.lando/compose/dr/appserver-0.yml","--file","/Users/ken.colwell/.lando/compose/dr/appserver-1.yml","--file","/Users/ken.colwell/.lando/compose/dr/appserver-2.yml","--file","/Users/ken.colwell/.lando/compose/dr/appserver-3.yml","--file","/Users/ken.colwell/.lando/compose/dr/database-0.yml","--file","/Users/ken.colwell/.lando/compose/dr/database-1.yml","--file","/Users/ken.colwell/.lando/compose/dr/database-2.yml","--file","/Users/ken.colwell/.lando/compose/dr/database-3.yml","--file","/Users/ken.colwell/.lando/compose/dr/database-4.yml","--file","/Users/ken.colwell/.lando/compose/dr/database-5.yml","--file","/Users/ken.colwell/.lando/compose/dr/node_service-0.yml","--file","/Users/ken.colwell/.lando/compose/dr/node_service-1.yml","--file","/Users/ken.colwell/.lando/compose/dr/node_service-2.yml","--file","/Users/ken.colwell/.lando/compose/dr/node_service-3.yml","--file","/Users/ken.colwell/.lando/compose/dr/express_service-0.yml","--file","/Users/ken.colwell/.lando/compose/dr/express_service-1.yml","--file","/Users/ken.colwell/.lando/compose/dr/express_service-2.yml","--file","/Users/ken.colwell/.lando/compose/dr/express_service-3.yml","--file","/Users/ken.colwell/.lando/compose/dr/proxy-0.yml","--file","/Users/ken.colwell/.lando/compose/dr/proxy-1.yml","--file","/Users/ken.colwell/.lando/compose/dr/proxy-2.yml","up","--detach","--no-recreate","--remove-orphans","express"] in /Users/ken.colwell/Documents/websites/d8 with options {"mode":"collect","detached":false}
debug: With stdio={"stdio":"inherit"}, mode=collect, detached=false, cwd=/Users/ken.colwell/Documents/websites/d8
ERROR: No such service: express
verbose: /Applications/Docker.app/Contents/Resources/bin/docker-compose,--project-name,dr,--file,/Users/ken.colwell/.lando/compose/dr/globals-0.yml,--file,/Users/ken.colwell/.lando/compose/dr/appserver-0.yml,--file,/Users/ken.colwell/.lando/compose/dr/appserver-1.yml,--file,/Users/ken.colwell/.lando/compose/dr/appserver-2.yml,--file,/Users/ken.colwell/.lando/compose/dr/appserver-3.yml,--file,/Users/ken.colwell/.lando/compose/dr/database-0.yml,--file,/Users/ken.colwell/.lando/compose/dr/database-1.yml,--file,/Users/ken.colwell/.lando/compose/dr/database-2.yml,--file,/Users/ken.colwell/.lando/compose/dr/database-3.yml,--file,/Users/ken.colwell/.lando/compose/dr/database-4.yml,--file,/Users/ken.colwell/.lando/compose/dr/database-5.yml,--file,/Users/ken.colwell/.lando/compose/dr/node_service-0.yml,--file,/Users/ken.colwell/.lando/compose/dr/node_service-1.yml,--file,/Users/ken.colwell/.lando/compose/dr/node_service-2.yml,--file,/Users/ken.colwell/.lando/compose/dr/node_service-3.yml,--file,/Users/ken.colwell/.lando/compose/dr/express_service-0.yml,--file,/Users/ken.colwell/.lando/compose/dr/express_service-1.yml,--file,/Users/ken.colwell/.lando/compose/dr/express_service-2.yml,--file,/Users/ken.colwell/.lando/compose/dr/express_service-3.yml,--file,/Users/ken.colwell/.lando/compose/dr/proxy-0.yml,--file,/Users/ken.colwell/.lando/compose/dr/proxy-1.yml,--file,/Users/ken.colwell/.lando/compose/dr/proxy-2.yml,up,--detach,--no-recreate,--remove-orphans,express finished with code 1
verbose: Running ["/Applications/Docker.app/Contents/Resources/bin/docker-compose","--project-name","dr","--file","/Users/ken.colwell/.lando/compose/dr/globals-0.yml","--file","/Users/ken.colwell/.lando/compose/dr/appserver-0.yml","--file","/Users/ken.colwell/.lando/compose/dr/appserver-1.yml","--file","/Users/ken.colwell/.lando/compose/dr/appserver-2.yml","--file","/Users/ken.colwell/.lando/compose/dr/appserver-3.yml","--file","/Users/ken.colwell/.lando/compose/dr/database-0.yml","--file","/Users/ken.colwell/.lando/compose/dr/database-1.yml","--file","/Users/ken.colwell/.lando/compose/dr/database-2.yml","--file","/Users/ken.colwell/.lando/compose/dr/database-3.yml","--file","/Users/ken.colwell/.lando/compose/dr/database-4.yml","--file","/Users/ken.colwell/.lando/compose/dr/database-5.yml","--file","/Users/ken.colwell/.lando/compose/dr/node_service-0.yml","--file","/Users/ken.colwell/.lando/compose/dr/node_service-1.yml","--file","/Users/ken.colwell/.lando/compose/dr/node_service-2.yml","--file","/Users/ken.colwell/.lando/compose/dr/node_service-3.yml","--file","/Users/ken.colwell/.lando/compose/dr/express_service-0.yml","--file","/Users/ken.colwell/.lando/compose/dr/express_service-1.yml","--file","/Users/ken.colwell/.lando/compose/dr/express_service-2.yml","--file","/Users/ken.colwell/.lando/compose/dr/express_service-3.yml","--file","/Users/ken.colwell/.lando/compose/dr/proxy-0.yml","--file","/Users/ken.colwell/.lando/compose/dr/proxy-1.yml","--file","/Users/ken.colwell/.lando/compose/dr/proxy-2.yml","up","--detach","--no-recreate","--remove-orphans","express"] in /Users/ken.colwell/Documents/websites/d8 with options {"mode":"collect","detached":false}
debug: With stdio={"stdio":"inherit"}, mode=collect, detached=false, cwd=/Users/ken.colwell/Documents/websites/d8
ERROR: No such service: express
verbose: /Applications/Docker.app/Contents/Resources/bin/docker-compose,--project-name,dr,--file,/Users/ken.colwell/.lando/compose/dr/globals-0.yml,--file,/Users/ken.colwell/.lando/compose/dr/appserver-0.yml,--file,/Users/ken.colwell/.lando/compose/dr/appserver-1.yml,--file,/Users/ken.colwell/.lando/compose/dr/appserver-2.yml,--file,/Users/ken.colwell/.lando/compose/dr/appserver-3.yml,--file,/Users/ken.colwell/.lando/compose/dr/database-0.yml,--file,/Users/ken.colwell/.lando/compose/dr/database-1.yml,--file,/Users/ken.colwell/.lando/compose/dr/database-2.yml,--file,/Users/ken.colwell/.lando/compose/dr/database-3.yml,--file,/Users/ken.colwell/.lando/compose/dr/database-4.yml,--file,/Users/ken.colwell/.lando/compose/dr/database-5.yml,--file,/Users/ken.colwell/.lando/compose/dr/node_service-0.yml,--file,/Users/ken.colwell/.lando/compose/dr/node_service-1.yml,--file,/Users/ken.colwell/.lando/compose/dr/node_service-2.yml,--file,/Users/ken.colwell/.lando/compose/dr/node_service-3.yml,--file,/Users/ken.colwell/.lando/compose/dr/express_service-0.yml,--file,/Users/ken.colwell/.lando/compose/dr/express_service-1.yml,--file,/Users/ken.colwell/.lando/compose/dr/express_service-2.yml,--file,/Users/ken.colwell/.lando/compose/dr/express_service-3.yml,--file,/Users/ken.colwell/.lando/compose/dr/proxy-0.yml,--file,/Users/ken.colwell/.lando/compose/dr/proxy-1.yml,--file,/Users/ken.colwell/.lando/compose/dr/proxy-2.yml,up,--detach,--no-recreate,--remove-orphans,express finished with code 1
error: Looks like one of your build steps failed! with Error
    at module.exports.sh.Promise.try.then (/snapshot/lando/build/cli/lib/shell.js:0:0)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
From previous event:
    at Shell.sh (/snapshot/lando/build/cli/lib/shell.js:0:0)
    at Object.exports.dc (/snapshot/lando/build/cli/lib/bootstrap.js:0:0)
    at compose (/snapshot/lando/build/cli/lib/bootstrap.js:0:0)
    at exports.start.datum (/snapshot/lando/build/cli/lib/router.js:0:0)
    at Promise.each.Promise.retry (/snapshot/lando/build/cli/lib/router.js:0:0)
    at Promise.resolve.then.Promise.try (/snapshot/lando/build/cli/lib/promise.js:0:0)
    at rec (/snapshot/lando/build/cli/lib/promise.js:0:0)
    at Promise.resolve.then.Promise.try.fn.catch.Promise.delay.then (/snapshot/lando/build/cli/lib/promise.js:0:0)
    at ontimeout (timers.js:427:11)
    at tryOnTimeout (timers.js:289:5)
warn: This **MAY** prevent your app from working
warn: Check for errors above, fix them, and try again
debug: Build error {}
debug: Emitting event pre-engine-up
debug: Event pre-engine-up has 0 listeners
debug: Engine is up.
debug: Emitting event post-engine-up
debug: Event post-engine-up has 0 listeners
debug: Emitting event pre-engine-start
debug: Event pre-engine-start has 4 listeners

```

**Tell us generally about your bug**

I renamed the services and now I get the error message. Just removing the express service and running a rebuild then produces the same error but with "node."

Removing both the node_services and express_services from the lando file does stop the error from appearing on restart. Then when you add them back in the error reappears.

Old services name -> New services name.

node -> node_service
express -> express_service

Doing the following and it didn't help:

lando destroy -y 
lando poweroff 
docker container prune -f 
docker image prune -a -f 
docker network prune -f 
docker volume prune -f 
lando start

I also tried deleting everything in the the ~/.lando/compose directory.

Thanks,
Ken Colwell

**Comment by smutlord** [comment]
@kcolwell i am not able to replicate this, seems to work as expected for me
