### ISSUE TITLE
Cannot run lando drush - container / permissions issue

### ISSUE THREAD

**Issue by jcicero518** [lando/lando#1793]
This is for the latest version of Lando - v3.0.0-rc.20

Running on MacOS Mojave 10.14.4

When attempting to run lando drush I get:

```
PHP Warning:  pcntl_exec(): Error has occurred: (errno 13) Permission denied in phar:///usr/local/bin/drush/includes/startup.inc on line 422

Warning: pcntl_exec(): Error has occurred: (errno 13) Permission denied in phar:///usr/local/bin/drush/includes/startup.inc on line 422
Error has occurred executing the Drush script found at /app/vendor/bin/drush.launcher
(errno 13) Permission denied
```

I've tried all the various steps outlined in other issues - lando rebuild, destroy, restart, etc. with no result. 

The issue might be because of an error during the startup process that I can't quite figure out. On any rebuild, start, restart I get this:

```
Starting theforestfarmers_appserver_1 ... done
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   599    0   599    0     0   2245      0 --:--:-- --:--:-- --:--:--  2243
100 4673k  100 4673k    0     0  5309k      0 --:--:-- --:--:-- --:--:-- 5309k
PHP Warning:  pcntl_exec(): Error has occurred: (errno 13) Permission denied in phar:///usr/local/bin/drush/includes/startup.inc on line 422

Warning: pcntl_exec(): Error has occurred: (errno 13) Permission denied in phar:///usr/local/bin/drush/includes/startup.inc on line 422
Error has occurred executing the Drush script found at /app/vendor/bin/drush.launcher
(errno 13) Permission denied
error: Looks like one of your build steps failed! with Error
    at module.exports.sh.Promise.try.then (/snapshot/lando/build/cli/lib/shell.js:0:0)
From previous event:
    at Shell.sh (/snapshot/lando/build/cli/lib/shell.js:0:0)
    at Object.exports.dc (/snapshot/lando/build/cli/lib/bootstrap.js:0:0)
    at compose (/snapshot/lando/build/cli/lib/bootstrap.js:0:0)
    at exports.run.Promise.each.docker.isRunning.then.then (/snapshot/lando/build/cli/lib/router.js:0:0)
```

.. plus a lot more eventually ending with:

```
warn: This **MAY** prevent your app from working
warn: Check for errors above, fix them, and try again
```

This is just a vanilla Drupal 8 setup with Pantheon from running lando init --source=pantheon. 

Lando file:
```
name: the-forest-farmers
recipe: pantheon
config:
  framework: drupal8
  site: the-forest-farmers
  id: 82442f8c-aa0a-4406-9db8-bb319a852da4
```

I used to be running v3.0.0-rc.14 and just upgraded to the latest version to make sure this issue wasn't already fixed.

The weirdest part about this is it only happens on *some* sites, the only difference being that they have some additional Composer packages installed, namely the Commerce package for Drupal:

```
"require": {
        "php": ">=7.0.8",
        "composer/installers": "^1.0.20",
        "cweagans/composer-patches": "^1.0",
        "drupal-composer/drupal-scaffold": "^2.0.1",
        "drupal/commerce": "^2.13",
        "drupal/commerce_authnet": "^1.1",
        "drupal/config_direct_save": "^1.0",
        "drupal/config_installer": "^1.0",
        "drupal/console": "^1",
        "drupal/core": "^8.7",
        "drupal/entity": "^1.0",
        "drupal/eu_cookie_compliance": "^1.8",
        "drupal/gdpr": "^1.0",
        "drupal/pathauto": "^1.4",
        "drush-ops/behat-drush-endpoint": "^9.3",
        "drush/drush": "~8",
        "pantheon-systems/quicksilver-pushback": "~1",
        "rvtraveller/qs-composer-installer": "^1.1",
        "webflo/drupal-core-strict": "^8.6.15",
        "zaporylie/composer-drupal-optimizations": "^1.0"
    }
```

This wouldn't be a big deal if it was intermittent, but lando drush and lando drupal NEVER work on the sites that have this problem. I *really* need drush, so it's a critical issue for me.

Someone in another issue suggested there may be a race condition involved, as the error is initiated by JS (I think), but how does that relate to different composer packages? The main point here being that the sites where Drush does not work are using Pantheon's "empty upstreams", so Composer is managing them and not Pantheon. 

Here's pantheon.yml:
```
api_version: 1
web_docroot: true
php_version: 7.2
workflows:
  deploy_product:
    after:
      -
        type: webphp
        description: 'Run composer prepare-for-pantheon'
        script: private/scripts/deploy_product/prepare-for-pantheon.php
      -
        type: webphp
        description: 'Run composer install & drupal-scaffold'
        script: private/scripts/deploy_product/composer-install.php
  sync_code:
    after:
      - type: webphp
        description: Push changes back to GitHub if needed
        script: private/scripts/quicksilver/quicksilver-pushback/push-back-to-github.php
```

Commands that cause the bug:
lando drush 
lando drush ** (meaning it doesn't matter what options I give it)

Also, if it makes a difference, the directory structure is slightly different. I'm initializing lando one directory above the web root:

```
drwxr-xr-x@  18 Jeff  staff   576B Sep 17 11:50 .
drwxr-xr-x   30 Jeff  staff   960B Sep 16 15:26 ..
-rw-r--r--@   1 Jeff  staff   366B Sep 16 15:27 .editorconfig
drwxr-xr-x@  15 Jeff  staff   480B Sep 16 16:59 .git
-rw-r--r--@   1 Jeff  staff   1.0K Sep 16 15:27 .gitignore
drwxr-xr-x@  12 Jeff  staff   384B Sep 17 12:53 .idea
-rw-r--r--@   1 Jeff  staff   141B Sep 16 15:29 .lando.yml
-rw-r--r--@   1 Jeff  staff   1.0K Sep 16 15:27 LICENSE
-rw-r--r--@   1 Jeff  staff   4.8K Sep 16 15:27 README.md
-rw-r--r--@   1 Jeff  staff   5.1K Sep 17 11:50 composer.json
-rw-r--r--@   1 Jeff  staff   329K Sep 16 15:27 composer.lock
drwxr-xr-x@ 449 Jeff  staff    14K Sep 16 15:27 config
drwxr-xr-x@   3 Jeff  staff    96B Sep 16 15:27 console
drwxr-xr-x@   4 Jeff  staff   128B Sep 16 15:27 drush
-rw-r--r--@   1 Jeff  staff   600B Sep 16 15:27 pantheon.yml
drwxr-xr-x@   3 Jeff  staff    96B Sep 16 15:27 scripts
drwxr-xr-x@  54 Jeff  staff   1.7K Sep 16 15:28 vendor
drwxr-xr-x@  17 Jeff  staff   544B Sep 16 15:29 web
```

where *web* is the actual Drupal root directory with the usual modules, themes directories.

Here is the full debug output for the lando drush command:

```
lando drush -vvv
info: Bootstraping...
info: config bootstrap beginning...
debug: Emitting event pre-bootstrap-config
debug: Event pre-bootstrap-config has 0 listeners
verbose: Loading event pre-engine-start priority 2
verbose: Loading event pre-engine-start priority 3
verbose: Plugin lando-core loaded from /snapshot/lando/build/cli/plugins/lando-core/index.js
debug: Plugin lando-core has {"config":{"appEnv":{"COLUMNS":256,"LANDO":"ON","LANDO_WEBROOT_USER":"www-data","LANDO_WEBROOT_GROUP":"www-data","TERM":"xterm","LANDO_HOST_UID":"502","LANDO_HOST_GID":"20","LANDO_HOST_USER":"Jeff","LANDO_CA_CERT":"/lando/certs/lndo.site.pem","LANDO_CA_KEY":"/lando/certs/lndo.site.key","LANDO_CONFIG_DIR":"/Users/Jeff/.lando","LANDO_DOMAIN":"lndo.site","LANDO_HOST_HOME":"/Users/Jeff","LANDO_HOST_OS":"darwin","LANDO_HOST_IP":"host.docker.internal","LANDO_MOUNT":"/app"},"appLabels":{"io.lando.container":"TRUE","io.lando.id":"789fc4813f187edcfaf214849a878ac9aa6396e1"},"gid":"20","uid":"502","username":"Jeff","caCert":"/Users/Jeff/.lando/certs/lndo.site.pem","caDomain":"lndo.site","caKey":"/Users/Jeff/.lando/certs/lndo.site.key","caProject":"landocasetupkenobi38ahsoka789fc4813f187edcfaf214849a878ac9aa6396e1"}}
verbose: Plugin lando-events loaded from /snapshot/lando/build/cli/plugins/lando-events/index.js
debug: Plugin lando-events has undefined
verbose: Loading event pre-engine-start priority 1
verbose: Loading event pre-engine-start priority 2
verbose: Plugin lando-networking loaded from /snapshot/lando/build/cli/plugins/lando-networking/index.js
debug: Plugin lando-networking has {"config":{"networkBridge":"lando_bridge_network"}}
verbose: Plugin lando-pantheon loaded from /snapshot/lando/build/cli/plugins/lando-pantheon/index.js
debug: Plugin lando-pantheon has undefined
verbose: Loading event post-bootstrap-config priority 5
verbose: Plugin lando-proxy loaded from /snapshot/lando/build/cli/plugins/lando-proxy/index.js
debug: Plugin lando-proxy has {"config":{"proxy":"ON","proxyCert":"/certs/cert.crt","proxyKey":"/certs/cert.key","proxyName":"landoproxyhyperion5000gandalfedition","proxyDash":"58087","proxyCache":"proxyCache","proxyHttpPort":"80","proxyHttpsPort":"443","proxyHttpFallbacks":["8000","8080","8888","8008"],"proxyHttpsFallbacks":["444","4433","4444","4443"],"proxyDomain":"lndo.site","proxyIp":"127.0.0.1"}}
verbose: Plugin lando-recipes loaded from /snapshot/lando/build/cli/plugins/lando-recipes/index.js
debug: Plugin lando-recipes has undefined
verbose: Plugin lando-services loaded from /snapshot/lando/build/cli/plugins/lando-services/index.js
debug: Plugin lando-services has undefined
verbose: Plugin lando-sharing loaded from /snapshot/lando/build/cli/plugins/lando-sharing/index.js
debug: Plugin lando-sharing has undefined
verbose: Plugin lando-test loaded from /snapshot/lando/build/cli/plugins/lando-test/index.js
debug: Plugin lando-test has {"plugin-test":true}
verbose: Plugin lando-tooling loaded from /snapshot/lando/build/cli/plugins/lando-tooling/index.js
debug: Plugin lando-tooling has undefined
debug: Emitting event post-bootstrap-config
debug: Event post-bootstrap-config has 1 listeners
info: config bootstrap completed.
info: tasks bootstrap beginning...
debug: Emitting event pre-bootstrap-tasks
debug: Event pre-bootstrap-tasks has 0 listeners
debug: Autoloaded task config
debug: Autoloaded task destroy
debug: Autoloaded task info
debug: Autoloaded task list
debug: Autoloaded task logs
debug: Autoloaded task poweroff
debug: Autoloaded task rebuild
debug: Autoloaded task restart
debug: Autoloaded task share
debug: Autoloaded task start
debug: Autoloaded task stop
debug: Autoloaded task version
debug: Autoloaded task init
debug: Autoloaded task ssh
debug: Emitting event post-bootstrap-tasks
debug: Event post-bootstrap-tasks has 0 listeners
info: tasks bootstrap completed.
info: engine bootstrap beginning...
debug: Emitting event pre-bootstrap-engine
debug: Event pre-bootstrap-engine has 0 listeners
debug: Automoved scripts from /snapshot/lando/build/cli/plugins/lando-core/scripts to /Users/Jeff/.lando/scripts and setting 755
debug: Automoved scripts from /snapshot/lando/build/cli/plugins/lando-pantheon/scripts to /Users/Jeff/.lando/scripts and setting 755
debug: Automoved scripts from /snapshot/lando/build/cli/plugins/lando-recipes/scripts to /Users/Jeff/.lando/scripts and setting 755
debug: Automoved scripts from /snapshot/lando/build/cli/plugins/lando-services/scripts to /Users/Jeff/.lando/scripts and setting 755
debug: Automoved scripts from /snapshot/lando/build/cli/plugins/lando-sharing/scripts to /Users/Jeff/.lando/scripts and setting 755
debug: Emitting event post-bootstrap-engine
debug: Event post-bootstrap-engine has 0 listeners
info: engine bootstrap completed.
info: Bootstrap completed.
debug: Emitting event cli-answers
debug: Event cli-answers has 0 listeners
debug: Emitting event cli-drush-answers
debug: Event cli-drush-answers has 0 listeners
debug: Emitting event cli-run
debug: Event cli-run has 0 listeners
debug: Emitting event cli-drush-run
debug: Event cli-drush-run has 0 listeners
debug: Emitting event pre-drush
debug: Event pre-drush has 0 listeners
verbose: Running ["/Applications/Docker.app/Contents/Resources/bin/docker","exec","--tty","--interactive","--user","www-data","--workdir","/app","--env","PHP_MEMORY_LIMIT=-1","theforestfarmers_appserver_1","drush","-vvv"] in /Users/Jeff/Lando/forestfarmers with options {"mode":"attach","detached":false}
debug: With stdio={"stdio":["inherit","inherit","ignore"]}, mode=attach, detached=false, cwd=/Users/Jeff/Lando/forestfarmers
PHP Warning:  pcntl_exec(): Error has occurred: (errno 13) Permission denied in phar:///usr/local/bin/drush/includes/startup.inc on line 422

Warning: pcntl_exec(): Error has occurred: (errno 13) Permission denied in phar:///usr/local/bin/drush/includes/startup.inc on line 422
Error has occurred executing the Drush script found at /app/vendor/bin/drush.launcher
(errno 13) Permission denied
verbose: /Applications/Docker.app/Contents/Resources/bin/docker,exec,--tty,--interactive,--user,www-data,--workdir,/app,--env,PHP_MEMORY_LIMIT=-1,theforestfarmers_appserver_1,drush,-vvv finished with code 1
debug: Emitting event pre-engine-up
debug: Event pre-engine-up has 0 listeners
debug: Engine is up.
debug: Emitting event post-engine-up
debug: Event post-engine-up has 0 listeners
debug: Emitting event pre-engine-isRunning
debug: Event pre-engine-isRunning has 0 listeners
debug: Emitting event post-engine-isRunning
debug: Event post-engine-isRunning has 0 listeners
debug: Logging metrics data {"context":"local","devMode":false,"instance":"789fc4813f187edcfaf214849a878ac9aa6396e1","nodeVersion":"v10.4.1","mode":"cli","os":{"type":"Darwin","platform":"darwin","release":"18.5.0","arch":"x64"},"product":"lando","version":"3.0.0-rc.20","message":"","stack":"Error\n    at module.exports.sh.Promise.try.then (/snapshot/lando/build/cli/lib/shell.js:0:0)\nFrom previous event:\n    at Shell.sh (/snapshot/lando/build/cli/lib/shell.js:0:0)\n    at Object.exports.dockerExec (/snapshot/lando/build/cli/plugins/lando-tooling/lib/utils.js:0:0)\n    at module.exports.lando.Promise.try.then.then.map.each.runner (/snapshot/lando/build/cli/plugins/lando-tooling/lib/build.js:0:0)\n    at runCallback (timers.js:696:18)\n    at tryOnImmediate (timers.js:667:5)\n    at processImmediate (timers.js:649:5)\nFrom previous event:\n    at Object.run (/snapshot/lando/build/cli/plugins/lando-tooling/lib/build.js:0:0)\n    at engineRunner (/snapshot/lando/build/cli/lib/bootstrap.js:0:0)\n    at module.exports.parseToYargs.checkForUpdates.then.lando.bootstrap.then.lando.events.emit.then.then.then.then.then (/snapshot/lando/build/cli/lib/cli.js:0:0)\nFrom previous event:\n    at module.exports.parseToYargs.checkForUpdates.then.lando.bootstrap.then.lando (/snapshot/lando/build/cli/lib/cli.js:0:0)\nFrom previous event:\n    at module.exports.parseToYargs.checkForUpdates.then (/snapshot/lando/build/cli/lib/cli.js:0:0)\n    at runCallback (timers.js:696:18)\n    at tryOnImmediate (timers.js:667:5)\n    at processImmediate (timers.js:649:5)\nFrom previous event:\n    at Object.handler (/snapshot/lando/build/cli/lib/cli.js:0:0)\n    at Object.runCommand (/snapshot/lando/build/cli/node_modules/yargs/lib/command.js:238:44)\n    at Object.parseArgs [as _parseArgs] (/snapshot/lando/build/cli/node_modules/yargs/yargs.js:1063:30)\n    at Function.get [as argv] (/snapshot/lando/build/cli/node_modules/yargs/yargs.js:1004:21)\n    at Cli.run (/snapshot/lando/build/cli/lib/cli.js:0:0)\n    at Object.<anonymous> (/snapshot/lando/build/cli/bin/lando.js:0:0)\n    at Module._compile (pkg/prelude/bootstrap.js:1254:22)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:711:10)\n    at Module.load (internal/modules/cjs/loader.js:610:32)\n    at tryModuleLoad (internal/modules/cjs/loader.js:549:12)\n    at Function.Module._load (internal/modules/cjs/loader.js:541:3)\n    at Function.Module.runMain (pkg/prelude/bootstrap.js:1309:12)\n    at startup (internal/bootstrap/node.js:274:19)\n    at bootstrapNodeJSCore (internal/bootstrap/node.js:608:3)","action":"error","created":"2019-09-17T17:07:40.294Z"}
```

Any assistance is GREATLY GREATLY appreciated. I've been using Lando for awhile but I'll have to look at other options if I can't run drush.

Thanks.

**Comment by GiorgosK** [comment]
```ssh
rm vendor -rf
composer install
```
did it for me

**Comment by weri** [comment]
I was running in a similar issue, and this was related to missing executable permissions. A chmod helped:

`chmod +x vendor/drush/drush/drush`

**Comment by attheshow** [comment]
I was able to fix this on my install by updating drush using:
```
composer update drush/drush
```
