### ISSUE TITLE
WordPress recipe: Build issues when XDebug is enabled

### ISSUE THREAD

**Issue by JodiWarren** [lando/lando#1801]
**Tell us about your setup**
v3.0.0-rc.2 on MacOS 10.14.6

**Tell us about your `.lando.yml`**

```yml
name: wptest
recipe: wordpress
config:
  webroot: ./build
  xdebug: true
```

**Tell us about the command you were running**

Paste in a series of commands that caused the bug.

```bash
lando rebuild
```

**Tell us about the error you got**

```bash
debug: With stdio={"stdio":"inherit"}, mode=collect, detached=false, cwd=/Users/jodi/Sites/hlk
Starting hlk_appserver_1 ... done
verbose: /Applications/Docker.app/Contents/Resources/bin/docker-compose,--project-name,hlk,--file,/Users/jodi/.lando/compose/hlk/globals-0.yml,--file,/Users/jodi/.lando/compose/hlk/appserver-0.yml,--file,/Users/jodi/.lando/compose/hlk/appserver-1.yml,--file,/Users/jodi/.lando/compose/hlk/appserver-2.yml,--file,/Users/jodi/.lando/compose/hlk/appserver-3.yml,--file,/Users/jodi/.lando/compose/hlk/database-0.yml,--file,/Users/jodi/.lando/compose/hlk/database-1.yml,--file,/Users/jodi/.lando/compose/hlk/database-2.yml,--file,/Users/jodi/.lando/compose/hlk/database-3.yml,--file,/Users/jodi/.lando/compose/hlk/database-4.yml,--file,/Users/jodi/.lando/compose/hlk/database-5.yml,--file,/Users/jodi/.lando/compose/hlk/proxy-0.yml,up,--detach,--no-recreate,--remove-orphans,appserver finished with code 0
verbose: Running ["/Applications/Docker.app/Contents/Resources/bin/docker-compose","--project-name","hlk","--file","/Users/jodi/.lando/compose/hlk/globals-0.yml","--file","/Users/jodi/.lando/compose/hlk/appserver-0.yml","--file","/Users/jodi/.lando/compose/hlk/appserver-1.yml","--file","/Users/jodi/.lando/compose/hlk/appserver-2.yml","--file","/Users/jodi/.lando/compose/hlk/appserver-3.yml","--file","/Users/jodi/.lando/compose/hlk/database-0.yml","--file","/Users/jodi/.lando/compose/hlk/database-1.yml","--file","/Users/jodi/.lando/compose/hlk/database-2.yml","--file","/Users/jodi/.lando/compose/hlk/database-3.yml","--file","/Users/jodi/.lando/compose/hlk/database-4.yml","--file","/Users/jodi/.lando/compose/hlk/database-5.yml","--file","/Users/jodi/.lando/compose/hlk/proxy-0.yml","exec","--env","PHP_MEMORY_LIMIT=-1","--user","www-data","appserver","/bin/sh","-c","curl https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar -L -o /tmp/wp-cli.phar && chmod +x /tmp/wp-cli.phar && mv /tmp/wp-cli.phar /usr/local/bin/wp && php /usr/local/bin/wp --info"] in /Users/jodi/Sites/hlk with options {"mode":"attach","detached":false}
debug: With stdio={"stdio":"inherit"}, mode=attach, detached=false, cwd=/Users/jodi/Sites/hlk
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 5412k  100 5412k    0     0  7437k      0 --:--:-- --:--:-- --:--:-- 7434k
^Cverbose: /Applications/Docker.app/Contents/Resources/bin/docker-compose,--project-name,hlk,--file,/Users/jodi/.lando/compose/hlk/globals-0.yml,--file,/Users/jodi/.lando/compose/hlk/appserver-0.yml,--file,/Users/jodi/.lando/compose/hlk/appserver-1.yml,--file,/Users/jodi/.lando/compose/hlk/appserver-2.yml,--file,/Users/jodi/.lando/compose/hlk/appserver-3.yml,--file,/Users/jodi/.lando/compose/hlk/database-0.yml,--file,/Users/jodi/.lando/compose/hlk/database-1.yml,--file,/Users/jodi/.lando/compose/hlk/database-2.yml,--file,/Users/jodi/.lando/compose/hlk/database-3.yml,--file,/Users/jodi/.lando/compose/hlk/database-4.yml,--file,/Users/jodi/.lando/compose/hlk/database-5.yml,--file,/Users/jodi/.lando/compose/hlk/proxy-0.yml,exec,--env,PHP_MEMORY_LIMIT=-1,--user,www-data,appserver,/bin/sh,-c,curl https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar -L -o /tmp/wp-cli.phar && chmod +x /tmp/wp-cli.phar && mv /tmp/wp-cli.phar /usr/local/bin/wp && php /usr/local/bin/wp --info finished with code 130
error: Looks like one of your build steps failed! with Error
    at module.exports.sh.Promise.try.then (/snapshot/lando/build/cli/lib/shell.js:0:0)
From previous event:
    at Shell.sh (/snapshot/lando/build/cli/lib/shell.js:0:0)
    at Object.exports.dc (/snapshot/lando/build/cli/lib/bootstrap.js:0:0)
    at compose (/snapshot/lando/build/cli/lib/bootstrap.js:0:0)
    at exports.run.Promise.each.docker.isRunning.then.then (/snapshot/lando/build/cli/lib/router.js:0:0)
From previous event:
    at exports.run.Promise.each.datum (/snapshot/lando/build/cli/lib/router.js:0:0)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
From previous event:
    at Object.exports.run (/snapshot/lando/build/cli/lib/router.js:0:0)
    at run (/snapshot/lando/build/cli/lib/engine.js:0:0)
    at exports.eventWrapper.daemon.up.then.then (/snapshot/lando/build/cli/lib/router.js:0:0)
From previous event:
    at Object.exports.eventWrapper (/snapshot/lando/build/cli/lib/router.js:0:0)
    at Engine.module.exports.constructor.engineCmd (/snapshot/lando/build/cli/lib/engine.js:0:0)
    at Engine.run (/snapshot/lando/build/cli/lib/engine.js:0:0)
    at Object.exports.runBuild (/snapshot/lando/build/cli/plugins/lando-services/lib/utils.js:0:0)
    at AsyncEvents.module.exports.app.events.on.app.events.on (/snapshot/lando/build/cli/plugins/lando-services/app.js:0:0)
    at AsyncEvents.handle (/snapshot/lando/build/cli/lib/events.js:0:0)
    at emit.Promise.each.fn (/snapshot/lando/build/cli/lib/events.js:0:0)
From previous event:
    at AsyncEvents.emit (/snapshot/lando/build/cli/lib/events.js:0:0)
    at module.exports.start.initAndReport.then (/snapshot/lando/build/cli/lib/app.js:0:0)
From previous event:
    at App.start (/snapshot/lando/build/cli/lib/app.js:0:0)
    at module.exports.rebuild.initAndReport.then.then.then.then.then (/snapshot/lando/build/cli/lib/app.js:0:0)
From previous event:
    at App.rebuild (/snapshot/lando/build/cli/lib/app.js:0:0)
    at Object.exports.appToggle (/snapshot/lando/build/cli/plugins/lando-core/lib/utils.js:0:0)
    at Object.run (/snapshot/lando/build/cli/plugins/lando-core/tasks/rebuild.js:0:0)
    at module.exports.parseToYargs.checkForUpdates.then.lando.bootstrap.then.lando.events.emit.then.then.then.then.then (/snapshot/lando/build/cli/lib/cli.js:0:0)
From previous event:
    at module.exports.parseToYargs.checkForUpdates.then.lando.bootstrap.then.lando (/snapshot/lando/build/cli/lib/cli.js:0:0)
From previous event:
    at module.exports.parseToYargs.checkForUpdates.then (/snapshot/lando/build/cli/lib/cli.js:0:0)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
From previous event:
    at Object.handler (/snapshot/lando/build/cli/lib/cli.js:0:0)
    at Object.runCommand (/snapshot/lando/build/cli/node_modules/yargs/lib/command.js:238:44)
    at Object.parseArgs [as _parseArgs] (/snapshot/lando/build/cli/node_modules/yargs/yargs.js:1063:30)
    at Function.get [as argv] (/snapshot/lando/build/cli/node_modules/yargs/yargs.js:1004:21)
    at Cli.run (/snapshot/lando/build/cli/lib/cli.js:0:0)
    at Object.<anonymous> (/snapshot/lando/build/cli/bin/lando.js:0:0)
    at Module._compile (pkg/prelude/bootstrap.js:1254:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:711:10)
    at Module.load (internal/modules/cjs/loader.js:610:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:549:12)
    at Function.Module._load (internal/modules/cjs/loader.js:541:3)
    at Function.Module.runMain (pkg/prelude/bootstrap.js:1309:12)
    at startup (internal/bootstrap/node.js:274:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:608:3)
warn: This **MAY** prevent your app from working
warn: Check for errors above, fix them, and try again
```

**Tell us generally about your bug**

The rebuild hangs on the download. It will continue after cancelling with ctrl+c, but shows the above error.

Please detail the steps we can take to replicate this bug. Be as detailed as possible.

```bash
lando init --name=wptest --recipe=wordpress
echo "  xdebug: true" >> .lando.yml
lando start
```

**Comment by JodiWarren** [comment]
Is `wontfix` correct here? I can still replicate this bug.

**Comment by davideprevosto** [comment]
Hi @JodiWarren,

we are using MacOS 10.15.2 and lando v3.0.0-rc.23.

This is our .lando.yml

`name: mylandoapp
recipe: wordpress
config:
  php: '7.3'
  via: nginx
  database: mariadb
  xdebug: true
  webroot: .
proxy:
  appserver_nginx:
  - mylandoapp.local.enc
mailhog:
  - mailhog.local.enc
domain: local.enc
services:
  database:
    type: mariadb
    portforward: 3327
    creds:
      user: xxxxxx
      password: xxxxxx
      database: mylandoapp
  mailhog:
    type: mailhog
    hogfrom:
      - appserver
    portforward: true`

It seems it's working fine, hope it helps.

**Comment by JodiWarren** [comment]
Can confirm, my original steps run fine on `v3.0.0-rc.23`

Thanks for the prompt @davideprevosto 

```
$ lando init --name=wptest --recipe=wordpress
$ echo "  xdebug: true" >> .lando.yml
$ lando start
```
