### ISSUE TITLE
Vanilla Apache service fails to start

### ISSUE THREAD

**Issue by abbydrury** [lando/lando#1804]
**Tell us about your setup**

What is your lando version and operating system?

v3.0.0-rc.20 on macOS Mojave 10.14.6

**Tell us about your `.lando.yml`**

```yml
name: test
proxy:
  appserver:
    - test.lndo.site

services:
  appserver:
    type: apache
    webroot: htdocs
    ssl: true
```

**Tell us about the command you were running**

```bash
lando start
```

**Tell us about the error you got**

`lando start` with a vanilla apache server does not successfully start; it complains about being unable to find the app entrypoint.

I uninstalled Docker and Lando and removed `~/.lando` and its contents immediately before attempting this in an attempt to ensure a clean, current, up-to-date environment.

```bash
$ lando rebuild --yes -vvv
...
info: Checking to see if https://localhost:32803 is ready.
verbose: http://localhost:32804 not currently accessible
verbose: https://localhost:32803 not currently accessible
debug: URL scan results url=https://localhost:32803, status=false, color=red, url=http://localhost:32804, status=false, color=red, url=http://test.lndo.site, status=true, color=green, url=https://test.lndo.site, status=true, color=green
debug: Emitting event pre-engine-up
debug: Event pre-engine-up has 0 listeners
debug: Engine is up.
debug: Emitting event post-engine-up
debug: Event post-engine-up has 0 listeners
debug: Emitting event pre-engine-run
debug: Event pre-engine-run has 0 listeners
verbose: Running ["/Applications/Docker.app/Contents/Resources/bin/docker-compose","--project-name","test","--file","/Users/adrury/.lando/compose/test/globals-0.yml","--file","/Users/adrury/.lando/compose/test/appserver-0.yml","--file","/Users/adrury/.lando/compose/test/appserver-1.yml","--file","/Users/adrury/.lando/compose/test/appserver-2.yml","--file","/Users/adrury/.lando/compose/test/appserver-3.yml","--file","/Users/adrury/.lando/compose/test/proxy-0.yml","up","--detach","--no-recreate","--remove-orphans","appserver"] in /Users/adrury/Projects/test with options {"mode":"collect","detached":false}
debug: With stdio={"stdio":"inherit"}, mode=collect, detached=false, cwd=/Users/adrury/Projects/test
Starting test_appserver_1 ... done
verbose: /Applications/Docker.app/Contents/Resources/bin/docker-compose,--project-name,test,--file,/Users/adrury/.lando/compose/test/globals-0.yml,--file,/Users/adrury/.lando/compose/test/appserver-0.yml,--file,/Users/adrury/.lando/compose/test/appserver-1.yml,--file,/Users/adrury/.lando/compose/test/appserver-2.yml,--file,/Users/adrury/.lando/compose/test/appserver-3.yml,--file,/Users/adrury/.lando/compose/test/proxy-0.yml,up,--detach,--no-recreate,--remove-orphans,appserver finished with code 0
verbose: Running ["/Applications/Docker.app/Contents/Resources/bin/docker-compose","--project-name","test","--file","/Users/adrury/.lando/compose/test/globals-0.yml","--file","/Users/adrury/.lando/compose/test/appserver-0.yml","--file","/Users/adrury/.lando/compose/test/appserver-1.yml","--file","/Users/adrury/.lando/compose/test/appserver-2.yml","--file","/Users/adrury/.lando/compose/test/appserver-3.yml","--file","/Users/adrury/.lando/compose/test/proxy-0.yml","exec","--detach","--env","PHP_MEMORY_LIMIT=-1","--user","root","appserver","/bin/sh","-c","/helpers/refresh-certs.sh > /cert-log.txt"] in /Users/adrury/Projects/test with options {"mode":"attach","detached":false}
debug: With stdio={"stdio":"inherit"}, mode=attach, detached=false, cwd=/Users/adrury/Projects/test
ERROR: Container cd5a69692d65663b13cc142817e15a89f53abc558d10d4924856bf8a1dd3a9fc is not running
verbose: /Applications/Docker.app/Contents/Resources/bin/docker-compose,--project-name,test,--file,/Users/adrury/.lando/compose/test/globals-0.yml,--file,/Users/adrury/.lando/compose/test/appserver-0.yml,--file,/Users/adrury/.lando/compose/test/appserver-1.yml,--file,/Users/adrury/.lando/compose/test/appserver-2.yml,--file,/Users/adrury/.lando/compose/test/appserver-3.yml,--file,/Users/adrury/.lando/compose/test/proxy-0.yml,exec,--detach,--env,PHP_MEMORY_LIMIT=-1,--user,root,appserver,/bin/sh,-c,/helpers/refresh-certs.sh > /cert-log.txt finished with code 1
error: Looks like appserver is not running! It should be so this is a problem.
warn: Try running `lando logs -s appserver` to help locate the problem!
debug: Error
    at module.exports.sh.Promise.try.then (/snapshot/lando/build/cli/lib/shell.js:0:0)
From previous event:
    at Shell.sh (/snapshot/lando/build/cli/lib/shell.js:0:0)
    at Object.exports.dc (/snapshot/lando/build/cli/lib/bootstrap.js:0:0)
    at compose (/snapshot/lando/build/cli/lib/bootstrap.js:0:0)
    at exports.run.Promise.each.docker.isRunning.then.then (/snapshot/lando/build/cli/lib/router.js:0:0)
From previous event:
    at exports.run.Promise.each.datum (/snapshot/lando/build/cli/lib/router.js:0:0)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
From previous event:
    at Object.exports.run (/snapshot/lando/build/cli/lib/router.js:0:0)
    at run (/snapshot/lando/build/cli/lib/engine.js:0:0)
    at exports.eventWrapper.daemon.up.then.then (/snapshot/lando/build/cli/lib/router.js:0:0)
From previous event:
    at Object.exports.eventWrapper (/snapshot/lando/build/cli/lib/router.js:0:0)
    at Engine.module.exports.constructor.engineCmd (/snapshot/lando/build/cli/lib/engine.js:0:0)
    at Engine.run (/snapshot/lando/build/cli/lib/engine.js:0:0)
    at module.exports.app.events.on.app.events.on.lando.Promise.each.service (/snapshot/lando/build/cli/plugins/lando-core/app.js:0:0)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
From previous event:
    at AsyncEvents.module.exports.app.events.on.app.events.on (/snapshot/lando/build/cli/plugins/lando-core/app.js:0:0)
    at AsyncEvents.handle (/snapshot/lando/build/cli/lib/events.js:0:0)
    at emit.Promise.each.fn (/snapshot/lando/build/cli/lib/events.js:0:0)
From previous event:
    at AsyncEvents.emit (/snapshot/lando/build/cli/lib/events.js:0:0)
    at module.exports.start.initAndReport.then.then.then (/snapshot/lando/build/cli/lib/app.js:0:0)
From previous event:
    at App.start (/snapshot/lando/build/cli/lib/app.js:0:0)
    at module.exports.rebuild.initAndReport.then.then.then.then.then (/snapshot/lando/build/cli/lib/app.js:0:0)
From previous event:
    at App.rebuild (/snapshot/lando/build/cli/lib/app.js:0:0)
    at Object.exports.appToggle (/snapshot/lando/build/cli/plugins/lando-core/lib/utils.js:0:0)
    at Object.run (/snapshot/lando/build/cli/plugins/lando-core/tasks/rebuild.js:0:0)
    at module.exports.parseToYargs.checkForUpdates.then.lando.bootstrap.then.lando.events.emit.then.then.then.then.then (/snapshot/lando/build/cli/lib/cli.js:0:0)
From previous event:
    at module.exports.parseToYargs.checkForUpdates.then.lando.bootstrap.then.lando (/snapshot/lando/build/cli/lib/cli.js:0:0)
From previous event:
    at module.exports.parseToYargs.checkForUpdates.then (/snapshot/lando/build/cli/lib/cli.js:0:0)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
From previous event:
    at Object.handler (/snapshot/lando/build/cli/lib/cli.js:0:0)
    at Object.runCommand (/snapshot/lando/build/cli/node_modules/yargs/lib/command.js:238:44)
    at Object.parseArgs [as _parseArgs] (/snapshot/lando/build/cli/node_modules/yargs/yargs.js:1063:30)
    at Function.get [as argv] (/snapshot/lando/build/cli/node_modules/yargs/yargs.js:1004:21)
    at Cli.run (/snapshot/lando/build/cli/lib/cli.js:0:0)
    at Object.<anonymous> (/snapshot/lando/build/cli/bin/lando.js:0:0)
    at Module._compile (pkg/prelude/bootstrap.js:1254:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:711:10)
    at Module.load (internal/modules/cjs/loader.js:610:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:549:12)
    at Function.Module._load (internal/modules/cjs/loader.js:541:3)
    at Function.Module.runMain (pkg/prelude/bootstrap.js:1309:12)
    at startup (internal/bootstrap/node.js:274:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:608:3)
debug: Emitting event post-rebuild
debug: Event post-rebuild has 0 listeners

BOOMSHAKALAKA!!!

Your app has started up correctly.
Here are some vitals:

 NAME            test                        
 LOCATION        /Users/adrury/Projects/test 
 SERVICES        appserver                   
 APPSERVER URLS  https://localhost:32803     
                 http://localhost:32804      
                 http://test.lndo.site       
                 https://test.lndo.site     
```

As the error indicates, I ran the log command:
```bash
$ lando logs -s appserver
Attaching to test_appserver_1
appserver_1  | This is a debian container
appserver_1  | user-perms.sh kicking off as user uid=0(root) gid=0(root) groups=0(root)
appserver_1  | Lando ENVVARS set at
appserver_1  | LANDO_WEBROOT_USER: www-data
appserver_1  | LANDO_WEBROOT_GROUP: www-data
appserver_1  | LANDO_WEBROOT_UID: 33
appserver_1  | LANDO_WEBROOT_GID: 33
appserver_1  | LANDO_HOST_UID: 501
appserver_1  | LANDO_HOST_GID: 20
appserver_1  | Making sure correct user:group (www-data:www-data) exists...
appserver_1  | Remapping ownership to handle docker volume sharing...
appserver_1  | LANDO_HOST_UID: 501
appserver_1  | LANDO_HOST_GID: 20
appserver_1  | Resetting www-data:www-data from 33:33 to 501:20
appserver_1  | www-data:www-data is now running as uid=501(www-data) gid=20(dialout) groups=20(dialout),33(www-data)!
appserver_1  | And here. we. go.
appserver_1  | Cert creation kicking off
appserver_1  | LANDO_CA_CERT: /lando/certs/lndo.site.pem
appserver_1  | LANDO_CA_KEY: /lando/certs/lndo.site.key
appserver_1  | CA_DIR: /usr/share/ca-certificates
appserver_1  | CA_CERT_FILENAME: lndo.site.pem
appserver_1  | CA_CERT_CONTAINER: /usr/share/ca-certificates/lndo.site.pem
appserver_1  | Generating certs...
appserver_1  | Generating RSA private key, 2048 bit long modulus
appserver_1  | ..........................................+++++
appserver_1  | .........................................................................................................................+++++
appserver_1  | e is 65537 (0x010001)
appserver_1  | Signature ok
appserver_1  | subject=C = US, ST = California, L = San Francisco, O = Lando, OU = Bespin, CN = *.lndo.site
appserver_1  | Getting CA Private Key
appserver_1  | /usr/share/ca-certificates/lndo.site.pem not found... copying /lando/certs/lndo.site.pem over
appserver_1  | Scanning /lando/keys for keys...
appserver_1  | Found keys 
appserver_1  | Scanning /user/.ssh for keys...
appserver_1  | Found keys /user/.ssh/config /user/.ssh/id_rsa
appserver_1  | Ensuring permissions and ownership of /user/.ssh/config...
appserver_1  | chmod: cannot access '/user/.ssh/config.pub': No such file or directory
appserver_1  | Checking whether /user/.ssh/config is a private key...
appserver_1  | Ensuring permissions and ownership of /user/.ssh/id_rsa...
appserver_1  | Checking whether /user/.ssh/id_rsa is a private key...
appserver_1  | Scanning /var/www/.ssh for keys...
appserver_1  | Found keys 
appserver_1  | Using the following keys: /user/.ssh/id_rsa
appserver_1  | Running command /app-entrypoint.sh httpd -f /opt/bitnami/apache/conf/httpd.conf -DFOREGROUND
appserver_1  | Running with exec!
appserver_1  | /lando-entrypoint.sh: 26: exec: /app-entrypoint.sh: not found
appserver_1  | This is a debian container
appserver_1  | user-perms.sh kicking off as user uid=0(root) gid=0(root) groups=0(root)
appserver_1  | Lando ENVVARS set at
appserver_1  | LANDO_WEBROOT_USER: www-data
appserver_1  | LANDO_WEBROOT_GROUP: www-data
appserver_1  | LANDO_WEBROOT_UID: 501
appserver_1  | LANDO_WEBROOT_GID: 20
appserver_1  | LANDO_HOST_UID: 501
appserver_1  | LANDO_HOST_GID: 20
appserver_1  | Making sure correct user:group (www-data:www-data) exists...
appserver_1  | Remapping ownership to handle docker volume sharing...
appserver_1  | LANDO_HOST_UID: 501
appserver_1  | LANDO_HOST_GID: 20
appserver_1  | Resetting www-data:www-data from 501:20 to 501:20
appserver_1  | www-data:www-data is now running as uid=501(www-data) gid=20(dialout) groups=20(dialout),33(www-data)!
appserver_1  | And here. we. go.
appserver_1  | Scanning /lando/keys for keys...
appserver_1  | Found keys 
appserver_1  | Scanning /user/.ssh for keys...
appserver_1  | Found keys /user/.ssh/config /user/.ssh/id_rsa
appserver_1  | Ensuring permissions and ownership of /user/.ssh/config...
appserver_1  | chmod: cannot access '/user/.ssh/config.pub': No such file or directory
appserver_1  | Checking whether /user/.ssh/config is a private key...
appserver_1  | Ensuring permissions and ownership of /user/.ssh/id_rsa...
appserver_1  | Checking whether /user/.ssh/id_rsa is a private key...
appserver_1  | Scanning /var/www/.ssh for keys...
appserver_1  | Found keys 
appserver_1  | Using the following keys: /user/.ssh/id_rsa
appserver_1  | /lando-entrypoint.sh: 26: exec: /app-entrypoint.sh: not found
appserver_1  | Running command /app-entrypoint.sh httpd -f /opt/bitnami/apache/conf/httpd.conf -DFOREGROUND
appserver_1  | Running with exec!
```

**Tell us generally about your bug**

I tried to create a vanilla Apache service. Creating the above landofile and starting the service does not succeed. It will fail to start and the logs show a failure to start the entrypoint.

Possibly related to issues #1612 and #1674? The error message about the `app-entrypoint.sh` script is similar.

**Tell us more**
Does this bug prevent you from using lando?
Yes.

**Comment by abbydrury** [comment]
I'm currently able to start a vanilla Apache service using rc23, and looking at the release notes I think this may have been fixed as of rc21...?
