### ISSUE TITLE
exec export is not found in $PATH

### ISSUE THREAD

**Issue by skepsys** [lando/lando#1814]
**What is your lando version and operating system?**
v3.0.0-rc.21 on Windows 10 Enterprise v1803

**Tell us about your `.lando.yml`**
```yml
name: test
services:
  appserver:
    type: ruby:2.6 # same results with type: php
    run_as_root:   # same results with run
      - export SOMENAME=somevalue
```
**Tell us about the command you were running**
```bash
lando start
```

**Tell us about the error you got**
```bash
D:\work\_tbk\test> lando start
Let's get this party started! Starting app..
Creating network "test_default" with the default driver
Creating volume "test_data_appserver" with default driver
Creating volume "test_home_appserver" with default driver
Creating test_appserver_1 ... done
Waiting until appserver service is ready...
OCI runtime exec failed: exec failed: container_linux.go:348: starting container process caused "exec: \"export\": executable file not found in $PATH": unknown
error: Looks like one of your build steps failed! with Error
    at module.exports.sh.Promise.try.then (C:\snapshot\lando\build\cli\lib\shell.js:0:0)
From previous event:
    at Shell.sh (C:\snapshot\lando\build\cli\lib\shell.js:0:0)
    at Object.exports.dc (C:\snapshot\lando\build\cli\lib\bootstrap.js:0:0)
    at compose (C:\snapshot\lando\build\cli\lib\bootstrap.js:0:0)
    at exports.run.Promise.each.docker.isRunning.then.then (C:\snapshot\lando\build\cli\lib\router.js:0:0)
From previous event:
    at exports.run.Promise.each.datum (C:\snapshot\lando\build\cli\lib\router.js:0:0)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
From previous event:
    at Object.exports.run (C:\snapshot\lando\build\cli\lib\router.js:0:0)
    at run (C:\snapshot\lando\build\cli\lib\engine.js:0:0)
    at exports.eventWrapper.daemon.up.then.then (C:\snapshot\lando\build\cli\lib\router.js:0:0)
From previous event:
    at Object.exports.eventWrapper (C:\snapshot\lando\build\cli\lib\router.js:0:0)
    at Engine.module.exports.constructor.engineCmd (C:\snapshot\lando\build\cli\lib\engine.js:0:0)
    at Engine.run (C:\snapshot\lando\build\cli\lib\engine.js:0:0)
    at Object.exports.runBuild (C:\snapshot\lando\build\cli\plugins\lando-services\lib\utils.js:0:0)
    at AsyncEvents.module.exports.app.events.on.app.events.on (C:\snapshot\lando\build\cli\plugins\lando-services\app.js:0:0)
    at AsyncEvents.handle (C:\snapshot\lando\build\cli\lib\events.js:0:0)
    at emit.Promise.each.fn (C:\snapshot\lando\build\cli\lib\events.js:0:0)
From previous event:
    at AsyncEvents.emit (C:\snapshot\lando\build\cli\lib\events.js:0:0)
    at module.exports.start.initAndReport.then.then.then (C:\snapshot\lando\build\cli\lib\app.js:0:0)
From previous event:
    at App.start (C:\snapshot\lando\build\cli\lib\app.js:0:0)
    at Object.exports.appToggle (C:\snapshot\lando\build\cli\plugins\lando-core\lib\utils.js:0:0)
    at Object.run (C:\snapshot\lando\build\cli\plugins\lando-core\tasks\start.js:0:0)
    at module.exports.parseToYargs.checkForUpdates.then.lando.bootstrap.then.lando.events.emit.then.then.then.then.then (C:\snapshot\lando\build\cli\lib\cli.js:0:0)
From previous event:
    at module.exports.parseToYargs.checkForUpdates.then.lando.bootstrap.then.lando (C:\snapshot\lando\build\cli\lib\cli.js:0:0)
From previous event:
    at module.exports.parseToYargs.checkForUpdates.then (C:\snapshot\lando\build\cli\lib\cli.js:0:0)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
From previous event:
    at Object.handler (C:\snapshot\lando\build\cli\lib\cli.js:0:0)
    at Object.runCommand (C:\snapshot\lando\build\cli\node_modules\yargs\lib\command.js:238:44)
    at Object.parseArgs [as _parseArgs] (C:\snapshot\lando\build\cli\node_modules\yargs\yargs.js:1063:30)
    at Function.get [as argv] (C:\snapshot\lando\build\cli\node_modules\yargs\yargs.js:1004:21)
    at Cli.run (C:\snapshot\lando\build\cli\lib\cli.js:0:0)
    at Object.<anonymous> (C:\snapshot\lando\build\cli\bin\lando.js:0:0)
    at Module._compile (pkg/prelude/bootstrap.js:1254:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:711:10)
    at Module.load (internal/modules/cjs/loader.js:610:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:549:12)
    at Function.Module._load (internal/modules/cjs/loader.js:541:3)
    at Function.Module.runMain (pkg/prelude/bootstrap.js:1309:12)
    at startup (internal/bootstrap/node.js:274:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:608:3)
warn: This **MAY** prevent your app from working
warn: Check for errors above, fix them, and try again
```

**Tell us generally about your bug**

I tried to set up an environment variable on container creation process as mentioned at #1239 [comment](https://github.com/lando/lando/issues/1239#issuecomment-434247543)
````
run:
    - export SOMENAME=somevalue
````
But it looks like the command is not recognized while lando starts since it throws:
`OCI runtime exec failed: exec failed: container_linux.go:348: starting container process caused "exec: \"export\": executable file not found in $PATH": unknown`

 However, **running the same command via SSH after(!) lando has started works as it should.**

Is it a bug or am I doing something wrong? Thanks.

**Comment by skepsys** [comment]
This does not solves the issue itself,  but I ended up with a workaround using Lando overrides:

```
services:
  appserver:
    type: ruby # or other type
    overrides:
      environment:
        SOMENAME: somevalue

```
Documentation: https://docs.lando.dev/config/services.html#overrides

Another workaround is to use external `env_file`: https://docs.lando.dev/config/env.html#environment-files

See the same issue on Stackoverflow: https://stackoverflow.com/questions/58303293

**Comment by edurenye** [comment]
This does not fix the issue, as you can end up with the same error in a tooling command.
Can you reopen this issue @skepsys please? This is still a bug in RC-23.

**Comment by AS-adci** [comment]
Reopen please. Still not fixed.

**Comment by nelsonamaya82** [comment]
Same error here.

**Comment by anthraxn8b** [comment]
Okay. Same problem. Stale.

Does anyone feel that the stale-robot feature may not be as helpful as expected?
So as long as no one pings the thread it will automatically die?
Maybe you could disable the comment function. Then the software will have no bugs at all ;-)

Anyway: Please reopen.

**Comment by skepsys** [comment]
@anthraxn8b  Sorry, I can not re-open this since it was closed by a bot, so only a repo collaborator could re-open the issue now.
