### ISSUE TITLE
_appserver_1  Cannot start service appserver: b'Ports are not available: /forwards/expose/port returned unexpected status: 500'

### ISSUE THREAD

**Issue by faiwiz** [lando/lando#1834]
I have installed Drupal from https://www.isovera.com/blog/build-it-your-way-lando-docker-and-drupal
I am getting following error when run **lando start** command
_appserver_1  Cannot start service appserver: b'Ports are not available: /forwards/expose/port returned unexpected status: 500'

**here is more detail of error**

ERROR: Encountered errors while bringing up the project.                                                            
error: Looks like one of your build steps failed! with Error                                                        
    at module.exports.sh.Promise.try.then (C:\snapshot\lando\build\cli\lib\shell.js:0:0)                            
    at runCallback (timers.js:696:18)                                                                               
    at tryOnImmediate (timers.js:667:5)                                                                             
    at processImmediate (timers.js:649:5)                                                                           
From previous event:                                                                                                
    at Shell.sh (C:\snapshot\lando\build\cli\lib\shell.js:0:0)                                                      
    at Object.exports.dc (C:\snapshot\lando\build\cli\lib\bootstrap.js:0:0)                                         
    at compose (C:\snapshot\lando\build\cli\lib\bootstrap.js:0:0)                                                   
    at exports.start.datum (C:\snapshot\lando\build\cli\lib\router.js:0:0)                                          
    at Promise.each.Promise.retry (C:\snapshot\lando\build\cli\lib\router.js:0:0)                                   
    at Promise.resolve.then.Promise.try (C:\snapshot\lando\build\cli\lib\promise.js:0:0)                            
    at rec (C:\snapshot\lando\build\cli\lib\promise.js:0:0)                                                         
    at Promise.resolve.then.Promise.try.fn.catch.Promise.delay.then (C:\snapshot\lando\build\cli\lib\promise.js:0:0)
    at ontimeout (timers.js:427:11)                                                                                 
    at tryOnTimeout (timers.js:289:5)                                                                               
warn: This **MAY** prevent your app from working                                                                    
warn: Check for errors above, fix them, and try again                                                               
Starting ipaaslandogit_appserver_1 ... error                                                                        
Starting ipaaslandogit_database_1  ... done

**Comment by mm4492** [comment]
I had this same error using Docker Edge 2.1.4.0. I downgraded Edge to 2.1.3.0 and that resolved the problem.

**Comment by faisalwiz** [comment]
> I had this same error using Docker Edge 2.1.4.0. I downgraded Edge to 2.1.3.0 and that resolved the problem.

yea thanks also it's works for me after upgrading both lando/docker.

**Comment by killua99** [comment]
I can confirm some Docker Edge on mac is broken:

* Docker edge 2.1.5.0 - broken
* Docker edge 2.1.4.0 - broken
* Docker edge 2.1.3.0 - functional

All test by the latest lando version from this date: v3.0.0-rc.22
