### ISSUE TITLE
Lando init fails for source Pantheon: mkdir: cannot create directory '/user/.ssh': File exists

### ISSUE THREAD

**Issue by heitoralthmann** [lando/lando#1844]
> What is your lando version and operating system?
Lando v3.0.0-rc.22 on OSX Mojave 10.14.5

**Tell us about the error you got**
Following [this guide](https://docs.lando.dev/basics/first-app.html#from-pantheon) I tried to `lando init --source pantheon` **on an empty folder**.

After informing my _Pantheon Machine Token_ and selecting the project I wanted to use, this happened:

```sh
[~/Sites/sandbox/pantheon] λ lando init
? From where should we get your app's codebase? pantheon
? Enter a Pantheon machine token [hidden]
? Which site? halthmann
Creating network "landoinithalthmann_default" with the default driver
Creating volume "landoinithalthmann_data_init" with default driver
Creating volume "landoinithalthmann_home_init" with default driver
Creating landoinithalthmann_init_1 ... done
Stopping landoinithalthmann_init_1 ... done
Starting landoinithalthmann_init_1 ... done
mkdir: cannot create directory '/user/.ssh': File exists
Stopping landoinithalthmann_init_1 ... done
Removing landoinithalthmann_init_1 ... done
Removing network landoinithalthmann_default
Removing volume landoinithalthmann_data_init
Removing volume landoinithalthmann_home_init
error: Error
    at module.exports.sh.Promise.try.then (/snapshot/lando/build/cli/lib/shell.js:0:0)
From previous event:
    at Shell.sh (/snapshot/lando/build/cli/lib/shell.js:0:0)
    at Object.exports.dc (/snapshot/lando/build/cli/lib/bootstrap.js:0:0)
    at compose (/snapshot/lando/build/cli/lib/bootstrap.js:0:0)
    at exports.run.Promise.each.docker.isRunning.then.then (/snapshot/lando/build/cli/lib/router.js:0:0)
From previous event:
    at exports.run.Promise.each.datum (/snapshot/lando/build/cli/lib/router.js:0:0)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
From previous event:
    at Object.exports.run (/snapshot/lando/build/cli/lib/router.js:0:0)
    at run (/snapshot/lando/build/cli/lib/engine.js:0:0)
    at exports.eventWrapper.daemon.up.then.then (/snapshot/lando/build/cli/lib/router.js:0:0)
From previous event:
    at Object.exports.eventWrapper (/snapshot/lando/build/cli/lib/router.js:0:0)
    at Engine.module.exports.constructor.engineCmd (/snapshot/lando/build/cli/lib/engine.js:0:0)
    at Engine.run (/snapshot/lando/build/cli/lib/engine.js:0:0)
    at Object.exports.run (/snapshot/lando/build/cli/plugins/lando-recipes/lib/build.js:0:0)
    at lando.Promise.each.step (/snapshot/lando/build/cli/plugins/lando-recipes/tasks/init.js:0:0)
From previous event:
    at runBuild (/snapshot/lando/build/cli/plugins/lando-recipes/tasks/init.js:0:0)
    at module.exports.lando.run.lando.events.emit.then (/snapshot/lando/build/cli/plugins/lando-recipes/tasks/init.js:0:0)
From previous event:
    at Object.run (/snapshot/lando/build/cli/plugins/lando-recipes/tasks/init.js:0:0)
    at module.exports.parseToYargs.checkForUpdates.then.lando.bootstrap.then.lando.events.emit.then.then.then.then.then (/snapshot/lando/build/cli/lib/cli.js:0:0)
From previous event:
    at module.exports.parseToYargs.checkForUpdates.then.lando.bootstrap.then.lando (/snapshot/lando/build/cli/lib/cli.js:0:0)
From previous event:
    at module.exports.parseToYargs.checkForUpdates.then (/snapshot/lando/build/cli/lib/cli.js:0:0)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
From previous event:
    at Object.handler (/snapshot/lando/build/cli/lib/cli.js:0:0)
    at Object.runCommand (/snapshot/lando/build/cli/node_modules/yargs/lib/command.js:238:44)
    at Object.parseArgs [as _parseArgs] (/snapshot/lando/build/cli/node_modules/yargs/yargs.js:1063:30)
    at Function.get [as argv] (/snapshot/lando/build/cli/node_modules/yargs/yargs.js:1004:21)
    at Cli.run (/snapshot/lando/build/cli/lib/cli.js:0:0)
    at Object.<anonymous> (/snapshot/lando/build/cli/bin/lando.js:0:0)
    at Module._compile (pkg/prelude/bootstrap.js:1254:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:711:10)
    at Module.load (internal/modules/cjs/loader.js:610:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:549:12)
    at Function.Module._load (internal/modules/cjs/loader.js:541:3)
    at Function.Module.runMain (pkg/prelude/bootstrap.js:1309:12)
    at startup (internal/bootstrap/node.js:274:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:608:3)
```

As you can see the command breaks after the following error: **mkdir: cannot create directory '/user/.ssh': File exists**.

Tried a downgrading Lando, then upgrading, then tried using different Pantheon projects, but I always get the same error from it.

Is the docs page I am following incorrect and I'm supposed to have any `.lando.*.yml` files before running `lando init` for source Pantheon?

**Comment by gitressa** [comment]
> What is your lando version and operating system?
> Lando v3.0.0-rc.22 on Ubuntu 18.04

I am also seeing this error, but it seems to work. I am not using Pantheon or need SSH, which of course is a factor:

```
$ lando init --source cwd --recipe drupal8 --webroot web --name landotest

NOW WE'RE COOKING WITH FIRE!!!
Your app has been initialized!

Go to the directory where your app was initialized and run `lando start` to get rolling.
Check the LOCATION printed below if you are unsure where to go.

Oh... and here are some vitals:

 NAME      landotest                                           
 LOCATION  /home/USERNAME/dev/landotest                             
 RECIPE    drupal8                                             
 DOCS      https://docs.devwithlando.io/tutorials/drupal8.html 

$ lando start
Let's get this party started! Starting app..
landoproxyhyperion5000gandalfedition_proxy_1 is up-to-date
Creating network "landotest_default" with the default driver
Creating volume "landotest_data_appserver" with default driver
Creating volume "landotest_home_appserver" with default driver
Creating volume "landotest_data_database" with default driver
Creating volume "landotest_home_database" with default driver
Creating landotest_appserver_1 ... done
mkdir: cannot create directory '/user/.ssh': File exists
Stopping landotest_appserver_1 ... 
....
$ drush st
 Drupal version : 8.7.10                            
 Site URI       : http://default                    
 PHP binary     : /usr/local/bin/php                
 PHP config     :                                   
 PHP OS         : Linux                             
 Drush script   : /app/vendor/drush/drush/drush     
 Drush version  : 9.7.1                             
 Drush temp     : /tmp                              
 Drush configs  : /app/vendor/drush/drush/drush.yml 
                  /app/drush/drush.yml              
 Drupal root    : /app/web                          
 Site path      : sites/default                     

$ drush site-install --db-url=mysql://drupal8:drupal8@database/drupal8 --account-pass=admin -y

 // You are about to DROP all tables in your 'drupal8' database. Do you want to continue?: yes.                         

 [notice] Starting Drupal installation. This takes a while.
 [success] Installation complete.
```

**Comment by gobinathm** [comment]
This issue frequently & I'm running lando v3.0.23

**Comment by gitressa** [comment]
Still happening in Ubuntu 20.04 ...

**Comment by gitressa** [comment]
I finally figured out this is happening because my `~/.ssh` folder is symlinked, and the actual `.ssh` folder is living on another partition. I reverted to use a normal folder, and now everything works fine.

**Comment by midweste** [comment]
> I finally figured out this is happening because my `~/.ssh` folder is symlinked, and the actual `.ssh` folder is living on another partition. I reverted to use a normal folder, and now everything works fine.

I can verify I also got this error by symlinking my .ssh folder.

It will work correctly if you use mount --bind OR mount bind in etc/fstab

https://unix.stackexchange.com/a/539851

```
mkdir -m 700 .ssh
mount --bind  /pool/secure/ssh  .ssh
```
_above will not persist on reboot_

OR

```
# using mount bind in /etc/fstab
/mnt/data/eric/.ssh /home/eric/.ssh	none	defaults,bind	0	0
```
_will persist on reboot_

**Comment by robme** [comment]
I have this error. No symlinks, `~/.ssh` is a normal directory with normal permissions.

It doesn't appear to stop lando from working, it just gives that error multiple times during `lando start`.
