### ISSUE TITLE
Remove a service (database) from recipe

### ISSUE THREAD

**Issue by RicLeP** [lando/lando#1860]
Can I remove a service from a recipe? For instance I want to use the base Laravel recipe without any database. Can this be done in the .lando.yml file? Or can I duplicate and edit the base recipe? I can’t see how to do this.

**Comment by gilzow** [comment]
+1 to this request. Needing to do (almost) exactly the same thing.

**Comment by runofthemill** [comment]
Also needing this; I think this might be doable via a plugin (https://docs.lando.dev/contrib/plugins.html) using some of the engine events (https://docs.lando.dev/api/engine.html) that get emitted. I might try working on this...if I figure anything out, I'll follow up here.

**Comment by markdorison** [comment]
What about allowing a service to be disabled in configuration, [similar to what is available for tooling](https://github.com/lando/lando/commit/1a7f9c1c9c8e06dfc322fb6c537fbd5475ab9673)?

**Comment by pirog** [comment]
Here is a proposal on how to do this #1965

**Comment by Eldair** [comment]
Any news on this?

**Comment by pirog** [comment]
Not something we currently have plans to work on.

**Comment by Eldair** [comment]
Oh, okay. Is there some way I can manually recreate a recipe as lando file?

**Comment by pirog** [comment]
I think if you do a `lando init` with the `--full` flag it will dump the entire recipe config into a landofile

**Comment by Eldair** [comment]
Niiiice ! Thanks a lot @pirog

**Comment by Eldair** [comment]
@pirog I started playing with this and it is mostly ok except nginx. How can we use laravel nginx without everything else from laravel recipe?

**Comment by vladdancer** [comment]
Here is the my way to disable service locally. Add `.lando.local.yml` ensure that it will be picked by global lando config.
Then use compose override directive to change service entry point:

```yml
services:
  phpmyadmin:
    type: phpmyadmin
    overrides:
      entrypoint: 'echo disabled service'
      restart: no

```

But I agree that `state: off` would be nice to have in config file to avoid waiting of manually stopped services: `Scanning to determine which services are ready... Please standby`

**Comment by pirog** [comment]
The URL scanning can actually be disabled as well.

**Comment by vladdancer** [comment]
FYI: @pirog 

Just noticed that for each disabled service using `entrypoint` approach I get the below error log.
It is ok for one service but when I have 1+ disabled ones then it is annoying to see that log's flow.

```bash
Starting superpuperproject_ phpmyadmin_1 ... done
ERROR: No container found for varnish_1
ERROR ==>  message=, stack=Error
    at /Users/VladDancer/lando/lib/shell.js:158:44
From previous event:
    at Shell.sh (/Users/VladDancer/lando/lib/shell.js:150:6)
    at Object.exports.dc (/Users/VladDancer/lando/lib/bootstrap.js:126:16)
    at compose (/Users/VladDancer/lando/lib/bootstrap.js:227:43)
    at /Users/VladDancer/lando/lib/router.js:85:15
From previous event:
    at /Users/VladDancer/lando/lib/router.js:85:4
    at processImmediate (internal/timers.js:458:21)
From previous event:
    at Object.exports.run (/Users/VladDancer/lando/lib/router.js:69:66)
    at run (/Users/VladDancer/lando/lib/engine.js:18:59)
    at /Users/VladDancer/lando/lib/router.js:26:15
From previous event:
    at Object.exports.eventWrapper (/Users/VladDancer/lando/lib/router.js:26:4)
    at Engine.engineCmd (/Users/VladDancer/lando/lib/engine.js:18:104)
    at Engine.run (/Users/VladDancer/lando/lib/engine.js:354:17)
    at /Users/VladDancer/lando/plugins/lando-core/app.js:73:25
From previous event:
    at AsyncEvents.<anonymous> (/Users/VladDancer/lando/plugins/lando-core/app.js:72:59)
    at AsyncEvents.handle (/Users/VladDancer/lando/lib/events.js:84:25)
    at /Users/VladDancer/lando/lib/events.js:117:21
From previous event:
    at AsyncEvents.emit (/Users/VladDancer/lando/lib/events.js:111:20)
    at /Users/VladDancer/lando/lib/app.js:438:29
From previous event:
    at App.start (/Users/VladDancer/lando/lib/app.js:438:6)
    at Object.run (/Users/VladDancer/lando/plugins/lando-core/tasks/start.js:17:20)
    at /Users/VladDancer/lando/lib/cli.js:387:54
From previous event:
    at /Users/VladDancer/lando/lib/cli.js:385:10
From previous event:
    at Object.handler (/Users/VladDancer/lando/lib/cli.js:319:37)
    at Object.runCommand (/Users/VladDancer/lando/node_modules/yargs/lib/command.js:238:44)
    at Object.parseArgs [as _parseArgs] (/Users/VladDancer/lando/node_modules/yargs/yargs.js:1063:30)
    at Function.get [as argv] (/Users/VladDancer/lando/node_modules/yargs/yargs.js:1004:21)
    at Cli.init (/Users/VladDancer/lando/lib/cli.js:238:51)
    at Cli.run (/Users/VladDancer/lando/lib/cli.js:446:10)
    at Object.<anonymous> (/Users/VladDancer/lando/bin/lando.js:58:7)
    at Module._compile (internal/modules/cjs/loader.js:1251:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1272:10)
    at Module.load (internal/modules/cjs/loader.js:1100:32)
    at Function.Module._load (internal/modules/cjs/loader.js:962:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47, __stackCleaned__=true
```

**Comment by hardyoyo** [comment]
Hmm... disabling a db service seems to cause Lando to freak a little bit:

```
  _      __              _           __
 | | /| / /__ ________  (_)__  ___ _/ /
 | |/ |/ / _ `/ __/ _ \/ / _ \/ _ `/_/
 |__/|__/\_,_/_/ /_//_/_/_//_/\_, (_)
                             /___/

Your app started up but we detected some things you may wish to investigate.
These only may be a problem.


 ■ The service "db" is not running!
   This is likely a critical problem and we recommend you run the command below to investigate
   lando logs -s db
   ```

**Comment by JPustkuchen** [comment]
+1 for this request! Disabling certain services like the database, when not needed, absolutely makes sense! :)

**Comment by hardyoyo** [comment]
I completely forgot this issue already exists, have been trying off and on to find a clever enough workaround for turning off a db service, I had forgotten I had managed to do it once, and got yelled at by Lando (see above).

Anyway, yeah, +1 from me, this should be an option for a service. It may require another flag elsewhere to mark the service as not required.

**Comment by simesy** [comment]
I have a [demonstration build](https://github.com/simesy/drupalcaas/blob/master/.lando.yml) where solr and elasticsearch are both included to give people the option. But from a practically point of view it would be great to disable one or the other from .lando.local.yml.

**Comment by pirog** [comment]
We plan on supporting this in Lando 4.0. TBD on whether it will make it back into Lando 3.0.

**Comment by vladdancer** [comment]
Any updates here?

**Comment by Aldo-f** [comment]
``` yaml
name: lap
recipe: lamp
services:
  database: disabled
```
![image](https://user-images.githubusercontent.com/5683799/205385863-a187e50a-6512-4915-bf57-ca25154afa52.png)

Source: 
- https://github.com/lando/lando/commit/1a7f9c1c9c8e06dfc322fb6c537fbd5475ab9673#diff-fcbfc389d20c042e78ef894ccbbf30235ed1b0d8982fee787a164ed1ca0ecc04R62

**Comment by Eldair** [comment]
Well, is lando 3.6.5 released?

**Comment by gilzow** [comment]
> Well, is lando 3.6.5 released?

https://github.com/lando/lando/releases/tag/v3.6.5

**Comment by Eldair** [comment]
Hm, it's not in releases on GH 🫤 sorry about that
