### ISSUE TITLE
Can't start lemp recipe with mysql 8

### ISSUE THREAD

**Issue by ChristianGiupponi** [lando/lando#1871]
What is your lando version and operating system? 
`v3.0.0-rc.22` on MacOS

**Tell us about your `.lando.yml`**

```yml
name: prova-lando-revolution
recipe: lemp
config:
  webroot: public
  php: '7.2'
  database: mysql
  xdebug: true
services:
  database:
    type: mysql:8
    portforward: 3306
    creds:
      user: prova
      password: prova
      database: prova
```

**Tell us about the command you were running**
just `lando start`

**Tell us about the error you got**

```bash
Let's get this party started! Starting app..
error: Error: mysql version 8 is not supported
    at new LandoService (/snapshot/lando/build/cli/plugins/lando-core/compose/lando/builder.js:0:0)
    at new LandoService (/snapshot/lando/build/cli/plugins/lando-core/types/service/builder.js:0:0)
    at new LandoMySql (/snapshot/lando/build/cli/plugins/lando-services/services/mysql/builder.js:0:0)
    at module.exports.app.events.on._.forEach.service (/snapshot/lando/build/cli/plugins/lando-services/app.js:0:0)
    at arrayEach (/snapshot/lando/build/cli/node_modules/lodash/lodash.js:516:11)
    at Function.forEach (/snapshot/lando/build/cli/node_modules/lodash/lodash.js:9344:14)
    at AsyncEvents.module.exports.app.events.on (/snapshot/lando/build/cli/plugins/lando-services/app.js:0:0)
    at AsyncEvents.handle (/snapshot/lando/build/cli/lib/events.js:0:0)
    at emit.Promise.each.fn (/snapshot/lando/build/cli/lib/events.js:0:0)
From previous event:
    at AsyncEvents.emit (/snapshot/lando/build/cli/lib/events.js:0:0)
    at module.exports.init.loadPlugins.then (/snapshot/lando/build/cli/lib/app.js:0:0)
From previous event:
    at App.init (/snapshot/lando/build/cli/lib/app.js:0:0)
    at initAndReport (/snapshot/lando/build/cli/lib/app.js:0:0)
    at App.start (/snapshot/lando/build/cli/lib/app.js:0:0)
    at Object.exports.appToggle (/snapshot/lando/build/cli/plugins/lando-core/lib/utils.js:0:0)
    at Object.run (/snapshot/lando/build/cli/plugins/lando-core/tasks/start.js:0:0)
    at module.exports.parseToYargs.checkForUpdates.then.lando.bootstrap.then.lando.events.emit.then.then.then.then.then (/snapshot/lando/build/cli/lib/cli.js:0:0)
From previous event:
    at module.exports.parseToYargs.checkForUpdates.then.lando.bootstrap.then.lando (/snapshot/lando/build/cli/lib/cli.js:0:0)
From previous event:
    at module.exports.parseToYargs.checkForUpdates.then (/snapshot/lando/build/cli/lib/cli.js:0:0)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
From previous event:
    at Object.handler (/snapshot/lando/build/cli/lib/cli.js:0:0)
    at Object.runCommand (/snapshot/lando/build/cli/node_modules/yargs/lib/command.js:238:44)
    at Object.parseArgs [as _parseArgs] (/snapshot/lando/build/cli/node_modules/yargs/yargs.js:1063:30)
    at Function.get [as argv] (/snapshot/lando/build/cli/node_modules/yargs/yargs.js:1004:21)
    at Cli.run (/snapshot/lando/build/cli/lib/cli.js:0:0)
    at Object.<anonymous> (/snapshot/lando/build/cli/bin/lando.js:0:0)
    at Module._compile (pkg/prelude/bootstrap.js:1254:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:711:10)
    at Module.load (internal/modules/cjs/loader.js:610:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:549:12)
    at Function.Module._load (internal/modules/cjs/loader.js:541:3)
    at Function.Module.runMain (pkg/prelude/bootstrap.js:1309:12)
    at startup (internal/bootstrap/node.js:274:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:608:3)
```

**Comment by kimdcottrell** [comment]
Throwing this here since it may be a solution for the Lando project, tho this is native Docker and I don't know Node so I can't contribute. 

MySQL 8 retired the authentication scheme that PHP is used to. You can get MySQL 8 to play nice by running this command in the mysql service: https://github.com/kimdcottrell/devcafe-docker/blob/master/docker-compose.yml#L33 

```
 database:
    image: mysql:8
    command: '--default-authentication-plugin=mysql_native_password'
```

**Comment by pjoulot** [comment]
I have the same issue, according to the documentation I set my yml file like this:

```
recipe: drupal8
config:
  database: mysql:8.0
```

Mysql is well installed, I can connect to it by running lando mysql -u drupal8 -p drupal8
But Drupal can't access because of the default_authentication_plugin  which is not mysql_native_password by default with mysql 8.0
