### ISSUE TITLE
Failed to execute script docker-compose (Docker v2.2)

### ISSUE THREAD

**Issue by gtjamesa** [lando/lando#1943]
**Tell us about your setup**

What is your lando version and operating system? **(note that the older your version the less likely we are to reply)**

Lando

```bash
v3.0.0-rc.23 on Windows 10 Pro 18363
```

Docker Desktop v2.2.0.0

```bash
Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea838
 Built:             Wed Nov 13 07:29:52 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea
  Built:            Wed Nov 13 07:29:19 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

Using Lando in WSL, with an [alias to the cmd.exe](https://github.com/lando/lando/issues/462#issuecomment-511937745)

**Tell us about your `.lando.yml`**

```yml
name: ezines
recipe: lamp
config:
  php: '5.6'
  webroot: .
  database: mysql:5.7
  xdebug: false

services:
    database:
      portforward: 33060
      config:
          database: .lando/mysql/my.cnf

proxy:
  appserver:
    - ezines.local
```

**Tell us about the command you were running**

```bash
# Starting containers caused the error
lando start

# Attempted rebuild, same error
lando rebuild -y
```

**Tell us about the error you got**

*Large paste below, scroll to bottom for explanation*

```bash
james@DESKTOP:/d/wamp/www/ezines.local$ lando start -vvv
info: Bootstraping...
info: config bootstrap beginning...
debug: Emitting event pre-bootstrap-config
debug: Event pre-bootstrap-config has 0 listeners
verbose: Loading event pre-engine-start priority 2
verbose: Loading event pre-engine-start priority 3
verbose: Plugin lando-core loaded from C:/snapshot/lando/build/cli/plugins/lando-core/index.js
debug: Plugin lando-core has {"config":{"appEnv":{"COLUMNS":256,"LANDO":"ON","LANDO_WEBROOT_USER":"www-data","LANDO_WEBROOT_GROUP":"www-data","TERM":"xterm","LANDO_HOST_UID":"1000","LANDO_HOST_GID":"1000","LANDO_HOST_USER"
:"James","LANDO_CA_CERT":"/lando/certs/lndo.site.pem","LANDO_CA_KEY":"/lando/certs/lndo.site.key","LANDO_CONFIG_DIR":"C:\\Users\\James\\.lando","LANDO_DOMAIN":"lndo.site","LANDO_HOST_HOME":"C:\\Users\\James","LANDO_HOST_OS
":"win32","LANDO_HOST_IP":"host.docker.internal","LANDO_MOUNT":"/app"},"appLabels":{"io.lando.container":"TRUE","io.lando.id":"78688e4cf3f6a97e47dd76ebe9496b6d64725593"},"gid":"1000","uid":"1000","username":"James","caCert
":"C:\\Users\\James\\.lando\\certs\\lndo.site.pem","caDomain":"lndo.site","caKey":"C:\\Users\\James\\.lando\\certs\\lndo.site.key","caProject":"landocasetupkenobi38ahsoka78688e4cf3f6a97e47dd76ebe9496b6d64725593"}}
verbose: Plugin lando-events loaded from C:/snapshot/lando/build/cli/plugins/lando-events/index.js

... 

info: Checking to see if https://localhost:32807 is ready.
info: Checking to see if http://localhost:32808 is ready.
info: Checking to see if http://ezines.local is ready.
info: Checking to see if https://ezines.local is ready.
info: http://localhost:32808 is ready
info: https://localhost:32807 is ready
info: http://ezines.local is ready
info: https://ezines.local is ready
debug: URL scan results url=https://localhost:32807, status=true, color=green, url=http://localhost:32808, status=true, color=green, url=http://ezines.local, status=true, color=green, url=https://ezines.local, status=true,
 color=green
debug: Emitting event pre-engine-up
debug: Event pre-engine-up has 0 listeners
debug: Emitting event post-engine-up
debug: Event post-engine-up has 0 listeners
debug: Emitting event pre-engine-run
debug: Event pre-engine-run has 0 listeners
verbose: Running pid5 ["C:\\Program Files\\Docker\\Docker\\resources\\bin\\docker-compose.exe","--project-name","ezines","--file","C:\\Users\\James\\.lando\\compose\\ezines\\globals-0.yml","--file","C:\\Users\\James\\.land
o\\compose\\ezines\\appserver-0.yml","--file","C:\\Users\\James\\.lando\\compose\\ezines\\appserver-1.yml","--file","C:\\Users\\James\\.lando\\compose\\ezines\\appserver-2.yml","--file","C:\\Users\\James\\.lando\\compose\\
ezines\\appserver-3.yml","--file","C:\\Users\\James\\.lando\\compose\\ezines\\database-0.yml","--file","C:\\Users\\James\\.lando\\compose\\ezines\\database-1.yml","--file","C:\\Users\\James\\.lando\\compose\\ezines\\databa
se-2.yml","--file","C:\\Users\\James\\.lando\\compose\\ezines\\database-3.yml","--file","C:\\Users\\James\\.lando\\compose\\ezines\\database-4.yml","--file","C:\\Users\\James\\.lando\\compose\\ezines\\database-5.yml","--fi
le","C:\\Users\\James\\.lando\\compose\\ezines\\proxy-0.yml","exec","--detach","--env","PHP_MEMORY_LIMIT=-1","--user","root","appserver","/bin/sh","-c","/helpers/refresh-certs.sh > /cert-log.txt"] in D:\wamp\www\ezines.loc
al with options {"mode":"attach","detached":false}
debug: With stdio={"stdio":"inherit"}, mode=attach, detached=false, cwd=D:\wamp\www\ezines.local
Traceback (most recent call last):
  File "docker-compose", line 6, in <module>
  File "compose\cli\main.py", line 72, in main
  File "compose\cli\main.py", line 128, in perform_command
  File "compose\cli\main.py", line 491, in exec_command
  File "compose\cli\main.py", line 1469, in call_docker
  File "subprocess.py", line 172, in call
  File "subprocess.py", line 394, in __init__
  File "subprocess.py", line 644, in _execute_child
TypeError: environment can only contain strings
[169916] Failed to execute script docker-compose
verbose: C:\Program Files\Docker\Docker\resources\bin\docker-compose.exe,--project-name,ezines,--file,C:\Users\James\.lando\compose\ezines\globals-0.yml,--file,C:\Users\James\.lando\compose\ezines\appserver-0.yml,--file,C:
\Users\James\.lando\compose\ezines\appserver-1.yml,--file,C:\Users\James\.lando\compose\ezines\appserver-2.yml,--file,C:\Users\James\.lando\compose\ezines\appserver-3.yml,--file,C:\Users\James\.lando\compose\ezines\databas
e-0.yml,--file,C:\Users\James\.lando\compose\ezines\database-1.yml,--file,C:\Users\James\.lando\compose\ezines\database-2.yml,--file,C:\Users\James\.lando\compose\ezines\database-3.yml,--file,C:\Users\James\.lando\compose\
ezines\database-4.yml,--file,C:\Users\James\.lando\compose\ezines\database-5.yml,--file,C:\Users\James\.lando\compose\ezines\proxy-0.yml,exec,--detach,--env,PHP_MEMORY_LIMIT=-1,--user,root,appserver,/bin/sh,-c,/helpers/ref
resh-certs.sh > /cert-log.txt finished with code 4294967295
error: Looks like appserver is not running! It should be so this is a problem.
warn: Try running `lando logs -s appserver` to help locate the problem!
debug: Error
    at module.exports.sh.Promise.try.then (C:\snapshot\lando\build\cli\lib\shell.js:0:0)
From previous event:
    at Shell.sh (C:\snapshot\lando\build\cli\lib\shell.js:0:0)
    at Object.exports.dc (C:\snapshot\lando\build\cli\lib\bootstrap.js:0:0)
    at compose (C:\snapshot\lando\build\cli\lib\bootstrap.js:0:0)
    at exports.run.Promise.each.docker.isRunning.then.then (C:\snapshot\lando\build\cli\lib\router.js:0:0)
From previous event:
    at exports.run.Promise.each.datum (C:\snapshot\lando\build\cli\lib\router.js:0:0)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
From previous event:
    at Object.exports.run (C:\snapshot\lando\build\cli\lib\router.js:0:0)
    at run (C:\snapshot\lando\build\cli\lib\engine.js:0:0)
    at exports.eventWrapper.daemon.up.then.then (C:\snapshot\lando\build\cli\lib\router.js:0:0)
From previous event:
    at Object.exports.eventWrapper (C:\snapshot\lando\build\cli\lib\router.js:0:0)
    at Engine.module.exports.constructor.engineCmd (C:\snapshot\lando\build\cli\lib\engine.js:0:0)
    at Engine.run (C:\snapshot\lando\build\cli\lib\engine.js:0:0)
    at module.exports.app.events.on.app.events.on.lando.Promise.each.service (C:\snapshot\lando\build\cli\plugins\lando-core\app.js:0:0)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
From previous event:
    at AsyncEvents.module.exports.app.events.on.app.events.on (C:\snapshot\lando\build\cli\plugins\lando-core\app.js:0:0)
    at AsyncEvents.handle (C:\snapshot\lando\build\cli\lib\events.js:0:0)
    at emit.Promise.each.fn (C:\snapshot\lando\build\cli\lib\events.js:0:0)
From previous event:
    at AsyncEvents.emit (C:\snapshot\lando\build\cli\lib\events.js:0:0)
    at module.exports.start.initAndReport.then.then.then (C:\snapshot\lando\build\cli\lib\app.js:0:0)
From previous event:
    at App.start (C:\snapshot\lando\build\cli\lib\app.js:0:0)
    at Object.exports.appToggle (C:\snapshot\lando\build\cli\plugins\lando-core\lib\utils.js:0:0)
    at Object.run (C:\snapshot\lando\build\cli\plugins\lando-core\tasks\start.js:0:0)
    at module.exports.parseToYargs.checkForUpdates.then.lando.bootstrap.then.lando.events.emit.then.then.then.then.then (C:\snapshot\lando\build\cli\lib\cli.js:0:0)
From previous event:
    at module.exports.parseToYargs.checkForUpdates.then.lando.bootstrap.then.lando (C:\snapshot\lando\build\cli\lib\cli.js:0:0)
From previous event:
    at module.exports.parseToYargs.checkForUpdates.then (C:\snapshot\lando\build\cli\lib\cli.js:0:0)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
From previous event:
    at Object.handler (C:\snapshot\lando\build\cli\lib\cli.js:0:0)
    at Object.runCommand (C:\snapshot\lando\build\cli\node_modules\yargs\lib\command.js:238:44)
    at Object.parseArgs [as _parseArgs] (C:\snapshot\lando\build\cli\node_modules\yargs\yargs.js:1063:30)
    at Function.get [as argv] (C:\snapshot\lando\build\cli\node_modules\yargs\yargs.js:1004:21)
    at Cli.run (C:\snapshot\lando\build\cli\lib\cli.js:0:0)
    at Object.<anonymous> (C:\snapshot\lando\build\cli\bin\lando.js:0:0)
    at Module._compile (pkg/prelude/bootstrap.js:1254:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:711:10)
    at Module.load (internal/modules/cjs/loader.js:610:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:549:12)
    at Function.Module._load (internal/modules/cjs/loader.js:541:3)
    at Function.Module.runMain (pkg/prelude/bootstrap.js:1309:12)
    at startup (internal/bootstrap/node.js:274:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:608:3)
debug: Emitting event pre-engine-up
debug: Event pre-engine-up has 0 listeners
debug: Emitting event post-engine-up
debug: Event post-engine-up has 0 listeners
debug: Emitting event pre-engine-run
debug: Event pre-engine-run has 0 listeners
verbose: Running pid6 ["C:\\Program Files\\Docker\\Docker\\resources\\bin\\docker-compose.exe","--project-name","ezines","--file","C:\\Users\\James\\.lando\\compose\\ezines\\globals-0.yml","--file","C:\\Users\\James\\.land
o\\compose\\ezines\\appserver-0.yml","--file","C:\\Users\\James\\.lando\\compose\\ezines\\appserver-1.yml","--file","C:\\Users\\James\\.lando\\compose\\ezines\\appserver-2.yml","--file","C:\\Users\\James\\.lando\\compose\\
ezines\\appserver-3.yml","--file","C:\\Users\\James\\.lando\\compose\\ezines\\database-0.yml","--file","C:\\Users\\James\\.lando\\compose\\ezines\\database-1.yml","--file","C:\\Users\\James\\.lando\\compose\\ezines\\databa
se-2.yml","--file","C:\\Users\\James\\.lando\\compose\\ezines\\database-3.yml","--file","C:\\Users\\James\\.lando\\compose\\ezines\\database-4.yml","--file","C:\\Users\\James\\.lando\\compose\\ezines\\database-5.yml","--fi
le","C:\\Users\\James\\.lando\\compose\\ezines\\proxy-0.yml","exec","--detach","--env","PHP_MEMORY_LIMIT=-1","--user","root","database","/bin/sh","-c","/helpers/refresh-certs.sh > /cert-log.txt"] in D:\wamp\www\ezines.loca
l with options {"mode":"attach","detached":false}
debug: With stdio={"stdio":"inherit"}, mode=attach, detached=false, cwd=D:\wamp\www\ezines.local
Traceback (most recent call last):
  File "docker-compose", line 6, in <module>
  File "compose\cli\main.py", line 72, in main
  File "compose\cli\main.py", line 128, in perform_command
  File "compose\cli\main.py", line 491, in exec_command
  File "compose\cli\main.py", line 1469, in call_docker
  File "subprocess.py", line 172, in call
  File "subprocess.py", line 394, in __init__
  File "subprocess.py", line 644, in _execute_child
TypeError: environment can only contain strings
[169804] Failed to execute script docker-compose
verbose: C:\Program Files\Docker\Docker\resources\bin\docker-compose.exe,--project-name,ezines,--file,C:\Users\James\.lando\compose\ezines\globals-0.yml,--file,C:\Users\James\.lando\compose\ezines\appserver-0.yml,--file,C:
\Users\James\.lando\compose\ezines\appserver-1.yml,--file,C:\Users\James\.lando\compose\ezines\appserver-2.yml,--file,C:\Users\James\.lando\compose\ezines\appserver-3.yml,--file,C:\Users\James\.lando\compose\ezines\databas
e-0.yml,--file,C:\Users\James\.lando\compose\ezines\database-1.yml,--file,C:\Users\James\.lando\compose\ezines\database-2.yml,--file,C:\Users\James\.lando\compose\ezines\database-3.yml,--file,C:\Users\James\.lando\compose\
ezines\database-4.yml,--file,C:\Users\James\.lando\compose\ezines\database-5.yml,--file,C:\Users\James\.lando\compose\ezines\proxy-0.yml,exec,--detach,--env,PHP_MEMORY_LIMIT=-1,--user,root,database,/bin/sh,-c,/helpers/refr
esh-certs.sh > /cert-log.txt finished with code 4294967295
error: Looks like database is not running! It should be so this is a problem.
warn: Try running `lando logs -s database` to help locate the problem!
debug: Error
    at module.exports.sh.Promise.try.then (C:\snapshot\lando\build\cli\lib\shell.js:0:0)
From previous event:
    at Shell.sh (C:\snapshot\lando\build\cli\lib\shell.js:0:0)
    at Object.exports.dc (C:\snapshot\lando\build\cli\lib\bootstrap.js:0:0)
    at compose (C:\snapshot\lando\build\cli\lib\bootstrap.js:0:0)
    at exports.run.Promise.each.docker.isRunning.then.then (C:\snapshot\lando\build\cli\lib\router.js:0:0)
From previous event:
    at exports.run.Promise.each.datum (C:\snapshot\lando\build\cli\lib\router.js:0:0)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
From previous event:
    at Object.exports.run (C:\snapshot\lando\build\cli\lib\router.js:0:0)
    at run (C:\snapshot\lando\build\cli\lib\engine.js:0:0)
    at exports.eventWrapper.daemon.up.then.then (C:\snapshot\lando\build\cli\lib\router.js:0:0)
From previous event:
    at Object.exports.eventWrapper (C:\snapshot\lando\build\cli\lib\router.js:0:0)
    at Engine.module.exports.constructor.engineCmd (C:\snapshot\lando\build\cli\lib\engine.js:0:0)
    at Engine.run (C:\snapshot\lando\build\cli\lib\engine.js:0:0)
    at module.exports.app.events.on.app.events.on.lando.Promise.each.service (C:\snapshot\lando\build\cli\plugins\lando-core\app.js:0:0)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
From previous event:
    at AsyncEvents.module.exports.app.events.on.app.events.on (C:\snapshot\lando\build\cli\plugins\lando-core\app.js:0:0)
    at AsyncEvents.handle (C:\snapshot\lando\build\cli\lib\events.js:0:0)
    at emit.Promise.each.fn (C:\snapshot\lando\build\cli\lib\events.js:0:0)
From previous event:
    at AsyncEvents.emit (C:\snapshot\lando\build\cli\lib\events.js:0:0)
    at module.exports.start.initAndReport.then.then.then (C:\snapshot\lando\build\cli\lib\app.js:0:0)
From previous event:
    at App.start (C:\snapshot\lando\build\cli\lib\app.js:0:0)
    at Object.exports.appToggle (C:\snapshot\lando\build\cli\plugins\lando-core\lib\utils.js:0:0)
    at Object.run (C:\snapshot\lando\build\cli\plugins\lando-core\tasks\start.js:0:0)
    at module.exports.parseToYargs.checkForUpdates.then.lando.bootstrap.then.lando.events.emit.then.then.then.then.then (C:\snapshot\lando\build\cli\lib\cli.js:0:0)
From previous event:
    at module.exports.parseToYargs.checkForUpdates.then.lando.bootstrap.then.lando (C:\snapshot\lando\build\cli\lib\cli.js:0:0)
From previous event:
    at module.exports.parseToYargs.checkForUpdates.then (C:\snapshot\lando\build\cli\lib\cli.js:0:0)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
From previous event:
    at Object.handler (C:\snapshot\lando\build\cli\lib\cli.js:0:0)
    at Object.runCommand (C:\snapshot\lando\build\cli\node_modules\yargs\lib\command.js:238:44)
    at Object.parseArgs [as _parseArgs] (C:\snapshot\lando\build\cli\node_modules\yargs\yargs.js:1063:30)
    at Function.get [as argv] (C:\snapshot\lando\build\cli\node_modules\yargs\yargs.js:1004:21)
    at Cli.run (C:\snapshot\lando\build\cli\lib\cli.js:0:0)
    at Object.<anonymous> (C:\snapshot\lando\build\cli\bin\lando.js:0:0)
    at Module._compile (pkg/prelude/bootstrap.js:1254:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:711:10)
    at Module.load (internal/modules/cjs/loader.js:610:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:549:12)
    at Function.Module._load (internal/modules/cjs/loader.js:541:3)
    at Function.Module.runMain (pkg/prelude/bootstrap.js:1309:12)
    at startup (internal/bootstrap/node.js:274:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:608:3)

BOOMSHAKALAKA!!!

Your app has started up correctly.
Here are some vitals:

 NAME            ezines
 LOCATION        D:\wamp\www\ezines.local
 SERVICES        appserver, database
 APPSERVER URLS  https://localhost:32807
                 http://localhost:32808
                 http://ezines.local
                 https://ezines.local
```

**Tell us generally about your bug**

This error started occurring since upgrading Docker Desktop 2.1 -> 2.2.0.0. All containers all start and rebuild fine, and I can access the web service and connected database, however, commands such as `lando ssh ...` are not working.

If I recall correctly, Lando will download the latest version of Docker Desktop upon install, and as such, this will be an issue for all new users. There has been another issue posted at #1941 which is the same issue on Mac.

```bash
Traceback (most recent call last):
  File "docker-compose", line 6, in <module>
  File "compose\cli\main.py", line 72, in main
  File "compose\cli\main.py", line 128, in perform_command
  File "compose\cli\main.py", line 491, in exec_command
  File "compose\cli\main.py", line 1469, in call_docker
  File "subprocess.py", line 172, in call
  File "subprocess.py", line 394, in __init__
  File "subprocess.py", line 644, in _execute_child
TypeError: environment can only contain strings
[171336] Failed to execute script docker-compose
error: Looks like database is not running! It should be so this is a problem.
warn: Try running `lando logs -s database` to help locate the problem!
```

**Comment by blakestein** [comment]
I'm on windows, also just updated to 2.2.0 and while I'm not seeing docker composer issues I'm seeing a lot of `shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory` and general file system issues, like changes not being picked up on refresh. Not sure if that's related to this.

**Comment by alexfinnarn** [comment]
I have the same issue and can post logs, but for now I have...

macOS: 10.15.2
Docker for MacOS: 2.2.0.0
Lando: v3.0.0-rc.23

```
$ lando init
? From where should we get your app's codebase? pantheon
? Enter a Pantheon machine token [hidden]
? Which site? blah-blah

Error: spawn /Applications/Docker.app/Contents/Resources/bin/docker-compose EACCES
```

**Comment by fbray** [comment]
Seeing the same problem as alexfinnarn on Mac (and as logged in #1941).

`Error: spawn /Applications/Docker.app/Contents/Resources/bin/docker-compose EACCES`

MacOS:  10.13.6
Docker for mac:  2.2.0.0
Lando:  v3.0.0-rc.14

**Comment by pirog** [comment]
To everyone here, we only support the version of Docker Desktop that ships with Lando so if you have upgraded passed that point you are in HERE BE MONSTERS territory.  

We recommend that you roll back to the version of Docker Desktop that comes with Lando if you are having issues. When we are able to provide compatibility with the new Docker Desktop version we will cut a new Lando release, which will include that version, and indicate that in the changelog.

**Comment by gtjamesa** [comment]
> we do not pull down the latest version of Docker, specifically to avoid problems like this, we peg to a very specific version of docker so we can best ensure things work as intended.

@pirog That's good to know. Any idea when this particular version will be supported?

I'll downgrade Docker in the meantime.

Cheers!

**Comment by s1x** [comment]
@gtjamesa The same issue occured for me also with https://laradock.io/. Hence I guess there are some changes in the new current Docker breaking something.

**Comment by dm-ati** [comment]
The error on Mac seems to be with the most recent update to Docker Desktop, which for my upgrade yesterday updated to v2.2.0.0 
I started getting the following errors on `lando start` and `lando stop` following the update:
```
A647-Morrison:appletree-laravel-upgrade davidmorrisonerror: Error: /bin/sh: /Applications/Docker.app/Contents/Resources/bin/docker-compose: is a directory

$ lando stop
error: Error: spawn EACCES
```
Upon comparing a previous version of Docker Desktop (v2.1.0.5) to the updated (v2.2.0.0), it seems that `docker-compose` in the `/Applications/Docker.app/Contents/Resources/bin/` directory was an executable, but in the updated version the `docker-compose` executable was moved in to a `docker-compose` subdirectory under `bin`.  This would account for the two above errors, as well as several others listed in this thread (can't speak for the Windows version of Docker Desktop, but would assume its related).

I checked the source under the `~/.lando/` dir for instances of `bin/docker-compose` and only found references to the alias in `/usr/local/bin/docker-compose` which points to the correct new location for the `docker-compose` executable:
```
/Applications/Docker.app/Contents/Resources/bin/docker-compose/docker-compose
```

**Comment by dm-ati** [comment]
The Mac fix for this is to downgrade to the most recently supported version of Docker Desktop listed in the 2019 changelog (v2.1.0.5) as previously mentioned in this thread:

- https://github.com/lando/lando/blob/master/docs/help/2019-changelog.md#v300-rc23---november-26-2019

- https://docs.docker.com/docker-for-mac/release-notes/#docker-desktop-community-2105

To downgrade, double click the DMG file and drag-drop the Docker icon to the Applications folder, no need to uninstall anything.

**Comment by ezekel** [comment]
please help how to downgrade same error here

**Comment by s1x** [comment]
@ezekel See other issue from laradock or docker-compose -> https://github.com/laradock/laradock/issues/2473#issuecomment-577955368 / https://github.com/docker/compose/issues/7169#issuecomment-577897868

**Comment by davideprevosto** [comment]
@ezekel you could download the previous version: https://download.docker.com/mac/stable/39773/Docker.dmg

**Comment by ezekel** [comment]
@s1x ,

```
To update docker-compose (windows user)

   1. update python to 3.x
    2.execute this command pip install --upgrade docker-compose
    3. restart docker


```
How to update python to 3.x in windows?

**Comment by anaelbe** [comment]
@ezekel use chocolatey (https://chocolatey.org/), updating python did the trick for me

**Comment by hussainweb** [comment]
@dm-ati, this is where the docker-compose path is determined: https://github.com/lando/lando/blob/62a0d1bebfd2c196f06da88666a7afe69e0d56e0/lib/env.js#L34

I don't think Lando is following a symlink to get there (such as from `/usr/local/bin/docker-compose` which is the path on my system). If it did, we probably wouldn't have this error. But maybe it is done to support users who don't get these binaries symlinked in `PATH` for some reason.

**Comment by hussainweb** [comment]
Correction, that path was for docker binary. The docker-compose binary path is determined here: https://github.com/lando/lando/blob/62a0d1bebfd2c196f06da88666a7afe69e0d56e0/lib/env.js#L49

**Comment by pirog** [comment]
@hussainweb the preference is for direct invocation so we can ensure we are using a specific version and are not subject to the users `PATH`. Note that when we initially made Lando there were still MANY ways you could get Docker rolling on macOS so this is a decreasing concern but probably still a good design decision. 

That said, falling back to `PATH` if direct invocation is not possible might help us mitigate any future changes Docker makes to their binary paths

**Comment by hussainweb** [comment]
@pirog, thanks. I was also reviewing the code and seeing that it should work when I noticed you already fixed it in https://github.com/lando/lando/commit/dadb4f9eca1c81e16cecb0284324f838a620b3ab. I am looking forward to rc25 release now. Thanks!

**Comment by hussainweb** [comment]
@pirog, also, I agree with what you said. Personally, I would want this to be decoupled so that it can work better with any Docker version (which is kinda like what you did in this change). But that is your call as maintainers.

**Comment by hussainweb** [comment]
Finally, falling back to `PATH` in case it doesn't work is also tricky. For example, if you had checked only if the path exists, then it still wouldn't work because the path does exist but is a directory. So, you explicitly have to check if the path is executable AND is a file.

Maybe a different strategy such as setting the path via env variables might work if users want to try with multiple Docker versions on the same machine. If they have a usecase to run multiple Docker versions, it would be easy for them to set an environment variable. For regular users who use a single version of Docker, falling back to PATH seems reasonable. So, the order of check might be:
1. Custom Lando specific env variable
2. PATH
3. Hard-coded path like right now.

**Comment by pirog** [comment]
yeah i did some initial discovery work on that specific concern but there are some other big changes in this `2.2.0.0` release we need to figure out better before the next release. 

we also are going to be launching some mechanisms in a few weeks to help the project become more robust and sustainable so we can both stay on top of the ever changing toolscape a bit better and provide better and more reliable support/feedback to our users

on the docker front i sadly i dont think we will ever be in a position to officially support _any_ docker version but having a sane default that users can override seems reasonable and is certainly better aligned with how lando works for most other things

**Comment by pirog** [comment]
@hussainweb yup good call on checking for FILE and not a DIRECTORY, that will definitely be critical. 

On the customization front im guessing the global lando config file is that place we want to do that. in fact its possible you might already be able to customize there. of course every global config setting also has an associated envvar so im guessing by extension could still do it the way you suggest as well

**Comment by pirog** [comment]
going to close this in favor of #1975
