### ISSUE TITLE
Using lando generate:guide w/ Team Lando as the author I get an error

### ISSUE THREAD

**Issue by serundeputy** [lando/lando#1945]
1.  Update to the [latest version](https://github.com/lando/lando/releases) of Lando and make sure the issue isn't fixed already.
 
  * on `master` 

**Tell us about your setup**

  * running lando from `master` with `lando --secret-toggle` on

**Tell us about the command you were running**

When running `lando generate:guide` w/ Team Lando as the author I get an error:

```bash
└─ $ ∴ lando.dev guide:generate
? Guide title? Gff
? Guide description? what gff wants?
? Written by? Team Lando
? Best category? General
? URL of original content? 
? URL of example repo? example_replace
error: pic is not defined
```
```

**Tell us about the error you got**

here is `lando.dev guide:generate -vvv`:

```bash
debug: Emitting event cli-guide:generate-run
debug: Event cli-guide:generate-run has 0 listeners
error: ReferenceError: pic is not defined
    at eval (lodash.templateSources[0]:23:11)
    at Object.run (/home/gff/code/lando-ops/lando/plugins/lando-alliance/tasks/guide-generate.js:121:39)
    at lando.events.emit.then.then.then.then.then (/home/gff/code/lando-ops/lando/lib/cli.js:302:54)
From previous event:
    at lando.bootstrap.then.lando (/home/gff/code/lando-ops/lando/lib/cli.js:300:10)
From previous event:
    at checkForUpdates.then (/home/gff/code/lando-ops/lando/lib/cli.js:268:76)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
From previous event:
    at Object.handler (/home/gff/code/lando-ops/lando/lib/cli.js:268:42)
    at Object.runCommand (/home/gff/code/lando-ops/lando/node_modules/yargs/lib/command.js:238:44)
    at Object.parseArgs [as _parseArgs] (/home/gff/code/lando-ops/lando/node_modules/yargs/yargs.js:1063:30)
    at Function.get [as argv] (/home/gff/code/lando-ops/lando/node_modules/yargs/yargs.js:1004:21)
    at Cli.init (/home/gff/code/lando-ops/lando/lib/cli.js:211:51)
    at Cli.run (/home/gff/code/lando-ops/lando/lib/cli.js:345:10)
    at Object.<anonymous> (/home/gff/code/lando-ops/lando/bin/lando.js:53:7)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
debug: Logging metrics data {"command":"lando guide:generate","context":"local","devMode":false,"instance":"da9d651611abd9b6fd4c00f8c6fe13436f3f4269","nodeVersion":"v10.18.1","mode":"cli","os":{"type":"Linux","platform":"linux","release":"5.3.0-7625-generic","arch":"x64"},"product":"lando","version":"3.0.0-rc.23","message":"pic is not defined","stack":"ReferenceError: pic is not defined\n    at eval (lodash.templateSources[0]:23:11)\n    at Object.run (guide-generate.js:121:39)\n    at lando.events.emit.then.then.then.then.then (cli.js:302:54)\nFrom previous event:\n    at lando.bootstrap.then.lando (cli.js:300:10)\nFrom previous event:\n    at checkForUpdates.then (cli.js:268:76)\nFrom previous event:\n    at Object.handler (cli.js:268:42)\n    at Object.runCommand (command.js:238:44)\n    at Object.parseArgs [as _parseArgs] (yargs.js:1063:30)\n    at Function.get [as argv] (yargs.js:1004:21)\n    at Cli.init (cli.js:211:51)\n    at Cli.run (cli.js:345:10)\n    at Object.<anonymous> (lando.js:53:7)","action":"error","created":"2020-01-21T19:50:06.024Z"} to [{"report":true,"url":"https://metrics.lando.dev"}]

```

**Comment by pirog** [comment]
@serundeputy this seems like a good and easy bug to work on. Can you give it an attempt?

**Comment by serundeputy** [comment]
PR: https://github.com/lando/lando/pull/1946
