### ISSUE TITLE
TypeError: Invalid Version: untagged-cd0a57284f9dc4e6bc77

### ISSUE THREAD

**Issue by Geriler** [lando/lando#1973]
```
TypeError: Invalid Version: untagged-cd0a57284f9dc4e6bc77
    at new SemVer (/snapshot/lando/build/cli/node_modules/semver/semver.js:312:11)
    at compare (/snapshot/lando/build/cli/node_modules/semver/semver.js:585:39)
    at Function.lt (/snapshot/lando/build/cli/node_modules/semver/semver.js:619:10)
    at UpdateManager.updateAvailable (/snapshot/lando/build/cli/lib/updates.js:0:0)
    at lando.Promise.try.then (/snapshot/lando/build/cli/lib/cli.js:0:0)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
From previous event:
    at checkForUpdates (/snapshot/lando/build/cli/lib/cli.js:0:0)
    at Object.handler (/snapshot/lando/build/cli/lib/cli.js:0:0)
    at Object.runCommand (/snapshot/lando/build/cli/node_modules/yargs/lib/command.js:238:44)
    at Object.parseArgs [as _parseArgs] (/snapshot/lando/build/cli/node_modules/yargs/yargs.js:1063:30)
    at Function.get [as argv] (/snapshot/lando/build/cli/node_modules/yargs/yargs.js:1004:21)
    at Cli.run (/snapshot/lando/build/cli/lib/cli.js:0:0)
    at Object.<anonymous> (/snapshot/lando/build/cli/bin/lando.js:0:0)
    at Module._compile (pkg/prelude/bootstrap.js:1254:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:711:10)
    at Module.load (internal/modules/cjs/loader.js:610:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:549:12)
    at Function.Module._load (internal/modules/cjs/loader.js:541:3)
    at Function.Module.runMain (pkg/prelude/bootstrap.js:1309:12)
    at startup (internal/bootstrap/node.js:274:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:608:3)
```

Most likely, this error appeared after ![this release](https://github.com/lando/lando/releases/tag/untagged-cd0a57284f9dc4e6bc77)
UPD: Possible solution: remove this release
UPD2: Removing release didn't help

**Comment by aneek** [comment]
Same issue here. Lando not able to start.

**Comment by aneek** [comment]
Is there any solution implemented? Our whole organization is facing this issue from today morning.

**Comment by Geriler** [comment]
I looked at code in commit, after which lando stopped working, and could not find solution. The only solution I could find was to deploy project locally on nginx/apache.

**Comment by aneek** [comment]
That is a temporary solution mate. All our local development environment depends on it. :(

**Comment by aneek** [comment]
Solved it. Here it goes:
1. Navigate to the ".lando" directory in user's home.
2. Inside it go to the "cache" folder and remove the **updates** file.
3. Go inside a lando instance, and do a lando restart.
4. That is it.

**Comment by Geriler** [comment]
@aneek thanks for you solution

**Comment by jodyheavener** [comment]
@aneek thanks! This worked for me as well.

**Comment by soniktrooth** [comment]
This worked for me. 

Just in case it's useful to someone here is the contents of the file:

```
{"version":"untagged-cd0a57284f9dc4e6bc77","url":"https://github.com/lando/lando/releases/tag/untagged-cd0a57284f9dc4e6bc77","expires":1581051737384}
```

**Comment by campaignupgrade** [comment]
Solved for me. 

@Geriler can you edit the title and body of this message to reflect the error name so that other users can find this ticket? The vague title and screenshot means this issue is impossible to find via search. 

Use `TypeError: Invalid Version: untagged-cd0a57284f9dc4e6bc77` please
