### ISSUE TITLE
Nginx container fail to start with custom config

### ISSUE THREAD

**Issue by CecileBr** [lando/lando#1979]
**Tell us about your setup**

Lando version : v3.0.0-rc.23
Operating system : macOs Catalina Version 10.15.3

**Tell us about your `.lando.yml`**

```yml
name: qda2
recipe: lemp
config:
    webroot: web
    php: '7.2'
    conf:
        php: .lando/php.ini
services:
    appserver:
        config:
            server: .lando/nginx.conf
    database:
        type: mariadb:10.2
        portforward: 3307
    legacydb:
        type: mysql
        portforward: 3308
```
The `.lando/nginx.conf`

```conf
server {
    server_name  localhost;
    root   /app/web/;
    
    location / {
        try_files $uri /app.php$is_args$args;
    }
    # DEV
    location ~ ^/(app_dev|config)\.php(/|$) {
        fastcgi_pass fpm:9000;
        fastcgi_split_path_info ^(.+\.php)(/.*)$;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        fastcgi_param DOCUMENT_ROOT $realpath_root;
    }
    # PROD
    location ~ ^/app\.php(/|$) {
        fastcgi_pass fpm:9000;
        fastcgi_split_path_info ^(.+\.php)(/.*)$;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        fastcgi_param DOCUMENT_ROOT $realpath_root;
        internal;
    }
    location ~ \.php$ {
        return 404;
    }
}
```

**Tell us about the command you were running**

```bash
lando start
```

**Tell us about the error you got**

Rerun the command that produced your error in `debug` mode. Note that `debug` mode is run like this `lando command -vvv`. Paste in the error and the `~100` lines that proceeded it.

*Example:*

```bash
lando start -vvv
#Log for appserver error
Starting qda2_appserver_1 ... done
Starting qda2_appserver_nginx_1 ... done
verbose: /Applications/Docker.app/Contents/Resources/bin/docker-compose,--project-name,qda2,--file,/Users/CecileBriard/.lando/compose/qda2/globals-0.yml,--file,/Users/CecileBriard/.lando/compose/qda2/appserver-0.yml,--file,/Users/CecileBriard/.lando/compose/qda2/appserver-1.yml,--file,/Users/CecileBriard/.lando/compose/qda2/appserver-2.yml,--file,/Users/CecileBriard/.lando/compose/qda2/appserver-3.yml,--file,/Users/CecileBriard/.lando/compose/qda2/appserver-4.yml,--file,/Users/CecileBriard/.lando/compose/qda2/appserver-5.yml,--file,/Users/CecileBriard/.lando/compose/qda2/appserver-6.yml,--file,/Users/CecileBriard/.lando/compose/qda2/appserver-7.yml,--file,/Users/CecileBriard/.lando/compose/qda2/appserver-8.yml,--file,/Users/CecileBriard/.lando/compose/qda2/database-0.yml,--file,/Users/CecileBriard/.lando/compose/qda2/database-1.yml,--file,/Users/CecileBriard/.lando/compose/qda2/database-2.yml,--file,/Users/CecileBriard/.lando/compose/qda2/database-3.yml,--file,/Users/CecileBriard/.lando/compose/qda2/database-4.yml,--file,/Users/CecileBriard/.lando/compose/qda2/database-5.yml,--file,/Users/CecileBriard/.lando/compose/qda2/legacydb-0.yml,--file,/Users/CecileBriard/.lando/compose/qda2/legacydb-1.yml,--file,/Users/CecileBriard/.lando/compose/qda2/legacydb-2.yml,--file,/Users/CecileBriard/.lando/compose/qda2/legacydb-3.yml,--file,/Users/CecileBriard/.lando/compose/qda2/legacydb-4.yml,--file,/Users/CecileBriard/.lando/compose/qda2/legacydb-5.yml,--file,/Users/CecileBriard/.lando/compose/qda2/proxy-0.yml,up,--detach,--no-recreate,--remove-orphans,appserver_nginx finished with code 0
verbose: Running pid10 ["/Applications/Docker.app/Contents/Resources/bin/docker-compose","--project-name","qda2","--file","/Users/CecileBriard/.lando/compose/qda2/globals-0.yml","--file","/Users/CecileBriard/.lando/compose/qda2/appserver-0.yml","--file","/Users/CecileBriard/.lando/compose/qda2/appserver-1.yml","--file","/Users/CecileBriard/.lando/compose/qda2/appserver-2.yml","--file","/Users/CecileBriard/.lando/compose/qda2/appserver-3.yml","--file","/Users/CecileBriard/.lando/compose/qda2/appserver-4.yml","--file","/Users/CecileBriard/.lando/compose/qda2/appserver-5.yml","--file","/Users/CecileBriard/.lando/compose/qda2/appserver-6.yml","--file","/Users/CecileBriard/.lando/compose/qda2/appserver-7.yml","--file","/Users/CecileBriard/.lando/compose/qda2/appserver-8.yml","--file","/Users/CecileBriard/.lando/compose/qda2/database-0.yml","--file","/Users/CecileBriard/.lando/compose/qda2/database-1.yml","--file","/Users/CecileBriard/.lando/compose/qda2/database-2.yml","--file","/Users/CecileBriard/.lando/compose/qda2/database-3.yml","--file","/Users/CecileBriard/.lando/compose/qda2/database-4.yml","--file","/Users/CecileBriard/.lando/compose/qda2/database-5.yml","--file","/Users/CecileBriard/.lando/compose/qda2/legacydb-0.yml","--file","/Users/CecileBriard/.lando/compose/qda2/legacydb-1.yml","--file","/Users/CecileBriard/.lando/compose/qda2/legacydb-2.yml","--file","/Users/CecileBriard/.lando/compose/qda2/legacydb-3.yml","--file","/Users/CecileBriard/.lando/compose/qda2/legacydb-4.yml","--file","/Users/CecileBriard/.lando/compose/qda2/legacydb-5.yml","--file","/Users/CecileBriard/.lando/compose/qda2/proxy-0.yml","exec","--detach","--env","PHP_MEMORY_LIMIT=-1","--user","root","appserver_nginx","/bin/sh","-c","/helpers/refresh-certs.sh > /cert-log.txt"] in /Users/CecileBriard/Documents/WORK/QdA/QuotidienDeLArt-V2 with options {"mode":"attach","detached":false}
debug: With stdio={"stdio":"inherit"}, mode=attach, detached=false, cwd=/Users/CecileBriard/Documents/WORK/QdA/QuotidienDeLArt-V2
ERROR: Container 312597917b08318b3a8a2335942ed61edb666fedea12c8c1ffbef97c3a46a53a is not running
verbose: /Applications/Docker.app/Contents/Resources/bin/docker-compose,--project-name,qda2,--file,/Users/CecileBriard/.lando/compose/qda2/globals-0.yml,--file,/Users/CecileBriard/.lando/compose/qda2/appserver-0.yml,--file,/Users/CecileBriard/.lando/compose/qda2/appserver-1.yml,--file,/Users/CecileBriard/.lando/compose/qda2/appserver-2.yml,--file,/Users/CecileBriard/.lando/compose/qda2/appserver-3.yml,--file,/Users/CecileBriard/.lando/compose/qda2/appserver-4.yml,--file,/Users/CecileBriard/.lando/compose/qda2/appserver-5.yml,--file,/Users/CecileBriard/.lando/compose/qda2/appserver-6.yml,--file,/Users/CecileBriard/.lando/compose/qda2/appserver-7.yml,--file,/Users/CecileBriard/.lando/compose/qda2/appserver-8.yml,--file,/Users/CecileBriard/.lando/compose/qda2/database-0.yml,--file,/Users/CecileBriard/.lando/compose/qda2/database-1.yml,--file,/Users/CecileBriard/.lando/compose/qda2/database-2.yml,--file,/Users/CecileBriard/.lando/compose/qda2/database-3.yml,--file,/Users/CecileBriard/.lando/compose/qda2/database-4.yml,--file,/Users/CecileBriard/.lando/compose/qda2/database-5.yml,--file,/Users/CecileBriard/.lando/compose/qda2/legacydb-0.yml,--file,/Users/CecileBriard/.lando/compose/qda2/legacydb-1.yml,--file,/Users/CecileBriard/.lando/compose/qda2/legacydb-2.yml,--file,/Users/CecileBriard/.lando/compose/qda2/legacydb-3.yml,--file,/Users/CecileBriard/.lando/compose/qda2/legacydb-4.yml,--file,/Users/CecileBriard/.lando/compose/qda2/legacydb-5.yml,--file,/Users/CecileBriard/.lando/compose/qda2/proxy-0.yml,exec,--detach,--env,PHP_MEMORY_LIMIT=-1,--user,root,appserver_nginx,/bin/sh,-c,/helpers/refresh-certs.sh > /cert-log.txt finished with code 1
error: Looks like appserver_nginx is not running! It should be so this is a problem.
warn: Try running `lando logs -s appserver_nginx` to help locate the problem!
debug: Error
    at module.exports.sh.Promise.try.then (/snapshot/lando/build/cli/lib/shell.js:0:0)
From previous event:
    at Shell.sh (/snapshot/lando/build/cli/lib/shell.js:0:0)
    at Object.exports.dc (/snapshot/lando/build/cli/lib/bootstrap.js:0:0)
    at compose (/snapshot/lando/build/cli/lib/bootstrap.js:0:0)
    at exports.run.Promise.each.docker.isRunning.then.then (/snapshot/lando/build/cli/lib/router.js:0:0)
From previous event:
    at exports.run.Promise.each.datum (/snapshot/lando/build/cli/lib/router.js:0:0)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
From previous event:
    at Object.exports.run (/snapshot/lando/build/cli/lib/router.js:0:0)
    at run (/snapshot/lando/build/cli/lib/engine.js:0:0)
    at exports.eventWrapper.daemon.up.then.then (/snapshot/lando/build/cli/lib/router.js:0:0)
From previous event:
    at Object.exports.eventWrapper (/snapshot/lando/build/cli/lib/router.js:0:0)
    at Engine.module.exports.constructor.engineCmd (/snapshot/lando/build/cli/lib/engine.js:0:0)
    at Engine.run (/snapshot/lando/build/cli/lib/engine.js:0:0)
    at module.exports.app.events.on.app.events.on.lando.Promise.each.service (/snapshot/lando/build/cli/plugins/lando-core/app.js:0:0)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
From previous event:
    at AsyncEvents.module.exports.app.events.on.app.events.on (/snapshot/lando/build/cli/plugins/lando-core/app.js:0:0)
    at AsyncEvents.handle (/snapshot/lando/build/cli/lib/events.js:0:0)
    at emit.Promise.each.fn (/snapshot/lando/build/cli/lib/events.js:0:0)
From previous event:
    at AsyncEvents.emit (/snapshot/lando/build/cli/lib/events.js:0:0)
    at module.exports.start.initAndReport.then.then.then (/snapshot/lando/build/cli/lib/app.js:0:0)
From previous event:
    at App.start (/snapshot/lando/build/cli/lib/app.js:0:0)
    at Object.exports.appToggle (/snapshot/lando/build/cli/plugins/lando-core/lib/utils.js:0:0)
    at Object.run (/snapshot/lando/build/cli/plugins/lando-core/tasks/start.js:0:0)
    at module.exports.parseToYargs.checkForUpdates.then.lando.bootstrap.then.lando.events.emit.then.then.then.then.then (/snapshot/lando/build/cli/lib/cli.js:0:0)
From previous event:
    at module.exports.parseToYargs.checkForUpdates.then.lando.bootstrap.then.lando (/snapshot/lando/build/cli/lib/cli.js:0:0)
From previous event:
    at module.exports.parseToYargs.checkForUpdates.then (/snapshot/lando/build/cli/lib/cli.js:0:0)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
From previous event:
    at Object.handler (/snapshot/lando/build/cli/lib/cli.js:0:0)
    at Object.runCommand (/snapshot/lando/build/cli/node_modules/yargs/lib/command.js:238:44)
    at Object.parseArgs [as _parseArgs] (/snapshot/lando/build/cli/node_modules/yargs/yargs.js:1063:30)
    at Function.get [as argv] (/snapshot/lando/build/cli/node_modules/yargs/yargs.js:1004:21)
    at Cli.run (/snapshot/lando/build/cli/lib/cli.js:0:0)
    at lando.bootstrap.then.lando.getApp.init.then (/snapshot/lando/build/cli/bin/lando.js:0:0)
From previous event:
    at lando.bootstrap.then.lando (/snapshot/lando/build/cli/bin/lando.js:0:0)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
From previous event:
    at Object.<anonymous> (/snapshot/lando/build/cli/bin/lando.js:0:0)
    at Module._compile (pkg/prelude/bootstrap.js:1254:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:711:10)
    at Module.load (internal/modules/cjs/loader.js:610:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:549:12)
    at Function.Module._load (internal/modules/cjs/loader.js:541:3)
    at Function.Module.runMain (pkg/prelude/bootstrap.js:1309:12)
    at startup (internal/bootstrap/node.js:274:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:608:3)
```

If I run `lando logs -s appserver_nginx`, I get

``` bash
appserver_nginx_1  | This is a debian container
appserver_nginx_1  | user-perms.sh kicking off as user uid=0(root) gid=0(root) groups=0(root)
appserver_nginx_1  | Lando ENVVARS set at
appserver_nginx_1  | LANDO_WEBROOT_USER: www-data
appserver_nginx_1  | LANDO_WEBROOT_GROUP: www-data
appserver_nginx_1  | LANDO_WEBROOT_UID: 501
appserver_nginx_1  | LANDO_WEBROOT_GID: 20
appserver_nginx_1  | LANDO_HOST_UID: 501
appserver_nginx_1  | LANDO_HOST_GID: 20
appserver_nginx_1  | Making sure correct user:group (www-data:www-data) exists...
appserver_nginx_1  | Remapping ownership to handle docker volume sharing...
appserver_nginx_1  | LANDO_HOST_UID: 501
appserver_nginx_1  | LANDO_HOST_GID: 20
appserver_nginx_1  | Resetting www-data:www-data from 501:20 to 501:20
appserver_nginx_1  | www-data:www-data is now running as uid=501(www-data) gid=20(dialout) groups=20(dialout),33(www-data)!
appserver_nginx_1  | And here. we. go.
appserver_nginx_1  | Scanning /lando/keys for keys...
appserver_nginx_1  | Found keys 
appserver_nginx_1  | Scanning /user/.ssh for keys...
appserver_nginx_1  | Found keys /user/.ssh/id_ed25519 /user/.ssh/known_hosts.old /user/.ssh/id_rsa
appserver_nginx_1  | Ensuring permissions and ownership of /user/.ssh/id_ed25519...
appserver_nginx_1  | Checking whether /user/.ssh/id_ed25519 is a private key...
appserver_nginx_1  | Ensuring permissions and ownership of /user/.ssh/known_hosts.old...
appserver_nginx_1  | chmod: cannot access '/user/.ssh/known_hosts.old.pub': No such file or directory
appserver_nginx_1  | Checking whether /user/.ssh/known_hosts.old is a private key...
appserver_nginx_1  | Ensuring permissions and ownership of /user/.ssh/id_rsa...
appserver_nginx_1  | Checking whether /user/.ssh/id_rsa is a private key...
appserver_nginx_1  | Scanning /var/www/.ssh for keys...
appserver_nginx_1  | Found keys 
appserver_nginx_1  | Using the following keys: /user/.ssh/id_ed25519 /user/.ssh/id_rsa
appserver_nginx_1  | Running command /bin/bash -c mkdir -p /opt/bitnami/nginx/conf/vhosts && render-template /opt/bitnami/extra/nginx/templates/default.conf.tpl > /opt/bitnami/nginx/conf/vhosts/lando.conf && /entrypoint.sh /run.sh
appserver_nginx_1  | Running with exec!
appserver_nginx_1  | 
appserver_nginx_1  | Welcome to the Bitnami nginx container
appserver_nginx_1  | Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-nginx
appserver_nginx_1  | Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-nginx/issues
appserver_nginx_1  | Send us your feedback at containers@bitnami.com
appserver_nginx_1  | 
appserver_nginx_1  | INFO  ==> ** Starting NGINX setup **
appserver_nginx_1  | INFO  ==> Validating settings in NGINX_* env vars...
appserver_nginx_1  | INFO  ==> Initializing NGINX...
appserver_nginx_1  | DEBUG ==> Custom configuration detected. Using it...
appserver_nginx_1  | 
appserver_nginx_1  | INFO  ==> ** NGINX setup finished! **
appserver_nginx_1  | INFO  ==> ** Starting NGINX **
appserver_nginx_1  | 2020/02/12 12:46:55 [emerg] 1#0: "server" directive is not allowed here in /opt/bitnami/nginx/conf/nginx.conf:1
appserver_nginx_1  | nginx: [emerg] "server" directive is not allowed here in /opt/bitnami/nginx/conf/nginx.conf:1
```

**Tell us generally about your bug**

```bash
1. Tried to start start a legacy project with the above config files.
2. Got the error above with appserver container
3. Opened `https://qda2.lndo.site/` and got `404 page not found`
```

If I delete the custom nginx config from `lando.yml`, I don't get any error.

**Comment by troseman** [comment]
It looks like you want a custom vhosts file, not a custom nginx config.
This works for me:


```
recipe: lemp
config:
  via: nginx
  config:
    # custom nginx vhosts config
    vhosts: .lando/nginx.conf
    # custom php.ini
    php: config/lando/php/my-php.ini
```
