### ISSUE TITLE
syntax errors thrown on build steps on service.appserver_nginx

### ISSUE THREAD

**Issue by TMFEspresso** [lando/lando#1990]
if you include something like this in your landofile:

```
recipe: wordpress
service:
  appserver_nginx:
    build_as_root:
      - echo 'hello world'
```

lando itself throws a syntax error. 

```
Unhandled rejection TypeError: Cannot read property 'split' of undefined
    at _.map.map.service (/Users/kcottrell/tmp/lando/plugins/lando-services/lib/utils.js:97:74)
    at arrayMap (/Users/kcottrell/tmp/lando/node_modules/lodash/lodash.js:639:23)
    at Function.map (/Users/kcottrell/tmp/lando/node_modules/lodash/lodash.js:9556:14)
    at interceptor (/Users/kcottrell/tmp/lando/node_modules/lodash/lodash.js:16993:35)
    at Function.thru (/Users/kcottrell/tmp/lando/node_modules/lodash/lodash.js:8797:14)
    at /Users/kcottrell/tmp/lando/node_modules/lodash/lodash.js:4374:28
    at arrayReduce (/Users/kcottrell/tmp/lando/node_modules/lodash/lodash.js:683:21)
    at baseWrapperValue (/Users/kcottrell/tmp/lando/node_modules/lodash/lodash.js:4373:14)
    at LodashWrapper.wrapperValue (/Users/kcottrell/tmp/lando/node_modules/lodash/lodash.js:9052:14)
    at Object.exports.parseConfig (/Users/kcottrell/tmp/lando/plugins/lando-services/lib/utils.js:105:4)
    at AsyncEvents.app.events.on (/Users/kcottrell/tmp/lando/plugins/lando-services/app.js:44:28)
    at AsyncEvents.handle (/Users/kcottrell/tmp/lando/lib/events.js:84:25)
    at Promise.each.fn (/Users/kcottrell/tmp/lando/lib/events.js:115:21)
```

This occurs in both `v3.0.0-rc.23` of lando and the latest, cloned down from github and running as `lando.dev`.

**Comment by TMFEspresso** [comment]
So this doesn't just affect build steps, but anything under `appserver_nginx`: 

```
services:
  appserver_nginx:
      overrides:
        volumes:
        - ./config/.bashrc:~/.bashrc
```

I wonder if this is due to the service name containing a `_`?

**Comment by Leamsi9** [comment]
I am getting the same error with:
```name: WebHooks
recipe: laravel
config:
  php: '7.3'
  via: apache
  webroot: .
  database: mariadb
  cache: none
  xdebug: false


----------------------------------------
**Error message:**

Unhandled rejection TypeError: Cannot read property 'split' of undefined
    at exports.parseConfig._.map.map.service (/snapshot/lando/build/cli/plugins/lando-services/lib/utils.js:0:0)
    at arrayMap (/snapshot/lando/build/cli/node_modules/lodash/lodash.js:639:23)
    at Function.map (/snapshot/lando/build/cli/node_modules/lodash/lodash.js:9556:14)
    at interceptor (/snapshot/lando/build/cli/node_modules/lodash/lodash.js:16993:35)
    at Function.thru (/snapshot/lando/build/cli/node_modules/lodash/lodash.js:8797:14)
    at /snapshot/lando/build/cli/node_modules/lodash/lodash.js:4374:28
    at arrayReduce (/snapshot/lando/build/cli/node_modules/lodash/lodash.js:683:21)
    at baseWrapperValue (/snapshot/lando/build/cli/node_modules/lodash/lodash.js:4373:14)
    at LodashWrapper.wrapperValue (/snapshot/lando/build/cli/node_modules/lodash/lodash.js:9052:14)
    at Object.exports.parseConfig (/snapshot/lando/build/cli/plugins/lando-services/lib/utils.js:0:0)
    at AsyncEvents.module.exports.app.events.on (/snapshot/lando/build/cli/plugins/lando-services/app.js:0:0)
    at AsyncEvents.handle (/snapshot/lando/build/cli/lib/events.js:0:0)
    at emit.Promise.each.fn (/snapshot/lando/build/cli/lib/events.js:0:0)
From previous event:
    at AsyncEvents.emit (/snapshot/lando/build/cli/lib/events.js:0:0)
    at module.exports.init.loadPlugins.then (/snapshot/lando/build/cli/lib/app.js:0:0)
From previous event:
    at App.init (/snapshot/lando/build/cli/lib/app.js:0:0)
    at lando.bootstrap.then.lando (/snapshot/lando/build/cli/bin/lando.js:0:0)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
From previous event:
    at Object.<anonymous> (/snapshot/lando/build/cli/bin/lando.js:0:0)
    at Module._compile (pkg/prelude/bootstrap.js:1254:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:711:10)
    at Module.load (internal/modules/cjs/loader.js:610:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:549:12)
    at Function.Module._load (internal/modules/cjs/loader.js:541:3)
    at Function.Module.runMain (pkg/prelude/bootstrap.js:1309:12)
    at startup (internal/bootstrap/node.js:274:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:608:3)

**Comment by graid2030** [comment]
I have the same problem
```yml
name: somename
recipe: laravel
config:
  webroot: public
  php: '7.3'
  via: nginx
  database: mysql
  cache: redis
  xdebug: false
services:
  appserver_nginx:
    run_as_root:
      - "groupadd -g 999 vboxsf"
      - "usermod -G vboxsf -a www-data"
```

**Comment by graid2030** [comment]
As I understand it, there is no service with this name, I also tried to use "nginx" as the name of the service with the same result

**Comment by pirog** [comment]
@TMFEspresso we didnt anticipate users would attempt to do build steps or other overrides with lando managed services like `appserver_nginx` although i think this may be happenstance fixed now.

**Comment by pirog** [comment]
@TMFEspresso ok i can replicate this on `master` still. Regardless of whether we anticipate/expect this or not this _should_ work.

**Comment by TMFEspresso** [comment]
Thanks for looking into it! I really appreciate it :)

**Comment by pirog** [comment]
@TMFEspresso thanks for flagging it!

**Comment by pirog** [comment]
Alright, this should be fixed in the next release!
