### ISSUE TITLE
Error : 502 Bad Gateway

### ISSUE THREAD

**Issue by Asterovim** [lando/lando#2085]
I use use docker 2.2.0.3 (42716). Channel stable. Engine : 19.03.5 Lastest lando : v3.0.0-rrc.1. Windows 10.

I have just edited one file this morning and i have a white page. I have restart with lando restart and i have this error :
```
PS D:\www\mylando> lando restart
Stopping and restarting your app...Shiny!
Killing mylando_appserver_nginx_1  ... done
Killing mylando_database_1         ... done
Killing mylando_elasticsearchieb_1 ... done
Killing mylando_appserver_1        ... done
landoproxyhyperion5000gandalfedition_proxy_1 is up-to-date
Starting mylando_appserver_1 ... done
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  811k  100  811k    0     0   241k      0  0:00:03  0:00:03 --:--:--  241k
Changed current directory to /var/www/.composer
    1/1:        http://repo.packagist.org/p/provider-latest$14f78b92361b78506446ccf4bd436ccb6a40ce33ba6fa47348fe0647f151904f.json
    Finished: success: 1, skipped: 0, failure: 0, total: 1
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Package container-interop/container-interop is abandoned, you should avoid using it. Use psr/container instead.
Generating autoload files


  [Seld\JsonLint\ParsingException]
  "./composer.json" does not contain valid JSON
  Parse error on line 1:

  ^
  Expected one of: 'STRING', 'NUMBER', 'NULL', 'TRUE', 'FALSE', '{', '['


error: Looks like one of your build steps failed! with Error
    at C:\snapshot\lando\build\cli\lib\shell.js
From previous event:
    at Shell.sh (C:\snapshot\lando\build\cli\lib\shell.js)
    at Object.dc (C:\snapshot\lando\build\cli\lib\bootstrap.js)
    at compose (C:\snapshot\lando\build\cli\lib\bootstrap.js)
From previous event:
    at C:\snapshot\lando\build\cli\lib\router.js
    at processImmediate (internal/timers.js:439:21)
From previous event:
    at Object.run (C:\snapshot\lando\build\cli\lib\router.js)
    at run (C:\snapshot\lando\build\cli\lib\engine.js)
    at C:\snapshot\lando\build\cli\lib\router.js
From previous event:
    at Object.eventWrapper (C:\snapshot\lando\build\cli\lib\router.js)
    at Engine.engineCmd (C:\snapshot\lando\build\cli\lib\engine.js)
    at Engine.run (C:\snapshot\lando\build\cli\lib\engine.js)
    at Object.runBuild (C:\snapshot\lando\build\cli\plugins\lando-services\lib\utils.js)
    at AsyncEvents.<anonymous> (C:\snapshot\lando\build\cli\plugins\lando-services\app.js)
    at AsyncEvents.handle (C:\snapshot\lando\build\cli\lib\events.js)
    at C:\snapshot\lando\build\cli\lib\events.js
From previous event:
    at AsyncEvents.emit (C:\snapshot\lando\build\cli\lib\events.js)
From previous event:
    at App.start (C:\snapshot\lando\build\cli\lib\app.js)
    at C:\snapshot\lando\build\cli\lib\app.js
From previous event:
    at App.restart (C:\snapshot\lando\build\cli\lib\app.js)
    at Object.run (C:\snapshot\lando\build\cli\plugins\lando-core\tasks\restart.js)
    at C:\snapshot\lando\build\cli\lib\cli.js
From previous event:
    at Object.handler (C:\snapshot\lando\build\cli\lib\cli.js)
    at Object.runCommand (C:\snapshot\lando\build\cli\node_modules\yargs\lib\command.js:238:44)
    at Object.parseArgs [as _parseArgs] (C:\snapshot\lando\build\cli\node_modules\yargs\yargs.js:1063:30)
    at Function.get [as argv] (C:\snapshot\lando\build\cli\node_modules\yargs\yargs.js:1004:21)
    at Cli.init (C:\snapshot\lando\build\cli\lib\cli.js)
    at Cli.run (C:\snapshot\lando\build\cli\lib\cli.js)
From previous event:
    at C:\snapshot\lando\build\cli\bin\lando.js
    at processImmediate (internal/timers.js:439:21)
From previous event:
    at Object.<anonymous> (C:\snapshot\lando\build\cli\bin\lando.js)
    at Module._compile (pkg/prelude/bootstrap.js:1324:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:993:10)
    at Module.load (internal/modules/cjs/loader.js:813:32)
    at Function.Module._load (internal/modules/cjs/loader.js:725:14)
    at Function.Module.runMain (pkg/prelude/bootstrap.js:1379:12)
    at internal/main/run_main_module.js:17:11
warn: This **MAY** prevent your app from working
warn: Check for errors above, fix them, and try again
```
My app didn't work. I have test with lando rebuild -y and same problem :(

**Comment by Asterovim** [comment]
I have completly delete my docker and lando. I have restart them and it's work. 
But if i edit one file with sub system linux (WSL) i have this error. 

I think it is a new problem with WSL and lastest update of lando / docker.

**Comment by rabauss** [comment]
``"./composer.json" does not contain valid JSON`` is there something wrong in your composer configuration?
You could disable the ``composer install`` on startup and manually call ``lando composer install``

**Comment by Asterovim** [comment]
Same problem when disable composer install and lando composer install.

I can execute composer install with WSL whitout any problem/error.

**Comment by rabauss** [comment]
Which composer version do you have? maybe you have a different version in your WSL than in the lando container!

**Comment by Asterovim** [comment]
Problem is fixed with lastest release rc2.

**Comment by npoku** [comment]
Recently encountered this problem on a Drupal 8 build with Lando v3.1.2 and Docker 3.3.0. What worked for me was a simple `lando drush cr`. Sad to say, I had been chasing a ghost for two days and all I needed was a simple clearing of my cache.
