### ISSUE TITLE
Tooling commands never terminate

### ISSUE THREAD

**Issue by DanielKulbe** [lando/lando#2137]
**Tell us about your setup**
v3.0.0-rrc.3 on Linux Mint 19.3 Cinnamon

**Tell us about your `.lando.yml`**
I'm using the Drupal 8 receipe, where I have added Node.js 10.15.1 with Yarn 1.22.0 in an additional custom build step. I did not want an additional container just for building assets from time to time.
```yml
recipe: drupal8

config:
  via: 'nginx'
  database: 'mariadb:10.2'
  drush: '^9.5'
  php: '7.3'

tooling:
  yarn:
    service: appserver
    user: 1000
  update-translation:
    service: appserver
    description: Import translations from source
    user: 1000
    cmd: drush locale:check && drush locale:update
```

I have some simple scripts defined in `package.json` to build my assets.
```json
{
  "scripts": {
    "postinstall": "patch-package",
    "build": "webpack",
    "build-core": "webpack --env.h5p=skip",
    "build-h5p": "webpack --env.h5p=only",
    "test": "echo \"Error: no test specified\" && exit 1",
    "watch": "webpack --watch"
  },
}
```

**Tell us about the command you were running**

It is happening for some `lando drush` commands like `lando drush locale:update` as well as for most `lando yarn` commands (webpack, see `package.json`). Commands like `lando drush cache:rebuild` work just fine.

**Tell us about the error you got**

After a few seconds the terminal exits, but proceeds the command, sometimes with more indention. At the end of the command, it does not terminate. I have to push Ctrl+C to get back to input.

```bash
daniel:~/workspace/learnattack (master) $ lando update-translation -vvvv
info: Bootstraping...
silly: It's not particularly silly, is it?
info: config bootstrap beginning...
debug: Emitting event pre-bootstrap-config
debug: Event pre-bootstrap-config has 0 listeners
verbose: Loading event pre-engine-start priority 2
verbose: Loading event pre-engine-start priority 3
verbose: Plugin lando-core loaded from /snapshot/lando/build/cli/plugins/lando-core/index.js
debug: Plugin lando-core has {"config":{"appEnv":{"COLUMNS":256,"LANDO":"ON","LANDO_WEBROOT_USER":"www-data","LANDO_WEBROOT_GROUP":"www-data","TERM":"xterm","LANDO_HOST_UID":"1000","LANDO_HOST_GID":"1000","LANDO_HOST_USER":"daniel","LANDO_CA_CERT":"/lando/certs/lndo.site.pem","LANDO_CA_KEY":"/lando/certs/lndo.site.key","LANDO_CONFIG_DIR":"/home/daniel/.lando","LANDO_DOMAIN":"lndo.site","LANDO_HOST_HOME":"/home/daniel","LANDO_HOST_OS":"linux","LANDO_HOST_IP":"192.168.2.122","LANDO_MOUNT":"/app"},"appLabels":{"io.lando.container":"TRUE","io.lando.id":"6e1986c67664132f04a9c03123ad75377844cefe"},"gid":"1000","uid":"1000","username":"daniel","caCert":"/home/daniel/.lando/certs/lndo.site.pem","caDomain":"lndo.site","caKey":"/home/daniel/.lando/certs/lndo.site.key","caProject":"landocasetupkenobi38ahsoka6e1986c67664132f04a9c03123ad75377844cefe"}}
verbose: Plugin lando-events loaded from /snapshot/lando/build/cli/plugins/lando-events/index.js
debug: Plugin lando-events has undefined
verbose: Loading event pre-engine-start priority 1
verbose: Loading event pre-engine-start priority 2
verbose: Loading event pre-engine-start priority 3
verbose: Plugin lando-networking loaded from /snapshot/lando/build/cli/plugins/lando-networking/index.js
debug: Plugin lando-networking has {"config":{"networkBridge":"lando_bridge_network"}}
verbose: Plugin lando-pantheon loaded from /snapshot/lando/build/cli/plugins/lando-pantheon/index.js
debug: Plugin lando-pantheon has undefined
verbose: Loading event post-bootstrap-config priority 5
verbose: Plugin lando-proxy loaded from /snapshot/lando/build/cli/plugins/lando-proxy/index.js
debug: Plugin lando-proxy has {"config":{"proxy":"ON","proxyCert":"/certs/cert.crt","proxyKey":"/certs/cert.key","proxyName":"landoproxyhyperion5000gandalfedition","proxyDash":"58087","proxyCache":"proxyCache","proxyHttpPort":"80","proxyHttpsPort":"443","proxyHttpFallbacks":["8000","8080","8888","8008"],"proxyHttpsFallbacks":["444","4433","4444","4443"],"proxyDomain":"lndo.site","proxyIp":"127.0.0.1"}}
verbose: Plugin lando-recipes loaded from /snapshot/lando/build/cli/plugins/lando-recipes/index.js
debug: Plugin lando-recipes has undefined
verbose: Plugin lando-services loaded from /snapshot/lando/build/cli/plugins/lando-services/index.js
debug: Plugin lando-services has undefined
verbose: Plugin lando-sharing loaded from /snapshot/lando/build/cli/plugins/lando-sharing/index.js
debug: Plugin lando-sharing has undefined
verbose: Plugin lando-test loaded from /snapshot/lando/build/cli/plugins/lando-test/index.js
debug: Plugin lando-test has {"plugin-test":true}
verbose: Plugin lando-tooling loaded from /snapshot/lando/build/cli/plugins/lando-tooling/index.js
debug: Plugin lando-tooling has undefined
debug: Emitting event post-bootstrap-config
debug: Event post-bootstrap-config has 1 listeners
info: config bootstrap completed.
info: tasks bootstrap beginning...
debug: Emitting event pre-bootstrap-tasks
debug: Event pre-bootstrap-tasks has 0 listeners
debug: Autoloaded task config
debug: Autoloaded task destroy
debug: Autoloaded task info
debug: Autoloaded task list
debug: Autoloaded task logs
debug: Autoloaded task poweroff
debug: Autoloaded task rebuild
debug: Autoloaded task restart
debug: Autoloaded task share
debug: Autoloaded task start
debug: Autoloaded task stop
debug: Autoloaded task version
debug: Autoloaded task init
debug: Autoloaded task ssh
debug: Emitting event post-bootstrap-tasks
debug: Event post-bootstrap-tasks has 0 listeners
info: tasks bootstrap completed.
info: engine bootstrap beginning...
debug: Emitting event pre-bootstrap-engine
debug: Event pre-bootstrap-engine has 0 listeners
debug: Automoved scripts from /snapshot/lando/build/cli/plugins/lando-core/scripts to /home/daniel/.lando/scripts and setting 755
debug: Automoved scripts from /snapshot/lando/build/cli/plugins/lando-pantheon/scripts to /home/daniel/.lando/scripts and setting 755
debug: Automoved scripts from /snapshot/lando/build/cli/plugins/lando-recipes/scripts to /home/daniel/.lando/scripts and setting 755
debug: Automoved scripts from /snapshot/lando/build/cli/plugins/lando-services/scripts to /home/daniel/.lando/scripts and setting 755
debug: Automoved scripts from /snapshot/lando/build/cli/plugins/lando-sharing/scripts to /home/daniel/.lando/scripts and setting 755
debug: Emitting event post-bootstrap-engine
debug: Event post-bootstrap-engine has 0 listeners
info: engine bootstrap completed.
info: Bootstrap completed.
debug: Emitting event cli-answers
debug: Event cli-answers has 0 listeners
debug: Emitting event cli-update-translation-answers
debug: Event cli-update-translation-answers has 0 listeners
debug: Emitting event cli-run
debug: Event cli-run has 0 listeners
debug: Emitting event cli-update-translation-run
debug: Event cli-update-translation-run has 0 listeners
verbose: Loading event post-db-import priority 9999
debug: Emitting event pre-update-translation
debug: Event pre-update-translation has 0 listeners
verbose: Running pid1 ["/usr/bin/docker","exec","--tty","--interactive","--user",1000,"--workdir","/app","--env","PHP_MEMORY_LIMIT=-1","learnattack_appserver_1","/bin/sh","-c","drush locale:check && drush locale:update -vvvv","drush","locale:update","-vvvv"] in /home/daniel/workspace/learnattack with options {"mode":"attach","detached":false}
silly: With env {"LS_COLORS":"rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:","LESSCLOSE":"/usr/bin/lesspipe %s %s","LANG":"de_DE.UTF-8","GDM_LANG":"de_DE","DISPLAY":":0","GTK_OVERLAY_SCROLLING":"1","COLORTERM":"truecolor","CHROME_DESKTOP":"code-url-handler.desktop","XDG_VTNR":"7","GIO_LAUNCHED_DESKTOP_FILE_PID":"22842","SSH_AUTH_SOCK":"/run/user/1000/keyring/ssh","MANDATORY_PATH":"/usr/share/gconf/cinnamon.mandatory.path","XDG_SESSION_ID":"c2","XDG_GREETER_DATA_DIR":"/var/lib/lightdm-data/daniel","USER":"daniel","DESKTOP_SESSION":"cinnamon","TEXTDOMAINDIR":"/usr/share/locale/","DEFAULTS_PATH":"/usr/share/gconf/cinnamon.default.path","QT_QPA_PLATFORMTHEME":"qt5ct","PWD":"/home/daniel/workspace/learnattack","HOME":"/home/daniel","TEXTDOMAIN":"im-config","SSH_AGENT_PID":"2332","TERM_PROGRAM":"vscode","TERM_PROGRAM_VERSION":"1.43.2","QT_ACCESSIBILITY":"1","XDG_SESSION_TYPE":"x11","XDG_DATA_DIRS":"/usr/share/cinnamon:/usr/share/gnome:/home/daniel/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share","XDG_SESSION_DESKTOP":"cinnamon","GJS_DEBUG_OUTPUT":"stderr","GTK_MODULES":"gail:atk-bridge","TERM":"xterm-256color","SHELL":"/bin/bash","XDG_SEAT_PATH":"/org/freedesktop/DisplayManager/Seat0","IM_CONFIG_PHASE":"2","XDG_CURRENT_DESKTOP":"X-Cinnamon","GPG_AGENT_INFO":"/run/user/1000/gnupg/S.gpg-agent:0:1","GIO_LAUNCHED_DESKTOP_FILE":"/usr/share/applications/code.desktop","SHLVL":"2","XDG_SEAT":"seat0","LANGUAGE":"de_DE","GDMSESSION":"cinnamon","GNOME_DESKTOP_SESSION_ID":"this-is-deprecated","LOGNAME":"daniel","DBUS_SESSION_BUS_ADDRESS":"unix:path=/run/user/1000/bus","XDG_RUNTIME_DIR":"/run/user/1000","XAUTHORITY":"/home/daniel/.Xauthority","XDG_SESSION_PATH":"/org/freedesktop/DisplayManager/Session0","XDG_CONFIG_DIRS":"/etc/xdg/xdg-cinnamon:/etc/xdg","PATH":"/opt/tools/bin:/home/daniel/.composer/vendor/bin:/home/daniel/.local/bin:/opt/tools/bin:/home/daniel/.composer/vendor/bin:/home/daniel/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games","CINNAMON_VERSION":"4.4.8","GJS_DEBUG_TOPICS":"JS ERROR;JS LOG","SESSION_MANAGER":"local/Daniel-ThinkPad-L480:@/tmp/.ICE-unix/2263,unix/Daniel-ThinkPad-L480:/tmp/.ICE-unix/2263","LESSOPEN":"| /usr/bin/lesspipe %s","_":"/usr/local/bin/lando"}
debug: With stdio={"stdio":["inherit","inherit","ignore"]}, mode=attach, detached=false, cwd=/home/daniel/workspace/learnattack
debug: Emitting event pre-engine-up
debug: Event pre-engine-up has 0 listeners
debug: Engine is up.
                    debug: Emitting event post-engine-up
                                                        debug: Event post-engine-up has 0 listeners
                                                                                                   debug: Emitting event pre-engine-isRunning
                                                                                                                                             debug: Event pre-engine-isRunning has 0 listeners
                                                                                                                                                                                              debug: Emitting event post-engine-isRunning
                         debug: Event post-engine-isRunning has 0 listeners
                                                                           debug: Logging metrics data {"command":"lando update-translation","context":"local","devMode":false,"instance":"6e1986c67664132f04a9c03123ad75377844cefe","nodeVersion":"v12.13.1","mode":"cli","os":{"type":"Linux","platform":"linux","release":"5.3.0-46-generic","arch":"x64"},"product":"lando","version":"3.0.0-rrc.3","message":"next.match is not a function","stack":"TypeError: next.match is not a function\n    at parse (index.js:192:42)\n    at Parser (index.js:855:16)\n    at addCommand (shell.js)\n    at /snapshot/lando/build/cli/lib/shell.js\nFrom previous event:\n    at Shell.sh (shell.js)\n    at Object.dockerExec (utils.js)\n    at /snapshot/lando/build/cli/plugins/lando-tooling/lib/build.js\nFrom previous event:\n    at Object.run (build.js)\n    at /snapshot/lando/build/cli/lib/bootstrap.js\n    at /snapshot/lando/build/cli/lib/cli.js\nFrom previous event:\n    at Object.handler (cli.js)\n    at Object.runCommand (command.js:238:44)\n    at Object.parseArgs [as _parseArgs] (yargs.js:1063:30)\n    at Function.get [as argv] (yargs.js:1004:21)\n    at Cli.init (cli.js)\n    at Cli.run (cli.js)\n    at Object.<anonymous> (lando.js)\n    at Module._compile (bootstrap.js:1324:22)\n    at Function.Module.runMain (bootstrap.js:1379:12)\n    at internal/main/run_main_module.js:17:11","action":"error","created":"2020-04-06T22:57:04.652Z"} to [{"report":true,"url":"https://metrics.lando.dev"}]
                              daniel:~/workspace/learnattack (master) $ >  [notice] Übersetzung für drupal überprüft.
>  [notice] Übersetzung für admin_toolbar überprüft.
>  [notice] Übersetzung für advagg überprüft.
...
```

**Tell us generally about your bug**
This happens since Version *v3.0.0-rc.23* - meaning in *v3.0.0-rc22* everything worked just fine.

**Comment by ckidow** [comment]
Can confirm this.
Just updated from 3.0.0-rc21 to 3.0.0-rrc.3

**Comment by DanielKulbe** [comment]
The issue is gone with version v3.0.0-rrc4
