### ISSUE TITLE
Cannot start containers after upgrading to 3.0.1

### ISSUE THREAD

**Issue by dalin-** [lando/lando#2234]
Congratulations to everyone who's worked so hard to get to 3.0.  May the force be with you. 

**Tell us about your setup**

What is your lando version? 
3.0.1

and operating system? 
OSX Catalina 10.15.4 (19E287)

**Tell us about your `.lando.yml`**

Doesn't seem to matter.  Problem happens with any Lando app, but here's a failing one:

```yml
name: my-site
recipe: pantheon
config:
  framework: drupal8
  env: dev
  site: my-site
  id: a-long-uuid
  disableAutoComposerInstall: true
services:
  mailhog:
    type: mailhog
    hogfrom:
      - appserver
  pma:
    type: phpmyadmin
    hosts:
      - database
tooling:
  push: disabled
  drush:
    service: appserver
    cmd: /app/bin/drush --root=/app/web
```

**Tell us about the command you were running**

```bash
lando start
Let's get this party started! Starting app eam-d8...
Starting landoproxyhyperion5000gandalfedition_proxy_1 ...

ERROR: for landoproxyhyperion5000gandalfedition_proxy_1  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)

ERROR: for proxy  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)
ERROR: An HTTP request took too long to complete. Retry with --verbose to obtain debug information.
If you encounter this issue regularly because of slow network conditions, consider setting COMPOSE_HTTP_TIMEOUT to a higher value (current value: 60).
ERROR ==>  message=, stack=Error
    at /snapshot/lando/build/cli/lib/shell.js
From previous event:
    at Shell.sh (/snapshot/lando/build/cli/lib/shell.js)
    at Object.dc (/snapshot/lando/build/cli/lib/bootstrap.js)
    at compose (/snapshot/lando/build/cli/lib/bootstrap.js)
    at /snapshot/lando/build/cli/lib/router.js
    at /snapshot/lando/build/cli/lib/router.js
    at processImmediate (internal/timers.js:439:21)
From previous event:
    at retryEach (/snapshot/lando/build/cli/lib/router.js)
    at Object.start (/snapshot/lando/build/cli/lib/router.js)
    at /snapshot/lando/build/cli/lib/engine.js
    at /snapshot/lando/build/cli/lib/router.js
From previous event:
    at Object.eventWrapper (/snapshot/lando/build/cli/lib/router.js)
    at Engine.engineCmd (/snapshot/lando/build/cli/lib/engine.js)
    at Engine.start (/snapshot/lando/build/cli/lib/engine.js)
    at /snapshot/lando/build/cli/plugins/lando-proxy/app.js
From previous event:
    at AsyncEvents.<anonymous> (/snapshot/lando/build/cli/plugins/lando-proxy/app.js)
    at AsyncEvents.handle (/snapshot/lando/build/cli/lib/events.js)
    at /snapshot/lando/build/cli/lib/events.js
    at processImmediate (internal/timers.js:439:21)
From previous event:
    at AsyncEvents.emit (/snapshot/lando/build/cli/lib/events.js)
    at /snapshot/lando/build/cli/lib/app.js
From previous event:
    at App.start (/snapshot/lando/build/cli/lib/app.js)
    at Object.run (/snapshot/lando/build/cli/plugins/lando-core/tasks/start.js)
From previous event:
    at /snapshot/lando/build/cli/lib/cli.js
From previous event:
    at Object.handler (/snapshot/lando/build/cli/lib/cli.js)
    at Object.runCommand (/snapshot/lando/build/cli/node_modules/yargs/lib/command.js:238:44)
    at Object.parseArgs [as _parseArgs] (/snapshot/lando/build/cli/node_modules/yargs/yargs.js:1063:30)
    at Function.get [as argv] (/snapshot/lando/build/cli/node_modules/yargs/yargs.js:1004:21)
    at Cli.init (/snapshot/lando/build/cli/lib/cli.js)
    at Cli.run (/snapshot/lando/build/cli/lib/cli.js)
From previous event:
    at /snapshot/lando/build/cli/bin/lando.js
From previous event:
    at Object.<anonymous> (/snapshot/lando/build/cli/bin/lando.js)
    at Module._compile (pkg/prelude/bootstrap.js:1324:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:993:10)
    at Module.load (internal/modules/cjs/loader.js:813:32)
    at Function.Module._load (internal/modules/cjs/loader.js:725:14)
    at Function.Module.runMain (pkg/prelude/bootstrap.js:1379:12)
    at internal/main/run_main_module.js:17:11, __stackCleaned__=true
Starting eamd8_appserver_1 ...

ERROR: for eamd8_appserver_1  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)

ERROR: for appserver  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)
ERROR: An HTTP request took too long to complete. Retry with --verbose to obtain debug information.
If you encounter this issue regularly because of slow network conditions, consider setting COMPOSE_HTTP_TIMEOUT to a higher value (current value: 60).
ERROR ==>  message=, stack=Error
    at /snapshot/lando/build/cli/lib/shell.js
From previous event:
    at Shell.sh (/snapshot/lando/build/cli/lib/shell.js)
    at Object.dc (/snapshot/lando/build/cli/lib/bootstrap.js)
    at compose (/snapshot/lando/build/cli/lib/bootstrap.js)
    at /snapshot/lando/build/cli/lib/router.js
From previous event:
    at retryEach (/snapshot/lando/build/cli/lib/router.js)
    at Object.start (/snapshot/lando/build/cli/lib/router.js)
From previous event:
    at /snapshot/lando/build/cli/lib/router.js
    at processImmediate (internal/timers.js:439:21)
From previous event:
    at Object.run (/snapshot/lando/build/cli/lib/router.js)
    at run (/snapshot/lando/build/cli/lib/engine.js)
    at /snapshot/lando/build/cli/lib/router.js
From previous event:
    at Object.eventWrapper (/snapshot/lando/build/cli/lib/router.js)
    at Engine.engineCmd (/snapshot/lando/build/cli/lib/engine.js)
    at Engine.run (/snapshot/lando/build/cli/lib/engine.js)
    at Object.runBuild (/snapshot/lando/build/cli/plugins/lando-services/lib/utils.js)
    at AsyncEvents.<anonymous> (/snapshot/lando/build/cli/plugins/lando-services/app.js)
    at AsyncEvents.handle (/snapshot/lando/build/cli/lib/events.js)
    at /snapshot/lando/build/cli/lib/events.js
From previous event:
    at AsyncEvents.emit (/snapshot/lando/build/cli/lib/events.js)
    at /snapshot/lando/build/cli/lib/app.js
From previous event:
    at App.start (/snapshot/lando/build/cli/lib/app.js)
    at Object.run (/snapshot/lando/build/cli/plugins/lando-core/tasks/start.js)
From previous event:
    at /snapshot/lando/build/cli/lib/cli.js
From previous event:
    at Object.handler (/snapshot/lando/build/cli/lib/cli.js)
    at Object.runCommand (/snapshot/lando/build/cli/node_modules/yargs/lib/command.js:238:44)
    at Object.parseArgs [as _parseArgs] (/snapshot/lando/build/cli/node_modules/yargs/yargs.js:1063:30)
    at Function.get [as argv] (/snapshot/lando/build/cli/node_modules/yargs/yargs.js:1004:21)
    at Cli.init (/snapshot/lando/build/cli/lib/cli.js)
    at Cli.run (/snapshot/lando/build/cli/lib/cli.js)
From previous event:
    at /snapshot/lando/build/cli/bin/lando.js
From previous event:
    at Object.<anonymous> (/snapshot/lando/build/cli/bin/lando.js)
    at Module._compile (pkg/prelude/bootstrap.js:1324:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:993:10)
    at Module.load (internal/modules/cjs/loader.js:813:32)
    at Function.Module._load (internal/modules/cjs/loader.js:725:14)
    at Function.Module.runMain (pkg/prelude/bootstrap.js:1379:12)
    at internal/main/run_main_module.js:17:11, __stackCleaned__=true
Creating eamd8_mailhog_1 ...
Creating eamd8_index_1   ...
Starting eamd8_appserver_1 ...
Creating eamd8_database_1  ...
Creating eamd8_cache_1     ...
Creating eamd8_appserver_nginx_1 ...
Creating eamd8_pma_1             ...

ERROR: for eamd8_appserver_1  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)

ERROR: for eamd8_mailhog_1  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)

ERROR: for eamd8_index_1  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)

ERROR: for eamd8_database_1  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)

ERROR: for eamd8_pma_1  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)

ERROR: for eamd8_appserver_nginx_1  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)

ERROR: for eamd8_cache_1  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)

ERROR: for appserver  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)

ERROR: for mailhog  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)

ERROR: for index  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)

ERROR: for database  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)

ERROR: for pma  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)

ERROR: for appserver_nginx  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)

ERROR: for cache  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)
ERROR: An HTTP request took too long to complete. Retry with --verbose to obtain debug information.
If you encounter this issue regularly because of slow network conditions, consider setting COMPOSE_HTTP_TIMEOUT to a higher value (current value: 60).
ERROR ==>  message=, stack=Error
    at /snapshot/lando/build/cli/lib/shell.js
From previous event:
    at Shell.sh (/snapshot/lando/build/cli/lib/shell.js)
    at Object.dc (/snapshot/lando/build/cli/lib/bootstrap.js)
    at compose (/snapshot/lando/build/cli/lib/bootstrap.js)
    at /snapshot/lando/build/cli/lib/router.js
    at /snapshot/lando/build/cli/lib/router.js
    at processImmediate (internal/timers.js:439:21)
From previous event:
    at retryEach (/snapshot/lando/build/cli/lib/router.js)
    at Object.start (/snapshot/lando/build/cli/lib/router.js)
    at /snapshot/lando/build/cli/lib/engine.js
    at /snapshot/lando/build/cli/lib/router.js
From previous event:
    at Object.eventWrapper (/snapshot/lando/build/cli/lib/router.js)
    at Engine.engineCmd (/snapshot/lando/build/cli/lib/engine.js)
    at Engine.start (/snapshot/lando/build/cli/lib/engine.js)
    at /snapshot/lando/build/cli/lib/app.js
From previous event:
    at App.start (/snapshot/lando/build/cli/lib/app.js)
    at Object.run (/snapshot/lando/build/cli/plugins/lando-core/tasks/start.js)
From previous event:
    at /snapshot/lando/build/cli/lib/cli.js
From previous event:
    at Object.handler (/snapshot/lando/build/cli/lib/cli.js)
    at Object.runCommand (/snapshot/lando/build/cli/node_modules/yargs/lib/command.js:238:44)
    at Object.parseArgs [as _parseArgs] (/snapshot/lando/build/cli/node_modules/yargs/yargs.js:1063:30)
    at Function.get [as argv] (/snapshot/lando/build/cli/node_modules/yargs/yargs.js:1004:21)
    at Cli.init (/snapshot/lando/build/cli/lib/cli.js)
    at Cli.run (/snapshot/lando/build/cli/lib/cli.js)
From previous event:
    at /snapshot/lando/build/cli/bin/lando.js
From previous event:
    at Object.<anonymous> (/snapshot/lando/build/cli/bin/lando.js)
    at Module._compile (pkg/prelude/bootstrap.js:1324:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:993:10)
    at Module.load (internal/modules/cjs/loader.js:813:32)
    at Function.Module._load (internal/modules/cjs/loader.js:725:14)
    at Function.Module.runMain (pkg/prelude/bootstrap.js:1379:12)
    at internal/main/run_main_module.js:17:11, __stackCleaned__=true

██╗   ██╗██╗  ██╗     ██████╗ ██╗  ██╗██╗
██║   ██║██║  ██║    ██╔═══██╗██║  ██║██║
██║   ██║███████║    ██║   ██║███████║██║
██║   ██║██╔══██║    ██║   ██║██╔══██║╚═╝
╚██████╔╝██║  ██║    ╚██████╔╝██║  ██║██╗
 ╚═════╝ ╚═╝  ╚═╝     ╚═════╝ ╚═╝  ╚═╝╚═╝


An error occurred while starting up your app!
Here are a few things you can try to get back into a good state:

  ■ Try running lando rebuild
  ■ Try restarting in debug mode lando restart -vvv
  ■ Try checking the logs with lando logs

If those fail then consult the troubleshooting materials:

  ■ https://docs.lando.dev/help/logs.html
  ■ https://docs.lando.dev/help/updating.html

Or post your issue to Slack or GitHub

  ■ Slack - https://launchpass.com/devwithlando
  ■ GitHub - https://github.com/lando/lando/issues/new/choose


 ██████╗██████╗  █████╗ ███████╗██╗  ██╗██╗██╗██╗
██╔════╝██╔══██╗██╔══██╗██╔════╝██║  ██║██║██║██║
██║     ██████╔╝███████║███████╗███████║██║██║██║
██║     ██╔══██╗██╔══██║╚════██║██╔══██║╚═╝╚═╝╚═╝
╚██████╗██║  ██║██║  ██║███████║██║  ██║██╗██╗██╗
 ╚═════╝╚═╝  ╚═╝╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝╚═╝╚═╝╚═╝


Would you like to report it, and subsequent crashes, to Lando?

This data is only used by the Lando team to ensure the application runs as well as it can.
For more details check out https://docs.lando.dev/privacy/
```

**Tell us generally about your bug**

Any lando app that I try, it's unable to start any container.  It seems to take several minutes between the lines with the error, and whatever was printed before it.  Uninstalling Lando and Docker, restarting laptop, and re-installing Lando/Docker had no effect.

Downgrading to v3.0.0-rrc.3 fixed the problem.

**Comment by pirog** [comment]
@dalin- probably not a huge surprise that i cannot replicate this. The error you are getting is coming straight from Docker though and usually happens when Lando cannot connect to it for whatever reason.

**Comment by smutlord** [comment]
@dalin- heard from another user that experienced this that restarting docker resolved the issue

**Comment by dalin-** [comment]
Here's the things that I tried that haven't worked:
* Restart laptop
* Rebuild app
* Downgrade to 3.0.0-rrc.3, upgrade to 3.0.1 (but keep the previous Docker 2.2.0.5), rebuild
* Uninstall everything, install 3.0.2, rebuild

Same error in all scenarios.

The only thing that has worked:
* uninstall docker, install v3.0.0-rrc.3, rebuild

**Comment by dalin-** [comment]
FWIW I tried again with 3.0.13 with no luck.  

I did a bit more sleuthing.  Between the working version (3.0.0 rrc3) and the version where things start to break (3.0.2) there was no new version of Docker.  But Traefik was upgraded from 1.6.3 to 2.2.0 which apparently required a major configuration rewrite.  

I was also playing around more directly with Docker.  I can start 20 containers (not including Traefik) without issue. But as soon as I start Traefik, then the next container (or _maybe_ the one after that) will fail.  So I'm not even sure what technology to file a bug with.  Is there a Lando config issue with Traefik?   Is Traefik the problem?  Or is this a deeper Docker issue???

I did find a workaround: In `~/.lando/config.yml` If I disable the proxy:

```
proxy: 'OFF'
```

Then I can start up a Lando project again!  Of course I only get the localhost URLs.   

The only problem so far that I've encountered is that `lando pull` can no longer pull a DB (it reports 0.00 B/s for hours).  But I can work around that.

**Comment by techieshark** [comment]
I had same issue -

> ERROR: An HTTP request took too long to complete. Retry with --verbose to obtain debug information.
> If you encounter this issue regularly because of slow network conditions, consider setting COMPOSE_HTTP_TIMEOUT to a higher value (current value: 60)

* Restarted Docker
* `lando destroy` my app
* `lando start`

That seemed to work for me.

**Comment by edurenye** [comment]
I have this error with lando 3.6.0

**Comment by labboy0276** [comment]
@edurenye please try a complete uninstall, or `lando destroy` on your app.  That usually fixes the issue.

**Comment by edurenye** [comment]
Thank you, there was another error related to my app, that I could find and fix using -vvv, but I think this error should show more information at least of in which step of build it happens.

**Comment by philltran** [comment]
I am also getting a similar issue on lando 3.6.0. I tried upgrading, downgrading, destroying lando and docker. I see the error below in my appserver container 
```
runsv tideways: fatal: unable to lock supervise/lock: temporary failure

runsv ssh: fatal: unable to lock supervise/lock: temporary failure

runsv idmapd: fatal: unable to lock supervise/lock: temporary failure

runsv nginx: fatal: unable to lock supervise/lock: temporary failure

runsv blackfire: fatal: unable to lock supervise/lock: temporary failure

runsv newrelic: fatal: unable to lock supervise/lock: temporary failure

runsv app: fatal: unable to lock supervise/lock: temporary failure
```
