### ISSUE TITLE
Upgrading from 3.0.0-rrc.3 to 3.0.1 causes lando to fail with error "Compose file is invalid.."

### ISSUE THREAD

**Issue by stacyvlasits** [lando/lando#2256]
1.  Update to the [latest version](https://github.com/lando/lando/releases) of Lando and make sure the issue isn't fixed already.  **CHECK**
2.  Please review the [current list of issues](https://github.com/lando/lando/issues) to make sure you are not submitting a duplicate.  **CHECK**

> lando version and operating system
**v3.0.1 on Ubuntu 19.10**

> Paste in the contents of your `.lando.yml` 

```yml
name: labs
recipe: wordpress
config:
  webroot: wordpress
  config:
    php: .vscode/php.ini
services:
  my-service:
    type: phpmyadmin
    hosts:
      - database
  appserver:
    overrides:
      ports:
        - target: 80
          published: 36986
          protocol: tcp
          mode: host  
  node:
    type: node
    build:
      - npm install
    globals:
      gulp-cli: latest
tooling:
    npm:
      service: node
    node:
      service: node
    gulp:
      service: node```

**Tell us about the command you were running**

```bash
lando rebuild -y
```

**Tell us about the error you got**

```
labs  15:27:38 VERBOSE ==> app is ready! 
labs  15:27:38 DEBUG ==> emitting event ready 
labs  15:27:38 VERBOSE ==> discovering dynamic portforward info... 
labs  15:27:38 VERBOSE ==> reporting rebuild action to report=true, url=https://metrics.lando.dev, report=true, url=https://metrics.lando.dev
labs  15:27:38 DEBUG ==> reported data command=lando rebuild,y, context=local, devMode=false, instance=904e4eb444fe5ab3fc5590e7410a65213f58d2ef, nodeVersion=v12.13.1, mode=cli, type=Linux, platform=linux, release=5.3.0-51-generic, arch=x64, product=lando, version=3.0.1, app=c8ff3ffa42e686cca68822ac173583b8c242912e, type=wordpress, services=[php:7.3, mysql, phpmyadmin, node], action=rebuild, created=2020-05-13T20:27:38.121Z
labs  15:27:38 DEBUG ==> emitting event pre-rebuild 
labs  15:27:38 VERBOSE ==> determining pullable services... 
labs  15:27:38 DEBUG ==> determined pullable services service=appserver, isLocal=false, service=database, isLocal=false, service=my-service, isLocal=false, service=node, isLocal=false
labs  15:27:38 INFO ==> stopping app... 
labs  15:27:38 DEBUG ==> emitting event ready 
labs  15:27:38 VERBOSE ==> discovering dynamic portforward info... 
labs  15:27:38 VERBOSE ==> reporting stop action to report=true, url=https://metrics.lando.dev, report=true, url=https://metrics.lando.dev
labs  15:27:38 DEBUG ==> reported data command=lando rebuild,y, context=local, devMode=false, instance=904e4eb444fe5ab3fc5590e7410a65213f58d2ef, nodeVersion=v12.13.1, mode=cli, type=Linux, platform=linux, release=5.3.0-51-generic, arch=x64, product=lando, version=3.0.1, app=c8ff3ffa42e686cca68822ac173583b8c242912e, type=wordpress, services=[php:7.3, mysql, phpmyadmin, node], action=stop, created=2020-05-13T20:27:38.168Z
labs  15:27:38 DEBUG ==> emitting event pre-stop 
labs  15:27:38 DEBUG ==> process pid6 running /usr/share/lando/bin/docker-compose kill cstdio=inherit, silent=false, mode=spawn, detached=false
ERROR: The Compose file '/home/sgv287/.lando/compose/labs/appserver-3.yml' is invalid because:
services.appserver.ports contains an invalid type, it should be a number, or an object
labs  15:27:39 DEBUG ==> process pid6 finished with exit code 1 
lando 15:27:39 ERROR ==> Error
    at /snapshot/lando/build/cli/lib/shell.js
From previous event:
    at Shell.sh (/snapshot/lando/build/cli/lib/shell.js)
    at Object.dc (/snapshot/lando/build/cli/lib/bootstrap.js)
    at compose (/snapshot/lando/build/cli/lib/bootstrap.js)
    at /snapshot/lando/build/cli/lib/router.js
    at /snapshot/lando/build/cli/lib/router.js
    at processImmediate (internal/timers.js:439:21)
From previous event:
    at retryEach (/snapshot/lando/build/cli/lib/router.js)
    at Object.stop (/snapshot/lando/build/cli/lib/router.js)
    at run (/snapshot/lando/build/cli/lib/engine.js)
    at /snapshot/lando/build/cli/lib/router.js
From previous event:
    at Object.eventWrapper (/snapshot/lando/build/cli/lib/router.js)
    at Engine.engineCmd (/snapshot/lando/build/cli/lib/engine.js)
    at Engine.stop (/snapshot/lando/build/cli/lib/engine.js)
From previous event:
    at App.stop (/snapshot/lando/build/cli/lib/app.js)
    at /snapshot/lando/build/cli/lib/app.js
From previous event:
    at App.rebuild (/snapshot/lando/build/cli/lib/app.js)
    at Object.run (/snapshot/lando/build/cli/plugins/lando-core/tasks/rebuild.js)
From previous event:
    at /snapshot/lando/build/cli/lib/cli.js
From previous event:
    at Object.handler (/snapshot/lando/build/cli/lib/cli.js)
    at Object.runCommand (/snapshot/lando/build/cli/node_modules/yargs/lib/command.js:238:44)
    at Object.parseArgs [as _parseArgs] (/snapshot/lando/build/cli/node_modules/yargs/yargs.js:1063:30)
    at Function.get [as argv] (/snapshot/lando/build/cli/node_modules/yargs/yargs.js:1004:21)
    at Cli.init (/snapshot/lando/build/cli/lib/cli.js)
    at Cli.run (/snapshot/lando/build/cli/lib/cli.js)
    at Object.<anonymous> (/snapshot/lando/build/cli/bin/lando.js)
    at Module._compile (pkg/prelude/bootstrap.js:1324:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:993:10)
    at Module.load (internal/modules/cjs/loader.js:813:32)
    at Function.Module._load (internal/modules/cjs/loader.js:725:14)
    at Function.Module.runMain (pkg/prelude/bootstrap.js:1379:12)
    at internal/main/run_main_module.js:17:11 
lando 15:27:39 VERBOSE ==> reporting error action to report=true, url=https://metrics.lando.dev, report=true, url=https://metrics.lando.dev
lando 15:27:39 DEBUG ==> reported data command=lando rebuild,y, context=local, devMode=false, instance=904e4eb444fe5ab3fc5590e7410a65213f58d2ef, nodeVersion=v12.13.1, mode=cli, type=Linux, platform=linux, release=5.3.0-51-generic, arch=x64, product=lando, version=3.0.1, message=, stack=Error
    at /snapshot/lando/build/cli/lib/shell.js
From previous event:
    at Shell.sh (shell.js)
    at Object.dc (bootstrap.js)
    at compose (bootstrap.js)
    at /snapshot/lando/build/cli/lib/router.js
    at /snapshot/lando/build/cli/lib/router.js
From previous event:
    at retryEach (router.js)
    at Object.stop (router.js)
    at run (engine.js)
    at /snapshot/lando/build/cli/lib/router.js
From previous event:
    at Object.eventWrapper (router.js)
    at Engine.engineCmd (engine.js)
    at Engine.stop (engine.js)
From previous event:
    at App.stop (app.js)
    at /snapshot/lando/build/cli/lib/app.js
From previous event:
    at App.rebuild (app.js)
    at Object.run (rebuild.js)
From previous event:
    at /snapshot/lando/build/cli/lib/cli.js
From previous event:
    at Object.handler (cli.js)
    at Object.runCommand (command.js:238:44)
    at Object.parseArgs [as _parseArgs] (yargs.js:1063:30)
    at Function.get [as argv] (yargs.js:1004:21)
    at Cli.init (cli.js)
    at Cli.run (cli.js)
    at Object.<anonymous> (lando.js)
    at Module._compile (bootstrap.js:1324:22)
    at Function.Module.runMain (bootstrap.js:1379:12)
    at internal/main/run_main_module.js:17:11, action=error, created=2020-05-13T20:27:39.165Z
```

>  **Tell us generally about your bug**

I upgraded to a new version of lando and now I get an error each time I try to use Lando.
The error message accurately describes the state of the referenced file, but since I don't have any (obvious) way to control the state of the referenced file, I don't know how to fix it.

```bash
Had a working installation of lando using v3.0.0-rrc.3 with a working application using the above .lando.yml
1. Upgraded to v3.0.1
2. Restarted docker
3. ran the command 'lando start' got the error above
4.  ran '`lando rebuild -y', same error
5.  deleted the named file, same error
6.  followed each of the steps https://docs.lando.dev/help/updating.html#_4-progressively-prune-the-lando-config-directory
7.  after each step ran lando rebuild, same error
```
The error without the debugging code is:
```ERROR: The Compose file '/home/sgv287/.lando/compose/labs/appserver-3.yml' is invalid because: services.appserver.ports contains an invalid type, it should be a number, or an object```

The contents of the file referenced in the error are:
```yml
services:
  appserver:
    ports:
      - '127.0.0.1::[object Object]'
version: '3.6'
```
**Tell us more**

> Could better documentation have prevented this issue? if so what should we change?

I don't know

> Does this bug prevent you from using lando?

Yes

**Comment by stacyvlasits** [comment]
Update: @pirog suggested changing the port override in my yml file to string (from an object).  This workaround fixed my issue.

**Comment by pirog** [comment]
@stacyvlasits this should be fixed in https://github.com/lando/lando/releases/tag/v3.0.3, releases are still building so might take a few
