### ISSUE TITLE
Fedora 32 suddenly does not work, crash with no error | Linux libcurl ssh

### ISSUE THREAD

**Issue by don-dev** [lando/lando#2274]
I am using v3.0.3

Lando was working, I had a fedora update and it stopped due to a docker-ce issue. The docker issue was resolved by changing the cgroupv2 to v1 per other edge documentation on the internet.

docker is working fine and hello world runs as expected. Previous containers using various recipes have started to crash and latest, I can't init anything new. My use case is pantheon. It will go through the init questions, then start and stop a bunch of containers, ending in a crash with no real error:

![image](https://user-images.githubusercontent.com/6163393/82478721-51bc6480-9a9f-11ea-8ad6-bd1cde60aaf0.png)

running init with -vvvv shows the shell.js error that could really mean anything, but it follows:
lando 13:31:18 DEBUG ==> process pid16 running /usr/share/lando/bin/docker-compose down cstdio=inherit, silent=false, mode=spawn, detached=false
lando 13:31:18 SILLY ==> process pid16 full command, running _=[/usr/share/lando/bin/docker-compose, down], project-name=landoinittridentbooks, projectName=landoinittridentbooks, file=[/home/donalcasey/.lando/init/trident-books/init-0.yml, /home/donalcasey/.lando/init/trident-books/init-1.yml, /home/donalcasey/.lando/init/trident-books/init-2.yml], remove-orphans=true, removeOrphans=true, v=true
Removing landoinittridentbooks_init_1 ... done
Removing network landoinittridentbooks_default
Removing volume landoinittridentbooks_data_init
Removing volume landoinittridentbooks_home_init
lando 13:31:19 DEBUG ==> process pid16 finished with exit code 0 
lando 13:31:19 SILLY ==> process pid16 had output stdout=, stderr=
lando 13:31:19 ERROR ==> Error
    at /snapshot/lando/build/cli/lib/shell.js
From previous event:
    at Shell.sh (/snapshot/lando/build/cli/lib/shell.js)
    at Object.dc (/snapshot/lando/build/cli/lib/bootstrap.js)
    at compose (/snapshot/lando/build/cli/lib/bootstrap.js)
From previous event:
    at /snapshot/lando/build/cli/lib/router.js
    at processImmediate (internal/timers.js:439:21)
From previous event:
    at Object.run (/snapshot/lando/build/cli/lib/router.js)
    at run (/snapshot/lando/build/cli/lib/engine.js)
    at /snapshot/lando/build/cli/lib/router.js
From previous event:
    at Object.eventWrapper (/snapshot/lando/build/cli/lib/router.js)
    at Engine.engineCmd (/snapshot/lando/build/cli/lib/engine.js)
    at Engine.run (/snapshot/lando/build/cli/lib/engine.js)
    at Object.run (/snapshot/lando/build/cli/plugins/lando-recipes/lib/build.js)
From previous event:
    at runBuild (/snapshot/lando/build/cli/plugins/lando-recipes/tasks/init.js)
    at /snapshot/lando/build/cli/plugins/lando-recipes/tasks/init.js
From previous event:
    at Object.run (/snapshot/lando/build/cli/plugins/lando-recipes/tasks/init.js)
From previous event:
    at /snapshot/lando/build/cli/lib/cli.js
From previous event:
    at Object.handler (/snapshot/lando/build/cli/lib/cli.js)
    at Object.runCommand (/snapshot/lando/build/cli/node_modules/yargs/lib/command.js:238:44)
    at Object.parseArgs [as _parseArgs] (/snapshot/lando/build/cli/node_modules/yargs/yargs.js:1063:30)
    at Function.get [as argv] (/snapshot/lando/build/cli/node_modules/yargs/yargs.js:1004:21)
    at Cli.init (/snapshot/lando/build/cli/lib/cli.js)
    at Cli.run (/snapshot/lando/build/cli/lib/cli.js)
    at Object.<anonymous> (/snapshot/lando/build/cli/bin/lando.js)
    at Module._compile (pkg/prelude/bootstrap.js:1324:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:993:10)
    at Module.load (internal/modules/cjs/loader.js:813:32)
    at Function.Module._load (internal/modules/cjs/loader.js:725:14)
    at Function.Module.runMain (pkg/prelude/bootstrap.js:1379:12)
    at internal/main/run_main_module.js:17:11 
lando 13:31:19 VERBOSE ==> reporting error action to report=true, url=https://metrics.lando.dev, report=true, url=https://metrics.lando.dev
lando 13:31:19 DEBUG ==> reported data command=lando init, context=local, devMode=false, instance=34d77cebe5432ea23aab09d906ad324bcbb0897c, nodeVersion=v12.13.1, mode=cli, type=Linux, platform=linux, release=5.6.12-300.fc32.x86_64, arch=x64, product=lando, version=3.0.3, message=, stack=Error
    at /snapshot/lando/build/cli/lib/shell.js
From previous event:
    at Shell.sh (shell.js)
    at Object.dc (bootstrap.js)
    at compose (bootstrap.js)
From previous event:
    at /snapshot/lando/build/cli/lib/router.js
From previous event:
    at Object.run (router.js)
    at run (engine.js)
    at /snapshot/lando/build/cli/lib/router.js
From previous event:
    at Object.eventWrapper (router.js)
    at Engine.engineCmd (engine.js)
    at Engine.run (engine.js)
    at Object.run (build.js)
From previous event:
    at runBuild (init.js)
    at /snapshot/lando/build/cli/plugins/lando-recipes/tasks/init.js
From previous event:
    at Object.run (init.js)
From previous event:
    at /snapshot/lando/build/cli/lib/cli.js
From previous event:
    at Object.handler (cli.js)
    at Object.runCommand (command.js:238:44)
    at Object.parseArgs [as _parseArgs] (yargs.js:1063:30)
    at Function.get [as argv] (yargs.js:1004:21)
    at Cli.init (cli.js)
    at Cli.run (cli.js)
    at Object.<anonymous> (lando.js)
    at Module._compile (bootstrap.js:1324:22)
    at Function.Module.runMain (bootstrap.js:1379:12)
    at internal/main/run_main_module.js:17:11, action=error, created=2020-05-20T17:31:19.416Z

**Comment by don-dev** [comment]
I have found another issue that seems similar, but old. It describes port 2222 was firewalled for a WIN install. I am on linux, and do not see why this would have changed, but I am trying to whitelist that and notice these messages before non error:
```
Detected that ssh://codeserver.dev.ce2909e1-1549-4dd7-9b51-28610feb4192@codeserver.dev.ce2909e1-1549-4dd7-9b51-28610feb4192.drush.in:2222/~/repository.git is a tar archive
Downloading ssh://codeserver.dev.ce2909e1-1549-4dd7-9b51-28610feb4192@codeserver.dev.ce2909e1-1549-4dd7-9b51-28610feb4192.drush.in:2222/~/repository.git...
curl: (1) Protocol "ssh" not supported or disabled in libcurl
Killing landoinittridentbooks_init_1 ... done
```

**Comment by don-dev** [comment]
whitelisting didn't resolve
