### ISSUE TITLE
Underscores in service names causes build steps to fail

### ISSUE THREAD

**Issue by hussainweb** [lando/lando#2293]
**Tell us about your setup**

What is your lando version and operating system?

v3.0.3 on macOS Catalina

**Tell us about your `.lando.yml`**

Paste in the contents of your `.lando.yml` this is **SUPER HELPFUL** for us.

*Example:*

```yml
name: migr
recipe: drupal8

services:
  appserver:
    type: php:7.4
    via: apache
    webroot: d9/web
  database:
    type: mariadb:10.4
    overrides:
      image: bitnami/mariadb:10.4
  cache:
    type: redis:5

  d7simple_php:
    type: php:7.3
    via: apache
    webroot: d7simple
    build:
      - echo "Hello"
  d7simple_db:
    type: mariadb:10.4
    overrides:
      image: bitnami/mariadb:10.4

tooling:
  drush:
    service: appserver
    cmd: /app/d9/vendor/bin/drush
```

**Tell us about the command you were running**

```bash
lando start
```

**Tell us about the error you got**

With the above config, I get an error similar to below. The actual error is this followed by a stacktrace.

**Error**:

```
ERROR: No such service: d7simple
migr  20:10:09 DEBUG ==> process pid7 finished with exit code 1
migr  20:10:09 ERROR ==>  message=, stack=Error
```

I can do things to avoid the error:
1. Remove the `build` step from the `d7simple_php` service.
2. Rename the `d7simple_php` to something like `d7simplephp` (without underscore).

From the above (which I repeated over several tries), it became clear to me that the problem is the underscore in the name.

**Full output:**

```bash
lando start -vvvv
migr  20:10:05 DEBUG ==> adding app cli task composer
migr  20:10:05 DEBUG ==> adding app cli task db-import <file>
migr  20:10:05 DEBUG ==> adding app cli task db-export [file]
migr  20:10:05 DEBUG ==> adding app cli task php
migr  20:10:05 DEBUG ==> adding app cli task mysql
migr  20:10:05 DEBUG ==> adding app cli task drush
migr  20:10:05 DEBUG ==> adding app cli task drupal
migr  20:10:05 VERBOSE ==> setting LANDO_INFO...
migr  20:10:05 DEBUG ==> ensuring exposed ports on appserver are bound to 127.0.0.1
migr  20:10:05 DEBUG ==> ensuring exposed ports on appserver are bound to 127.0.0.1
migr  20:10:05 DEBUG ==> ensuring exposed ports on database are bound to 127.0.0.1
migr  20:10:05 DEBUG ==> ensuring exposed ports on d7simple_php are bound to 127.0.0.1
migr  20:10:05 VERBOSE ==> app is ready!
migr  20:10:05 DEBUG ==> emitting event ready
migr  20:10:05 VERBOSE ==> discovering dynamic portforward info...
migr  20:10:05 VERBOSE ==> reporting start action to report=true, url=https://metrics.lando.dev, report=true, url=https://metrics.lando.dev
migr  20:10:05 DEBUG ==> reported data command=lando start, context=local, devMode=false, instance=ad82e2f1353b4345608647b584b705352c6ea4df, nodeVersion=v12.13.1, mode=cli, type=Darwin, platform=darwin, release=19.4.0, arch=x64, product=lando, version=3.0.3, app=b8a04486b83aa9a21aee10f8ecd1202aa3f42891, type=drupal8, services=[php:7.4, mariadb:10.4, php:7.3, mariadb:10.4], action=start, created=2020-05-28T00:10:05.889Z
migr  20:10:05 DEBUG ==> emitting event pre-start
lando 20:10:05 VERBOSE ==> about to scan urls
lando 20:10:05 DEBUG ==> scanning data urls=[http://127.0.0.1:80, http://127.0.0.1:8000, http://127.0.0.1:8080, http://127.0.0.1:8888, http://127.0.0.1:8008], max=1, waitCodes=[]
lando 20:10:05 VERBOSE ==> about to scan urls
lando 20:10:05 DEBUG ==> scanning data urls=[https://127.0.0.1:443, https://127.0.0.1:444, https://127.0.0.1:4433, https://127.0.0.1:4444, https://127.0.0.1:4443], max=1, waitCodes=[]
lando 20:10:05 DEBUG ==> checking to see if http://127.0.0.1:80 is ready.
lando 20:10:05 DEBUG ==> checking to see if http://127.0.0.1:8000 is ready.
lando 20:10:05 DEBUG ==> checking to see if http://127.0.0.1:8080 is ready.
lando 20:10:05 DEBUG ==> checking to see if http://127.0.0.1:8888 is ready.
lando 20:10:05 DEBUG ==> checking to see if http://127.0.0.1:8008 is ready.
lando 20:10:05 DEBUG ==> checking to see if https://127.0.0.1:443 is ready.
lando 20:10:05 DEBUG ==> checking to see if https://127.0.0.1:444 is ready.
lando 20:10:05 DEBUG ==> checking to see if https://127.0.0.1:4433 is ready.
lando 20:10:05 DEBUG ==> checking to see if https://127.0.0.1:4444 is ready.
lando 20:10:05 DEBUG ==> checking to see if https://127.0.0.1:4443 is ready.
lando 20:10:06 DEBUG ==> checking to see if http://127.0.0.1:80 is ready.
lando 20:10:06 DEBUG ==> checking to see if http://127.0.0.1:8000 is ready.
lando 20:10:06 DEBUG ==> checking to see if http://127.0.0.1:8080 is ready.
lando 20:10:06 DEBUG ==> checking to see if http://127.0.0.1:8888 is ready.
lando 20:10:06 DEBUG ==> checking to see if http://127.0.0.1:8008 is ready.
lando 20:10:06 DEBUG ==> checking to see if https://127.0.0.1:443 is ready.
lando 20:10:06 DEBUG ==> checking to see if https://127.0.0.1:444 is ready.
lando 20:10:06 DEBUG ==> checking to see if https://127.0.0.1:4433 is ready.
lando 20:10:06 DEBUG ==> checking to see if https://127.0.0.1:4444 is ready.
lando 20:10:06 DEBUG ==> checking to see if https://127.0.0.1:4443 is ready.
lando 20:10:06 DEBUG ==> http://127.0.0.1:80 not currently accessible
lando 20:10:06 DEBUG ==> http://127.0.0.1:8000 not currently accessible
lando 20:10:06 DEBUG ==> http://127.0.0.1:8080 not currently accessible
lando 20:10:06 DEBUG ==> http://127.0.0.1:8888 not currently accessible
lando 20:10:06 DEBUG ==> http://127.0.0.1:8008 not currently accessible
lando 20:10:06 DEBUG ==> https://127.0.0.1:443 not currently accessible
lando 20:10:06 DEBUG ==> https://127.0.0.1:444 not currently accessible
lando 20:10:06 DEBUG ==> https://127.0.0.1:4433 not currently accessible
lando 20:10:06 DEBUG ==> https://127.0.0.1:4444 not currently accessible
lando 20:10:06 DEBUG ==> https://127.0.0.1:4443 not currently accessible
lando 20:10:06 VERBOSE ==> scan completed.
lando 20:10:06 DEBUG ==> scan results. url=http://127.0.0.1:80, status=false, color=red, url=http://127.0.0.1:8000, status=false, color=red, url=http://127.0.0.1:8080, status=false, color=red, url=http://127.0.0.1:8888, status=false, color=red, url=http://127.0.0.1:8008, status=false, color=red
lando 20:10:06 VERBOSE ==> scan completed.
lando 20:10:06 DEBUG ==> scan results. url=https://127.0.0.1:443, status=false, color=red, url=https://127.0.0.1:444, status=false, color=red, url=https://127.0.0.1:4433, status=false, color=red, url=https://127.0.0.1:4444, status=false, color=red, url=https://127.0.0.1:4443, status=false, color=red
lando 20:10:06 DEBUG ==> process pid6 running /Applications/Docker.app/Contents/Resources/bin/docker-compose/docker-compose up cstdio=inherit, silent=false, mode=spawn, detached=false
Creating landoproxyhyperion5000gandalfedition_proxy_1 ... done
lando 20:10:08 DEBUG ==> process pid6 finished with exit code 0
migr  20:10:08 DEBUG ==> app has proxy compose files 0=/Users/hw/.lando/compose/migr/proxy-0.yml
migr  20:10:08 INFO ==> running build steps...
migr  20:10:08 DEBUG ==> process pid7 running /Applications/Docker.app/Contents/Resources/bin/docker-compose/docker-compose up cstdio=inherit, silent=false, mode=spawn, detached=false
Creating network "migr_default" with the default driver
Creating volume "migr_data_appserver" with default driver
Creating volume "migr_home_appserver" with default driver
Creating volume "migr_data_database" with default driver
Creating volume "migr_home_database" with default driver
Creating volume "migr_data_d7simple_php" with default driver
Creating volume "migr_home_d7simple_php" with default driver
Creating volume "migr_data_d7simple_db" with default driver
Creating volume "migr_home_d7simple_db" with default driver
ERROR: No such service: d7simple
migr  20:10:09 DEBUG ==> process pid7 finished with exit code 1
migr  20:10:09 ERROR ==>  message=, stack=Error
    at /snapshot/lando/build/cli/lib/shell.js
From previous event:
    at Shell.sh (/snapshot/lando/build/cli/lib/shell.js)
    at Object.dc (/snapshot/lando/build/cli/lib/bootstrap.js)
    at compose (/snapshot/lando/build/cli/lib/bootstrap.js)
    at /snapshot/lando/build/cli/lib/router.js
From previous event:
    at retryEach (/snapshot/lando/build/cli/lib/router.js)
    at Object.start (/snapshot/lando/build/cli/lib/router.js)
From previous event:
    at /snapshot/lando/build/cli/lib/router.js
    at processImmediate (internal/timers.js:439:21)
From previous event:
    at Object.run (/snapshot/lando/build/cli/lib/router.js)
    at run (/snapshot/lando/build/cli/lib/engine.js)
    at /snapshot/lando/build/cli/lib/router.js
From previous event:
    at Object.eventWrapper (/snapshot/lando/build/cli/lib/router.js)
    at Engine.engineCmd (/snapshot/lando/build/cli/lib/engine.js)
    at Engine.run (/snapshot/lando/build/cli/lib/engine.js)
    at Object.runBuild (/snapshot/lando/build/cli/plugins/lando-services/lib/utils.js)
    at AsyncEvents.<anonymous> (/snapshot/lando/build/cli/plugins/lando-services/app.js)
    at AsyncEvents.handle (/snapshot/lando/build/cli/lib/events.js)
    at /snapshot/lando/build/cli/lib/events.js
From previous event:
    at AsyncEvents.emit (/snapshot/lando/build/cli/lib/events.js)
    at /snapshot/lando/build/cli/lib/app.js
From previous event:
    at App.start (/snapshot/lando/build/cli/lib/app.js)
    at Object.run (/snapshot/lando/build/cli/plugins/lando-core/tasks/start.js)
From previous event:
    at /snapshot/lando/build/cli/lib/cli.js
From previous event:
    at Object.handler (/snapshot/lando/build/cli/lib/cli.js)
    at Object.runCommand (/snapshot/lando/build/cli/node_modules/yargs/lib/command.js:238:44)
    at Object.parseArgs [as _parseArgs] (/snapshot/lando/build/cli/node_modules/yargs/yargs.js:1063:30)
    at Function.get [as argv] (/snapshot/lando/build/cli/node_modules/yargs/yargs.js:1004:21)
    at Cli.init (/snapshot/lando/build/cli/lib/cli.js)
    at Cli.run (/snapshot/lando/build/cli/lib/cli.js)
    at Object.<anonymous> (/snapshot/lando/build/cli/bin/lando.js)
    at Module._compile (pkg/prelude/bootstrap.js:1324:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:993:10)
    at Module.load (internal/modules/cjs/loader.js:813:32)
    at Function.Module._load (internal/modules/cjs/loader.js:725:14)
    at Function.Module.runMain (pkg/prelude/bootstrap.js:1379:12)
    at internal/main/run_main_module.js:17:11, __stackCleaned__=true
migr  20:10:09 DEBUG ==>  message=, stack=Error
    at /snapshot/lando/build/cli/lib/shell.js
From previous event:
    at Shell.sh (/snapshot/lando/build/cli/lib/shell.js)
    at Object.dc (/snapshot/lando/build/cli/lib/bootstrap.js)
    at compose (/snapshot/lando/build/cli/lib/bootstrap.js)
    at /snapshot/lando/build/cli/lib/router.js
From previous event:
    at retryEach (/snapshot/lando/build/cli/lib/router.js)
    at Object.start (/snapshot/lando/build/cli/lib/router.js)
From previous event:
    at /snapshot/lando/build/cli/lib/router.js
    at processImmediate (internal/timers.js:439:21)
From previous event:
    at Object.run (/snapshot/lando/build/cli/lib/router.js)
    at run (/snapshot/lando/build/cli/lib/engine.js)
    at /snapshot/lando/build/cli/lib/router.js
From previous event:
    at Object.eventWrapper (/snapshot/lando/build/cli/lib/router.js)
    at Engine.engineCmd (/snapshot/lando/build/cli/lib/engine.js)
    at Engine.run (/snapshot/lando/build/cli/lib/engine.js)
    at Object.runBuild (/snapshot/lando/build/cli/plugins/lando-services/lib/utils.js)
    at AsyncEvents.<anonymous> (/snapshot/lando/build/cli/plugins/lando-services/app.js)
    at AsyncEvents.handle (/snapshot/lando/build/cli/lib/events.js)
    at /snapshot/lando/build/cli/lib/events.js
From previous event:
    at AsyncEvents.emit (/snapshot/lando/build/cli/lib/events.js)
    at /snapshot/lando/build/cli/lib/app.js
From previous event:
    at App.start (/snapshot/lando/build/cli/lib/app.js)
    at Object.run (/snapshot/lando/build/cli/plugins/lando-core/tasks/start.js)
From previous event:
    at /snapshot/lando/build/cli/lib/cli.js
From previous event:
    at Object.handler (/snapshot/lando/build/cli/lib/cli.js)
    at Object.runCommand (/snapshot/lando/build/cli/node_modules/yargs/lib/command.js:238:44)
    at Object.parseArgs [as _parseArgs] (/snapshot/lando/build/cli/node_modules/yargs/yargs.js:1063:30)
    at Function.get [as argv] (/snapshot/lando/build/cli/node_modules/yargs/yargs.js:1004:21)
    at Cli.init (/snapshot/lando/build/cli/lib/cli.js)
    at Cli.run (/snapshot/lando/build/cli/lib/cli.js)
    at Object.<anonymous> (/snapshot/lando/build/cli/bin/lando.js)
    at Module._compile (pkg/prelude/bootstrap.js:1324:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:993:10)
    at Module.load (internal/modules/cjs/loader.js:813:32)
    at Function.Module._load (internal/modules/cjs/loader.js:725:14)
    at Function.Module.runMain (pkg/prelude/bootstrap.js:1379:12)
    at internal/main/run_main_module.js:17:11, __stackCleaned__=true
```

**Tell us more**

I searched the documentation, particularly on [the services page](https://docs.lando.dev/config/services.html#build-steps), but didn't find any references on not using underscores in the service names.

**Comment by codebymikey** [comment]
I just ran into this issue, I initially thought it was related to me renaming a service or something, and Lando getting out of sync and breaking something under the hood on the Docker level.

However, destroying the Lando instance confirmed that it was in fact a bug or undocumented limitation of services.

**Comment by codebymikey** [comment]
/unstale I think this still needs addressing.

**Comment by pfrenssen** [comment]
I also hit this bug. Can confirm it happens when a service name includes an underscore, and `build` steps are added to the service.
