### ISSUE TITLE
WSL2 + PHPStorm + Xdebug? - "Proper" way to imitate the "Expose daemon on tcp://localhost:2375 without TLS" setting from Docker Desktop?

### ISSUE THREAD

**Issue by mrweiner** [lando/lando#2304]
I've gotten lando+PHPStorm setup on WSL2 using

- Ubuntu + Lando hyperdrive
- vxsrv to provide a GUI

By default, the instructions from https://docs.lando.dev/guides/lando-phpstorm.html do not work on Windows (or WSL, apparently). To make docker available to PHPStorm via Docker Desktop we need to enable the "Expose daemon on tcp://localhost:2375 without TLS" setting (which is tracked at https://youtrack.jetbrains.com/issue/IDEA-207148 -- some people seem to be having luck without TLS disabled but I don't appear to be so lucky). This obviously isn't available on linux. 

Xdebug is running and the site loading on Ubuntu from the localhost:32xxxx paths (although not on windows), but the proxy myapp.lndo.site urls are broken. 

The setup I've got going right now is:
1. Add a /etc/docker/daemon.json in WSL
```
 {
     "tls": false,
     "hosts": ["tcp://127.0.0.1:2375"]
}
```
2. Add `export LANDO_ENGINE_CONFIG='{"host": "localhost", "port":"2375"}'` to `~/.bashrc` (found in https://github.com/lando/lando/issues/1072#issuecomment-401898955)

Without steps 1 or 2, `lando start` worked as expected and the proxy domains loaded up fine (both on ubuntu and windows).  Without step 2 I get the same error as if I try to run `lando start` without first running `sudo service docker start`:
```
mrweiner@WeinerDell:~/dev/sites/dywm$ lando start
Let's get this party started! Starting app dywm...
WARN ==> docker is not running! 
Starting docker up before we begin... please wait...
ERROR ==> System has not been booted with systemd as init system (PID 1). Can't operate.
```

With step 1 and 2 done, I hit this when starting/rebuilding:

```
mrweiner@WeinerDell:~/dev/sites/dywm$ lando start
Let's get this party started! Starting app dywm...
Starting landoproxyhyperion5000gandalfedition_proxy_1 ... error

ERROR: for landoproxyhyperion5000gandalfedition_proxy_1  Cannot start service proxy: OCI runtime create failed: container_linux.go:345: starting container process caused "process_linux.go:430: container init caused \"rootfs_linux.go:58: mounting \\\"/var/run/docker.sock\\\" to rootfs \\\"/var/lib/docker/overlay2/39a45af94d779d41931cc1c96c07c801c6aafda05d8d3a72432a4a772bdba29f/merged\\\" at \\\"/var/lib/docker/overlay2/39a45af94d779d41931cc1c96c07c801c6aafda05d8d3a72432a4a772bdba29f/merged/run/docker.sock\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type

ERROR: for proxy  Cannot start service proxy: OCI runtime create failed: container_linux.go:345: starting container process caused "process_linux.go:430: container init caused \"rootfs_linux.go:58: mounting \\\"/var/run/docker.sock\\\" to rootfs \\\"/var/lib/docker/overlay2/39a45af94d779d41931cc1c96c07c801c6aafda05d8d3a72432a4a772bdba29f/merged\\\" at \\\"/var/lib/docker/overlay2/39a45af94d779d41931cc1c96c07c801c6aafda05d8d3a72432a4a772bdba29f/merged/run/docker.sock\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
ERROR: Encountered errors while bringing up the project.
ERROR ==>  message=, stack=Error
    at /snapshot/lando/build/cli/lib/shell.js
From previous event:
    at Shell.sh (/snapshot/lando/build/cli/lib/shell.js)
    at Object.dc (/snapshot/lando/build/cli/lib/bootstrap.js)
    at compose (/snapshot/lando/build/cli/lib/bootstrap.js)
    at /snapshot/lando/build/cli/lib/router.js
    at /snapshot/lando/build/cli/lib/router.js
    at processImmediate (internal/timers.js:439:21)
From previous event:
    at retryEach (/snapshot/lando/build/cli/lib/router.js)
    at Object.start (/snapshot/lando/build/cli/lib/router.js)
    at /snapshot/lando/build/cli/lib/engine.js
    at /snapshot/lando/build/cli/lib/router.js
From previous event:
    at Object.eventWrapper (/snapshot/lando/build/cli/lib/router.js)
    at Engine.engineCmd (/snapshot/lando/build/cli/lib/engine.js)
    at Engine.start (/snapshot/lando/build/cli/lib/engine.js)
    at /snapshot/lando/build/cli/plugins/lando-proxy/app.js
From previous event:
    at AsyncEvents.<anonymous> (/snapshot/lando/build/cli/plugins/lando-proxy/app.js)
    at AsyncEvents.handle (/snapshot/lando/build/cli/lib/events.js)
    at /snapshot/lando/build/cli/lib/events.js
    at processImmediate (internal/timers.js:439:21)
From previous event:
    at AsyncEvents.emit (/snapshot/lando/build/cli/lib/events.js)
    at /snapshot/lando/build/cli/lib/app.js
From previous event:
    at App.start (/snapshot/lando/build/cli/lib/app.js)
    at Object.run (/snapshot/lando/build/cli/plugins/lando-core/tasks/start.js)
From previous event:
    at /snapshot/lando/build/cli/lib/cli.js
From previous event:
    at Object.handler (/snapshot/lando/build/cli/lib/cli.js)
    at Object.runCommand (/snapshot/lando/build/cli/node_modules/yargs/lib/command.js:238:44)
    at Object.parseArgs [as _parseArgs] (/snapshot/lando/build/cli/node_modules/yargs/yargs.js:1063:30)
    at Function.get [as argv] (/snapshot/lando/build/cli/node_modules/yargs/yargs.js:1004:21)
    at Cli.init (/snapshot/lando/build/cli/lib/cli.js)
    at Cli.run (/snapshot/lando/build/cli/lib/cli.js)
    at Object.<anonymous> (/snapshot/lando/build/cli/bin/lando.js)
    at Module._compile (pkg/prelude/bootstrap.js:1324:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:993:10)
    at Module.load (internal/modules/cjs/loader.js:813:32)
    at Function.Module._load (internal/modules/cjs/loader.js:725:14)
    at Function.Module.runMain (pkg/prelude/bootstrap.js:1379:12)
    at internal/main/run_main_module.js:17:11, __stackCleaned__=true
Starting dywm_database_1  ... done
Starting dywm_appserver_1 ... done
Scanning to determine which services are ready... Please standby...

  _      __              _           __
 | | /| / /__ ________  (_)__  ___ _/ /
 | |/ |/ / _ `/ __/ _ \/ / _ \/ _ `/_/ 
 |__/|__/\_,_/_/ /_//_/_/_//_/\_, (_)  
                             /___/     

Your app started up but we detected some things you may wish to investigate.
These only may be a problem.


 ■ Lando was not able to start the proxy
   Error
   The proxy has been disabled for now so you can continue to work.
   Check out the docs below, resolve your issue and build this app
   https://docs.lando.dev/config/proxy.html


Here are some vitals:

 NAME            dywm                          
 LOCATION        /home/mrweiner/dev/sites/dywm 
 SERVICES        appserver, database           
 APPSERVER URLS  https://localhost:32798 [green]
                 http://localhost:32799 [green]        
                 http://dywm.lndo.site/ [red]        
                 https://dywm.lndo.site/ [red]  
```

**Comment by mrweiner** [comment]
Hmmm, after running `wsl --shutdown` from powershell and trying everything again, the foo.lndo.site urls are still red but I'm not getting any warning like I was before. Interesting...

**Comment by mrweiner** [comment]
Okay actually I think I got this sorted. Removed `export LANDO_ENGINE_CONFIG='{"host": "localhost", "port":"2375"}'` from `~/.bashrc`. My /etc/docker/daemon.json now looks like
```
 {
   "tls": false,
   "hosts": [
    "unix:///var/run/docker.sock",
    "tcp://0.0.0.0:2375",
     "tcp://0.0.0.0:2376"
   ]
 }

**Comment by mrweiner** [comment]
Better way to accomplish the xdebug integration is:


1.     In PHPStorm, File -> Settings -> PHP -> CLI Interpreter -> ... button
2.     Press + button to add a new interpreter
3.     'from Docker'
4.     'Docker' radio button
5.     For Server, click New
6.     Choose Docker and connect by Unix socket, click OK
7.     Wait for image name to populate
8.     Choose devwithlando/pantheonappserver or whatever your appserver is
9.     Click OK
10.     Go to Settings -> Languages & Frameworks -> PHP and delete everything from Include path (you can use CTRL+A and the - button to select all and then delete in one action)
11.     Install an xdebug browser extension (https://www.jetbrains.com/help/phpstorm/browser-debugging-extensions.html)
12.     Toggle on browser extension, PHPStorm Xdebug
13.     Reload your site; prompt appears from localhost in xdebug, accept
14.     Path map must be fixed; go to Settings -> Languages & Frameworks -> PHP -> Servers and find localhost; set your project directory's absolute path on server to /app

From https://github.com/lando/lando/issues/1723#issuecomment-636422514
