### ISSUE TITLE
Escape $ sign in location

### ISSUE THREAD

**Issue by JensYvanDeCraecker** [lando/lando#2333]
When using the Windows installation of Lando in WSL2, Lando fails to build the containers when the directory is inside the WSL2 filesystem.

This is the error I got:
`ERROR: Invalid interpolation format for "environment" option in service "appserver": "\\wsl$\Ubuntu\home\jens\blog"`

To my understandig this problem is caused by the variable substitution in the docker-compose file format (see: `https://docs.docker.com/compose/compose-file/#variable-substitution`).

Some more info:

- Used command: "lando.exe start"
- Stack trace:
```
ERROR ==>  message=, stack=Error
    at C:\snapshot\lando\build\cli\lib\shell.js
From previous event:
    at Shell.sh (C:\snapshot\lando\build\cli\lib\shell.js)
    at Object.dc (C:\snapshot\lando\build\cli\lib\bootstrap.js)
    at compose (C:\snapshot\lando\build\cli\lib\bootstrap.js)
    at C:\snapshot\lando\build\cli\lib\router.js
From previous event:
    at retryEach (C:\snapshot\lando\build\cli\lib\router.js)
    at Object.start (C:\snapshot\lando\build\cli\lib\router.js)
From previous event:
    at C:\snapshot\lando\build\cli\lib\router.js
    at processImmediate (internal/timers.js:439:21)
From previous event:
    at Object.run (C:\snapshot\lando\build\cli\lib\router.js)
    at run (C:\snapshot\lando\build\cli\lib\engine.js)
    at C:\snapshot\lando\build\cli\lib\router.js
From previous event:
    at Object.eventWrapper (C:\snapshot\lando\build\cli\lib\router.js)
    at Engine.engineCmd (C:\snapshot\lando\build\cli\lib\engine.js)
    at Engine.run (C:\snapshot\lando\build\cli\lib\engine.js)
    at Object.runBuild (C:\snapshot\lando\build\cli\plugins\lando-services\lib\utils.js)
    at AsyncEvents.<anonymous> (C:\snapshot\lando\build\cli\plugins\lando-services\app.js)
    at AsyncEvents.handle (C:\snapshot\lando\build\cli\lib\events.js)
    at C:\snapshot\lando\build\cli\lib\events.js
From previous event:
    at AsyncEvents.emit (C:\snapshot\lando\build\cli\lib\events.js)
    at C:\snapshot\lando\build\cli\lib\app.js
From previous event:
    at App.start (C:\snapshot\lando\build\cli\lib\app.js)
    at Object.run (C:\snapshot\lando\build\cli\plugins\lando-core\tasks\start.js)
From previous event:
    at C:\snapshot\lando\build\cli\lib\cli.js
From previous event:
    at Object.handler (C:\snapshot\lando\build\cli\lib\cli.js)
    at Object.runCommand (C:\snapshot\lando\build\cli\node_modules\yargs\lib\command.js:238:44)
    at Object.parseArgs [as _parseArgs] (C:\snapshot\lando\build\cli\node_modules\yargs\yargs.js:1063:30)
    at Function.get [as argv] (C:\snapshot\lando\build\cli\node_modules\yargs\yargs.js:1004:21)
    at Cli.init (C:\snapshot\lando\build\cli\lib\cli.js)
    at Cli.run (C:\snapshot\lando\build\cli\lib\cli.js)
From previous event:
    at C:\snapshot\lando\build\cli\bin\lando.js
From previous event:
    at Object.<anonymous> (C:\snapshot\lando\build\cli\bin\lando.js)
    at Module._compile (pkg/prelude/bootstrap.js:1324:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:993:10)
    at Module.load (internal/modules/cjs/loader.js:813:32)
    at Function.Module._load (internal/modules/cjs/loader.js:725:14)
    at Function.Module.runMain (pkg/prelude/bootstrap.js:1379:12)
    at internal/main/run_main_module.js:17:11, __stackCleaned__=true
```

**Comment by pirog** [comment]
@JensYvanDeCraecker we dont support WSL and even if we did you certainly shouldnt be installing the WINDOWS version of lando inside of it

cc @dustinleblanc

**Comment by JensYvanDeCraecker** [comment]
Im using the Windows installation from WSL2 (It's not installed in WSL2, I'm just using the interop functionality of WSL2 to use Windows programs that are installed on my system) because some of my tools live in the WSL2 system (like PHP, Composer, etc.). And I also use Lando directly from Windows for other projects.

**Comment by dustinleblanc** [comment]
I would highly, highly recommend just installing docker inside WSL2 and then installing Lando there and running all of your lando apps outside of the windows FS mount (don't use /mnt/c/blah, use /home/unixuser/projectsnstuff). CPU and battery usage are night and day better as is the general speed of Lando. https://github.com/lando/lando/issues/1723 has lots of discussion about the easy ways to set all this up, this is how I run my system and for the past several weeks, it has been just as stable as my old Pop OS machine running native, just a tad slower.

**Comment by JensYvanDeCraecker** [comment]
The point was that I was trying to use lando apps from inside the wsl filesystem (/home/jens/blog for example) which gets correctly translated to '\\wsl$\Ubuntu\home\jens\blog'.
When using windows lando from wsl with a folder in /mnt/c/blah this again gets correctly translated to C:\blah. 

I feel like installing lando and docker in wsl2 directly feels like a trade-off for me because I do use both tools in my Windows envirnmont as well.

**Comment by JensYvanDeCraecker** [comment]
Hello, I was able to solve this issue with modifying the source and building the lando app myself.
But because I still want to use official releases of lando, I decided to create a plugin for it, but there, I again had some issues:

1. The guide at [https://docs.lando.dev/contrib/contrib-plugins.html#index-js](url) doesn't work. The app argument is in fact the lando object while the lando argument is 'undefined';
2. [https://docs.lando.dev/api/app.html#pre-init](url) states that the 'pre-init' events should be observed by 'lando.events.on' while it is in fact with 'app.events.on'. In the built in plugins, the event is also observed with 'app.events.on' and not 'lando.events.on'.

**Comment by pirog** [comment]
the contrib and api docs are WIP so thats not surprising.

**Comment by JensYvanDeCraecker** [comment]
Hello

I have fixed my issue and I'm closing this issue.

I'll drop the code snippet below if you'd care:
`module.exports = (app, lando) => {
  app.configFiles = app.configFiles.map(escape);
  app.root = escape(app.root);
  // Override some previously set variables.
  return {
    env: {
      LANDO_APP_ROOT: app.root,
      LANDO_APP_ROOT_BIND: app.root,
    },
    labels: {
      "io.lando.src": app.configFiles.join(","),
    },
  };
};

function escape(path) {
  return path.replace(/(?<![$])[$](?![$])/g, "$$$"); // Only escape single $ signs.
}`

However I do still believe this should be fixed because the '$' sign is valid path character in Windows and Linux and could lead to (who even uses a '$' sign in a file or directory name?) rare but unforeseen errors.

Have a nice day!

**Comment by marcandreappel** [comment]
> I would highly, highly recommend just installing docker inside WSL2 and then installing Lando there and running all of your lando apps outside of the windows FS mount (don't use /mnt/c/blah, use /home/unixuser/projectsnstuff). CPU and battery usage are night and day better as is the general speed of Lando. #1723 has lots of discussion about the easy ways to set all this up, this is how I run my system and for the past several weeks, it has been just as stable as my old Pop OS machine running native, just a tad slower.

@dustinleblanc I absolutely get that point, but in this case I can't use the PHP cli from Docker in PhpStorm on Windows (Xdebug, etc)

> I have fixed my issue and I'm closing this issue.

@JensYvanDeCraecker Did you encounter a problem with ` LOCATION  \\wsl$$\Ubuntu` double-dollar signs which generated 404s?

**Comment by dustinleblanc** [comment]
@marcandreappel yeah PHPStorm + WSL2 has been a difficult combo, I've had to just get used to running VS Code with my Windows box and I agree that it's less than amazing.
