### ISSUE TITLE
RPC Connection consistently throws error in logs for platform.sh services

### ISSUE THREAD

**Issue by pirog** [lando/lando#2364]
As far as i can tell this does not actually prevent anything from working correctly but once we have more users its certainly only a matter of time before its flagged, probably incorrectly, as the source of some other error. For that reason it would be good to resolve the underlying reason this gets reported. 

```
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 766, in gevent._greenlet.Greenlet.run
  File "/usr/lib/python2.7/dist-packages/gevent_jsonrpc/__init__.py", line 161, in _reader
    f = self._socket.makefile("r+b")
  File "/usr/lib/python2.7/dist-packages/gevent/_socket2.py", line 286, in makefile
    fobj = _fileobject(type(self)(_sock=self), mode, bufsize)
  File "/usr/lib/python2.7/dist-packages/gevent/_socket2.py", line 138, in __init__
    self._sock.setblocking(0)
  File "/usr/lib/python2.7/dist-packages/gevent/_socket2.py", line 90, in _dummy
    raise error(EBADF, 'Bad file descriptor')
error: [Errno 9] Bad file descriptor
2020-06-02T12:47:53Z <Greenlet at 0x7fb7b9cac578: <bound method RpcConnection._reader of <gevent_jsonrpc.RpcConnection object at 0x7fb7b9c23b90>>> failed with error
```

Steps to replicate:

1. `lando init` the `lando-d8` project
2. `lando start` that project
3. `lando logs -s app` 
4. If you don't see the above error in the logs then try a `lando restart` and/or `lando rebuild` until you do

**Comment by pirog** [comment]
@ralt says we might just need to modify
https://github.com/lando/lando/blob/master/experimental/plugins/lando-platformsh/scripts/psh-fake-rpc.py

to remove ` and c.close()`. He thinks this is causing the socket to double close which is what causes the error

**Comment by mikemilano** [comment]
@pirog this seems to resolve the trace errors. Unfortunately this wasn't the source of the Elastic issue.

Here's the PR: #2384
