### ISSUE TITLE
`config.drush: false` throws an error

### ISSUE THREAD

**Issue by chazchumley** [lando/lando#2372]
When simply running "lando" from command line.

Unhandled rejection TypeError: Invalid Version: null
    at new SemVer (/snapshot/lando/build/cli/node_modules/semver/classes/semver.js:22:13)
    at compare (/snapshot/lando/build/cli/node_modules/semver/functions/compare.js:3:3)
    at Object.gte (/snapshot/lando/build/cli/node_modules/semver/functions/gte.js:2:30)
    at new LandoDrupal (/snapshot/lando/build/cli/plugins/lando-recipes/types/drupaly/builder.js)
    at new LandoDrupal8 (/snapshot/lando/build/cli/plugins/lando-recipes/recipes/drupal8/builder.js)
    at AsyncEvents.<anonymous> (/snapshot/lando/build/cli/plugins/lando-recipes/app.js)
    at AsyncEvents.handle (/snapshot/lando/build/cli/lib/events.js)
    at /snapshot/lando/build/cli/lib/events.js
From previous event:
    at AsyncEvents.emit (/snapshot/lando/build/cli/lib/events.js)
    at /snapshot/lando/build/cli/lib/app.js
From previous event:
    at App.init (/snapshot/lando/build/cli/lib/app.js)
    at /snapshot/lando/build/cli/bin/lando.js
From previous event:
    at Object.<anonymous> (/snapshot/lando/build/cli/bin/lando.js)
    at Module._compile (pkg/prelude/bootstrap.js:1324:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:993:10)
    at Module.load (internal/modules/cjs/loader.js:813:32)
    at Function.Module._load (internal/modules/cjs/loader.js:725:14)
    at Function.Module.runMain (pkg/prelude/bootstrap.js:1379:12)
    at internal/main/run_main_module.js:17:11

**Comment by pirog** [comment]
@chazchumley none of our functional or unit tests flag this so im guessing it might be specific to your configuration. What does your Landofile look like?

**Comment by chazchumley** [comment]
name: fsis
recipe: drupal8

config:
  via: apache
  webroot: web
  php: 7.3
  xdebug: true
  drush: false
  conf:
    php: lando/config/php.ini
    mysql: lando/config/my.cnf

proxy:
  search:
    - search.fsis.lndo.site:8983
  pma:
    - pma.fsis.lndo.site
  mailhog:
    - mail.fsis.lndo.site

services:
  search:
    type: solr:8.4
    portforward: true
    core: collection1
    config:
      dir: solr-conf
  database:
    type: mariadb:10.1
  pma:
    type: phpmyadmin
    hosts:
      - database
  appserver:
    composer:
      phpunit/phpunit: 8
      behat/behat: 3.3.1
    run:
      - "ln -s /usr/local/bin/composer /usr/local/bin/composer.phar"
    run_as_root:
      - "bash /app/lando/scripts/build.sh"
    overrides:
      environment:
        DRUSH_OPTIONS_URI: "http://fsis.lndo.site"  # TODO Get this out of this file, but it doesn't seem to work in .lando.base.yml
  mailhog:
    type: mailhog
    hogfrom:
      - appserver

tooling:
  drush:
    service: appserver
    description: run drush commands
    cmd: /app/vendor/drush/drush/drush
  phpunit:
    service: appserver
    description: run PHPUnit- use lando phpunit
  behat:
    service: appserver
    description: run behat- use lando behat
    cmd: cd /app ; behat  # Run behat from the /app  directory
  mailhog:
    service: mailhog

**Comment by pirog** [comment]
I dont think `config.drush: false` has been supported syntax for awhile so that might be your issue. I'd just remove `drush` completely for now.

**Comment by chazchumley** [comment]
@pirog 

That did the trick...Thanks.

**Comment by pirog** [comment]
@chazchumley im going to keep this open so we can provide better handling for other people who are still using this syntax

**Comment by jklmnop** [comment]
this fails too, btw `config.drush: "*"` but `config.drush: ^8` works just fine. i'm using lando 3.0.5

if the star syntax is deprecated, it's still in the docs https://docs.lando.dev/config/drupal8.html#configuration

**Comment by pirog** [comment]
It's not deprecated so that would be a legit bug.

**Comment by pirog** [comment]
@jklmnop we are going to roll a hotfix release with this in it. also added in some better testing so we can catch this kind of thing better next time.

**Comment by jklmnop** [comment]
thank you, @pirog! 

fyi, the `.dmg` is still not available in the 3.0.6 releases, but i'll just keep an eye on it.

**Comment by pirog** [comment]
might just be a slow day for travis macOS builds

**Comment by tormi** [comment]
`config.drush: ^8` is broken now.

**Comment by pirog** [comment]
@tormi should be fixed in latestl 3.0.7 release
