### ISSUE TITLE
No container found for appserver_1

### ISSUE THREAD

**Issue by ahsynv** [lando/lando#2380]
### **My `.lando.yml`**

```
name: test-project
recipe: wordpress
config:
  webroot: .
  php: '7.2'
  xdebug: true
  ssl: true
services:
  pma:
    type: phpmyadmin
    hosts:
      - database
```

### **When i want to start lando on my project with "lando start" i have this error**

```
ERROR: No container found for appserver_1                             
ERROR ==>  message=, stack=Error                                      
    at C:\snapshot\lando\build\cli\lib\shell.js                       
From previous event:                                                  
    at Shell.sh (C:\snapshot\lando\build\cli\lib\shell.js)            
    at Object.dc (C:\snapshot\lando\build\cli\lib\bootstrap.js)       
    at compose (C:\snapshot\lando\build\cli\lib\bootstrap.js)         
From previous event:                                                  
    at C:\snapshot\lando\build\cli\lib\router.js                      
    at processImmediate (internal/timers.js:439:21)                   
From previous event:                                                  
    at Object.run (C:\snapshot\lando\build\cli\lib\router.js)         
    at run (C:\snapshot\lando\build\cli\lib\engine.js)                
    at C:\snapshot\lando\build\cli\lib\router.js                      
From previous event:                                                  
    at Object.eventWrapper (C:\snapshot\lando\build\cli\lib\router.js)
    at Engine.engineCmd (C:\snapshot\lando\build\cli\lib\engine.js)   
    at Engine.run (C:\snapshot\lando\build\cli\lib\engine.js)         
    at C:\snapshot\lando\build\cli\plugins\lando-core\app.js          
From previous event:                                                  
    at AsyncEvents.<anonymous> (C:\snapshot\lando\build\cli\plugins\la
    at AsyncEvents.handle (C:\snapshot\lando\build\cli\lib\events.js) 
    at C:\snapshot\lando\build\cli\lib\events.js                      
    at processImmediate (internal/timers.js:439:21)                   
From previous event:                                                  
    at AsyncEvents.emit (C:\snapshot\lando\build\cli\lib\events.js)   
    at C:\snapshot\lando\build\cli\lib\app.js                         
From previous event:                                                  
    at App.start (C:\snapshot\lando\build\cli\lib\app.js)             
    at Object.run (C:\snapshot\lando\build\cli\plugins\lando-core\task
From previous event:                                                  
    at C:\snapshot\lando\build\cli\lib\cli.js                         
From previous event:                                                  
    at Object.handler (C:\snapshot\lando\build\cli\lib\cli.js)        
    at Object.runCommand (C:\snapshot\lando\build\cli\node_modules\yar
    at Object.parseArgs [as _parseArgs] (C:\snapshot\lando\build\cli\n
    at Function.get [as argv] (C:\snapshot\lando\build\cli\node_module
    at Cli.init (C:\snapshot\lando\build\cli\lib\cli.js)              
    at Cli.run (C:\snapshot\lando\build\cli\lib\cli.js)               
    at Object.<anonymous> (C:\snapshot\lando\build\cli\bin\lando.js)  
    at Module._compile (pkg/prelude/bootstrap.js:1324:22)             
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:9
    at Module.load (internal/modules/cjs/loader.js:813:32)            
    at Function.Module._load (internal/modules/cjs/loader.js:725:14)  
    at Function.Module.runMain (pkg/prelude/bootstrap.js:1379:12)     
    at internal/main/run_main_module.js:17:11, __stackCleaned__=true  
```

### **This is my logfile with 'lando restart -vvv'**

```
ERROR ==> Error: (HTTP code 500) server error - container b2440934184c955e804c62a6acbe25e27e76eac6778579c93f7ae38cb6d1e3c4 is not connected to the network lando_bridge_network
    at C:\snapshot\lando\build\cli\node_modules\docker-modem\lib\modem.js:254:17
    at getCause (C:\snapshot\lando\build\cli\node_modules\docker-modem\lib\modem.js:284:7)
    at Modem.buildPayload (C:\snapshot\lando\build\cli\node_modules\docker-modem\lib\modem.js:253:5)
    at IncomingMessage.<anonymous> (C:\snapshot\lando\build\cli\node_modules\docker-modem\lib\modem.js:229:14)
    at IncomingMessage.emit (events.js:215:7)
    at endReadableNT (_stream_readable.js:1184:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
From previous event:
    at Network.disconnect (C:\snapshot\lando\build\cli\node_modules\dockerode\lib\network.js:150:12)
    at C:\snapshot\lando\build\cli\plugins\lando-networking\app.js
From previous event:
    at AsyncEvents.<anonymous> (C:\snapshot\lando\build\cli\plugins\lando-networking\app.js)
    at AsyncEvents.handle (C:\snapshot\lando\build\cli\lib\events.js)
    at C:\snapshot\lando\build\cli\lib\events.js
From previous event:
    at AsyncEvents.emit (C:\snapshot\lando\build\cli\lib\events.js)
From previous event:
    at App.start (C:\snapshot\lando\build\cli\lib\app.js)
    at C:\snapshot\lando\build\cli\lib\app.js
From previous event:
    at App.restart (C:\snapshot\lando\build\cli\lib\app.js)
    at Object.run (C:\snapshot\lando\build\cli\plugins\lando-core\tasks\restart.js)
From previous event:
    at C:\snapshot\lando\build\cli\lib\cli.js
From previous event:
    at Object.handler (C:\snapshot\lando\build\cli\lib\cli.js)
    at Object.runCommand (C:\snapshot\lando\build\cli\node_modules\yargs\lib\command.js:238:44)
    at Object.parseArgs [as _parseArgs] (C:\snapshot\lando\build\cli\node_modules\yargs\yargs.js:1063:30)
    at Function.get [as argv] (C:\snapshot\lando\build\cli\node_modules\yargs\yargs.js:1004:21)
    at Cli.init (C:\snapshot\lando\build\cli\lib\cli.js)
    at Cli.run (C:\snapshot\lando\build\cli\lib\cli.js)
    at Object.<anonymous> (C:\snapshot\lando\build\cli\bin\lando.js)
    at Module._compile (pkg/prelude/bootstrap.js:1324:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:993:10)
    at Module.load (internal/modules/cjs/loader.js:813:32)
    at Function.Module._load (internal/modules/cjs/loader.js:725:14)
    at Function.Module.runMain (pkg/prelude/bootstrap.js:1379:12)
    at internal/main/run_main_module.js:17:11
```

**Comment by Developer-Rocha** [comment]
I have the same problem and I'm use the same version of the Lando (v3.0.5)
