### ISSUE TITLE
Lando suddenly won't start?

### ISSUE THREAD

**Issue by tonypartridge** [lando/lando#2577]
Soo today I decided to fire up a container and all of a sudden lando won't start see:

devsite 11:29:28 INFO ==> starting app...
lando        11:29:28 WARN ==> docker is not running!
Starting docker up before we begin... please wait...
lando        11:29:29 ERROR ==> Error
    at C:\snapshot\lando\build\cli\lib\shell.js
From previous event:
    at Shell.sh (C:\snapshot\lando\build\cli\lib\shell.js)
    at C:\snapshot\lando\build\cli\lib\daemon.js
    at processImmediate (internal/timers.js:439:21)
From previous event:
    at C:\snapshot\lando\build\cli\lib\daemon.js
From previous event:
    at LandoDaemon.up (C:\snapshot\lando\build\cli\lib\daemon.js)
    at Object.eventWrapper (C:\snapshot\lando\build\cli\lib\router.js)
    at Engine.engineCmd (C:\snapshot\lando\build\cli\lib\engine.js)
    at Engine.list (C:\snapshot\lando\build\cli\lib\engine.js)
    at AsyncEvents.<anonymous> (C:\snapshot\lando\build\cli\plugins\lando-core\app.js)
    at AsyncEvents.handle (C:\snapshot\lando\build\cli\lib\events.js)
    at C:\snapshot\lando\build\cli\lib\events.js
From previous event:
    at AsyncEvents.emit (C:\snapshot\lando\build\cli\lib\events.js)
    at C:\snapshot\lando\build\cli\lib\app.js
From previous event:
    at App.init (C:\snapshot\lando\build\cli\lib\app.js)
    at initAndReport (C:\snapshot\lando\build\cli\lib\app.js)
    at App.start (C:\snapshot\lando\build\cli\lib\app.js)
    at Object.run (C:\snapshot\lando\build\cli\plugins\lando-core\tasks\start.js)
From previous event:
    at C:\snapshot\lando\build\cli\lib\cli.js
From previous event:
    at Object.handler (C:\snapshot\lando\build\cli\lib\cli.js)
    at Object.runCommand (C:\snapshot\lando\build\cli\node_modules\yargs\lib\command.js:238:44)
    at Object.parseArgs [as _parseArgs] (C:\snapshot\lando\build\cli\node_modules\yargs\yargs.js:1063:30)
    at Function.get [as argv] (C:\snapshot\lando\build\cli\node_modules\yargs\yargs.js:1004:21)
    at Cli.init (C:\snapshot\lando\build\cli\lib\cli.js)
    at Cli.run (C:\snapshot\lando\build\cli\lib\cli.js)
    at Object.<anonymous> (C:\snapshot\lando\build\cli\bin\lando.js)
    at Module._compile (pkg/prelude/bootstrap.js:1324:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:993:10)
    at Module.load (internal/modules/cjs/loader.js:813:32)
    at Function.Module._load (internal/modules/cjs/loader.js:725:14)
    at Function.Module.runMain (pkg/prelude/bootstrap.js:1379:12)
    at internal/main/run_main_module.js:17:11

Any suggestions?

**Comment by tonypartridge** [comment]
Docker issue, removed, disabled hyper-v and restarted. Suspect it was caused by the latest windows update. Will try enabling Hyper V later.
