### ISSUE TITLE
Drupal 9 installation fails, requires drush cache:rebuild

### ISSUE THREAD

**Issue by gitressa** [lando/lando#2582]
After creating a fresh Drupal 9 installation, I get a WSOD with an error, `The website encountered an unexpected error. Please try again later.`

### System
- Ubuntu 18.04
- Docker 19.03.12
- Lando 3.0.10

(Side note: Installed with `wget https://files.devwithlando.io/lando-stable.deb` from https://docs.lando.dev/basics/installation.html#linux so shouldn't I have 3.0.9, which is the [Latest release](https://github.com/lando/lando/releases)?)

To re-create:
```
$ composer create-project drupal/recommended-project d9
$ cd d9/
$ lando init --source cwd --recipe drupal9 --webroot web --name d9comppath
$ lando start
$ drush site-install --db-url=mysql://drupal9:drupal9@database/drupal9 -y
$ drush uli -l https://d9comppath.lndo.site
```
Visit the generated login link and get this error:

> The website encountered an unexpected error. Please try again later.

Run `drush cache:rebuild` a few times and the web site works as expected.

Another way to re-create the error is adding and enabling a module:
```
$ composer require drupal/admin_toolbar
$ drush en admin_toolbar admin_toolbar_tools admin_toolbar_search -y
```

### From the error log

After running `drush uli` and visiting the generated link, this is in the error log:

```
Location  https://d9comppath.lndo.site/user/reset/1/1598698441/gLeERYC8y0o539-bHwCcDmN0KphVAZGjsug13XUIhyc/login

Message   Error: Class 'Drush\Log\DrushLog' not found in Drupal\Component\DependencyInjection\Container->createService() (line 257 of /app/web/core/lib/Drupal/Component/DependencyInjection/Container.php)

#0 /app/web/core/lib/Drupal/Component/DependencyInjection/Container.php(171): Drupal\Component\DependencyInjection\Container->createService(Array, 'logger.drupalto...')
#1 /app/web/core/lib/Drupal/Component/DependencyInjection/Container.php(432): Drupal\Component\DependencyInjection\Container->get('logger.drupalto...', 1)
#2 /app/web/core/lib/Drupal/Component/DependencyInjection/Container.php(271): Drupal\Component\DependencyInjection\Container->resolveServicesAndParameters(Array)
#3 /app/web/core/lib/Drupal/Component/DependencyInjection/Container.php(171): Drupal\Component\DependencyInjection\Container->createService(Array, 'logger.factory')
#4 /app/web/core/modules/user/src/Controller/UserController.php(90): Drupal\Component\DependencyInjection\Container->get('logger.factory')
#5 /app/web/core/lib/Drupal/Core/DependencyInjection/ClassResolver.php(28): Drupal\user\Controller\UserController::create(Object(Drupal\Core\DependencyInjection\Container))
#6 /app/web/core/lib/Drupal/Core/Controller/ControllerResolver.php(117): Drupal\Core\DependencyInjection\ClassResolver->getInstanceFromDefinition('\\Drupal\\user\\Co...')
#7 /app/web/core/lib/Drupal/Core/Controller/ControllerResolver.php(69): Drupal\Core\Controller\ControllerResolver->createController('\\Drupal\\user\\Co...')
#8 /app/web/core/lib/Drupal/Core/Controller/ControllerResolver.php(85): Drupal\Core\Controller\ControllerResolver->getControllerFromDefinition('\\Drupal\\user\\Co...', '/user/reset/1/1...')
#9 /app/vendor/symfony/http-kernel/HttpKernel.php(141): Drupal\Core\Controller\ControllerResolver->getController(Object(Symfony\Component\HttpFoundation\Request))
#10 /app/vendor/symfony/http-kernel/HttpKernel.php(80): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
#11 /app/web/core/lib/Drupal/Core/StackMiddleware/Session.php(57): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#12 /app/web/core/lib/Drupal/Core/StackMiddleware/KernelPreHandle.php(47): Drupal\Core\StackMiddleware\Session->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#13 /app/web/core/modules/page_cache/src/StackMiddleware/PageCache.php(191): Drupal\Core\StackMiddleware\KernelPreHandle->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#14 /app/web/core/modules/page_cache/src/StackMiddleware/PageCache.php(128): Drupal\page_cache\StackMiddleware\PageCache->fetch(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#15 /app/web/core/modules/page_cache/src/StackMiddleware/PageCache.php(82): Drupal\page_cache\StackMiddleware\PageCache->lookup(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#16 /app/web/core/lib/Drupal/Core/StackMiddleware/ReverseProxyMiddleware.php(47): Drupal\page_cache\StackMiddleware\PageCache->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#17 /app/web/core/lib/Drupal/Core/StackMiddleware/NegotiationMiddleware.php(52): Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#18 /app/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Drupal\Core\StackMiddleware\NegotiationMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#19 /app/web/core/lib/Drupal/Core/DrupalKernel.php(705): Stack\StackedHttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#20 /app/web/index.php(19): Drupal\Core\DrupalKernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#21 {main}

```
Visit to front page
```
Location  https://d9comppath.lndo.site/
Message   Error: Class 'Drush\Log\DrushLog' not found in Drupal\Component\DependencyInjection\Container->createService() (line 257 of /app/web/core/lib/Drupal/Component/DependencyInjection/Container.php)

#0 /app/web/core/lib/Drupal/Component/DependencyInjection/Container.php(171): Drupal\Component\DependencyInjection\Container->createService(Array, 'logger.drupalto...')
#1 /app/web/core/lib/Drupal/Component/DependencyInjection/Container.php(432): Drupal\Component\DependencyInjection\Container->get('logger.drupalto...', 1)
#2 /app/web/core/lib/Drupal/Component/DependencyInjection/Container.php(271): Drupal\Component\DependencyInjection\Container->resolveServicesAndParameters(Array)
#3 /app/web/core/lib/Drupal/Component/DependencyInjection/Container.php(171): Drupal\Component\DependencyInjection\Container->createService(Array, 'logger.factory')
#4 /app/web/core/lib/Drupal/Component/DependencyInjection/Container.php(432): Drupal\Component\DependencyInjection\Container->get('logger.factory', 1)
#5 /app/web/core/lib/Drupal/Component/DependencyInjection/Container.php(247): Drupal\Component\DependencyInjection\Container->resolveServicesAndParameters(Array)
#6 /app/web/core/lib/Drupal/Component/DependencyInjection/Container.php(171): Drupal\Component\DependencyInjection\Container->createService(Array, 'logger.channel....')
#7 /app/web/core/lib/Drupal/Component/DependencyInjection/Container.php(432): Drupal\Component\DependencyInjection\Container->get('logger.channel....', 1)
#8 /app/web/core/lib/Drupal/Component/DependencyInjection/Container.php(235): Drupal\Component\DependencyInjection\Container->resolveServicesAndParameters(Array)
#9 /app/web/core/lib/Drupal/Component/DependencyInjection/Container.php(171): Drupal\Component\DependencyInjection\Container->createService(Array, 'file_system')
#10 /app/web/core/lib/Drupal.php(156): Drupal\Component\DependencyInjection\Container->get('file_system')
#11 /app/web/core/includes/theme.inc(221): Drupal::service('file_system')
#12 /app/web/core/themes/engines/twig/twig.engine(18): drupal_find_theme_templates(Array, '.html.twig', 'core/themes/bar...')
#13 /app/web/core/lib/Drupal/Core/Theme/Registry.php(454): twig_theme(Array, 'theme_engine', 'bartik', 'core/themes/bar...')
#14 /app/web/core/lib/Drupal/Core/Theme/Registry.php(363): Drupal\Core\Theme\Registry->processExtension(Array, 'twig', 'theme_engine', 'bartik', 'core/themes/bar...')
#15 /app/web/core/lib/Drupal/Core/Theme/Registry.php(240): Drupal\Core\Theme\Registry->build()
#16 /app/web/core/lib/Drupal/Core/Utility/ThemeRegistry.php(88): Drupal\Core\Theme\Registry->get()
#17 /app/web/core/lib/Drupal/Core/Utility/ThemeRegistry.php(69): Drupal\Core\Utility\ThemeRegistry->initializeRegistry()
#18 /app/web/core/lib/Drupal/Core/Theme/Registry.php(260): Drupal\Core\Utility\ThemeRegistry->__construct('theme_registry:...', Object(Drupal\Core\Cache\ChainedFastBackend), Object(Drupal\Core\ProxyClass\Lock\DatabaseLockBackend), Array, true)
#19 /app/web/core/lib/Drupal/Core/Theme/ThemeManager.php(142): Drupal\Core\Theme\Registry->getRuntime()
#20 /app/web/core/lib/Drupal/Core/Render/Renderer.php(431): Drupal\Core\Theme\ThemeManager->render(Array, Array)
#21 /app/web/core/lib/Drupal/Core/Render/Renderer.php(444): Drupal\Core\Render\Renderer->doRender(Array)
#22 /app/web/core/lib/Drupal/Core/Render/Renderer.php(200): Drupal\Core\Render\Renderer->doRender(Array, false)
#23 /app/web/core/lib/Drupal/Core/Render/MainContent/HtmlRenderer.php(226): Drupal\Core\Render\Renderer->render(Array, false)
#24 /app/web/core/lib/Drupal/Core/Render/Renderer.php(573): Drupal\Core\Render\MainContent\HtmlRenderer->Drupal\Core\Render\MainContent\{closure}()
#25 /app/web/core/lib/Drupal/Core/Render/MainContent/HtmlRenderer.php(227): Drupal\Core\Render\Renderer->executeInRenderContext(Object(Drupal\Core\Render\RenderContext), Object(Closure))
#26 /app/web/core/lib/Drupal/Core/Render/MainContent/HtmlRenderer.php(117): Drupal\Core\Render\MainContent\HtmlRenderer->prepare(Array, Object(Symfony\Component\HttpFoundation\Request), Object(Drupal\Core\Routing\CurrentRouteMatch))
#27 /app/web/core/lib/Drupal/Core/EventSubscriber/MainContentViewSubscriber.php(90): Drupal\Core\Render\MainContent\HtmlRenderer->renderResponse(Array, Object(Symfony\Component\HttpFoundation\Request), Object(Drupal\Core\Routing\CurrentRouteMatch))
#28 /app/vendor/symfony/event-dispatcher/LegacyEventDispatcherProxy.php(78): Drupal\Core\EventSubscriber\MainContentViewSubscriber->onViewRenderArray(Object(Symfony\Component\HttpKernel\Event\ViewEvent), 'kernel.view', Object(Symfony\Component\EventDispatcher\LegacyEventDispatcherProxy))
#29 /app/vendor/symfony/http-kernel/HttpKernel.php(163): Symfony\Component\EventDispatcher\LegacyEventDispatcherProxy->dispatch(Object(Symfony\Component\HttpKernel\Event\ViewEvent), 'kernel.view')
#30 /app/vendor/symfony/http-kernel/HttpKernel.php(80): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
#31 /app/web/core/lib/Drupal/Core/StackMiddleware/Session.php(57): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#32 /app/web/core/lib/Drupal/Core/StackMiddleware/KernelPreHandle.php(47): Drupal\Core\StackMiddleware\Session->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#33 /app/web/core/modules/page_cache/src/StackMiddleware/PageCache.php(191): Drupal\Core\StackMiddleware\KernelPreHandle->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#34 /app/web/core/modules/page_cache/src/StackMiddleware/PageCache.php(128): Drupal\page_cache\StackMiddleware\PageCache->fetch(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#35 /app/web/core/modules/page_cache/src/StackMiddleware/PageCache.php(82): Drupal\page_cache\StackMiddleware\PageCache->lookup(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#36 /app/web/core/lib/Drupal/Core/StackMiddleware/ReverseProxyMiddleware.php(47): Drupal\page_cache\StackMiddleware\PageCache->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#37 /app/web/core/lib/Drupal/Core/StackMiddleware/NegotiationMiddleware.php(52): Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#38 /app/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Drupal\Core\StackMiddleware\NegotiationMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#39 /app/web/core/lib/Drupal/Core/DrupalKernel.php(705): Stack\StackedHttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#40 /app/web/index.php(19): Drupal\Core\DrupalKernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#41 {main}
```

**Comment by pirog** [comment]
@gitressa i don’t see how lando would be involved here. FWIW can not replicate

**Comment by gitressa** [comment]
Thanks for checking @pirog, I'll try to dig some more. Interestingly, the same process works for Drupal 8 just fine ... could it be because Drush 10 is added in the Drupal 9 recipe, and some tables are not ready, right away? I'll try to run the commands with more verbosity, and see if anything stands out.

**Comment by alexmazaltov** [comment]
I faced the same Error
drush cr fixed the error randomly.
I am using drush installed globally via `cgr`
Drush Commandline Tool 10.3.4

**Comment by greggmarshall** [comment]
I think I'm seeing this also.
Drupal 9.0.6 with Drush 10.3.4 using Lando v3.0.11
Site created using "composer create-project drupal/recommended-project"
If I do a "lando drush cex" then switch to the browser and refresh the front page I get the error
Doing a "lando drush cr" then refresh the front page and it returns

Then I tried installing drush locally using "lando composer require drush/drush" and it would appear I'm not getting the error (so far)

YMMV

**Comment by gitressa** [comment]
This is still an issue in the latest Lando version `v3.0.14`. It also happens with the dev-release:

```
git clone --branch 9.1.x https://git.drupal.org/project/drupal.git d91dev
cd d91dev/
lando init --source cwd --recipe drupal9 --webroot . --name d91dev
composer install
drush site-install --db-url=mysql://drupal9:drupal9@database/drupal9 -y
```
Could we add a `drush cache:rebuild` to the Drupal 9 build process, at the very end?

**Comment by gitressa** [comment]
This is still an issue in the latest Lando version `v3.0.14`. It also happens with the dev-release:

```
git clone --branch 9.1.x https://git.drupal.org/project/drupal.git d91dev
cd d91dev/
lando init --source cwd --recipe drupal9 --webroot . --name d91dev
composer install
drush site-install --db-url=mysql://drupal9:drupal9@database/drupal9 -y
```

**Comment by gitressa** [comment]
Even just enabling a module results in `The website encountered an unexpected error. Please try again later.` error.

**Comment by yorchperaza** [comment]
This error still happened, my version of Drupal is 9.0.7, I'm using Lando in my local.

**Comment by gitressa** [comment]
Thanks for sharing your solution @greggmarshall. I tried adding Drush 10 site-locally (`composer` or `lando composer` seems to work equally well) and rebuilding, and Drupal 9 works fine, after enabling and disabling modules, etc. with Drush 10:

```
composer require drush/drush
lando rebuild -y
```
I wonder if it is possible somehow via the `drupal9` recipe to add Drush 10 as a dependency in `composer.json`, so that it is installed to be available site-locally by default?

Otherwise, I agree that the `■ May need site-local drush` warning needs to be reworded into stronger language, something like `■ Requires site-local drush` and the command to do it.

**Comment by gitressa** [comment]
Or could the `drupal9` recipe check if `drush/drush` is present in `composer.json`, to see if the user has already added it?

```
$ composer create-project drupal/recommended-project d9
$ cd d9
$ composer require drush/drush
$ lando init --source cwd --recipe drupal9 --webroot web --name d9
```

In this case, Lando should not install a global Drush.

**Comment by pirog** [comment]
My opinion is that we probably dont want lando modifying users code by installing a site-local drush for the user and i dont think checking `composer.json` is something that long term is going to be as reliable and robust as we want it to be although i certainly get the spirit of that approach. 

I think the solution that we were considering here is to have a "fake" globally installed `drush` buried all the way at the end of `PATH` so that if the user does not have `drush` installed in any of the myriad ways one can install `drush` they end up hitting our "fake" one. The "fake" one would basically just be a shell script that says "HEY! You need to install a site local drush by running composer require drush/drush". Then once you install it, `PATH` is set up so the user hits the "real" drush instead of the "fake" one

**Comment by gitressa** [comment]
That sounds like a sane solution @pirog, which would work well.

Still, wouldn't it be worth considering somehow not installing a global `drush`, if a site-local `drush` is already present? It seems to me like extra time used if Lando installs a global `drush` via Composer, which will not be used ... Or will the fake `drush` you mention not be `drush` 10 installed by Composer, but just the shell script you mention? That would probably work.

**Comment by pirog** [comment]
Just the shell script. So the implication of my suggestion is that lando would no longer globally install Drush for versions of Drupal that dont like that sort of thing.

**Comment by greggmarshall** [comment]
I agree on not installing Drush for users.  My original point was to make the warning a bit stronger to emphasize the need to have a local Drush, perhaps explaining what needs to be done (drush cr more often) if you don't.

**Comment by pirog** [comment]
Yup @greggmarshall 💯 agreed. I _think_ what we are planning on addresses that concenr.

**Comment by gitressa** [comment]
Sounds good @pirog, not installing global `drush` and a stronger warning that adding local-site `drush` is required would be a great solution.
