### ISSUE TITLE
YAMLException after uninstall nodejs and install nvm windows

### ISSUE THREAD

**Issue by joseooortega** [lando/lando#2636]
A couple of days ago I uninstalled my local node.js installation and tried to use https://github.com/coreybutler/nvm-windows to get rid of different node versions for projects.

After all this management and prove that nvm was working fine, I tried the classic "lando starts" in my current project that always has worked with lando with zero problems and the below error prompted:

```
C:\snapshot\lando\build\cli\node_modules\js-yaml\lib\js-yaml\loader.js:171
throw generateError(state, message);
^
YAMLException: end of the stream or a document separator is expected at line 1, column 1:

^
at generateError (C:\snapshot\lando\build\cli\node_modules\js-yaml\lib\js-yaml\loader.js:165:10)
at throwError (C:\snapshot\lando\build\cli\node_modules\js-yaml\lib\js-yaml\loader.js:171:9)
at readDocument (C:\snapshot\lando\build\cli\node_modules\js-yaml\lib\js-yaml\loader.js:1512:5)
at loadDocuments (C:\snapshot\lando\build\cli\node_modules\js-yaml\lib\js-yaml\loader.js:1548:5)
at load (C:\snapshot\lando\build\cli\node_modules\js-yaml\lib\js-yaml\loader.js:1569:19)
at Object.safeLoad (C:\snapshot\lando\build\cli\node_modules\js-yaml\lib\js-yaml\loader.js:1591:10)
at C:\snapshot\lando\build\cli\lib\config.js
at arrayReduce (C:\snapshot\lando\build\cli\node_modules\lodash\lodash.js:683:21)
at Function.reduce (C:\snapshot\lando\build\cli\node_modules\lodash\lodash.js:9707:14)
at LodashWrapper.reduce (C:\snapshot\lando\build\cli\node_modules\lodash\lodash.js:15758:25) {
    name: 'YAMLException',
    reason: 'end of the stream or a document separator is expected',
    mark: Mark {
    name: null,
    buffer: '\u0000\u0000\u0000\n\u0000',
    position: 0,
    line: 0,
    column: 0
    },
    message: 'end of the stream or a document separator is expected at line 1, column 1:\n' +
    '    \n' +
    '    ^'
}
```

Then I realyzed that even the "lando" command throws the same error.

The error message is so generic and because of that i can't find anything related on google.

I tried reinstalling docker, lando, nodejs and nvm windows but anything seems to work. This message is my last hope before I format the computer.

Thanks in advance.

**Comment by joseooortega** [comment]
Well.. after a long research I manage to fix it following this from lando docu: https://docs.lando.dev/basics/uninstalling.html#further-cleanup
