### ISSUE TITLE
ERROR ==> Cannot read property 'split' of undefined (Windows 10 Pro)

### ISSUE THREAD

**Issue by K2ouMais** [lando/lando#2657]
Hello,

OS: Windows 10 Pro (Build 20H2 with all updates installed)
Docker: stable 2.4.0.0
Lando: 3.0.16

I tried to initialize lando on a laravel project, but there is an error and I cant choose anything:
ERROR ==> Cannot read property 'split' of undefined

I dont get a chance to choose anything through the arrow buttons, because it exits.

Thank you

**Comment by pirog** [comment]
@K2ouMais it would be very useful if you could write out some steps we can take to replicate this!

**Comment by K2ouMais** [comment]
Instead of explaining the steps, I made a video so you can see what happens.

- I showed Docker up and running and the version of it.
- Installed the newest version of Lando.
- Tried to initialize lando on an empty folder.
- I have installed a Laravel project and tried there to initialize Lando.
- Tried to initialize Lando on the Laravel project with a cmd prompt instead of Cmder.

It jumps everytime out of the list and so I dont get a chance to choose anything.

Here is the Video:
https://youtu.be/MRsTnHpBYvM

**Comment by de-Stan** [comment]
Hello, i have encountered this before. I guess you have updated to the latest version of Docker 2.4.0.0 ? If so, just remove it and then install the docker bundled with the lando package. There seems to be some sort of a bug with the new version

**Comment by K2ouMais** [comment]
> Hello, i have encountered this before. I guess you have updated to the latest version of Docker 2.4.0.0 ? If so, just remove it and then install the docker bundled with the lando package. There seems to be some sort of a bug with the new version
> 
> Edit: Seeing the video i see you do have 2.4.0.0 installed so try installing the bundled one.

That was exacty the problem. If you install the provided Docker version it will work.

**Comment by pirog** [comment]
Let's keep this open so we know about it when we make the jump to 2.4.0.0

**Comment by de-Stan** [comment]
OK since we keep info about the newest version i will also note these:

At least in Laravel recipe the composer is not found. Building the appserver, fails with a warning. Also trying to run composer commands through lando like `lando composer install` will also fail with a crash.

I'm not really sure about this but maybe having Hyper-V in Windows instead of making the jump to WSL the above bugs do not exist. Do not take my words for granted i was troubleshooting with two computers and one was using Hyper-V for docker but i do not remember if i installed the provided docker version.

**Comment by pirog** [comment]
I can replicate this on Windows 10 Pro and Docker Desktop 2.4.0.0

**Comment by pirog** [comment]
Alright, this will be fixed in the next release!

**Comment by JedrzejMarciniakDev** [comment]
OS: Win 11 Pro 22H2 / WSL2
Lando 3.6.11
Docker version 20.10.23, build 7155243
Docker Desktop 4.17.0 (99724)

Cant run any command with lando.
For lando status, init or start i get below error:

Unhandled rejection TypeError: Cannot read properties of undefined (reading 'split')
    at /snapshot/cli/node_modules/@lando/platformsh/lib/config.js
    at arrayMap (/snapshot/cli/node_modules/@lando/platformsh/node_modules/lodash/lodash.js)
    at Function.map (/snapshot/cli/node_modules/@lando/platformsh/node_modules/lodash/lodash.js)
    at interceptor (/snapshot/cli/node_modules/@lando/platformsh/node_modules/lodash/lodash.js)
    at Function.thru (/snapshot/cli/node_modules/@lando/platformsh/node_modules/lodash/lodash.js)
    at /snapshot/cli/node_modules/@lando/platformsh/node_modules/lodash/lodash.js
    at arrayReduce (/snapshot/cli/node_modules/@lando/platformsh/node_modules/lodash/lodash.js)
    at baseWrapperValue (/snapshot/cli/node_modules/@lando/platformsh/node_modules/lodash/lodash.js)
    at LodashWrapper.wrapperValue (/snapshot/cli/node_modules/@lando/platformsh/node_modules/lodash/lodash.js)
    at Object.getSyncableRelationships (/snapshot/cli/node_modules/@lando/platformsh/lib/config.js)
    at AsyncEvents.<anonymous> (/snapshot/cli/node_modules/@lando/platformsh/app.js)
    at AsyncEvents.handle (/snapshot/cli/node_modules/@lando/core/lib/events.js)
    at /snapshot/cli/node_modules/@lando/core/lib/events.js
From previous event:
    at AsyncEvents.emit (/snapshot/cli/node_modules/@lando/core/lib/events.js)
    at /snapshot/cli/node_modules/@lando/core/lib/app.js
From previous event:
    at App.init (/snapshot/cli/node_modules/@lando/core/lib/app.js)
    at /snapshot/cli/bin/lando.js
    at processImmediate (node:internal/timers:466:21)
From previous event:
    at Object.<anonymous> (/snapshot/cli/bin/lando.js)
    at Module._compile (pkg/prelude/bootstrap.js:1887:22)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.runMain (pkg/prelude/bootstrap.js:1940:12)
    at node:internal/main/run_main_module:17:47
