### ISSUE TITLE
Lando Init Failure

### ISSUE THREAD

**Issue by jahzlariosa** [lando/lando#2668]
Lando init throws this error

` remote git repo or archive ERROR ==> Cannot read property 'split' of undefined`

```
current working directory
  github
  lagoon
  pantheon
  platformsh
  remote git repo or archive lando 00:54:34 ERROR ==> TypeError: Cannot read property 'split' of undefined
    at clean (C:\snapshot\lando\build\cli\lib\engine.js)
    at C:\snapshot\lando\build\cli\lib\engine.js
    at C:\snapshot\lando\build\cli\node_modules\lodash\lodash.js:3543:27
    at C:\snapshot\lando\build\cli\node_modules\lodash\lodash.js:4925:15
    at baseForOwn (C:\snapshot\lando\build\cli\node_modules\lodash\lodash.js:2990:24)
    at C:\snapshot\lando\build\cli\node_modules\lodash\lodash.js:4894:18
    at baseMap (C:\snapshot\lando\build\cli\node_modules\lodash\lodash.js:3542:7)
    at Function.map (C:\snapshot\lando\build\cli\node_modules\lodash\lodash.js:9580:14)
    at interceptor (C:\snapshot\lando\build\cli\node_modules\lodash\lodash.js:17046:35)
    at Function.thru (C:\snapshot\lando\build\cli\node_modules\lodash\lodash.js:8817:14)
    at C:\snapshot\lando\build\cli\node_modules\lodash\lodash.js:4388:28
    at arrayReduce (C:\snapshot\lando\build\cli\node_modules\lodash\lodash.js:683:21)
    at baseWrapperValue (C:\snapshot\lando\build\cli\node_modules\lodash\lodash.js:4387:14)
    at LodashWrapper.wrapperValue (C:\snapshot\lando\build\cli\node_modules\lodash\lodash.js:9072:14)
    at C:\snapshot\lando\build\cli\lib\engine.js
From previous event:
    at Engine.getCompatibility (C:\snapshot\lando\build\cli\lib\engine.js)
    at C:\snapshot\lando\build\cli\lib\cli.js
From previous event:
    at C:\snapshot\lando\build\cli\lib\cli.js
From previous event:
    at Object.handler (C:\snapshot\lando\build\cli\lib\cli.js)
    at Object.runCommand (C:\snapshot\lando\build\cli\node_modules\yargs\lib\command.js:238:44)
    at Object.parseArgs [as _parseArgs] (C:\snapshot\lando\build\cli\node_modules\yargs\yargs.js:1063:30)
    at Function.get [as argv] (C:\snapshot\lando\build\cli\node_modules\yargs\yargs.js:1004:21)
    at Cli.init (C:\snapshot\lando\build\cli\lib\cli.js)
    at Cli.run (C:\snapshot\lando\build\cli\lib\cli.js)
    at Object.<anonymous> (C:\snapshot\lando\build\cli\bin\lando.js)
    at Module._compile (pkg/prelude/bootstrap.js:1324:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:993:10)
    at Module.load (internal/modules/cjs/loader.js:813:32)
    at Function.Module._load (internal/modules/cjs/loader.js:725:14)
    at Function.Module.runMain (pkg/prelude/bootstrap.js:1379:12)
    at internal/main/run_main_module.js:17:11

```

**Comment by jahzlariosa** [comment]
That worked! Thanks @pirog
