### ISSUE TITLE
Platform.sh install fails

### ISSUE THREAD

**Issue by pjoulot** [lando/lando#2684]
Hello,

1. Setup a website using platform.sh by following the steps:
https://docs.lando.dev/config/platformsh.html#getting-started

My .lando.yml is very basic
```
name: mywebsite
recipe: platformsh
config:
  id: myid
```

2. After lando init and lando start. Everything seems to have been ok in the console, but it seems it actually didn't. If you go to the URL, the website has a fatal error. The error doesn't even seem to show in the logs. But you can see previous errors than seemed to happen during the generation of the nginx config. The error seems to happen in platformsh-prepare.

```
2020-11-10 00:29:11,018 platformsh.agent.service ERROR Unable to render template /etc/nginx/nginx.conf: 

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/platformsh/agent/service.py", line 379, in generate_config_files
    safe_write(path, template.render(**self.config), mode=output_mode)
  File "/usr/lib/python2.7/dist-packages/mako/template.py", line 462, in render
    return runtime._render(self, self.callable_, args, data)
  File "/usr/lib/python2.7/dist-packages/mako/runtime.py", line 838, in _render
    **_kwargs_for_callable(callable_, data))
  File "/usr/lib/python2.7/dist-packages/mako/runtime.py", line 873, in _render_context
    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
  File "/usr/lib/python2.7/dist-packages/mako/runtime.py", line 899, in _exec_template
    callable_(context, *args, **kwargs)
  File "/etc/nginx/nginx.conf.psh-tmpl", line 0, in render_body
```

My setup:
- Ubuntu 18.04
- Lando v3.0.18

My local database doesn't seem to work as well. If I run lando database.

`lando database
ERROR 2002 (HY000): Can't connect to MySQL server on 'db' (115)`

**Comment by dustinleblanc** [comment]
Spinning up the Drupal 9 template from Platform I am able to reproduce an initial error, but running `lando drush cr` twice in a row brings the site back up.

THe error only showed up for me after the installer ran.

**Comment by kwiechmann** [comment]
Any additional thoughts? Getting a similar issue with a different (and older) environment.
* Drupal Core 7.67
* PHP 7.2

**Comment by JimmyHowe** [comment]
Getting same error, any more information on this?
