### ISSUE TITLE
Mysql failed to start (using pantheon recipe)

### ISSUE THREAD

**Issue by karagaulrapp** [lando/lando#270]
Bug Report
==========

OSX 10.12.6
Lando v3.0.0-beta.7

lando.yml:
```yml
name: SITE
recipe: pantheon
config:
  framework: drupal
  id: b0961792-028f-4967-8cfd-38496da8cd76
  site: SITE
  env: dev
```

All other config files are using defaults.
No pantheon.yml in use

Ran:
```bash
lando init SITE --recipe pantheon
lando switch FEATURE
lando start
```

"start" command reports no errors and exits normally, but database container is not running.

connecting to the site in a browser results in a PHP exception: 
```
PDOException: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name or service not known in variable_initialize() (line 1214 of /app/includes/bootstrap.inc).
```

trying to connect to the database container:
```bash
lando mysql
```
results in this error:
```bash
error:  Error: (HTTP code 500) server error - Container acef7efbd3d61f1c01a6a8203707d962c415a2252c515c5266efb1fc613ea603 is not running 
    at /snapshot/cli/node_modules/docker-modem/lib/modem.js:243:17
    at getCause (/snapshot/cli/node_modules/docker-modem/lib/modem.js:273:7)
    at Modem.buildPayload (/snapshot/cli/node_modules/docker-modem/lib/modem.js:242:5)
    at IncomingMessage.<anonymous> (/snapshot/cli/node_modules/docker-modem/lib/modem.js:218:14)
    at emitNone (events.js:110:20)
    at IncomingMessage.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1045:12)
    at _combinedTickCallback (internal/process/next_tick.js:102:11)
    at process._tickCallback (internal/process/next_tick.js:161:9)
From previous event:
    at /snapshot/cli/lib/container.js:283:20
From previous event:
    at Object.exports.run (/snapshot/cli/lib/container.js:282:4)
    at /snapshot/cli/lib/docker.js:168:24
    at runCallback (timers.js:800:20)
    at tryOnImmediate (timers.js:762:5)
    at processImmediate [as _immediateCallback] (timers.js:733:5)
From previous event:
    at Object.exports.run (/snapshot/cli/lib/docker.js:148:18)
    at /snapshot/cli/lib/engine.js:526:19
From previous event:
    at Object.exports.run (/snapshot/cli/lib/engine.js:525:4)
    at /snapshot/cli/plugins/lando-tooling/lib/tooling.js:106:31
    at runCallback (timers.js:800:20)
    at tryOnImmediate (timers.js:762:5)
    at processImmediate [as _immediateCallback] (timers.js:733:5)
From previous event:
    at /snapshot/cli/plugins/lando-tooling/lib/tooling.js:105:10
From previous event:
    at Object.run (/snapshot/cli/plugins/lando-tooling/lib/tooling.js:59:8)
    at /snapshot/cli/lib/tasks.js:137:19
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:169:7)
```

Lando logs report the following issues when trying to start the database container:
```
database_1   | Making sure correct user exists...
database_1   | 33
database_1   | Scanning /user/.ssh for keys...
database_1   | Scanning /user/.lando/keys for keys...
database_1   | Checking whether /user/.ssh/config is a suitable key...
database_1   | Checking whether /user/.ssh/id_rsa is a suitable key...
database_1   | Using the following keys: /user/.ssh/config /user/.ssh/id_rsa
database_1   | Running command docker-entrypoint.sh mysqld
database_1   | 170808 17:05:31 [Note] mysqld (mysqld 10.0.31-MariaDB-1~jessie) starting as process 65 ...
database_1   | 170808 17:05:31 [Note] InnoDB: Using mutexes to ref count buffer pool pages
database_1   | 170808 17:05:31 [Note] InnoDB: The InnoDB memory heap is disabled
database_1   | 170808 17:05:31 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
database_1   | 170808 17:05:31 [Note] InnoDB: GCC builtin __atomic_thread_fence() is used for memory barrier
database_1   | 170808 17:05:31 [Note] InnoDB: Compressed tables use zlib 1.2.8
database_1   | 170808 17:05:31 [Note] InnoDB: Using Linux native AIO
database_1   | 170808 17:05:32 [Note] InnoDB: Using CPU crc32 instructions
database_1   | 170808 17:05:32 [Note] InnoDB: Initializing buffer pool, size = 384.0M
database_1   | 170808 17:05:32 [Note] InnoDB: Completed initialization of buffer pool
database_1   | 170808 17:05:32 [Note] InnoDB: Highest supported file format is Barracuda.
database_1   | InnoDB: No valid checkpoint found.
database_1   | InnoDB: If you are attempting downgrade from MySQL 5.7.9 or later,
database_1   | InnoDB: please refer to http://dev.mysql.com/doc/refman/5.6/en/upgrading-downgrading.html
database_1   | InnoDB: If this error appears when you are creating an InnoDB database,
database_1   | InnoDB: the problem may be that during an earlier attempt you managed
database_1   | InnoDB: to create the InnoDB data files, but log file creation failed.
database_1   | InnoDB: If that is the case, please refer to
database_1   | InnoDB: http://dev.mysql.com/doc/refman/5.6/en/error-creating-innodb.html
database_1   | 170808 17:05:32 [ERROR] Plugin 'InnoDB' init function returned error.
database_1   | 170808 17:05:32 [ERROR] Plugin 'InnoDB' registration as a STORAGE ENGINE failed.
database_1   | 170808 17:05:33 [Note] Plugin 'FEEDBACK' is disabled.
database_1   | 170808 17:05:33 [ERROR] Can't open the mysql.plugin table. Please run mysql_upgrade to create it.
database_1   | 170808 17:05:33 [ERROR] Unknown/unsupported storage engine: innodb
database_1   | 170808 17:05:33 [ERROR] Aborting
database_1   | 
database_1   | 170808 17:05:33 [Note] mysqld: Shutdown complete
```

Finally, not sure if it's related, but lando seems to be having trouble finding PHP extensions:
```
Failed loading /usr/local/lib/php/extensions/no-debug-non-zts-20131226/opcache.so:  /usr/local/lib/php/extensions/no-debug-non-zts-20131226/opcache.so: undefined symbol: zend_opcode_handlers
Xdebug requires Zend Engine API version 220131226.
The Zend Engine API version 320151012 which is installed, is newer.
Contact Derick Rethans at http://xdebug.org/docs/faq#api for a later version of Xdebug.

PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/lib/php/extensions/no-debug-non-zts-20151012/bcmath.so' - /usr/local/lib/php/extensions/no-debug-non-zts-20151012/bcmath.so: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/lib/php/extensions/no-debug-non-zts-20151012/bz2.so' - /usr/local/lib/php/extensions/no-debug-non-zts-20151012/bz2.so: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/lib/php/extensions/no-debug-non-zts-20151012/calendar.so' - /usr/local/lib/php/extensions/no-debug-non-zts-20151012/calendar.so: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/lib/php/extensions/no-debug-non-zts-20151012/gd.so' - /usr/local/lib/php/extensions/no-debug-non-zts-20151012/gd.so: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/lib/php/extensions/no-debug-non-zts-20151012/imagick.so' - /usr/local/lib/php/extensions/no-debug-non-zts-20151012/imagick.so: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/lib/php/extensions/no-debug-non-zts-20151012/imap.so' - /usr/local/lib/php/extensions/no-debug-non-zts-20151012/imap.so: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/lib/php/extensions/no-debug-non-zts-20151012/ldap.so' - /usr/local/lib/php/extensions/no-debug-non-zts-20151012/ldap.so: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/lib/php/extensions/no-debug-non-zts-20151012/mcrypt.so' - /usr/local/lib/php/extensions/no-debug-non-zts-20151012/mcrypt.so: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/lib/php/extensions/no-debug-non-zts-20151012/mysql.so' - /usr/local/lib/php/extensions/no-debug-non-zts-20151012/mysql.so: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/lib/php/extensions/no-debug-non-zts-20151012/mysqli.so' - /usr/local/lib/php/extensions/no-debug-non-zts-20151012/mysqli.so: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/lib/php/extensions/no-debug-non-zts-20151012/oauth.so' - /usr/local/lib/php/extensions/no-debug-non-zts-20151012/oauth.so: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/lib/php/extensions/no-debug-non-zts-20151012/pdo_mysql.so' - /usr/local/lib/php/extensions/no-debug-non-zts-20151012/pdo_mysql.so: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/lib/php/extensions/no-debug-non-zts-20151012/pdo_pgsql.so' - /usr/local/lib/php/extensions/no-debug-non-zts-20151012/pdo_pgsql.so: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/lib/php/extensions/no-debug-non-zts-20151012/redis.so' - /usr/local/lib/php/extensions/no-debug-non-zts-20151012/redis.so: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/lib/php/extensions/no-debug-non-zts-20151012/soap.so' - /usr/local/lib/php/extensions/no-debug-non-zts-20151012/soap.so: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/lib/php/extensions/no-debug-non-zts-20151012/zip.so' - /usr/local/lib/php/extensions/no-debug-non-zts-20151012/zip.so: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Fatal error:  Uncaught Error: Call to undefined function cache_get() in /app/includes/module.inc:754
Stack trace:
#0 /app/includes/module.inc(954): module_implements('system_theme_in...')
#1 /app/modules/system/system.module(2511): module_invoke_all('system_theme_in...')
#2 /app/includes/theme.inc(798): _system_rebuild_theme_data()
#3 /app/includes/theme.maintenance.inc(57): list_themes()
#4 /app/includes/bootstrap.inc(2913): _drupal_maintenance_theme()
#5 /app/includes/errors.inc(179): drupal_maintenance_theme()
#6 /app/includes/bootstrap.inc(2634): _drupal_log_error(Array, true)
#7 [internal function]: _drupal_exception_handler(Object(Error))
#8 {main}
  thrown in /app/includes/module.inc on line 754

Fatal error: Uncaught Error: Call to undefined function cache_get() in /app/includes/module.inc:754
Stack trace:
#0 /app/includes/module.inc(954): module_implements('system_theme_in...')
#1 /app/modules/system/system.module(2511): module_invoke_all('system_theme_in...')
#2 /app/includes/theme.inc(798): _system_rebuild_theme_data()
#3 /app/includes/theme.maintenance.inc(57): list_themes()
#4 /app/includes/bootstrap.inc(2913): _drupal_maintenance_theme()
#5 /app/includes/errors.inc(179): drupal_maintenance_theme()
#6 /app/includes/bootstrap.inc(2634): _drupal_log_error(Array, true)
#7 [internal function]: _drupal_exception_handler(Object(Error))
#8 {main}
  thrown in /app/includes/module.inc on line 754
Drush command terminated abnormally due to an unrecoverable error.                                                                                                                                                                                   [error]
Error: Uncaught Error: Call to undefined function cache_get() in /app/includes/module.inc:754
Stack trace:
#0 /app/includes/module.inc(954): module_implements('system_theme_in...')
#1 /app/modules/system/system.module(2511): module_invoke_all('system_theme_in...')
#2 /app/includes/theme.inc(798): _system_rebuild_theme_data()
#3 /app/includes/theme.maintenance.inc(57): list_themes()
#4 /app/includes/bootstrap.inc(2913): _drupal_maintenance_theme()
#5 /app/includes/errors.inc(179): drupal_maintenance_theme()
#6 /app/includes/bootstrap.inc(2634): _drupal_log_error(Array, true)
#7 [internal function]: _drupal_exception_handler(Object(Error))
#8 {main}
  thrown in /app/includes/module.inc, line 754
error: Failed loading /usr/local/lib/php/extensions/no-debug-non-zts-20131226/opcache.so:  /usr/local/lib/php/extensions/no-debug-non-zts-20131226/opcache.so: undefined symbol: zend_opcode_handlers
Xdebug requires Zend Engine API version 220131226.
The Zend Engine API version 320151012 which is installed, is newer.
Contact Derick Rethans at http://xdebug.org/docs/faq#api for a later version of Xdebug.

PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/lib/php/extensions/no-debug-non-zts-20151012/bcmath.so' - /usr/local/lib/php/extensions/no-debug-non-zts-20151012/bcmath.so: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/lib/php/extensions/no-debug-non-zts-20151012/bz2.so' - /usr/local/lib/php/extensions/no-debug-non-zts-20151012/bz2.so: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/lib/php/extensions/no-debug-non-zts-20151012/calendar.so' - /usr/local/lib/php/extensions/no-debug-non-zts-20151012/calendar.so: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/lib/php/extensions/no-debug-non-zts-20151012/gd.so' - /usr/local/lib/php/extensions/no-debug-non-zts-20151012/gd.so: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/lib/php/extensions/no-debug-non-zts-20151012/imagick.so' - /usr/local/lib/php/extensions/no-debug-non-zts-20151012/imagick.so: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/lib/php/extensions/no-debug-non-zts-20151012/imap.so' - /usr/local/lib/php/extensions/no-debug-non-zts-20151012/imap.so: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/lib/php/extensions/no-debug-non-zts-20151012/ldap.so' - /usr/local/lib/php/extensions/no-debug-non-zts-20151012/ldap.so: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/lib/php/extensions/no-debug-non-zts-20151012/mcrypt.so' - /usr/local/lib/php/extensions/no-debug-non-zts-20151012/mcrypt.so: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/lib/php/extensions/no-debug-non-zts-20151012/mysql.so' - /usr/local/lib/php/extensions/no-debug-non-zts-20151012/mysql.so: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/lib/php/extensions/no-debug-non-zts-20151012/mysqli.so' - /usr/local/lib/php/extensions/no-debug-non-zts-20151012/mysqli.so: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/lib/php/extensions/no-debug-non-zts-20151012/oauth.so' - /usr/local/lib/php/extensions/no-debug-non-zts-20151012/oauth.so: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/lib/php/extensions/no-debug-non-zts-20151012/pdo_mysql.so' - /usr/local/lib/php/extensions/no-debug-non-zts-20151012/pdo_mysql.so: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/lib/php/extensions/no-debug-non-zts-20151012/pdo_pgsql.so' - /usr/local/lib/php/extensions/no-debug-non-zts-20151012/pdo_pgsql.so: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/lib/php/extensions/no-debug-non-zts-20151012/redis.so' - /usr/local/lib/php/extensions/no-debug-non-zts-20151012/redis.so: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/lib/php/extensions/no-debug-non-zts-20151012/soap.so' - /usr/local/lib/php/extensions/no-debug-non-zts-20151012/soap.so: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/lib/php/extensions/no-debug-non-zts-20151012/zip.so' - /usr/local/lib/php/extensions/no-debug-non-zts-20151012/zip.so: cannot open shared object file: No such file or directory in Unknown on line 0
```

**Comment by nalipaz** [comment]
I am getting this too when just spinning up a service of type mysql:5.6. It seems like there is something wrong with mysql:5.6 image as I don't get this image if I take off the 5.6

**Comment by abstractpenguin** [comment]
I am encountering this as well.

**Comment by pirog** [comment]
I'm guessing this is a result of 
https://docs.devwithlando.io/issues/switching-dbs.html

id go through the above and see if you the corrective actions there help
