### ISSUE TITLE
Starting or rebuilding with PHP 8.0 fails when installing Composer

### ISSUE THREAD

**Issue by leoloso** [lando/lando#2795]
**Tell us about your setup**

What is your lando version and operating system? **(note that the older your version the less likely we are to reply)**

`v3.0.23` on MacOS Catalina `v10.15.7`

**Tell us about your `.lando.yml`**

```yml
name: graphql-api-import-test-5
recipe: wordpress
config:
  webroot: wordpress
  php: '8.0'
  ssl: true
  database: mariadb
```

**Tell us about the command you were running**

```bash
$ lando start
# or also
lando rebuild -y
```

**Tell us about the error you got**

When building Lando using the WordPress recipe, it fails when installing Composer:

```
$ lando start
Let's get this party started! Starting app graphql-api-import-test-5...
landoproxyhyperion5000gandalfedition_proxy_1 is up-to-date
Creating network "graphqlapiimporttest5_default" with the default driver
Creating volume "graphqlapiimporttest5_data_appserver" with default driver
Creating volume "graphqlapiimporttest5_home_appserver" with default driver
Creating volume "graphqlapiimporttest5_data_database" with default driver
Creating volume "graphqlapiimporttest5_home_database" with default driver
Creating graphqlapiimporttest5_appserver_1 ... done
501
501
All settings correct for using Composer
Downloading...

Composer (version 2.0.7) successfully installed to: /usr/local/bin/composer
Use it: php /usr/local/bin/composer

Changed current directory to /var/www/.composer

                                                                                        
  [RuntimeException]                                                                    
  Could not read ./composer.json                                                        
                                                                                        
  file_get_contents(./composer.json): Failed to open stream: No such file or directory  
                                                                                        

remove [--dev] [--dry-run] [--no-progress] [--no-update] [--no-install] [--no-scripts] [--update-no-dev] [-w|--update-with-dependencies] [-W|--update-with-all-dependencies] [--with-all-dependencies] [--no-update-with-dependencies] [--unused] [--ignore-platform-req IGNORE-PLATFORM-REQ] [--ignore-platform-reqs] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--apcu-autoloader-prefix APCU-AUTOLOADER-PREFIX] [--] <packages> (<packages>)...

ERROR ==>  message=, stack=Error
    at /snapshot/lando/build/cli/lib/shell.js
From previous event:
    at Shell.sh (/snapshot/lando/build/cli/lib/shell.js)
    at Object.dc (/snapshot/lando/build/cli/lib/bootstrap.js)
    at compose (/snapshot/lando/build/cli/lib/bootstrap.js)
From previous event:
    at /snapshot/lando/build/cli/lib/router.js
    at processImmediate (internal/timers.js:439:21)
From previous event:
    at Object.run (/snapshot/lando/build/cli/lib/router.js)
    at run (/snapshot/lando/build/cli/lib/engine.js)
    at /snapshot/lando/build/cli/lib/router.js
From previous event:
    at Object.eventWrapper (/snapshot/lando/build/cli/lib/router.js)
    at Engine.engineCmd (/snapshot/lando/build/cli/lib/engine.js)
    at Engine.run (/snapshot/lando/build/cli/lib/engine.js)
    at Object.runBuild (/snapshot/lando/build/cli/plugins/lando-services/lib/utils.js)
    at AsyncEvents.<anonymous> (/snapshot/lando/build/cli/plugins/lando-services/app.js)
    at AsyncEvents.handle (/snapshot/lando/build/cli/lib/events.js)
    at /snapshot/lando/build/cli/lib/events.js
From previous event:
    at AsyncEvents.emit (/snapshot/lando/build/cli/lib/events.js)
    at /snapshot/lando/build/cli/lib/app.js
From previous event:
    at App.start (/snapshot/lando/build/cli/lib/app.js)
    at Object.run (/snapshot/lando/build/cli/plugins/lando-core/tasks/start.js)
From previous event:
    at /snapshot/lando/build/cli/lib/cli.js
From previous event:
    at Object.handler (/snapshot/lando/build/cli/lib/cli.js)
    at Object.runCommand (/snapshot/lando/build/cli/node_modules/yargs/lib/command.js:238:44)
    at Object.parseArgs [as _parseArgs] (/snapshot/lando/build/cli/node_modules/yargs/yargs.js:1063:30)
    at Function.get [as argv] (/snapshot/lando/build/cli/node_modules/yargs/yargs.js:1004:21)
    at Cli.init (/snapshot/lando/build/cli/lib/cli.js)
    at Cli.run (/snapshot/lando/build/cli/lib/cli.js)
From previous event:
    at /snapshot/lando/build/cli/bin/lando.js
From previous event:
    at Object.<anonymous> (/snapshot/lando/build/cli/bin/lando.js)
    at Module._compile (pkg/prelude/bootstrap.js:1324:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:993:10)
    at Module.load (internal/modules/cjs/loader.js:813:32)
    at Function.Module._load (internal/modules/cjs/loader.js:725:14)
    at Function.Module.runMain (pkg/prelude/bootstrap.js:1379:12)
    at internal/main/run_main_module.js:17:11, __stackCleaned__=true
Creating graphqlapiimporttest5_database_1 ... done
Waiting until database service is ready...
Scanning to determine which services are ready... Please standby...
501
501
/bin/sh: 1: wp: not found
ERROR ==> /bin/sh: 1: wp: not found 

  _      __              _           __
 | | /| / /__ ________  (_)__  ___ _/ /
 | |/ |/ / _ `/ __/ _ \/ / _ \/ _ `/_/ 
 |__/|__/\_,_/_/ /_//_/_/_//_/\_, (_)  
                             /___/     

Your app started up but we detected some things you may wish to investigate.
These only may be a problem.


 ■ One of your build steps failed
   This **MAY** prevent your app from working.
   Check for errors above, fix them in your Landofile, and try again by running:
   lando rebuild


 ■ One of your build steps failed
   This **MAY** prevent your app from working.
   Check for errors above, fix them in your Landofile, and try again by running:
   lando rebuild


Here are some vitals:

 NAME            graphql-api-import-test-5                    
 LOCATION        /Users/mac/Temporary/lando-test-5            
 SERVICES        appserver, database                          
 APPSERVER URLS  https://localhost:32898                      
                 http://localhost:32899                       
                 http://graphql-api-import-test-5.lndo.site/  
                 https://graphql-api-import-test-5.lndo.site/ 
```

I logged into the server:

```bash
lando ssh
```

And checked for the files in `/var/www/.composer`. Certainly, there's no file `composer.json` (nor folders `cache` and `vendor`, nor `composer.lock`):

```bash
$ ls -lh /var/www/.composer
total 8.0K
-rw-r--r-- 1 www-data dialout 799 Jan  7 09:54 keys.dev.pub
-rw-r--r-- 1 www-data dialout 799 Jan  7 09:54 keys.tags.pub
```

From then on, I can't run Composer.

**Tell us generally about your bug**

1. Use WordPress recipe
2. Use `php: '8.0'`
3. Start (or rebuild) Lando

When using PHP 7.4, it works well.

Here a screenshot of the problem:

<img width="1284" alt="Screenshot 2021-01-07 at 5 32 35 PM" src="https://user-images.githubusercontent.com/1981996/103877688-60c85380-5110-11eb-8af8-5f9b541b9a0d.png">

**Comment by benperiton** [comment]
The install-composer.sh tries to remove hirak/prestissimo if version is  > 2
https://github.com/lando/lando/blob/62a7db6c03d4c44ddacc7740d56b9083d5516cb8/plugins/lando-services/scripts/install-composer.sh#L32

but it is already commented out in https://github.com/lando/lando/blob/bc41ef1d76d0590aec456e165412b593c98aecce/plugins/lando-services/services/php/8.0-apache/Dockerfile#L77 so there is nothing to remove

I ended up creating my own Dockerfile that is basically a copy of https://github.com/lando/lando/blob/bc41ef1d76d0590aec456e165412b593c98aecce/plugins/lando-services/services/php/8.0-apache/Dockerfile but that has the line uncommented out. (I already created a copy because I wanted 8.0.1 to fix php-cs issues)

**Comment by leoloso** [comment]
Could you integrate your change into the repo? Or should we ping somebody who can? Right now, PHP 8.0 can't be used, so this is an important bug to fix

**Comment by benperiton** [comment]
I guess it depends on how they want to fix it.

The Dockerfiles for PHP seem to install composer anyway (https://github.com/lando/lando/blob/bc41ef1d76d0590aec456e165412b593c98aecce/plugins/lando-services/services/php/8.0-apache/Dockerfile#L74) so I'm not sure what the need for the install-composer.sh is? I guess so that different versions can be installed.

Perhaps removing the composer install and `composer global require hirak/prestissimo` from the PHP Dockerfiles and then reversing the code in the install-composer.sh so that rather than removing it if > 2, we only install it if it is < 2 ?

**Comment by pirog** [comment]
I can replicate this and so far it seems like #2835 does the trick.
