### ISSUE TITLE
lando start - "Unable to write keys.dev.pub to: /var/www/.composer"

### ISSUE THREAD

**Issue by apredmore-tag** [lando/lando#2806]
**Tell us about your setup**

Lando: v3.0.23
macOS Big Sur Version 11.1

**Tell us about your `.lando.yml`**

```yml
name: client-lectures
recipe: wordpress
config:
  webroot: .
  composer_version: 1
  via: nginx
```

**Tell us about the command you were running**

`lando start`

**Tell us about the error you got**

```bash
lando             16:38:01 DEBUG ==> checking to see if https://127.0.0.1:4443 is ready. 
lando             16:38:01 DEBUG ==> http://127.0.0.1:8000 not currently accessible 
lando             16:38:01 DEBUG ==> http://127.0.0.1:8080 not currently accessible 
lando             16:38:01 DEBUG ==> http://127.0.0.1:8888 not currently accessible 
lando             16:38:01 DEBUG ==> http://127.0.0.1:8008 not currently accessible 
lando             16:38:01 DEBUG ==> https://127.0.0.1:443 not currently accessible 
lando             16:38:01 DEBUG ==> https://127.0.0.1:444 not currently accessible 
lando             16:38:01 DEBUG ==> https://127.0.0.1:4433 not currently accessible 
lando             16:38:01 DEBUG ==> https://127.0.0.1:4444 not currently accessible 
lando             16:38:01 DEBUG ==> https://127.0.0.1:4443 not currently accessible 
lando             16:38:01 VERBOSE ==> scan completed. 
lando             16:38:01 DEBUG ==> scan results. url=http://127.0.0.1:80, status=true, color=green, url=http://127.0.0.1:8000, status=false, color=red, url=http://127.0.0.1:8080, status=false, color=red, url=http://127.0.0.1:8888, status=false, color=red, url=http://127.0.0.1:8008, status=false, color=red
lando             16:38:01 VERBOSE ==> scan completed. 
lando             16:38:01 DEBUG ==> scan results. url=https://127.0.0.1:443, status=false, color=red, url=https://127.0.0.1:444, status=false, color=red, url=https://127.0.0.1:4433, status=false, color=red, url=https://127.0.0.1:4444, status=false, color=red, url=https://127.0.0.1:4443, status=false, color=red
lando             16:38:01 DEBUG ==> process pid6 running /Applications/Docker.app/Contents/Resources/bin/docker-compose/docker-compose up cstdio=inherit, silent=false, mode=spawn, detached=false
Starting landoproxyhyperion5000gandalfedition_proxy_1 ... done
lando             16:38:03 DEBUG ==> process pid6 finished with exit code 0 
client-lectures 16:38:03 DEBUG ==> app has proxy compose files 0=/Users/claytonapredmore/.lando/compose/clientlectures/proxy-0.yml
client-lectures 16:38:03 INFO ==> running build steps... 
client-lectures 16:38:03 DEBUG ==> process pid7 running /Applications/Docker.app/Contents/Resources/bin/docker-compose/docker-compose up cstdio=inherit, silent=false, mode=spawn, detached=false
Starting clientlectures_appserver_1 ... done
client-lectures 16:38:04 DEBUG ==> process pid7 finished with exit code 0 
client-lectures 16:38:04 DEBUG ==> process pid8 running /Applications/Docker.app/Contents/Resources/bin/docker-compose/docker-compose exec appserver /helpers/user-perms.sh cstdio=inherit, silent=false, mode=spawn, detached=false
501
501
client-lectures 16:38:06 DEBUG ==> process pid8 finished with exit code 0 
client-lectures 16:38:06 DEBUG ==> process pid9 running /Applications/Docker.app/Contents/Resources/bin/docker-compose/docker-compose exec appserver /bin/sh /helpers/install-composer.sh 1 cstdio=[inherit, pipe, pipe], silent=false, mode=spawn, detached=false
All settings correct for using Composer
Unable to write keys.dev.pub to: /var/www/.composer
client-lectures 16:38:07 DEBUG ==> process pid9 finished with exit code 1 
client-lectures 16:38:07 ERROR ==> Unable to write keys.dev.pub to: /var/www/.composer 
client-lectures 16:38:07 DEBUG ==>  message=Unable to write keys.dev.pub to: /var/www/.composer, stack=Error: Unable to write keys.dev.pub to: /var/www/.composer
    at /snapshot/lando/build/cli/lib/shell.js
From previous event:
    at Shell.sh (/snapshot/lando/build/cli/lib/shell.js)
    at Object.dc (/snapshot/lando/build/cli/lib/bootstrap.js)
    at compose (/snapshot/lando/build/cli/lib/bootstrap.js)
From previous event:
    at /snapshot/lando/build/cli/lib/router.js
    at processImmediate (internal/timers.js:439:21)
From previous event:
    at Object.run (/snapshot/lando/build/cli/lib/router.js)
    at run (/snapshot/lando/build/cli/lib/engine.js)
    at /snapshot/lando/build/cli/lib/router.js
From previous event:
    at Object.eventWrapper (/snapshot/lando/build/cli/lib/router.js)
    at Engine.engineCmd (/snapshot/lando/build/cli/lib/engine.js)
    at Engine.run (/snapshot/lando/build/cli/lib/engine.js)
    at Object.runBuild (/snapshot/lando/build/cli/plugins/lando-services/lib/utils.js)
    at AsyncEvents.<anonymous> (/snapshot/lando/build/cli/plugins/lando-services/app.js)
    at AsyncEvents.handle (/snapshot/lando/build/cli/lib/events.js)
    at /snapshot/lando/build/cli/lib/events.js
From previous event:
    at AsyncEvents.emit (/snapshot/lando/build/cli/lib/events.js)
    at /snapshot/lando/build/cli/lib/app.js
From previous event:
    at App.start (/snapshot/lando/build/cli/lib/app.js)
    at Object.run (/snapshot/lando/build/cli/plugins/lando-core/tasks/start.js)
From previous event:
    at /snapshot/lando/build/cli/lib/cli.js
From previous event:
    at Object.handler (/snapshot/lando/build/cli/lib/cli.js)
    at Object.runCommand (/snapshot/lando/build/cli/node_modules/yargs/lib/command.js:238:44)
    at Object.parseArgs [as _parseArgs] (/snapshot/lando/build/cli/node_modules/yargs/yargs.js:1063:30)
    at Function.get [as argv] (/snapshot/lando/build/cli/node_modules/yargs/yargs.js:1004:21)
    at Cli.init (/snapshot/lando/build/cli/lib/cli.js)
    at Cli.run (/snapshot/lando/build/cli/lib/cli.js)
    at Object.<anonymous> (/snapshot/lando/build/cli/bin/lando.js)
    at Module._compile (pkg/prelude/bootstrap.js:1324:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:993:10)
    at Module.load (internal/modules/cjs/loader.js:813:32)
    at Function.Module._load (internal/modules/cjs/loader.js:725:14)
    at Function.Module.runMain (pkg/prelude/bootstrap.js:1379:12)
    at internal/main/run_main_module.js:17:11, __stackCleaned__=true
client-lectures 16:38:07 VERBOSE ==> reporting error action to report=true, url=https://metrics.lando.dev, report=true, url=https://metrics.lando.dev
client-lectures 16:38:07 DEBUG ==> reported data command=lando start, context=local, devMode=false, instance=b40d5fce8b148eca3e015557bdfaa0d752804182, nodeVersion=v12.13.1, mode=cli, type=Darwin, platform=darwin, release=20.2.0, arch=x64, product=lando, version=3.0.23, message=Unable to write keys.dev.pub to: /var/www/.composer, action=error, created=2021-01-12T21:38:07.435Z
```

**Tell us generally about your bug**

Just trying to init lando on some WordPress code. I did this last week and it seemed to work fine.

I am also having the issue where it says "Waiting until database service is ready..." for several minutes before finally giving up.

**Comment by RoloDMonkey** [comment]
Later in the day, I discovered that none of my Lando environments would start. Even ones that had been working for months.

So, I uninstalled Lando, uninstalled Docker and removed the `.lando` folder from my home directory. Then, I re-installed Lando. After that, I was able to run `lando start` on my environments without a problem.

I still would love to know what happened though.

Also, why does Lando output:
```501
501```
Without explaining what that means?

**Comment by calogeromigliore** [comment]
I have the same problem, does anyone know how to fix it without reinstalling everything?

**Comment by apredmore-tag** [comment]
@calogeromigliore - I closed this issue. So, you won't get a response here. If you want, you can open a new issue and refer to this one.

**Comment by mourogers** [comment]
I had this issue today and it was caused by Docker running out of space.

**Comment by digisavvy** [comment]
Docker space issue for me, too. `docker system prune -a` seemed to do the trick for me.

**Comment by kclarkson** [comment]
@digisavvy thank you! I tried increasing my space with Docker but nothing worked.  I also had to do a `docker system prune -a`. Note this destroys everything in docker so be sure you have backups.

**Comment by peterfeddo** [comment]
@digisavvy suggestion worked for me in a situation where one of my Lando environments has an excessively large database.
