### ISSUE TITLE
Platformsh - error on lando start

### ISSUE THREAD

**Issue by markushausammann** [lando/lando#2817]
I'm setting up lando configurations for a multi application platform.sh instance. This project has four applications, three of which I was able to spin up with lando successfully. What I realised was that the routes were not picked up so I created them with my own `proxy` settings. At that point I didn't know yet that lando should pick them up automatically from the `routes.yaml`.

When trying to start the fourth application, which is the only one with a relationship (mariadb) I get the following error when trying to run `lando start`:

```
Unhandled rejection TypeError: Cannot read property 'split' of undefined
    at /snapshot/lando/build/cli/integrations/lando-platformsh/lib/config.js
    at arrayMap (/snapshot/lando/build/cli/node_modules/lodash/lodash.js:639:23)
    at Function.map (/snapshot/lando/build/cli/node_modules/lodash/lodash.js:9580:14)
    at interceptor (/snapshot/lando/build/cli/node_modules/lodash/lodash.js:17046:35)
    at Function.thru (/snapshot/lando/build/cli/node_modules/lodash/lodash.js:8817:14)
    at /snapshot/lando/build/cli/node_modules/lodash/lodash.js:4388:28
    at arrayReduce (/snapshot/lando/build/cli/node_modules/lodash/lodash.js:683:21)
    at baseWrapperValue (/snapshot/lando/build/cli/node_modules/lodash/lodash.js:4387:14)
    at LodashWrapper.wrapperValue (/snapshot/lando/build/cli/node_modules/lodash/lodash.js:9072:14)
    at Object.getSyncableRelationships (/snapshot/lando/build/cli/integrations/lando-platformsh/lib/config.js)
    at AsyncEvents.<anonymous> (/snapshot/lando/build/cli/integrations/lando-platformsh/app.js)
    at AsyncEvents.handle (/snapshot/lando/build/cli/lib/events.js)
    at /snapshot/lando/build/cli/lib/events.js
From previous event:
    at AsyncEvents.emit (/snapshot/lando/build/cli/lib/events.js)
    at /snapshot/lando/build/cli/lib/app.js
From previous event:
    at App.init (/snapshot/lando/build/cli/lib/app.js)
    at /snapshot/lando/build/cli/bin/lando.js
From previous event:
    at Object.<anonymous> (/snapshot/lando/build/cli/bin/lando.js)
    at Module._compile (pkg/prelude/bootstrap.js:1324:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:993:10)
    at Module.load (internal/modules/cjs/loader.js:813:32)
    at Function.Module._load (internal/modules/cjs/loader.js:725:14)
    at Function.Module.runMain (pkg/prelude/bootstrap.js:1379:12)
    at internal/main/run_main_module.js:17:11
```
My guess is that lando does not find the `routes.yaml` and the `services.yaml`.

Why is that, resp. how can I test if that's the case? Any tips on how to trouble shoot this?

**Comment by reevo** [comment]
I had the same error with a multi-app instance. I'm not sure how similar our setups are or whether you managed to figure things out, but I've just my instance working, so:

1. My routes.yaml only had FQDN routes. This didn't resolve the error, but it did mean that routes were picked up when everything was working.

2. The instance had two apps, each had a relationship to the other. eg: 

```
# app1/.platform.app.yaml
relationships:
  database: 'mysqldb:mysql'
  solr: 'solr:main'
  app2: 'app2:http'
  
# app2/.platform.app.yaml
relationships:
  database: 'mongodb:mongodb'
  app1: 'app1:http'
```
Though a load of trial and error, I found that removing the inter-app relationships made the error go away, and everything booted up. After further trial and error, I discovered that it only threw an error if the _first_ app had a relationship to the second - having a relationship from the second app to the first always worked. Out of curiosity, I created a new basic PHP app to sit at the top of the list, with my real apps in positions 2 and 3, and now the inter-app relationships work as expected. 

All this may be completely unrelated, of course! Will revisit this when/if I get to a point where I'm able to start debugging Lando - am pretty new to it all right now.

**Comment by dman-coders** [comment]
I started getting "Unhandled rejection TypeError: Cannot read property 'split' of undefined" a lot recently. When trying to initialize a new project. ` lando init --source cwd --recipe platformsh`
After much fruitless digging, and re-installing from scratch (then deleting ~/.lando and re-installing again) I found I was also getting it in an older project that used to work. (!?)

... Turns out I had a `.lando.yaml` file higher up in my directory tree than the local folder I thought I was initializing. That was an error on my side (I'd run an init in the wrong dir a while ago, and cancelled, but the trash was left behind). Removing that made things work again.

But it would help if the error was more helpful: IE "Error when parsing /var/www/.lando.yaml" or, if it's going to recurse up the directory tree to find a yaml *when initializing a new one* we should get a warning about problems with nested projects.

**Comment by dwkitchen** [comment]
I also had the same issue with the order of app folders due to alphabetical ordering.
