### ISSUE TITLE
PHP full semantic version numbers break build.

### ISSUE THREAD

**Issue by ndouglas** [lando/lando#2884]
**Tell us about your setup**
Lando v3.0.26 on Mac.

**Tell us about your `.lando.yml`**
```yaml
name: va-gov-cms
recipe: drupal8
config:
  webroot: docroot
  php: "7.2.32"
  # Match with terraform-aws-vsp-cms/rds.tf (another repo)
  # Match with .tugboat/config.yml (this repo)
  database: mariadb:10.5
  composer_version: '1.10.1'
```

**Tell us about the command you were running**
`lando rebuild -y`

**Tell us about the error you got**
```
va-gov-cms 15:03:05 VERBOSE ==> initiatilizing app at /Users/nathan.douglas/Projects/va.gov-cms... 
lando      15:03:05 DEBUG ==> plugin lando-core loaded from /snapshot/lando/build/cli/plugins/lando-core/app.js 
lando      15:03:05 DEBUG ==> plugin lando-events loaded from /snapshot/lando/build/cli/plugins/lando-events/app.js 
lando      15:03:05 DEBUG ==> plugin lando-networking loaded from /snapshot/lando/build/cli/plugins/lando-networking/app.js 
va-gov-cms 15:03:05 VERBOSE ==> proxy settings detected. 
lando      15:03:05 DEBUG ==> plugin lando-proxy loaded from /snapshot/lando/build/cli/plugins/lando-proxy/app.js 
lando      15:03:05 DEBUG ==> plugin lando-recipes loaded from /snapshot/lando/build/cli/plugins/lando-recipes/app.js 
lando      15:03:05 DEBUG ==> plugin lando-services loaded from /snapshot/lando/build/cli/plugins/lando-services/app.js 
lando      15:03:05 DEBUG ==> plugin lando-sharing loaded from /snapshot/lando/build/cli/plugins/lando-sharing/app.js 
lando      15:03:05 DEBUG ==> plugin lando-tooling loaded from /snapshot/lando/build/cli/plugins/lando-tooling/app.js 
lando      15:03:05 DEBUG ==> plugin lando-lagoon loaded from /snapshot/lando/build/cli/integrations/lando-lagoon/app.js 
lando      15:03:05 DEBUG ==> plugin lando-pantheon loaded from /snapshot/lando/build/cli/integrations/lando-pantheon/app.js 
lando      15:03:05 DEBUG ==> plugin lando-platformsh loaded from /snapshot/lando/build/cli/integrations/lando-platformsh/app.js 
va-gov-cms 15:03:05 DEBUG ==> emitting event pre-init 
va-gov-cms 15:03:05 VERBOSE ==> building drupal8 recipe named 
lando      15:03:05 VERBOSE ==> proxy is ON. 
lando      15:03:05 VERBOSE ==> Setting the default proxy certificate /certs/cert.crt 
va-gov-cms 15:03:05 VERBOSE ==> building php service appserver 
lando      15:03:05 ERROR ==> TypeError: Invalid Version: 7.2.32.0
    at new SemVer (/snapshot/lando/build/cli/node_modules/semver/classes/semver.js:41:13)
    at compare (/snapshot/lando/build/cli/node_modules/semver/functions/compare.js:3:3)
    at Object.gt (/snapshot/lando/build/cli/node_modules/semver/functions/gt.js:2:29)
    at new LandoPhp (/snapshot/lando/build/cli/plugins/lando-services/services/php/builder.js)
    at /snapshot/lando/build/cli/plugins/lando-services/app.js
    at arrayEach (/snapshot/lando/build/cli/node_modules/lodash/lodash.js:516:11)
    at Function.forEach (/snapshot/lando/build/cli/node_modules/lodash/lodash.js:9368:14)
    at AsyncEvents.<anonymous> (/snapshot/lando/build/cli/plugins/lando-services/app.js)
    at AsyncEvents.handle (/snapshot/lando/build/cli/lib/events.js)
    at /snapshot/lando/build/cli/lib/events.js
From previous event:
    at AsyncEvents.emit (/snapshot/lando/build/cli/lib/events.js)
    at /snapshot/lando/build/cli/lib/app.js
From previous event:
    at App.init (/snapshot/lando/build/cli/lib/app.js)
    at /snapshot/lando/build/cli/lib/formatters.js
From previous event:
    at Object.handleInteractive (/snapshot/lando/build/cli/lib/formatters.js)
From previous event:
    at /snapshot/lando/build/cli/lib/cli.js
From previous event:
    at Object.handler (/snapshot/lando/build/cli/lib/cli.js)
    at Object.runCommand (/snapshot/lando/build/cli/node_modules/yargs/lib/command.js:238:44)
    at Object.parseArgs [as _parseArgs] (/snapshot/lando/build/cli/node_modules/yargs/yargs.js:1063:30)
    at Function.get [as argv] (/snapshot/lando/build/cli/node_modules/yargs/yargs.js:1004:21)
    at Cli.init (/snapshot/lando/build/cli/lib/cli.js)
    at Cli.run (/snapshot/lando/build/cli/lib/cli.js)
    at Object.<anonymous> (/snapshot/lando/build/cli/bin/lando.js)
    at Module._compile (pkg/prelude/bootstrap.js:1324:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:993:10)
    at Module.load (internal/modules/cjs/loader.js:813:32)
    at Function.Module._load (internal/modules/cjs/loader.js:725:14)
    at Function.Module.runMain (pkg/prelude/bootstrap.js:1379:12)
    at internal/main/run_main_module.js:17:11 
```

**Tell us generally about your bug**
Lando seems to fail build/rebuild when PHP provides a full semantic version number, as we are, to lock version numbers across local, testing, and production environments.  It seems as though it is appending a '.0' to the end of the PHP version number, even when this is not appropriate.

*Example:*

```bash
1. Started up GUI
2. Clicked on my Pantheon account in the sidebar
3. Selected a site and an environment
4. Kept the default create options and pressed submit
```

**Tell us more**
Presumably the fault of this code here, which forecast the possibility:
```javascript
      // Shift on the docker entrypoint if this is a more recent version
      // @TODO: can we assume we will always have major.minor for php release?
      if (options.version !== 'custom' && semver.gt(`${options.version}.0`, '5.5.0')) {
        options.command.unshift('docker-php-entrypoint');
      }
```

I'll open a PR in a bit.

**Comment by ndouglas** [comment]
Closed by #2885.
