### ISSUE TITLE
issue connecting to postgres

### ISSUE THREAD

**Issue by dolly-k** [lando/lando#2892]
I am trying to set up drupal 8 using lando which uses Postgres database.
However, it's not able to connect.

**Here is my code**
name: my-lando-app
recipe: drupal8
config:
  webroot: web
  # database: postgres
  # port: 5432
services:
  database:
    type: postgres
    # portforward: true
    creds:
      database: postgres
      user: postgres
      password: 
      host: localhost
    # for mysql
      port: 5432

Also I tried to update my settings.php, but still it doesn't works
$databases['default']['default'] = array (
  'database' => 'postgres',
  'username' => 'postgres',
  'password' => '',
  'prefix' => '',
  'host' => 'localhost',
  'port' => '5432',
  'namespace' => 'Drupal\\Core\\Database\\Driver\\pgsql',
  'driver' => 'pgsql',
);
$settings['config_sync_directory'] = 'sites/default/sync';
$settings['file_private_path'] = $app_root . '/../private';

**ERROR**
appserver_1  | [Fri Mar 05 04:43:50.642693 2021] [php7:notice] [pid 215] [client 172.20.0.2:40324] PDOException: SQLSTATE[08006] [7] could not connect to server: Connection refused\n\tIs the server running on host "localhost" (127.0.0.1) and accepting\n\tTCP/IP connections on port 55796?\ncould not connect to server: Cannot assign requested address\n\tIs the server running on host "localhost" (::1) and accepting\n\tTCP/IP connections on port 55796? in /app/web/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php on line 79 #0 /app/web/core/lib/Drupal/Core/Database/Driver/pgsql/Connection.php(142): PDO->__construct('pgsql:host=loca...', 'postgres', NULL, Array)\n#1 /app/web/core/lib/Drupal/Core/Database/Database.php(374): Drupal\\Core\\Database\\Driver\\pgsql\\Connection::open(Array)\n#2 /app/web/core/lib/Drupal/Core/Database/Database.php(169): Drupal\\Core\\Database\\Database::openConnection('default', 'default')\n#3 [internal function]: Drupal\\Core\\Database\\Database::getConnection('default')\n#4 /app/web/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(79): call_user_func_array('Drupal\\\\Core\\\\Dat...', Array)\n#5 /app/web/core/lib/Drupal/Component/DependencyInjection/Container.php(173): Drupal\\Component\\DependencyInjection\\PhpArrayContainer->createService(Array, 'database')\n#6 /app/web/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(212): Drupal\\Component\\DependencyInjection\\Container->get('database', 1)\n#7 /app/web/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(62): Drupal\\Component\\DependencyInjection\\PhpArrayContainer->resolveServicesAndParameters(Array)\n#8 /app/web/core/lib/Drupal/Component/DependencyInjection/Container.php(173): Drupal\\Component\\DependencyInjection\\PhpArrayContainer->createService(Array, 'cache.container')\n#9 /app/web/core/lib/Drupal/Core/DrupalKernel.php(544): Drupal\\Component\\DependencyInjection\\Container->get('cache.container')\n#10 /app/web/core/lib/Drupal/Core/DrupalKernel.php(910): Drupal\\Core\\DrupalKernel->getCachedContainerDefinition()\n#11 /app/web/core/lib/Drupal/Core/DrupalKernel.php(477): Drupal\\Core\\DrupalKernel->initializeContainer()\n#12 /app/web/core/lib/Drupal/Core/DrupalKernel.php(707): Drupal\\Core\\DrupalKernel->boot()\n#13 /app/web/index.php(19): Drupal\\Core\\DrupalKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request))\n#14 {main}

Could someone please help.
Also I am using SQLPRO for postgres

**Comment by dolly-k** [comment]
could someone help me please. It's urgent
