### ISSUE TITLE
PHP Composer killed without reason (memory_limit = -1) 

### ISSUE THREAD

**Issue by zuernBernhard** [lando/lando#2924]
**Tell us about your setup**

Mac OS Catalina

```
$ lando version
v3.0.26
```

```
$ lando composer -V
You are running Composer with SSL/TLS protection disabled.
Composer version 1.10.1 2020-03-13 20:34:27
```

```
$ lando php -v
PHP 7.1.33 (cli) (built: Nov 22 2019 18:52:53) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.1.33, Copyright (c) 1999-2018, by Zend Technologies
    with Xdebug v2.9.4, Copyright (c) 2002-2020, by Derick Rethans
```

**Tell us about your `.lando.yml`**

```
name: dimplex
recipe: drupal8
proxy:
  mailhog:
    - mail.dimplex.lndo.site
services:
  appserver:
    type: php:7.1
    xdebug: true
    build_as_root:
      - cd /tmp && wget -nv https://www.pdflib.com/binaries/PDFlib/912/PDFlib-9.1.2p1-Linux-x86_64-php.tar.gz
      - cd /tmp && tar -zxf PDFlib-9.1.2p1-Linux-x86_64-php.tar.gz
      - && cp /tmp/PDFlib-9.1.2p1-Linux-x86_64-php/bind/php/php-710-nts/php_pdflib.so /app/php_pdflib.so
      - curl -sL https://deb.nodesource.com/setup_12.x | bash -
      - apt-get install -y nodejs
      - npm install
    globals:
      grunt-cli: "latest"
    overrides:
      environment:
        # Support debugging Drush with XDEBUG
        PHP_IDE_CONFIG: "serverName=dimplex.lndo.site"
    config:
      php: lando/php.ini
  mailhog:
    type: mailhog
    hogfrom:
      - appserver
  mediando:
    type: mysql
    portforward: 13308
    creds:
      user: mediando
      password: mediando
      database: mediando
  sonstiges:
    type: mysql
    creds:
      user: sonstiges
      password: sonstiges
      database: sonstiges
  dimplex_betriebskostenrechner:
    type: mysql
    creds:
      user: dimplex_betriebskostenrechner
      password: dimplex_betriebskostenrechner
      database: dimplex_betriebskostenrechner
  dimplex_apl:
    type: mysql
    creds:
      user: dimplex_apl
      password: dimplex_apl
      database: dimplex_apl
  wp_rechner:
    type: mysql
    creds:
      user: wp_rechner
      password: wp_rechner
      database: wp_rechner
tooling:
  node:
    service: appserver
  npm:
    service: appserver
  grunt:
    service: appserver
  xdebug-on:
    service: appserver
    description: Enable xdebug for apache.
    cmd: "docker-php-ext-enable xdebug && /etc/init.d/apache2 reload"
    user: root
  xdebug-off:
    service: appserver
    description: Disable xdebug for apache.
    cmd: "rm /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini && /etc/init.d/apache2 reload"
    user: root
config:
  webroot: web
  xdebug: true
  composer_version: "1.10.1"

```
**Tell us about the command you were running**

```
$ lando php -i | grep limit
memory_limit => -1 => -1
Total Links => 0/unlimited
ldap.max_links => Unlimited => Unlimited
memcached.sess_server_failure_limit => 0 => 0
mysqli.max_links => Unlimited => Unlimited
mysqli.max_persistent => Unlimited => Unlimited
pcre.backtrack_limit => 1000000 => 1000000
pcre.recursion_limit => 100000 => 100000
session.cache_limiter => nocache => nocache
soap.wsdl_cache_limit => 5 => 5
```

```
$ lando composer -vvv require drupal/cookiebot
lando 17:38:08 DEBUG ==> No update available.
lando 17:38:08 VERBOSE ==> starting bootstrap at level engine...
lando 17:38:08 VERBOSE ==> config bootstrap beginning...
lando 17:38:08 DEBUG ==> emitting event pre-bootstrap-config
lando 17:38:08 DEBUG ==> plugin lando-core loaded from /snapshot/lando/build/cli/plugins/lando-core/index.js
lando 17:38:08 DEBUG ==> plugin lando-events loaded from /snapshot/lando/build/cli/plugins/lando-events/index.js
lando 17:38:08 DEBUG ==> plugin lando-networking loaded from /snapshot/lando/build/cli/plugins/lando-networking/index.js
lando 17:38:08 DEBUG ==> plugin lando-proxy loaded from /snapshot/lando/build/cli/plugins/lando-proxy/index.js
lando 17:38:08 DEBUG ==> plugin lando-recipes loaded from /snapshot/lando/build/cli/plugins/lando-recipes/index.js
lando 17:38:08 DEBUG ==> plugin lando-services loaded from /snapshot/lando/build/cli/plugins/lando-services/index.js
lando 17:38:08 DEBUG ==> plugin lando-sharing loaded from /snapshot/lando/build/cli/plugins/lando-sharing/index.js
lando 17:38:08 DEBUG ==> plugin lando-test loaded from /snapshot/lando/build/cli/plugins/lando-test/index.js
lando 17:38:08 DEBUG ==> plugin lando-tooling loaded from /snapshot/lando/build/cli/plugins/lando-tooling/index.js
lando 17:38:08 DEBUG ==> plugin lando-lagoon loaded from /snapshot/lando/build/cli/integrations/lando-lagoon/index.js
lando 17:38:08 DEBUG ==> plugin lando-pantheon loaded from /snapshot/lando/build/cli/integrations/lando-pantheon/index.js
lando 17:38:08 DEBUG ==> plugin lando-platformsh loaded from /snapshot/lando/build/cli/integrations/lando-platformsh/index.js
lando 17:38:08 DEBUG ==> emitting event post-bootstrap-config
lando 17:38:08 VERBOSE ==> building proxy config...
lando 17:38:08 VERBOSE ==> config bootstrap completed.
lando 17:38:08 VERBOSE ==> tasks bootstrap beginning...
lando 17:38:08 DEBUG ==> emitting event pre-bootstrap-tasks
lando 17:38:08 DEBUG ==> autoloaded task config
lando 17:38:08 DEBUG ==> autoloaded task destroy
lando 17:38:08 DEBUG ==> autoloaded task info
lando 17:38:08 DEBUG ==> autoloaded task list
lando 17:38:08 DEBUG ==> autoloaded task logs
lando 17:38:08 DEBUG ==> autoloaded task poweroff
lando 17:38:08 DEBUG ==> autoloaded task rebuild
lando 17:38:08 DEBUG ==> autoloaded task restart
lando 17:38:08 DEBUG ==> autoloaded task share
lando 17:38:08 DEBUG ==> autoloaded task start
lando 17:38:08 DEBUG ==> autoloaded task stop
lando 17:38:08 DEBUG ==> autoloaded task version
lando 17:38:08 DEBUG ==> autoloaded task init
lando 17:38:08 DEBUG ==> autoloaded task ssh
lando 17:38:08 DEBUG ==> emitting event post-bootstrap-tasks
lando 17:38:08 VERBOSE ==> tasks bootstrap completed.
lando 17:38:08 VERBOSE ==> engine bootstrap beginning...
lando 17:38:08 DEBUG ==> emitting event pre-bootstrap-engine
lando 17:38:08 DEBUG ==> automoved scripts from /snapshot/lando/build/cli/plugins/lando-core/scripts to /Users/bernhard/.lando/scripts and set to mode 755
lando 17:38:08 DEBUG ==> automoved scripts from /snapshot/lando/build/cli/plugins/lando-proxy/scripts to /Users/bernhard/.lando/scripts and set to mode 755
lando 17:38:08 DEBUG ==> automoved scripts from /snapshot/lando/build/cli/plugins/lando-recipes/scripts to /Users/bernhard/.lando/scripts and set to mode 755
lando 17:38:08 DEBUG ==> automoved scripts from /snapshot/lando/build/cli/plugins/lando-services/scripts to /Users/bernhard/.lando/scripts and set to mode 755
lando 17:38:08 DEBUG ==> automoved scripts from /snapshot/lando/build/cli/plugins/lando-sharing/scripts to /Users/bernhard/.lando/scripts and set to mode 755
lando 17:38:08 DEBUG ==> automoved scripts from /snapshot/lando/build/cli/integrations/lando-lagoon/scripts to /Users/bernhard/.lando/scripts and set to mode 755
lando 17:38:08 DEBUG ==> automoved scripts from /snapshot/lando/build/cli/integrations/lando-pantheon/scripts to /Users/bernhard/.lando/scripts and set to mode 755
lando 17:38:08 DEBUG ==> automoved scripts from /snapshot/lando/build/cli/integrations/lando-platformsh/scripts to /Users/bernhard/.lando/scripts and set to mode 755
lando 17:38:08 DEBUG ==> emitting event post-bootstrap-engine
lando 17:38:08 VERBOSE ==> engine bootstrap completed.
lando 17:38:08 VERBOSE ==> bootstrap completed.
lando 17:38:08 DEBUG ==> emitting event post-bootstrap
lando 17:38:08 VERBOSE ==> docker-engine exists: true
lando 17:38:08 VERBOSE ==> docker-compose exists: true
lando 17:38:08 DEBUG ==> emitting event cli-answers
lando 17:38:08 DEBUG ==> emitting event cli-composer-answers
lando 17:38:08 DEBUG ==> emitting event cli-run
lando 17:38:08 DEBUG ==> emitting event cli-composer-run
lando 17:38:08 DEBUG ==> emitting event pre-command-runner
lando 17:38:08 DEBUG ==> emitting event pre-composer
lando 17:38:08 DEBUG ==> process pid5 running /Applications/Docker.app/Contents/Resources/bin/docker exec dimplex_appserver_1 composer drupal/cookiebot cstdio=[inherit, pipe, pipe], silent=false, mode=attach, detached=false
lando 17:38:08 VERBOSE ==> checking docker version compatibility...
lando 17:38:08 DEBUG ==> compatibility results name=desktop, link=https://docs.docker.com/docker-for-mac/release-notes/, wants=2.1.0.0 - 3.1.99, version=3.2.2, semversion=3.2.2, semmin=2.1.0, semmax=3.1.99, dockerVersion=true, satisfied=false
Reading ./composer.json
Loading config file /var/www/.composer/config.json
Loading config file /var/www/.composer/auth.json
Loading config file ./composer.json
You are running Composer with SSL/TLS protection disabled.
Executing command (/app): git branch --no-color --no-abbrev -v
lando 17:38:09 DEBUG ==> engine is up.
                                       lando 17:38:09 DEBUG ==> docker is running.
                                                                                   Reading /var/www/.composer/composer.json
Loading config file /var/www/.composer/config.json
Loading config file /var/www/.composer/auth.json
Loading config file /var/www/.composer/composer.json
Loading config file /var/www/.composer/auth.json
Reading /var/www/.composer/auth.json
Reading /app/vendor/composer/installed.json
Reading /var/www/.composer/vendor/composer/installed.json
Loading plugin zaporylie\ComposerDrupalOptimizations\Plugin
Required tags were not explicitly set so the zaporylie/composer-drupal-optimizations set default based on project's composer.json content.
extra.commerce-drupal-optimizations.require.symfony/symfony: '>3.4'
Loading plugin TopFloor\ComposerCleanupVcsDirs\Plugin
Loading plugin OomphInc\ComposerInstallersExtender\Plugin
Loading plugin Drupal\Console\Composer\Plugin\Extender
Loading plugin DrupalComposer\DrupalScaffold\Plugin
Loading plugin cweagans\Composer\Patches
Loading plugin Composer\Installers\Plugin
Running 1.10.1 (2020-03-13 20:34:27) with PHP 7.1.33 on Linux / 4.19.121-linuxkit
Downloading https://packages.drupal.org/8/packages.json
Writing /var/www/.composer/cache/repo/https---packages.drupal.org-8/packages.json into cache
Downloading https://asset-packagist.org/packages.json
Writing /var/www/.composer/cache/repo/https---asset-packagist.org/packages.json into cache
Downloading https://repo.packagist.org/packages.json
Warning from https://repo.packagist.org: You are using an outdated version of Composer. Composer 2 is now available and you should upgrade. See https://getcomposer.org/2
Writing /var/www/.composer/cache/repo/https---repo.packagist.org/packages.json into cache
Reading /var/www/.composer/cache/repo/https---packages.drupal.org-8/drupal-provider-2021-1.json from cache
Reading /var/www/.composer/cache/repo/https---packages.drupal.org-8/drupal-provider-2020-4.json from cache
Reading /var/www/.composer/cache/repo/https---packages.drupal.org-8/drupal-provider-2020-3.json from cache
Reading /var/www/.composer/cache/repo/https---packages.drupal.org-8/drupal-provider-2020-2.json from cache
Reading /var/www/.composer/cache/repo/https---packages.drupal.org-8/drupal-provider-2020-1.json from cache
Reading /var/www/.composer/cache/repo/https---packages.drupal.org-8/drupal-provider-2019-4.json from cache
Reading /var/www/.composer/cache/repo/https---packages.drupal.org-8/drupal-provider-2019-3.json from cache
Reading /var/www/.composer/cache/repo/https---packages.drupal.org-8/drupal-provider-2019-2.json from cache
Reading /var/www/.composer/cache/repo/https---packages.drupal.org-8/drupal-provider-2019-1.json from cache
Reading /var/www/.composer/cache/repo/https---packages.drupal.org-8/drupal-provider-2018-4.json from cache
Reading /var/www/.composer/cache/repo/https---packages.drupal.org-8/drupal-provider-2018-3.json from cache
Reading /var/www/.composer/cache/repo/https---packages.drupal.org-8/drupal-provider-2018-2.json from cache
Reading /var/www/.composer/cache/repo/https---packages.drupal.org-8/drupal-provider-2018-1.json from cache
Reading /var/www/.composer/cache/repo/https---packages.drupal.org-8/drupal-provider-2017-4.json from cache
Reading /var/www/.composer/cache/repo/https---packages.drupal.org-8/drupal-provider-2017-3.json from cache
Reading /var/www/.composer/cache/repo/https---packages.drupal.org-8/drupal-provider-2017-2.json from cache
Reading /var/www/.composer/cache/repo/https---packages.drupal.org-8/drupal-provider-2017-1.json from cache
Reading /var/www/.composer/cache/repo/https---packages.drupal.org-8/drupal-provider-2016-4.json from cache
Reading /var/www/.composer/cache/repo/https---packages.drupal.org-8/drupal-provider-2016-3.json from cache
Reading /var/www/.composer/cache/repo/https---packages.drupal.org-8/drupal-provider-2016-2.json from cache
Reading /var/www/.composer/cache/repo/https---packages.drupal.org-8/drupal-provider-2016-1.json from cache
Reading /var/www/.composer/cache/repo/https---packages.drupal.org-8/drupal-provider-2015-4.json from cache
Reading /var/www/.composer/cache/repo/https---packages.drupal.org-8/drupal-provider-2015-3.json from cache
Reading /var/www/.composer/cache/repo/https---packages.drupal.org-8/drupal-provider-2015-2.json from cache
Reading /var/www/.composer/cache/repo/https---packages.drupal.org-8/drupal-provider-2015-1.json from cache
Reading /var/www/.composer/cache/repo/https---packages.drupal.org-8/drupal-provider-2014-4.json from cache
Reading /var/www/.composer/cache/repo/https---packages.drupal.org-8/drupal-provider-2014-3.json from cache
Reading /var/www/.composer/cache/repo/https---packages.drupal.org-8/drupal-provider-2014-2.json from cache
Reading /var/www/.composer/cache/repo/https---packages.drupal.org-8/drupal-provider-2014-1.json from cache
Reading /var/www/.composer/cache/repo/https---packages.drupal.org-8/drupal-provider-2013-4.json from cache
Reading /var/www/.composer/cache/repo/https---packages.drupal.org-8/drupal-provider-2013-3.json from cache
Reading /var/www/.composer/cache/repo/https---packages.drupal.org-8/drupal-provider-2013-2.json from cache
Reading /var/www/.composer/cache/repo/https---packages.drupal.org-8/drupal-provider-2013-1.json from cache
Reading /var/www/.composer/cache/repo/https---packages.drupal.org-8/drupal-provider-2012-4.json from cache
Reading /var/www/.composer/cache/repo/https---packages.drupal.org-8/drupal-provider-2012-3.json from cache
Reading /var/www/.composer/cache/repo/https---packages.drupal.org-8/drupal-provider-2012-2.json from cache
Reading /var/www/.composer/cache/repo/https---packages.drupal.org-8/drupal-provider-2012-1.json from cache
Reading /var/www/.composer/cache/repo/https---packages.drupal.org-8/drupal-provider-2011-4.json from cache
Reading /var/www/.composer/cache/repo/https---packages.drupal.org-8/drupal-provider-2011-3.json from cache
Reading /var/www/.composer/cache/repo/https---packages.drupal.org-8/drupal-provider-2011-2.json from cache
Reading /var/www/.composer/cache/repo/https---packages.drupal.org-8/provider-drupal$cookiebot.json from cache
Reading /var/www/.composer/cache/repo/https---asset-packagist.org/p-provider-latest-.json from cache
Reading /var/www/.composer/cache/repo/https---repo.packagist.org/p-provider-2013.json from cache
Reading /var/www/.composer/cache/repo/https---repo.packagist.org/p-provider-2014.json from cache
Reading /var/www/.composer/cache/repo/https---repo.packagist.org/p-provider-2015.json from cache
Reading /var/www/.composer/cache/repo/https---repo.packagist.org/p-provider-2016.json from cache
Reading /var/www/.composer/cache/repo/https---repo.packagist.org/p-provider-2017.json from cache
Reading /var/www/.composer/cache/repo/https---repo.packagist.org/p-provider-2018.json from cache
Reading /var/www/.composer/cache/repo/https---repo.packagist.org/p-provider-2019.json from cache
Reading /var/www/.composer/cache/repo/https---repo.packagist.org/p-provider-2020.json from cache
Reading /var/www/.composer/cache/repo/https---repo.packagist.org/p-provider-2020-04.json from cache
Reading /var/www/.composer/cache/repo/https---repo.packagist.org/p-provider-2020-07.json from cache
Reading /var/www/.composer/cache/repo/https---repo.packagist.org/p-provider-2020-10.json from cache
Reading /var/www/.composer/cache/repo/https---repo.packagist.org/p-provider-2021-01.json from cache
Reading /var/www/.composer/cache/repo/https---repo.packagist.org/p-provider-archived.json from cache
Reading /var/www/.composer/cache/repo/https---repo.packagist.org/p-provider-latest.json from cache
Using version ^1.0@alpha for drupal/cookiebot
./composer.json has been updated
Reading ./composer.json
Loading config file /var/www/.composer/config.json
Loading config file /var/www/.composer/auth.json
Loading config file ./composer.json
Executing command (/app): git branch --no-color --no-abbrev -v
Reading /var/www/.composer/composer.json
Loading config file /var/www/.composer/config.json
Loading config file /var/www/.composer/auth.json
Loading config file /var/www/.composer/composer.json
Loading config file /var/www/.composer/auth.json
Reading /var/www/.composer/auth.json
Reading /app/vendor/composer/installed.json
Reading /var/www/.composer/vendor/composer/installed.json
Loading plugin zaporylie\ComposerDrupalOptimizations\Plugin_composer_tmp0
Required tags were not explicitly set so the zaporylie/composer-drupal-optimizations set default based on project's composer.json content.
extra.commerce-drupal-optimizations.require.symfony/symfony: '>3.4'
Loading plugin TopFloor\ComposerCleanupVcsDirs\Plugin_composer_tmp1
Loading plugin OomphInc\ComposerInstallersExtender\Plugin_composer_tmp2
Loading plugin Drupal\Console\Composer\Plugin\Extender_composer_tmp3
Loading plugin DrupalComposer\DrupalScaffold\Plugin_composer_tmp4
Loading plugin cweagans\Composer\Patches_composer_tmp5
Loading plugin Composer\Installers\Plugin_composer_tmp6
Gathering patches for root package.
> pre-update-cmd: DrupalProject\composer\ScriptHandler::checkComposerVersion
Reading ./composer.lock
Loading composer repositories with package information
Downloading https://packages.drupal.org/8/packages.json
Writing /var/www/.composer/cache/repo/https---packages.drupal.org-8/packages.json into cache
Downloading https://asset-packagist.org/packages.json
Writing /var/www/.composer/cache/repo/https---asset-packagist.org/packages.json into cache
Downloading https://repo.packagist.org/packages.json
Warning from https://repo.packagist.org: You are using an outdated version of Composer. Composer 2 is now available and you should upgrade. See https://getcomposer.org/2
Writing /var/www/.composer/cache/repo/https---repo.packagist.org/packages.json into cache
Updating dependencies (including require-dev)
Reading /var/www/.composer/cache/repo/https---packages.drupal.org-8/drupal-provider-2021-1.json from cache
Reading /var/www/.composer/cache/repo/https---packages.drupal.org-8/drupal-provider-2020-4.json from cache
Reading /var/www/.composer/cache/repo/https---packages.drupal.org-8/drupal-provider-2020-3.json from cache
Reading /var/www/.composer/cache/repo/https---packages.drupal.org-8/drupal-provider-2020-2.json from cache
Reading /var/www/.composer/cache/repo/https---packages.drupal.org-8/drupal-provider-2020-1.json from cache
Reading /var/www/.composer/cache/repo/https---packages.drupal.org-8/drupal-provider-2019-4.json from cache
Reading /var/www/.composer/cache/repo/https---packages.drupal.org-8/drupal-provider-2019-3.json from cache
Reading /var/www/.composer/cache/repo/https---packages.drupal.org-8/drupal-provider-2019-2.json from cache
Reading /var/www/.composer/cache/repo/https---packages.drupal.org-8/drupal-provider-2019-1.json from cache
Reading /var/www/.composer/cache/repo/https---packages.drupal.org-8/drupal-provider-2018-4.json from cache
Reading /var/www/.composer/cache/repo/https---packages.drupal.org-8/drupal-provider-2018-3.json from cache
Reading /var/www/.composer/cache/repo/https---packages.drupal.org-8/drupal-provider-2018-2.json from cache
Reading /var/www/.composer/cache/repo/https---packages.drupal.org-8/drupal-provider-2018-1.json from cache
Reading /var/www/.composer/cache/repo/https---packages.drupal.org-8/drupal-provider-2017-4.json from cache
Reading /var/www/.composer/cache/repo/https---packages.drupal.org-8/drupal-provider-2017-3.json from cache
Reading /var/www/.composer/cache/repo/https---packages.drupal.org-8/drupal-provider-2017-2.json from cache
Reading /var/www/.composer/cache/repo/https---packages.drupal.org-8/drupal-provider-2017-1.json from cache
Reading /var/www/.composer/cache/repo/https---packages.drupal.org-8/drupal-provider-2016-4.json from cache
Reading /var/www/.composer/cache/repo/https---packages.drupal.org-8/drupal-provider-2016-3.json from cache
Reading /var/www/.composer/cache/repo/https---packages.drupal.org-8/drupal-provider-2016-2.json from cache
Reading /var/www/.composer/cache/repo/https---packages.drupal.org-8/drupal-provider-2016-1.json from cache
Reading /var/www/.composer/cache/repo/https---packages.drupal.org-8/drupal-provider-2015-4.json from cache
Reading /var/www/.composer/cache/repo/https---packages.drupal.org-8/drupal-provider-2015-3.json from cache
Reading /var/www/.composer/cache/repo/https---packages.drupal.org-8/drupal-provider-2015-2.json from cache
Reading /var/www/.composer/cache/repo/https---packages.drupal.org-8/drupal-provider-2015-1.json from cache
Reading /var/www/.composer/cache/repo/https---packages.drupal.org-8/drupal-provider-2014-4.json from cache
Reading /var/www/.composer/cache/repo/https---packages.drupal.org-8/drupal-provider-2014-3.json from cache
Reading /var/www/.composer/cache/repo/https---packages.drupal.org-8/drupal-provider-2014-2.json from cache
Reading /var/www/.composer/cache/repo/https---packages.drupal.org-8/drupal-provider-2014-1.json from cache
Reading /var/www/.composer/cache/repo/https---packages.drupal.org-8/drupal-provider-2013-4.json from cache
Reading /var/www/.composer/cache/repo/https---packages.drupal.org-8/drupal-provider-2013-3.json from cache
Reading /var/www/.composer/cache/repo/https---packages.drupal.org-8/drupal-provider-2013-2.json from cache
Reading /var/www/.composer/cache/repo/https---packages.drupal.org-8/drupal-provider-2013-1.json from cache
Reading /var/www/.composer/cache/repo/https---packages.drupal.org-8/drupal-provider-2012-4.json from cache
Reading /var/www/.composer/cache/repo/https---packages.drupal.org-8/drupal-provider-2012-3.json from cache
Reading /var/www/.composer/cache/repo/https---packages.drupal.org-8/drupal-provider-2012-2.json from cache
Reading /var/www/.composer/cache/repo/https---packages.drupal.org-8/drupal-provider-2012-1.json from cache
Reading /var/www/.composer/cache/repo/https---packages.drupal.org-8/drupal-provider-2011-4.json from cache
Reading /var/www/.composer/cache/repo/https---packages.drupal.org-8/drupal-provider-2011-3.json from cache
Reading /var/www/.composer/cache/repo/https---packages.drupal.org-8/drupal-provider-2011-2.json from cache
Reading /var/www/.composer/cache/repo/https---asset-packagist.org/p-provider-latest-.json from cache
Reading /var/www/.composer/cache/repo/https---repo.packagist.org/p-provider-2013.json from cache
Reading /var/www/.composer/cache/repo/https---repo.packagist.org/p-provider-2014.json from cache
Reading /var/www/.composer/cache/repo/https---repo.packagist.org/p-provider-2015.json from cache
Reading /var/www/.composer/cache/repo/https---repo.packagist.org/p-provider-2016.json from cache
Reading /var/www/.composer/cache/repo/https---repo.packagist.org/p-provider-2017.json from cache
Reading /var/www/.composer/cache/repo/https---repo.packagist.org/p-provider-2018.json from cache
Reading /var/www/.composer/cache/repo/https---repo.packagist.org/p-provider-2019.json from cache
Reading /var/www/.composer/cache/repo/https---repo.packagist.org/p-provider-2020.json from cache
Reading /var/www/.composer/cache/repo/https---repo.packagist.org/p-provider-2020-04.json from cache
Reading /var/www/.composer/cache/repo/https---repo.packagist.org/p-provider-2020-07.json from cache
Reading /var/www/.composer/cache/repo/https---repo.packagist.org/p-provider-2020-10.json from cache
Reading /var/www/.composer/cache/repo/https---repo.packagist.org/p-provider-2021-01.json from cache
Reading /var/www/.composer/cache/repo/https---repo.packagist.org/p-provider-archived.json from cache
Reading /var/www/.composer/cache/repo/https---repo.packagist.org/p-provider-latest.json from cache
Reading /var/www/.composer/cache/repo/https---repo.packagist.org/provider-doctrine$collections.json from cache
Reading /var/www/.composer/cache/repo/https---repo.packagist.org/provider-symfony$filesystem.json from cache
Reading /var/www/.composer/cache/repo/https---repo.packagist.org/provider-symfony$polyfill-mbstring.json from cache
Reading /var/www/.composer/cache/repo/https---repo.packagist.org/provider-symfony$process.json from cache
Reading /var/www/.composer/cache/repo/https---repo.packagist.org/provider-alchemy$zippy.json from cache
Downloading http://repo.packagist.org/p/symfony/polyfill-ctype%2445076abfe42f3d9248c8eeee53ffbac0cbd5956c0cdfad44b8bf00492dd8d382.json
Killed
lando 17:38:20 DEBUG ==> process pid5 finished with exit code 137
lando 17:38:20 DEBUG ==> engine is up.
lando 17:38:20 VERBOSE ==> reporting error action to report=true, url=https://metrics.lando.dev, report=true, url=https://metrics.lando.dev
lando 17:38:20 DEBUG ==> reported data command=lando composer,drupal/cookiebot,require, context=local, devMode=false, instance=c3d9774425fd88c9ac42e67023b77c58e69c05ae, nodeVersion=v12.13.1, mode=cli, type=Darwin, platform=darwin, release=19.6.0, arch=x64, product=lando, version=3.0.26, message=Killed, stack=Error: Killed
    at /snapshot/lando/build/cli/lib/shell.js
From previous event:
    at Shell.sh (shell.js)
    at Object.dockerExec (utils.js)
    at /snapshot/lando/build/cli/plugins/lando-tooling/lib/build.js
From previous event:
    at Object.run (build.js)
From previous event:
    at /snapshot/lando/build/cli/lib/bootstrap.js
From previous event:
    at /snapshot/lando/build/cli/lib/cli.js
From previous event:
    at Object.handler (cli.js)
    at Object.runCommand (command.js:238:44)
    at Object.parseArgs [as _parseArgs] (yargs.js:1063:30)
    at Function.get [as argv] (yargs.js:1004:21)
    at Cli.init (cli.js)
    at Cli.run (cli.js)
    at Object.<anonymous> (lando.js)
    at Module._compile (bootstrap.js:1324:22)
    at Function.Module.runMain (bootstrap.js:1379:12)
    at internal/main/run_main_module.js:17:11, action=error, created=2021-03-23T16:38:20.392Z
```

--> lando composer clearcache makes no difference

**Comment by zuernBernhard** [comment]
![Bildschirmfoto 2021-03-23 um 17 45 15](https://user-images.githubusercontent.com/1442798/112184545-994fd780-8bff-11eb-9c09-4563ca112b02.jpg)

**Comment by pirog** [comment]
@zuernBernhard probably want to bump the memory in Docker Desktop ^

**Comment by zuernBernhard** [comment]
That did the trick - thank you ! 

![Bildschirmfoto 2021-03-23 um 17 59 24](https://user-images.githubusercontent.com/1442798/112186541-863e0700-8c01-11eb-8368-c063e732fbb4.jpg)

```
 $ lando composer require drupal/cookiebot 
You are running Composer with SSL/TLS protection disabled.
Warning from https://repo.packagist.org: You are using an outdated version of Composer. Composer 2 is now available and you should upgrade. See https://getcomposer.org/2
Using version ^1.0@alpha for drupal/cookiebot
./composer.json has been updated
Gathering patches for root package.
> DrupalProject\composer\ScriptHandler::checkComposerVersion
Loading composer repositories with package information
Warning from https://repo.packagist.org: You are using an outdated version of Composer. Composer 2 is now available and you should upgrade. See https://getcomposer.org/2
Updating dependencies (including require-dev)
Package operations: 1 install, 0 updates, 0 removals
Gathering patches for root package.
Gathering patches for dependencies. This might take a minute.
  - Installing drupal/cookiebot (1.0.0-alpha8): Downloading (100%)         
Package container-interop/container-interop is abandoned, you should avoid using it. Use psr/container instead.
Package doctrine/reflection is abandoned, you should avoid using it. Use roave/better-reflection instead.
Package drupal-composer/drupal-scaffold is abandoned, you should avoid using it. Use drupal/core-composer-scaffold instead.
Package drush/config-extra is abandoned, you should avoid using it. No replacement was suggested.
Writing lock file
Generating autoload files
41 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
> DrupalProject\composer\ScriptHandler::createRequiredFiles
```
