### ISSUE TITLE
Lando Acquia Experimental returns TypeError when authenticated in Acquia CLI

### ISSUE THREAD

**Issue by aalderman19** [lando/lando#2961]
**Tell us about your setup**

What is your lando version and operating system? **(note that the older your version the less likely we are to reply)**

*v3.1.0 on MacOS Catalina 10.15.7*

**Tell us about your `.lando.yml`**

```yml
name: <name>
recipe: acquia
config:
  acli_version: master
  ah_application_uuid: <uuid>
  ah_site_group: <name>
  php: '7.4'
  conf:
    php: .vscode/php.ini
```

**Tell us about the command you were running**

```bash
lando --experimental   #turn on flags
acli auth:login        #login to acquia with an API key in acli
lando version          #check lando version
```

**Tell us about the error you got**
```bash
lando 10:18:00 DEBUG ==> Checking for updates... 
lando 10:18:00 VERBOSE ==> starting bootstrap at level tasks... 
lando 10:18:00 VERBOSE ==> config bootstrap beginning... 
lando 10:18:00 DEBUG ==> emitting event pre-bootstrap-config 
lando 10:18:00 DEBUG ==> plugin lando-core loaded from /snapshot/lando/build/cli/plugins/lando-core/index.js 
lando 10:18:00 DEBUG ==> plugin lando-events loaded from /snapshot/lando/build/cli/plugins/lando-events/index.js 
lando 10:18:00 DEBUG ==> plugin lando-networking loaded from /snapshot/lando/build/cli/plugins/lando-networking/index.js 
lando 10:18:00 DEBUG ==> plugin lando-proxy loaded from /snapshot/lando/build/cli/plugins/lando-proxy/index.js 
lando 10:18:00 DEBUG ==> plugin lando-recipes loaded from /snapshot/lando/build/cli/plugins/lando-recipes/index.js 
lando 10:18:00 DEBUG ==> plugin lando-services loaded from /snapshot/lando/build/cli/plugins/lando-services/index.js 
lando 10:18:00 DEBUG ==> plugin lando-sharing loaded from /snapshot/lando/build/cli/plugins/lando-sharing/index.js 
lando 10:18:00 DEBUG ==> plugin lando-test loaded from /snapshot/lando/build/cli/plugins/lando-test/index.js 
lando 10:18:00 DEBUG ==> plugin lando-tooling loaded from /snapshot/lando/build/cli/plugins/lando-tooling/index.js 
lando 10:18:00 DEBUG ==> plugin lando-lagoon loaded from /snapshot/lando/build/cli/integrations/lando-lagoon/index.js 
lando 10:18:00 DEBUG ==> plugin lando-pantheon loaded from /snapshot/lando/build/cli/integrations/lando-pantheon/index.js 
lando 10:18:00 DEBUG ==> plugin lando-platformsh loaded from /snapshot/lando/build/cli/integrations/lando-platformsh/index.js 
lando 10:18:00 DEBUG ==> plugin lando-acquia loaded from /snapshot/lando/build/cli/experimental/lando-acquia/index.js 
lando 10:18:00 DEBUG ==> plugin lando-experimental loaded from /snapshot/lando/build/cli/experimental/lando-experimental/index.js 
lando 10:18:00 DEBUG ==> emitting event post-bootstrap-config 
lando 10:18:00 VERBOSE ==> building proxy config... 
lando 10:18:00 VERBOSE ==> config bootstrap completed. 
lando 10:18:00 VERBOSE ==> tasks bootstrap beginning... 
lando 10:18:00 DEBUG ==> emitting event pre-bootstrap-tasks 
lando 10:18:00 DEBUG ==> autoloaded task config 
lando 10:18:00 DEBUG ==> autoloaded task destroy 
lando 10:18:00 DEBUG ==> autoloaded task info 
lando 10:18:00 DEBUG ==> autoloaded task list 
lando 10:18:00 DEBUG ==> autoloaded task logs 
lando 10:18:00 DEBUG ==> autoloaded task poweroff 
lando 10:18:00 DEBUG ==> autoloaded task rebuild 
lando 10:18:00 DEBUG ==> autoloaded task restart 
lando 10:18:00 DEBUG ==> autoloaded task share 
lando 10:18:00 DEBUG ==> autoloaded task start 
lando 10:18:00 DEBUG ==> autoloaded task stop 
lando 10:18:00 DEBUG ==> autoloaded task version 
lando version

Displays the lando version

Options:
  --channel       Sets the update channel                                      [array] [choices: "edge", "none", "stable"]
  --clear         Clears the lando tasks cache                                                                   [boolean]
  --experimental  Activates experimental features                                                                [boolean]
  --help          Shows lando or delegated command help if applicable                                            [boolean]
  --verbose, -v   Runs with extra verbosity                                                                        [count]
  --all, ---a     Shows additional version information

TypeError: Cannot create property 'key' on string 'a'
    at /snapshot/lando/build/cli/experimental/lando-acquia/lib/utils.js
    at /snapshot/lando/build/cli/node_modules/lodash/lodash.js:4901:15
    at Function.forEach (/snapshot/lando/build/cli/node_modules/lodash/lodash.js:9368:14)
    at Object.getHostKeys (/snapshot/lando/build/cli/experimental/lando-acquia/lib/utils.js)
    at mergeKeys (/snapshot/lando/build/cli/experimental/lando-acquia/recipes/acquia/init.js)
    at Object.options (/snapshot/lando/build/cli/experimental/lando-acquia/recipes/acquia/init.js)
    at /snapshot/lando/build/cli/plugins/lando-recipes/lib/options.js
    at arrayEach (/snapshot/lando/build/cli/node_modules/lodash/lodash.js:516:11)
    at Function.forEach (/snapshot/lando/build/cli/node_modules/lodash/lodash.js:9368:14)
    at Object.getConfigOptions (/snapshot/lando/build/cli/plugins/lando-recipes/lib/options.js)
    at /snapshot/lando/build/cli/plugins/lando-recipes/tasks/init.js
    at /snapshot/lando/build/cli/lib/lando.js
From previous event:
    at processImmediate (internal/timers.js:439:21)
```

**Tell us generally about your bug**
*I tried to run a lando command after logging into the Acquia CLI, but lando would not run in experimental mode.*

Please detail the steps we can take to replicate this bug. Be as detailed as possible.
```bash
1. Login using an API key to the Acquia CLI using `acli auth:login`
2. Try to run any lando command in the terminal
```

**Tell us more**
Logging out of the acli using `acli auth:logout` was still not enough to fix the issue. I was able to resolve this, by deleting my acli configuration folder, but don't want to have to go through those steps if I login to acli to manage something in Acquia directly.

**Comment by mikemilano** [comment]
@aalderman19 can you show us the `~/.acquia/cloud_api.conf` on your host system? (Without disclosing sensitive data)

**Comment by aalderman19** [comment]
```json
{"send_telemetry":false,"keys":{"<KEY_ID>":{"label":"<LABEL>","uuid":"<KEY_ID>","secret":"<KEY_SECRET>"}},"acli_key":"<ACLI_KEY>"}
```

As a note, since I have made the report, it seems that there have been some updates to the Acquia CLI repo. In addition, I have upgraded my local `acli` to v1.10.0 from v1.9.0. After these updates, I can no longer replicate this issue. Might have been a problem with that.

Thanks for taking a look at this so quickly!

**Comment by mikemilano** [comment]
Great! And yes, there were changes to the structure of that file with recent ACLI releases. We control the ACLI version in the application container but we try to save some effort by loading the keys from the host if they exist. Thanks for reporting the fix.

**Comment by pirog** [comment]
Relatedly, @mikemilano and @grasmash, we are still hardcoding `master` as the `acli` version. Has `acli` dev cooled off to the point where we could put in an actual versioned release?

**Comment by mikemilano** [comment]
@pirog [1.1.0](https://github.com/acquia/cli/releases) was released yesterday so I'll go ahead and update the plugin today to use the `latest` build after confirming with Matt in Slack this makes sense.
