### ISSUE TITLE
PHP 8.0 not working for custom service

### ISSUE THREAD

**Issue by tylersatre** [lando/lando#2972]
I'm running Lando v3.0.26 on MacOS 11.2.3.  The `.lando.yml` file is:

```yml
name: freesite-amp-theme
services:
  appserver:
    type: php:8.0
    via: cli
    run:
      - composer install
tooling:
  test:
    service: appserver
    description: Run test suite.
    cmd: composer test
```
When I run `lando rebuild -y` to try to rebuild this with php 8.0 (moving from 7.3) I get the error `php version 8.0 is not supported`.  The detailed logging is:

``` bash
tyler.satre@TSATRE wp-freesite-amp-theme % lando rebuild -y -vvv
lando 10:46:22 DEBUG ==> No update available. 
lando 10:46:22 VERBOSE ==> starting bootstrap at level app... 
lando 10:46:22 VERBOSE ==> config bootstrap beginning... 
lando 10:46:22 DEBUG ==> emitting event pre-bootstrap-config 
lando 10:46:22 DEBUG ==> plugin lando-core loaded from /Users/tyler.satre/.lando/plugins/lando-core/index.js 
lando 10:46:22 DEBUG ==> plugin lando-events loaded from /Users/tyler.satre/.lando/plugins/lando-events/index.js 
lando 10:46:22 DEBUG ==> plugin lando-networking loaded from /Users/tyler.satre/.lando/plugins/lando-networking/index.js 
lando 10:46:22 DEBUG ==> plugin lando-proxy loaded from /Users/tyler.satre/.lando/plugins/lando-proxy/index.js 
lando 10:46:22 DEBUG ==> plugin lando-recipes loaded from /Users/tyler.satre/.lando/plugins/lando-recipes/index.js 
lando 10:46:22 DEBUG ==> plugin lando-services loaded from /Users/tyler.satre/.lando/plugins/lando-services/index.js 
lando 10:46:22 DEBUG ==> plugin lando-sharing loaded from /Users/tyler.satre/.lando/plugins/lando-sharing/index.js 
lando 10:46:22 DEBUG ==> plugin lando-test loaded from /Users/tyler.satre/.lando/plugins/lando-test/index.js 
lando 10:46:22 DEBUG ==> plugin lando-tooling loaded from /Users/tyler.satre/.lando/plugins/lando-tooling/index.js 
lando 10:46:22 DEBUG ==> plugin lando-lagoon loaded from /snapshot/lando/build/cli/integrations/lando-lagoon/index.js 
lando 10:46:22 DEBUG ==> plugin lando-pantheon loaded from /snapshot/lando/build/cli/integrations/lando-pantheon/index.js 
lando 10:46:22 DEBUG ==> plugin lando-platformsh loaded from /snapshot/lando/build/cli/integrations/lando-platformsh/index.js 
lando 10:46:22 DEBUG ==> emitting event post-bootstrap-config 
lando 10:46:22 VERBOSE ==> building proxy config... 
lando 10:46:22 VERBOSE ==> config bootstrap completed. 
lando 10:46:22 VERBOSE ==> tasks bootstrap beginning... 
lando 10:46:22 DEBUG ==> emitting event pre-bootstrap-tasks 
lando 10:46:22 DEBUG ==> autoloaded task config 
lando 10:46:22 DEBUG ==> autoloaded task destroy 
lando 10:46:22 DEBUG ==> autoloaded task info 
lando 10:46:22 DEBUG ==> autoloaded task list 
lando 10:46:22 DEBUG ==> autoloaded task logs 
lando 10:46:22 DEBUG ==> autoloaded task poweroff 
lando 10:46:22 DEBUG ==> autoloaded task rebuild 
lando 10:46:22 DEBUG ==> autoloaded task restart 
lando 10:46:22 DEBUG ==> autoloaded task share 
lando 10:46:22 DEBUG ==> autoloaded task start 
lando 10:46:22 DEBUG ==> autoloaded task stop 
lando 10:46:22 DEBUG ==> autoloaded task version 
lando 10:46:22 DEBUG ==> autoloaded task init 
lando 10:46:22 DEBUG ==> autoloaded task ssh 
lando 10:46:22 DEBUG ==> emitting event post-bootstrap-tasks 
lando 10:46:22 VERBOSE ==> tasks bootstrap completed. 
lando 10:46:22 VERBOSE ==> engine bootstrap beginning... 
lando 10:46:22 DEBUG ==> emitting event pre-bootstrap-engine 
lando 10:46:22 DEBUG ==> automoved scripts from /Users/tyler.satre/.lando/plugins/lando-core/scripts to /Users/tyler.satre/.lando/scripts and set to mode 755 
lando 10:46:22 DEBUG ==> automoved scripts from /Users/tyler.satre/.lando/plugins/lando-proxy/scripts to /Users/tyler.satre/.lando/scripts and set to mode 755 
lando 10:46:22 DEBUG ==> automoved scripts from /Users/tyler.satre/.lando/plugins/lando-recipes/scripts to /Users/tyler.satre/.lando/scripts and set to mode 755 
lando 10:46:22 DEBUG ==> automoved scripts from /Users/tyler.satre/.lando/plugins/lando-services/scripts to /Users/tyler.satre/.lando/scripts and set to mode 755 
lando 10:46:22 DEBUG ==> automoved scripts from /Users/tyler.satre/.lando/plugins/lando-sharing/scripts to /Users/tyler.satre/.lando/scripts and set to mode 755 
lando 10:46:22 DEBUG ==> automoved scripts from /snapshot/lando/build/cli/integrations/lando-lagoon/scripts to /Users/tyler.satre/.lando/scripts and set to mode 755 
lando 10:46:22 DEBUG ==> automoved scripts from /snapshot/lando/build/cli/integrations/lando-pantheon/scripts to /Users/tyler.satre/.lando/scripts and set to mode 755 
lando 10:46:22 DEBUG ==> automoved scripts from /snapshot/lando/build/cli/integrations/lando-platformsh/scripts to /Users/tyler.satre/.lando/scripts and set to mode 755 
lando 10:46:22 DEBUG ==> emitting event post-bootstrap-engine 
lando 10:46:22 VERBOSE ==> engine bootstrap completed. 
lando 10:46:22 VERBOSE ==> app bootstrap beginning... 
lando 10:46:22 DEBUG ==> emitting event pre-bootstrap-app 
lando 10:46:22 DEBUG ==> autoloaded builder LandoCompose 
lando 10:46:22 DEBUG ==> autoloaded builder LandoAppserver 
lando 10:46:22 DEBUG ==> autoloaded builder LandoService 
lando 10:46:22 DEBUG ==> autoloaded builder LandoUtility 
lando 10:46:22 DEBUG ==> autoloaded builder LandoWebServer 
lando 10:46:22 DEBUG ==> autoloaded builder LandoDrupal 
lando 10:46:22 DEBUG ==> autoloaded builder LandoLaemp 
lando 10:46:22 DEBUG ==> autoloaded builder LandoAppserver 
lando 10:46:22 DEBUG ==> autoloaded builder LandoPlatformAppserver 
lando 10:46:22 DEBUG ==> autoloaded builder LandoPlatformService 
lando 10:46:22 DEBUG ==> autoloaded builder LandoCa 
lando 10:46:22 DEBUG ==> autoloaded builder LandoProxy 
lando 10:46:22 DEBUG ==> autoloaded builder LandoInit 
lando 10:46:22 DEBUG ==> autoloaded builder LandoApache 
lando 10:46:22 DEBUG ==> autoloaded builder LandoCompose 
lando 10:46:22 DEBUG ==> autoloaded builder LandoDotNet 
lando 10:46:22 DEBUG ==> autoloaded builder LandoElasticSearch 
lando 10:46:22 DEBUG ==> autoloaded builder LandoGo 
lando 10:46:22 DEBUG ==> autoloaded builder LandoMailHog 
lando 10:46:22 DEBUG ==> autoloaded builder LandoMariaDb 
lando 10:46:22 DEBUG ==> autoloaded builder LandoMemcached 
lando 10:46:22 DEBUG ==> autoloaded builder LandoMongoDb 
lando 10:46:22 DEBUG ==> autoloaded builder LandoMsSql 
lando 10:46:22 DEBUG ==> autoloaded builder LandoMySql 
lando 10:46:22 DEBUG ==> autoloaded builder LandoNginx 
lando 10:46:22 DEBUG ==> autoloaded builder LandoNode 
lando 10:46:22 DEBUG ==> autoloaded builder LandoPhp 
lando 10:46:22 DEBUG ==> autoloaded builder LandoPma 
lando 10:46:22 DEBUG ==> autoloaded builder LandoPostgres 
lando 10:46:22 DEBUG ==> autoloaded builder LandoPython 
lando 10:46:22 DEBUG ==> autoloaded builder LandoRedis 
lando 10:46:22 DEBUG ==> autoloaded builder LandoRuby 
lando 10:46:22 DEBUG ==> autoloaded builder LandoSolr 
lando 10:46:22 DEBUG ==> autoloaded builder LandoTomcat 
lando 10:46:22 DEBUG ==> autoloaded builder LandoVarnish 
lando 10:46:22 DEBUG ==> autoloaded builder LandoMounter 
lando 10:46:22 DEBUG ==> autoloaded builder LandoLagoonMariaDb 
lando 10:46:22 DEBUG ==> autoloaded builder LandoLagoonNginx 
lando 10:46:22 DEBUG ==> autoloaded builder LandoLagoonNone 
lando 10:46:22 DEBUG ==> autoloaded builder LandoLagoonPhp 
lando 10:46:22 DEBUG ==> autoloaded builder LandoLagoonPhp 
lando 10:46:22 DEBUG ==> autoloaded builder LandoLagoonPostgres 
lando 10:46:22 DEBUG ==> autoloaded builder LandoLagoonRedis 
lando 10:46:22 DEBUG ==> autoloaded builder LandoLagoonSolr 
lando 10:46:22 DEBUG ==> autoloaded builder LandoLagoonVarnish 
lando 10:46:22 DEBUG ==> autoloaded builder LandoPlatformshChromeHeadless 
lando 10:46:22 DEBUG ==> autoloaded builder LandoPlatformsElasticsearch 
lando 10:46:22 DEBUG ==> autoloaded builder LandoPlatformshInfluxdb 
lando 10:46:22 DEBUG ==> autoloaded builder LandoPlatformshKafka 
lando 10:46:22 DEBUG ==> autoloaded builder LandoPlatformshMariaDB 
lando 10:46:22 DEBUG ==> autoloaded builder LandoPlatformshMemcached 
lando 10:46:22 DEBUG ==> autoloaded builder LandoPlatformsMongoDB 
lando 10:46:22 DEBUG ==> autoloaded builder LandoPlatformshPhp 
lando 10:46:22 DEBUG ==> autoloaded builder LandoPlatformshPostgres 
lando 10:46:22 DEBUG ==> autoloaded builder LandoPlatformshRabbitmq 
lando 10:46:22 DEBUG ==> autoloaded builder LandoPlatformshRedis 
lando 10:46:22 DEBUG ==> autoloaded builder LandoPlatformshSolr 
lando 10:46:22 DEBUG ==> autoloaded builder LandoPlatformshVarnish 
lando 10:46:22 DEBUG ==> autoloaded builder LandoBackdrop 
lando 10:46:22 DEBUG ==> autoloaded builder LandoDrupal6 
lando 10:46:22 DEBUG ==> autoloaded builder LandoDrupal7 
lando 10:46:22 DEBUG ==> autoloaded builder LandoDrupal8 
lando 10:46:22 DEBUG ==> autoloaded builder LandoDrupal9 
lando 10:46:22 DEBUG ==> autoloaded builder LandoJoomla 
lando 10:46:22 DEBUG ==> autoloaded builder LandoLamp 
lando 10:46:22 DEBUG ==> autoloaded builder LandoLaravel 
lando 10:46:22 DEBUG ==> autoloaded builder LandoLamp 
lando 10:46:22 DEBUG ==> autoloaded builder LandoMean 
lando 10:46:22 DEBUG ==> autoloaded builder LandoWordPress 
lando 10:46:22 DEBUG ==> autoloaded builder LandoLagoon 
lando 10:46:22 DEBUG ==> autoloaded builder LandoPantheon 
lando 10:46:22 DEBUG ==> autoloaded builder LandoPlatformsh 
lando 10:46:22 DEBUG ==> emitting event post-bootstrap-app 
lando 10:46:22 VERBOSE ==> app bootstrap completed. 
lando 10:46:22 VERBOSE ==> bootstrap completed. 
lando 10:46:22 DEBUG ==> emitting event post-bootstrap 
lando 10:46:22 VERBOSE ==> docker-engine exists: true 
lando 10:46:22 VERBOSE ==> docker-compose exists: true 
lando 10:46:22 DEBUG ==> emitting event cli-answers 
lando 10:46:22 DEBUG ==> emitting event cli-rebuild-answers 
lando 10:46:22 INFO ==> loading app freesite-amp-theme from config files 0=/Users/tyler.satre/WIP/wp-freesite-amp-theme/.lando.yml
lando 10:46:22 DEBUG ==> app freesite-amp-theme has config name=freesite-amp-theme, type=php:8.0, via=cli, run=[composer install], service=appserver, description=Run test suite., cmd=composer test
freesite-amp-theme 10:46:22 VERBOSE ==> initiatilizing app at /Users/tyler.satre/WIP/wp-freesite-amp-theme... 
lando              10:46:22 DEBUG ==> plugin lando-core loaded from /Users/tyler.satre/.lando/plugins/lando-core/app.js 
lando              10:46:22 DEBUG ==> plugin lando-events loaded from /Users/tyler.satre/.lando/plugins/lando-events/app.js 
lando              10:46:22 DEBUG ==> plugin lando-networking loaded from /Users/tyler.satre/.lando/plugins/lando-networking/app.js 
lando              10:46:22 DEBUG ==> plugin lando-proxy loaded from /Users/tyler.satre/.lando/plugins/lando-proxy/app.js 
lando              10:46:22 DEBUG ==> plugin lando-recipes loaded from /Users/tyler.satre/.lando/plugins/lando-recipes/app.js 
lando              10:46:22 DEBUG ==> plugin lando-services loaded from /Users/tyler.satre/.lando/plugins/lando-services/app.js 
lando              10:46:22 DEBUG ==> plugin lando-sharing loaded from /Users/tyler.satre/.lando/plugins/lando-sharing/app.js 
lando              10:46:22 DEBUG ==> plugin lando-tooling loaded from /Users/tyler.satre/.lando/plugins/lando-tooling/app.js 
lando              10:46:22 DEBUG ==> plugin lando-lagoon loaded from /snapshot/lando/build/cli/integrations/lando-lagoon/app.js 
lando              10:46:22 DEBUG ==> plugin lando-pantheon loaded from /snapshot/lando/build/cli/integrations/lando-pantheon/app.js 
lando              10:46:22 DEBUG ==> plugin lando-platformsh loaded from /snapshot/lando/build/cli/integrations/lando-platformsh/app.js 
freesite-amp-theme 10:46:22 DEBUG ==> emitting event pre-init 
freesite-amp-theme 10:46:22 VERBOSE ==> building php service appserver 
lando              10:46:22 ERROR ==> Error: php version 8.0 is not supported
    at new LandoCompose (/Users/tyler.satre/.lando/plugins/lando-core/compose/lando/builder.js:64:17)
    at new LandoAppserver (/Users/tyler.satre/.lando/plugins/lando-core/types/appserver/builder.js:27:7)
    at new LandoPhp (/Users/tyler.satre/.lando/plugins/lando-services/services/php/builder.js:185:7)
    at /Users/tyler.satre/.lando/plugins/lando-services/app.js:55:20
    at arrayEach (/Users/tyler.satre/.lando/node_modules/lodash/lodash.js:516:11)
    at Function.forEach (/Users/tyler.satre/.lando/node_modules/lodash/lodash.js:9368:14)
    at AsyncEvents.<anonymous> (/Users/tyler.satre/.lando/plugins/lando-services/app.js:45:7)
    at AsyncEvents.handle (/snapshot/lando/build/cli/lib/events.js)
    at /snapshot/lando/build/cli/lib/events.js
    at processImmediate (internal/timers.js:439:21)
From previous event:
    at AsyncEvents.emit (/snapshot/lando/build/cli/lib/events.js)
    at /snapshot/lando/build/cli/lib/app.js
From previous event:
    at App.init (/snapshot/lando/build/cli/lib/app.js)
    at /snapshot/lando/build/cli/lib/formatters.js
From previous event:
    at Object.handleInteractive (/snapshot/lando/build/cli/lib/formatters.js)
    at /snapshot/lando/build/cli/lib/cli.js
    at processImmediate (internal/timers.js:439:21)
From previous event:
    at /snapshot/lando/build/cli/lib/cli.js
From previous event:
    at Object.handler (/snapshot/lando/build/cli/lib/cli.js)
    at Object.runCommand (/snapshot/lando/build/cli/node_modules/yargs/lib/command.js:238:44)
    at Object.parseArgs [as _parseArgs] (/snapshot/lando/build/cli/node_modules/yargs/yargs.js:1063:30)
    at Function.get [as argv] (/snapshot/lando/build/cli/node_modules/yargs/yargs.js:1004:21)
    at Cli.init (/snapshot/lando/build/cli/lib/cli.js)
    at Cli.run (/snapshot/lando/build/cli/lib/cli.js)
    at Object.<anonymous> (/snapshot/lando/build/cli/bin/lando.js)
    at Module._compile (pkg/prelude/bootstrap.js:1324:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:993:10)
    at Module.load (internal/modules/cjs/loader.js:813:32)
    at Function.Module._load (internal/modules/cjs/loader.js:725:14)
    at Function.Module.runMain (pkg/prelude/bootstrap.js:1379:12)
    at internal/main/run_main_module.js:17:11 
```

**Comment by tylersatre** [comment]
So it turns out I'm an idiot and had old plugin overrides
