### ISSUE TITLE
Experimental toggle validation order

### ISSUE THREAD

**Issue by rubenvarela** [lando/lando#2979]
If you are not sure how to do that then please complete as much of the below section as possible

**Tell us about your setup**

What is your lando version and operating system? **(note that the older your version the less likely we are to reply)**

Lando v3.1.2 macOS Big Sur

**Tell us about your `.lando.yml`**

Paste in the contents of your `.lando.yml` this is **SUPER HELPFUL** for us.

*Example:*

```yml
name: application
recipe: acquia
config:
  ah_application_uuid:
  ah_site_group:
```

**Tell us about the command you were running**

```bash
lando --experimental
```

**Tell us about the error you got**

*Example:*

```bash
$ lando --experimental
WARN ==> acquia is not a supported recipe type.
Unhandled rejection TypeError: Cannot read property 'builder' of undefined
    at Factory.get (/snapshot/lando/build/cli/lib/factory.js)
    at AsyncEvents.<anonymous> (/snapshot/lando/build/cli/plugins/lando-recipes/app.js)
    at AsyncEvents.handle (/snapshot/lando/build/cli/lib/events.js)
    at /snapshot/lando/build/cli/lib/events.js
    at processImmediate (internal/timers.js:456:21)
From previous event:
    at AsyncEvents.emit (/snapshot/lando/build/cli/lib/events.js)
    at /snapshot/lando/build/cli/lib/app.js
From previous event:
    at App.init (/snapshot/lando/build/cli/lib/app.js)
    at /snapshot/lando/build/cli/bin/lando.js
From previous event:
    at Object.<anonymous> (/snapshot/lando/build/cli/bin/lando.js)
    at Module._compile (pkg/prelude/bootstrap.js:1433:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1156:10)
    at Module.load (internal/modules/cjs/loader.js:984:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)
    at Function.runMain (pkg/prelude/bootstrap.js:1488:12)
    at internal/main/run_main_module.js:17:47
```

**Tell us generally about your bug**

Validation about recipes are done before experimental is toggled. 

There is a workaround of course (changing the recipe while toggling experimental) but it's come up as an issue. 

I believe validation for `--experimental` shouldn't test the recipe.

**Comment by pirog** [comment]
@rubenvarela i can replicate this however we will be moving `acquia` out of experimental in the next release and then we will be overhauling our update/release/distribution system, including how the --experimental flag works. 

For that reason i am going to tag this as wont fix and close.

**Comment by rubenvarela** [comment]
Sounds good! Thank you!
