### ISSUE TITLE
Unhandled rejection TypeError: Cannot create property 'key' on string 'a

### ISSUE THREAD

**Issue by DicksB** [lando/lando#3016]
First installation of Lando 3.1.4 and Docker Desktop on MacOS 11.3.1 (Intel), I'm getting the following error when trying to initialize the "hello" example:

Unhandled rejection TypeError: Cannot create property 'key' on string 'a'
    at /snapshot/lando/build/cli/integrations/lando-acquia/lib/utils.js
    at /snapshot/lando/build/cli/node_modules/lodash/lodash.js:4943:15
    at Function.forEach (/snapshot/lando/build/cli/node_modules/lodash/lodash.js:9410:14)
    at Object.getHostKeys (/snapshot/lando/build/cli/integrations/lando-acquia/lib/utils.js)
    at mergeKeys (/snapshot/lando/build/cli/integrations/lando-acquia/recipes/acquia/init.js)
    at Object.options (/snapshot/lando/build/cli/integrations/lando-acquia/recipes/acquia/init.js)
    at /snapshot/lando/build/cli/plugins/lando-recipes/lib/options.js
    at arrayEach (/snapshot/lando/build/cli/node_modules/lodash/lodash.js:530:11)
    at Function.forEach (/snapshot/lando/build/cli/node_modules/lodash/lodash.js:9410:14)
    at Object.getConfigOptions (/snapshot/lando/build/cli/plugins/lando-recipes/lib/options.js)
    at /snapshot/lando/build/cli/plugins/lando-recipes/tasks/init.js
    at /snapshot/lando/build/cli/lib/lando.js
From previous event:
    at processImmediate (internal/timers.js:456:21)

If I delete Docker Desktop and start over with an installation of Lando 3.1.2, the "hello" example initializes and starts up as expected. If I then stop the application, and upgrade to 3.1.4 again, trying to start it up again results in the same error as above. Downgrading back to 3.1.2 again results in a working application.

**Comment by mikemilano** [comment]
This appears to be an issue with an old ACLI config file on the host system. `~/.acquia/cloud_api.conf`

I'd recommend removing that file and trying again, although updating ACLI on the host may fix the problem as well.

If the credentials in that file are still valid, you may want to copy the key and secret as you will be prompted to enter them again when setting up an Acquia project for the first time in Lando.

**Comment by mikemilano** [comment]
We confirmed removing `~/.acquia/cloud_api.conf` resolved the issue after an attempt to update acli on the host system failed.
