### ISSUE TITLE
Error when trying to initialize with Acquia recipe

### ISSUE THREAD

**Issue by DicksB** [lando/lando#3017]
MacOS 11.3.1
Docker Desktop 3.3.3
Lando 3.1.4

Having corrected my ACLI problem (thanks to Mike Milano), I got my "hello" application up and running under 3.1.4. I then tried initializing a project with the Acquia Cloud recipe:

% lando init --source acquia -v
? Enter an Acquia API key (obfuscated)
? Enter an Acquia API secret [hidden]
lando 09:41:24 ERROR ==> TypeError: Cannot read property 'data' of undefined
    at /snapshot/lando/build/cli/integrations/lando-acquia/lib/api.js
    at processTicksAndRejections (internal/process/task_queues.js:97:5) 

Same error occurs whether initializing an empty directory, or a directory into which I've already cloned a codebase from Acquia Cloud:

% lando init -v --source cwd --recipe acquia
? Enter an Acquia API key (obfuscated)
? Enter an Acquia API secret [hidden]
lando 09:40:00 ERROR ==> TypeError: Cannot read property 'data' of undefined
    at /snapshot/lando/build/cli/integrations/lando-acquia/lib/api.js
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

**Comment by mikemilano** [comment]
We've tracked this down to most likely being a VPN issue. It works outside the VPN.

**Comment by wesleymusgrove** [comment]
I'm getting this too.
![image](https://user-images.githubusercontent.com/1711791/120033694-8cfe4700-bfc1-11eb-971f-2e068e65b20a.png)

I've got a working drupal8 recipe for when I'm on VPN/corporate proxy that requires custom CA certificates to be installed.  Is there a way to specify proxy/CAfile info into `/snapshot/lando/build/cli/integrations/lando-acquia/lib/api.js`?
