### ISSUE TITLE
PostgreSQL version 13 not supported 

### ISSUE THREAD

**Issue by gitressa** [lando/lando#3048]
The documentation says that PostgreSQL 13 is supported (https://docs.lando.dev/config/postgres.html) but I get an error if I try with that version ... Using Lando v3.0.26 on Ubuntu 20.04:

**`.lando.yml` for PostgreSQL 12, works**

```
name: psql12
recipe: lamp

services:
  database:
    type: postgres:12
```
Result:
```
$ lando info
[ { service: 'appserver',
    urls:
     [ 'https://localhost:49296',
       'http://localhost:49297',
       'http://psql12.lndo.site/',
       'https://psql12.lndo.site/' ],
    type: 'php',
    healthy: true,
    via: 'apache',
    webroot: '.',
    config: {},
    version: '7.3',
    meUser: 'www-data',
    hasCerts: true,
    hostnames: [ 'appserver.psql12.internal' ] },
  { service: 'database',
    urls: [],
    type: 'postgres',
    healthy: true,
    internal_connection: { host: 'database', port: '5432' },
    external_connection: { host: '127.0.0.1', port: '49298' },
    healthcheck: 'psql -U postgres -c "\\l"',
    creds: { database: 'lamp', user: 'postgres', password: '' },
    config: {},
    version: '12',
    meUser: 'www-data',
    hasCerts: false,
    hostnames: [ 'database.psql12.internal' ] } ]
```

**`.lando.yml` for PostgreSQL 13, fails**
```
name: psql13
recipe: lamp

services:
  database:
    type: postgres:13
```

Result:
```
$ lando start -v
Unhandled rejection Error: postgres version 13 is not supported
    at new LandoCompose (/snapshot/lando/build/cli/plugins/lando-core/compose/lando/builder.js)
    at new LandoService (/snapshot/lando/build/cli/plugins/lando-core/types/service/builder.js)
    at new LandoPostgres (/snapshot/lando/build/cli/plugins/lando-services/services/postgres/builder.js)
    at /snapshot/lando/build/cli/plugins/lando-services/app.js
    at arrayEach (/snapshot/lando/build/cli/node_modules/lodash/lodash.js:516:11)
    at Function.forEach (/snapshot/lando/build/cli/node_modules/lodash/lodash.js:9368:14)
    at AsyncEvents.<anonymous> (/snapshot/lando/build/cli/plugins/lando-services/app.js)
    at AsyncEvents.handle (/snapshot/lando/build/cli/lib/events.js)
    at /snapshot/lando/build/cli/lib/events.js
From previous event:
    at AsyncEvents.emit (/snapshot/lando/build/cli/lib/events.js)
    at /snapshot/lando/build/cli/lib/app.js
From previous event:
    at App.init (/snapshot/lando/build/cli/lib/app.js)
    at /snapshot/lando/build/cli/bin/lando.js
From previous event:
    at Object.<anonymous> (/snapshot/lando/build/cli/bin/lando.js)
    at Module._compile (pkg/prelude/bootstrap.js:1324:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:993:10)
    at Module.load (internal/modules/cjs/loader.js:813:32)
    at Function.Module._load (internal/modules/cjs/loader.js:725:14)
    at Function.Module.runMain (pkg/prelude/bootstrap.js:1379:12)
    at internal/main/run_main_module.js:17:11
```

**Comment by vaggelis-net** [comment]
Support for version 13 added in Lando 3.1.3 according to this [link](https://github.com/lando/lando/releases/tag/v3.1.3)

**Comment by gitressa** [comment]
Thanks @vaggelis-net. I am using the latest official release (`3.0.26`) so that explains it, since PostgreSQL 13 support was merged into the `Pre-release` 3.1 branch. The documentation is just a little bit ahead of the latest official release :-)

**Comment by gitressa** [comment]
Scratch that. The "Latest" release on the project page (https://github.com/lando/lando) is `3.0.26`:
### Releases 133
**v3.0.26** _Latest_
`on 23 Feb`
`+132 releases `

But using the recommended method of installation gives you Lando 3.1.4:
```
$ wget https://files.devwithlando.io/lando-stable.deb
$ dpkg --info lando-stable.deb
 new Debian package, version 2.0.
 size 34485064 bytes: control archive=1714 bytes.
     296 bytes,    12 lines      control              
     588 bytes,     9 lines      md5sums              
    1697 bytes,    60 lines   *  postinst             #!/bin/bash
     183 bytes,    13 lines   *  postrm               #!/bin/bash
      13 bytes,     2 lines   *  preinst              #!/bin/bash
      13 bytes,     2 lines   *  prerm                #!/bin/bash
 Package: lando
 Version: 3.1.4
[...]
```

**Comment by vaggelis-net** [comment]
So on what version you are now? If the stable links serve the latest pre-release, this can be an issue on it's own.

**Comment by gitressa** [comment]
I tried with Lando 3.1.4 and PostgreSQL 13 was supported.

And yes, it would be great if `wget https://files.devwithlando.io/lando-stable.deb` and the "Stable" version on the [Releases](https://github.com/lando/lando/releases) page were synchronized.

**Comment by gitressa** [comment]
I created #3049.

**Comment by djassie** [comment]
Working formula, showing Drupal as example. 

```yaml
name: dpr
recipe: drupal8
config:
  webroot: web
  php: '7.4'
  composer_version: '1.10.22'
  xdebug: false
  database: postgres:13
```

For Database CLI

```sh
lando psql
\l
```
