### ISSUE TITLE
Running Lando in CI

### ISSUE THREAD

**Issue by kerasai** [lando/lando#3085]
It struck me the other day, instead of "building the stack" in my CI environment (Github Actions, CircleCI, Gitlab, etc), can I just install Lando? Turns out the answer is yes, and it make it super simple to run functional (Behat) and visual regression testing w/a functioning Drupal site.

Unfortunately it's a bit slow to install docker and Lando, then spin up the Lando site. Any guidance on speeding this up?

A couple ideas I've had:

* Get docker and Lando installed on an image and use that image for the CI runner
  * My initial attempt failed, but I think this will work after some debugging
  * Would it be possible to "prime" this image so its Lando already has its images
    * Downside, the resulting image will probably be _huge_... Is this an issue?
* Somehow obtain Lando's `docker-compose` handling, and use docker-compose directly w/o Lando
  * I've poked thru the `~/.lando` dir, but it wasn't super obvious on initial glance how it's all wired together
  * A couple related things that I've found:
    * https://github.com/lando/lando/issues/385
    * https://github.com/lando/lando/issues/1039

I'm super interested to hear if anyone is doing this, and what ideas/tips you all may have.

**Comment by agarzola** [comment]
@kerasai I’m curious whether you’ve had any progress re:
>Somehow obtain Lando’s `docker-compose` handling, and use docker-compose directly w/o Lando

I’m interested in this as a starting point for a GitHub Codespace setup for a project that is already using Lando.

**Comment by davereid-pfg** [comment]
I'm also trying to use Lando within our Github action, has anyone had any luck or instructions on how to make this work?

**Comment by labboy0276** [comment]
@davereid-pfg if you look at the tests for lando itself, you can see how we do it:

https://github.com/lando/php/blob/main/.github/workflows/pr-php7-tests.yml for example

**Comment by davereid-pfg** [comment]
@labboy0276 I'm encountering issues doing the actual `lando start` within a standard Github action container.

```
usermod: no changes
usermod: no changes
ERROR ==>  message=, stack=Error
    at /snapshot/cli/lib/shell.js
From previous event:
    at Shell.sh (/snapshot/cli/lib/shell.js)
    at Object.dc (/snapshot/cli/lib/bootstrap.js)
    at compose (/snapshot/cli/lib/bootstrap.js)
From previous event:
    at /snapshot/cli/lib/router.js
    at processImmediate (internal/timers.js:464:21)
From previous event:
    at Object.run (/snapshot/cli/lib/router.js)
    at run (/snapshot/cli/lib/engine.js)
    at /snapshot/cli/lib/router.js
From previous event:
    at Object.eventWrapper (/snapshot/cli/lib/router.js)
    at Engine.engineCmd (/snapshot/cli/lib/engine.js)
    at Engine.run (/snapshot/cli/lib/engine.js)
    at AsyncEvents.<anonymous> (/snapshot/cli/plugins/lando-events/app.js)
    at AsyncEvents.handle (/snapshot/cli/lib/events.js)
    at /snapshot/cli/lib/events.js
From previous event:
    at AsyncEvents.emit (/snapshot/cli/lib/events.js)
    at /snapshot/cli/lib/app.js
From previous event:
    at App.start (/snapshot/cli/lib/app.js)
    at Object.run (/snapshot/cli/plugins/lando-core/tasks/start.js)
    at /snapshot/cli/lib/cli.js
    at processImmediate (internal/timers.js:464:21)
From previous event:
    at /snapshot/cli/lib/cli.js
From previous event:
    at Object.handler (/snapshot/cli/lib/cli.js)
    at Object.runCommand (/snapshot/cli/node_modules/yargs/lib/command.js:238:44)
    at Object.parseArgs [as _parseArgs] (/snapshot/cli/node_modules/yargs/yargs.js:1063:30)
    at Function.get [as argv] (/snapshot/cli/node_modules/yargs/yargs.js:1004:21)
    at Cli.init (/snapshot/cli/lib/cli.js)
    at Cli.run (/snapshot/cli/lib/cli.js)
From previous event:
    at /snapshot/cli/bin/lando.js
From previous event:
    at Object.<anonymous> (/snapshot/cli/bin/lando.js)
    at Module._compile (pkg/prelude/bootstrap.js:1751:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Function.runMain (pkg/prelude/bootstrap.js:1804:12)
    at internal/main/run_main_module.js:17:47, __stackCleaned__=true

  _      __              _           __
 | | /| / /__ ________  (_)__  ___ _/ /
 | |/ |/ / _ `/ __/ _ \/ / _ \/ _ `/_/ 
 |__/|__/\_,_/_/ /_//_/_/_//_/\_, (_)  
                             /___/     

Your app started up but we detected some things you may wish to investigate.
These only may be a problem.


 ■ One of your events failed
   This **MAY** prevent your app from working.
   Check for errors above, fix them in your Landofile, and run the command again:
   


Here are some vitals:

 NAME                  mysite                               
 LOCATION              /home/runner/work/mysite/mysite            
 SERVICES              appserver_nginx, appserver, database, chrome 
 APPSERVER_NGINX URLS  https://localhost:49155                      
                       http://localhost:49156                       
                       http://mysite.lndo.site/             
                       https://mysite.lndo.site/            
```

**Comment by labboy0276** [comment]
@davereid-pfg awesome

**Comment by Crell** [comment]
I have a detailed writeup of how we're using Lando in GHA here:

https://peakd.com/php/@crell/running-lando-on-github-actions-rnq6q0

**Comment by reynoldsalec** [comment]
Probably the best way to use Lando in GitHub Actions (and CircleCI) is to use the official `setup-lando` action that Lando uses across all of its internal tests: https://github.com/lando/setup-lando

GHA instructions: https://docs.lando.dev/install/gha.html
GHA example: https://github.com/lando/drupal/blob/7099181dd34ed39f5d6aabd62518d93d49ef47c5/.github/workflows/pr-drupal-tests.yml#L55-L62

CircleCI Instructions: https://docs.lando.dev/install/circleci.html

For all other CI platforms, I'd recommend reading the most up-to-date install instructions for Linux: https://docs.lando.dev/install/linux.html

If you're interested in running simple command line tests as functional tests of your Lando environment, check out [Leia](https://github.com/lando/leia). Essentially every Lando repo uses that for testing; look at [how the workflows use Leia](https://github.com/lando/drupal/blob/7099181dd34ed39f5d6aabd62518d93d49ef47c5/.github/workflows/pr-drupal-tests.yml#L63-L69), and the [examples directory](https://github.com/lando/drupal/tree/main/examples) to see how Leia reads tests from the provided [README.md files](https://github.com/lando/drupal/blob/main/examples/drupal10/README.md).

This seems like a good guide topic; Lando has really good resources for running in CI, but I don't think there's a comprehensive guide that puts all of it together in one place.
