### ISSUE TITLE
Proxy fallback ports not working

### ISSUE THREAD

**Issue by hades200082** [lando/lando#3123]
Ref: https://github.com/lando/lando/issues/1360

I have this exact same issue on Windows. 

This used to work pre 3.1.4 but since updating to 3.1.4 or 3.3.0 it no longer falls back to the fallback ports if 80/443 are in use.

**Tell us about your setup**
Lando version 3.3.0
Windows 10 Pro

**Tell us about your `.lando.yml`**

```
name: mysite
recipe: pantheon
config:
  framework: wordpress
  site: removed
  id: removed
```

**Tell us about the command you were running**

```bash
lando start
```

**Tell us about the error you got**

```
lando 08:23:05 DEBUG ==> No update available.
lando 08:23:05 VERBOSE ==> starting bootstrap at level app...
lando 08:23:05 VERBOSE ==> config bootstrap beginning...
lando 08:23:05 DEBUG ==> emitting event pre-bootstrap-config
lando 08:23:05 DEBUG ==> plugin lando-core loaded from C:/snapshot/cli/plugins/lando-core/index.js
lando 08:23:05 DEBUG ==> plugin lando-events loaded from C:/snapshot/cli/plugins/lando-events/index.js
lando 08:23:05 DEBUG ==> plugin lando-networking loaded from C:/snapshot/cli/plugins/lando-networking/index.js
lando 08:23:05 DEBUG ==> plugin lando-proxy loaded from C:/snapshot/cli/plugins/lando-proxy/index.js
lando 08:23:05 DEBUG ==> plugin lando-recipes loaded from C:/snapshot/cli/plugins/lando-recipes/index.js
lando 08:23:05 DEBUG ==> plugin lando-services loaded from C:/snapshot/cli/plugins/lando-services/index.js
lando 08:23:05 DEBUG ==> plugin lando-sharing loaded from C:/snapshot/cli/plugins/lando-sharing/index.js
lando 08:23:05 DEBUG ==> plugin lando-test loaded from C:/snapshot/cli/plugins/lando-test/index.js
lando 08:23:05 DEBUG ==> plugin lando-tooling loaded from C:/snapshot/cli/plugins/lando-tooling/index.js
lando 08:23:05 DEBUG ==> plugin lando-acquia loaded from C:/snapshot/cli/integrations/lando-acquia/index.js
lando 08:23:05 DEBUG ==> plugin lando-lagoon loaded from C:/snapshot/cli/integrations/lando-lagoon/index.js
lando 08:23:05 DEBUG ==> plugin lando-pantheon loaded from C:/snapshot/cli/integrations/lando-pantheon/index.js
lando 08:23:05 DEBUG ==> plugin lando-platformsh loaded from C:/snapshot/cli/integrations/lando-platformsh/index.js
lando 08:23:05 DEBUG ==> emitting event post-bootstrap-config
lando 08:23:05 VERBOSE ==> building proxy config...
lando 08:23:05 VERBOSE ==> config bootstrap completed.
lando 08:23:05 VERBOSE ==> tasks bootstrap beginning...
lando 08:23:05 DEBUG ==> emitting event pre-bootstrap-tasks
lando 08:23:05 DEBUG ==> autoloaded task config
lando 08:23:05 DEBUG ==> autoloaded task destroy
lando 08:23:05 DEBUG ==> autoloaded task info
lando 08:23:05 DEBUG ==> autoloaded task list
lando 08:23:05 DEBUG ==> autoloaded task logs
lando 08:23:05 DEBUG ==> autoloaded task poweroff
lando 08:23:05 DEBUG ==> autoloaded task rebuild
lando 08:23:05 DEBUG ==> autoloaded task restart
lando 08:23:05 DEBUG ==> autoloaded task share
lando 08:23:05 DEBUG ==> autoloaded task start
lando 08:23:05 DEBUG ==> autoloaded task stop
lando 08:23:05 DEBUG ==> autoloaded task version
lando 08:23:05 DEBUG ==> autoloaded task init
lando 08:23:05 DEBUG ==> autoloaded task ssh
lando 08:23:05 DEBUG ==> emitting event post-bootstrap-tasks
lando 08:23:05 VERBOSE ==> tasks bootstrap completed.
lando 08:23:05 VERBOSE ==> engine bootstrap beginning...
lando 08:23:05 DEBUG ==> emitting event pre-bootstrap-engine
lando 08:23:05 DEBUG ==> automoved scripts from C:\snapshot\cli\plugins\lando-core\scripts to C:\Users\lee20\.lando\scripts and set to mode 755
lando 08:23:05 DEBUG ==> automoved scripts from C:\snapshot\cli\plugins\lando-proxy\scripts to C:\Users\lee20\.lando\scripts and set to mode 755
lando 08:23:05 DEBUG ==> automoved scripts from C:\snapshot\cli\plugins\lando-recipes\scripts to C:\Users\lee20\.lando\scripts and set to mode 755
lando 08:23:05 DEBUG ==> automoved scripts from C:\snapshot\cli\plugins\lando-services\scripts to C:\Users\lee20\.lando\scripts and set to mode 755
lando 08:23:05 DEBUG ==> automoved scripts from C:\snapshot\cli\plugins\lando-sharing\scripts to C:\Users\lee20\.lando\scripts and set to mode 755
lando 08:23:05 DEBUG ==> automoved scripts from C:\snapshot\cli\integrations\lando-acquia\scripts to C:\Users\lee20\.lando\scripts and set to mode 755
lando 08:23:05 DEBUG ==> automoved scripts from C:\snapshot\cli\integrations\lando-lagoon\scripts to C:\Users\lee20\.lando\scripts and set to mode 755
lando 08:23:05 DEBUG ==> automoved scripts from C:\snapshot\cli\integrations\lando-pantheon\scripts to C:\Users\lee20\.lando\scripts and set to mode 755
lando 08:23:05 DEBUG ==> automoved scripts from C:\snapshot\cli\integrations\lando-platformsh\scripts to C:\Users\lee20\.lando\scripts and set to mode 755
lando 08:23:05 DEBUG ==> emitting event post-bootstrap-engine
lando 08:23:05 VERBOSE ==> engine bootstrap completed.
lando 08:23:05 VERBOSE ==> app bootstrap beginning...
lando 08:23:05 DEBUG ==> emitting event pre-bootstrap-app
lando 08:23:05 DEBUG ==> autoloaded builder LandoCompose
lando 08:23:05 DEBUG ==> autoloaded builder LandoAppserver
lando 08:23:05 DEBUG ==> autoloaded builder LandoService
lando 08:23:05 DEBUG ==> autoloaded builder LandoUtility
lando 08:23:05 DEBUG ==> autoloaded builder LandoWebServer
lando 08:23:05 DEBUG ==> autoloaded builder LandoDrupal
lando 08:23:05 DEBUG ==> autoloaded builder LandoLaemp
lando 08:23:05 DEBUG ==> autoloaded builder LandoAppserver
lando 08:23:05 DEBUG ==> autoloaded builder LandoPlatformAppserver
lando 08:23:05 DEBUG ==> autoloaded builder LandoPlatformService
lando 08:23:05 DEBUG ==> autoloaded builder LandoCa
lando 08:23:05 DEBUG ==> autoloaded builder LandoProxy
lando 08:23:05 DEBUG ==> autoloaded builder LandoInit
lando 08:23:05 DEBUG ==> autoloaded builder LandoApache
lando 08:23:05 DEBUG ==> autoloaded builder LandoCompose
lando 08:23:05 DEBUG ==> autoloaded builder LandoDotNet
lando 08:23:05 DEBUG ==> autoloaded builder LandoElasticSearch
lando 08:23:05 DEBUG ==> autoloaded builder LandoGo
lando 08:23:05 DEBUG ==> autoloaded builder LandoMailHog
lando 08:23:05 DEBUG ==> autoloaded builder LandoMariaDb
lando 08:23:05 DEBUG ==> autoloaded builder LandoMemcached
lando 08:23:05 DEBUG ==> autoloaded builder LandoMongoDb
lando 08:23:05 DEBUG ==> autoloaded builder LandoMsSql
lando 08:23:05 DEBUG ==> autoloaded builder LandoMySql
lando 08:23:05 DEBUG ==> autoloaded builder LandoNginx
lando 08:23:05 DEBUG ==> autoloaded builder LandoNode
lando 08:23:05 DEBUG ==> autoloaded builder LandoPhp
lando 08:23:05 DEBUG ==> autoloaded builder LandoPma
lando 08:23:05 DEBUG ==> autoloaded builder LandoPostgres
lando 08:23:05 DEBUG ==> autoloaded builder LandoPython
lando 08:23:05 DEBUG ==> autoloaded builder LandoRedis
lando 08:23:05 DEBUG ==> autoloaded builder LandoRuby
lando 08:23:05 DEBUG ==> autoloaded builder LandoSolr
lando 08:23:05 DEBUG ==> autoloaded builder LandoTomcat
lando 08:23:05 DEBUG ==> autoloaded builder LandoVarnish
lando 08:23:05 DEBUG ==> autoloaded builder LandoMounter
lando 08:23:05 DEBUG ==> autoloaded builder LandoLagoonElasticsearch
lando 08:23:05 DEBUG ==> autoloaded builder LandoLagoonMariaDb
lando 08:23:05 DEBUG ==> autoloaded builder LandoLagoonNginx
lando 08:23:05 DEBUG ==> autoloaded builder LandoLagoonNone
lando 08:23:05 DEBUG ==> autoloaded builder LandoLagoonPhp
lando 08:23:05 DEBUG ==> autoloaded builder LandoLagoonPhp
lando 08:23:05 DEBUG ==> autoloaded builder LandoLagoonPostgres
lando 08:23:05 DEBUG ==> autoloaded builder LandoLagoonRedis
lando 08:23:05 DEBUG ==> autoloaded builder LandoLagoonSolr
lando 08:23:05 DEBUG ==> autoloaded builder LandoLagoonVarnish
lando 08:23:05 DEBUG ==> autoloaded builder LandoPlatformshChromeHeadless
lando 08:23:05 DEBUG ==> autoloaded builder LandoPlatformsElasticsearch
lando 08:23:05 DEBUG ==> autoloaded builder LandoPlatformshInfluxdb
lando 08:23:05 DEBUG ==> autoloaded builder LandoPlatformshKafka
lando 08:23:05 DEBUG ==> autoloaded builder LandoPlatformshMariaDB
lando 08:23:05 DEBUG ==> autoloaded builder LandoPlatformshMemcached
lando 08:23:05 DEBUG ==> autoloaded builder LandoPlatformsMongoDB
lando 08:23:05 DEBUG ==> autoloaded builder LandoPlatformshPhp
lando 08:23:05 DEBUG ==> autoloaded builder LandoPlatformshPostgres
lando 08:23:05 DEBUG ==> autoloaded builder LandoPlatformshRabbitmq
lando 08:23:05 DEBUG ==> autoloaded builder LandoPlatformshRedis
lando 08:23:05 DEBUG ==> autoloaded builder LandoPlatformshSolr
lando 08:23:05 DEBUG ==> autoloaded builder LandoPlatformshVarnish
lando 08:23:05 DEBUG ==> autoloaded builder LandoBackdrop
lando 08:23:05 DEBUG ==> autoloaded builder LandoDrupal6
lando 08:23:05 DEBUG ==> autoloaded builder LandoDrupal7
lando 08:23:05 DEBUG ==> autoloaded builder LandoDrupal8
lando 08:23:05 DEBUG ==> autoloaded builder LandoDrupal9
lando 08:23:05 DEBUG ==> autoloaded builder LandoJoomla
lando 08:23:05 DEBUG ==> autoloaded builder LandoLamp
lando 08:23:05 DEBUG ==> autoloaded builder LandoLaravel
lando 08:23:05 DEBUG ==> autoloaded builder LandoLamp
lando 08:23:05 DEBUG ==> autoloaded builder LandoMean
lando 08:23:05 DEBUG ==> autoloaded builder LandoSymfony
lando 08:23:05 DEBUG ==> autoloaded builder LandoWordPress
lando 08:23:05 DEBUG ==> autoloaded builder LandoAcquia
lando 08:23:05 DEBUG ==> autoloaded builder LandoLagoon
lando 08:23:05 DEBUG ==> autoloaded builder LandoPantheon
lando 08:23:05 DEBUG ==> autoloaded builder LandoPlatformsh
lando 08:23:05 DEBUG ==> emitting event post-bootstrap-app
lando 08:23:05 VERBOSE ==> app bootstrap completed.
lando 08:23:05 VERBOSE ==> bootstrap completed.
lando 08:23:05 DEBUG ==> emitting event post-bootstrap
lando 08:23:05 VERBOSE ==> docker-engine exists: true
lando 08:23:05 VERBOSE ==> docker-compose exists: true
lando 08:23:05 DEBUG ==> emitting event cli-answers
lando 08:23:05 VERBOSE ==> checking docker version compatibility...
lando 08:23:05 DEBUG ==> compatibility results name=desktop, link=https://docs.docker.com/docker-for-windows/release-notes/, wants=2.1.0.0 - 3.6.99, version=4.0.0, semversion=4.0.0, semmin=2.1.0, semmax=3.6.99, dockerVersion=true, s
atisfied=false
lando 08:23:05 DEBUG ==> emitting event cli-start-answers
lando 08:23:05 DEBUG ==> emitting event cli-run
lando 08:23:05 DEBUG ==> emitting event cli-start-run
lando 08:23:05 INFO ==> loading app lodders from config files 0=E:\Projects\Distinction\lodders\.lando.yml
lando 08:23:05 DEBUG ==> app lodders has config name=lodders, recipe=pantheon, framework=wordpress, site=lodders, id=755a8638-4517-4117-bc96-17a07710dd70
Let's get this party started! Starting app lodders...
lodders 08:23:05 INFO ==> starting app...
lodders 08:23:05 VERBOSE ==> initiatilizing app at E:\Projects\Distinction\lodders...
lando   08:23:05 DEBUG ==> plugin lando-core loaded from C:\snapshot\cli\plugins\lando-core\app.js
lando   08:23:05 DEBUG ==> plugin lando-events loaded from C:\snapshot\cli\plugins\lando-events\app.js
lando   08:23:05 DEBUG ==> plugin lando-networking loaded from C:\snapshot\cli\plugins\lando-networking\app.js
lodders 08:23:05 VERBOSE ==> proxy settings detected.
lando   08:23:05 DEBUG ==> plugin lando-proxy loaded from C:\snapshot\cli\plugins\lando-proxy\app.js
lando   08:23:05 DEBUG ==> plugin lando-recipes loaded from C:\snapshot\cli\plugins\lando-recipes\app.js
lando   08:23:05 DEBUG ==> plugin lando-services loaded from C:\snapshot\cli\plugins\lando-services\app.js
lando   08:23:05 DEBUG ==> plugin lando-sharing loaded from C:\snapshot\cli\plugins\lando-sharing\app.js
lando   08:23:05 DEBUG ==> plugin lando-tooling loaded from C:\snapshot\cli\plugins\lando-tooling\app.js
lando   08:23:05 DEBUG ==> plugin lando-acquia loaded from C:\snapshot\cli\integrations\lando-acquia\app.js
lando   08:23:05 DEBUG ==> plugin lando-lagoon loaded from C:\snapshot\cli\integrations\lando-lagoon\app.js
lando   08:23:05 DEBUG ==> plugin lando-pantheon loaded from C:\snapshot\cli\integrations\lando-pantheon\app.js
lando   08:23:05 DEBUG ==> plugin lando-platformsh loaded from C:\snapshot\cli\integrations\lando-platformsh\app.js
lodders 08:23:05 DEBUG ==> emitting event pre-init
lodders 08:23:05 VERBOSE ==> building pantheon recipe named
lando   08:23:05 VERBOSE ==> proxy is ON.
lando   08:23:05 VERBOSE ==> Setting the default proxy certificate /certs/cert.crt
lodders 08:23:05 VERBOSE ==> building php service appserver
lodders 08:23:05 VERBOSE ==> building mariadb service database
lodders 08:23:05 VERBOSE ==> building redis service cache
lodders 08:23:05 VERBOSE ==> building varnish service edge
lodders 08:23:05 VERBOSE ==> building solr service index
lodders 08:23:05 DEBUG ==> emitting event post-init
lodders 08:23:05 DEBUG ==> adding hostnames to the app...
lodders 08:23:05 DEBUG ==> hostnames added to appserver_nginx 0=appserver_nginx.lodders.internal
lodders 08:23:05 DEBUG ==> hostnames added to appserver 0=appserver.lodders.internal
lodders 08:23:05 DEBUG ==> hostnames added to database 0=database.lodders.internal
lodders 08:23:05 DEBUG ==> hostnames added to cache 0=cache.lodders.internal
lodders 08:23:05 DEBUG ==> hostnames added to edge_ssl 0=edge_ssl.lodders.internal
lodders 08:23:05 DEBUG ==> hostnames added to edge 0=edge.lodders.internal
lodders 08:23:05 DEBUG ==> hostnames added to index 0=index.lodders.internal
lodders 08:23:05 VERBOSE ==> attempting to find open services...
lando   08:23:06 DEBUG ==> engine is up.
lando   08:23:06 DEBUG ==> docker is running.
lodders 08:23:06 DEBUG ==> engine is up.
lodders 08:23:06 VERBOSE ==> refreshing certificates... 0=appserver_nginx, 1=appserver, 2=database, 3=cache, 4=edge_ssl, 5=edge, 6=index
lodders 08:23:06 VERBOSE ==> perm sweeping flagged non-root containers ... 0=database
lodders 08:23:06 VERBOSE ==> analyzing user ssh keys... using 6 of 6
lodders 08:23:06 DEBUG ==> key config...  none
lodders 08:23:06 VERBOSE ==> additional tooling detected
lodders 08:23:06 DEBUG ==> adding app cli task composer
lodders 08:23:06 DEBUG ==> adding app cli task db-import <file>
lodders 08:23:06 DEBUG ==> adding app cli task db-export [file]
lodders 08:23:06 DEBUG ==> adding app cli task php
lodders 08:23:06 DEBUG ==> adding app cli task mysql
lodders 08:23:06 DEBUG ==> adding app cli task terminus
lodders 08:23:06 DEBUG ==> adding app cli task redis-cli
lodders 08:23:06 DEBUG ==> adding app cli task varnishadm
lodders 08:23:06 DEBUG ==> adding app cli task pull
lodders 08:23:06 DEBUG ==> adding app cli task push
lodders 08:23:06 DEBUG ==> adding app cli task switch
lodders 08:23:06 DEBUG ==> adding app cli task wp
lodders 08:23:06 VERBOSE ==> setting LANDO_INFO...
lodders 08:23:06 DEBUG ==> ensuring exposed ports on appserver_nginx are bound to 127.0.0.1
lodders 08:23:06 DEBUG ==> ensuring exposed ports on appserver_nginx are bound to 127.0.0.1
lodders 08:23:06 DEBUG ==> ensuring exposed ports on database are bound to 127.0.0.1
lodders 08:23:06 DEBUG ==> ensuring exposed ports on cache are bound to 127.0.0.1
lodders 08:23:06 DEBUG ==> ensuring exposed ports on edge_ssl are bound to 127.0.0.1
lodders 08:23:06 DEBUG ==> ensuring exposed ports on edge are bound to 127.0.0.1
lodders 08:23:06 DEBUG ==> ensuring exposed ports on index are bound to 127.0.0.1
lodders 08:23:06 VERBOSE ==> app is ready!
lodders 08:23:06 DEBUG ==> emitting event ready
lodders 08:23:06 VERBOSE ==> discovering dynamic portforward info...
lodders 08:23:06 VERBOSE ==> reporting start action to report=true, url=https://metrics.lando.dev, report=true, url=https://metrics.lando.dev
lodders 08:23:06 DEBUG ==> reported data command=lando start, context=local, devMode=false, instance=9097e410c8a3c7bd7db65ba8b7e24064733e4bc2, nodeVersion=v14.17.2, mode=cli, type=Windows_NT, platform=win32, release=10.0.19043, arch
=x64, product=lando, version=3.3.0, app=926fcb551a7368018fe47150ef1601051f97cdba, type=pantheon, services=[php:7.3, mariadb:10.1, redis:2.8, varnish:4.1, solr:custom], action=start, created=2021-09-02T07:23:06.392Z
lodders 08:23:06 DEBUG ==> emitting event pre-start
lando   08:23:06 VERBOSE ==> about to scan urls
lando   08:23:06 DEBUG ==> scanning data urls=[http://127.0.0.1:80, http://127.0.0.1:8000, http://127.0.0.1:8080, http://127.0.0.1:8888, http://127.0.0.1:8008], max=1, waitCodes=[]
lando   08:23:06 VERBOSE ==> about to scan urls
lando   08:23:06 DEBUG ==> scanning data urls=[https://127.0.0.1:443, https://127.0.0.1:444, https://127.0.0.1:4433, https://127.0.0.1:4444, https://127.0.0.1:4443], max=1, waitCodes=[]
lando   08:23:06 DEBUG ==> checking to see if http://127.0.0.1:80 is ready.
lando   08:23:06 DEBUG ==> checking to see if http://127.0.0.1:8000 is ready.
lando   08:23:06 DEBUG ==> checking to see if http://127.0.0.1:8080 is ready.
lando   08:23:06 DEBUG ==> checking to see if http://127.0.0.1:8888 is ready.
lando   08:23:06 DEBUG ==> checking to see if http://127.0.0.1:8008 is ready.
lando   08:23:06 DEBUG ==> checking to see if https://127.0.0.1:443 is ready.
lando   08:23:06 DEBUG ==> checking to see if https://127.0.0.1:444 is ready.
lando   08:23:06 DEBUG ==> checking to see if https://127.0.0.1:4433 is ready.
lando   08:23:06 DEBUG ==> checking to see if https://127.0.0.1:4444 is ready.
lando   08:23:06 DEBUG ==> checking to see if https://127.0.0.1:4443 is ready.
lando   08:23:06 DEBUG ==> http://127.0.0.1:80 is ready
lando   08:23:06 DEBUG ==> checking to see if http://127.0.0.1:8000 is ready.
lando   08:23:06 DEBUG ==> checking to see if http://127.0.0.1:8080 is ready.
lando   08:23:06 DEBUG ==> checking to see if http://127.0.0.1:8888 is ready.
lando   08:23:06 DEBUG ==> checking to see if http://127.0.0.1:8008 is ready.
lando   08:23:06 DEBUG ==> checking to see if https://127.0.0.1:444 is ready.
lando   08:23:06 DEBUG ==> checking to see if https://127.0.0.1:4433 is ready.
lando   08:23:06 DEBUG ==> checking to see if https://127.0.0.1:4444 is ready.
lando   08:23:06 DEBUG ==> checking to see if https://127.0.0.1:4443 is ready.
lando   08:23:06 DEBUG ==> checking to see if https://127.0.0.1:443 is ready.
lando   08:23:06 DEBUG ==> http://127.0.0.1:8000 not currently accessible
lando   08:23:06 DEBUG ==> http://127.0.0.1:8080 not currently accessible
lando   08:23:06 DEBUG ==> http://127.0.0.1:8888 not currently accessible
lando   08:23:06 DEBUG ==> http://127.0.0.1:8008 not currently accessible
lando   08:23:06 DEBUG ==> https://127.0.0.1:444 not currently accessible
lando   08:23:06 DEBUG ==> https://127.0.0.1:4433 not currently accessible
lando   08:23:06 DEBUG ==> https://127.0.0.1:4444 not currently accessible
lando   08:23:06 DEBUG ==> https://127.0.0.1:4443 not currently accessible
lando   08:23:06 VERBOSE ==> scan completed.
lando   08:23:06 DEBUG ==> scan results. url=http://127.0.0.1:80, status=true, color=green, url=http://127.0.0.1:8000, status=false, color=red, url=http://127.0.0.1:8080, status=false, color=red, url=http://127.0.0.1:8888, status=fa
lse, color=red, url=http://127.0.0.1:8008, status=false, color=red
lando   08:23:06 DEBUG ==> https://127.0.0.1:443 not currently accessible
lando   08:23:06 VERBOSE ==> scan completed.
lando   08:23:06 DEBUG ==> scan results. url=https://127.0.0.1:443, status=false, color=red, url=https://127.0.0.1:444, status=false, color=red, url=https://127.0.0.1:4433, status=false, color=red, url=https://127.0.0.1:4444, status
=false, color=red, url=https://127.0.0.1:4443, status=false, color=red
lando   08:23:06 DEBUG ==> process pid3 running C:\Program Files\Docker\Docker\resources\bin\docker-compose-v1.exe up cstdio=inherit, silent=false, mode=spawn, detached=false
Starting landoproxyhyperion5000gandalfedition_proxy_1 ... error

ERROR: for landoproxyhyperion5000gandalfedition_proxy_1  Cannot start service proxy: Ports are not available: listen tcp 127.0.0.1:443: bind: An attempt was made to access a socket in a way forbidden by its access permissions.

ERROR: for proxy  Cannot start service proxy: Ports are not available: listen tcp 127.0.0.1:443: bind: An attempt was made to access a socket in a way forbidden by its access permissions.
ERROR: Encountered errors while bringing up the project.
lando   08:23:07 DEBUG ==> process pid3 finished with exit code 1
lodders 08:23:07 ERROR ==>  message=, stack=Error
    at C:\snapshot\cli\lib\shell.js
From previous event:
    at Shell.sh (C:\snapshot\cli\lib\shell.js)
    at Object.dc (C:\snapshot\cli\lib\bootstrap.js)
    at compose (C:\snapshot\cli\lib\bootstrap.js)
    at C:\snapshot\cli\lib\router.js
    at C:\snapshot\cli\lib\router.js
    at processImmediate (internal/timers.js:464:21)
From previous event:
    at retryEach (C:\snapshot\cli\lib\router.js)
    at Object.start (C:\snapshot\cli\lib\router.js)
    at C:\snapshot\cli\lib\engine.js
    at C:\snapshot\cli\lib\router.js
From previous event:
    at Object.eventWrapper (C:\snapshot\cli\lib\router.js)
    at Engine.engineCmd (C:\snapshot\cli\lib\engine.js)
    at Engine.start (C:\snapshot\cli\lib\engine.js)
    at C:\snapshot\cli\plugins\lando-proxy\app.js
From previous event:
    at AsyncEvents.<anonymous> (C:\snapshot\cli\plugins\lando-proxy\app.js)
    at AsyncEvents.handle (C:\snapshot\cli\lib\events.js)
    at C:\snapshot\cli\lib\events.js
    at processImmediate (internal/timers.js:464:21)
From previous event:
    at AsyncEvents.emit (C:\snapshot\cli\lib\events.js)
    at C:\snapshot\cli\lib\app.js
From previous event:
    at App.start (C:\snapshot\cli\lib\app.js)
    at Object.run (C:\snapshot\cli\plugins\lando-core\tasks\start.js)
From previous event:
    at C:\snapshot\cli\lib\cli.js
From previous event:
    at Object.handler (C:\snapshot\cli\lib\cli.js)
    at Object.runCommand (C:\snapshot\cli\node_modules\yargs\lib\command.js:238:44)
    at Object.parseArgs [as _parseArgs] (C:\snapshot\cli\node_modules\yargs\yargs.js:1063:30)
    at Function.get [as argv] (C:\snapshot\cli\node_modules\yargs\yargs.js:1004:21)
    at Cli.init (C:\snapshot\cli\lib\cli.js)
    at Cli.run (C:\snapshot\cli\lib\cli.js)
    at Object.<anonymous> (C:\snapshot\cli\bin\lando.js)
    at Module._compile (pkg/prelude/bootstrap.js:1751:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Function.runMain (pkg/prelude/bootstrap.js:1804:12)
    at internal/main/run_main_module.js:17:47, __stackCleaned__=true
lodders 08:23:07 DEBUG ==>  message=, stack=Error
    at C:\snapshot\cli\lib\shell.js
From previous event:
    at Shell.sh (C:\snapshot\cli\lib\shell.js)
    at Object.dc (C:\snapshot\cli\lib\bootstrap.js)
    at compose (C:\snapshot\cli\lib\bootstrap.js)
    at C:\snapshot\cli\lib\router.js
    at C:\snapshot\cli\lib\router.js
    at processImmediate (internal/timers.js:464:21)
From previous event:
    at retryEach (C:\snapshot\cli\lib\router.js)
    at Object.start (C:\snapshot\cli\lib\router.js)
    at C:\snapshot\cli\lib\engine.js
    at C:\snapshot\cli\lib\router.js
From previous event:
    at Object.eventWrapper (C:\snapshot\cli\lib\router.js)
    at Engine.engineCmd (C:\snapshot\cli\lib\engine.js)
    at Engine.start (C:\snapshot\cli\lib\engine.js)
    at C:\snapshot\cli\plugins\lando-proxy\app.js
From previous event:
    at AsyncEvents.<anonymous> (C:\snapshot\cli\plugins\lando-proxy\app.js)
    at AsyncEvents.handle (C:\snapshot\cli\lib\events.js)
    at C:\snapshot\cli\lib\events.js
    at processImmediate (internal/timers.js:464:21)
From previous event:
    at AsyncEvents.emit (C:\snapshot\cli\lib\events.js)
    at C:\snapshot\cli\lib\app.js
From previous event:
    at App.start (C:\snapshot\cli\lib\app.js)
    at Object.run (C:\snapshot\cli\plugins\lando-core\tasks\start.js)
From previous event:
    at C:\snapshot\cli\lib\cli.js
From previous event:
    at Object.handler (C:\snapshot\cli\lib\cli.js)
    at Object.runCommand (C:\snapshot\cli\node_modules\yargs\lib\command.js:238:44)
    at Object.parseArgs [as _parseArgs] (C:\snapshot\cli\node_modules\yargs\yargs.js:1063:30)
    at Function.get [as argv] (C:\snapshot\cli\node_modules\yargs\yargs.js:1004:21)
    at Cli.init (C:\snapshot\cli\lib\cli.js)
    at Cli.run (C:\snapshot\cli\lib\cli.js)
    at Object.<anonymous> (C:\snapshot\cli\bin\lando.js)
    at Module._compile (pkg/prelude/bootstrap.js:1751:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Function.runMain (pkg/prelude/bootstrap.js:1804:12)
    at internal/main/run_main_module.js:17:47, __stackCleaned__=true
lodders 08:23:07 VERBOSE ==> reporting error action to report=true, url=https://metrics.lando.dev, report=true, url=https://metrics.lando.dev
lodders 08:23:07 DEBUG ==> reported data command=lando start, context=local, devMode=false, instance=9097e410c8a3c7bd7db65ba8b7e24064733e4bc2, nodeVersion=v14.17.2, mode=cli, type=Windows_NT, platform=win32, release=10.0.19043, arch
=x64, product=lando, version=3.3.0, , action=error, created=2021-09-02T07:23:07.680Z
lodders 08:23:07 DEBUG ==> process pid4 running C:\Program Files\Docker\Docker\resources\bin\docker-compose-v1.exe up cstdio=inherit, silent=false, mode=spawn, detached=false
Starting lodders_appserver_1       ... done
Starting lodders_database_1        ... done
Starting lodders_appserver_nginx_1 ... done
Starting lodders_cache_1           ... done
Starting lodders_index_1           ... done
Starting lodders_edge_1            ... done
Starting lodders_edge_ssl_1        ... done
lodders 08:23:16 DEBUG ==> process pid4 finished with exit code 0
lodders 08:23:16 DEBUG ==> emitting event post-start
lando   08:23:16 DEBUG ==> engine is up.
lodders 08:23:16 DEBUG ==> process pid6 running C:\Program Files\Docker\Docker\resources\bin\docker-compose-v1.exe exec database mysql cstdio=pipe, silent=true, mode=spawn, detached=false
lodders 08:23:17 DEBUG ==> process pid6 finished with exit code 0
lodders 08:23:18 DEBUG ==> connected lodders_edge_ssl_1 to the landonet
lodders 08:23:18 DEBUG ==> connected lodders_appserver_nginx_1 to the landonet
lodders 08:23:18 DEBUG ==> connected lodders_edge_1 to the landonet
lodders 08:23:19 DEBUG ==> connected lodders_appserver_1 to the landonet
lodders 08:23:19 DEBUG ==> connected lodders_index_1 to the landonet
lodders 08:23:19 DEBUG ==> connected lodders_database_1 to the landonet
lodders 08:23:19 DEBUG ==> connected lodders_cache_1 to the landonet
lodders 08:23:20 DEBUG ==> process pid7 running C:\Program Files\Docker\Docker\resources\bin\docker-compose-v1.exe exec database /helpers/user-perms.sh cstdio=inherit, silent=false, mode=spawn, detached=false
lodders 08:23:21 DEBUG ==> process pid7 finished with exit code 0
lodders 08:23:21 VERBOSE ==> attempting to find open services...
lodders 08:23:21 VERBOSE ==> This app was built on a different version of Lando.
lodders 08:23:21 VERBOSE ==> Using an unsupported version of DOCKER DESKTOP
Scanning to determine which services are ready... Please standby...
lodders 08:23:21 VERBOSE ==> about to scan urls
lodders 08:23:21 DEBUG ==> scanning data urls=[https://localhost:51231, http://localhost:51232, https://localhost:60705, http://localhost:60704, http://lodders.lndo.site/, https://lodders.lndo.site/], max=16, waitCodes=[400, 502, 40
4]
lodders 08:23:21 DEBUG ==> checking to see if https://localhost:51231 is ready.
lodders 08:23:21 DEBUG ==> checking to see if http://localhost:51232 is ready.
lodders 08:23:21 DEBUG ==> checking to see if https://localhost:60705 is ready.
lodders 08:23:21 DEBUG ==> checking to see if http://localhost:60704 is ready.
lodders 08:23:21 DEBUG ==> checking to see if http://lodders.lndo.site/ is ready.
lodders 08:23:21 DEBUG ==> checking to see if https://lodders.lndo.site/ is ready.
lodders 08:23:21 DEBUG ==> http://lodders.lndo.site/ not currently accessible
lodders 08:23:21 DEBUG ==> http://localhost:51232 is ready
lodders 08:23:21 DEBUG ==> http://localhost:60704 is ready
lodders 08:23:21 DEBUG ==> https://localhost:51231 is ready
lodders 08:23:21 DEBUG ==> https://localhost:60705 is ready
lodders 08:23:22 DEBUG ==> checking to see if http://lodders.lndo.site/ is ready.
lodders 08:23:22 DEBUG ==> checking to see if https://lodders.lndo.site/ is ready.
lodders 08:23:22 DEBUG ==> http://lodders.lndo.site/ not currently access
```

**Tell us generally about your bug**

Lando fails to fall back to the fallback ports even though they are available on my system.

**Tell us more**

Could better documentation have prevented this issue? if so what should we change? No
Does this bug prevent you from using lando? Yes

**Comment by reynoldsalec** [comment]
@hades200082 I'm guessing that your problem falls into the category Pirog mentioned on the referenced ticket https://github.com/lando/lando/issues/1360#issuecomment-456576493, so there probably isn't an easy win here.
