### ISSUE TITLE
Permission denied error occurs when running lando inside Ubuntu image in Windows OS

### ISSUE THREAD

**Issue by gpetrounrt** [lando/lando#3154]
I am currently trying to run lando inside an Ubuntu Docker image in Windows OS with Docker Desktop.

If I use the following Dockerfile, everything works when building by executing:
`docker build -f Dockerfile -t lando-test .`

    FROM ubuntu:20.04

    ARG LANDO_VERSION=3.4.0

    RUN apt-get update && \
        apt-get -y install apt-transport-https \
        ca-certificates \
        curl \
        sudo \
        gnupg2 \
        software-properties-common && \
        curl -fsSL https://download.docker.com/linux/$(. /etc/os-release; echo "$ID")/gpg > /tmp/dkey; apt-key add /tmp/dkey && \
        add-apt-repository \
        "deb [arch=amd64] https://download.docker.com/linux/$(. /etc/os-release; echo "$ID") \
        $(lsb_release -cs) \
        stable" && \
        apt-get update && \
        apt-get -y install docker-ce docker-ce-cli containerd.io

    RUN curl -L "https://github.com/docker/compose/releases/download/1.22.0/docker-compose-$(uname -s)-$(uname -m)" -o 
    /usr/local/bin/docker-compose && chmod +x /usr/local/bin/docker-compose

    RUN curl -OL https://github.com/lando/lando/releases/download/v${LANDO_VERSION}/lando-x64-v${LANDO_VERSION}.deb \
        && sudo dpkg -i lando-x64-v${LANDO_VERSION}.deb \
        && rm -rf lando-x64-v${LANDO_VERSION}.deb

    RUN adduser dockeruser

    RUN usermod -aG docker dockeruser

    RUN newgrp docker 

    RUN mkdir /usr/hello

    RUN chown -R dockeruser /usr/hello
    RUN chmod 777 /usr/hello

    USER dockeruser

    WORKDIR /usr/hello

    RUN echo "<h1>Lando says hellooo what have we here?</h1>" > index.html

    RUN lando init --source cwd --recipe lamp --webroot . --name hello-lando

However, when I try to run the image by executing:
`docker run -i --name lando-test --group-add 0 -v //var/run/docker.sock:/var/run/docker.sock lando-test`
I observe the following when executing commands inside the image:
`docker run hello-world` works just fine and gives the expected output
`lando version` works just fine and gives the expected output
`lando start` throws the following error:

    Let's get this party started! Starting app hello-lando...
    Creating network "landocasetupkenobi38ahsoka26c162085ab41dd307f5d9510d66bbb2ffb72ae7_default" with the default driver
    Creating landocasetupkenobi38ahsoka26c162085ab41dd307f5d9510d66bbb2ffb72ae7_ca_1 ... error

    ERROR: for landocasetupkenobi38ahsoka26c162085ab41dd307f5d9510d66bbb2ffb72ae7_ca_1  Cannot start service ca: OCI 
    runtime create failed: container_linux.go:380: starting container process caused: exec: "/lando-entrypoint.sh": permission 
    denied: unknown

    ERROR: for ca  Cannot start service ca: OCI runtime create failed: container_linux.go:380: starting container process caused: 
    exec: "/lando-entrypoint.sh": permission denied: unknown
    ERROR: Encountered errors while bringing up the project.
    ERROR ==>  message=, stack=Error
         at /snapshot/cli/lib/shell.js
    From previous event:
         at Shell.sh (/snapshot/cli/lib/shell.js)
         at Object.dc (/snapshot/cli/lib/bootstrap.js)
         at compose (/snapshot/cli/lib/bootstrap.js)
         at /snapshot/cli/lib/router.js
    From previous event:
        at retryEach (/snapshot/cli/lib/router.js)
        at Object.start (/snapshot/cli/lib/router.js)
    From previous event:
        at /snapshot/cli/lib/router.js
        at processImmediate (internal/timers.js:464:21)
    From previous event:
        at Object.run (/snapshot/cli/lib/router.js)
        at run (/snapshot/cli/lib/engine.js)
        at /snapshot/cli/lib/router.js
    From previous event:
        at Object.eventWrapper (/snapshot/cli/lib/router.js)
        at Engine.engineCmd (/snapshot/cli/lib/engine.js)
        at Engine.run (/snapshot/cli/lib/engine.js)
        at AsyncEvents.<anonymous> (/snapshot/cli/plugins/lando-core/index.js)
        at AsyncEvents.handle (/snapshot/cli/lib/events.js)
        at /snapshot/cli/lib/events.js
        at processImmediate (internal/timers.js:464:21)
    From previous event:
        at AsyncEvents.emit (/snapshot/cli/lib/events.js)
        at /snapshot/cli/lib/router.js
    From previous event:
        at Object.eventWrapper (/snapshot/cli/lib/router.js)
        at Engine.engineCmd (/snapshot/cli/lib/engine.js)
        at Engine.start (/snapshot/cli/lib/engine.js)
        at /snapshot/cli/plugins/lando-proxy/app.js
    From previous event:
        at AsyncEvents.<anonymous> (/snapshot/cli/plugins/lando-proxy/app.js)
        at AsyncEvents.handle (/snapshot/cli/lib/events.js)
        at /snapshot/cli/lib/events.js
        at processImmediate (internal/timers.js:464:21)
    From previous event:
        at AsyncEvents.emit (/snapshot/cli/lib/events.js)
        at /snapshot/cli/lib/app.js
    From previous event:
       at App.start (/snapshot/cli/lib/app.js)
       at Object.run (/snapshot/cli/plugins/lando-core/tasks/start.js)
    From previous event:
       at /snapshot/cli/lib/cli.js
    From previous event:
       at Object.handler (/snapshot/cli/lib/cli.js)
       at Object.runCommand (/snapshot/cli/node_modules/yargs/lib/command.js:238:44)
       at Object.parseArgs [as _parseArgs] (/snapshot/cli/node_modules/yargs/yargs.js:1063:30)
       at Function.get [as argv] (/snapshot/cli/node_modules/yargs/yargs.js:1004:21)
       at Cli.init (/snapshot/cli/lib/cli.js)
       at Cli.run (/snapshot/cli/lib/cli.js)
       at Object.<anonymous> (/snapshot/cli/bin/lando.js)
       at Module._compile (pkg/prelude/bootstrap.js:1751:22)
       at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
       at Module.load (internal/modules/cjs/loader.js:950:32)
       at Function.Module._load (internal/modules/cjs/loader.js:790:14)
       at Function.runMain (pkg/prelude/bootstrap.js:1804:12)
       at internal/main/run_main_module.js:17:47, __stackCleaned__=true

Am I doing something wrong when running the image?
Do I need to fix permissions somewhere?

**Comment by drjayvee** [comment]
> ERROR: for ca  Cannot start service ca: OCI runtime create failed: container_linux.go:380: starting container process caused:

This looks very familiar to me. Sometimes `lando rebuild -y` solves that. Other times, only the nuclear option works: `lando stop; docker system prune;` and restart the host OS.

You also might want to check out #3030, #2527 #2060.
