### ISSUE TITLE
PostgreSQL not working on macOS Big Sur 11.6 (MySQL config being used)

### ISSUE THREAD

**Issue by dpacassi** [lando/lando#3167]
I was having issues setting up a new Lando project with a Postgres database service.
Here's my `.lando.yml` file:

```
name: dpr
recipe: drupal8
config:
  webroot: web
  php: '7.4'
  xdebug: false
services:
  database:
    type: postgres:10
  appserver:
    composer_version: '1.10.22'
```

I was running Lando `3.1.4`, I've updated to the latest release `3.4.2` but still get the same errors.
I've tried switch to Postgres `13` and even
```
type: postgres:custom
overrides:
  image: bitnami/postgresql:13.4.0-debian-10-r53
```

But after `lando start` I receive:
```
06b3220526d9: Pull complete
Digest: sha256:80d9598eeb300de7ee4f0e67f77255ec0aded873e460666fc4e20dc40d06dafc
Status: Downloaded newer image for bitnami/postgresql:10.12.0-debian-10-r36
Starting dpr_appserver_1 ... done
Creating dpr_database_1  ... done
Waiting until database service is ready...
Waiting until database service is ready...
Waiting until database service is ready...
Waiting until database service is ready...
Waiting until database service is ready...
Waiting until database service is ready...
Waiting until database service is ready...
Waiting until database service is ready...
Waiting until database service is ready...
Waiting until database service is ready...
Waiting until database service is ready...
Waiting until database service is ready...
Waiting until database service is ready...
Waiting until database service is ready...
Waiting until database service is ready...
Waiting until database service is ready...
Waiting until database service is ready...
Waiting until database service is ready...
Waiting until database service is ready...
Waiting until database service is ready...
Waiting until database service is ready...
Waiting until database service is ready...
Waiting until database service is ready...
Waiting until database service is ready...
Waiting until database service is ready...
Waiting until database service is ready...
ERROR ==> database reported as unhealthy.
Starting dpr_database_1 ... done
ERROR ==>  message=, stack=Error
    at /snapshot/cli/lib/shell.js
From previous event:
    at Shell.sh (/snapshot/cli/lib/shell.js)
    at Object.dc (/snapshot/cli/lib/bootstrap.js)
    at compose (/snapshot/cli/lib/bootstrap.js)
From previous event:
    at /snapshot/cli/lib/router.js
    at processImmediate (internal/timers.js:464:21)
From previous event:
    at Object.run (/snapshot/cli/lib/router.js)
    at run (/snapshot/cli/lib/engine.js)
    at /snapshot/cli/lib/router.js
From previous event:
    at Object.eventWrapper (/snapshot/cli/lib/router.js)
    at Engine.engineCmd (/snapshot/cli/lib/engine.js)
    at Engine.run (/snapshot/cli/lib/engine.js)
    at /snapshot/cli/plugins/lando-core/app.js
From previous event:
    at AsyncEvents.<anonymous> (/snapshot/cli/plugins/lando-core/app.js)
    at AsyncEvents.handle (/snapshot/cli/lib/events.js)
    at /snapshot/cli/lib/events.js
    at processImmediate (internal/timers.js:464:21)
From previous event:
    at AsyncEvents.emit (/snapshot/cli/lib/events.js)
    at /snapshot/cli/lib/app.js
From previous event:
    at App.start (/snapshot/cli/lib/app.js)
    at Object.run (/snapshot/cli/plugins/lando-core/tasks/start.js)
From previous event:
    at /snapshot/cli/lib/cli.js
From previous event:
    at Object.handler (/snapshot/cli/lib/cli.js)
    at Object.runCommand (/snapshot/cli/node_modules/yargs/lib/command.js:238:44)
    at Object.parseArgs [as _parseArgs] (/snapshot/cli/node_modules/yargs/yargs.js:1063:30)
    at Function.get [as argv] (/snapshot/cli/node_modules/yargs/yargs.js:1004:21)
    at Cli.init (/snapshot/cli/lib/cli.js)
    at Cli.run (/snapshot/cli/lib/cli.js)
From previous event:
    at /snapshot/cli/bin/lando.js
From previous event:
    at Object.<anonymous> (/snapshot/cli/bin/lando.js)
    at Module._compile (pkg/prelude/bootstrap.js:1751:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Function.runMain (pkg/prelude/bootstrap.js:1804:12)
    at internal/main/run_main_module.js:17:47, __stackCleaned__=true
Scanning to determine which services are ready... Please standby...
Starting dpr_database_1 ... done
ERROR ==>  message=, stack=Error
    at /snapshot/cli/lib/shell.js
From previous event:
    at Shell.sh (/snapshot/cli/lib/shell.js)
    at Object.dc (/snapshot/cli/lib/bootstrap.js)
    at compose (/snapshot/cli/lib/bootstrap.js)
From previous event:
    at /snapshot/cli/lib/router.js
    at processImmediate (internal/timers.js:464:21)
From previous event:
    at Object.run (/snapshot/cli/lib/router.js)
    at run (/snapshot/cli/lib/engine.js)
    at /snapshot/cli/lib/router.js
From previous event:
    at Object.eventWrapper (/snapshot/cli/lib/router.js)
    at Engine.engineCmd (/snapshot/cli/lib/engine.js)
    at Engine.run (/snapshot/cli/lib/engine.js)
    at /snapshot/cli/plugins/lando-core/app.js
From previous event:
    at AsyncEvents.<anonymous> (/snapshot/cli/plugins/lando-core/app.js)
    at AsyncEvents.handle (/snapshot/cli/lib/events.js)
    at /snapshot/cli/lib/events.js
From previous event:
    at AsyncEvents.emit (/snapshot/cli/lib/events.js)
    at /snapshot/cli/lib/app.js
From previous event:
    at App.start (/snapshot/cli/lib/app.js)
    at Object.run (/snapshot/cli/plugins/lando-core/tasks/start.js)
From previous event:
    at /snapshot/cli/lib/cli.js
From previous event:
    at Object.handler (/snapshot/cli/lib/cli.js)
    at Object.runCommand (/snapshot/cli/node_modules/yargs/lib/command.js:238:44)
    at Object.parseArgs [as _parseArgs] (/snapshot/cli/node_modules/yargs/yargs.js:1063:30)
    at Function.get [as argv] (/snapshot/cli/node_modules/yargs/yargs.js:1004:21)
    at Cli.init (/snapshot/cli/lib/cli.js)
    at Cli.run (/snapshot/cli/lib/cli.js)
From previous event:
    at /snapshot/cli/bin/lando.js
From previous event:
    at Object.<anonymous> (/snapshot/cli/bin/lando.js)
    at Module._compile (pkg/prelude/bootstrap.js:1751:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Function.runMain (pkg/prelude/bootstrap.js:1804:12)
    at internal/main/run_main_module.js:17:47, __stackCleaned__=true

  _      __              _           __
 | | /| / /__ ________  (_)__  ___ _/ /
 | |/ |/ / _ `/ __/ _ \/ / _ \/ _ `/_/
 |__/|__/\_,_/_/ /_//_/_/_//_/\_, (_)
                             /___/

Your app started up but we detected some things you may wish to investigate.
These only may be a problem.


 ■ The service "database" failed its healthcheck
   This may be ok but we recommend you run the command below to investigate:
   lando logs -s database


 ■ The service "database" is not running!
   This is likely a critical problem and we recommend you run the command below to investigate
   lando logs -s database


 ■ The service "database" is not running!
   This is likely a critical problem and we recommend you run the command below to investigate
   lando logs -s database
```

When I run `lando logs -s database` I get:
```
database_1   | postgresql 10:34:22.79 INFO  ==> ** PostgreSQL setup finished! **
database_1   | postgresql 10:34:22.90 INFO  ==> ** Starting PostgreSQL **
database_1   | 2021-10-06 10:34:22.936 GMT [17] LOG:  syntax error in file "/opt/bitnami/postgresql/conf/conf.d/lando.conf" line 5, near token "["
database_1   | 2021-10-06 10:34:22.936 GMT [17] LOG:  syntax error in file "/opt/bitnami/postgresql/conf/conf.d/lando.conf" line 10, near token "default-storage-engine"
database_1   | 2021-10-06 10:34:22.937 GMT [17] LOG:  syntax error in file "/opt/bitnami/postgresql/conf/conf.d/lando.conf" line 98, near token "["
database_1   | 2021-10-06 10:34:22.937 GMT [17] LOG:  syntax error in file "/opt/bitnami/postgresql/conf/conf.d/lando.conf" line 99, near end of line
database_1   | 2021-10-06 10:34:22.937 GMT [17] LOG:  syntax error in file "/opt/bitnami/postgresql/conf/conf.d/lando.conf" line 100, near token "quote-names"
database_1   | 2021-10-06 10:34:22.937 GMT [17] LOG:  syntax error in file "/opt/bitnami/postgresql/conf/conf.d/lando.conf" line 103, near token "["
database_1   | 2021-10-06 10:34:22.937 GMT [17] LOG:  syntax error in file "/opt/bitnami/postgresql/conf/conf.d/lando.conf" line 106, near token "["
database_1   | 2021-10-06 10:34:22.937 GMT [17] FATAL:  configuration file "/opt/bitnami/postgresql/conf/postgresql.conf" contains errors
```

If i run `lando info` I see that the MySQL config is being used:

```
service: 'database',
    urls: [],
    type: 'postgres',
    healthy: true,
    internal_connection: { host: 'database', port: '5432' },
    external_connection: { host: '127.0.0.1', port: true },
    healthcheck: 'psql -U postgres -c "\\l"',
    creds: { database: 'drupal8', user: 'postgres', password: '' },
    config: { database: '/Users/dpacassi/.lando/config/drupal8/mysql.cnf' },
    version: '10',
    meUser: 'www-data',
    hasCerts: false,
    hostnames: [ 'database.hihihoho.internal' ] }
```

So it seems that the bug fixed by #1454 is still somehow present.
Is there any fix to this?

**Comment by djassie** [comment]
Works
```yaml
name: dpr
recipe: drupal8
config:
  webroot: web
  php: '7.4'
  composer_version: '1.10.22'
  xdebug: false
  database: postgres:13
```
