### ISSUE TITLE
volume "landoproxyhyperion5000gandalfedition_proxy_config" already exists but was not created for project "landoproxyhyperion5000gandalfedition"

### ISSUE THREAD

**Issue by ElijahLynn** [lando/lando#3227]
Been a while since I used Lando on our project and something got borked badly when I tried to boot it up just now. I have completely removed all containers, volumes and networks from the system by using suggestions here > https://stackoverflow.com/questions/34658836/docker-is-in-volume-in-use-but-there-arent-any-docker-containers. However, every time I completely wipe, then run `lando poweroff` then run a `lando rebuild` or `lando start` I keep getting the error:

> volume "landoproxyhyperion5000gandalfedition_proxy_config" already exists but was not created for project "landoproxyhyperion5000gandalfedition"

```
❯ lando version
v3.4.2
```

**CLI Logs Below (expand 'Details')**
<details>

~/Projects/va.gov/va.gov-cms main
❯ docker network list
NETWORK ID     NAME      DRIVER    SCOPE
488612af4313   bridge    bridge    local
00272c3103c2   host      host      local
fe6cd282aa0c   none      null      local

~/Projects/va.gov/va.gov-cms main
❯ docker volume list
DRIVER    VOLUME NAME

~/Projects/va.gov/va.gov-cms main
❯ docker container list
CONTAINER ID   IMAGE     COMMAND   CREATED   STATUS    PORTS     NAMES

~/Projects/va.gov/va.gov-cms main
❯ lando poweroff

NO!! SHUT IT ALL DOWN!!!
   ___                     _                  ______
  / _ \___ _    _____ ____(_)__  ___ _  ___  / _/ _/
 / ___/ _ \ |/|/ / -_) __/ / _ \/ _ `/ / _ \/ _/ _/ _ _
/_/   \___/__,__/\__/_/ /_/_//_/\_, /  \___/_//_/(_|_|_)
                               /___/

Lando containers have been spun down.

~/Projects/va.gov/va.gov-cms main
❯ lando start
Let's get this party started! Starting app va-gov-cms...
[+] Running 4/4
 ⠿ Network landoproxyhyperion5000gandalfedition_edge           Created                                                                              0.0s
 ⠿ Volume "landoproxyhyperion5000gandalfedition_proxy_config"  Created                                                                              0.0s
 ⠿ Volume "landoproxyhyperion5000gandalfedition_home_proxy"    Created                                                                              0.0s
 ⠿ Container landoproxyhyperion5000gandalfedition-proxy-1      Started                                                                              0.4s
WARN[0000] network lando_proxyedge: network.external.name is deprecated in favor of network.name
[+] Running 4/0
 ⠿ Network vagovcms_default         Created                                                                                                         0.0s
 ⠿ Volume "vagovcms_home_database"  Created                                                                                                         0.0s
 ⠿ Volume "vagovcms_home_mailhog"   Created                                                                                                         0.0s
 ⠿ Volume "vagovcms_home_memcache"  Created                                                                                                         0.0s
volume "landoproxyhyperion5000gandalfedition_proxy_config" already exists but was not created for project "landoproxyhyperion5000gandalfedition". Use `external: true` to use an existing volume
ERROR ==>  message=, stack=Error
    at /snapshot/cli/lib/shell.js
From previous event:
    at Shell.sh (/snapshot/cli/lib/shell.js)
    at Object.dc (/snapshot/cli/lib/bootstrap.js)
    at compose (/snapshot/cli/lib/bootstrap.js)
    at /snapshot/cli/lib/router.js
From previous event:
    at retryEach (/snapshot/cli/lib/router.js)
    at Object.start (/snapshot/cli/lib/router.js)
From previous event:
    at /snapshot/cli/lib/router.js
    at processImmediate (internal/timers.js:464:21)
From previous event:
    at Object.run (/snapshot/cli/lib/router.js)
    at run (/snapshot/cli/lib/engine.js)
    at /snapshot/cli/lib/router.js
From previous event:
    at Object.eventWrapper (/snapshot/cli/lib/router.js)
    at Engine.engineCmd (/snapshot/cli/lib/engine.js)
    at Engine.run (/snapshot/cli/lib/engine.js)
    at Object.runBuild (/snapshot/cli/plugins/lando-services/lib/utils.js)
    at AsyncEvents.<anonymous> (/snapshot/cli/plugins/lando-services/app.js)
    at AsyncEvents.handle (/snapshot/cli/lib/events.js)
    at /snapshot/cli/lib/events.js
From previous event:
    at AsyncEvents.emit (/snapshot/cli/lib/events.js)
    at /snapshot/cli/lib/app.js
From previous event:
    at App.start (/snapshot/cli/lib/app.js)
    at Object.run (/snapshot/cli/plugins/lando-core/tasks/start.js)
From previous event:
    at /snapshot/cli/lib/cli.js
From previous event:
    at Object.handler (/snapshot/cli/lib/cli.js)
    at Object.runCommand (/snapshot/cli/node_modules/yargs/lib/command.js:238:44)
    at Object.parseArgs [as _parseArgs] (/snapshot/cli/node_modules/yargs/yargs.js:1063:30)
    at Function.get [as argv] (/snapshot/cli/node_modules/yargs/yargs.js:1004:21)
    at Cli.init (/snapshot/cli/lib/cli.js)
    at Cli.run (/snapshot/cli/lib/cli.js)
    at Object.<anonymous> (/snapshot/cli/bin/lando.js)
    at Module._compile (pkg/prelude/bootstrap.js:1751:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Function.runMain (pkg/prelude/bootstrap.js:1804:12)
    at internal/main/run_main_module.js:17:47, __stackCleaned__=true
WARN[0000] network lando_proxyedge: network.external.name is deprecated in favor of network.name
volume "landoproxyhyperion5000gandalfedition_proxy_config" already exists but was not created for project "landoproxyhyperion5000gandalfedition". Use `external: true` to use an existing volume
ERROR ==>  message=, stack=Error
    at /snapshot/cli/lib/shell.js
From previous event:
    at Shell.sh (/snapshot/cli/lib/shell.js)
    at Object.dc (/snapshot/cli/lib/bootstrap.js)
    at compose (/snapshot/cli/lib/bootstrap.js)
    at /snapshot/cli/lib/router.js
    at /snapshot/cli/lib/router.js
    at processImmediate (internal/timers.js:464:21)
From previous event:
    at retryEach (/snapshot/cli/lib/router.js)
    at Object.start (/snapshot/cli/lib/router.js)
    at /snapshot/cli/lib/engine.js
    at /snapshot/cli/lib/router.js
From previous event:
    at Object.eventWrapper (/snapshot/cli/lib/router.js)
    at Engine.engineCmd (/snapshot/cli/lib/engine.js)
    at Engine.start (/snapshot/cli/lib/engine.js)
    at /snapshot/cli/lib/app.js
From previous event:
    at App.start (/snapshot/cli/lib/app.js)
    at Object.run (/snapshot/cli/plugins/lando-core/tasks/start.js)
From previous event:
    at /snapshot/cli/lib/cli.js
From previous event:
    at Object.handler (/snapshot/cli/lib/cli.js)
    at Object.runCommand (/snapshot/cli/node_modules/yargs/lib/command.js:238:44)
    at Object.parseArgs [as _parseArgs] (/snapshot/cli/node_modules/yargs/yargs.js:1063:30)
    at Function.get [as argv] (/snapshot/cli/node_modules/yargs/yargs.js:1004:21)
    at Cli.init (/snapshot/cli/lib/cli.js)
    at Cli.run (/snapshot/cli/lib/cli.js)
    at Object.<anonymous> (/snapshot/cli/bin/lando.js)
    at Module._compile (pkg/prelude/bootstrap.js:1751:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Function.runMain (pkg/prelude/bootstrap.js:1804:12)
    at internal/main/run_main_module.js:17:47, __stackCleaned__=true

██╗   ██╗██╗  ██╗     ██████╗ ██╗  ██╗██╗
██║   ██║██║  ██║    ██╔═══██╗██║  ██║██║
██║   ██║███████║    ██║   ██║███████║██║
██║   ██║██╔══██║    ██║   ██║██╔══██║╚═╝
╚██████╔╝██║  ██║    ╚██████╔╝██║  ██║██╗
 ╚═════╝ ╚═╝  ╚═╝     ╚═════╝ ╚═╝  ╚═╝╚═╝

An error occurred while starting up your app!
Here are a few things you can try to get back into a good state:

  ■ Try running lando rebuild
  ■ Try restarting in debug mode lando restart -vvv
  ■ Try checking the logs with lando logs

If those fail then consult the troubleshooting materials:

  ■ https://docs.lando.dev/help/logs.html
  ■ https://docs.lando.dev/help/updating.html

Or post your issue to Slack or GitHub

  ■ Slack - https://launchpass.com/devwithlando
  ■ GitHub - https://github.com/lando/lando/issues/new/choose

ERROR ==>

</details>

**Comment by ElijahLynn** [comment]
I think it is by design, but worth noting that `lando destroy` doesn't remove the proxy. 

~/Projects/va.gov/va.gov-cms main                                  
❯ lando destroy                                                    
? Are you sure you want to DESTROY? Yes                            
Preparing to consign va-gov-cms to the dustbin of history...       
[+] Running 4/0                                                    
 ⠿ Volume vagovcms_home_memcache  Removed                          
 ⠿ Volume vagovcms_home_database  Removed                          
 ⠿ Network vagovcms_default       Removed                          
 ⠿ Volume vagovcms_home_mailhog   Removed                          
The app known as va-gov-cms has paid the IRON PRICE. App destroyed!
                                                                   
~/Projects/va.gov/va.gov-cms main                                  
❯ docker volume list                                               
DRIVER    VOLUME NAME                                              
local     landoproxyhyperion5000gandalfedition_home_proxy          
local     landoproxyhyperion5000gandalfedition_proxy_config

**Comment by ElijahLynn** [comment]
I manually remove them all with the below commands and end up back where I started in the first comment:

```
❯ docker kill landoproxyhyperion5000gandalfedition-proxy-1
landoproxyhyperion5000gandalfedition-proxy-1        

❯ docker container prune
WARNING! This will remove all stopped containers.
Are you sure you want to continue? [y/N] y
Deleted Containers:
832830167c6f86fc1b82c681a16c8556b868f5768072958172e9eeff3307e064

❯ docker network prune                                                           
WARNING! This will remove all custom networks not used by at least one container.
Are you sure you want to continue? [y/N] y                                       
Deleted Networks:                                                                
lando_bridge_network                                                             
landoproxyhyperion5000gandalfedition_edge                                        

❯ docker volume prune
WARNING! This will remove all local volumes not used by at least one container.
Are you sure you want to continue? [y/N] y
Deleted Volumes:
landoproxyhyperion5000gandalfedition_proxy_config
landoproxyhyperion5000gandalfedition_home_proxy

Total reclaimed space: 239B

❯ docker volume list                                                   
DRIVER    VOLUME NAME                                                  
                                                                       
❯ docker container list                                                
CONTAINER ID   IMAGE     COMMAND   CREATED   STATUS    PORTS     NAMES 
                                                                       
❯ docker network list                                                  
NETWORK ID     NAME      DRIVER    SCOPE                               
488612af4313   bridge    bridge    local                               
00272c3103c2   host      host      local                               
fe6cd282aa0c   none      null      local                               
                                                                       
```
