### ISSUE TITLE
Cannot boot Lando apps on Apple Silicon because curl can't resolve github.com

### ISSUE THREAD

**Issue by jasonevines** [lando/lando#3236]
The specific error is this, when running Lando 3.5.1 on a Macbook M1 Pro Max:

`curl: (6) Could not resolve host: github.com`

Here's the output pertaining to the error when running with the -vvv flag:

`app-name 15:40:47 DEBUG ==> process pid14 running /Applications/Docker.app/Contents/Resources/bin/docker-compose-v1/docker-compose exec app /bin/sh curl -fsSL -o /usr/local/bin/mhsendmail github.com/evertiro/mhsendmail/releases/download/v0.2.0-M1/mhsendmail_linux_arm64 cstdio=[inherit, pipe, pipe], silent=false, mode=spawn, detached=false
curl: (6) Could not resolve host: github.com
app-name 15:40:48 DEBUG ==> process pid14 finished with exit code 6
app-name 15:40:48 ERROR ==> curl: (6) Could not resolve host: github.com
app-name 15:40:48 DEBUG ==>  message=curl: (6) Could not resolve host: github.com, stack=Error: curl: (6) Could not resolve host: github.com
    at /snapshot/cli/lib/shell.js
From previous event:
    at Shell.sh (/snapshot/cli/lib/shell.js)
    at Object.dc (/snapshot/cli/lib/bootstrap.js)
    at compose (/snapshot/cli/lib/bootstrap.js)
From previous event:
    at /snapshot/cli/lib/router.js
    at processImmediate (internal/timers.js:464:21)
From previous event:
    at Object.run (/snapshot/cli/lib/router.js)
    at run (/snapshot/cli/lib/engine.js)
    at /snapshot/cli/lib/router.js
From previous event:
    at Object.eventWrapper (/snapshot/cli/lib/router.js)
    at Engine.engineCmd (/snapshot/cli/lib/engine.js)
    at Engine.run (/snapshot/cli/lib/engine.js)
    at Object.runBuild (/snapshot/cli/plugins/lando-services/lib/utils.js)
    at AsyncEvents.<anonymous> (/snapshot/cli/plugins/lando-services/app.js)
    at AsyncEvents.handle (/snapshot/cli/lib/events.js)
    at /snapshot/cli/lib/events.js
From previous event:
    at AsyncEvents.emit (/snapshot/cli/lib/events.js)
    at /snapshot/cli/lib/app.js
From previous event:
    at App.start (/snapshot/cli/lib/app.js)
    at Object.run (/snapshot/cli/plugins/lando-core/tasks/start.js)
From previous event:
    at /snapshot/cli/lib/cli.js
From previous event:
    at Object.handler (/snapshot/cli/lib/cli.js)
    at Object.runCommand (/snapshot/cli/node_modules/yargs/lib/command.js:238:44)
    at Object.parseArgs [as _parseArgs] (/snapshot/cli/node_modules/yargs/yargs.js:1063:30)
    at Function.get [as argv] (/snapshot/cli/node_modules/yargs/yargs.js:1004:21)
    at Cli.init (/snapshot/cli/lib/cli.js)
    at Cli.run (/snapshot/cli/lib/cli.js)
From previous event:
    at /snapshot/cli/bin/lando.js
From previous event:
    at Object.<anonymous> (/snapshot/cli/bin/lando.js)
    at Module._compile (pkg/prelude/bootstrap.js:1751:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Function.runMain (pkg/prelude/bootstrap.js:1804:12)
    at internal/main/run_main_module.js:17:47, __stackCleaned__=true
app-name 15:40:48 VERBOSE ==> reporting error action to report=true, url=https://metrics.lando.dev, report=true, url=https://metrics.lando.dev, report=true, url=https://metrics.lando.dev
app-name 15:40:48 DEBUG ==> reported data command=lando start, context=local, devMode=false, instance=a358bfe49393a9e5ae4636c478a952e19142530e, nodeVersion=v14.17.2, mode=cli, type=Darwin, platform=darwin, release=21.1.0, arch=arm64, product=lando, version=3.5.1, message=curl: (6) Could not resolve host: github.com, action=error, created=2021-12-07T20:40:48.327Z`

I do not encounter this problem when running the same applications using Lando on my Intel Mac.

**Comment by jasonevines** [comment]
The error appears to be related to the Mailhog service. If I omit the hogfrom setting in the Mailhog configuration, the error does not happen.

**Comment by labboy0276** [comment]
@jasonevines can you try the [pre-release 3.6.0](https://github.com/lando/lando/releases/tag/v3.6.0) to see if this addresses your issue

**Comment by jasonevines** [comment]
The 3.6.0 release has not fixed the issue.

**Comment by jasonevines** [comment]
Note that I'm using Platform.sh, so maybe this should be more properly be considered a problem with the Platform.sh plugin and / or Docker images?
