### ISSUE TITLE
After Upgrade for lando 3.6.0-2 No such container: landoproxyhyperion5000gandalfedition_proxy_1 (docker ps shows: landoproxyhyperion5000gandalfedition-proxy-1)

### ISSUE THREAD

**Issue by Gregg-Hendrix** [lando/lando#3255]
Just rubber ducking this here:

I knew that I shouldn't have installed the new version of lando...I just got SO excited by everyone updating! Does anyone have any insight on this error?

After running `lando start` I got this : 

```
ERROR ==> Error: (HTTP code 404) no such container - No such container: landoproxyhyperion5000gandalfedition_proxy_1  message=Error: (HTTP code 404) no such container - No such container: landoproxyhyperion5000gandalfedition_proxy_1 , stack=Error: Error: (HTTP code 404) no such container - No such container: landoproxyhyperion5000gandalfedition_proxy_1 
    at /snapshot/cli/lib/docker.js
    at processImmediate (internal/timers.js:464:21)
From previous event:
    at containerOpt (/snapshot/cli/lib/docker.js)
    at Landerode.scan (/snapshot/cli/lib/docker.js)
    at Object.scan (/snapshot/cli/lib/router.js)
    at run (/snapshot/cli/lib/engine.js)
    at /snapshot/cli/lib/router.js
From previous event:
    at Object.eventWrapper (/snapshot/cli/lib/router.js)
    at Engine.engineCmd (/snapshot/cli/lib/engine.js)
    at Engine.scan (/snapshot/cli/lib/engine.js)
    at /snapshot/cli/plugins/lando-networking/app.js
From previous event:
    at AsyncEvents.<anonymous> (/snapshot/cli/plugins/lando-networking/app.js)
    at AsyncEvents.handle (/snapshot/cli/lib/events.js)
    at /snapshot/cli/lib/events.js
    at processImmediate (internal/timers.js:464:21)
From previous event:
    at AsyncEvents.emit (/snapshot/cli/lib/events.js)
    at /snapshot/cli/lib/app.js
From previous event:
    at App.start (/snapshot/cli/lib/app.js)
    at Object.run (/snapshot/cli/plugins/lando-core/tasks/start.js)
    at /snapshot/cli/lib/cli.js
    at processImmediate (internal/timers.js:464:21)
From previous event:
    at /snapshot/cli/lib/cli.js
From previous event:
    at Object.handler (/snapshot/cli/lib/cli.js)
    at Object.runCommand (/snapshot/cli/node_modules/yargs/lib/command.js:238:44)
    at Object.parseArgs [as _parseArgs] (/snapshot/cli/node_modules/yargs/yargs.js:1063:30)
    at Function.get [as argv] (/snapshot/cli/node_modules/yargs/yargs.js:1004:21)
    at Cli.init (/snapshot/cli/lib/cli.js)
    at Cli.run (/snapshot/cli/lib/cli.js)
    at Object.<anonymous> (/snapshot/cli/bin/lando.js)
    at Module._compile (pkg/prelude/bootstrap.js:1751:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Function.runMain (pkg/prelude/bootstrap.js:1804:12)
    at internal/main/run_main_module.js:17:47, __stackCleaned__=true

```
I then ran lando rebuild  and got this error :

```
ERROR ==> database reported as unhealthy. 
ERROR ==> Error: (HTTP code 404) no such container - No such container: landoproxyhyperion5000gandalfedition_proxy_1 
```

I'm SUPER out of my depth with lando in general (haha). I'm thinking that since I don't really know what I'm doing...Perhaps the best thing for me is to uninstall and re-install the previous version that was working? Any thoughts would be appreciated

P.s - I tried a `lando poweroff `

and

`lando destroy`

**Comment by Gregg-Hendrix** [comment]
It looks like landoproxyhyperion5000gandalfedition-proxy-1 exists, but its looking like its a hyphen vs underscore issue?

**Comment by ElijahLynn** [comment]
Seems like it might be related to https://github.com/lando/lando/issues/1297 which suggests that certain versions of `docker-compose` changed how they create containers. I wonder if there is a Lando cache of the old naming scheme (with underscores). Maybe try clearing out the `~/.lando` folder?

**Comment by ElijahLynn** [comment]
If that doesn't work, this comment https://github.com/lando/lando/issues/1297#issuecomment-953896580 suggest downgrading `docker-composer` from a 2.x version to a 1.x version.

**Comment by ElijahLynn** [comment]
I troubleshooted this with Gregg a bit and what appears to happen is that Arch Linux just updated `docker-compose` to 2.2.2. We downgraded `docker-compose to 1.29.2. The Arch package `docker-compose-bin` mentioned in https://github.com/lando/lando/issues/1297#issuecomment-953896580 is not available anymore. But we we found https://github.com/gbleux/aur-docker-compose-bin/blob/master/PKGBUILD which we modified to include the right version and SHAs and then ran `makepkg` and then `sudo pacman -U <filename.zst)`. Which solved the issue. 

So it appears that Lando needs to have support to work with Docker Composer 2.x maybe?

**Comment by ElijahLynn** [comment]
In hindsight, we could have done a `ls /var/cache/pacman/pkg/ | grep docker-compose` and found the *.zst file for 1.29.2. So then all you have to do is `pacman --upgrade /var/cache/pacman/pkg/docker-compose-1.29.2-1-any.pkg.tar.zst` to update, which asks you if you want to remove the other version. Then you have to pin it in /etc/pacman.conf by adding a `IgnorePkg   = docker-compose` line.

**Comment by joshmiller83** [comment]
I'm documenting my efforts to get lando working with this 404 error on the `landoproxyhyperion500gandalfeditioin_proxy_1` error above on a Mac Intel that is running the latest version of Lando and version 2.0.0-rc1 of `docker composer`.

1. I've tried `lando rebuild` and got a weird error
2. I decided to restart Docker and got the 404 error
3. Requested someone interpret Elijah above on the community slack at Lando and johnouellet helped me understand that Elijah was talking about installing docker compose on a Linux machine 
4. We decided a good `lando destroy` was called for, to try and rebuild the container that was causing problems.
5. After destroy, lando came up with the following message:

> Recreating ec54b6be2d04_landoproxyhyperion5000gandalfedition_proxy_1 ... 
Recreating ec54b6be2d04_landoproxyhyperion5000gandalfedition_proxy_1 ... error
>
> ERROR: for ec54b6be2d04_landoproxyhyperion5000gandalfedition_proxy_1  Cannot start service proxy: driver failed programming external connectivity on endpoint landoproxyhyperion5000gandalfedition_proxy_1 (aac937dfcd3722fd33b32ac6d7537bf2f43c62bc89a79f974f5b6fb41bfa8b7e): Bind for 127.0.0.1:8080 failed: port is already allocated
> 
> ERROR: for proxy  Cannot start service proxy: driver failed programming external connectivity on endpoint landoproxyhyperion5000gandalfedition_proxy_1 (aac937dfcd3722fd33b32ac6d7537bf2f43c62bc89a79f974f5b6fb41bfa8b7e): Bind for 127.0.0.1:8080 failed: port is already allocated
> ERROR: Encountered errors while bringing up the project.

But it did come up!

>Lando was not able to start the proxy
   Error
   The proxy has been disabled for now so you can continue to work.
   Check out the docs below, resolve your issue and build this app
   https://docs.lando.dev/config/proxy.html

I think my next attempt will be a full reboot, see if a "clean" docker start will resolve the port issues.

**Comment by benperiton** [comment]
I found that running lando start, then once it fails renaming the proxy, then starting again seems to work

````
docker rename landoproxyhyperion5000gandalfedition-proxy-1 landoproxyhyperion5000gandalfedition_proxy_1
````

**Comment by pirog** [comment]
Lando **DOES NOT** support Docker Compose 2 at this time so YMMV if you try it out.

**Comment by sirdiego** [comment]
> Lando **DOES NOT** support Docker Compose 2 at this time so YMMV if you try it out.

Thanks for letting us know. Would be nice to place this info somewhere prominent in the documentation. Currently the ArchLinux installation is broken, because it installs docker-composer 2 alongside lando.

**Comment by pirog** [comment]
If you install one of Lando's package installers it should install the correct version of Docker Compose so i'm guessing this is only relevant if you are installing Lando from source. We should update those docs so its clear what version of Docker Compose is required:
https://docs.lando.dev/basics/installation.html#from-source

**Comment by pirog** [comment]
Moving this ticket over to the docs repo so it can be handled there
