### ISSUE TITLE
Can't start any Lando project anymore

### ISSUE THREAD

**Issue by grasmachien** [lando/lando#3270]
**Tell us about your setup**
Just a simple LAMP recipe with Lando.

**What is your lando version?**
3.6.0 but I downgraded to 3.5.1 without success.

**Tell us about your .lando.yml**
```
name: boilerplate
recipe: lamp
config:
  webroot: /public
```

**Tell us about the command you were running**
`lando start`

**Tell us generally about your bug**

As the title says I'm currently unable to start any Lando project.
Even the simpelest .lando.yml config returns the following error:

```
Creating boilerplate_webserver_1 ... done
ERROR ==>  message=, stack=Error
    at /snapshot/cli/lib/shell.js
From previous event:
    at Shell.sh (/snapshot/cli/lib/shell.js)
    at Object.dc (/snapshot/cli/lib/bootstrap.js)
    at compose (/snapshot/cli/lib/bootstrap.js)
From previous event:
    at /snapshot/cli/lib/router.js
    at processImmediate (internal/timers.js:464:21)
From previous event:
    at Object.run (/snapshot/cli/lib/router.js)
    at run (/snapshot/cli/lib/engine.js)
    at /snapshot/cli/lib/router.js
From previous event:
    at Object.eventWrapper (/snapshot/cli/lib/router.js)
    at Engine.engineCmd (/snapshot/cli/lib/engine.js)
    at Engine.run (/snapshot/cli/lib/engine.js)
    at Object.runBuild (/snapshot/cli/plugins/lando-services/lib/utils.js)
    at AsyncEvents.<anonymous> (/snapshot/cli/plugins/lando-services/app.js)
    at AsyncEvents.handle (/snapshot/cli/lib/events.js)
    at /snapshot/cli/lib/events.js
From previous event:
    at AsyncEvents.emit (/snapshot/cli/lib/events.js)
From previous event:
    at App.start (/snapshot/cli/lib/app.js)
    at /snapshot/cli/lib/app.js
From previous event:
    at App.rebuild (/snapshot/cli/lib/app.js)
    at Object.run (/snapshot/cli/plugins/lando-core/tasks/rebuild.js)
From previous event:
    at /snapshot/cli/lib/cli.js
From previous event:
    at Object.handler (/snapshot/cli/lib/cli.js)
    at Object.runCommand (/snapshot/cli/node_modules/yargs/lib/command.js:238:44)
    at Object.parseArgs [as _parseArgs] (/snapshot/cli/node_modules/yargs/yargs.js:1063:30)
    at Function.get [as argv] (/snapshot/cli/node_modules/yargs/yargs.js:1004:21)
    at Cli.init (/snapshot/cli/lib/cli.js)
    at Cli.run (/snapshot/cli/lib/cli.js)
    at Object.<anonymous> (/snapshot/cli/bin/lando.js)
    at Module._compile (pkg/prelude/bootstrap.js:1751:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Function.runMain (pkg/prelude/bootstrap.js:1804:12)
    at internal/main/run_main_module.js:17:47, __stackCleaned__=true
```

I have tried;
- downgrading lando to 3.5.1
- uninstalling lando and docker and reinstalling
- lando rebuild
- pruning all volumes, images and containers
- Rebooting computer

Nothing seems to fix this issue...

I'm running the ARM version of lando and docker on a macbook pro M1 PRO with 32gig of RAM.

**Comment by grasmachien** [comment]
The issue seems to be fixed.
I removed all contents from ~/.lando/certs and did another `lando start`.
This fixed all my issues.
I have no clue what caused the issue in the first place but at least there is a fix!

**Comment by gitressa** [comment]
Could it have been the web root having a slash in the front? Normally the folder is without, like this:

```
config:
  webroot: public
```
