### ISSUE TITLE
More actionable error messages

### ISSUE THREAD

**Issue by MarttiR** [lando/lando#3322]
When developing multiple Lando projects, sometimes there are port conflicts, and a service cannot be started.

The error in that case looks like this:

```console
ERROR: for elasticsearch  Cannot start service elasticsearch: driver failed programming external connectivity on endpoint lando_elasticsearch_1 (bc84dfa6c8a7498065f6fa12cba346435518600edbc330816069807b5bd4c18b): Bind for 127.0.0.1:9200 failed: port is already allocated
ERROR: Encountered errors while bringing up the project.
lando 12:10:41 ERROR ==>  message=, stack=Error
    at /snapshot/cli/lib/shell.js
From previous event:
    at Shell.sh (/snapshot/cli/lib/shell.js)
    at Object.dc (/snapshot/cli/lib/bootstrap.js)
    at compose (/snapshot/cli/lib/bootstrap.js)
    at /snapshot/cli/lib/router.js
    at /snapshot/cli/lib/router.js
    at processImmediate (internal/timers.js:464:21)
From previous event:
    at retryEach (/snapshot/cli/lib/router.js)
    at Object.start (/snapshot/cli/lib/router.js)
    at /snapshot/cli/lib/engine.js
    at /snapshot/cli/lib/router.js
From previous event:
    at Object.eventWrapper (/snapshot/cli/lib/router.js)
    at Engine.engineCmd (/snapshot/cli/lib/engine.js)
    at Engine.start (/snapshot/cli/lib/engine.js)
From previous event:
    at App.start (/snapshot/cli/lib/app.js)
    at /snapshot/cli/lib/app.js
From previous event:
    at App.restart (/snapshot/cli/lib/app.js)
    at Object.run (/snapshot/cli/plugins/lando-core/tasks/restart.js)
From previous event:
    at /snapshot/cli/lib/cli.js
From previous event:
    at Object.handler (/snapshot/cli/lib/cli.js)
    at Object.runCommand (/snapshot/cli/node_modules/yargs/lib/command.js:238:44)
    at Object.parseArgs [as _parseArgs] (/snapshot/cli/node_modules/yargs/yargs.js:1063:30)
    at Function.get [as argv] (/snapshot/cli/node_modules/yargs/yargs.js:1004:21)
    at Cli.init (/snapshot/cli/lib/cli.js)
    at Cli.run (/snapshot/cli/lib/cli.js)
    at Object.<anonymous> (/snapshot/cli/bin/lando.js)
    at Module._compile (pkg/prelude/bootstrap.js:1751:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Function.runMain (pkg/prelude/bootstrap.js:1804:12)
    at internal/main/run_main_module.js:17:47, __stackCleaned__=true
lando   12:10:41 VERBOSE ==> reporting error action to report=true, url=https://metrics.lando.dev, report=true, url=https://metrics.lando.dev
lando   12:10:41 DEBUG ==> reported data command=lando restart, context=local, devMode=false, instance=<redacted>, nodeVersion=v14.17.2, mode=cli, type=Darwin, platform=darwin, release=21.3.0, arch=x64, product=lando, version=3.5.1, message=, stack=Error
    at /snapshot/cli/lib/shell.js
From previous event:
    at Shell.sh (shell.js)
    at Object.dc (bootstrap.js)
    at compose (bootstrap.js)
    at /snapshot/cli/lib/router.js
    at /snapshot/cli/lib/router.js
From previous event:
    at retryEach (router.js)
    at Object.start (router.js)
    at /snapshot/cli/lib/engine.js
    at /snapshot/cli/lib/router.js
From previous event:
    at Object.eventWrapper (router.js)
    at Engine.engineCmd (engine.js)
    at Engine.start (engine.js)
From previous event:
    at App.start (app.js)
    at /snapshot/cli/lib/app.js
From previous event:
    at App.restart (app.js)
    at Object.run (restart.js)
From previous event:
    at /snapshot/cli/lib/cli.js
From previous event:
    at Object.handler (cli.js)
    at Object.runCommand (command.js:238:44)
    at Object.parseArgs [as _parseArgs] (yargs.js:1063:30)
    at Function.get [as argv] (yargs.js:1004:21)
    at Cli.init (cli.js)
    at Cli.run (cli.js)
    at Object.<anonymous> (lando.js)
    at Module._compile (bootstrap.js:1751:22)
    at Function.runMain (bootstrap.js:1804:12)
    at internal/main/run_main_module.js:17:47, action=error, created=2022-02-14T11:10:41.883Z
```

This is not that difficult to decipher for seasoned Docker veterans, but newcomers might feel a bit lost. 

1. The most useful part of the error message is at the very end of a long line, which becomes hard to distinguish in a terminal
2. The excessive CLI stacktrace pushes the actual error into scrollback
3. There is another Lando running the same service in the same port, but Lando doesn't account for this

Lando could be more friendly here and tell the user exactly which Lando environment is conflicting with this one, and what are their options to fix the issue :)

**Comment by xtfer** [comment]
I've been chasing this error four five hours now and I still can't work out how to resolve it. It's an absolute mess.

> The most useful part of the error message is at the very end of a long line, which becomes hard to distinguish in a terminal

Which file are you referencing?

**Comment by MarttiR** [comment]
> > The most useful part of the error message is at the very end of a long line, which becomes hard to distinguish in a terminal
> 
> Which file are you referencing?

The first line in the log message above ends with the actual reason, line breaks added for clarity:

> ERROR: for elasticsearch
>
> Cannot start service elasticsearch: 
>
> driver failed programming external connectivity on endpoint lando_elasticsearch_1
>
> (bc84dfa6c8a7498065f6fa12cba346435518600edbc330816069807b5bd4c18b):
>
> **Bind for 127.0.0.1:9200 failed: port is already allocated**
