### ISSUE TITLE
Issue with Lando CA

### ISSUE THREAD

**Issue by xtfer** [lando/lando#3329]
Attempting to build PHP app containers on MacOS 12.1 fails without explanation. This was working previously. 

With 3.6.2 and a completely vanilla LAMP stack using `lando init` on a fresh install of Lando and Docker.

```
 test lando rebuild
? Are you sure you want to rebuild? Yes
Rising anew like a fire phoenix from the ashes! Rebuilding app...
No stopped containers
Pulling appserver ... done
Pulling database  ... done
database uses an image, skipping
appserver uses an image, skipping
Creating network "landoproxyhyperion5000gandalfedition_edge" with driver "bridge"
Creating landoproxyhyperion5000gandalfedition_proxy_1 ... done
Creating network "mylandoapp_default" with the default driver
Creating mylandoapp_appserver_1 ... done
usermod: no changes
usermod: no changes
Starting mylandoapp_appserver_1 ... 
Starting mylandoapp_appserver_1 ... done
ERROR ==>  message=, stack=Error
    at /snapshot/cli/lib/shell.js
From previous event:
    at Shell.sh (/snapshot/cli/lib/shell.js)
    at Object.dc (/snapshot/cli/lib/bootstrap.js)
    at compose (/snapshot/cli/lib/bootstrap.js)
From previous event:
    at /snapshot/cli/lib/router.js
    at processImmediate (internal/timers.js:464:21)
From previous event:
    at Object.run (/snapshot/cli/lib/router.js)
    at run (/snapshot/cli/lib/engine.js)
    at /snapshot/cli/lib/router.js
From previous event:
    at Object.eventWrapper (/snapshot/cli/lib/router.js)
    at Engine.engineCmd (/snapshot/cli/lib/engine.js)
    at Engine.run (/snapshot/cli/lib/engine.js)
    at Object.runBuild (/snapshot/cli/plugins/lando-services/lib/utils.js)
    at AsyncEvents.<anonymous> (/snapshot/cli/plugins/lando-services/app.js)
    at AsyncEvents.handle (/snapshot/cli/lib/events.js)
    at /snapshot/cli/lib/events.js
From previous event:
    at AsyncEvents.emit (/snapshot/cli/lib/events.js)
From previous event:
    at App.start (/snapshot/cli/lib/app.js)
    at /snapshot/cli/lib/app.js
From previous event:
    at App.rebuild (/snapshot/cli/lib/app.js)
    at Object.run (/snapshot/cli/plugins/lando-core/tasks/rebuild.js)
    at /snapshot/cli/lib/cli.js
    at processImmediate (internal/timers.js:464:21)
From previous event:
    at /snapshot/cli/lib/cli.js
From previous event:
    at Object.handler (/snapshot/cli/lib/cli.js)
    at Object.runCommand (/snapshot/cli/node_modules/yargs/lib/command.js:238:44)
    at Object.parseArgs [as _parseArgs] (/snapshot/cli/node_modules/yargs/yargs.js:1063:30)
    at Function.get [as argv] (/snapshot/cli/node_modules/yargs/yargs.js:1004:21)
    at Cli.init (/snapshot/cli/lib/cli.js)
    at Cli.run (/snapshot/cli/lib/cli.js)
    at Object.<anonymous> (/snapshot/cli/bin/lando.js)
    at Module._compile (pkg/prelude/bootstrap.js:1751:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Function.runMain (pkg/prelude/bootstrap.js:1804:12)
    at internal/main/run_main_module.js:17:47, __stackCleaned__=true
Starting mylandoapp_appserver_1 ... done
Creating mylandoapp_database_1  ... done
Waiting until database service is ready...
Waiting until database service is ready...
Waiting until database service is ready...
Scanning to determine which services are ready... Please standby...
Starting mylandoapp_appserver_1 ... done

```

Running under 3.6.0 adds the following output prior to the error

```
OCI runtime exec failed: exec failed: container_linux.go:380: starting container process caused: process_linux.go:130: executing setns process caused: exit status 1: unknown
ERROR ==>  message=, stack=Error
```

**Comment by xtfer** [comment]
Okay, so this was ACTUALLY related to https://github.com/lando/lando/issues/3315. 

Removing ./lando and forcing a new Lando CA fixed it, but it's still a bug, and unless you are a genius like @markb-wa, and think to check certs, you'll never find it.

This was real doozy to track down.

**Comment by backlineint** [comment]
I also ran into this / #3315 Had to uninstall Lando, and this was not resolved until I followed the optional manual step to remove lingering Lando containers with `docker rm -f $(docker ps --filter label=io.lando.container=TRUE --all -q)`

**Comment by xtfer** [comment]
That's probably correct, @backlineint. I think I'd already done that by the time I found the other solution.

**Comment by labboy0276** [comment]
Purging with something like:

```
#!/bin/bash

echo 'Stopping Containers'
# Stop all containers
containers=`docker ps -a -q`
if [ -n "$containers" ] ; then
        docker stop $containers
fi

echo 'Deleting Containers'
# Delete all containers
containers=`docker ps -a -q`
if [ -n "$containers" ]; then
        docker rm -f -v $containers
fi

echo 'Deleting Images'
# Delete all images
images=`docker images -q -a`
if [ -n "$images" ]; then
        docker rmi -f $images
fi

echo 'Pruning Network'
docker network prune -f

echo 'Clearing Lando Cache'
rm -rf ~/.lando
```

Is what we usually recommend when facing weird docker issues like this.  Purging and reinstalling always seems to be the way.

**Comment by xtfer** [comment]
@labboy0276 Only the last step will fix this, clearing the lando cache, since this is a CA issue. I had already tried all the others without success.

Personally Id be keeping this open till you worked out why the CA was failing or had a mechanism for fixing it. I spend over six hours tracking this down, and it would have been a lot easier if there had been an open issue.

**Comment by laxmancozzarin** [comment]
> Purging with something like:
> 
> ```
> #!/bin/bash
> 
> echo 'Stopping Containers'
> # Stop all containers
> containers=`docker ps -a -q`
> if [ -n "$containers" ] ; then
>         docker stop $containers
> fi
> 
> echo 'Deleting Containers'
> # Delete all containers
> containers=`docker ps -a -q`
> if [ -n "$containers" ]; then
>         docker rm -f -v $containers
> fi
> 
> echo 'Deleting Images'
> # Delete all images
> images=`docker images -q -a`
> if [ -n "$images" ]; then
>         docker rmi -f $images
> fi
> 
> echo 'Pruning Network'
> docker network prune -f
> 
> echo 'Clearing Lando Cache'
> rm -rf ~/.lando
> ```
> 
> Is what we usually recommend when facing weird docker issues like this. Purging and reinstalling always seems to be the way.

That worked for me.
Thanks a lot man, I had a hard time figuring out how to fix this problem.
(I use an M2 Pro chip)
