### ISSUE TITLE
Laravel recipe Throws TypeError:  Cannot read property 'type' of undefined

### ISSUE THREAD

**Issue by percymamedy** [lando/lando#3335]
**Lando Version**: 3.6.0
**System**: macOS Monterey, x64
**Docker engine version**: 20.10.8 

Lando file

```yml
name: events
recipe: laravel
config:
  php: '8.0'
  composer_version: 2.0.7
  via: apache
  database: mariadb
  cache: false
  xdebug: false
  webroot: .
```

Running `lando start  -vvv`

```
lando 23:25:36 DEBUG ==> No update available.
lando 23:25:36 VERBOSE ==> starting bootstrap at level app...
lando 23:25:36 VERBOSE ==> config bootstrap beginning...
lando 23:25:36 DEBUG ==> emitting event pre-bootstrap-config
lando 23:25:36 DEBUG ==> plugin lando-core loaded from /snapshot/cli/plugins/lando-core/index.js
lando 23:25:36 DEBUG ==> plugin lando-events loaded from /snapshot/cli/plugins/lando-events/index.js
lando 23:25:36 DEBUG ==> plugin lando-networking loaded from /snapshot/cli/plugins/lando-networking/index.js
lando 23:25:36 DEBUG ==> plugin lando-proxy loaded from /snapshot/cli/plugins/lando-proxy/index.js
lando 23:25:36 DEBUG ==> plugin lando-recipes loaded from /snapshot/cli/plugins/lando-recipes/index.js
lando 23:25:36 DEBUG ==> plugin lando-services loaded from /snapshot/cli/plugins/lando-services/index.js
lando 23:25:36 DEBUG ==> plugin lando-sharing loaded from /snapshot/cli/plugins/lando-sharing/index.js
lando 23:25:36 DEBUG ==> plugin lando-test loaded from /snapshot/cli/plugins/lando-test/index.js
lando 23:25:36 DEBUG ==> plugin lando-tooling loaded from /snapshot/cli/plugins/lando-tooling/index.js
lando 23:25:36 DEBUG ==> plugin @lando/acquia loaded from /snapshot/cli/node_modules/@lando/acquia/index.js
lando 23:25:36 DEBUG ==> plugin @lando/apache loaded from /snapshot/cli/node_modules/@lando/apache/index.js
lando 23:25:36 DEBUG ==> plugin @lando/backdrop loaded from /snapshot/cli/node_modules/@lando/backdrop/index.js
lando 23:25:36 DEBUG ==> plugin @lando/compose loaded from /snapshot/cli/node_modules/@lando/compose/index.js
lando 23:25:36 DEBUG ==> plugin @lando/dotnet loaded from /snapshot/cli/node_modules/@lando/dotnet/index.js
lando 23:25:36 DEBUG ==> plugin @lando/drupal loaded from /snapshot/cli/node_modules/@lando/drupal/index.js
lando 23:25:36 DEBUG ==> plugin @lando/elasticsearch loaded from /snapshot/cli/node_modules/@lando/elasticsearch/index.js
lando 23:25:36 DEBUG ==> plugin @lando/go loaded from /snapshot/cli/node_modules/@lando/go/index.js
lando 23:25:36 DEBUG ==> plugin @lando/joomla loaded from /snapshot/cli/node_modules/@lando/joomla/index.js
lando 23:25:36 DEBUG ==> plugin @lando/lagoon loaded from /snapshot/cli/node_modules/@lando/lagoon/index.js
lando 23:25:36 DEBUG ==> plugin @lando/lamp loaded from /snapshot/cli/node_modules/@lando/lamp/index.js
lando 23:25:36 DEBUG ==> plugin @lando/laravel loaded from /snapshot/cli/node_modules/@lando/laravel/index.js
lando 23:25:36 DEBUG ==> plugin @lando/lemp loaded from /snapshot/cli/node_modules/@lando/lemp/index.js
lando 23:25:36 DEBUG ==> plugin @lando/mailhog loaded from /snapshot/cli/node_modules/@lando/mailhog/index.js
lando 23:25:36 DEBUG ==> plugin @lando/mariadb loaded from /snapshot/cli/node_modules/@lando/mariadb/index.js
lando 23:25:36 DEBUG ==> plugin @lando/mean loaded from /snapshot/cli/node_modules/@lando/mean/index.js
lando 23:25:36 DEBUG ==> plugin @lando/memcached loaded from /snapshot/cli/node_modules/@lando/memcached/index.js
lando 23:25:36 DEBUG ==> plugin @lando/mongo loaded from /snapshot/cli/node_modules/@lando/mongo/index.js
lando 23:25:36 DEBUG ==> plugin @lando/mssql loaded from /snapshot/cli/node_modules/@lando/mssql/index.js
lando 23:25:36 DEBUG ==> plugin @lando/mysql loaded from /snapshot/cli/node_modules/@lando/mysql/index.js
lando 23:25:36 DEBUG ==> plugin @lando/nginx loaded from /snapshot/cli/node_modules/@lando/nginx/index.js
lando 23:25:36 DEBUG ==> plugin @lando/node loaded from /snapshot/cli/node_modules/@lando/node/index.js
lando 23:25:36 DEBUG ==> plugin @lando/pantheon loaded from /snapshot/cli/node_modules/@lando/pantheon/index.js
lando 23:25:36 DEBUG ==> plugin @lando/php loaded from /snapshot/cli/node_modules/@lando/php/index.js
lando 23:25:36 DEBUG ==> plugin @lando/phpmyadmin loaded from /snapshot/cli/node_modules/@lando/phpmyadmin/index.js
lando 23:25:36 DEBUG ==> plugin @lando/platformsh loaded from /snapshot/cli/node_modules/@lando/platformsh/index.js
lando 23:25:36 DEBUG ==> plugin @lando/postgres loaded from /snapshot/cli/node_modules/@lando/postgres/index.js
lando 23:25:36 DEBUG ==> plugin @lando/python loaded from /snapshot/cli/node_modules/@lando/python/index.js
lando 23:25:36 DEBUG ==> plugin @lando/redis loaded from /snapshot/cli/node_modules/@lando/redis/index.js
lando 23:25:36 DEBUG ==> plugin @lando/ruby loaded from /snapshot/cli/node_modules/@lando/ruby/index.js
lando 23:25:36 DEBUG ==> plugin @lando/solr loaded from /snapshot/cli/node_modules/@lando/solr/index.js
lando 23:25:36 DEBUG ==> plugin @lando/symfony loaded from /snapshot/cli/node_modules/@lando/symfony/index.js
lando 23:25:36 DEBUG ==> plugin @lando/tomcat loaded from /snapshot/cli/node_modules/@lando/tomcat/index.js
lando 23:25:36 DEBUG ==> plugin @lando/varnish loaded from /snapshot/cli/node_modules/@lando/varnish/index.js
lando 23:25:36 DEBUG ==> plugin @lando/wordpress loaded from /snapshot/cli/node_modules/@lando/wordpress/index.js
lando 23:25:36 DEBUG ==> emitting event post-bootstrap-config
lando 23:25:36 VERBOSE ==> building proxy config...
lando 23:25:36 VERBOSE ==> config bootstrap completed.
lando 23:25:36 VERBOSE ==> tasks bootstrap beginning...
lando 23:25:36 DEBUG ==> emitting event pre-bootstrap-tasks
lando 23:25:37 DEBUG ==> autoloaded task config
lando 23:25:37 DEBUG ==> autoloaded task destroy
lando 23:25:37 DEBUG ==> autoloaded task info
lando 23:25:37 DEBUG ==> autoloaded task list
lando 23:25:37 DEBUG ==> autoloaded task logs
lando 23:25:37 DEBUG ==> autoloaded task poweroff
lando 23:25:37 DEBUG ==> autoloaded task rebuild
lando 23:25:37 DEBUG ==> autoloaded task restart
lando 23:25:37 DEBUG ==> autoloaded task share
lando 23:25:37 DEBUG ==> autoloaded task start
lando 23:25:37 DEBUG ==> autoloaded task stop
lando 23:25:37 DEBUG ==> autoloaded task version
lando 23:25:37 DEBUG ==> autoloaded task init
lando 23:25:37 DEBUG ==> autoloaded task ssh
lando 23:25:37 DEBUG ==> emitting event post-bootstrap-tasks
lando 23:25:37 VERBOSE ==> tasks bootstrap completed.
lando 23:25:37 VERBOSE ==> engine bootstrap beginning...
lando 23:25:37 DEBUG ==> emitting event pre-bootstrap-engine
lando 23:25:37 DEBUG ==> automoved scripts from /snapshot/cli/plugins/lando-core/scripts to /Users/percymamedy/.lando/scripts and set to mode 755
lando 23:25:37 DEBUG ==> automoved scripts from /snapshot/cli/plugins/lando-proxy/scripts to /Users/percymamedy/.lando/scripts and set to mode 755
lando 23:25:37 DEBUG ==> automoved scripts from /snapshot/cli/plugins/lando-recipes/scripts to /Users/percymamedy/.lando/scripts and set to mode 755
lando 23:25:37 DEBUG ==> automoved scripts from /snapshot/cli/plugins/lando-services/scripts to /Users/percymamedy/.lando/scripts and set to mode 755
lando 23:25:37 DEBUG ==> automoved scripts from /snapshot/cli/plugins/lando-sharing/scripts to /Users/percymamedy/.lando/scripts and set to mode 755
lando 23:25:37 DEBUG ==> automoved scripts from /snapshot/cli/node_modules/@lando/acquia/scripts to /Users/percymamedy/.lando/scripts and set to mode 755
lando 23:25:37 DEBUG ==> automoved scripts from /snapshot/cli/node_modules/@lando/lagoon/scripts to /Users/percymamedy/.lando/scripts and set to mode 755
lando 23:25:37 DEBUG ==> automoved scripts from /snapshot/cli/node_modules/@lando/pantheon/scripts to /Users/percymamedy/.lando/scripts and set to mode 755
lando 23:25:37 DEBUG ==> automoved scripts from /snapshot/cli/node_modules/@lando/platformsh/scripts to /Users/percymamedy/.lando/scripts and set to mode 755
lando 23:25:37 DEBUG ==> emitting event post-bootstrap-engine
lando 23:25:37 VERBOSE ==> engine bootstrap completed.
lando 23:25:37 VERBOSE ==> app bootstrap beginning...
lando 23:25:37 DEBUG ==> emitting event pre-bootstrap-app
lando 23:25:37 DEBUG ==> autoloaded builder LandoCompose
lando 23:25:37 DEBUG ==> autoloaded builder LandoAppserver
lando 23:25:37 DEBUG ==> autoloaded builder LandoService
lando 23:25:37 DEBUG ==> autoloaded builder LandoUtility
lando 23:25:37 DEBUG ==> autoloaded builder LandoWebServer
lando 23:25:37 DEBUG ==> autoloaded builder LandoDrupal
lando 23:25:37 DEBUG ==> autoloaded builder LandoLaemp
lando 23:25:37 DEBUG ==> autoloaded builder LandoAppserver
lando 23:25:37 DEBUG ==> autoloaded builder LandoPlatformAppserver
lando 23:25:37 DEBUG ==> autoloaded builder LandoPlatformService
lando 23:25:37 DEBUG ==> autoloaded builder LandoCa
lando 23:25:37 DEBUG ==> autoloaded builder LandoProxy
lando 23:25:37 DEBUG ==> autoloaded builder LandoInit
lando 23:25:37 DEBUG ==> autoloaded builder LandoMounter
lando 23:25:37 DEBUG ==> autoloaded builder LandoApache
lando 23:25:37 DEBUG ==> autoloaded builder LandoCompose
lando 23:25:37 DEBUG ==> autoloaded builder LandoDotNet
lando 23:25:37 DEBUG ==> autoloaded builder LandoElasticSearch
lando 23:25:37 DEBUG ==> autoloaded builder LandoGo
lando 23:25:37 DEBUG ==> autoloaded builder LandoLagoonElasticsearch
lando 23:25:37 DEBUG ==> autoloaded builder LandoLagoonMariaDb
lando 23:25:37 DEBUG ==> autoloaded builder LandoLagoonNginx
lando 23:25:37 DEBUG ==> autoloaded builder LandoLagoonNone
lando 23:25:37 DEBUG ==> autoloaded builder LandoLagoonPhp
lando 23:25:37 DEBUG ==> autoloaded builder LandoLagoonPhp
lando 23:25:37 DEBUG ==> autoloaded builder LandoLagoonPostgres
lando 23:25:37 DEBUG ==> autoloaded builder LandoLagoonRedis
lando 23:25:37 DEBUG ==> autoloaded builder LandoLagoonSolr
lando 23:25:37 DEBUG ==> autoloaded builder LandoLagoonVarnish
lando 23:25:37 DEBUG ==> autoloaded builder LandoMailHog
lando 23:25:37 DEBUG ==> autoloaded builder LandoMariaDb
lando 23:25:37 DEBUG ==> autoloaded builder LandoMemcached
lando 23:25:37 DEBUG ==> autoloaded builder LandoMongoDb
lando 23:25:37 DEBUG ==> autoloaded builder LandoMsSql
lando 23:25:37 DEBUG ==> autoloaded builder LandoMySql
lando 23:25:37 DEBUG ==> autoloaded builder LandoNginx
lando 23:25:37 DEBUG ==> autoloaded builder LandoNode
lando 23:25:37 DEBUG ==> autoloaded builder PantheonMariaDb
lando 23:25:37 DEBUG ==> autoloaded builder LandoPhp
lando 23:25:37 DEBUG ==> autoloaded builder LandoPma
lando 23:25:37 DEBUG ==> autoloaded builder LandoPlatformshChromeHeadless
lando 23:25:37 DEBUG ==> autoloaded builder LandoPlatformsElasticsearch
lando 23:25:37 DEBUG ==> autoloaded builder LandoPlatformshInfluxdb
lando 23:25:37 DEBUG ==> autoloaded builder LandoPlatformshKafka
lando 23:25:37 DEBUG ==> autoloaded builder LandoPlatformshMariaDB
lando 23:25:37 DEBUG ==> autoloaded builder LandoPlatformshMemcached
lando 23:25:37 DEBUG ==> autoloaded builder LandoPlatformsMongoDB
lando 23:25:37 DEBUG ==> autoloaded builder LandoPlatformshMySQL
lando 23:25:37 DEBUG ==> autoloaded builder LandoPlatformshPhp
lando 23:25:37 DEBUG ==> autoloaded builder LandoPlatformshPostgres
lando 23:25:37 DEBUG ==> autoloaded builder LandoPlatformshRabbitmq
lando 23:25:37 DEBUG ==> autoloaded builder LandoPlatformshRedis
lando 23:25:37 DEBUG ==> autoloaded builder LandoPlatformshSolr
lando 23:25:37 DEBUG ==> autoloaded builder LandoPlatformshVarnish
lando 23:25:37 DEBUG ==> autoloaded builder LandoPostgres
lando 23:25:37 DEBUG ==> autoloaded builder LandoPython
lando 23:25:37 DEBUG ==> autoloaded builder LandoRedis
lando 23:25:37 DEBUG ==> autoloaded builder LandoRuby
lando 23:25:37 DEBUG ==> autoloaded builder LandoSolr
lando 23:25:37 DEBUG ==> autoloaded builder LandoTomcat
lando 23:25:37 DEBUG ==> autoloaded builder LandoVarnish
lando 23:25:37 DEBUG ==> autoloaded builder LandoAcquia
lando 23:25:37 DEBUG ==> autoloaded builder LandoBackdrop
lando 23:25:37 DEBUG ==> autoloaded builder LandoDrupal10
lando 23:25:37 DEBUG ==> autoloaded builder LandoDrupal6
lando 23:25:37 DEBUG ==> autoloaded builder LandoDrupal7
lando 23:25:37 DEBUG ==> autoloaded builder LandoDrupal8
lando 23:25:37 DEBUG ==> autoloaded builder LandoDrupal9
lando 23:25:37 DEBUG ==> autoloaded builder LandoJoomla
lando 23:25:37 DEBUG ==> autoloaded builder LandoLagoon
lando 23:25:37 DEBUG ==> autoloaded builder LandoLamp
lando 23:25:37 DEBUG ==> autoloaded builder LandoLaravel
lando 23:25:37 DEBUG ==> autoloaded builder LandoLamp
lando 23:25:37 DEBUG ==> autoloaded builder LandoMean
lando 23:25:37 DEBUG ==> autoloaded builder LandoPantheon
lando 23:25:37 DEBUG ==> autoloaded builder LandoPlatformsh
lando 23:25:37 DEBUG ==> autoloaded builder LandoSymfony
lando 23:25:37 DEBUG ==> autoloaded builder LandoWordPress
lando 23:25:37 DEBUG ==> emitting event post-bootstrap-app
lando 23:25:37 VERBOSE ==> app bootstrap completed.
lando 23:25:37 VERBOSE ==> bootstrap completed.
lando 23:25:37 DEBUG ==> emitting event post-bootstrap
lando 23:25:37 VERBOSE ==> docker-engine exists: true
lando 23:25:37 VERBOSE ==> docker-compose exists: true
lando 23:25:37 DEBUG ==> emitting event cli-answers
lando 23:25:37 DEBUG ==> emitting event cli-start-answers
lando 23:25:37 DEBUG ==> emitting event cli-run
lando 23:25:37 DEBUG ==> emitting event cli-start-run
lando 23:25:37 INFO ==> loading app assurdeal-events from config files 0=/Users/percymamedy/Documents/Code/assurdeal/events/.lando.yml
lando 23:25:37 DEBUG ==> app assurdeal-events has config name=assurdeal-events, recipe=laravel, php=8.0, composer_version=2.0.7, via=apache, database=mariadb, cache=false, xdebug=false, webroot=.
Let's get this party started! Starting app assurdeal-events...
assurdeal-events 23:25:37 INFO ==> starting app...
assurdeal-events 23:25:37 VERBOSE ==> initiatilizing app at /Users/percymamedy/Documents/Code/assurdeal/events...
lando            23:25:37 DEBUG ==> plugin lando-core loaded from /snapshot/cli/plugins/lando-core/app.js
lando            23:25:37 DEBUG ==> plugin lando-events loaded from /snapshot/cli/plugins/lando-events/app.js
lando            23:25:37 DEBUG ==> plugin lando-networking loaded from /snapshot/cli/plugins/lando-networking/app.js
assurdeal-events 23:25:37 VERBOSE ==> proxy settings detected.
lando            23:25:37 DEBUG ==> plugin lando-proxy loaded from /snapshot/cli/plugins/lando-proxy/app.js
lando            23:25:37 DEBUG ==> plugin lando-recipes loaded from /snapshot/cli/plugins/lando-recipes/app.js
lando            23:25:37 DEBUG ==> plugin lando-services loaded from /snapshot/cli/plugins/lando-services/app.js
lando            23:25:37 DEBUG ==> plugin lando-sharing loaded from /snapshot/cli/plugins/lando-sharing/app.js
lando            23:25:37 DEBUG ==> plugin lando-tooling loaded from /snapshot/cli/plugins/lando-tooling/app.js
lando            23:25:37 DEBUG ==> plugin @lando/acquia loaded from /snapshot/cli/node_modules/@lando/acquia/app.js
lando            23:25:37 DEBUG ==> plugin @lando/lagoon loaded from /snapshot/cli/node_modules/@lando/lagoon/app.js
lando            23:25:37 DEBUG ==> plugin @lando/pantheon loaded from /snapshot/cli/node_modules/@lando/pantheon/app.js
lando            23:25:37 DEBUG ==> plugin @lando/platformsh loaded from /snapshot/cli/node_modules/@lando/platformsh/app.js
assurdeal-events 23:25:37 DEBUG ==> emitting event pre-init
assurdeal-events 23:25:37 VERBOSE ==> building laravel recipe named
lando            23:25:37 VERBOSE ==> proxy is ON.
lando            23:25:37 VERBOSE ==> Setting the default proxy certificate /certs/cert.crt
assurdeal-events 23:25:37 VERBOSE ==> building php service appserver
assurdeal-events 23:25:37 VERBOSE ==> building mariadb service database
assurdeal-events 23:25:37 DEBUG ==> emitting event post-init
assurdeal-events 23:25:37 DEBUG ==> adding hostnames to the app...
assurdeal-events 23:25:37 DEBUG ==> hostnames added to appserver 0=appserver.assurdealevents.internal
assurdeal-events 23:25:37 DEBUG ==> hostnames added to database 0=database.assurdealevents.internal
assurdeal-events 23:25:37 VERBOSE ==> attempting to find open services...
lando            23:25:37 VERBOSE ==> checking docker version compatibility...
lando            23:25:37 DEBUG ==> compatibility results name=desktop, link=https://docs.docker.com/docker-for-mac/release-notes/, wants=2.1.0.0 - 3.6.99, version=4.5.0, semversion=4.5.0, semmin=2.1.0, semmax=3.6.99, dockerVersion=true, satisfied=false
lando            23:25:37 DEBUG ==> engine is up.
lando            23:25:37 DEBUG ==> docker is running.
assurdeal-events 23:25:37 DEBUG ==> engine is up.
assurdeal-events 23:25:38 VERBOSE ==> refreshing certificates... 0=appserver, 1=database
assurdeal-events 23:25:38 VERBOSE ==> perm sweeping flagged non-root containers ... 0=database
assurdeal-events 23:25:38 VERBOSE ==> analyzing user ssh keys... using 10 of 10
assurdeal-events 23:25:38 DEBUG ==> key config...  none
assurdeal-events 23:25:38 VERBOSE ==> additional tooling detected
assurdeal-events 23:25:38 DEBUG ==> adding app cli task composer
assurdeal-events 23:25:38 DEBUG ==> adding app cli task db-import <file>
assurdeal-events 23:25:38 DEBUG ==> adding app cli task db-export [file]
assurdeal-events 23:25:38 DEBUG ==> adding app cli task php
assurdeal-events 23:25:38 DEBUG ==> adding app cli task mysql
assurdeal-events 23:25:38 DEBUG ==> adding app cli task laravel
assurdeal-events 23:25:38 DEBUG ==> adding app cli task artisan
assurdeal-events 23:25:38 VERBOSE ==> setting LANDO_INFO...
assurdeal-events 23:25:38 DEBUG ==> ensuring exposed ports on appserver are bound to 127.0.0.1
assurdeal-events 23:25:38 DEBUG ==> ensuring exposed ports on appserver are bound to 127.0.0.1
assurdeal-events 23:25:38 DEBUG ==> ensuring exposed ports on database are bound to 127.0.0.1
assurdeal-events 23:25:38 VERBOSE ==> app is ready!
assurdeal-events 23:25:38 DEBUG ==> emitting event ready
assurdeal-events 23:25:38 VERBOSE ==> discovering dynamic portforward info...
assurdeal-events 23:25:38 ERROR ==> Cannot read property 'type' of undefined message=Cannot read property 'type' of undefined, stack=TypeError: Cannot read property 'type' of undefined
    at /snapshot/cli/lib/utils.js
    at /snapshot/cli/node_modules/lodash/lodash.js:3585:27
    at /snapshot/cli/node_modules/lodash/lodash.js:4967:15
    at baseForOwn (/snapshot/cli/node_modules/lodash/lodash.js:3032:24)
    at /snapshot/cli/node_modules/lodash/lodash.js:4936:18
    at baseMap (/snapshot/cli/node_modules/lodash/lodash.js:3584:7)
    at Function.map (/snapshot/cli/node_modules/lodash/lodash.js:9622:14)
    at Object.metricsParse (/snapshot/cli/lib/utils.js)
    at /snapshot/cli/lib/app.js
From previous event:
    at initAndReport (/snapshot/cli/lib/app.js)
    at App.start (/snapshot/cli/lib/app.js)
    at Object.run (/snapshot/cli/plugins/lando-core/tasks/start.js)
From previous event:
    at /snapshot/cli/lib/cli.js
From previous event:
    at Object.handler (/snapshot/cli/lib/cli.js)
    at Object.runCommand (/snapshot/cli/node_modules/yargs/lib/command.js:238:44)
    at Object.parseArgs [as _parseArgs] (/snapshot/cli/node_modules/yargs/yargs.js:1063:30)
    at Function.get [as argv] (/snapshot/cli/node_modules/yargs/yargs.js:1004:21)
    at Cli.init (/snapshot/cli/lib/cli.js)
    at Cli.run (/snapshot/cli/lib/cli.js)
    at Object.<anonymous> (/snapshot/cli/bin/lando.js)
    at Module._compile (pkg/prelude/bootstrap.js:1751:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Function.runMain (pkg/prelude/bootstrap.js:1804:12)
    at internal/main/run_main_module.js:17:47, __stackCleaned__=true

██╗   ██╗██╗  ██╗     ██████╗ ██╗  ██╗██╗
██║   ██║██║  ██║    ██╔═══██╗██║  ██║██║
██║   ██║███████║    ██║   ██║███████║██║
██║   ██║██╔══██║    ██║   ██║██╔══██║╚═╝
╚██████╔╝██║  ██║    ╚██████╔╝██║  ██║██╗
 ╚═════╝ ╚═╝  ╚═╝     ╚═════╝ ╚═╝  ╚═╝╚═╝


An error occurred while starting up your app!
Here are a few things you can try to get back into a good state:

  ■ Try running lando rebuild
  ■ Try restarting in debug mode lando restart -vvv
  ■ Try checking the logs with lando logs

If those fail then consult the troubleshooting materials:

  ■ https://docs.lando.dev/help/logs.html
  ■ https://docs.lando.dev/help/updating.html

Or post your issue to Slack or GitHub

  ■ Slack - https://launchpass.com/devwithlando
  ■ GitHub - https://github.com/lando/lando/issues/new/choose

lando            23:25:38 ERROR ==> TypeError: Cannot read property 'type' of undefined
    at /snapshot/cli/lib/utils.js
    at /snapshot/cli/node_modules/lodash/lodash.js:3585:27
    at /snapshot/cli/node_modules/lodash/lodash.js:4967:15
    at baseForOwn (/snapshot/cli/node_modules/lodash/lodash.js:3032:24)
    at /snapshot/cli/node_modules/lodash/lodash.js:4936:18
    at baseMap (/snapshot/cli/node_modules/lodash/lodash.js:3584:7)
    at Function.map (/snapshot/cli/node_modules/lodash/lodash.js:9622:14)
    at Object.metricsParse (/snapshot/cli/lib/utils.js)
    at /snapshot/cli/lib/app.js
From previous event:
    at initAndReport (/snapshot/cli/lib/app.js)
    at App.start (/snapshot/cli/lib/app.js)
    at Object.run (/snapshot/cli/plugins/lando-core/tasks/start.js)
From previous event:
    at /snapshot/cli/lib/cli.js
From previous event:
    at Object.handler (/snapshot/cli/lib/cli.js)
    at Object.runCommand (/snapshot/cli/node_modules/yargs/lib/command.js:238:44)
    at Object.parseArgs [as _parseArgs] (/snapshot/cli/node_modules/yargs/yargs.js:1063:30)
    at Function.get [as argv] (/snapshot/cli/node_modules/yargs/yargs.js:1004:21)
    at Cli.init (/snapshot/cli/lib/cli.js)
    at Cli.run (/snapshot/cli/lib/cli.js)
    at Object.<anonymous> (/snapshot/cli/bin/lando.js)
    at Module._compile (pkg/prelude/bootstrap.js:1751:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Function.runMain (pkg/prelude/bootstrap.js:1804:12)
    at internal/main/run_main_module.js:17:47
```

**Comment by percymamedy** [comment]
Updates:

Need to remove 

```
  cache: false
```
