### ISSUE TITLE
Unable to start the proxy

### ISSUE THREAD

**Issue by musicaljoeker** [lando/lando#3336]
I am unable to start lando with the proxy. Here's the verbose output of my `lando start -vvv`. Any help is appreciated.

```
joseph@charlie:~/dev/Cw/Breeze/breezitory$ lando start -vvv
lando 19:23:00 DEBUG ==> No update available. 
lando 19:23:00 VERBOSE ==> starting bootstrap at level app... 
lando 19:23:00 VERBOSE ==> config bootstrap beginning... 
lando 19:23:00 DEBUG ==> emitting event pre-bootstrap-config 
lando 19:23:00 DEBUG ==> plugin lando-core loaded from /snapshot/cli/plugins/lando-core/index.js 
lando 19:23:00 DEBUG ==> plugin lando-events loaded from /snapshot/cli/plugins/lando-events/index.js 
lando 19:23:00 DEBUG ==> plugin lando-networking loaded from /snapshot/cli/plugins/lando-networking/index.js 
lando 19:23:00 DEBUG ==> plugin lando-proxy loaded from /snapshot/cli/plugins/lando-proxy/index.js 
lando 19:23:00 DEBUG ==> plugin lando-recipes loaded from /snapshot/cli/plugins/lando-recipes/index.js 
lando 19:23:00 DEBUG ==> plugin lando-services loaded from /snapshot/cli/plugins/lando-services/index.js 
lando 19:23:00 DEBUG ==> plugin lando-sharing loaded from /snapshot/cli/plugins/lando-sharing/index.js 
lando 19:23:00 DEBUG ==> plugin lando-test loaded from /snapshot/cli/plugins/lando-test/index.js 
lando 19:23:00 DEBUG ==> plugin lando-tooling loaded from /snapshot/cli/plugins/lando-tooling/index.js 
lando 19:23:00 DEBUG ==> plugin @lando/acquia loaded from /snapshot/cli/node_modules/@lando/acquia/index.js 
lando 19:23:00 DEBUG ==> plugin @lando/lagoon loaded from /snapshot/cli/node_modules/@lando/lagoon/index.js 
lando 19:23:00 DEBUG ==> plugin @lando/pantheon loaded from /snapshot/cli/node_modules/@lando/pantheon/index.js 
lando 19:23:00 DEBUG ==> plugin @lando/platformsh loaded from /snapshot/cli/node_modules/@lando/platformsh/index.js 
lando 19:23:00 DEBUG ==> emitting event post-bootstrap-config 
lando 19:23:00 VERBOSE ==> building proxy config... 
lando 19:23:00 VERBOSE ==> config bootstrap completed. 
lando 19:23:00 VERBOSE ==> tasks bootstrap beginning... 
lando 19:23:00 DEBUG ==> emitting event pre-bootstrap-tasks 
lando 19:23:00 DEBUG ==> autoloaded task config 
lando 19:23:00 DEBUG ==> autoloaded task destroy 
lando 19:23:00 DEBUG ==> autoloaded task info 
lando 19:23:00 DEBUG ==> autoloaded task list 
lando 19:23:00 DEBUG ==> autoloaded task logs 
lando 19:23:00 DEBUG ==> autoloaded task poweroff 
lando 19:23:00 DEBUG ==> autoloaded task rebuild 
lando 19:23:00 DEBUG ==> autoloaded task restart 
lando 19:23:00 DEBUG ==> autoloaded task share 
lando 19:23:00 DEBUG ==> autoloaded task start 
lando 19:23:00 DEBUG ==> autoloaded task stop 
lando 19:23:00 DEBUG ==> autoloaded task version 
lando 19:23:00 DEBUG ==> autoloaded task init 
lando 19:23:00 DEBUG ==> autoloaded task ssh 
lando 19:23:00 DEBUG ==> emitting event post-bootstrap-tasks 
lando 19:23:00 VERBOSE ==> tasks bootstrap completed. 
lando 19:23:00 VERBOSE ==> engine bootstrap beginning... 
lando 19:23:00 DEBUG ==> emitting event pre-bootstrap-engine 
lando 19:23:00 DEBUG ==> automoved scripts from /snapshot/cli/plugins/lando-core/scripts to /home/joseph/.lando/scripts and set to mode 755 
lando 19:23:00 DEBUG ==> automoved scripts from /snapshot/cli/plugins/lando-proxy/scripts to /home/joseph/.lando/scripts and set to mode 755 
lando 19:23:00 DEBUG ==> automoved scripts from /snapshot/cli/plugins/lando-recipes/scripts to /home/joseph/.lando/scripts and set to mode 755 
lando 19:23:00 DEBUG ==> automoved scripts from /snapshot/cli/plugins/lando-services/scripts to /home/joseph/.lando/scripts and set to mode 755 
lando 19:23:00 DEBUG ==> automoved scripts from /snapshot/cli/plugins/lando-sharing/scripts to /home/joseph/.lando/scripts and set to mode 755 
lando 19:23:00 DEBUG ==> automoved scripts from /snapshot/cli/node_modules/@lando/acquia/scripts to /home/joseph/.lando/scripts and set to mode 755 
lando 19:23:00 DEBUG ==> automoved scripts from /snapshot/cli/node_modules/@lando/lagoon/scripts to /home/joseph/.lando/scripts and set to mode 755 
lando 19:23:00 DEBUG ==> automoved scripts from /snapshot/cli/node_modules/@lando/pantheon/scripts to /home/joseph/.lando/scripts and set to mode 755 
lando 19:23:00 DEBUG ==> automoved scripts from /snapshot/cli/node_modules/@lando/platformsh/scripts to /home/joseph/.lando/scripts and set to mode 755 
lando 19:23:00 DEBUG ==> emitting event post-bootstrap-engine 
lando 19:23:00 VERBOSE ==> engine bootstrap completed. 
lando 19:23:00 VERBOSE ==> app bootstrap beginning... 
lando 19:23:00 DEBUG ==> emitting event pre-bootstrap-app 
lando 19:23:00 DEBUG ==> autoloaded builder LandoCompose 
lando 19:23:00 DEBUG ==> autoloaded builder LandoAppserver 
lando 19:23:00 DEBUG ==> autoloaded builder LandoService 
lando 19:23:00 DEBUG ==> autoloaded builder LandoUtility 
lando 19:23:00 DEBUG ==> autoloaded builder LandoWebServer 
lando 19:23:00 DEBUG ==> autoloaded builder LandoDrupal 
lando 19:23:00 DEBUG ==> autoloaded builder LandoLaemp 
lando 19:23:00 DEBUG ==> autoloaded builder LandoAppserver 
lando 19:23:00 DEBUG ==> autoloaded builder LandoPlatformAppserver 
lando 19:23:00 DEBUG ==> autoloaded builder LandoPlatformService 
lando 19:23:00 DEBUG ==> autoloaded builder LandoCa 
lando 19:23:00 DEBUG ==> autoloaded builder LandoProxy 
lando 19:23:00 DEBUG ==> autoloaded builder LandoInit 
lando 19:23:00 DEBUG ==> autoloaded builder LandoApache 
lando 19:23:00 DEBUG ==> autoloaded builder LandoCompose 
lando 19:23:00 DEBUG ==> autoloaded builder LandoDotNet 
lando 19:23:00 DEBUG ==> autoloaded builder LandoElasticSearch 
lando 19:23:00 DEBUG ==> autoloaded builder LandoGo 
lando 19:23:00 DEBUG ==> autoloaded builder LandoMailHog 
lando 19:23:00 DEBUG ==> autoloaded builder LandoMariaDb 
lando 19:23:00 DEBUG ==> autoloaded builder LandoMemcached 
lando 19:23:00 DEBUG ==> autoloaded builder LandoMongoDb 
lando 19:23:00 DEBUG ==> autoloaded builder LandoMsSql 
lando 19:23:00 DEBUG ==> autoloaded builder LandoMySql 
lando 19:23:00 DEBUG ==> autoloaded builder LandoNginx 
lando 19:23:00 DEBUG ==> autoloaded builder LandoNode 
lando 19:23:00 DEBUG ==> autoloaded builder LandoPhp 
lando 19:23:00 DEBUG ==> autoloaded builder LandoPma 
lando 19:23:00 DEBUG ==> autoloaded builder LandoPostgres 
lando 19:23:00 DEBUG ==> autoloaded builder LandoPython 
lando 19:23:00 DEBUG ==> autoloaded builder LandoRedis 
lando 19:23:00 DEBUG ==> autoloaded builder LandoRuby 
lando 19:23:00 DEBUG ==> autoloaded builder LandoSolr 
lando 19:23:00 DEBUG ==> autoloaded builder LandoTomcat 
lando 19:23:00 DEBUG ==> autoloaded builder LandoVarnish 
lando 19:23:00 DEBUG ==> autoloaded builder LandoMounter 
lando 19:23:00 DEBUG ==> autoloaded builder LandoLagoonElasticsearch 
lando 19:23:00 DEBUG ==> autoloaded builder LandoLagoonMariaDb 
lando 19:23:00 DEBUG ==> autoloaded builder LandoLagoonNginx 
lando 19:23:00 DEBUG ==> autoloaded builder LandoLagoonNone 
lando 19:23:00 DEBUG ==> autoloaded builder LandoLagoonPhp 
lando 19:23:00 DEBUG ==> autoloaded builder LandoLagoonPhp 
lando 19:23:00 DEBUG ==> autoloaded builder LandoLagoonPostgres 
lando 19:23:00 DEBUG ==> autoloaded builder LandoLagoonRedis 
lando 19:23:00 DEBUG ==> autoloaded builder LandoLagoonSolr 
lando 19:23:00 DEBUG ==> autoloaded builder LandoLagoonVarnish 
lando 19:23:00 DEBUG ==> autoloaded builder PantheonMariaDb 
lando 19:23:00 DEBUG ==> autoloaded builder LandoPlatformshChromeHeadless 
lando 19:23:00 DEBUG ==> autoloaded builder LandoPlatformsElasticsearch 
lando 19:23:00 DEBUG ==> autoloaded builder LandoPlatformshInfluxdb 
lando 19:23:00 DEBUG ==> autoloaded builder LandoPlatformshKafka 
lando 19:23:00 DEBUG ==> autoloaded builder LandoPlatformshMariaDB 
lando 19:23:00 DEBUG ==> autoloaded builder LandoPlatformshMemcached 
lando 19:23:00 DEBUG ==> autoloaded builder LandoPlatformsMongoDB 
lando 19:23:00 DEBUG ==> autoloaded builder LandoPlatformshMySQL 
lando 19:23:00 DEBUG ==> autoloaded builder LandoPlatformshPhp 
lando 19:23:00 DEBUG ==> autoloaded builder LandoPlatformshPostgres 
lando 19:23:00 DEBUG ==> autoloaded builder LandoPlatformshRabbitmq 
lando 19:23:00 DEBUG ==> autoloaded builder LandoPlatformshRedis 
lando 19:23:00 DEBUG ==> autoloaded builder LandoPlatformshSolr 
lando 19:23:00 DEBUG ==> autoloaded builder LandoPlatformshVarnish 
lando 19:23:00 DEBUG ==> autoloaded builder LandoBackdrop 
lando 19:23:00 DEBUG ==> autoloaded builder LandoDrupal6 
lando 19:23:00 DEBUG ==> autoloaded builder LandoDrupal7 
lando 19:23:00 DEBUG ==> autoloaded builder LandoDrupal8 
lando 19:23:00 DEBUG ==> autoloaded builder LandoDrupal9 
lando 19:23:00 DEBUG ==> autoloaded builder LandoJoomla 
lando 19:23:00 DEBUG ==> autoloaded builder LandoLamp 
lando 19:23:00 DEBUG ==> autoloaded builder LandoLaravel 
lando 19:23:00 DEBUG ==> autoloaded builder LandoLamp 
lando 19:23:00 DEBUG ==> autoloaded builder LandoMean 
lando 19:23:00 DEBUG ==> autoloaded builder LandoSymfony 
lando 19:23:00 DEBUG ==> autoloaded builder LandoWordPress 
lando 19:23:00 DEBUG ==> autoloaded builder LandoAcquia 
lando 19:23:00 DEBUG ==> autoloaded builder LandoLagoon 
lando 19:23:00 DEBUG ==> autoloaded builder LandoPantheon 
lando 19:23:00 DEBUG ==> autoloaded builder LandoPlatformsh 
lando 19:23:00 DEBUG ==> emitting event post-bootstrap-app 
lando 19:23:00 VERBOSE ==> app bootstrap completed. 
lando 19:23:00 VERBOSE ==> bootstrap completed. 
lando 19:23:00 DEBUG ==> emitting event post-bootstrap 
lando 19:23:00 VERBOSE ==> docker-engine exists: true 
lando 19:23:00 VERBOSE ==> docker-compose exists: true 
lando 19:23:00 DEBUG ==> emitting event cli-answers 
lando 19:23:00 DEBUG ==> emitting event cli-start-answers 
lando 19:23:00 DEBUG ==> emitting event cli-run 
lando 19:23:00 DEBUG ==> emitting event cli-start-run 
lando 19:23:00 INFO ==> loading app breeze-avenue from config files 0=/home/joseph/dev/Cw/Breeze/breezitory/.lando.yml
lando 19:23:00 DEBUG ==> app breeze-avenue has config name=breeze-avenue, php=[breezeavenue.lndo.site], type=node:14, ssl=true, type=php:8.0, via=apache, xdebug=false, webroot=public, description=Installs all composer and node packages, dir=/app, cmd=[php=composer install, node=yarn], description=Run yarn commands, service=node, dir=/app, cmd=yarn, description=Builds production version of the front end application., service=node, dir=/app, cmd=yarn build, description=Watches and rebuild assets as files change, service=node, dir=/app, cmd=yarn watch, description=Runs initial script to setup the .env file for the site, dir=/app, service=php, cmd=[bin/site-setup.sh], description=Run composer commands such as composer require package, dir=/app, service=php, cmd=composer, description=Run artisan commands such as artisan view:clear, dir=/app, service=php, cmd=php artisan
Let's get this party started! Starting app breeze-avenue...
breeze-avenue 19:23:00 INFO ==> starting app... 
breeze-avenue 19:23:00 VERBOSE ==> initiatilizing app at /home/joseph/dev/Cw/Breeze/breezitory... 
lando         19:23:00 DEBUG ==> plugin lando-core loaded from /snapshot/cli/plugins/lando-core/app.js 
lando         19:23:00 DEBUG ==> plugin lando-events loaded from /snapshot/cli/plugins/lando-events/app.js 
lando         19:23:00 DEBUG ==> plugin lando-networking loaded from /snapshot/cli/plugins/lando-networking/app.js 
breeze-avenue 19:23:00 VERBOSE ==> proxy settings detected. 
lando         19:23:00 DEBUG ==> plugin lando-proxy loaded from /snapshot/cli/plugins/lando-proxy/app.js 
lando         19:23:00 DEBUG ==> plugin lando-recipes loaded from /snapshot/cli/plugins/lando-recipes/app.js 
lando         19:23:00 DEBUG ==> plugin lando-services loaded from /snapshot/cli/plugins/lando-services/app.js 
lando         19:23:00 DEBUG ==> plugin lando-sharing loaded from /snapshot/cli/plugins/lando-sharing/app.js 
lando         19:23:00 DEBUG ==> plugin lando-tooling loaded from /snapshot/cli/plugins/lando-tooling/app.js 
lando         19:23:00 DEBUG ==> plugin @lando/acquia loaded from /snapshot/cli/node_modules/@lando/acquia/app.js 
lando         19:23:00 DEBUG ==> plugin @lando/lagoon loaded from /snapshot/cli/node_modules/@lando/lagoon/app.js 
lando         19:23:00 DEBUG ==> plugin @lando/pantheon loaded from /snapshot/cli/node_modules/@lando/pantheon/app.js 
lando         19:23:00 DEBUG ==> plugin @lando/platformsh loaded from /snapshot/cli/node_modules/@lando/platformsh/app.js 
breeze-avenue 19:23:00 DEBUG ==> emitting event pre-init 
lando         19:23:00 VERBOSE ==> proxy is ON. 
lando         19:23:00 VERBOSE ==> Setting the default proxy certificate /certs/cert.crt 
breeze-avenue 19:23:00 VERBOSE ==> building node service node 
breeze-avenue 19:23:00 VERBOSE ==> building php service php 
breeze-avenue 19:23:00 DEBUG ==> emitting event post-init 
breeze-avenue 19:23:00 DEBUG ==> adding hostnames to the app... 
breeze-avenue 19:23:00 DEBUG ==> hostnames added to node 0=node.breezeavenue.internal
breeze-avenue 19:23:00 DEBUG ==> hostnames added to php 0=php.breezeavenue.internal
breeze-avenue 19:23:00 VERBOSE ==> attempting to find open services... 
lando         19:23:00 DEBUG ==> engine is up. 
lando         19:23:00 DEBUG ==> docker is running. 
breeze-avenue 19:23:00 DEBUG ==> engine is up. 
breeze-avenue 19:23:00 VERBOSE ==> refreshing certificates... 0=node, 1=php
breeze-avenue 19:23:00 VERBOSE ==> analyzing user ssh keys... using 5 of 5 
breeze-avenue 19:23:00 DEBUG ==> key config...  none 
breeze-avenue 19:23:00 VERBOSE ==> additional tooling detected 
breeze-avenue 19:23:00 DEBUG ==> adding app cli task install 
breeze-avenue 19:23:00 DEBUG ==> adding app cli task yarn 
breeze-avenue 19:23:00 DEBUG ==> adding app cli task build 
breeze-avenue 19:23:00 DEBUG ==> adding app cli task watch 
breeze-avenue 19:23:00 DEBUG ==> adding app cli task setup-env 
breeze-avenue 19:23:00 DEBUG ==> adding app cli task composer 
breeze-avenue 19:23:00 DEBUG ==> adding app cli task artisan 
breeze-avenue 19:23:00 VERBOSE ==> setting LANDO_INFO... 
breeze-avenue 19:23:00 DEBUG ==> ensuring exposed ports on php are bound to 127.0.0.1 
breeze-avenue 19:23:00 DEBUG ==> ensuring exposed ports on php are bound to 127.0.0.1 
breeze-avenue 19:23:00 VERBOSE ==> app is ready! 
breeze-avenue 19:23:00 DEBUG ==> emitting event ready 
breeze-avenue 19:23:00 VERBOSE ==> discovering dynamic portforward info... 
breeze-avenue 19:23:00 VERBOSE ==> reporting start action to report=true, url=https://metrics.lando.dev, report=true, url=https://metrics.lando.dev
breeze-avenue 19:23:00 DEBUG ==> reported data command=lando start, context=local, devMode=false, instance=13a08edd14272b0ccb90b1a00af49c1bbd439955, nodeVersion=v14.17.2, mode=cli, type=Linux, platform=linux, release=5.15.21-1-MANJARO, arch=x64, product=lando, version=3.6.0, app=14e53ec6da361afda926c19c8675860c1535bc85, type=none, services=[node:14, php:8.0], action=start, created=2022-02-23T01:23:00.744Z
breeze-avenue 19:23:00 DEBUG ==> emitting event pre-start 
lando         19:23:00 VERBOSE ==> about to scan urls 
lando         19:23:00 DEBUG ==> scanning data urls=[http://127.0.0.1:80, http://127.0.0.1:8000, http://127.0.0.1:8080, http://127.0.0.1:8888, http://127.0.0.1:8008], max=1, waitCodes=[]
lando         19:23:00 VERBOSE ==> about to scan urls 
lando         19:23:00 DEBUG ==> scanning data urls=[https://127.0.0.1:443, https://127.0.0.1:444, https://127.0.0.1:4433, https://127.0.0.1:4444, https://127.0.0.1:4443], max=1, waitCodes=[]
lando         19:23:00 DEBUG ==> checking to see if http://127.0.0.1:80 is ready. 
lando         19:23:00 DEBUG ==> checking to see if http://127.0.0.1:8000 is ready. 
lando         19:23:00 DEBUG ==> checking to see if http://127.0.0.1:8080 is ready. 
lando         19:23:00 DEBUG ==> checking to see if http://127.0.0.1:8888 is ready. 
lando         19:23:00 DEBUG ==> checking to see if http://127.0.0.1:8008 is ready. 
lando         19:23:00 DEBUG ==> checking to see if https://127.0.0.1:443 is ready. 
lando         19:23:00 DEBUG ==> checking to see if https://127.0.0.1:444 is ready. 
lando         19:23:00 DEBUG ==> checking to see if https://127.0.0.1:4433 is ready. 
lando         19:23:00 DEBUG ==> checking to see if https://127.0.0.1:4444 is ready. 
lando         19:23:00 DEBUG ==> checking to see if https://127.0.0.1:4443 is ready. 
lando         19:23:01 VERBOSE ==> checking docker version compatibility... 
lando         19:23:01 DEBUG ==> compatibility results name=compose, link=https://docs.docker.com/compose/install/#install-compose-on-linux-systems, wants=1.23.0 - 1.30.0, version=1.29.2, semversion=1.29.2, semmin=1.23.0, semmax=1.30.0, dockerVersion=true, satisfied=true, name=engine, link=https://docs.docker.com/engine/install/, wants=18.09.3 - 20.10.99, version=20.10.12, semversion=20.10.12, semmin=18.9.3, semmax=20.10.99, dockerVersion=true, satisfied=true
lando         19:23:01 DEBUG ==> checking to see if http://127.0.0.1:80 is ready. 
lando         19:23:01 DEBUG ==> checking to see if http://127.0.0.1:8000 is ready. 
lando         19:23:01 DEBUG ==> checking to see if http://127.0.0.1:8080 is ready. 
lando         19:23:01 DEBUG ==> checking to see if http://127.0.0.1:8888 is ready. 
lando         19:23:01 DEBUG ==> checking to see if http://127.0.0.1:8008 is ready. 
lando         19:23:01 DEBUG ==> checking to see if https://127.0.0.1:443 is ready. 
lando         19:23:01 DEBUG ==> checking to see if https://127.0.0.1:444 is ready. 
lando         19:23:01 DEBUG ==> checking to see if https://127.0.0.1:4433 is ready. 
lando         19:23:01 DEBUG ==> checking to see if https://127.0.0.1:4444 is ready. 
lando         19:23:01 DEBUG ==> checking to see if https://127.0.0.1:4443 is ready. 
lando         19:23:01 DEBUG ==> http://127.0.0.1:80 not currently accessible 
lando         19:23:01 DEBUG ==> http://127.0.0.1:8000 not currently accessible 
lando         19:23:01 DEBUG ==> http://127.0.0.1:8080 not currently accessible 
lando         19:23:01 DEBUG ==> http://127.0.0.1:8888 not currently accessible 
lando         19:23:01 DEBUG ==> http://127.0.0.1:8008 not currently accessible 
lando         19:23:01 DEBUG ==> https://127.0.0.1:443 not currently accessible 
lando         19:23:01 DEBUG ==> https://127.0.0.1:444 not currently accessible 
lando         19:23:01 DEBUG ==> https://127.0.0.1:4433 not currently accessible 
lando         19:23:01 DEBUG ==> https://127.0.0.1:4444 not currently accessible 
lando         19:23:01 DEBUG ==> https://127.0.0.1:4443 not currently accessible 
lando         19:23:01 VERBOSE ==> scan completed. 
lando         19:23:01 DEBUG ==> scan results. url=http://127.0.0.1:80, status=false, color=red, url=http://127.0.0.1:8000, status=false, color=red, url=http://127.0.0.1:8080, status=false, color=red, url=http://127.0.0.1:8888, status=false, color=red, url=http://127.0.0.1:8008, status=false, color=red
lando         19:23:01 VERBOSE ==> scan completed. 
lando         19:23:01 DEBUG ==> scan results. url=https://127.0.0.1:443, status=false, color=red, url=https://127.0.0.1:444, status=false, color=red, url=https://127.0.0.1:4433, status=false, color=red, url=https://127.0.0.1:4444, status=false, color=red, url=https://127.0.0.1:4443, status=false, color=red
lando         19:23:01 DEBUG ==> process pid5 running /usr/share/lando/bin/docker-compose up cstdio=inherit, silent=false, mode=spawn, detached=false
Starting landoproxyhyperion5000gandalfedition_proxy_1 ... error

ERROR: for landoproxyhyperion5000gandalfedition_proxy_1  Cannot start service proxy: network c20d2507bd45b9ae10894a97bd60c5dc8abedac65200e18f94892b17fbd6eea8 not found

ERROR: for proxy  Cannot start service proxy: network c20d2507bd45b9ae10894a97bd60c5dc8abedac65200e18f94892b17fbd6eea8 not found
ERROR: Encountered errors while bringing up the project.
lando         19:23:02 DEBUG ==> process pid5 finished with exit code 1 
breeze-avenue 19:23:02 ERROR ==>  message=, stack=Error
    at /snapshot/cli/lib/shell.js
From previous event:
    at Shell.sh (/snapshot/cli/lib/shell.js)
    at Object.dc (/snapshot/cli/lib/bootstrap.js)
    at compose (/snapshot/cli/lib/bootstrap.js)
    at /snapshot/cli/lib/router.js
    at /snapshot/cli/lib/router.js
    at processImmediate (internal/timers.js:464:21)
From previous event:
    at retryEach (/snapshot/cli/lib/router.js)
    at Object.start (/snapshot/cli/lib/router.js)
    at /snapshot/cli/lib/engine.js
    at /snapshot/cli/lib/router.js
From previous event:
    at Object.eventWrapper (/snapshot/cli/lib/router.js)
    at Engine.engineCmd (/snapshot/cli/lib/engine.js)
    at Engine.start (/snapshot/cli/lib/engine.js)
    at /snapshot/cli/plugins/lando-proxy/app.js
From previous event:
    at AsyncEvents.<anonymous> (/snapshot/cli/plugins/lando-proxy/app.js)
    at AsyncEvents.handle (/snapshot/cli/lib/events.js)
    at /snapshot/cli/lib/events.js
    at processImmediate (internal/timers.js:464:21)
From previous event:
    at AsyncEvents.emit (/snapshot/cli/lib/events.js)
    at /snapshot/cli/lib/app.js
From previous event:
    at App.start (/snapshot/cli/lib/app.js)
    at Object.run (/snapshot/cli/plugins/lando-core/tasks/start.js)
    at /snapshot/cli/lib/cli.js
    at processImmediate (internal/timers.js:464:21)
From previous event:
    at /snapshot/cli/lib/cli.js
From previous event:
    at Object.handler (/snapshot/cli/lib/cli.js)
    at Object.runCommand (/snapshot/cli/node_modules/yargs/lib/command.js:238:44)
    at Object.parseArgs [as _parseArgs] (/snapshot/cli/node_modules/yargs/yargs.js:1063:30)
    at Function.get [as argv] (/snapshot/cli/node_modules/yargs/yargs.js:1004:21)
    at Cli.init (/snapshot/cli/lib/cli.js)
    at Cli.run (/snapshot/cli/lib/cli.js)
    at Object.<anonymous> (/snapshot/cli/bin/lando.js)
    at Module._compile (pkg/prelude/bootstrap.js:1751:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Function.runMain (pkg/prelude/bootstrap.js:1804:12)
    at internal/main/run_main_module.js:17:47, __stackCleaned__=true
breeze-avenue 19:23:02 DEBUG ==>  message=, stack=Error
    at /snapshot/cli/lib/shell.js
From previous event:
    at Shell.sh (/snapshot/cli/lib/shell.js)
    at Object.dc (/snapshot/cli/lib/bootstrap.js)
    at compose (/snapshot/cli/lib/bootstrap.js)
    at /snapshot/cli/lib/router.js
    at /snapshot/cli/lib/router.js
    at processImmediate (internal/timers.js:464:21)
From previous event:
    at retryEach (/snapshot/cli/lib/router.js)
    at Object.start (/snapshot/cli/lib/router.js)
    at /snapshot/cli/lib/engine.js
    at /snapshot/cli/lib/router.js
From previous event:
    at Object.eventWrapper (/snapshot/cli/lib/router.js)
    at Engine.engineCmd (/snapshot/cli/lib/engine.js)
    at Engine.start (/snapshot/cli/lib/engine.js)
    at /snapshot/cli/plugins/lando-proxy/app.js
From previous event:
    at AsyncEvents.<anonymous> (/snapshot/cli/plugins/lando-proxy/app.js)
    at AsyncEvents.handle (/snapshot/cli/lib/events.js)
    at /snapshot/cli/lib/events.js
    at processImmediate (internal/timers.js:464:21)
From previous event:
    at AsyncEvents.emit (/snapshot/cli/lib/events.js)
    at /snapshot/cli/lib/app.js
From previous event:
    at App.start (/snapshot/cli/lib/app.js)
    at Object.run (/snapshot/cli/plugins/lando-core/tasks/start.js)
    at /snapshot/cli/lib/cli.js
    at processImmediate (internal/timers.js:464:21)
From previous event:
    at /snapshot/cli/lib/cli.js
From previous event:
    at Object.handler (/snapshot/cli/lib/cli.js)
    at Object.runCommand (/snapshot/cli/node_modules/yargs/lib/command.js:238:44)
    at Object.parseArgs [as _parseArgs] (/snapshot/cli/node_modules/yargs/yargs.js:1063:30)
    at Function.get [as argv] (/snapshot/cli/node_modules/yargs/yargs.js:1004:21)
    at Cli.init (/snapshot/cli/lib/cli.js)
    at Cli.run (/snapshot/cli/lib/cli.js)
    at Object.<anonymous> (/snapshot/cli/bin/lando.js)
    at Module._compile (pkg/prelude/bootstrap.js:1751:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Function.runMain (pkg/prelude/bootstrap.js:1804:12)
    at internal/main/run_main_module.js:17:47, __stackCleaned__=true
breeze-avenue 19:23:02 VERBOSE ==> reporting error action to report=true, url=https://metrics.lando.dev, report=true, url=https://metrics.lando.dev
breeze-avenue 19:23:02 DEBUG ==> reported data command=lando start, context=local, devMode=false, instance=13a08edd14272b0ccb90b1a00af49c1bbd439955, nodeVersion=v14.17.2, mode=cli, type=Linux, platform=linux, release=5.15.21-1-MANJARO, arch=x64, product=lando, version=3.6.0, , action=error, created=2022-02-23T01:23:02.045Z
breeze-avenue 19:23:02 DEBUG ==> process pid6 running /usr/share/lando/bin/docker-compose up cstdio=inherit, silent=false, mode=spawn, detached=false
Starting breezeavenue_php_1  ... done
Starting breezeavenue_node_1 ... done
breeze-avenue 19:23:03 DEBUG ==> process pid6 finished with exit code 0 
breeze-avenue 19:23:03 DEBUG ==> emitting event post-start 
breeze-avenue 19:23:03 DEBUG ==> connected breezeavenue_node_1 to the landonet 
breeze-avenue 19:23:03 DEBUG ==> connected breezeavenue_php_1 to the landonet 
breeze-avenue 19:23:03 VERBOSE ==> attempting to find open services... 
Scanning to determine which services are ready... Please standby...
breeze-avenue 19:23:03 VERBOSE ==> about to scan urls 
breeze-avenue 19:23:03 DEBUG ==> scanning data urls=[https://localhost:49168, http://localhost:49169], max=16, waitCodes=[400, 502, 404]
breeze-avenue 19:23:03 DEBUG ==> checking to see if https://localhost:49168 is ready. 
breeze-avenue 19:23:03 DEBUG ==> checking to see if http://localhost:49169 is ready. 
breeze-avenue 19:23:04 DEBUG ==> http://localhost:49169 is ready 
breeze-avenue 19:23:04 DEBUG ==> https://localhost:49168 is ready 
breeze-avenue 19:23:04 VERBOSE ==> scan completed. 
breeze-avenue 19:23:04 DEBUG ==> scan results. url=https://localhost:49168, status=true, color=green, url=http://localhost:49169, status=true, color=green
breeze-avenue 19:23:04 DEBUG ==> process pid7 running /usr/share/lando/bin/docker-compose exec node /bin/sh mkdir -p /certs && /helpers/refresh-certs.sh > /certs/refresh.log cstdio=inherit, silent=false, mode=spawn, detached=false
breeze-avenue 19:23:04 DEBUG ==> process pid7 finished with exit code 0 
breeze-avenue 19:23:04 DEBUG ==> process pid8 running /usr/share/lando/bin/docker-compose exec php /bin/sh mkdir -p /certs && /helpers/refresh-certs.sh > /certs/refresh.log cstdio=inherit, silent=false, mode=spawn, detached=false
breeze-avenue 19:23:05 DEBUG ==> process pid8 finished with exit code 0 
breeze-avenue 19:23:05 INFO ==> started app. 

  _      __              _           __
 | | /| / /__ ________  (_)__  ___ _/ /
 | |/ |/ / _ `/ __/ _ \/ / _ \/ _ `/_/ 
 |__/|__/\_,_/_/ /_//_/_/_//_/\_, (_)  
                             /___/     

Your app started up but we detected some things you may wish to investigate.
These only may be a problem.


 ■ Lando was not able to start the proxy
   Error
   The proxy has been disabled for now so you can continue to work.
   Check out the docs below, resolve your issue and build this app
   https://docs.lando.dev/config/proxy.html


Here are some vitals:

 NAME      breeze-avenue                         
 LOCATION  /home/joseph/dev/Cw/Breeze/breezitory 
 SERVICES  node, php                             
 PHP URLS  https://localhost:49168               
           http://localhost:49169                

lando         19:23:05 DEBUG ==> emitting event before-end
```

**Comment by reynoldsalec** [comment]
@musicaljoeker likely the ports listed as inaccessible are already being used by another service on your computer. Relevant debug code:

```
lando         19:23:01 DEBUG ==> http://127.0.0.1:80 not currently accessible 
lando         19:23:01 DEBUG ==> http://127.0.0.1:8000 not currently accessible 
lando         19:23:01 DEBUG ==> http://127.0.0.1:8080 not currently accessible 
lando         19:23:01 DEBUG ==> http://127.0.0.1:8888 not currently accessible 
lando         19:23:01 DEBUG ==> http://127.0.0.1:8008 not currently accessible 
lando         19:23:01 DEBUG ==> https://127.0.0.1:443 not currently accessible 
lando         19:23:01 DEBUG ==> https://127.0.0.1:444 not currently accessible 
lando         19:23:01 DEBUG ==> https://127.0.0.1:4433 not currently accessible 
lando         19:23:01 DEBUG ==> https://127.0.0.1:4444 not currently accessible 
lando         19:23:01 DEBUG ==> https://127.0.0.1:4443 not currently accessible 
```

A couple things to try:

- See if you can find another service using localhost: https://docs.lando.dev/config/proxy.html#automatic-port-assignment
- Make sure your problem isn't DNS Rebinding protection: https://docs.lando.dev/help/dns-rebind.html

**Comment by musicaljoeker** [comment]
Hello, thank you for those recommendations. Since this error, I have started seeing new errors which appear to be completely separate, so I have logged a separate bug here (https://github.com/lando/lando/issues/3346). I have also joined the Lando Slack community, so I'm happy to talk there too.

**Comment by reynoldsalec** [comment]
Thanks @musicaljoeker, unless you have further questions here or a pathway for replication that others can repeat, I'm going to close this out.
