### ISSUE TITLE
Cannot start service appserver: error while creating mount source path '/var/www/html/visionart_d7': mkdir /var/www: read-only file system

### ISSUE THREAD

**Issue by MansiP10** [lando/lando#3348]
After install and run lando start its working fine but after restarting laptop its giving error related to read-only file system on runnig lando start. also given full permission to /var/www/.please find error below and help me.

> /var/www/html/visionart_d7 (development) $ lando start
Let's get this party started! Starting app visionart-d7...
php version 5.6 is a legacy version! We recommend upgrading.
Pulling proxy (traefik:2.2.0)...
2.2.0: Pulling from library/traefik
cbdbe7a5bc2a: Pull complete
f16506d32a25: Pull complete
2d2982f034f0: Pull complete
b731cd68f421: Pull complete
Digest: sha256:c32f75bfba23b0d22d4ee378e32833525cb0c85e971f7cae3bdb29d25586dba2
Status: Downloaded newer image for traefik:2.2.0
Creating landoproxyhyperion5000gandalfedition_proxy_1 ... done
Pulling appserver (devwithlando/php:5.6-apache-3)...
5.6-apache-3: Pulling from devwithlando/php
5e6ec7f28fb7: Pull complete
cf165947b5b7: Pull complete
7bd37682846d: Pull complete
99daf8e838e1: Pull complete
ae320713efba: Pull complete
ebcb99c48d8c: Pull complete
9867e71b4ab6: Pull complete
936eb418164a: Pull complete
bc298e7adaf7: Pull complete
ccd61b587bcd: Pull complete
b2d4b347f67c: Pull complete
56e9dde34152: Pull complete
9ad99b17eb78: Pull complete
a84b3fb2c15b: Pull complete
Digest: sha256:ca5f339d99d5c3d7c7e22176f7f1f2842e6b9d6c12d70f44d121ccfdda330ec9
Status: Downloaded newer image for devwithlando/php:5.6-apache-3
Creating visionartd7_appserver_1 ... error

ERROR: for visionartd7_appserver_1  Cannot start service appserver: error while creating mount source path '/var/www/html/visionart_d7': mkdir /var/www: read-only file system

ERROR: for appserver  Cannot start service appserver: error while creating mount source path '/var/www/html/visionart_d7': mkdir /var/www: read-only file system
ERROR: Encountered errors while bringing up the project.
ERROR ==>  message=, stack=Error
    at /snapshot/cli/lib/shell.js
From previous event:
    at Shell.sh (/snapshot/cli/lib/shell.js)
    at Object.dc (/snapshot/cli/lib/bootstrap.js)
    at compose (/snapshot/cli/lib/bootstrap.js)
    at /snapshot/cli/lib/router.js
From previous event:
    at retryEach (/snapshot/cli/lib/router.js)
    at Object.start (/snapshot/cli/lib/router.js)
From previous event:
    at /snapshot/cli/lib/router.js
    at processImmediate (internal/timers.js:464:21)
From previous event:
    at Object.run (/snapshot/cli/lib/router.js)
    at run (/snapshot/cli/lib/engine.js)
    at /snapshot/cli/lib/router.js
From previous event:
    at Object.eventWrapper (/snapshot/cli/lib/router.js)
    at Engine.engineCmd (/snapshot/cli/lib/engine.js)
    at Engine.run (/snapshot/cli/lib/engine.js)
    at Object.runBuild (/snapshot/cli/plugins/lando-services/lib/utils.js)
    at AsyncEvents.<anonymous> (/snapshot/cli/plugins/lando-services/app.js)
    at AsyncEvents.handle (/snapshot/cli/lib/events.js)
    at /snapshot/cli/lib/events.js
From previous event:
    at AsyncEvents.emit (/snapshot/cli/lib/events.js)
    at /snapshot/cli/lib/app.js
From previous event:
    at App.start (/snapshot/cli/lib/app.js)
    at Object.run (/snapshot/cli/plugins/lando-core/tasks/start.js)
    at /snapshot/cli/lib/cli.js
    at processImmediate (internal/timers.js:464:21)
From previous event:
    at /snapshot/cli/lib/cli.js
From previous event:
    at Object.handler (/snapshot/cli/lib/cli.js)
    at Object.runCommand (/snapshot/cli/node_modules/yargs/lib/command.js:238:44)
    at Object.parseArgs [as _parseArgs] (/snapshot/cli/node_modules/yargs/yargs.js:1063:30)
    at Function.get [as argv] (/snapshot/cli/node_modules/yargs/yargs.js:1004:21)
    at Cli.init (/snapshot/cli/lib/cli.js)
    at Cli.run (/snapshot/cli/lib/cli.js)
    at Object.<anonymous> (/snapshot/cli/bin/lando.js)
    at Module._compile (pkg/prelude/bootstrap.js:1751:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Function.runMain (pkg/prelude/bootstrap.js:1804:12)
    at internal/main/run_main_module.js:17:47, __stackCleaned__=true
Pulling phpmyadmin (phpmyadmin/phpmyadmin:5.1.1)...
5.1.1: Pulling from phpmyadmin/phpmyadmin
69692152171a: Pull complete
2040822db325: Pull complete
9b4ca5ae9dfa: Pull complete
ac1fe7c6d966: Pull complete
5b26fc9ce030: Pull complete
3492f4769444: Pull complete
1dec05775a74: Pull complete
77107a42338e: Pull complete
f58e4093c52a: Pull complete
d32715f578d3: Pull complete
7a73fb2558ce: Pull complete
667b573fcff7: Pull complete
75e2da936ffe: Pull complete
c725733fdfb1: Pull complete
ca3aa01b3215: Pull complete
df01d0b9f13f: Pull complete
b89f51f248c7: Pull complete
3971ed8ddc3b: Pull complete
Digest: sha256:9e584c08f981019aa9d50170c88b988c982dff09b95120912e280e9f614375af
Status: Downloaded newer image for phpmyadmin/phpmyadmin:5.1.1
Pulling database (bitnami/mysql:5.7.29-debian-10-r51)...
5.7.29-debian-10-r51: Pulling from bitnami/mysql
6729c2f8f6ae: Pull complete
1f597137fef6: Pull complete
2fa722995439: Pull complete
91056e90fa16: Pull complete
65bd68405a15: Pull complete
81e59cb20cec: Pull complete
4fc31094af46: Pull complete
d9ec2e1d4854: Pull complete
5749855cce30: Pull complete
aba2711ad87d: Pull complete
Digest: sha256:3f586d2f2e0fa1e1c7c933a7adccc3b5806227402fbc6a425953e4941a3d6d9f
Status: Downloaded newer image for bitnami/mysql:5.7.29-debian-10-r51
Starting visionartd7_appserver_1 ... 
Creating visionartd7_phpmyadmin_1 ... error
Creating visionartd7_database_1   ... 
Starting visionartd7_appserver_1  ... error
ERROR: for visionartd7_phpmyadmin_1  Cannot start service phpmyadmin: error while creating mount source path '/var/www/html/visionart_d7': mkdir /var/www: read-only file system

ERROR: for visionartd7_appserver_1  Cannot start service appserver: error while creating mount source path '/var/www/html/visionart_d7': mkdirCreating visionartd7_database_1   ... error

ERROR: for visionartd7_database_1  Cannot start service database: error while creating mount source path '/var/www/html/visionart_d7': mkdir /var/www: read-only file system

ERROR: for phpmyadmin  Cannot start service phpmyadmin: error while creating mount source path '/var/www/html/visionart_d7': mkdir /var/www: read-only file system

ERROR: for appserver  Cannot start service appserver: error while creating mount source path '/var/www/html/visionart_d7': mkdir /var/www: read-only file system

ERROR: for database  Cannot start service database: error while creating mount source path '/var/www/html/visionart_d7': mkdir /var/www: read-only file system
ERROR: Encountered errors while bringing up the project.
ERROR ==>  message=, stack=Error
    at /snapshot/cli/lib/shell.js
From previous event:
    at Shell.sh (/snapshot/cli/lib/shell.js)
    at Object.dc (/snapshot/cli/lib/bootstrap.js)
    at compose (/snapshot/cli/lib/bootstrap.js)
    at /snapshot/cli/lib/router.js
    at /snapshot/cli/lib/router.js
    at processImmediate (internal/timers.js:464:21)
From previous event:
    at retryEach (/snapshot/cli/lib/router.js)
    at Object.start (/snapshot/cli/lib/router.js)
    at /snapshot/cli/lib/engine.js
    at /snapshot/cli/lib/router.js
From previous event:
    at Object.eventWrapper (/snapshot/cli/lib/router.js)
    at Engine.engineCmd (/snapshot/cli/lib/engine.js)
    at Engine.start (/snapshot/cli/lib/engine.js)
    at /snapshot/cli/lib/app.js
From previous event:
    at App.start (/snapshot/cli/lib/app.js)
    at Object.run (/snapshot/cli/plugins/lando-core/tasks/start.js)
    at /snapshot/cli/lib/cli.js
    at processImmediate (internal/timers.js:464:21)
From previous event:
    at /snapshot/cli/lib/cli.js
From previous event:
    at Object.handler (/snapshot/cli/lib/cli.js)
    at Object.runCommand (/snapshot/cli/node_modules/yargs/lib/command.js:238:44)
    at Object.parseArgs [as _parseArgs] (/snapshot/cli/node_modules/yargs/yargs.js:1063:30)
    at Function.get [as argv] (/snapshot/cli/node_modules/yargs/yargs.js:1004:21)
    at Cli.init (/snapshot/cli/lib/cli.js)
    at Cli.run (/snapshot/cli/lib/cli.js)
    at Object.<anonymous> (/snapshot/cli/bin/lando.js)
    at Module._compile (pkg/prelude/bootstrap.js:1751:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Function.runMain (pkg/prelude/bootstrap.js:1804:12)
    at internal/main/run_main_module.js:17:47, __stackCleaned__=true

██╗   ██╗██╗  ██╗     ██████╗ ██╗  ██╗██╗
██║   ██║██║  ██║    ██╔═══██╗██║  ██║██║
██║   ██║███████║    ██║   ██║███████║██║
██║   ██║██╔══██║    ██║   ██║██╔══██║╚═╝
╚██████╔╝██║  ██║    ╚██████╔╝██║  ██║██╗
 ╚═════╝ ╚═╝  ╚═╝     ╚═════╝ ╚═╝  ╚═╝╚═╝
                                         

An error occurred while starting up your app!
Here are a few things you can try to get back into a good state:

  ■ Try running lando rebuild
  ■ Try restarting in debug mode lando restart -vvv
  ■ Try checking the logs with lando logs

If those fail then consult the troubleshooting materials:

  ■ https://docs.lando.dev/help/logs.html
  ■ https://docs.lando.dev/help/updating.html

Or post your issue to Slack or GitHub

  ■ Slack - https://launchpass.com/devwithlando
  ■ GitHub - https://github.com/lando/lando/issues/new/choose

ERROR ==>

**Comment by MansiP10** [comment]
@reynoldsalec yes i run lando destroy, still getting same error.

**Comment by sinnbeck** [comment]
Seems that you are trying to start lando from a directory where you don't have write permissions. Can you try again from a directory that is owned by your user?
