### ISSUE TITLE
I get a  TypeError on any lando command: Cannot read property 'pluginDirs' of undefined

### ISSUE THREAD

**Issue by va5y1** [lando/lando#3379]
**Tell us about your setup**

What is your lando version and operating system?

Ubuntu 20.04
Docker version 20.10.13, build a224086
Lando version **v3.6.2**

**Tell us about your .lando.yml**
```yml
name: drupal
recipe: drupal9
config:
  webroot: web
  xdebug: true
```

**Tell us about the command you were running**

Any lando command.

 **Tell us about the error you got**

After forcibly turning off the computer I got this on every lando command:
```
$ lando start

/snapshot/cli/node_modules/lodash/lodash.js:653
      result[index] = iteratee(array[index], index, array);
                      ^

TypeError: Cannot read property 'pluginDirs' of undefined
    at /snapshot/cli/lib/config.js
    at arrayMap (/snapshot/cli/node_modules/lodash/lodash.js:653:23)
    at Function.map (/snapshot/cli/node_modules/lodash/lodash.js:9622:14)
    at interceptor (/snapshot/cli/node_modules/lodash/lodash.js:17094:35)
    at thru (/snapshot/cli/node_modules/lodash/lodash.js:8859:14)
    at /snapshot/cli/node_modules/lodash/lodash.js:4430:28
    at arrayReduce (/snapshot/cli/node_modules/lodash/lodash.js:697:21)
    at baseWrapperValue (/snapshot/cli/node_modules/lodash/lodash.js:4429:14)
    at LazyWrapper.lazyValue [as value] (/snapshot/cli/node_modules/lodash/lodash.js:1901:16)
    at baseWrapperValue (/snapshot/cli/node_modules/lodash/lodash.js:4427:25)
```

_Before this accident, lando worked well._

**Comment by labboy0276** [comment]
@va5y1 Have you tried purging all your containers via: https://docs.lando.dev/help/purging-containers.html

**Comment by va5y1** [comment]
@labboy0276  `rm -rf ~/.lando ` helped me, thanks a lot!
 I used to think that deleting the entire lando directory may cause data loss, but it seems all right.

**Comment by labboy0276** [comment]
@va5y1 only if you have special config in there.  So, deleting the whoel dot folder is typically "safe-ish" otherwise.
