### ISSUE TITLE
lando wp throws Fatal Error: Call to undefined function get_role() in phar

### ISSUE THREAD

**Issue by acobster** [lando/lando#341]
**NOTE:** For other projects using WP CLI, I've fixed this error in the past by simply updating WP CLI. That didn't appear to work this time though. I updated from WP CLI 1.2.1 to 1.3.0 directly in the container and the error persists.

**Tell us about your setup**

lando v3.0.0-beta.17, Ubuntu 16.04

**Tell us about your `.lando.yml`**

```yml
name: emerald-city-staffing
recipe: pantheon
config:
  framework: wordpress
  env: dev
  site: emerald-city-staffing
  id: 01848ffa-8fe0-48d2-b962-3862a7e3e7e4
```

No pantheon.yml config.

**Tell us about the command you were running**

```bash
lando start
lanso wp --version
# WP-CLI 1.2.1
lando wp
```

**Tell us about the error you got**
```bash
App emerald-city-staffing is ready!
App emerald-city-staffing has config edge=[emerald-city-staffing.lndo.site], type=php:7.0, via=nginx:1.8, ssl=true, xdebug=false, server=/home/ctamayo/.lando/services/config/pantheon/wordpress.conf, conf=/home/ctamayo/.lando/services/config/pantheon/php.ini, FRAMEWORK=wordpress, DOCROOT=/, FILEMOUNT=wp-content/uploads, DRUPAL_HASH_SALT=fad5cfeb464e3cb6d2a72bfe290d84e25478753824970a9455f5cb350a9f8183, PANTHEON_SITE=01848ffa-8fe0-48d2-b962-3862a7e3e7e4, PANTHEON_SITE_NAME=emerald-city-staffing, PANTHEON_ENVIRONMENT=lando, DB_HOST=database, DB_PORT=3306, DB_USER=pantheon, DB_PASSWORD=pantheon, DB_NAME=pantheon, CACHE_HOST=cache, CACHE_PORT=6379, CACHE_PASSWORD=, PANTHEON_INDEX_HOST=index, PANTHEON_INDEX_PORT=449, BACKDROP_SETTINGS={"databases":{"default":{"default":{"driver":"mysql","prefix":"","database":"pantheon","username":"pantheon","password":"pantheon","host":"database","port":3306}}},"conf":{"pressflow_smart_start":true,"pantheon_binding":"lando","pantheon_site_uuid":"01848ffa-8fe0-48d2-b962-3862a7e3e7e4","pantheon_environment":"lando","pantheon_tier":"lando","pantheon_index_host":"index","pantheon_index_port":449,"redis_client_host":"cache","redis_client_port":6379,"redis_client_password":"","file_public_path":"sites/default/files","file_private_path":"sites/default/files/private","file_directory_path":"sites/default/files","file_temporary_path":"/tmp","file_directory_temp":"/tmp","css_gzip_compression":false,"js_gzip_compression":false,"page_compression":false},"drupal_hash_salt":"fad5cfeb464e3cb6d2a72bfe290d84e25478753824970a9455f5cb350a9f8183","config_directory_name":"config"}, PRESSFLOW_SETTINGS={"databases":{"default":{"default":{"driver":"mysql","prefix":"","database":"pantheon","username":"pantheon","password":"pantheon","host":"database","port":3306}}},"conf":{"pressflow_smart_start":true,"pantheon_binding":"lando","pantheon_site_uuid":"01848ffa-8fe0-48d2-b962-3862a7e3e7e4","pantheon_environment":"lando","pantheon_tier":"lando","pantheon_index_host":"index","pantheon_index_port":449,"redis_client_host":"cache","redis_client_port":6379,"redis_client_password":"","file_public_path":"sites/default/files","file_private_path":"sites/default/files/private","file_directory_path":"sites/default/files","file_temporary_path":"/tmp","file_directory_temp":"/tmp","css_gzip_compression":false,"js_gzip_compression":false,"page_compression":false},"drupal_hash_salt":"fad5cfeb464e3cb6d2a72bfe290d84e25478753824970a9455f5cb350a9f8183","config_directory_name":"config"}, AUTH_KEY=fad5cfeb464e3cb6d2a72bfe290d84e25478753824970a9455f5cb350a9f8183, SECURE_AUTH_KEY=99b67d8d1c4dd7647f3903504c9b4fa54dcdbe4b43acaad55dbc76ef56626539, LOGGED_IN_KEY=99b67d8d1c4dd7647f3903504c9b4fa54dcdbe4b43acaad55dbc76ef56626539, AUTH_SALT=d7dbca00bd657ee0f2345d4cec241a6554a1489a895989d48e3813fce89613aa, SECURE_AUTH_SALT=ae4bcc2f58f066e8d0a6d9038ef11fb1e7acbfb1f54dbbd0842f994fccbcd5b0, LOGGED_IN_SALT=177330d0a349a3e5017fafe75ee1ba4d7fe3036dcf28124d85f1614730ec4324, NONCE_SALT=2da5549bd4290c781bf0f74462d8dafc233157cd645b5b18942f2b95c55cdba3, NONCE_KEY=6326259bbbe9d25e1abe2247a675586094c2ee363dd57376ef5a3a5ab2b7732a, TERMINUS_SITE=emerald-city-staffing, TERMINUS_ENV=dev, volumes=[/var/www/.wp-cli, /home/ctamayo/.lando/services/config/pantheon/prepend.php:/srv/includes/prepend.php, /home/ctamayo/.lando/services/config/pantheon/nginx.conf:/etc/nginx/nginx.conf, /home/ctamayo/.lando/services/config/pantheon/pantheon.sh:/helpers/pantheon.sh, /home/ctamayo/.lando/services/config/pantheon/pull.sh:/helpers/pull.sh, /home/ctamayo/.lando/services/config/pantheon/push.sh:/helpers/push.sh, /home/ctamayo/.lando/services/config/pantheon/switch.sh:/helpers/switch.sh, /var/www/.terminus, /var/www/.drupal], image=devwithlando/pantheon-appserver:7.0-fpm, depends_on=[index], build=[rm -rf /var/www/.drush/backdrush/, drush cc drush, cd $LANDO_MOUNT && composer install, terminus auth:login --machine-token=vv-oZi2VFaTCZA1RU_oMUYnBXu4ijFJUlmWvk8PPJHeeC], extras=[/helpers/pantheon.sh], _app=emerald-city-staffing, _root=/home/ctamayo/Kalabox/emerald-city-staffing/code, _mount=/app, version=7.0, name=appserver, web=nginx, mount=/app, command=[docker-php-entrypoint, php-fpm], image=devwithlando/php:7.0-fpm, serverConf=/etc/nginx/conf.d/default.template, phpConf=/usr/local/etc/php/php.ini, type=mariadb:10.0, portforward=true, user=pantheon, password=pantheon, database=pantheon, confd=/home/ctamayo/.lando/services/config/pantheon/mysql, _app=emerald-city-staffing, _root=/home/ctamayo/Kalabox/emerald-city-staffing/code, _mount=/app, version=10.0, type=redis:2.8, persist=true, portforward=true, _app=emerald-city-staffing, _root=/home/ctamayo/Kalabox/emerald-city-staffing/code, _mount=/app, version=2.8, type=varnish:4.1, backends=[nginx], ssl=true, vcl=/home/ctamayo/.lando/services/config/pantheon/pantheon.vcl, _app=emerald-city-staffing, _root=/home/ctamayo/Kalabox/emerald-city-staffing/code, _mount=/app, version=4.1, type=solr:custom, port=449, image=devwithlando/pantheon-index:3.6, ports=[449], command=/bin/bash /start.sh, _app=emerald-city-staffing, _root=/home/ctamayo/Kalabox/emerald-city-staffing/code, _mount=/app, version=custom, service=appserver, description=Run composer commands, cmd=[composer, --ansi], service=appserver, description=Run php commands, service=database, description=Drop into a MySQL shell, user=root, service=appserver, needs=[database], description=Import <file> into database. File is relative to approot., cmd=/helpers/mysql-import.sh, description=The database host, alias=[h], description=The database user, default=root, alias=[u], description=The database name, alias=[d], description=The database password, alias=[p], description=The database port, default=3306, alias=[P], service=appserver, needs=[database], description=Export a database. Resulting file: {DB_NAME}.TIMESTAMP.gz, cmd=/helpers/mysql-export.sh, description=The database host, alias=[h], description=The database user, default=root, alias=[u], description=The database name, alias=[d], description=The database password, alias=[p], description=The database port, default=3306, alias=[P], service=appserver, description=Run wp-cli commands, cmd=[wp, --allow-root], service=cache, service=edge, user=root, service=appserver, service=appserver, description=Pull code, database and/or files from Pantheon, cmd=/helpers/pull.sh, description=The environment to get the code from or [none], passthrough=true, alias=[c], type=list, message=Pull code from?, choices=function () {
              getEnvs(this.async());
            }, default=dev, weight=600, description=The environment to get the db from or [none], passthrough=true, alias=[d], type=list, message=Pull DB from?, choices=function () {
              getEnvs(this.async());
            }, default=dev, weight=601, description=The environment to get the files from or [none], passthrough=true, alias=[f], type=list, message=Pull files from?, choices=function () {
              getEnvs(this.async());
            }, default=dev, weight=602, description=Rsync the files, good for subsequent pulls, boolean=true, default=false, service=appserver, description=Push code, database and/or files to Pantheon, cmd=/helpers/push.sh, description=A message describing your change, passthrough=true, alias=[m], type=string, message=What did you change?, default=My awesome Lando-based changes, weight=600, description=The environment to push the db to or [none], passthrough=true, alias=[d], type=list, message=Push db to?, choices=function () {
              getEnvs(this.async(), ['test', 'live']);
            }, default=dev, weight=601, description=The environment to push the files to or [none], passthrough=true, alias=[f], type=list, message=Push files to?, choices=function () {
              getEnvs(this.async(), ['test', 'live']);
            }, default=dev, weight=602, service=appserver, description=Switch to a different multidev environment, cmd=/helpers/switch.sh, description=Do not switch the database, boolean=true, default=false, description=Do not switch the files, boolean=true, default=false, name=emerald-city-staffing, recipe=pantheon, framework=wordpress, env=dev, site=emerald-city-staffing, id=01848ffa-8fe0-48d2-b962-3862a7e3e7e4, _app=emerald-city-staffing, _root=/home/ctamayo/Kalabox/emerald-city-staffing/code, _mount=/app, _recipe=pantheon, via=nginx:1.8, database=mariadb:10.0, cache=redis:2.8, edge=varnish:4.1, index=solr:custom, server=/home/ctamayo/.lando/services/config/pantheon/wordpress.conf, php=/home/ctamayo/.lando/services/config/pantheon/php.ini, database=/home/ctamayo/.lando/services/config/pantheon/mysql, php=7.0
Additional tooling detected for app emerald-city-staffing
Adding app cli task composer
Adding app cli task php
Adding app cli task mysql
Adding app cli task db-import <file>
Adding app cli task db-export
Adding app cli task wp
Adding app cli task redis-cli
Adding app cli task varnishadm
Adding app cli task terminus
Adding app cli task pull
Adding app cli task push
Adding app cli task switch <env>
App tooling loaded.
Recipe custom loaded
Recipe backdrop loaded
Recipe drupal6 loaded
Recipe drupal7 loaded
Recipe drupal8 loaded
Recipe joomla loaded
Recipe laravel loaded
Recipe lamp loaded
Recipe lemp loaded
Recipe mean loaded
Recipe pantheon loaded
Recipe wordpress loaded
Init method github loaded
Init method pantheon loaded
Service apache loaded
Service dotnet loaded
Service elasticsearch loaded
Service nginx loaded
Service node loaded
Service mailhog loaded
Service mariadb loaded
Service memcached loaded
Service mssql loaded
Service mongo loaded
Service mysql loaded
Service postgres loaded
Service php loaded
Service phpmyadmin loaded
Service python loaded
Service redis loaded
Service ruby loaded
Service solr loaded
Service varnish loaded
Bootstrap completed.
Initializing cli
Emitting event pre-cli-load
Event pre-cli-load has 0 listeners
Loading cli task composer
Loading cli task config
Loading cli task db-export
Loading cli task db-import <file>
Loading cli task destroy
Loading cli task info
Loading cli task init
Loading cli task list
Loading cli task logs
Loading cli task mysql
Loading cli task php
Loading cli task poweroff
Loading cli task pull
Loading cli task push
Loading cli task rebuild
Loading cli task redis-cli
Loading cli task restart
Loading cli task share
Loading cli task ssh
Loading cli task start
Loading cli task stop
Loading cli task switch <env>
Loading cli task terminus
Loading cli task varnishadm
Loading cli task version
Loading cli task wp
Emitting event task-wp-answers
Event task-wp-answers has 0 listeners
CLI args _=[wp, -vvvv], $0=/usr/local/bin/lando
Emitting event task-wp-run
Event task-wp-run has 0 listeners
Retrieved from file cache with key engineUp
Cache miss with key engineUp
About to run 0=/usr/bin/docker, 1=info
With pre run opts
Running exec /usr/bin/docker,info
With env XDG_VTNR=7, XDG_SESSION_ID=c2, XDG_GREETER_DATA_DIR=/var/lib/lightdm-data/ctamayo, CLUTTER_IM_MODULE=xim, SESSION=vrd, GPG_AGENT_INFO=/home/ctamayo/.gnupg/S.gpg-agent:0:1, VTE_VERSION=4205, TERM=xterm-256color, SHELL=/bin/bash, QT_LINUX_ACCESSIBILITY_ALWAYS_ON=1, WINDOWID=92274698, UPSTART_SESSION=unix:abstract=/com/ubuntu/upstart-session/1000/4170, GNOME_KEYRING_CONTROL=, GTK_MODULES=gail:atk-bridge:unity-gtk-module, USER=ctamayo, LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:, QT_ACCESSIBILITY=1, XDG_SESSION_PATH=/org/freedesktop/DisplayManager/Session0, XDG_SEAT_PATH=/org/freedesktop/DisplayManager/Seat0, SSH_AUTH_SOCK=/run/user/1000/keyring/ssh, DEFAULTS_PATH=/usr/share/gconf/ubuntu.default.path, TMUX=/tmp/tmux-1000/default,10844,2, XDG_CONFIG_DIRS=/etc/xdg/xdg-ubuntu:/usr/share/upstart/xdg:/etc/xdg, DESKTOP_SESSION=ubuntu, PATH=/usr/share/lando/bin:/home/ctamayo/bin:/home/ctamayo/.local/bin:/home/ctamayo/.rbenv/shims:/home/ctamayo/dotfiles/bin:/home/ctamayo/.rbenv/shims:/home/ctamayo/.rbenv/shims:/home/ctamayo/.rbenv/bin:/home/ctamayo/dotfiles/bin:/home/ctamayo/bin:/home/ctamayo/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin, QT_QPA_PLATFORMTHEME=appmenu-qt5, QT_IM_MODULE=ibus, XDG_SESSION_TYPE=x11, PWD=/home/ctamayo/Kalabox/emerald-city-staffing/code, JOB=unity-settings-daemon, XMODIFIERS=@im=ibus, EDITOR=vim, GNOME_KEYRING_PID=, LANG=en_US.UTF-8, GDM_LANG=en_US, MANDATORY_PATH=/usr/share/gconf/ubuntu.mandatory.path, NODE_PATH=/usr/lib/nodejs:/usr/lib/node_modules:/usr/share/javascript, TMUX_PANE=%5, COMPIZ_CONFIG_PROFILE=ubuntu, IM_CONFIG_PHASE=1, PS1=\u@\h\[$(tput bold 1)\]\[\e[1;35m\]$(__git_ps1) \[\e[01;32m\]$(__cwd_ps1)$(__env_ps1)\[$(tput sgr0)\] \$ , GDMSESSION=ubuntu, RBENV_SHELL=bash, HISTCONTROL=ignoreboth, SESSIONTYPE=gnome-session, GTK2_MODULES=overlay-scrollbar, XDG_SEAT=seat0, HOME=/home/ctamayo, SHLVL=3, LANGUAGE=en_US, GNOME_DESKTOP_SESSION_ID=this-is-deprecated, UPSTART_INSTANCE=, XDG_SESSION_DESKTOP=ubuntu, UPSTART_EVENTS=xsession started, LOGNAME=ctamayo, COMPIZ_BIN_PATH=/usr/bin/, XDG_DATA_DIRS=/usr/share/ubuntu:/usr/share/gnome:/usr/local/share/:/usr/share/:/var/lib/snapd/desktop, QT4_IM_MODULE=xim, DBUS_SESSION_BUS_ADDRESS=unix:abstract=/tmp/dbus-magz8hV1Y1, LESSOPEN=| /usr/bin/lesspipe %s, INSTANCE=, UPSTART_JOB=unity7, XDG_RUNTIME_DIR=/run/user/1000, DISPLAY=:0, XDG_CURRENT_DESKTOP=Unity, GTK_IM_MODULE=ibus, LESSCLOSE=/usr/bin/lesspipe %s %s, XAUTHORITY=/home/ctamayo/.Xauthority, OLDPWD=/home/ctamayo, _=/usr/local/bin/lando, LANDO_ENGINE_ID=1000, LANDO_ENGINE_GID=1000, LANDO_ENGINE_HOME=/home/ctamayo, LANDO_ENGINE_IP=tcp://127.0.0.1, LANDO_ENGINE_REMOTE_IP=10.0.10.20, LANDO_ENGINE_CONFIG_DIR=/home/ctamayo/.lando/services/config, LANDO_ENGINE_SCRIPTS_DIR=/home/ctamayo/.lando/services/config/scripts, LANDO_ENGINE_HELPERS_DIR=/home/ctamayo/.lando/services/config/helpers
Retrieved from file cache with key engineUp
Cache miss with key engineUp
About to run 0=/usr/bin/docker, 1=info
With pre run opts
Running exec /usr/bin/docker,info
With env XDG_VTNR=7, XDG_SESSION_ID=c2, XDG_GREETER_DATA_DIR=/var/lib/lightdm-data/ctamayo, CLUTTER_IM_MODULE=xim, SESSION=vrd, GPG_AGENT_INFO=/home/ctamayo/.gnupg/S.gpg-agent:0:1, VTE_VERSION=4205, TERM=xterm-256color, SHELL=/bin/bash, QT_LINUX_ACCESSIBILITY_ALWAYS_ON=1, WINDOWID=92274698, UPSTART_SESSION=unix:abstract=/com/ubuntu/upstart-session/1000/4170, GNOME_KEYRING_CONTROL=, GTK_MODULES=gail:atk-bridge:unity-gtk-module, USER=ctamayo, LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:, QT_ACCESSIBILITY=1, XDG_SESSION_PATH=/org/freedesktop/DisplayManager/Session0, XDG_SEAT_PATH=/org/freedesktop/DisplayManager/Seat0, SSH_AUTH_SOCK=/run/user/1000/keyring/ssh, DEFAULTS_PATH=/usr/share/gconf/ubuntu.default.path, TMUX=/tmp/tmux-1000/default,10844,2, XDG_CONFIG_DIRS=/etc/xdg/xdg-ubuntu:/usr/share/upstart/xdg:/etc/xdg, DESKTOP_SESSION=ubuntu, PATH=/usr/share/lando/bin:/home/ctamayo/bin:/home/ctamayo/.local/bin:/home/ctamayo/.rbenv/shims:/home/ctamayo/dotfiles/bin:/home/ctamayo/.rbenv/shims:/home/ctamayo/.rbenv/shims:/home/ctamayo/.rbenv/bin:/home/ctamayo/dotfiles/bin:/home/ctamayo/bin:/home/ctamayo/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin, QT_QPA_PLATFORMTHEME=appmenu-qt5, QT_IM_MODULE=ibus, XDG_SESSION_TYPE=x11, PWD=/home/ctamayo/Kalabox/emerald-city-staffing/code, JOB=unity-settings-daemon, XMODIFIERS=@im=ibus, EDITOR=vim, GNOME_KEYRING_PID=, LANG=en_US.UTF-8, GDM_LANG=en_US, MANDATORY_PATH=/usr/share/gconf/ubuntu.mandatory.path, NODE_PATH=/usr/lib/nodejs:/usr/lib/node_modules:/usr/share/javascript, TMUX_PANE=%5, COMPIZ_CONFIG_PROFILE=ubuntu, IM_CONFIG_PHASE=1, PS1=\u@\h\[$(tput bold 1)\]\[\e[1;35m\]$(__git_ps1) \[\e[01;32m\]$(__cwd_ps1)$(__env_ps1)\[$(tput sgr0)\] \$ , GDMSESSION=ubuntu, RBENV_SHELL=bash, HISTCONTROL=ignoreboth, SESSIONTYPE=gnome-session, GTK2_MODULES=overlay-scrollbar, XDG_SEAT=seat0, HOME=/home/ctamayo, SHLVL=3, LANGUAGE=en_US, GNOME_DESKTOP_SESSION_ID=this-is-deprecated, UPSTART_INSTANCE=, XDG_SESSION_DESKTOP=ubuntu, UPSTART_EVENTS=xsession started, LOGNAME=ctamayo, COMPIZ_BIN_PATH=/usr/bin/, XDG_DATA_DIRS=/usr/share/ubuntu:/usr/share/gnome:/usr/local/share/:/usr/share/:/var/lib/snapd/desktop, QT4_IM_MODULE=xim, DBUS_SESSION_BUS_ADDRESS=unix:abstract=/tmp/dbus-magz8hV1Y1, LESSOPEN=| /usr/bin/lesspipe %s, INSTANCE=, UPSTART_JOB=unity7, XDG_RUNTIME_DIR=/run/user/1000, DISPLAY=:0, XDG_CURRENT_DESKTOP=Unity, GTK_IM_MODULE=ibus, LESSCLOSE=/usr/bin/lesspipe %s %s, XAUTHORITY=/home/ctamayo/.Xauthority, OLDPWD=/home/ctamayo, _=/usr/local/bin/lando, LANDO_ENGINE_ID=1000, LANDO_ENGINE_GID=1000, LANDO_ENGINE_HOME=/home/ctamayo, LANDO_ENGINE_IP=tcp://127.0.0.1, LANDO_ENGINE_REMOTE_IP=10.0.10.20, LANDO_ENGINE_CONFIG_DIR=/home/ctamayo/.lando/services/config, LANDO_ENGINE_SCRIPTS_DIR=/home/ctamayo/.lando/services/config/scripts, LANDO_ENGINE_HELPERS_DIR=/home/ctamayo/.lando/services/config/helpers
Engine is up.
Cached true with key engineUp for {"persist":false,"ttl":5}
Failed to cache true with key engineUp
Engine is up.
Cached true with key engineUp for {"persist":false,"ttl":5}
Failed to cache true with key engineUp
Emitting event pre-wp
Event pre-wp has 0 listeners
Retrieved from memcache with key engineUp
Emitting event pre-engine-run
Event pre-engine-run has 0 listeners
Exec cd "$LANDO_MOUNT"&&wp --allow-root on emeraldcitystaffing_appserver_1 in mode attach
With opts AttachStdin=true, AttachStdout=true, AttachStderr=true, Cmd=[/bin/sh, -c, cd "$LANDO_MOUNT"&&wp --allow-root], Env=[], DetachKeys=ctrl-p,ctrl-q, Tty=true, User=www-data
PHP Fatal error:  Uncaught Error: Call to undefined function get_role() in phar:///usr/local/bin/wp/php/WP_CLI/Runner.php(964) : eval()'d code:161
Stack trace:
#0 phar:///usr/local/bin/wp/php/WP_CLI/Runner.php(964): eval()
#1 phar:///usr/local/bin/wp/php/WP_CLI/Runner.php(927): WP_CLI\Runner->load_wordpress()
#2 phar:///usr/local/bin/wp/php/WP_CLI/Bootstrap/LaunchRunner.php(23): WP_CLI\Runner->start()
#3 phar:///usr/local/bin/wp/php/bootstrap.php(75): WP_CLI\Bootstrap\LaunchRunner->process(Object(WP_CLI\Bootstrap\BootstrapState))
#4 phar:///usr/local/bin/wp/php/wp-cli.php(23): WP_CLI\bootstrap()
#5 phar:///usr/local/bin/wp/php/boot-phar.php(8): include('phar:///usr/loc...')
#6 /usr/local/bin/wp(4): include('phar:///usr/loc...')
#7 {main}
  thrown in phar:///usr/local/bin/wp/php/WP_CLI/Runner.php(964) : eval()'d code on line 161

Fatal error: Uncaught Error: Call to undefined function get_role() in phar:///usr/local/bin/wp/php/WP_CLI/Runner.php(964) : eval()'d code on line 161

Error: Call to undefined function get_role() in phar:///usr/local/bin/wp/php/WP_CLI/Runner.php(964) : eval()'d code on line 161

Call Stack:
    0.0002     379400   1. {main}() /usr/local/bin/wp:0
    0.0139    1065936   2. include('phar:///usr/local/bin/wp/php/boot-phar.php') /usr/local/bin/wp:4
    0.0140    1072368   3. include('phar:///usr/local/bin/wp/php/wp-cli.php') phar:///usr/local/bin/wp/php/boot-phar.php:8
    0.0140    1081128   4. WP_CLI\bootstrap() phar:///usr/local/bin/wp/php/wp-cli.php:23
    0.0499    6533864   5. WP_CLI\Bootstrap\LaunchRunner->process() phar:///usr/local/bin/wp/php/bootstrap.php:75
    0.0499    6533904   6. WP_CLI\Runner->start() phar:///usr/local/bin/wp/php/WP_CLI/Bootstrap/LaunchRunner.php:23
    0.0505    6639544   7. WP_CLI\Runner->load_wordpress() phar:///usr/local/bin/wp/php/WP_CLI/Runner.php:927
    0.0508    6670824   8. eval('


... here it outputs the contents of my entire wp-config.php D: ...

') phar:///usr/local/bin/wp/php/WP_CLI/Runner.php:964

Exec cd "$LANDO_MOUNT"&&wp --allow-root completed
With result ID=89d82e43c979ea1edf7328aea0bdc0215a3b733118a4263e33d95247aaf78111, Running=false, ExitCode=255, tty=true, entrypoint=/bin/sh, arguments=[-c, cd "$LANDO_MOUNT"&&wp --allow-root], privileged=false, user=www-data, OpenStdin=true, OpenStderr=true, OpenStdout=true, CanRemove=false, ContainerID=a87eefa100037256459d3c122a7a36667c382ef2bf6356723a27d05383ad7204, DetachKeys=EBE=, Pid=14187
```

**Tell us generally about your bug**

I need to run arbitrary `wp` commands inside the container.

**Does this bug prevent you from using lando?**

Not altogether, but it makes debugging much more difficult.

**Comment by pirog** [comment]
@acobster if you run `lando rebuild` on your app it will pull the latest versions of our containers which im **guessing** probably have WP CLI 1.3.x in them
