### ISSUE TITLE
PHP 8.1.6 is causing error on pre-release 3.6.4

### ISSUE THREAD

**Issue by madaley1** [lando/lando#3412]
Here's the error I'm getting:
```
██╗   ██╗██╗  ██╗     ██████╗ ██╗  ██╗██╗
██║   ██║██║  ██║    ██╔═══██╗██║  ██║██║
██║   ██║███████║    ██║   ██║███████║██║
██║   ██║██╔══██║    ██║   ██║██╔══██║╚═╝
╚██████╔╝██║  ██║    ╚██████╔╝██║  ██║██╗
 ╚═════╝ ╚═╝  ╚═╝     ╚═════╝ ╚═╝  ╚═╝╚═╝


An error occurred while starting up your app!
Here are a few things you can try to get back into a good state:

  ■ Try running lando rebuild
  ■ Try restarting in debug mode lando restart -vvv
  ■ Try checking the logs with lando logs

If those fail then consult the troubleshooting materials:

  ■ https://docs.lando.dev/help/logs.html
  ■ https://docs.lando.dev/help/updating.html

Or post your issue to Slack or GitHub

  ■ Slack - https://launchpass.com/devwithlando
  ■ GitHub - https://github.com/lando/lando/issues/new/choose

ERROR ==> php version 9.1.6 is not supported
```
I am sure I'm on 8.1.6, and since I don't believe there is a php 9, I'm not sure why it is telling me that is what is being used.

**Comment by Rufus13apostol** [comment]
Could you shared the yaml file? What happens if you `lando restart -vvv` ?

**Comment by madaley1** [comment]
Here's the output of lando restart -vvv
```
lando 12:28:46 DEBUG ==> No update available.
lando 12:28:46 VERBOSE ==> starting bootstrap at level app...
lando 12:28:46 VERBOSE ==> config bootstrap beginning...
lando 12:28:46 DEBUG ==> emitting event pre-bootstrap-config
lando 12:28:46 DEBUG ==> plugin lando-core loaded from C:/snapshot/cli/plugins/lando-core/index.js
lando 12:28:46 DEBUG ==> plugin lando-events loaded from C:/snapshot/cli/plugins/lando-events/index.js
lando 12:28:46 DEBUG ==> plugin lando-networking loaded from C:/snapshot/cli/plugins/lando-networking/index.js
lando 12:28:46 DEBUG ==> plugin lando-proxy loaded from C:/snapshot/cli/plugins/lando-proxy/index.js
lando 12:28:46 DEBUG ==> plugin lando-recipes loaded from C:/snapshot/cli/plugins/lando-recipes/index.js
lando 12:28:46 DEBUG ==> plugin lando-services loaded from C:/snapshot/cli/plugins/lando-services/index.js
lando 12:28:46 DEBUG ==> plugin lando-sharing loaded from C:/snapshot/cli/plugins/lando-sharing/index.js
lando 12:28:46 DEBUG ==> plugin lando-test loaded from C:/snapshot/cli/plugins/lando-test/index.js
lando 12:28:46 DEBUG ==> plugin lando-tooling loaded from C:/snapshot/cli/plugins/lando-tooling/index.js
lando 12:28:46 DEBUG ==> plugin @lando/acquia loaded from C:/snapshot/cli/node_modules/@lando/acquia/index.js
lando 12:28:46 DEBUG ==> plugin @lando/apache loaded from C:/snapshot/cli/node_modules/@lando/apache/index.js
lando 12:28:46 DEBUG ==> plugin @lando/backdrop loaded from C:/snapshot/cli/node_modules/@lando/backdrop/index.js
lando 12:28:46 DEBUG ==> plugin @lando/compose loaded from C:/snapshot/cli/node_modules/@lando/compose/index.js
lando 12:28:46 DEBUG ==> plugin @lando/dotnet loaded from C:/snapshot/cli/node_modules/@lando/dotnet/index.js
lando 12:28:46 DEBUG ==> plugin @lando/drupal loaded from C:/snapshot/cli/node_modules/@lando/drupal/index.js
lando 12:28:46 DEBUG ==> plugin @lando/elasticsearch loaded from C:/snapshot/cli/node_modules/@lando/elasticsearch/index.js
lando 12:28:46 DEBUG ==> plugin @lando/go loaded from C:/snapshot/cli/node_modules/@lando/go/index.js
lando 12:28:46 DEBUG ==> plugin @lando/joomla loaded from C:/snapshot/cli/node_modules/@lando/joomla/index.js
lando 12:28:46 DEBUG ==> plugin @lando/lagoon loaded from C:/snapshot/cli/node_modules/@lando/lagoon/index.js
lando 12:28:46 DEBUG ==> plugin @lando/lamp loaded from C:/snapshot/cli/node_modules/@lando/lamp/index.js
lando 12:28:46 DEBUG ==> plugin @lando/laravel loaded from C:/snapshot/cli/node_modules/@lando/laravel/index.js
lando 12:28:46 DEBUG ==> plugin @lando/lemp loaded from C:/snapshot/cli/node_modules/@lando/lemp/index.js
lando 12:28:46 DEBUG ==> plugin @lando/mailhog loaded from C:/snapshot/cli/node_modules/@lando/mailhog/index.js
lando 12:28:46 DEBUG ==> plugin @lando/mariadb loaded from C:/snapshot/cli/node_modules/@lando/mariadb/index.js
lando 12:28:46 DEBUG ==> plugin @lando/mean loaded from C:/snapshot/cli/node_modules/@lando/mean/index.js
lando 12:28:46 DEBUG ==> plugin @lando/memcached loaded from C:/snapshot/cli/node_modules/@lando/memcached/index.js
lando 12:28:46 DEBUG ==> plugin @lando/mongo loaded from C:/snapshot/cli/node_modules/@lando/mongo/index.js
lando 12:28:46 DEBUG ==> plugin @lando/mssql loaded from C:/snapshot/cli/node_modules/@lando/mssql/index.js
lando 12:28:46 DEBUG ==> plugin @lando/mysql loaded from C:/snapshot/cli/node_modules/@lando/mysql/index.js
lando 12:28:46 DEBUG ==> plugin @lando/nginx loaded from C:/snapshot/cli/node_modules/@lando/nginx/index.js
lando 12:28:46 DEBUG ==> plugin @lando/node loaded from C:/snapshot/cli/node_modules/@lando/node/index.js
lando 12:28:46 DEBUG ==> plugin @lando/pantheon loaded from C:/snapshot/cli/node_modules/@lando/pantheon/index.js
lando 12:28:46 DEBUG ==> plugin @lando/php loaded from C:/snapshot/cli/node_modules/@lando/php/index.js
lando 12:28:46 DEBUG ==> plugin @lando/phpmyadmin loaded from C:/snapshot/cli/node_modules/@lando/phpmyadmin/index.js
lando 12:28:46 DEBUG ==> plugin @lando/platformsh loaded from C:/snapshot/cli/node_modules/@lando/platformsh/index.js
lando 12:28:46 DEBUG ==> plugin @lando/postgres loaded from C:/snapshot/cli/node_modules/@lando/postgres/index.js
lando 12:28:46 DEBUG ==> plugin @lando/python loaded from C:/snapshot/cli/node_modules/@lando/python/index.js
lando 12:28:46 DEBUG ==> plugin @lando/redis loaded from C:/snapshot/cli/node_modules/@lando/redis/index.js
lando 12:28:46 DEBUG ==> plugin @lando/ruby loaded from C:/snapshot/cli/node_modules/@lando/ruby/index.js
lando 12:28:46 DEBUG ==> plugin @lando/solr loaded from C:/snapshot/cli/node_modules/@lando/solr/index.js
lando 12:28:46 DEBUG ==> plugin @lando/symfony loaded from C:/snapshot/cli/node_modules/@lando/symfony/index.js
lando 12:28:46 DEBUG ==> plugin @lando/tomcat loaded from C:/snapshot/cli/node_modules/@lando/tomcat/index.js
lando 12:28:46 DEBUG ==> plugin @lando/varnish loaded from C:/snapshot/cli/node_modules/@lando/varnish/index.js
lando 12:28:46 DEBUG ==> plugin @lando/wordpress loaded from C:/snapshot/cli/node_modules/@lando/wordpress/index.js
lando 12:28:46 DEBUG ==> emitting event post-bootstrap-config
lando 12:28:46 VERBOSE ==> building proxy config...
lando 12:28:46 VERBOSE ==> config bootstrap completed.
lando 12:28:46 VERBOSE ==> tasks bootstrap beginning...
lando 12:28:46 DEBUG ==> emitting event pre-bootstrap-tasks
lando 12:28:46 DEBUG ==> autoloaded task config
lando 12:28:46 DEBUG ==> autoloaded task destroy
lando 12:28:46 DEBUG ==> autoloaded task info
lando 12:28:46 DEBUG ==> autoloaded task list
lando 12:28:46 DEBUG ==> autoloaded task logs
lando 12:28:46 DEBUG ==> autoloaded task poweroff
lando 12:28:46 DEBUG ==> autoloaded task rebuild
lando 12:28:46 DEBUG ==> autoloaded task restart
lando 12:28:46 DEBUG ==> autoloaded task share
lando 12:28:46 DEBUG ==> autoloaded task start
lando 12:28:46 DEBUG ==> autoloaded task stop
lando 12:28:46 DEBUG ==> autoloaded task version
lando 12:28:46 DEBUG ==> autoloaded task init
lando 12:28:46 DEBUG ==> autoloaded task ssh
lando 12:28:46 DEBUG ==> emitting event post-bootstrap-tasks
lando 12:28:46 VERBOSE ==> tasks bootstrap completed.
lando 12:28:46 VERBOSE ==> engine bootstrap beginning...
lando 12:28:46 DEBUG ==> emitting event pre-bootstrap-engine
lando 12:28:46 DEBUG ==> automoved scripts from C:\snapshot\cli\plugins\lando-core\scripts to C:\Users\madaley1\.lando\scripts and set to mode 755
lando 12:28:46 DEBUG ==> automoved scripts from C:\snapshot\cli\plugins\lando-proxy\scripts to C:\Users\madaley1\.lando\scripts and set to mode 755
lando 12:28:46 DEBUG ==> automoved scripts from C:\snapshot\cli\plugins\lando-recipes\scripts to C:\Users\madaley1\.lando\scripts and set to mode 755
lando 12:28:46 DEBUG ==> automoved scripts from C:\snapshot\cli\plugins\lando-services\scripts to C:\Users\madaley1\.lando\scripts and set to mode 755
lando 12:28:46 DEBUG ==> automoved scripts from C:\snapshot\cli\plugins\lando-sharing\scripts to C:\Users\madaley1\.lando\scripts and set to mode 755
lando 12:28:46 DEBUG ==> automoved scripts from C:\snapshot\cli\node_modules\@lando\acquia\scripts to C:\Users\madaley1\.lando\scripts and set to mode 755
lando 12:28:46 DEBUG ==> automoved scripts from C:\snapshot\cli\node_modules\@lando\lagoon\scripts to C:\Users\madaley1\.lando\scripts and set to mode 755
lando 12:28:46 DEBUG ==> automoved scripts from C:\snapshot\cli\node_modules\@lando\pantheon\scripts to C:\Users\madaley1\.lando\scripts and set to mode 755
lando 12:28:46 DEBUG ==> automoved scripts from C:\snapshot\cli\node_modules\@lando\platformsh\scripts to C:\Users\madaley1\.lando\scripts and set to mode 755
lando 12:28:46 DEBUG ==> emitting event post-bootstrap-engine
lando 12:28:46 VERBOSE ==> engine bootstrap completed.
lando 12:28:46 VERBOSE ==> app bootstrap beginning...
lando 12:28:46 DEBUG ==> emitting event pre-bootstrap-app
lando 12:28:46 DEBUG ==> autoloaded builder LandoCompose
lando 12:28:46 DEBUG ==> autoloaded builder LandoAppserver
lando 12:28:46 DEBUG ==> autoloaded builder LandoService
lando 12:28:46 DEBUG ==> autoloaded builder LandoUtility
lando 12:28:46 DEBUG ==> autoloaded builder LandoWebServer
lando 12:28:46 DEBUG ==> autoloaded builder LandoDrupal
lando 12:28:46 DEBUG ==> autoloaded builder LandoLaemp
lando 12:28:46 DEBUG ==> autoloaded builder LandoAppserver
lando 12:28:46 DEBUG ==> autoloaded builder LandoPlatformAppserver
lando 12:28:46 DEBUG ==> autoloaded builder LandoPlatformService
lando 12:28:46 DEBUG ==> autoloaded builder LandoCa
lando 12:28:46 DEBUG ==> autoloaded builder LandoProxy
lando 12:28:46 DEBUG ==> autoloaded builder LandoInit
lando 12:28:46 DEBUG ==> autoloaded builder LandoMounter
lando 12:28:46 DEBUG ==> autoloaded builder LandoApache
lando 12:28:46 DEBUG ==> autoloaded builder LandoCompose
lando 12:28:46 DEBUG ==> autoloaded builder LandoDotNet
lando 12:28:46 DEBUG ==> autoloaded builder LandoElasticSearch
lando 12:28:46 DEBUG ==> autoloaded builder LandoGo
lando 12:28:46 DEBUG ==> autoloaded builder LandoLagoonElasticsearch
lando 12:28:46 DEBUG ==> autoloaded builder LandoLagoonMariaDb
lando 12:28:46 DEBUG ==> autoloaded builder LandoLagoonNginx
lando 12:28:46 DEBUG ==> autoloaded builder LandoLagoonNone
lando 12:28:46 DEBUG ==> autoloaded builder LandoLagoonPhp
lando 12:28:46 DEBUG ==> autoloaded builder LandoLagoonPhp
lando 12:28:46 DEBUG ==> autoloaded builder LandoLagoonPostgres
lando 12:28:46 DEBUG ==> autoloaded builder LandoLagoonRedis
lando 12:28:46 DEBUG ==> autoloaded builder LandoLagoonSolr
lando 12:28:46 DEBUG ==> autoloaded builder LandoLagoonVarnish
lando 12:28:46 DEBUG ==> autoloaded builder LandoMailHog
lando 12:28:46 DEBUG ==> autoloaded builder LandoMariaDb
lando 12:28:46 DEBUG ==> autoloaded builder LandoMemcached
lando 12:28:46 DEBUG ==> autoloaded builder LandoMongoDb
lando 12:28:46 DEBUG ==> autoloaded builder LandoMsSql
lando 12:28:46 DEBUG ==> autoloaded builder LandoMySql
lando 12:28:46 DEBUG ==> autoloaded builder LandoNginx
lando 12:28:46 DEBUG ==> autoloaded builder LandoNode
lando 12:28:46 DEBUG ==> autoloaded builder PantheonMariaDb
lando 12:28:46 DEBUG ==> autoloaded builder LandoPhp
lando 12:28:46 DEBUG ==> autoloaded builder LandoPma
lando 12:28:46 DEBUG ==> autoloaded builder LandoPlatformshChromeHeadless
lando 12:28:46 DEBUG ==> autoloaded builder LandoPlatformsElasticsearch
lando 12:28:46 DEBUG ==> autoloaded builder LandoPlatformshInfluxdb
lando 12:28:46 DEBUG ==> autoloaded builder LandoPlatformshKafka
lando 12:28:46 DEBUG ==> autoloaded builder LandoPlatformshMariaDB
lando 12:28:46 DEBUG ==> autoloaded builder LandoPlatformshMemcached
lando 12:28:46 DEBUG ==> autoloaded builder LandoPlatformsMongoDB
lando 12:28:46 DEBUG ==> autoloaded builder LandoPlatformshMySQL
lando 12:28:46 DEBUG ==> autoloaded builder LandoPlatformshPhp
lando 12:28:46 DEBUG ==> autoloaded builder LandoPlatformshPostgres
lando 12:28:46 DEBUG ==> autoloaded builder LandoPlatformshRabbitmq
lando 12:28:46 DEBUG ==> autoloaded builder LandoPlatformshRedis
lando 12:28:46 DEBUG ==> autoloaded builder LandoPlatformshSolr
lando 12:28:46 DEBUG ==> autoloaded builder LandoPlatformshVarnish
lando 12:28:46 DEBUG ==> autoloaded builder LandoPostgres
lando 12:28:46 DEBUG ==> autoloaded builder LandoPython
lando 12:28:46 DEBUG ==> autoloaded builder LandoRedis
lando 12:28:46 DEBUG ==> autoloaded builder LandoRuby
lando 12:28:46 DEBUG ==> autoloaded builder LandoSolr
lando 12:28:46 DEBUG ==> autoloaded builder LandoTomcat
lando 12:28:46 DEBUG ==> autoloaded builder LandoVarnish
lando 12:28:46 DEBUG ==> autoloaded builder LandoAcquia
lando 12:28:46 DEBUG ==> autoloaded builder LandoBackdrop
lando 12:28:46 DEBUG ==> autoloaded builder LandoDrupal10
lando 12:28:46 DEBUG ==> autoloaded builder LandoDrupal6
lando 12:28:46 DEBUG ==> autoloaded builder LandoDrupal7
lando 12:28:47 DEBUG ==> autoloaded builder LandoDrupal8
lando 12:28:47 DEBUG ==> autoloaded builder LandoDrupal9
lando 12:28:47 DEBUG ==> autoloaded builder LandoJoomla
lando 12:28:47 DEBUG ==> autoloaded builder LandoLagoon
lando 12:28:47 DEBUG ==> autoloaded builder LandoLamp
lando 12:28:47 DEBUG ==> autoloaded builder LandoLaravel
lando 12:28:47 DEBUG ==> autoloaded builder LandoLamp
lando 12:28:47 DEBUG ==> autoloaded builder LandoMean
lando 12:28:47 DEBUG ==> autoloaded builder LandoPantheon
lando 12:28:47 DEBUG ==> autoloaded builder LandoPlatformsh
lando 12:28:47 DEBUG ==> autoloaded builder LandoSymfony
lando 12:28:47 DEBUG ==> autoloaded builder LandoWordPress
lando 12:28:47 DEBUG ==> emitting event post-bootstrap-app
lando 12:28:47 VERBOSE ==> app bootstrap completed.
lando 12:28:47 VERBOSE ==> bootstrap completed.
lando 12:28:47 DEBUG ==> emitting event post-bootstrap
lando 12:28:47 VERBOSE ==> docker-engine exists: true
lando 12:28:47 VERBOSE ==> docker-compose exists: true
lando 12:28:47 DEBUG ==> emitting event cli-answers
lando 12:28:47 VERBOSE ==> checking docker version compatibility...
lando 12:28:47 DEBUG ==> compatibility results name=desktop, link=https://docs.docker.com/docker-for-windows/release-notes/, wants=2.1.0.0 - 3.6.99, version=3.6.0, semversion=3.6.0, semmin=2.1.0, semmax=3.6.99, dockerVersion=true, satisfied=true
lando 12:28:47 DEBUG ==> emitting event cli-restart-answers
lando 12:28:47 DEBUG ==> emitting event cli-run
lando 12:28:47 DEBUG ==> emitting event cli-restart-run
lando 12:28:47 INFO ==> loading app drupal-base from config files 0=C:\Users\madaley1\Desktop\localDev\local\drupal-10.0.0-alpha3\.lando.yml
lando 12:28:47 DEBUG ==> app drupal-base has config name=drupal-base, recipe=drupal9, webroot=., php=9.1.6
Stopping and restarting your app...Shiny!
drupal-base 12:28:47 INFO ==> restarting app...
drupal-base 12:28:47 INFO ==> stopping app...
drupal-base 12:28:47 VERBOSE ==> initiatilizing app at C:\Users\madaley1\Desktop\localDev\local\drupal-10.0.0-alpha3...
lando       12:28:47 DEBUG ==> plugin lando-core loaded from C:\snapshot\cli\plugins\lando-core\app.js
lando       12:28:47 DEBUG ==> plugin lando-events loaded from C:\snapshot\cli\plugins\lando-events\app.js
lando       12:28:47 DEBUG ==> plugin lando-networking loaded from C:\snapshot\cli\plugins\lando-networking\app.js
drupal-base 12:28:47 VERBOSE ==> proxy settings detected.
lando       12:28:47 DEBUG ==> plugin lando-proxy loaded from C:\snapshot\cli\plugins\lando-proxy\app.js
lando       12:28:47 DEBUG ==> plugin lando-recipes loaded from C:\snapshot\cli\plugins\lando-recipes\app.js
lando       12:28:47 DEBUG ==> plugin lando-services loaded from C:\snapshot\cli\plugins\lando-services\app.js
lando       12:28:47 DEBUG ==> plugin lando-sharing loaded from C:\snapshot\cli\plugins\lando-sharing\app.js
lando       12:28:47 DEBUG ==> plugin lando-tooling loaded from C:\snapshot\cli\plugins\lando-tooling\app.js
lando       12:28:47 DEBUG ==> plugin @lando/acquia loaded from C:\snapshot\cli\node_modules\@lando\acquia\app.js
lando       12:28:47 DEBUG ==> plugin @lando/lagoon loaded from C:\snapshot\cli\node_modules\@lando\lagoon\app.js
lando       12:28:47 DEBUG ==> plugin @lando/pantheon loaded from C:\snapshot\cli\node_modules\@lando\pantheon\app.js
lando       12:28:47 DEBUG ==> plugin @lando/platformsh loaded from C:\snapshot\cli\node_modules\@lando\platformsh\app.js
drupal-base 12:28:47 DEBUG ==> emitting event pre-init
drupal-base 12:28:47 VERBOSE ==> building drupal9 recipe named
lando       12:28:47 VERBOSE ==> proxy is ON.
lando       12:28:47 VERBOSE ==> Setting the default proxy certificate /certs/cert.crt
drupal-base 12:28:47 VERBOSE ==> building php service appserver
drupal-base 12:28:47 ERROR ==> php version 9.1.6 is not supported message=php version 9.1.6 is not supported, stack=Error: php version 9.1.6 is not supported
    at new LandoCompose (C:\snapshot\cli\plugins\lando-core\compose\lando\builder.js)
    at new LandoAppserver (C:\snapshot\cli\plugins\lando-core\types\appserver\builder.js)
    at new LandoPhp (C:\snapshot\cli\node_modules\@lando\php\services\php\builder.js)
    at C:\snapshot\cli\plugins\lando-services\app.js
    at arrayEach (C:\snapshot\cli\node_modules\lodash\lodash.js:530:11)
    at Function.forEach (C:\snapshot\cli\node_modules\lodash\lodash.js:9410:14)
    at AsyncEvents.<anonymous> (C:\snapshot\cli\plugins\lando-services\app.js)
    at AsyncEvents.handle (C:\snapshot\cli\lib\events.js)
    at C:\snapshot\cli\lib\events.js
From previous event:
    at AsyncEvents.emit (C:\snapshot\cli\lib\events.js)
    at C:\snapshot\cli\lib\app.js
From previous event:
    at App.init (C:\snapshot\cli\lib\app.js)
    at initAndReport (C:\snapshot\cli\lib\app.js)
    at App.stop (C:\snapshot\cli\lib\app.js)
    at App.restart (C:\snapshot\cli\lib\app.js)
    at Object.run (C:\snapshot\cli\plugins\lando-core\tasks\restart.js)
From previous event:
    at C:\snapshot\cli\lib\cli.js
From previous event:
    at Object.handler (C:\snapshot\cli\lib\cli.js)
    at Object.runCommand (C:\snapshot\cli\node_modules\yargs\lib\command.js:238:44)
    at Object.parseArgs [as _parseArgs] (C:\snapshot\cli\node_modules\yargs\yargs.js:1063:30)
    at Function.get [as argv] (C:\snapshot\cli\node_modules\yargs\yargs.js:1004:21)
    at Cli.init (C:\snapshot\cli\lib\cli.js)
    at Cli.run (C:\snapshot\cli\lib\cli.js)
    at Object.<anonymous> (C:\snapshot\cli\bin\lando.js)
    at Module._compile (pkg/prelude/bootstrap.js:1887:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Function.runMain (pkg/prelude/bootstrap.js:1940:12)
    at internal/main/run_main_module.js:17:47, __stackCleaned__=true

██╗   ██╗██╗  ██╗     ██████╗ ██╗  ██╗██╗
██║   ██║██║  ██║    ██╔═══██╗██║  ██║██║
██║   ██║███████║    ██║   ██║███████║██║
██║   ██║██╔══██║    ██║   ██║██╔══██║╚═╝
╚██████╔╝██║  ██║    ╚██████╔╝██║  ██║██╗
 ╚═════╝ ╚═╝  ╚═╝     ╚═════╝ ╚═╝  ╚═╝╚═╝


An error occurred while starting up your app!
Here are a few things you can try to get back into a good state:

  ■ Try running lando rebuild
  ■ Try restarting in debug mode lando restart -vvv
  ■ Try checking the logs with lando logs

If those fail then consult the troubleshooting materials:

  ■ https://docs.lando.dev/help/logs.html
  ■ https://docs.lando.dev/help/updating.html

Or post your issue to Slack or GitHub

  ■ Slack - https://launchpass.com/devwithlando
  ■ GitHub - https://github.com/lando/lando/issues/new/choose

lando       12:28:47 ERROR ==> Error: php version 9.1.6 is not supported
    at new LandoCompose (C:\snapshot\cli\plugins\lando-core\compose\lando\builder.js)
    at new LandoAppserver (C:\snapshot\cli\plugins\lando-core\types\appserver\builder.js)
    at new LandoPhp (C:\snapshot\cli\node_modules\@lando\php\services\php\builder.js)
    at C:\snapshot\cli\plugins\lando-services\app.js
    at arrayEach (C:\snapshot\cli\node_modules\lodash\lodash.js:530:11)
    at Function.forEach (C:\snapshot\cli\node_modules\lodash\lodash.js:9410:14)
    at AsyncEvents.<anonymous> (C:\snapshot\cli\plugins\lando-services\app.js)
    at AsyncEvents.handle (C:\snapshot\cli\lib\events.js)
    at C:\snapshot\cli\lib\events.js
From previous event:
    at AsyncEvents.emit (C:\snapshot\cli\lib\events.js)
    at C:\snapshot\cli\lib\app.js
From previous event:
    at App.init (C:\snapshot\cli\lib\app.js)
    at initAndReport (C:\snapshot\cli\lib\app.js)
    at App.stop (C:\snapshot\cli\lib\app.js)
    at App.restart (C:\snapshot\cli\lib\app.js)
    at Object.run (C:\snapshot\cli\plugins\lando-core\tasks\restart.js)
From previous event:
    at C:\snapshot\cli\lib\cli.js
From previous event:
    at Object.handler (C:\snapshot\cli\lib\cli.js)
    at Object.runCommand (C:\snapshot\cli\node_modules\yargs\lib\command.js:238:44)
    at Object.parseArgs [as _parseArgs] (C:\snapshot\cli\node_modules\yargs\yargs.js:1063:30)
    at Function.get [as argv] (C:\snapshot\cli\node_modules\yargs\yargs.js:1004:21)
    at Cli.init (C:\snapshot\cli\lib\cli.js)
    at Cli.run (C:\snapshot\cli\lib\cli.js)
    at Object.<anonymous> (C:\snapshot\cli\bin\lando.js)
    at Module._compile (pkg/prelude/bootstrap.js:1887:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Function.runMain (pkg/prelude/bootstrap.js:1940:12)
    at internal/main/run_main_module.js:17:47
lando       12:28:47 VERBOSE ==> reporting error action to report=true, url=https://metrics.lando.dev, report=true, url=https://metrics.lando.dev
lando       12:28:47 DEBUG ==> reported data command=lando restart, context=local, devMode=false, instance=9194037c309721bd52d08502b4172ff0f3d40988, nodeVersion=v14.19.1, mode=cli, type=Windows_NT, platform=win32, release=10.0.19042, arch=x64, product=lando, version=3.6.5, message=php version 9.1.6 is not supported, stack=Error: php version 9.1.6 is not supported
    at new LandoCompose (builder.js)
    at new LandoAppserver (builder.js)
    at new LandoPhp (builder.js)
    at C:\snapshot\cli\plugins\lando-services\app.js
    at arrayEach (lodash.js:530:11)
    at Function.forEach (lodash.js:9410:14)
    at AsyncEvents.<anonymous> (app.js)
    at AsyncEvents.handle (events.js)
    at C:\snapshot\cli\lib\events.js
From previous event:
    at AsyncEvents.emit (events.js)
    at C:\snapshot\cli\lib\app.js
From previous event:
    at App.init (app.js)
    at initAndReport (app.js)
    at App.stop (app.js)
    at App.restart (app.js)
    at Object.run (restart.js)
From previous event:
    at C:\snapshot\cli\lib\cli.js
From previous event:
    at Object.handler (cli.js)
    at Object.runCommand (command.js:238:44)
    at Object.parseArgs [as _parseArgs] (yargs.js:1063:30)
    at Function.get [as argv] (yargs.js:1004:21)
    at Cli.init (cli.js)
    at Cli.run (cli.js)
    at Object.<anonymous> (lando.js)
    at Module._compile (pkg/prelude/bootstrap.js:1887:22)
    at Function.runMain (pkg/prelude/bootstrap.js:1940:12)
    at internal/main/run_main_module.js:17:47, action=error, created=2022-06-02T19:28:47.280Z
lando       12:28:47 DEBUG ==> engine is up.
lando       12:28:47 DEBUG ==> docker is running.
```
landofile code:

'''
name: drupal-base
recipe: drupal9
config:
  webroot: .
  php: '8.1.6'
'''

**Comment by madaley1** [comment]
Update: I deleted the .6 from the '8.1.6' and now it works, I'm not sure if that is a bug or intentional design. If someone can confirm this is intended we can close, else may want to keep it open.

**Comment by rabauss** [comment]
It's intended - see: 
https://docs.lando.dev/php/#supported-versions
and:
https://github.com/lando/php/blob/311eab6f789b974e20d4fd31786c4e0bc7b3d630/services/php/builder.js#L95

A minor version does not really make sense or do you have that requirement?

**Comment by rosana-sirvelia** [comment]
Hello, I'm  a beginer. I have lando 3.6.4. and I need to update the php version. In lando.yml doc the version is php 7.4 and I need the php 8.1 version. Could you help me please? I'm working with manjaro.
