### ISSUE TITLE
Ubuntu and docker

### ISSUE THREAD

**Issue by sm2017** [lando/lando#3427]
I have followed docs and [youtube](https://www.youtube.com/watch?v=n9ypNf2LP9A) to install lando on ubuntu

When I run `lando start` I have the following output

```
lando start
Let's get this party started! Starting app lantern...
WARN ==> docker is not running! 
Starting docker up before we begin... please wait...
ERROR ==> Could not automatically start the Docker Daemon. Please manually start it to continue. message=Could not automatically start the Docker Daemon. Please manually start it to continue., stack=Error: Could not automatically start the Docker Daemon. Please manually start it to continue.
    at /snapshot/cli/lib/daemon.js
From previous event:
    at LandoDaemon.up (/snapshot/cli/lib/daemon.js)
    at Object.eventWrapper (/snapshot/cli/lib/router.js)
    at Engine.engineCmd (/snapshot/cli/lib/engine.js)
    at Engine.list (/snapshot/cli/lib/engine.js)
    at AsyncEvents.<anonymous> (/snapshot/cli/plugins/lando-core/app.js)
    at AsyncEvents.handle (/snapshot/cli/lib/events.js)
    at /snapshot/cli/lib/events.js
From previous event:
    at AsyncEvents.emit (/snapshot/cli/lib/events.js)
    at /snapshot/cli/lib/app.js
From previous event:
    at App.init (/snapshot/cli/lib/app.js)
    at initAndReport (/snapshot/cli/lib/app.js)
    at App.start (/snapshot/cli/lib/app.js)
    at Object.run (/snapshot/cli/plugins/lando-core/tasks/start.js)
From previous event:
    at /snapshot/cli/lib/cli.js
From previous event:
    at Object.handler (/snapshot/cli/lib/cli.js)
    at Object.runCommand (/snapshot/cli/node_modules/yargs/lib/command.js:238:44)
    at Object.parseArgs [as _parseArgs] (/snapshot/cli/node_modules/yargs/yargs.js:1063:30)
    at Function.get [as argv] (/snapshot/cli/node_modules/yargs/yargs.js:1004:21)
    at Cli.init (/snapshot/cli/lib/cli.js)
    at Cli.run (/snapshot/cli/lib/cli.js)
    at Object.<anonymous> (/snapshot/cli/bin/lando.js)
    at Module._compile (pkg/prelude/bootstrap.js:1887:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Function.runMain (pkg/prelude/bootstrap.js:1940:12)
    at internal/main/run_main_module.js:17:47, __stackCleaned__=true

██╗   ██╗██╗  ██╗     ██████╗ ██╗  ██╗██╗
██║   ██║██║  ██║    ██╔═══██╗██║  ██║██║
██║   ██║███████║    ██║   ██║███████║██║
██║   ██║██╔══██║    ██║   ██║██╔══██║╚═╝
╚██████╔╝██║  ██║    ╚██████╔╝██║  ██║██╗
 ╚═════╝ ╚═╝  ╚═╝     ╚═════╝ ╚═╝  ╚═╝╚═╝
                                         

An error occurred while starting up your app!
Here are a few things you can try to get back into a good state:

  ■ Try running lando rebuild
  ■ Try restarting in debug mode lando restart -vvv
  ■ Try checking the logs with lando logs

If those fail then consult the troubleshooting materials:

  ■ https://docs.lando.dev/help/logs.html
  ■ https://docs.lando.dev/help/updating.html

Or post your issue to Slack or GitHub

  ■ Slack - https://launchpass.com/devwithlando
  ■ GitHub - https://github.com/lando/lando/issues/new/choose


 ██████╗██████╗  █████╗ ███████╗██╗  ██╗██╗██╗██╗
██╔════╝██╔══██╗██╔══██╗██╔════╝██║  ██║██║██║██║
██║     ██████╔╝███████║███████╗███████║██║██║██║
██║     ██╔══██╗██╔══██║╚════██║██╔══██║╚═╝╚═╝╚═╝
╚██████╗██║  ██║██║  ██║███████║██║  ██║██╗██╗██╗
 ╚═════╝╚═╝  ╚═╝╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝╚═╝╚═╝╚═╝
                                                 

Would you like to report it, and subsequent crashes, to Lando?

This data is only used by the Lando team to ensure the application runs as well as it can.
For more details check out https://docs.lando.dev/privacy/
? Send crash reports? Yes
ERROR ==> Could not automatically start the Docker Daemon. Please manually start it to continue. 

```

docker is installed and I can run it in non-root mode too

```
docker run hello-world

Hello from Docker!
This message shows that your installation appears to be working correctly.

To generate this message, Docker took the following steps:
 1. The Docker client contacted the Docker daemon.
 2. The Docker daemon pulled the "hello-world" image from the Docker Hub.
    (amd64)
 3. The Docker daemon created a new container from that image which runs the
    executable that produces the output you are currently reading.
 4. The Docker daemon streamed that output to the Docker client, which sent it
    to your terminal.

To try something more ambitious, you can run an Ubuntu container with:
 $ docker run -it ubuntu bash

Share images, automate workflows, and more with a free Docker ID:
 https://hub.docker.com/

For more examples and ideas, visit:
 https://docs.docker.com/get-started/


```

**Comment by rabauss** [comment]
Is your non-root user in the `docker` group? try to run:
```
sudo usermod -aG docker $USER`
```
I stumbled across this yesterday:
https://github.com/microsoft/WSL/issues/6655#issuecomment-1142933322

**Comment by sm2017** [comment]
Yes. I have tried before.

**Comment by phannphong** [comment]
I guess you need to start Docker Daemon first (`sudo systemctl start docker.service`) and after that, If it's still not working, try to restart your computer.

**Comment by sm2017** [comment]
Still not working after doing both

**Comment by phannphong** [comment]
Or maybe you're not create group `docker`? Check more detail at https://docs.docker.com/engine/install/linux-postinstall/#manage-docker-as-a-non-root-user

**Comment by sm2017** [comment]
I have followed that link

**Comment by shango** [comment]
I encountered this issue and it was resolved after a full restart of Ubuntu. Logging out was not sufficient.

**Comment by nosuprise** [comment]
Ubuntu 22.04 runs on SNAPS ... they way I got it to run was remove the docker snaps and reinstall using the procedures for docker and compose install from digitalocean.

**Comment by MrSalsbury** [comment]
All i know is by uninstalling those snaps i was able to get docker and docker compose to work.  If you are using SNAPS you need to access docker compose with docker.compose which looks like a problem for lando to handle.

**Comment by wp-coin** [comment]
Lando needs to be on homebrew... docker just starts up automatically

**Comment by D41196829** [comment]
For those who still having problem, i found a workaround that worked for me, the problem is that docker socket do not have proper permissions, running a:

sudo chmod 777 /var/run/docker.sock

Solved for me.

**Comment by ahmedch1** [comment]
> For those who still having problem, i found a workaround that worked for me, the problem is that docker socket do not have proper permissions, running a:
> 
> sudo chmod 777 /var/run/docker.sock
> 
> Solved for me.
> 
> _Note: This will give full access to your docker.dock file, if you believe that it is a problem find the proper permissions for your scenario._

Thanks @D41196829 , I was having lando takes time on start , (well I did not stay waiting much as my disk is SSD NVe) . But when I have used your command it is working without extra time .
