### ISSUE TITLE
`lando start` returns "Error: EACCES: permission denied, open '/home/sam/.lando/config.yml'"

### ISSUE THREAD

**Issue by AIGeneratedUsername** [lando/lando#3439]
# Steps to reproduce

Follow [Hello World!](https://docs.lando.dev/getting-started/first-app.html#hello-world) tutorial.

# Command 

`lando start`

# Error traceback

```bash
internal/fs/utils.js:332
    throw err;
    ^

Error: EACCES: permission denied, open '/home/sam/.lando/config.yml'
    at Object.openSync (fs.js:497:3)
    at Object.openSync (pkg/prelude/bootstrap.js:739:32)
    at Object.writeFileSync (fs.js:1528:35)
    at Yaml.dump (/snapshot/cli/lib/yaml.js)
    at Cli.updateUserConfig (/snapshot/cli/lib/cli.js)
    at Cli.run (/snapshot/cli/lib/cli.js)
    at Object.<anonymous> (/snapshot/cli/bin/lando.js)
    at Module._compile (pkg/prelude/bootstrap.js:1794:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32) {
  errno: -13,
  syscall: 'open',
  code: 'EACCES',
  path: '/home/sam/.lando/config.yml'
}
```
# System

- lando v3.6.4
- Lubuntu 22.04
- Docker version 20.10.17, build 100c701

**Comment by Mahdi-Abbariki** [comment]
same here

**Comment by pazthor** [comment]
in Linux (pop os)
I resolved thatt  check the   permission   in ~/.lando
```ls -la ```
 and change the permission 
```
 sudo chown -R user:user .lando
 ```

But I righ now I have another problem. i think is like  this https://github.com/lando/lando/issues/3336 haha :c

**Comment by javiertoledos** [comment]
Iḿ having the same problem, I installed lando with ignoring deps (I have docker desktop for linux) annd I got my ownership overwritten in the `.ssh` folder and in the `.lando` folder to the 100999 user and group.

**Comment by NazarTikhoniuk** [comment]
Same issue.

Lando 3.6.4
Ubuntu 22.04
Docker version 20.10.21, build baeda1f

**Comment by Gokujo** [comment]
Same issue here
```
node:internal/fs/utils:344
    throw err;
    ^

Error: EACCES: permission denied, unlink '/home/$USER/.lando/cache/_.tasks.cache'
    at Object.unlinkSync (node:fs:1722:3)
    at Object.<anonymous> (/snapshot/cli/bin/lando.js)
    at Module._compile (pkg/prelude/bootstrap.js:1887:22)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.runMain (pkg/prelude/bootstrap.js:1940:12)
    at node:internal/main/run_main_module:17:47 {
  errno: -13,
  syscall: 'unlink',
  code: 'EACCES',
  path: '/home/$USER/.lando/cache/_.tasks.cache'
}
```

I guess docker rewrites the permissions and even I am in docker group I get this kind of error every time
Command `sudo chown -R user:group ~/.lando` helps only once and then the rights get rewritten again.

**Comment by TheWoodenMan** [comment]
Same issue when trying to run `lando --version`
Ubuntu 22.04, 
lando x64 stable deb
docker 23.0.1 

```do --version
node:internal/fs/utils:344
    throw err;
    ^

Error: EACCES: permission denied, open '/home/andynwood/.lando/config.yml'
    at Object.openSync (node:fs:585:3)
    at Object.openSync (pkg/prelude/bootstrap.js:753:32)
    at Object.writeFileSync (node:fs:2157:35)
    at Yaml.dump (/snapshot/cli/node_modules/@lando/core/lib/yaml.js)
    at Cli.updateUserConfig (/snapshot/cli/lib/cli.js)
    at Cli.run (/snapshot/cli/lib/cli.js)
    at Object.<anonymous> (/snapshot/cli/bin/lando.js)
    at Module._compile (pkg/prelude/bootstrap.js:1887:22)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Module.load (node:internal/modules/cjs/loader:981:32) {
  errno: -13,
  syscall: 'open',
  code: 'EACCES',
  path: '/home/andynwood/.lando/config.yml'
}
```

**Comment by HarmonyAtHelloWorld** [comment]
> 

having issue, and with exact same file.

**Comment by Sm1g00l** [comment]
Same issue here as well. Today, after formatting my computer, I am encountering this exception on both versions 3.11 and 3.16. I have already removed and purged everything that was created by the Lando .deb package on reinstall.

**Comment by santino83** [comment]
Same error here using Ubuntu, Lando 3.17 and Docker-Desktop. Lando simply doesn't work, and change permissions everywhere.

**Comment by morovinger** [comment]
Same here using Ubuntu, Lando 3.17 and Docker-Desktop.

**Comment by LaYatiX** [comment]
Had the same issue. I was able to resolve it by downgrading docker-compose from V2 to 1.29.2 on Linux. On Docker Desktop there is checkbox to disable Docker Compose V2.

**Comment by J0hn3ch** [comment]
I had the same issue after a clean install of Docker Engine, Docker Compose and Lando. 
After I run the steps in the [First App tutorial](https://docs.lando.dev/getting-started/first-app.html) and execute lando init (with the parameters of tutorial) I get:

`Error: EACCES: permission denied, open '/home/user/.lando/cache/_.tasks.cache'`

### System

- Linux 5.19.0-43-generic
- Ubuntu 22.04.2 LTS
- Docker version 20.10.24, build 297e128
- docker-compose version 1.29.1, build c34c88b2
- Lando v3.18.0

**Comment by konfib** [comment]
Same issue after a clean install of 
docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin and Docker Desktop

Ubuntu 22.04.2 LTS
Linux 5.15.0-76-generic
Lando Version: 3.18.0
Docker version 24.0.4, build 3713ee1
docker-compose version 1.29.2-1


 
```
lando start -vvv
node:internal/fs/utils:345
    throw err;
    ^

Error: EACCES: permission denied, open '/home/user/.lando/config.yml'
    at Object.openSync (node:fs:585:3)
    at Object.openSync (pkg/prelude/bootstrap.js:796:32)
    at Object.writeFileSync (node:fs:2170:35)
    at Yaml.dump (/snapshot/cli/node_modules/@lando/core/lib/yaml.js)
    at Cli.updateUserConfig (/snapshot/cli/lib/cli.js)
    at Cli.run (/snapshot/cli/lib/cli.js)
    at Object.<anonymous> (/snapshot/cli/bin/lando.js)
    at Module._compile (pkg/prelude/bootstrap.js:1930:22)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32) {
  errno: -13,
  syscall: 'open',
  code: 'EACCES',
  path: '/home/user/.lando/config.yml'
}

```

What permission should  config.yml have?

**Comment by mwmdev** [comment]
Same here, everything was working fine, then did a `lando rebuild` and got a popin telling me I might give access to my home directory to Docker. After that I get the same error as everybody in this thread.

**Comment by luisalonsoduenasmanriquez-okta** [comment]
same here

**Comment by milos-ws** [comment]
Same here, it seems that Docker Desktop cannot work well on Linux Mint with Lando. However, Lando with Docker Engine (without Docker Desktop) works well.

**Comment by devlokman** [comment]
removing docker-desktop has worked also for me -.-
