### ISSUE TITLE
Cannot start any project (Cannot read property 'split' of null)

### ISSUE THREAD

**Issue by tpluscode** [lando/lando#3461]
A colleague of mine has this error when starting multiple of our lando projects. For example [this one](https://github.com/zazuko/ssz-view-builder/blob/main/.lando.yml), which produces the following output

I found similar error reported prior but appear to be something else?

```
kspace/ssz/ssz-view-builder publish-action
❯ lando start -vvv
lando 17:36:22 DEBUG ==> No update available.
lando 17:36:22 VERBOSE ==> starting bootstrap at level app...
lando 17:36:22 VERBOSE ==> config bootstrap beginning...
lando 17:36:22 DEBUG ==> emitting event pre-bootstrap-config
lando 17:36:22 DEBUG ==> plugin lando-core loaded from /snapshot/cli/plugins/lando-core/index.js
lando 17:36:22 DEBUG ==> plugin lando-events loaded from /snapshot/cli/plugins/lando-events/index.js
lando 17:36:22 DEBUG ==> plugin lando-networking loaded from /snapshot/cli/plugins/lando-networking/index.js
lando 17:36:22 DEBUG ==> plugin lando-proxy loaded from /snapshot/cli/plugins/lando-proxy/index.js
lando 17:36:22 DEBUG ==> plugin lando-recipes loaded from /snapshot/cli/plugins/lando-recipes/index.js
lando 17:36:22 DEBUG ==> plugin lando-services loaded from /snapshot/cli/plugins/lando-services/index.js
lando 17:36:22 DEBUG ==> plugin lando-sharing loaded from /snapshot/cli/plugins/lando-sharing/index.js
lando 17:36:22 DEBUG ==> plugin lando-test loaded from /snapshot/cli/plugins/lando-test/index.js
lando 17:36:22 DEBUG ==> plugin lando-tooling loaded from /snapshot/cli/plugins/lando-tooling/index.js
lando 17:36:22 DEBUG ==> plugin @lando/acquia loaded from /snapshot/cli/node_modules/@lando/acquia/index.js
lando 17:36:22 DEBUG ==> plugin @lando/apache loaded from /snapshot/cli/node_modules/@lando/apache/index.js
lando 17:36:22 DEBUG ==> plugin @lando/backdrop loaded from /snapshot/cli/node_modules/@lando/backdrop/index.js
lando 17:36:22 DEBUG ==> plugin @lando/compose loaded from /snapshot/cli/node_modules/@lando/compose/index.js
lando 17:36:22 DEBUG ==> plugin @lando/dotnet loaded from /snapshot/cli/node_modules/@lando/dotnet/index.js
lando 17:36:22 DEBUG ==> plugin @lando/drupal loaded from /snapshot/cli/node_modules/@lando/drupal/index.js
lando 17:36:22 DEBUG ==> plugin @lando/elasticsearch loaded from /snapshot/cli/node_modules/@lando/elasticsearch/index.js
lando 17:36:22 DEBUG ==> plugin @lando/go loaded from /snapshot/cli/node_modules/@lando/go/index.js
lando 17:36:22 DEBUG ==> plugin @lando/joomla loaded from /snapshot/cli/node_modules/@lando/joomla/index.js
lando 17:36:22 DEBUG ==> plugin @lando/lagoon loaded from /snapshot/cli/node_modules/@lando/lagoon/index.js
lando 17:36:22 DEBUG ==> plugin @lando/lamp loaded from /snapshot/cli/node_modules/@lando/lamp/index.js
lando 17:36:22 DEBUG ==> plugin @lando/laravel loaded from /snapshot/cli/node_modules/@lando/laravel/index.js
lando 17:36:22 DEBUG ==> plugin @lando/lemp loaded from /snapshot/cli/node_modules/@lando/lemp/index.js
lando 17:36:22 DEBUG ==> plugin @lando/mailhog loaded from /snapshot/cli/node_modules/@lando/mailhog/index.js
lando 17:36:22 DEBUG ==> plugin @lando/mariadb loaded from /snapshot/cli/node_modules/@lando/mariadb/index.js
lando 17:36:22 DEBUG ==> plugin @lando/mean loaded from /snapshot/cli/node_modules/@lando/mean/index.js
lando 17:36:22 DEBUG ==> plugin @lando/memcached loaded from /snapshot/cli/node_modules/@lando/memcached/index.js
lando 17:36:22 DEBUG ==> plugin @lando/mongo loaded from /snapshot/cli/node_modules/@lando/mongo/index.js
lando 17:36:22 DEBUG ==> plugin @lando/mssql loaded from /snapshot/cli/node_modules/@lando/mssql/index.js
lando 17:36:22 DEBUG ==> plugin @lando/mysql loaded from /snapshot/cli/node_modules/@lando/mysql/index.js
lando 17:36:22 DEBUG ==> plugin @lando/nginx loaded from /snapshot/cli/node_modules/@lando/nginx/index.js
lando 17:36:22 DEBUG ==> plugin @lando/node loaded from /snapshot/cli/node_modules/@lando/node/index.js
lando 17:36:22 DEBUG ==> plugin @lando/pantheon loaded from /snapshot/cli/node_modules/@lando/pantheon/index.js
lando 17:36:22 DEBUG ==> plugin @lando/php loaded from /snapshot/cli/node_modules/@lando/php/index.js
lando 17:36:22 DEBUG ==> plugin @lando/phpmyadmin loaded from /snapshot/cli/node_modules/@lando/phpmyadmin/index.js
lando 17:36:22 DEBUG ==> plugin @lando/platformsh loaded from /snapshot/cli/node_modules/@lando/platformsh/index.js
lando 17:36:22 DEBUG ==> plugin @lando/postgres loaded from /snapshot/cli/node_modules/@lando/postgres/index.js
lando 17:36:22 DEBUG ==> plugin @lando/python loaded from /snapshot/cli/node_modules/@lando/python/index.js
lando 17:36:22 DEBUG ==> plugin @lando/redis loaded from /snapshot/cli/node_modules/@lando/redis/index.js
lando 17:36:22 DEBUG ==> plugin @lando/ruby loaded from /snapshot/cli/node_modules/@lando/ruby/index.js
lando 17:36:22 DEBUG ==> plugin @lando/solr loaded from /snapshot/cli/node_modules/@lando/solr/index.js
lando 17:36:22 DEBUG ==> plugin @lando/symfony loaded from /snapshot/cli/node_modules/@lando/symfony/index.js
lando 17:36:22 DEBUG ==> plugin @lando/tomcat loaded from /snapshot/cli/node_modules/@lando/tomcat/index.js
lando 17:36:22 DEBUG ==> plugin @lando/varnish loaded from /snapshot/cli/node_modules/@lando/varnish/index.js
lando 17:36:22 DEBUG ==> plugin @lando/wordpress loaded from /snapshot/cli/node_modules/@lando/wordpress/index.js
lando 17:36:22 DEBUG ==> emitting event post-bootstrap-config
lando 17:36:22 VERBOSE ==> building proxy config...
lando 17:36:22 VERBOSE ==> config bootstrap completed.
lando 17:36:22 VERBOSE ==> tasks bootstrap beginning...
lando 17:36:22 DEBUG ==> emitting event pre-bootstrap-tasks
lando 17:36:22 DEBUG ==> autoloaded task config
lando 17:36:22 DEBUG ==> autoloaded task destroy
lando 17:36:22 DEBUG ==> autoloaded task info
lando 17:36:22 DEBUG ==> autoloaded task list
lando 17:36:22 DEBUG ==> autoloaded task logs
lando 17:36:22 DEBUG ==> autoloaded task poweroff
lando 17:36:22 DEBUG ==> autoloaded task rebuild
lando 17:36:22 DEBUG ==> autoloaded task restart
lando 17:36:22 DEBUG ==> autoloaded task share
lando 17:36:22 DEBUG ==> autoloaded task start
lando 17:36:22 DEBUG ==> autoloaded task stop
lando 17:36:22 DEBUG ==> autoloaded task version
lando 17:36:22 DEBUG ==> autoloaded task init
lando 17:36:22 DEBUG ==> autoloaded task ssh
lando 17:36:22 DEBUG ==> emitting event post-bootstrap-tasks
lando 17:36:22 VERBOSE ==> tasks bootstrap completed.
lando 17:36:22 VERBOSE ==> engine bootstrap beginning...
lando 17:36:22 DEBUG ==> emitting event pre-bootstrap-engine
lando 17:36:22 DEBUG ==> automoved scripts from /snapshot/cli/plugins/lando-core/scripts to /Users/ktk/.lando/scripts and set to mode 755
lando 17:36:22 DEBUG ==> automoved scripts from /snapshot/cli/plugins/lando-proxy/scripts to /Users/ktk/.lando/scripts and set to mode 755
lando 17:36:22 DEBUG ==> automoved scripts from /snapshot/cli/plugins/lando-recipes/scripts to /Users/ktk/.lando/scripts and set to mode 755
lando 17:36:22 DEBUG ==> automoved scripts from /snapshot/cli/plugins/lando-services/scripts to /Users/ktk/.lando/scripts and set to mode 755
lando 17:36:23 DEBUG ==> automoved scripts from /snapshot/cli/plugins/lando-sharing/scripts to /Users/ktk/.lando/scripts and set to mode 755
lando 17:36:23 DEBUG ==> automoved scripts from /snapshot/cli/node_modules/@lando/acquia/scripts to /Users/ktk/.lando/scripts and set to mode 755
lando 17:36:23 DEBUG ==> automoved scripts from /snapshot/cli/node_modules/@lando/lagoon/scripts to /Users/ktk/.lando/scripts and set to mode 755
lando 17:36:23 DEBUG ==> automoved scripts from /snapshot/cli/node_modules/@lando/pantheon/scripts to /Users/ktk/.lando/scripts and set to mode 755
lando 17:36:23 DEBUG ==> automoved scripts from /snapshot/cli/node_modules/@lando/platformsh/scripts to /Users/ktk/.lando/scripts and set to mode 755
lando 17:36:23 DEBUG ==> emitting event post-bootstrap-engine
lando 17:36:23 VERBOSE ==> engine bootstrap completed.
lando 17:36:23 VERBOSE ==> app bootstrap beginning...
lando 17:36:23 DEBUG ==> emitting event pre-bootstrap-app
lando 17:36:23 DEBUG ==> autoloaded builder LandoCompose
lando 17:36:23 DEBUG ==> autoloaded builder LandoAppserver
lando 17:36:23 DEBUG ==> autoloaded builder LandoService
lando 17:36:23 DEBUG ==> autoloaded builder LandoUtility
lando 17:36:23 DEBUG ==> autoloaded builder LandoWebServer
lando 17:36:23 DEBUG ==> autoloaded builder LandoDrupal
lando 17:36:23 DEBUG ==> autoloaded builder LandoLaemp
lando 17:36:23 DEBUG ==> autoloaded builder LandoAppserver
lando 17:36:23 DEBUG ==> autoloaded builder LandoPlatformAppserver
lando 17:36:23 DEBUG ==> autoloaded builder LandoPlatformService
lando 17:36:23 DEBUG ==> autoloaded builder LandoCa
lando 17:36:23 DEBUG ==> autoloaded builder LandoProxy
lando 17:36:23 DEBUG ==> autoloaded builder LandoInit
lando 17:36:23 DEBUG ==> autoloaded builder LandoMounter
lando 17:36:23 DEBUG ==> autoloaded builder LandoApache
lando 17:36:23 DEBUG ==> autoloaded builder LandoCompose
lando 17:36:23 DEBUG ==> autoloaded builder LandoDotNet
lando 17:36:23 DEBUG ==> autoloaded builder LandoElasticSearch
lando 17:36:23 DEBUG ==> autoloaded builder LandoGo
lando 17:36:23 DEBUG ==> autoloaded builder LandoLagoonElasticsearch
lando 17:36:23 DEBUG ==> autoloaded builder LandoLagoonMariaDb
lando 17:36:23 DEBUG ==> autoloaded builder LandoLagoonNginx
lando 17:36:23 DEBUG ==> autoloaded builder LandoLagoonNone
lando 17:36:23 DEBUG ==> autoloaded builder LandoLagoonPhp
lando 17:36:23 DEBUG ==> autoloaded builder LandoLagoonPhp
lando 17:36:23 DEBUG ==> autoloaded builder LandoLagoonPostgres
lando 17:36:23 DEBUG ==> autoloaded builder LandoLagoonRedis
lando 17:36:23 DEBUG ==> autoloaded builder LandoLagoonSolr
lando 17:36:23 DEBUG ==> autoloaded builder LandoLagoonVarnish
lando 17:36:23 DEBUG ==> autoloaded builder LandoMailHog
lando 17:36:23 DEBUG ==> autoloaded builder LandoMariaDb
lando 17:36:23 DEBUG ==> autoloaded builder LandoMemcached
lando 17:36:23 DEBUG ==> autoloaded builder LandoMongoDb
lando 17:36:23 DEBUG ==> autoloaded builder LandoMsSql
lando 17:36:23 DEBUG ==> autoloaded builder LandoMySql
lando 17:36:23 DEBUG ==> autoloaded builder LandoNginx
lando 17:36:23 DEBUG ==> autoloaded builder LandoNode
lando 17:36:23 DEBUG ==> autoloaded builder PantheonMariaDb
lando 17:36:23 DEBUG ==> autoloaded builder LandoPhp
lando 17:36:23 DEBUG ==> autoloaded builder LandoPma
lando 17:36:23 DEBUG ==> autoloaded builder LandoPlatformshChromeHeadless
lando 17:36:23 DEBUG ==> autoloaded builder LandoPlatformsElasticsearch
lando 17:36:23 DEBUG ==> autoloaded builder LandoPlatformshInfluxdb
lando 17:36:23 DEBUG ==> autoloaded builder LandoPlatformshKafka
lando 17:36:23 DEBUG ==> autoloaded builder LandoPlatformshMariaDB
lando 17:36:23 DEBUG ==> autoloaded builder LandoPlatformshMemcached
lando 17:36:23 DEBUG ==> autoloaded builder LandoPlatformsMongoDB
lando 17:36:23 DEBUG ==> autoloaded builder LandoPlatformshMySQL
lando 17:36:23 DEBUG ==> autoloaded builder LandoPlatformshPhp
lando 17:36:23 DEBUG ==> autoloaded builder LandoPlatformshPostgres
lando 17:36:23 DEBUG ==> autoloaded builder LandoPlatformshRabbitmq
lando 17:36:23 DEBUG ==> autoloaded builder LandoPlatformshRedis
lando 17:36:23 DEBUG ==> autoloaded builder LandoPlatformshSolr
lando 17:36:23 DEBUG ==> autoloaded builder LandoPlatformshVarnish
lando 17:36:23 DEBUG ==> autoloaded builder LandoPostgres
lando 17:36:23 DEBUG ==> autoloaded builder LandoPython
lando 17:36:23 DEBUG ==> autoloaded builder LandoRedis
lando 17:36:23 DEBUG ==> autoloaded builder LandoRuby
lando 17:36:23 DEBUG ==> autoloaded builder LandoSolr
lando 17:36:23 DEBUG ==> autoloaded builder LandoTomcat
lando 17:36:23 DEBUG ==> autoloaded builder LandoVarnish
lando 17:36:23 DEBUG ==> autoloaded builder LandoAcquia
lando 17:36:23 DEBUG ==> autoloaded builder LandoBackdrop
lando 17:36:23 DEBUG ==> autoloaded builder LandoDrupal10
lando 17:36:23 DEBUG ==> autoloaded builder LandoDrupal6
lando 17:36:23 DEBUG ==> autoloaded builder LandoDrupal7
lando 17:36:23 DEBUG ==> autoloaded builder LandoDrupal8
lando 17:36:23 DEBUG ==> autoloaded builder LandoDrupal9
lando 17:36:23 DEBUG ==> autoloaded builder LandoJoomla
lando 17:36:23 DEBUG ==> autoloaded builder LandoLagoon
lando 17:36:23 DEBUG ==> autoloaded builder LandoLamp
lando 17:36:23 DEBUG ==> autoloaded builder LandoLaravel
lando 17:36:23 DEBUG ==> autoloaded builder LandoLamp
lando 17:36:23 DEBUG ==> autoloaded builder LandoMean
lando 17:36:23 DEBUG ==> autoloaded builder LandoPantheon
lando 17:36:23 DEBUG ==> autoloaded builder LandoPlatformsh
lando 17:36:23 DEBUG ==> autoloaded builder LandoSymfony
lando 17:36:23 DEBUG ==> autoloaded builder LandoWordPress
lando 17:36:23 DEBUG ==> emitting event post-bootstrap-app
lando 17:36:23 VERBOSE ==> app bootstrap completed.
lando 17:36:23 VERBOSE ==> bootstrap completed.
lando 17:36:23 DEBUG ==> emitting event post-bootstrap
lando 17:36:23 VERBOSE ==> docker-engine exists: true
lando 17:36:23 VERBOSE ==> docker-compose exists: true
lando 17:36:23 DEBUG ==> emitting event cli-answers
lando 17:36:23 DEBUG ==> emitting event cli-start-answers
lando 17:36:23 DEBUG ==> emitting event cli-run
lando 17:36:23 DEBUG ==> emitting event cli-start-run
lando 17:36:23 INFO ==> loading app view-builder from config files 0=/Users/ktk/workspace/ssz/ssz-view-builder/.lando.yml
lando 17:36:23 DEBUG ==> app view-builder has config name=view-builder, env_file=[.env.local, .env], type=node:custom, build=[npm i -g nodemon], command=nodemon -w packages -w apps -i apps/www --ext ts,js,ttl --exec npm --node-options --inspect=0.0.0.0:32272 --inspect start, ssl=true, image=node:16, ports=[32272:32272], TS_NODE_TRANSPILE_ONLY=true, DEBUG=view-builder*,hydra*,hydra-box*,labyrinth*,SPARQL,-labyrinth:request:headers, scanner=false, moreHttpPorts=[32272], type=node, command=yarn wsrun -p @view-builder/app -c start --disable-host-check --host 0.0.0.0, ssl=true, scanner=false, port=8080, type=compose, stardog-home=null, build_as_root=[adduser www-data], run=[/opt/stardog/bin/stardog-admin db create -o preserve.bnode.ids=false query.describe.strategy=cbd -n view-builder || true, /opt/stardog/bin/stardog-admin db create -o preserve.bnode.ids=false -n published || true], image=stardog/stardog:8.1.0-java11-preview, command=/opt/stardog/bin/stardog-admin server start --foreground, LANDO_NO_USER_PERMS=NOTGONNADOIT, STARDOG_PROPERTIES=/app/.stardog/stardog.properties, volumes=[~/stardog-home/stardog-license-key.bin:/var/opt/stardog/stardog-license-key.bin], type=compose, app_mount=false, ssl=true, image=zazuko/trifid, command=tini -- /start.sh, user=root, DEBUG=trifid*, volumes=[./apps/trifid/start.sh:/start.sh], type=node, command=yarn wsrun -p @view-builder/explorer -c start --disable-host-check --host 0.0.0.0, scanner=false, type=compose, scanner=false, image=j4yf7o/restcli-node, command=tail -f /dev/null, service=store, cmd=/opt/stardog/bin/stardog-admin, service=store, cmd=/opt/stardog/bin/stardog, service=rest-cli, cmd=rest-cli -d test/api -e dev, store=[db.view-builder.lndo.site:5820], apis=[view-builder.lndo.site:8888], trifid=[trifid.view-builder.lndo.site:8080], ontodia=[explore.view-builder.lndo.site:8080], www=[view-builder.lndo.site:8080/app]
Let's get this party started! Starting app view-builder...
view-builder 17:36:23 INFO ==> starting app...
view-builder 17:36:23 VERBOSE ==> initiatilizing app at /Users/ktk/workspace/ssz/ssz-view-builder...
lando        17:36:23 DEBUG ==> plugin lando-core loaded from /snapshot/cli/plugins/lando-core/app.js
lando        17:36:23 DEBUG ==> plugin lando-events loaded from /snapshot/cli/plugins/lando-events/app.js
lando        17:36:23 DEBUG ==> plugin lando-networking loaded from /snapshot/cli/plugins/lando-networking/app.js
view-builder 17:36:23 VERBOSE ==> proxy settings detected.
lando        17:36:23 DEBUG ==> plugin lando-proxy loaded from /snapshot/cli/plugins/lando-proxy/app.js
lando        17:36:23 DEBUG ==> plugin lando-recipes loaded from /snapshot/cli/plugins/lando-recipes/app.js
lando        17:36:23 DEBUG ==> plugin lando-services loaded from /snapshot/cli/plugins/lando-services/app.js
lando        17:36:23 DEBUG ==> plugin lando-sharing loaded from /snapshot/cli/plugins/lando-sharing/app.js
lando        17:36:23 DEBUG ==> plugin lando-tooling loaded from /snapshot/cli/plugins/lando-tooling/app.js
lando        17:36:23 DEBUG ==> plugin @lando/acquia loaded from /snapshot/cli/node_modules/@lando/acquia/app.js
lando        17:36:23 DEBUG ==> plugin @lando/lagoon loaded from /snapshot/cli/node_modules/@lando/lagoon/app.js
lando        17:36:23 DEBUG ==> plugin @lando/pantheon loaded from /snapshot/cli/node_modules/@lando/pantheon/app.js
lando        17:36:23 DEBUG ==> plugin @lando/platformsh loaded from /snapshot/cli/node_modules/@lando/platformsh/app.js
view-builder 17:36:23 DEBUG ==> emitting event pre-init
lando        17:36:23 VERBOSE ==> proxy is ON.
lando        17:36:23 VERBOSE ==> Setting the default proxy certificate /certs/cert.crt
view-builder 17:36:23 VERBOSE ==> building node service apis
view-builder 17:36:23 VERBOSE ==> building node service www
view-builder 17:36:23 VERBOSE ==> building compose service store
view-builder 17:36:23 VERBOSE ==> building compose service trifid
view-builder 17:36:23 VERBOSE ==> building node service ontodia
view-builder 17:36:23 VERBOSE ==> building compose service rest-cli
view-builder 17:36:23 DEBUG ==> emitting event post-init
view-builder 17:36:23 DEBUG ==> adding hostnames to the app...
view-builder 17:36:23 DEBUG ==> hostnames added to apis 0=apis.viewbuilder.internal
view-builder 17:36:23 DEBUG ==> hostnames added to www 0=www.viewbuilder.internal
view-builder 17:36:23 DEBUG ==> hostnames added to store 0=store.viewbuilder.internal
view-builder 17:36:23 DEBUG ==> hostnames added to trifid 0=trifid.viewbuilder.internal
view-builder 17:36:23 DEBUG ==> hostnames added to ontodia 0=ontodia.viewbuilder.internal
view-builder 17:36:23 DEBUG ==> hostnames added to rest-cli 0=rest-cli.viewbuilder.internal
view-builder 17:36:23 VERBOSE ==> attempting to find open services...
lando        17:36:23 ERROR ==> TypeError: Cannot read property 'split' of null
    at clean (/snapshot/cli/lib/engine.js)
    at /snapshot/cli/lib/engine.js
    at /snapshot/cli/node_modules/lodash/lodash.js:3585:27
    at /snapshot/cli/node_modules/lodash/lodash.js:4967:15
    at baseForOwn (/snapshot/cli/node_modules/lodash/lodash.js:3032:24)
    at /snapshot/cli/node_modules/lodash/lodash.js:4936:18
    at baseMap (/snapshot/cli/node_modules/lodash/lodash.js:3584:7)
    at Function.map (/snapshot/cli/node_modules/lodash/lodash.js:9622:14)
    at interceptor (/snapshot/cli/node_modules/lodash/lodash.js:17094:35)
    at Function.thru (/snapshot/cli/node_modules/lodash/lodash.js:8859:14)
    at /snapshot/cli/node_modules/lodash/lodash.js:4430:28
    at arrayReduce (/snapshot/cli/node_modules/lodash/lodash.js:697:21)
    at baseWrapperValue (/snapshot/cli/node_modules/lodash/lodash.js:4429:14)
    at LodashWrapper.wrapperValue (/snapshot/cli/node_modules/lodash/lodash.js:9114:14)
    at /snapshot/cli/lib/engine.js
From previous event:
    at Engine.getCompatibility (/snapshot/cli/lib/engine.js)
    at /snapshot/cli/lib/cli.js
From previous event:
    at /snapshot/cli/lib/cli.js
From previous event:
    at Object.handler (/snapshot/cli/lib/cli.js)
    at Object.runCommand (/snapshot/cli/node_modules/yargs/lib/command.js:238:44)
    at Object.parseArgs [as _parseArgs] (/snapshot/cli/node_modules/yargs/yargs.js:1063:30)
    at Function.get [as argv] (/snapshot/cli/node_modules/yargs/yargs.js:1004:21)
    at Cli.init (/snapshot/cli/lib/cli.js)
    at Cli.run (/snapshot/cli/lib/cli.js)
    at Object.<anonymous> (/snapshot/cli/bin/lando.js)
    at Module._compile (pkg/prelude/bootstrap.js:1887:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Function.runMain (pkg/prelude/bootstrap.js:1940:12)
    at internal/main/run_main_module.js:17:47
```

**Comment by tpluscode** [comment]
This is using lando `v3.6.5` (and happened before too) and docker `v20.10.17`

**Comment by tpluscode** [comment]
@pirog any ideas? pretty please

**Comment by todeveni** [comment]
My guess they're running Docker using [colima](https://github.com/abiosoft/colima) (or similar), not Docker desktop.
I stumbled to this bug report since I'm having same exact issue trying to start Lando-project with colima.
Latest version of Docker desktop broke Lando on macOS too, since they removed `/var/run/docker.sock` on Docker desktop 4.13.0.

> By default Docker will not create the /var/run/docker.sock symlink on the host and use the docker-desktop CLI context instead.
https://docs.docker.com/desktop/release-notes/#docker-desktop-4130

**Comment by reynoldsalec** [comment]
@todeveni looks like other projects gave Docker grief for removing the symlink, so as of Docker Desktop 4.14 it's back: https://docs.docker.com/desktop/release-notes/#docker-desktop-4140...so if you get the error `ERROR ==> connect ENOENT /var/run/docker.sock`, make sure you're running Docker Desktop 4.14 or above (or below 4.13 for that matter).

@tpluscode that error almost looks like what happens when there's an error in the Landofile, but it sounds like you're able to run the same project without issues?

**Comment by ktk** [comment]
It was my system, I'm running Docker Desktop on my MacBook Pro (Intel). It's happening in two different projects that work perfectly fine for @tpluscode.

I'm currently on Docker Desktop Version 4.14.1 (91661).

If I can provide logs or anything alike let me know.

**Comment by hardyoyo** [comment]
BTW, we've seen a similar issue when running Orbstack instead of Docker Desktop.

**Comment by heikokrebs** [comment]
@hardyoyo do you have any fix for that?

**Comment by hardyoyo** [comment]
I think the "fix" is mentioned above... I deleted Orbstack, reinstalled Docker, then put in a symlink for the Docker socket.

**Comment by dh-sesame** [comment]
Using Colima latest released version installed via homebrew on Ventura (then Sonoma), along with various releases of Lando, I would repeatedly receive variations of this error when using Colima since around March of 2023 (not exact date possibly incorrect). Orbstack seemed to work out of the box, but preferring open source solution I returned to Colima this week. The below assumes `docker context use colima` is set. 

Two changes that seemed to improve lando with Colima on MacOS included:

1) altering ~/.docker/config.json to remove the "credsStore":"desktop" line (via https://github.com/abiosoft/colima/issues/52#issuecomment-956037291 ) which resolved a "exec: "docker-credential-desktop.exe": executable file not found in $PATH" error

2) Running lando from source via this guide https://docs.lando.dev/getting-started/installation.html#from-source
and commented out the "getCompatibility()" check. If I did this I could at least have a working environment using Colima on MacOS. Commenting out these lines below from the cli project ( linked here for context https://github.com/lando/cli/blob/9e618a2586079dc6b1f1fb807f398c64ca28f155/lib/cli.js#L373
lib/cli.js ) has at least allowed me to work again with Colima. I wanted to investigate where lando.engine.getCompatibility() was pulling from but haven't had time to retrace.

Sharing in the event helpful even if inconclusive and possibly leading to other issues. 

```
// Collect DOCKER VERSION COMPAT info, this can be an async check
// lando.engine.getCompatibility().then(results => {
//   lando.log.verbose('checking docker version compatibility...');
//   lando.log.debug('compatibility results', _.keyBy(results, 'name'));
//   lando.cache.set('versions', _.assign(lando.versions, _.keyBy(results, 'name')), {persist: true});
//   lando.versions = lando.cache.get('versions');
// });
```
