### ISSUE TITLE
No Such Host 

### ISSUE THREAD

**Issue by labboy0276** [lando/lando#354]
Bug Report
==========

**Tell us about your setup**

beta-17, ubuntu 16.04

**Tell us about the command you were running**

```bash
lando rebuild
lando start
```

**Tell us about the error you got**

```bash
john@kalamuna:~/lando/sfrcna$ lando rebuild
? Are you sure you want to rebuild? Yes
Pulling appserver (devwithlando/php:7.0-apache)...
ERROR: Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on 127.0.1.1:53: no such host
Pulling appserver (devwithlando/php:7.0-apache)...
ERROR: Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on 127.0.1.1:53: no such host
Pulling appserver (devwithlando/php:7.0-apache)...
ERROR: Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on 127.0.1.1:53: no such host
Pulling appserver (devwithlando/php:7.0-apache)...
ERROR: Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on 127.0.1.1:53: no such host
Pulling appserver (devwithlando/php:7.0-apache)...
ERROR: Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on 127.0.1.1:53: no such host
error:  Error: Error: 1
    at /snapshot/cli/lib/promise.js:56:17
    at runCallback (timers.js:800:20)
    at tryOnImmediate (timers.js:762:5)
    at processImmediate [as _immediateCallback] (timers.js:733:5)
From previous event:
    at rec (/snapshot/cli/lib/promise.js:42:13)
    at /snapshot/cli/lib/promise.js:50:20
    at ontimeout (timers.js:488:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:283:5)
From previous event:
    at /snapshot/cli/lib/promise.js:49:12
    at runCallback (timers.js:800:20)
    at tryOnImmediate (timers.js:762:5)
    at processImmediate [as _immediateCallback] (timers.js:733:5)

```

**Tell us generally about your bug**

I've had my laptop on for awhile and this happens, see the comments for the solution,  I am just putting this here in case anyone runs into this in the future.

**Comment by labboy0276** [comment]
To fix this run the following:

```bash
sudo service docker stop
lando poweroff
```

then start up your app normally and all will be well hopefully

**Comment by pirog** [comment]
@labboy0276 this is super helpful. When you have a sec maybe you can add it to the "known issues" section of our documentation?

**Comment by pirog** [comment]
@labboy0276 lets talk about how best to address this
