### ISSUE TITLE
YAML error: null byte is not allowed in input

### ISSUE THREAD

**Issue by iKlsR** [lando/lando#3585]
I've been on 3.18.0 for a couple weeks now, no issues, used up to yesterday and this morning any `lando` command I type I get the following... I also don't have a snapshot folder etc.

```bash
user@machineMINGW64 ~
$ lando version

C:\snapshot\cli\node_modules\js-yaml\lib\js-yaml\loader.js:167
  return new YAMLException(
         ^
YAMLException: null byte is not allowed in input at line 1, column 1:

    ^
    at generateError (C:\snapshot\cli\node_modules\js-yaml\lib\js-yaml\loader.js:167:10)
    at throwError (C:\snapshot\cli\node_modules\js-yaml\lib\js-yaml\loader.js:173:9)
    at loadDocuments (C:\snapshot\cli\node_modules\js-yaml\lib\js-yaml\loader.js:1576:5)
    at Object.load (C:\snapshot\cli\node_modules\js-yaml\lib\js-yaml\loader.js:1614:19)
    at C:\snapshot\cli\node_modules\@lando\core-next\utils\read-file.js
    at Object.loadFile (C:\snapshot\cli\lib\rts.js)
    at Object.<anonymous> (C:\snapshot\cli\bin\lando.js)
    at Module._compile (pkg/prelude/bootstrap.js:1930:22)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32) {
  reason: 'null byte is not allowed in input',
  mark: Mark {
    name: null,
    buffer: '\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\n',
    position: 0,
    line: 0,
    column: 0
  }
}```

**Comment by iKlsR** [comment]
Reinstalling, registry clean, restarting etc doesn't fix, downgraded to `3.17.1` and getting the same. Seems to be some change that triggered this on my system, not sure where to look.

```bash
user@machineMINGW64 ~
$ lando version

pkg/prelude/bootstrap.js:1930
      return wrapper.apply(this.exports, args);
                     ^
YAMLException: null byte is not allowed in input (1:1)

 1 |
-----^
 2 |
 3 |
    at generateError (C:\snapshot\cli\node_modules\@lando\core-next\node_modules\js-yaml\lib\loader.js)
    at throwError (C:\snapshot\cli\node_modules\@lando\core-next\node_modules\js-yaml\lib\loader.js)
    at loadDocuments (C:\snapshot\cli\node_modules\@lando\core-next\node_modules\js-yaml\lib\loader.js)
    at Object.load (C:\snapshot\cli\node_modules\@lando\core-next\node_modules\js-yaml\lib\loader.js)
    at C:\snapshot\cli\node_modules\@lando\core-next\utils\read-file.js
    at Object.loadFile (C:\snapshot\cli\lib\rts.js)
    at Object.<anonymous> (C:\snapshot\cli\bin\lando.js)
    at Module._compile (pkg/prelude/bootstrap.js:1930:22)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32) {
  reason: 'null byte is not allowed in input',
  mark: {
    name: null,
    buffer: '\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00',
    position: 0,
    line: 0,
    column: 0,
    snippet: ' 1 | \n-----^\n 2 | \n 3 | '
  }
}```

**Comment by iKlsR** [comment]
Very peculiar issue, not sure what happened but I figured it was trying to read a file and then remembered I didn't check the `.lando` folder, deleted the entire thing and had it recreate it, back to normal.

**Comment by jiangying000** [comment]
> Very peculiar issue, not sure what happened but I figured it was trying to read a file and then remembered I didn't check the `.lando` folder, deleted the entire thing and had it recreate it, back to normal.
> 
> Tracing my steps back to what could have changed yesterday is that I initiated a full malwarebytes scan on my pc, again very odd, when I tried to open the file before deleting the folder it had some null garbage inside (can't even copy it).
> 
> <img alt="nl" width="215" src="https://private-user-images.githubusercontent.com/741363/247633331-c4808f19-5938-4bb0-8622-476e263edba3.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ2MTE2ODEsIm5iZiI6MTcxNDYxMTM4MSwicGF0aCI6Ii83NDEzNjMvMjQ3NjMzMzMxLWM0ODA4ZjE5LTU5MzgtNGJiMC04NjIyLTQ3NmUyNjNlZGJhMy5QTkc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwMlQwMDU2MjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xODRlNmYzNzhkZDM3YTlhMDgwMjA0MDk0MWVkYjEwMzk5YmYxMGNhNTE2NjI3NzEwMWIzNDFhNTMxMDMzNzIxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.m1bqb4J3PUoI_RKKf4MZ_PweDBYZBbDZqULSPzdxLfQ">

hello, which editor did you use to make those NULNUL... visible

**Comment by jiangying000** [comment]
I got those error:

```
Parsing environment...
Error: null byte is not allowed in input (1:4)

 1 | ��n
--------^
 2 | a
 3 | m
```


turns out i was using utf16le when encoding environment.yml, convert that file to utf-8 resolve this issue

**Comment by iKlsR** [comment]
> > Very peculiar issue, not sure what happened but I figured it was trying to read a file and then remembered I didn't check the `.lando` folder, deleted the entire thing and had it recreate it, back to normal.
> > Tracing my steps back to what could have changed yesterday is that I initiated a full malwarebytes scan on my pc, again very odd, when I tried to open the file before deleting the folder it had some null garbage inside (can't even copy it).
> > <img alt="nl" width="215" src="https://private-user-images.githubusercontent.com/741363/247633331-c4808f19-5938-4bb0-8622-476e263edba3.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ2MTE2ODEsIm5iZiI6MTcxNDYxMTM4MSwicGF0aCI6Ii83NDEzNjMvMjQ3NjMzMzMxLWM0ODA4ZjE5LTU5MzgtNGJiMC04NjIyLTQ3NmUyNjNlZGJhMy5QTkc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwMlQwMDU2MjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xODRlNmYzNzhkZDM3YTlhMDgwMjA0MDk0MWVkYjEwMzk5YmYxMGNhNTE2NjI3NzEwMWIzNDFhNTMxMDMzNzIxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.m1bqb4J3PUoI_RKKf4MZ_PweDBYZBbDZqULSPzdxLfQ">
> 
> hello, which editor did you use to make those NULNUL... visible

Any code editor should work that's not just a plaintext editor, I used vs code
