### ISSUE TITLE
Cannot read properties of null (reading 'com.docker.compose.project') 

### ISSUE THREAD

**Issue by mdphoto** [lando/lando#3591]
Hi,
This morning, Lando doesn't start.
Linux Arch
Docker version 24.0.2
Docker Compose version 2.20.0
Lando 3.18.0

Then I try to run my project or I try to create a new lando init with lamp recipe in empty folder and lando start.
I always the same error.

`ERROR ==> Cannot read properties of null (reading 'com.docker.compose.project') message=Cannot read properties of null (reading 'com.docker.compose.project'), stack=TypeError: Cannot read properties of null (reading 'com.docker.compose.project')
    at Object.toLandoContainer (/snapshot/cli/node_modules/@lando/core/lib/utils.js)
    at /snapshot/cli/node_modules/@lando/core/lib/docker.js
From previous event:
    at Landerode.list (/snapshot/cli/node_modules/@lando/core/lib/docker.js)
    at /snapshot/cli/node_modules/@lando/core/lib/engine.js
    at /snapshot/cli/node_modules/@lando/core/lib/router.js
    at processImmediate (node:internal/timers:466:21)
From previous event:
    at Object.eventWrapper (/snapshot/cli/node_modules/@lando/core/lib/router.js)
    at Engine.engineCmd (/snapshot/cli/node_modules/@lando/core/lib/engine.js)
    at Engine.list (/snapshot/cli/node_modules/@lando/core/lib/engine.js)
    at AsyncEvents.<anonymous> (/snapshot/cli/node_modules/@lando/core/plugins/lando-core/app.js)
    at AsyncEvents.handle (/snapshot/cli/node_modules/@lando/core/lib/events.js)
    at /snapshot/cli/node_modules/@lando/core/lib/events.js
From previous event:
    at AsyncEvents.emit (/snapshot/cli/node_modules/@lando/core/lib/events.js)
    at /snapshot/cli/node_modules/@lando/core/lib/app.js
From previous event:
    at App.start (/snapshot/cli/node_modules/@lando/core/lib/app.js)
    at Object.run (/snapshot/cli/node_modules/@lando/core/plugins/lando-core/tasks/start.js)
From previous event:
    at /snapshot/cli/lib/cli.js
From previous event:
    at Object.handler (/snapshot/cli/lib/cli.js)
    at Object.runCommand (/snapshot/cli/node_modules/yargs/lib/command.js:238:44)
    at Object.parseArgs [as _parseArgs] (/snapshot/cli/node_modules/yargs/yargs.js:1063:30)
    at Function.get [as argv] (/snapshot/cli/node_modules/yargs/yargs.js:1004:21)
    at Cli.init (/snapshot/cli/lib/cli.js)
    at Cli.run (/snapshot/cli/lib/cli.js)
From previous event:
    at /snapshot/cli/bin/lando.js
    at processImmediate (node:internal/timers:466:21)
From previous event:
    at Object.<anonymous> (/snapshot/cli/bin/lando.js)
    at Module._compile (pkg/prelude/bootstrap.js:1930:22)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.runMain (pkg/prelude/bootstrap.js:1983:12)
    at node:internal/main/run_main_module:17:47, __stackCleaned__=true
`

Cannot read properties of null (reading 'com.docker.compose.project') 

I remove Lando, Docker, Docker-compose and install but same result.

**Comment by mdphoto** [comment]
I fix with 
lando poweroff && docker system prune -a --volumes && rm -rf ~/.lando/cache
