### ISSUE TITLE
With mac M2

### ISSUE THREAD

**Issue by kamalkech** [lando/lando#3609]
- System:  Apple m2 Ventura 13.6
- Docker: 24.0.6, build ed223bc
- Lando: v3.18.0

```yml
name: my-project
recipe: drupal9
config:
  webroot: web
  via: nginx
  php: 8.1
```

after lando start, i get this warning
```
WARN[0000] network lando_proxyedge: network.external.name is deprecated. Please set network.name with external: true 
```

then this error:
```
ERROR ==> database reported as unhealthy. 
ERROR ==> Error: (HTTP code 404) no such container - No such container: landoproxyhyperion5000gandalfedition_proxy_1  message=Error: (HTTP code 404) no such container - No such container: landoproxyhyperion5000gandalfedition_proxy_1 , stack=Error: Error: (HTTP code 404) no such container - No such container: landoproxyhyperion5000gandalfedition_proxy_1 
    at /snapshot/cli/node_modules/@lando/core/lib/docker.js
From previous event:
    at containerOpt (/snapshot/cli/node_modules/@lando/core/lib/docker.js)
    at Landerode.scan (/snapshot/cli/node_modules/@lando/core/lib/docker.js)
    at Object.scan (/snapshot/cli/node_modules/@lando/core/lib/router.js)
    at run (/snapshot/cli/node_modules/@lando/core/lib/engine.js)
    at /snapshot/cli/node_modules/@lando/core/lib/router.js
    at processImmediate (node:internal/timers:466:21)
From previous event:
    at Object.eventWrapper (/snapshot/cli/node_modules/@lando/core/lib/router.js)
    at Engine.engineCmd (/snapshot/cli/node_modules/@lando/core/lib/engine.js)
    at Engine.scan (/snapshot/cli/node_modules/@lando/core/lib/engine.js)
    at /snapshot/cli/node_modules/@lando/core/plugins/lando-networking/app.js
From previous event:
    at AsyncEvents.<anonymous> (/snapshot/cli/node_modules/@lando/core/plugins/lando-networking/app.js)
    at AsyncEvents.handle (/snapshot/cli/node_modules/@lando/core/lib/events.js)
    at /snapshot/cli/node_modules/@lando/core/lib/events.js
    at processImmediate (node:internal/timers:466:21)
From previous event:
    at AsyncEvents.emit (/snapshot/cli/node_modules/@lando/core/lib/events.js)
    at /snapshot/cli/node_modules/@lando/core/lib/app.js
From previous event:
    at App.start (/snapshot/cli/node_modules/@lando/core/lib/app.js)
    at Object.run (/snapshot/cli/node_modules/@lando/core/plugins/lando-core/tasks/start.js)
From previous event:
    at /snapshot/cli/lib/cli.js
    at processImmediate (node:internal/timers:466:21)
From previous event:
    at Object.handler (/snapshot/cli/lib/cli.js)
    at Object.runCommand (/snapshot/cli/node_modules/yargs/lib/command.js:238:44)
    at Object.parseArgs [as _parseArgs] (/snapshot/cli/node_modules/yargs/yargs.js:1063:30)
    at Function.get [as argv] (/snapshot/cli/node_modules/yargs/yargs.js:1004:21)
    at Cli.init (/snapshot/cli/lib/cli.js)
    at Cli.run (/snapshot/cli/lib/cli.js)
    at Object.<anonymous> (/snapshot/cli/bin/lando.js)
    at Module._compile (pkg/prelude/bootstrap.js:1930:22)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.runMain (pkg/prelude/bootstrap.js:1983:12)
    at node:internal/main/run_main_module:17:47, __stackCleaned__=true

██╗   ██╗██╗  ██╗     ██████╗ ██╗  ██╗██╗
██║   ██║██║  ██║    ██╔═══██╗██║  ██║██║
██║   ██║███████║    ██║   ██║███████║██║
██║   ██║██╔══██║    ██║   ██║██╔══██║╚═╝
╚██████╔╝██║  ██║    ╚██████╔╝██║  ██║██╗
 ╚═════╝ ╚═╝  ╚═╝     ╚═════╝ ╚═╝  ╚═╝╚═╝
                                         

An error occurred while starting up your app!
Here are a few things you can try to get back into a good state:

  ■ Try running lando rebuild
  ■ Try restarting in debug mode lando restart -vvv
  ■ Try checking the logs with lando logs

If those fail then consult the troubleshooting materials:

  ■ https://docs.lando.dev/help/logs.html
  ■ https://docs.lando.dev/help/updating.html

Or post your issue to Slack or GitHub

  ■ Slack - https://launchpass.com/devwithlando
  ■ GitHub - https://github.com/lando/lando/issues/new/choose

ERROR ==> Error: (HTTP code 404) no such container - No such container: landoproxyhyperion5000gandalfedition_proxy_1 
```

**Comment by mcroyle** [comment]
I experienced this on the M1 Max after updating to the latest version of Docker (4.23.0). I reinstalled Docker 4.22.1 and the error went away.

**Comment by nilsringersma** [comment]
Can confirm, our employees are also experiencing issues on 4.23. Downgrading to 4.22 seems to fix it, or swapping to MariaDB and rebuilding works too. For what's it worth, this also occurs on the intel chips.

**Comment by reynoldsalec** [comment]
This issue is probably due to Docker Desktop eliminating Docker Compose V1 support.

[Lando 3.20.1](https://github.com/lando/lando/releases/tag/v3.20.1) should fix this issue by introducing Docker Compose V2 support.

Going to close this out, feel free to re-open if any of the posters have issues with Docker Desktop 4.23 after upgrading to Lando 3.20.1.

**Comment by kamalkech** [comment]
@reynoldsalec ok thank you for share informations.
