### ISSUE TITLE
Error after update to 3.20.2: unknown flag: --project-name

### ISSUE THREAD

**Issue by oskarmodig** [lando/lando#3620]
After updating to 3.20.2 all lando commands fail with the error  `unknown flag: --project-name`.
First it tries downloads docker-compose on every command. I thought it succeeded (it got to 100%), but checking the verbose output , I can see that it failed:
`could not download docker-compose v2.21.0: Cannot read properties of null (reading 'toString') `

As you can see, that last thing it outputs before failing is:
`DEBUG ==> process pid3 running C:\Program Files\Docker\Docker\resources\bin\docker-compose.exe kill cstdio=inherit, silent=false, mode=spawn, detached=false`

```
  lando.js starting 'lando.js' version '3.20.2' runtime selector... +0ms
  lando.js merged in additional config source from file 'C:\\snapshot\\cli\\config.yml' +27ms
  lando.js merged in additional config source from file 'C:\\Users\\OskarModig\\.lando\\config.yml' +2ms
  lando.js merged in additional config source from 'LANDO_*' envvars with data { installPath: 'C:\\Program Files\\Lando' } +4ms
  lando.js final assembled minconf is {
  lando.js   configSources: [
  lando.js     'C:\\snapshot\\cli\\config.yml',
  lando.js     'C:\\Users\\OskarModig\\.lando\\config.yml'
  lando.js   ],
  lando.js   envPrefix: 'LANDO',
  lando.js   landoFile: '.lando.yml',
  lando.js   preLandoFiles: [
  lando.js     '.lando.base.yml',
  lando.js     '.lando.dist.yml',
  lando.js     '.lando.recipe.yml',
  lando.js     '.lando.upstream.yml'
  lando.js   ],
  lando.js   postLandoFiles: [ '.lando.local.yml', '.lando.user.yml' ],
  lando.js   runtime: 3,
  lando.js   srcRoot: 'C:\\snapshot\\cli',
  lando.js   userConfRoot: 'C:\\Users\\OskarModig\\.lando',
  lando.js   product: 'lando',
  lando.js   hyperdrive: 'hyperdrive',
  lando.js   channel: 'stable',
  lando.js   domain: 'lndo.site',
  lando.js   mode: 'cli',
  lando.js   stats: [ { report: true, url: 'https://metrics.lando.dev' } ],
  lando.js   installPath: 'C:\\Program Files\\Lando'
  lando.js } +1ms
  lando.js detected an app 'woo-sync' at 'C:\\Users\\OskarModig\\windows-git\\flo-sync\\woocommerce-sync' +12ms
  lando.js using '@lando/core' runtime version 3 +0ms
  lando.js starting lando with 'v3' runtime using cli { ENVPREFIX: undefined, LOGLEVELCONSOLE: 4, USERCONFROOT: undefined, COREBASE: '@lando/core' } +31ms
lando 13:46:39 DEBUG ==> No update available. 
lando 13:46:39 VERBOSE ==> starting bootstrap at level app...
lando 13:46:39 VERBOSE ==> config bootstrap beginning...
lando 13:46:39 DEBUG ==> emitting event pre-bootstrap-config
lando 13:46:39 DEBUG ==> plugin lando-core loaded from C:/snapshot/cli/node_modules/@lando/core/plugins/lando-core/index.js 
lando 13:46:39 DEBUG ==> plugin lando-events loaded from C:/snapshot/cli/node_modules/@lando/core/plugins/lando-events/index.js
lando 13:46:39 DEBUG ==> plugin lando-healthcheck loaded from C:/snapshot/cli/node_modules/@lando/core/plugins/lando-healthcheck/index.js
lando 13:46:39 DEBUG ==> plugin lando-networking loaded from C:/snapshot/cli/node_modules/@lando/core/plugins/lando-networking/index.js
lando 13:46:39 DEBUG ==> plugin lando-proxy loaded from C:/snapshot/cli/node_modules/@lando/core/plugins/lando-proxy/index.js
lando 13:46:39 DEBUG ==> plugin lando-recipes loaded from C:/snapshot/cli/node_modules/@lando/core/plugins/lando-recipes/index.js
lando 13:46:39 DEBUG ==> plugin lando-scanner loaded from C:/snapshot/cli/node_modules/@lando/core/plugins/lando-scanner/index.js
lando 13:46:39 DEBUG ==> plugin lando-services-v4 loaded from C:/snapshot/cli/node_modules/@lando/core/plugins/lando-services-v4/index.js
lando 13:46:39 DEBUG ==> plugin lando-services loaded from C:/snapshot/cli/node_modules/@lando/core/plugins/lando-services/index.js
lando 13:46:39 DEBUG ==> plugin lando-sharing loaded from C:/snapshot/cli/node_modules/@lando/core/plugins/lando-sharing/index.js
lando 13:46:39 DEBUG ==> plugin lando-test loaded from C:/snapshot/cli/node_modules/@lando/core/plugins/lando-test/index.js
lando 13:46:39 DEBUG ==> plugin lando-tooling loaded from C:/snapshot/cli/node_modules/@lando/core/plugins/lando-tooling/index.js
lando 13:46:39 DEBUG ==> plugin @lando/acquia loaded from C:/snapshot/cli/node_modules/@lando/acquia/index.js
lando 13:46:39 DEBUG ==> plugin @lando/apache loaded from C:/snapshot/cli/node_modules/@lando/apache/index.js
lando 13:46:39 DEBUG ==> plugin @lando/backdrop loaded from C:/snapshot/cli/node_modules/@lando/backdrop/index.js
lando 13:46:39 DEBUG ==> plugin @lando/compose loaded from C:/snapshot/cli/node_modules/@lando/compose/index.js 
lando 13:46:39 DEBUG ==> plugin @lando/dotnet loaded from C:/snapshot/cli/node_modules/@lando/dotnet/index.js
lando 13:46:39 DEBUG ==> plugin @lando/drupal loaded from C:/snapshot/cli/node_modules/@lando/drupal/index.js
lando 13:46:39 DEBUG ==> plugin @lando/elasticsearch loaded from C:/snapshot/cli/node_modules/@lando/elasticsearch/index.js
lando 13:46:39 DEBUG ==> plugin @lando/go loaded from C:/snapshot/cli/node_modules/@lando/go/index.js
lando 13:46:39 DEBUG ==> plugin @lando/joomla loaded from C:/snapshot/cli/node_modules/@lando/joomla/index.js
lando 13:46:39 DEBUG ==> plugin @lando/lagoon loaded from C:/snapshot/cli/node_modules/@lando/lagoon/index.js
lando 13:46:39 DEBUG ==> plugin @lando/lamp loaded from C:/snapshot/cli/node_modules/@lando/lamp/index.js
lando 13:46:39 DEBUG ==> plugin @lando/laravel loaded from C:/snapshot/cli/node_modules/@lando/laravel/index.js
lando 13:46:39 DEBUG ==> plugin @lando/lemp loaded from C:/snapshot/cli/node_modules/@lando/lemp/index.js
lando 13:46:39 DEBUG ==> plugin @lando/mailhog loaded from C:/snapshot/cli/node_modules/@lando/mailhog/index.js 
lando 13:46:39 DEBUG ==> plugin @lando/mariadb loaded from C:/snapshot/cli/node_modules/@lando/mariadb/index.js
lando 13:46:39 DEBUG ==> plugin @lando/mean loaded from C:/snapshot/cli/node_modules/@lando/mean/index.js
lando 13:46:39 DEBUG ==> plugin @lando/memcached loaded from C:/snapshot/cli/node_modules/@lando/memcached/index.js
lando 13:46:39 DEBUG ==> plugin @lando/mongo loaded from C:/snapshot/cli/node_modules/@lando/mongo/index.js
lando 13:46:39 DEBUG ==> plugin @lando/mssql loaded from C:/snapshot/cli/node_modules/@lando/mssql/index.js
lando 13:46:39 DEBUG ==> plugin @lando/mysql loaded from C:/snapshot/cli/node_modules/@lando/mysql/index.js
lando 13:46:39 DEBUG ==> plugin @lando/nginx loaded from C:/snapshot/cli/node_modules/@lando/nginx/index.js
lando 13:46:39 DEBUG ==> plugin @lando/node loaded from C:/snapshot/cli/node_modules/@lando/node/index.js
lando 13:46:40 DEBUG ==> plugin @lando/pantheon loaded from C:/snapshot/cli/node_modules/@lando/pantheon/index.js 
lando 13:46:40 DEBUG ==> plugin @lando/php loaded from C:/snapshot/cli/node_modules/@lando/php/index.js
lando 13:46:40 DEBUG ==> plugin @lando/phpmyadmin loaded from C:/snapshot/cli/node_modules/@lando/phpmyadmin/index.js
lando 13:46:40 DEBUG ==> plugin @lando/platformsh loaded from C:/snapshot/cli/node_modules/@lando/platformsh/index.js 
lando 13:46:40 DEBUG ==> plugin @lando/postgres loaded from C:/snapshot/cli/node_modules/@lando/postgres/index.js
lando 13:46:40 DEBUG ==> plugin @lando/python loaded from C:/snapshot/cli/node_modules/@lando/python/index.js
lando 13:46:40 DEBUG ==> plugin @lando/redis loaded from C:/snapshot/cli/node_modules/@lando/redis/index.js
lando 13:46:40 DEBUG ==> plugin @lando/ruby loaded from C:/snapshot/cli/node_modules/@lando/ruby/index.js
lando 13:46:40 DEBUG ==> plugin @lando/solr loaded from C:/snapshot/cli/node_modules/@lando/solr/index.js
lando 13:46:40 DEBUG ==> plugin @lando/symfony loaded from C:/snapshot/cli/node_modules/@lando/symfony/index.js
lando 13:46:40 DEBUG ==> plugin @lando/tomcat loaded from C:/snapshot/cli/node_modules/@lando/tomcat/index.js
lando 13:46:40 DEBUG ==> plugin @lando/varnish loaded from C:/snapshot/cli/node_modules/@lando/varnish/index.js
lando 13:46:40 DEBUG ==> plugin @lando/wordpress loaded from C:/snapshot/cli/node_modules/@lando/wordpress/index.js
lando 13:46:40 DEBUG ==> emitting event post-bootstrap-config
lando 13:46:40 VERBOSE ==> building proxy config...
lando 13:46:40 VERBOSE ==> config bootstrap completed.
lando 13:46:40 VERBOSE ==> tasks bootstrap beginning...
lando 13:46:40 DEBUG ==> emitting event pre-bootstrap-tasks
lando 13:46:40 DEBUG ==> autoloaded task config 
lando 13:46:40 DEBUG ==> autoloaded task destroy
lando 13:46:40 DEBUG ==> autoloaded task info
lando 13:46:40 DEBUG ==> autoloaded task list
lando 13:46:40 DEBUG ==> autoloaded task logs
lando 13:46:40 DEBUG ==> autoloaded task poweroff
lando 13:46:40 DEBUG ==> autoloaded task rebuild
lando 13:46:40 DEBUG ==> autoloaded task restart
lando 13:46:40 DEBUG ==> autoloaded task share
lando 13:46:40 DEBUG ==> autoloaded task start
lando 13:46:40 DEBUG ==> autoloaded task stop
lando 13:46:40 DEBUG ==> autoloaded task version
lando 13:46:40 DEBUG ==> autoloaded task init
lando 13:46:40 DEBUG ==> autoloaded task ssh
lando 13:46:40 DEBUG ==> emitting event post-bootstrap-tasks
lando 13:46:40 VERBOSE ==> tasks bootstrap completed.
lando 13:46:40 VERBOSE ==> engine bootstrap beginning... 
lando 13:46:40 DEBUG ==> emitting event pre-bootstrap-engine
lando 13:46:40 DEBUG ==> could not detect docker-compose v2.21.0!
lando 13:46:40 DEBUG ==> downloading https://github.com/docker/compose/releases/download/v2.21.0/docker-compose-windows-x86_64.exe to C:\Users\OskarModig\.lando\bin\docker-compose-v2.21.0... 
lando 13:46:45 DEBUG ==> could not download docker-compose v2.21.0: Cannot read properties of null (reading 'toString') 
lando 13:46:45 DEBUG ==> docker-compose setup failed! will attempt to use a system-installed version of docker-compose.
lando 13:46:45 DEBUG ==> using docker-compose C:\Program Files\Docker\Docker\resources\bin\docker-compose.exe
lando 13:46:45 DEBUG ==> automoved scripts from C:\snapshot\cli\node_modules\@lando\core\plugins\lando-core\scripts to C:\Users\OskarModig\.lando\scripts and set to mode 755 
lando 13:46:45 DEBUG ==> automoved scripts from C:\snapshot\cli\node_modules\@lando\core\plugins\lando-proxy\scripts to C:\Users\OskarModig\.lando\scripts and set to mode 755
lando 13:46:45 DEBUG ==> automoved scripts from C:\snapshot\cli\node_modules\@lando\core\plugins\lando-recipes\scripts to C:\Users\OskarModig\.lando\scripts and set to mode 755 
lando 13:46:45 DEBUG ==> automoved scripts from C:\snapshot\cli\node_modules\@lando\core\plugins\lando-services\scripts to C:\Users\OskarModig\.lando\scripts and set to mode 755
lando 13:46:45 DEBUG ==> automoved scripts from C:\snapshot\cli\node_modules\@lando\core\plugins\lando-sharing\scripts to C:\Users\OskarModig\.lando\scripts and set to mode 755 
lando 13:46:45 DEBUG ==> automoved scripts from C:\snapshot\cli\node_modules\@lando\acquia\scripts to C:\Users\OskarModig\.lando\scripts and set to mode 755
lando 13:46:45 DEBUG ==> automoved scripts from C:\snapshot\cli\node_modules\@lando\lagoon\scripts to C:\Users\OskarModig\.lando\scripts and set to mode 755 
lando 13:46:45 DEBUG ==> automoved scripts from C:\snapshot\cli\node_modules\@lando\pantheon\scripts to C:\Users\OskarModig\.lando\scripts and set to mode 755 
lando 13:46:45 DEBUG ==> automoved scripts from C:\snapshot\cli\node_modules\@lando\platformsh\scripts to C:\Users\OskarModig\.lando\scripts and set to mode 755
lando 13:46:45 DEBUG ==> emitting event post-bootstrap-engine
lando 13:46:45 VERBOSE ==> engine bootstrap completed.
lando 13:46:45 VERBOSE ==> app bootstrap beginning...
lando 13:46:45 DEBUG ==> emitting event pre-bootstrap-app
lando 13:46:45 DEBUG ==> autoloaded legacy builder _drupaly 
lando 13:46:45 DEBUG ==> autoloaded legacy builder _lamp
lando 13:46:45 DEBUG ==> autoloaded legacy builder _lagoon
lando 13:46:45 DEBUG ==> autoloaded legacy builder _platformsh_appserver
lando 13:46:45 DEBUG ==> autoloaded legacy builder _platformsh_service
lando 13:46:45 DEBUG ==> autoloaded legacy builder apache
lando 13:46:45 DEBUG ==> autoloaded legacy builder compose
lando 13:46:45 DEBUG ==> autoloaded legacy builder dotnet
lando 13:46:45 DEBUG ==> autoloaded legacy builder elasticsearch
lando 13:46:45 DEBUG ==> autoloaded legacy builder go
lando 13:46:45 DEBUG ==> autoloaded legacy builder lagoon-basic
lando 13:46:45 DEBUG ==> autoloaded legacy builder lagoon-elasticsearch
lando 13:46:45 DEBUG ==> autoloaded legacy builder lagoon-mariadb
lando 13:46:45 DEBUG ==> autoloaded legacy builder lagoon-nginx
lando 13:46:45 DEBUG ==> autoloaded legacy builder lagoon-node
lando 13:46:45 DEBUG ==> autoloaded legacy builder lagoon-none
lando 13:46:45 DEBUG ==> autoloaded legacy builder lagoon-php-cli
lando 13:46:45 DEBUG ==> autoloaded legacy builder lagoon-php
lando 13:46:45 DEBUG ==> autoloaded legacy builder lagoon-postgres
lando 13:46:45 DEBUG ==> autoloaded legacy builder lagoon-python
lando 13:46:45 DEBUG ==> autoloaded legacy builder lagoon-redis
lando 13:46:45 DEBUG ==> autoloaded legacy builder lagoon-ruby
lando 13:46:45 DEBUG ==> autoloaded legacy builder lagoon-solr
lando 13:46:45 DEBUG ==> autoloaded legacy builder lagoon-varnish
lando 13:46:45 DEBUG ==> autoloaded legacy builder mailhog
lando 13:46:45 DEBUG ==> autoloaded legacy builder mariadb
lando 13:46:45 DEBUG ==> autoloaded legacy builder memcached
lando 13:46:45 DEBUG ==> autoloaded legacy builder mongo
lando 13:46:45 DEBUG ==> autoloaded legacy builder mssql
lando 13:46:45 DEBUG ==> autoloaded legacy builder mysql
lando 13:46:45 DEBUG ==> autoloaded legacy builder nginx
lando 13:46:45 DEBUG ==> autoloaded legacy builder node
lando 13:46:45 DEBUG ==> autoloaded legacy builder pantheon-mariadb
lando 13:46:45 DEBUG ==> autoloaded legacy builder php
lando 13:46:45 DEBUG ==> autoloaded legacy builder phpmyadmin
lando 13:46:45 DEBUG ==> autoloaded legacy builder platformsh-chrome-headless
lando 13:46:45 DEBUG ==> autoloaded legacy builder platformsh-elasticsearch
lando 13:46:45 DEBUG ==> autoloaded legacy builder platformsh-influxdb
lando 13:46:45 DEBUG ==> autoloaded legacy builder platformsh-kafka
lando 13:46:45 DEBUG ==> autoloaded legacy builder platformsh-mariadb
lando 13:46:45 DEBUG ==> autoloaded legacy builder platformsh-memcached
lando 13:46:45 DEBUG ==> autoloaded legacy builder platformsh-mongodb
lando 13:46:45 DEBUG ==> autoloaded legacy builder platformsh-mysql
lando 13:46:45 DEBUG ==> autoloaded legacy builder platformsh-php
lando 13:46:45 DEBUG ==> autoloaded legacy builder platformsh-postgresql 
lando 13:46:45 DEBUG ==> autoloaded legacy builder platformsh-rabbitmq
lando 13:46:45 DEBUG ==> autoloaded legacy builder platformsh-redis
lando 13:46:45 DEBUG ==> autoloaded legacy builder platformsh-solr
lando 13:46:45 DEBUG ==> autoloaded legacy builder platformsh-varnish
lando 13:46:45 DEBUG ==> autoloaded legacy builder postgres
lando 13:46:45 DEBUG ==> autoloaded legacy builder python
lando 13:46:45 DEBUG ==> autoloaded legacy builder redis
lando 13:46:45 DEBUG ==> autoloaded legacy builder ruby
lando 13:46:45 DEBUG ==> autoloaded legacy builder solr
lando 13:46:45 DEBUG ==> autoloaded legacy builder tomcat
lando 13:46:45 DEBUG ==> autoloaded legacy builder varnish
lando 13:46:45 DEBUG ==> autoloaded legacy builder acquia
lando 13:46:45 DEBUG ==> autoloaded legacy builder backdrop
lando 13:46:45 DEBUG ==> autoloaded legacy builder drupal10
lando 13:46:45 DEBUG ==> autoloaded legacy builder drupal6
lando 13:46:45 DEBUG ==> autoloaded legacy builder drupal7
lando 13:46:45 DEBUG ==> autoloaded legacy builder drupal8
lando 13:46:45 DEBUG ==> autoloaded legacy builder drupal9
lando 13:46:45 DEBUG ==> autoloaded legacy builder joomla
lando 13:46:45 DEBUG ==> autoloaded legacy builder lagoon
lando 13:46:45 DEBUG ==> autoloaded legacy builder lamp
lando 13:46:45 DEBUG ==> autoloaded legacy builder laravel
lando 13:46:45 DEBUG ==> autoloaded legacy builder lemp
lando 13:46:45 DEBUG ==> autoloaded legacy builder mean
lando 13:46:45 DEBUG ==> autoloaded legacy builder pantheon
lando 13:46:45 DEBUG ==> autoloaded legacy builder platformsh
lando 13:46:45 DEBUG ==> autoloaded legacy builder symfony
lando 13:46:45 DEBUG ==> autoloaded legacy builder wordpress
lando 13:46:45 DEBUG ==> autodiscovered legacy builder _appserver
lando 13:46:45 DEBUG ==> autodiscovered legacy builder _casetup
lando 13:46:45 DEBUG ==> autodiscovered legacy builder _lando
lando 13:46:45 DEBUG ==> autodiscovered legacy builder _landoutil
lando 13:46:45 DEBUG ==> autodiscovered legacy builder _service
lando 13:46:45 DEBUG ==> autodiscovered legacy builder _webserver
lando 13:46:45 DEBUG ==> autodiscovered legacy builder _proxy
lando 13:46:45 DEBUG ==> autodiscovered legacy builder _init
lando 13:46:45 DEBUG ==> autodiscovered legacy builder _service
lando 13:46:45 DEBUG ==> autodiscovered legacy builder lando
lando 13:46:45 DEBUG ==> autodiscovered legacy builder lando
lando 13:46:45 DEBUG ==> autodiscovered legacy builder _mounter
lando 13:46:45 DEBUG ==> emitting event post-bootstrap-app
lando 13:46:45 VERBOSE ==> app bootstrap completed.
lando 13:46:45 VERBOSE ==> bootstrap completed.
lando 13:46:45 DEBUG ==> emitting event post-bootstrap
lando 13:46:45 VERBOSE ==> docker-engine exists: true
lando 13:46:45 VERBOSE ==> docker-compose exists: true
lando 13:46:45 DEBUG ==> emitting event cli-answers 
lando 13:46:45 VERBOSE ==> checking docker version compatibility...
lando 13:46:45 DEBUG ==> compatibility results name=compose, link=undefined, satisfied=true, dockerVersion=true, version=2.21.0, name=desktop, link=undefined, satisfied=true, dockerVersion=true, version=4.16.2
lando 13:46:45 DEBUG ==> emitting event cli-restart-answers
lando 13:46:45 DEBUG ==> emitting event cli-run
lando 13:46:45 DEBUG ==> emitting event cli-restart-run 
lando 13:46:45 INFO ==> loading app woo-sync from config files 0=C:\Users\path\.lando.yml
lando 13:46:45 DEBUG ==> app woo-sync has config [redacted, let me know if you need it]
Stopping and restarting your app...Shiny!
woo-sync 13:46:45 INFO ==> restarting app...
woo-sync 13:46:45 INFO ==> stopping app...
woo-sync 13:46:45 VERBOSE ==> initiatilizing app at C:\Users\path\woocommerce-sync...
lando    13:46:45 DEBUG ==> plugin lando-core loaded from C:\snapshot\cli\node_modules\@lando\core\plugins\lando-core\app.js
lando    13:46:45 DEBUG ==> plugin lando-events loaded from C:\snapshot\cli\node_modules\@lando\core\plugins\lando-events\app.js
lando    13:46:45 DEBUG ==> plugin lando-healthcheck loaded from C:\snapshot\cli\node_modules\@lando\core\plugins\lando-healthcheck\app.js
lando    13:46:45 DEBUG ==> plugin lando-networking loaded from C:\snapshot\cli\node_modules\@lando\core\plugins\lando-networking\app.js
woo-sync 13:46:45 VERBOSE ==> proxy settings detected.
lando    13:46:45 DEBUG ==> plugin lando-proxy loaded from C:\snapshot\cli\node_modules\@lando\core\plugins\lando-proxy\app.js
lando    13:46:45 DEBUG ==> plugin lando-recipes loaded from C:\snapshot\cli\node_modules\@lando\core\plugins\lando-recipes\app.js
lando    13:46:45 DEBUG ==> plugin lando-scanner loaded from C:\snapshot\cli\node_modules\@lando\core\plugins\lando-scanner\app.js
lando    13:46:45 DEBUG ==> plugin lando-services-v4 loaded from C:\snapshot\cli\node_modules\@lando\core\plugins\lando-services-v4\app.js 
lando    13:46:45 DEBUG ==> plugin lando-services loaded from C:\snapshot\cli\node_modules\@lando\core\plugins\lando-services\app.js
lando    13:46:45 DEBUG ==> plugin lando-sharing loaded from C:\snapshot\cli\node_modules\@lando\core\plugins\lando-sharing\app.js
lando    13:46:45 DEBUG ==> plugin lando-tooling loaded from C:\snapshot\cli\node_modules\@lando\core\plugins\lando-tooling\app.js
lando    13:46:45 DEBUG ==> plugin @lando/acquia loaded from C:\snapshot\cli\node_modules\@lando\acquia\app.js
lando    13:46:45 DEBUG ==> plugin @lando/lagoon loaded from C:\snapshot\cli\node_modules\@lando\lagoon\app.js
lando    13:46:45 DEBUG ==> plugin @lando/pantheon loaded from C:\snapshot\cli\node_modules\@lando\pantheon\app.js
lando    13:46:45 DEBUG ==> plugin @lando/platformsh loaded from C:\snapshot\cli\node_modules\@lando\platformsh\app.js 
woo-sync 13:46:45 DEBUG ==> emitting event pre-init
woo-sync 13:46:45 VERBOSE ==> building wordpress recipe named
lando    13:46:45 VERBOSE ==> proxy is ON.
lando    13:46:45 VERBOSE ==> Setting the default proxy certificate /certs/cert.crt
woo-sync 13:46:45 DEBUG ==> emitting event pre-services-generate 
woo-sync 13:46:45 VERBOSE ==> building v3 php service appserver
woo-sync 13:46:45 VERBOSE ==> building v3 mysql service database
woo-sync 13:46:45 VERBOSE ==> building v3 phpmyadmin service pma
woo-sync 13:46:45 VERBOSE ==> building v3 mailhog service mailhog
woo-sync 13:46:45 DEBUG ==> emitting event post-init 
woo-sync 13:46:45 DEBUG ==> adding hostnames to the app...
woo-sync 13:46:45 DEBUG ==> hostnames added to appserver 0=appserver.woosync.internal
woo-sync 13:46:45 DEBUG ==> hostnames added to database 0=database.woosync.internal
woo-sync 13:46:45 DEBUG ==> hostnames added to pma 0=pma.woosync.internal
woo-sync 13:46:45 DEBUG ==> hostnames added to mailhog 0=mailhog.woosync.internal
woo-sync 13:46:45 VERBOSE ==> attempting to find open services...
lando    13:46:45 DEBUG ==> engine is up.
lando    13:46:45 DEBUG ==> docker is running.
woo-sync 13:46:45 DEBUG ==> engine is up. 
woo-sync 13:46:45 VERBOSE ==> refreshing certificates... 0=appserver, 1=database, 2=pma, 3=mailhog
woo-sync 13:46:45 VERBOSE ==> perm sweeping flagged non-root containers ... 0=database
woo-sync 13:46:45 VERBOSE ==> analyzing user ssh keys... using 3 of 3
woo-sync 13:46:45 DEBUG ==> key config...  none
woo-sync 13:46:45 DEBUG ==> going to build v3 services if applicable 0=appserver, 1=database, 2=pma, 3=mailhog
woo-sync 13:46:45 VERBOSE ==> additional tooling detected
woo-sync 13:46:45 DEBUG ==> adding app cli task composer
woo-sync 13:46:45 DEBUG ==> adding app cli task db-import <file>
woo-sync 13:46:45 DEBUG ==> adding app cli task db-export [file]
woo-sync 13:46:45 DEBUG ==> adding app cli task php
woo-sync 13:46:45 DEBUG ==> adding app cli task mysql
woo-sync 13:46:45 DEBUG ==> adding app cli task wp
woo-sync 13:46:45 DEBUG ==> adding app cli task build
woo-sync 13:46:45 DEBUG ==> adding app cli task deploy
woo-sync 13:46:45 DEBUG ==> adding app cli task deploy-test
woo-sync 13:46:45 DEBUG ==> adding app cli task make-pot
woo-sync 13:46:45 VERBOSE ==> setting LANDO_INFO...
woo-sync 13:46:45 DEBUG ==> ensuring exposed ports on appserver are bound to 127.0.0.1
woo-sync 13:46:45 DEBUG ==> ensuring exposed ports on appserver are bound to 127.0.0.1
woo-sync 13:46:45 DEBUG ==> ensuring exposed ports on database are bound to 127.0.0.1
woo-sync 13:46:45 DEBUG ==> ensuring exposed ports on pma are bound to 127.0.0.1
woo-sync 13:46:45 DEBUG ==> ensuring exposed ports on mailhog are bound to 127.0.0.1
woo-sync 13:46:45 VERBOSE ==> app is ready! 
woo-sync 13:46:45 DEBUG ==> emitting event ready
woo-sync 13:46:45 VERBOSE ==> discovering dynamic portforward info...
woo-sync 13:46:45 VERBOSE ==> v4 app is ready! 
woo-sync 13:46:45 DEBUG ==> emitting event ready-v4
woo-sync 13:46:45 VERBOSE ==> reporting stop action to report=true, url=https://metrics.lando.dev, report=true, url=https://metrics.lando.dev
woo-sync 13:46:45 DEBUG ==> reported data command=lando restart, context=local, devMode=false, instance=c9f78431b03d6d83b864bcabf66a0e7dc7a923e3, nodeVersion=v16.16.0, mode=cli, type=Windows_NT, platform=win32, release=10.0.22621, arch=x64, product=lando, version=3.20.2, app=4c4feb6308e12670078d301008083646b3c26e49, type=wordpress, services=[api=3, type=php, version=7.4, api=3, type=mysql, version=5.7, api=3, type=phpmyadmin, version=5.1, api=3, type=mailhog, version=v1.0.1], action=stop, created=2023-10-04T11:46:45.858Z
woo-sync 13:46:45 DEBUG ==> emitting event pre-stop
woo-sync 13:46:45 DEBUG ==> process pid3 running C:\Program Files\Docker\Docker\resources\bin\docker-compose.exe kill cstdio=inherit, silent=false, mode=spawn, detached=false
unknown flag: --project-name
See 'docker --help'.

[docker help output]

woo-sync 13:46:46 DEBUG ==> process pid3 finished with exit code 125 

[UH OH! message]

lando    13:46:46 ERROR ==> Error
    at C:\snapshot\cli\node_modules\@lando\core\lib\shell.js
From previous event:
    at Shell.sh (C:\snapshot\cli\node_modules\@lando\core\lib\shell.js)
    at Object.dc (C:\snapshot\cli\node_modules\@lando\core\lib\bootstrap.js)
    at compose (C:\snapshot\cli\node_modules\@lando\core\lib\bootstrap.js)
    at C:\snapshot\cli\node_modules\@lando\core\lib\router.js
From previous event:
    at retryEach (C:\snapshot\cli\node_modules\@lando\core\lib\router.js)
    at Object.stop (C:\snapshot\cli\node_modules\@lando\core\lib\router.js)
    at run (C:\snapshot\cli\node_modules\@lando\core\lib\engine.js)
    at C:\snapshot\cli\node_modules\@lando\core\lib\router.js
From previous event:
    at Object.eventWrapper (C:\snapshot\cli\node_modules\@lando\core\lib\router.js)
    at Engine.engineCmd (C:\snapshot\cli\node_modules\@lando\core\lib\engine.js)
    at Engine.stop (C:\snapshot\cli\node_modules\@lando\core\lib\engine.js)
    at C:\snapshot\cli\node_modules\@lando\core\lib\app.js
From previous event:
    at App.stop (C:\snapshot\cli\node_modules\@lando\core\lib\app.js)
    at App.restart (C:\snapshot\cli\node_modules\@lando\core\lib\app.js)
    at Object.run (C:\snapshot\cli\node_modules\@lando\core\plugins\lando-core\tasks\restart.js)
From previous event:
    at C:\snapshot\cli\lib\cli.js
    at processImmediate (node:internal/timers:466:21)
From previous event:
    at Object.handler (C:\snapshot\cli\lib\cli.js)
    at Object.runCommand (C:\snapshot\cli\node_modules\yargs\lib\command.js:238:44)
    at Object.parseArgs [as _parseArgs] (C:\snapshot\cli\node_modules\yargs\yargs.js:1063:30)
    at Function.get [as argv] (C:\snapshot\cli\node_modules\yargs\yargs.js:1004:21)
    at Cli.init (C:\snapshot\cli\lib\cli.js)
    at Cli.run (C:\snapshot\cli\lib\cli.js)
    at Object.<anonymous> (C:\snapshot\cli\bin\lando.js)
    at Module._compile (pkg/prelude/bootstrap.js:1926:22)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.runMain (pkg/prelude/bootstrap.js:1979:12)
    at node:internal/main/run_main_module:17:47

```

**Comment by oskarmodig** [comment]
Apparently the lando 3.20.2. updater silently failed to update Docker Desktop. After doing so manually it works.
