### ISSUE TITLE
Failed to connect to raw.githubusercontent.com port 443: Connection refused error:  Error: 7

### ISSUE THREAD

**Issue by ibdf** [lando/lando#363]
First time using lando.

Started lando init with a wp recipe.

Got the following error:

Creating test_appserver_1 ... done
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:20 --:--:--     0curl: (7) F
ailed to connect to raw.githubusercontent.com port 443: Connection refused
error:  Error: 7
    at ChildProcess.<anonymous> (C:\snapshot\cli\lib\shell.js:143:16)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:887:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:208:5)
From previous event:
    at spawn (C:\snapshot\cli\lib\shell.js:93:10)
    at Object.exports.sh (C:\snapshot\cli\lib\shell.js:209:12)
    at shCompose (C:\snapshot\cli\lib\compose.js:24:16)
    at Object.exports.run (C:\snapshot\cli\lib\compose.js:343:10)
    at C:\snapshot\cli\lib\docker.js:163:22
    at runCallback (timers.js:800:20)
    at tryOnImmediate (timers.js:762:5)
    at processImmediate [as _immediateCallback] (timers.js:733:5)
From previous event:
    at Object.exports.run (C:\snapshot\cli\lib\docker.js:150:18)
    at C:\snapshot\cli\lib\engine.js:526:19
    at runCallback (timers.js:800:20)
From previous event:
    at Object.exports.run (C:\snapshot\cli\lib\engine.js:525:4)
    at AsyncEvents.<anonymous> (C:\snapshot\cli\plugins\lando-services\lib\config.js:148:
31)
    at AsyncEvents.handle (C:\snapshot\cli\lib\events.js:109:19)
    at C:\snapshot\cli\lib\events.js:170:19
From previous event:
    at AsyncEvents.emit (C:\snapshot\cli\lib\events.js:161:18)
    at C:\snapshot\cli\lib\app.js:767:23
    at runCallback (timers.js:800:20)
From previous event:
    at Object.exports.start (C:\snapshot\cli\lib\app.js:766:4)
    at C:\snapshot\cli\plugins\lando-core\lib\tasks\start.js:29:28
From previous event:
    at Object.run (C:\snapshot\cli\plugins\lando-core\lib\tasks\start.js:25:8)
    at C:\snapshot\cli\lib\tasks.js:173:21
From previous event:
    at C:\snapshot\cli\lib\tasks.js:172:8
    at runCallback (timers.js:800:20)
    at tryOnImmediate (timers.js:762:5)
    at processImmediate [as _immediateCallback] (timers.js:733:5)
From previous event:
    at Object.exports.parseToYargs.command.handler (C:\snapshot\cli\lib\tasks.js:157:6)
    at Object.module.exports.self.runCommand (C:\snapshot\cli\node_modules\yargs\lib\comm
and.js:170:22)
    at parseArgs (C:\snapshot\cli\node_modules\yargs\yargs.js:920:28)
    at Object.get [as argv] (C:\snapshot\cli\node_modules\yargs\yargs.js:860:16)
    at C:\snapshot\cli\lib\cli.js:271:7
From previous event:
    at Object.exports.init (C:\snapshot\cli\lib\cli.js:238:4)
    at C:\snapshot\cli\bin\lando.js:21:20
From previous event:
    at Object.<anonymous> (C:\snapshot\cli\bin\lando.js:20:2)
    at Module._compile (pkg/prelude/bootstrap.js:1226:22)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (pkg/prelude/bootstrap.js:1281:12)
    at startup (bootstrap_node.js:200:16)
    at bootstrap_node.js:617:3

**Comment by ptmkenny** [comment]
Could be an intermittent connection error.

I just made a wordpress recipe with beta17 like this:

```
mkdir wordpress
cd wordpress
lando init
select: wordpress
Webroot: just press enter
call app: Wordpress
lando start
```

Then I had a wordpress install.  If it's not working for you, please provide your lando version, OS, and other config details.

**Comment by ibdf** [comment]
It might be a proxy issue. I will try initializing it from home, and see if I can get pass that point.

**Comment by benhadad** [comment]
Still have a related issue with WP recipe.  Local loopback and RestAPI give this error [https://wordpress.org/support/topic/error-curl-error-7-3/]  Seems it might be an issue in how the directory permissions are setup or how the proxy server works.

I am on the most current lando & docker (2.3.03) and tired 2.3.04.
