### ISSUE TITLE
edge_ssl The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested

### ISSUE THREAD

**Issue by btruong** [lando/lando#3638]
I encountered an issue with my local lando after updating my Mac OS to Sonoma 14.1.2 and updating Lando to the lastest version v3.20.6. I also updated docker to version 4.25.2. I see the following error when running `lando rebuild` and was wondering to anyone had any insight.  `The error is  edge_ssl The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested`

I am tempted to delete the following volume in the Docker UI "discoverla_home_edge_ssl" to see if it helps fix the issue and perhaps the volume will be rebuilt in the correct format but I want to know whether this approach is advisable and get your thoughts.

Perhaps my docker version 4.25.2 is not the one I should be using with Lando v3.20.6? If that is the case, what docker version and settings would you recommend I use? Thank everyone.

**Comment by pirog** [comment]
@btruong as long as Docker is able to emulate via Rosetta (it does by default i think) its probably safe to ignore the warning. as an FYI we are in the process of rolling out arm64 images for all the services we can

**Comment by btruong** [comment]
Thanks @pirog for following up. Ah so that was a warning and not the cause of my issue of the `lando rebuild` command not working. This issue started with my recent update of my Mac OS to 14.1.2 and so I downloaded the most recent version of Lando version v3.20.6 and Docker version 4.26.0 and still have the issue where my Lando stopped working. I ran `lando destroy` and deleted the containers and images in my Docker for a clean start and ran the command in verbose `lando rebuild -v` to see the errors in detail and here is the output:

```
lando      16:37:32 ERROR ==> TypeError: Cannot read properties of null (reading 'command')
    at /snapshot/cli/node_modules/@lando/core/plugins/lando-healthcheck/utils/normalize-healthcheck.js
    at /snapshot/cli/node_modules/@lando/core/plugins/lando-healthcheck/app.js
    at arrayMap (/snapshot/cli/node_modules/@lando/core/node_modules/lodash/lodash.js)
    at Function.map (/snapshot/cli/node_modules/@lando/core/node_modules/lodash/lodash.js)
    at interceptor (/snapshot/cli/node_modules/@lando/core/node_modules/lodash/lodash.js)
    at thru (/snapshot/cli/node_modules/@lando/core/node_modules/lodash/lodash.js)
    at /snapshot/cli/node_modules/@lando/core/node_modules/lodash/lodash.js
    at arrayReduce (/snapshot/cli/node_modules/@lando/core/node_modules/lodash/lodash.js)
    at baseWrapperValue (/snapshot/cli/node_modules/@lando/core/node_modules/lodash/lodash.js)
    at LazyWrapper.lazyValue [as value] (/snapshot/cli/node_modules/@lando/core/node_modules/lodash/lodash.js)
    at baseWrapperValue (/snapshot/cli/node_modules/@lando/core/node_modules/lodash/lodash.js)
    at LodashWrapper.wrapperValue (/snapshot/cli/node_modules/@lando/core/node_modules/lodash/lodash.js)
    at AsyncEvents.<anonymous> (/snapshot/cli/node_modules/@lando/core/plugins/lando-healthcheck/app.js)
    at AsyncEvents.handle (/snapshot/cli/node_modules/@lando/core/lib/events.js)
    at /snapshot/cli/node_modules/@lando/core/lib/events.js
    at processImmediate (node:internal/timers:466:21)
From previous event:
    at AsyncEvents.emit (/snapshot/cli/node_modules/@lando/core/lib/events.js)
From previous event:
    at App.start (/snapshot/cli/node_modules/@lando/core/lib/app.js)
    at /snapshot/cli/node_modules/@lando/core/lib/app.js
From previous event:
    at App.rebuild (/snapshot/cli/node_modules/@lando/core/lib/app.js)
    at Object.run (/snapshot/cli/node_modules/@lando/core/plugins/lando-core/tasks/rebuild.js)
From previous event:
    at /snapshot/cli/lib/cli.js
From previous event:
    at Object.handler (/snapshot/cli/lib/cli.js)
    at Object.runCommand (/snapshot/cli/node_modules/yargs/lib/command.js:238:44)
    at Object.parseArgs [as _parseArgs] (/snapshot/cli/node_modules/yargs/yargs.js:1063:30)
    at Function.get [as argv] (/snapshot/cli/node_modules/yargs/yargs.js:1004:21)
    at Cli.init (/snapshot/cli/lib/cli.js)
    at Cli.run (/snapshot/cli/lib/cli.js)
From previous event:
    at /snapshot/cli/bin/lando.js
    at processImmediate (node:internal/timers:466:21)
From previous event:
    at Object.<anonymous> (/snapshot/cli/bin/lando.js)
    at Module._compile (pkg/prelude/bootstrap.js:1926:22)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.runMain (pkg/prelude/bootstrap.js:1979:12)
    at node:internal/main/run_main_module:17:47 
```

It would be great to see if anyone had the same issue and was able to find a solve.

**Comment by codafogo** [comment]
I'm having the same problem. Any resolution?

**Comment by JeremyEnglert** [comment]
Also having this issue.

**Comment by reynoldsalec** [comment]
@JeremyEnglert + @codafogo + @jellobrain are you experiencing the issue described in https://github.com/lando/lando/issues/3638#issuecomment-1846326285 (IE, an error with `Cannot read properties of null (reading 'command')`) or are you seeing warning messages about the requested image's platform not matching the detected host platform?

**Comment by codafogo** [comment]
My issue matches the original title and issue posted here: edge_ssl The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested. I've tried updating both lando & docker. That didn't work. I tried rolling back both lando & docker. That didn't work. I've completely deleted docker & reinstalled several times. I've deleted the docker images, volumes & containers many, many times and restarted everything. Any other suggestions?

**Comment by reynoldsalec** [comment]
@codafogo that message is only a warning; it shouldn't impact functionality at all. Are you experiencing any specific functional issues?

**Comment by nbennett25** [comment]
Lando version v3.21.2, OS X version 14.6.1.

I just re-installed `lando` with the `--arch=arm64` platform flag, following the instructions here: https://docs.lando.dev/install/macos.html, then rebuilt the stack, and am still getting the unsupported platform error on the `edge_ssl` image:

` ! edge_ssl The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested 0.0s`

I get the `⚠ One of your v3 build steps failed` error at the end of the rebuild, but all of the server urls are 500s:

```
 SERVICES  appserver_nginx, appserver, database, cache, edge_ssl, edge, index 
 URLS                                                                         
  ⚠ APPSERVER NGINX URLS
    ✖ Request failed with status code 500
    ✖ Request failed with status code 500
  ⚠ EDGE SSL URLS
    ✖ Request failed with status code 500
  ⚠ EDGE URLS
    ✖ Request failed with status code 500
```

Previously a couple of the other docker images were also throwing the unsupported platform error, so this feels like progress...

**Comment by reynoldsalec** [comment]
@nbennett25 if you run `lando rebuild -y --debug` on the app, do you see why the build step failed?

If you can paste your landofile that would also help me see if I can replicate. FWIW, the `requested image's platform` message is a warning that simply means your `edge_ssl` container is being virtualized to arm. You can try disabling that service to see if the app builds correctly as a debugging measure.

**Comment by nbennett25** [comment]
Thx @reynoldsalec  - I ran the `rebuild` command, and now have _2_ ssl containers that are not qualified for the platform:

```
ed0.3s _ssl The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested 0.0s 
 ✔ Container edge_ssl_1                                                                                                                           Started0.6s 
 ! edge_ssl The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested 0.0s 
[+] Healthchecking 1/1
```
```
 URLS                                                                         
  ⚠ APPSERVER NGINX URLS
    ✖ Request failed with status code 500
    ✖ Request failed with status code 500
  ⚠ EDGE SSL URLS
    ✖ Request failed with status code 500
  ⚠ EDGE URLS
    ✖ Request failed with status code 500
```

I am seeing an early error on the `lando start` command (but seems unrelated to the image platform issue)
```
scan of 'https://localhost:58153/' failed with 'ECONNRESET' 'unknown'
```

I'm not actively working with this project, but would love to get a working env at some point... thx for any pointers!

**Comment by reynoldsalec** [comment]
@nbennett25 what does your `.lando.yml` look like?

**Comment by nbennett25** [comment]
doesn't seem too crazy..:
```
name: [project-name]
recipe: pantheon
config:
  php: '8.3'
  database: mariadb:10.4
  composer_version: 2-latest
  framework: drupal8
  site: [site]
  id: [id]
tooling:
  drush:
    service: appserver
    env:
      DRUSH_OPTIONS_URI: "[site uri]"
```
