### ISSUE TITLE
"Lando cannot write to /usr/local/bin" when running `lando update`

### ISSUE THREAD

**Issue by ccharlton** [lando/lando#3671]
After running `lando setup` (those bits are good), running `lando update` presented the following error. (Just installed Lando v3.21.0-beta.1)

But here's a funny note, when I run `lando version` it returns "v3.21.0-beta.3"?

```
PACKAGE              STATUS             COMMENT
@lando/cli           ⚠ Update available https://github.com/lando/cli/releases/tag/v3.21.0-beta.2


  lando [STARTED] Updating @lando/cli to v3.21.0-beta.2  +7544ms
  lando [FAILED] Lando cannot write to /usr/local/bin!  +1ms
  lando {}  +0ms
  lando ERROR Error: An update error occured! Rerun with lando update --debug for more info.
    at Object.run (/Users/myuser/.lando/plugins/@lando/core/tasks/update.js:163:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
From previous event:
    at process.processImmediate (node:internal/timers:476:21)
From previous event:
    at Object.handler (/snapshot/cli/lib/cli.js)
    at Object.runCommand (/snapshot/cli/node_modules/yargs/lib/command.js:238:44)
    at Object.parseArgs [as _parseArgs] (/snapshot/cli/node_modules/yargs/yargs.js:1063:30)
    at Function.get [as argv] (/snapshot/cli/node_modules/yargs/yargs.js:1004:21)
    at Cli.init (/snapshot/cli/lib/cli.js)
    at Cli.run (/snapshot/cli/lib/cli.js)
    at /snapshot/cli/bin/lando.js
From previous event:
    at Object.<anonymous> (/snapshot/cli/bin/lando.js)
    at Module._compile (pkg/prelude/bootstrap.js:1930:22)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Function.runMain (pkg/prelude/bootstrap.js:1983:12)
    at node:internal/main/run_main_module:23:47  +4ms
```

**Comment by maskedjellybean** [comment]
I'm experiencing this too.

**Comment by jeyram** [comment]
Currently you could change the permissions of that file and run _lando  update_ again successfully. 
`sudo chmod 777 /usr/share/lando/bin`

![Screenshot from 2024-02-21 12-56-28](https://github.com/lando/lando/assets/826007/d301b06a-002c-4eee-a838-e568bf337105)

**Comment by reynoldsalec** [comment]
On Mac I needed to run the following:

`sudo chmod a+w /usr/local/bin && sudo chmod a+w /usr/local/bin/lando && lando update`

I'll let @pirog follow-up here, I know he's working on a short-term solution for this, and we'll need to put more work into a longer-term solution that's durable.
