### ISSUE TITLE
error: TypeError: Cannot read property 'toUpperCase'

### ISSUE THREAD

**Issue by ibdf** [lando/lando#417]
Windows 10 Pro 1703
Lando Version: v3.0.0-beta.21
I have Hyper-V, Docker, Git for Windows installed
Docker version 17.06.0-ce, build 02c1d87

**command**: lando init --recipe wordpress

I can't get passed the "what do you want to call this app" question. It doesn't matter if a use  a --recipe or if I choose one from the options provided.

**Steps + Error:**

? Where is your webroot relative to the init destination? .
? What do you want to call this app? my-lando-app
error:  TypeError: Cannot read property 'toUpperCase' of null
    at Object.exports.isInstalled (C:\snapshot\cli\lib\daemon.js:189:12)
    at verifyDaemonInstalled (C:\snapshot\cli\lib\engine.js:76:17)
    at verifyDaemonIsReady (C:\snapshot\cli\lib\engine.js:110:10)
    at Object.exports.exists (C:\snapshot\cli\lib\engine.js:343:10)
    at Object.kill (C:\snapshot\cli\plugins\lando-core\lib\init.js:181:25)
    at C:\snapshot\cli\plugins\lando-core\lib\tasks\init.js:119:27
    at runCallback (timers.js:800:20)
    at tryOnImmediate (timers.js:762:5)
    at processImmediate [as _immediateCallback] (timers.js:733:5)
From previous event:
    at Object.run (C:\snapshot\cli\plugins\lando-core\lib\tasks\init.js:118:8)
    at C:\snapshot\cli\lib\tasks.js:205:21
From previous event:
    at C:\snapshot\cli\lib\tasks.js:204:8
    at runCallback (timers.js:800:20)
    at tryOnImmediate (timers.js:762:5)
    at processImmediate [as _immediateCallback] (timers.js:733:5)
From previous event:
    at Object.exports.parseToYargs.command.handler (C:\snapshot\cli\lib\tasks.js:189:6)
    at Object.module.exports.self.runCommand (C:\snapshot\cli\node_modules\yargs\lib\comman
d.js:170:22)
    at parseArgs (C:\snapshot\cli\node_modules\yargs\yargs.js:920:28)
    at Object.get [as argv] (C:\snapshot\cli\node_modules\yargs\yargs.js:860:16)
    at C:\snapshot\cli\lib\cli.js:267:7
From previous event:
    at Object.exports.init (C:\snapshot\cli\lib\cli.js:237:4)
    at C:\snapshot\cli\bin\lando.js:21:20
From previous event:
    at Object.<anonymous> (C:\snapshot\cli\bin\lando.js:20:2)
    at Module._compile (pkg/prelude/bootstrap.js:1226:22)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (pkg/prelude/bootstrap.js:1281:12)
    at startup (bootstrap_node.js:200:16)
    at bootstrap_node.js:617:3

**Comment by pirog** [comment]
@ibdf based on where that error is coming from my guess is that you dont have the `docker` binary in your `PATH`

**Comment by ibdf** [comment]
Thank you. That was my issue. I think some of my settings changed after I installed the Linux subsystem.
