### ISSUE TITLE
Symfony Setup Fails

### ISSUE THREAD

**Issue by grayloon** [lando/lando#431]
v3.0.0-beta.22 on macOS 10.12.6 with Docker 17.09.0-ce-mac35 (19611)
I'm trying to get a Symfony site hosted at Platform.sh running locally.

**.lando.yml:**
```
name: alva
recipe: custom
config:
  webroot: web
  via: nginx
```

**Commands executed:**
```
platform get sramcn6docnmm
cd alva
platform build
lando init --recipe=custom
lando start
```

**Errors:**
```
ERROR: 
        Can't find a suitable configuration file in this directory or any
        parent. Are you in the right directory?

        Supported filenames: docker-compose.yml, docker-compose.yaml
        
ERROR: 
        Can't find a suitable configuration file in this directory or any
        parent. Are you in the right directory?

        Supported filenames: docker-compose.yml, docker-compose.yaml
        
ERROR: 
        Can't find a suitable configuration file in this directory or any
        parent. Are you in the right directory?

        Supported filenames: docker-compose.yml, docker-compose.yaml
        
ERROR: 
        Can't find a suitable configuration file in this directory or any
        parent. Are you in the right directory?

        Supported filenames: docker-compose.yml, docker-compose.yaml
        
ERROR: 
        Can't find a suitable configuration file in this directory or any
        parent. Are you in the right directory?

        Supported filenames: docker-compose.yml, docker-compose.yaml
        
error:  Error: Error: 1
    at /snapshot/cli/lib/promise.js:56:17
    at runCallback (timers.js:800:20)
    at tryOnImmediate (timers.js:762:5)
    at processImmediate [as _immediateCallback] (timers.js:733:5)
From previous event:
    at rec (/snapshot/cli/lib/promise.js:42:13)
    at /snapshot/cli/lib/promise.js:50:20
    at ontimeout (timers.js:488:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:283:5)
From previous event:
    at /snapshot/cli/lib/promise.js:49:12
    at runCallback (timers.js:800:20)
    at tryOnImmediate (timers.js:762:5)
    at processImmediate [as _immediateCallback] (timers.js:733:5)
```

Drupal sites hosted on Platform.sh work with Lando. Is there a trick to getting Symfony sites working? Platform.sh has an example in their docs, but it's for Drupal. https://docs.platform.sh/gettingstarted/local/lando.html

**Comment by pirog** [comment]
@grayloon the "custom" recipe basically means "up to user to do everything". Lando is not php specific so custom doesn't even imply a basic php setup. I'm guessing what you are looking for is the `lemp` recipe since platform.sh uses nginx 
https://docs.devwithlando.io/tutorials/lemp.html
