### ISSUE TITLE
no space left on device

### ISSUE THREAD

**Issue by psren** [lando/lando#466]
I want to try lando for the first time.
While following the docs i get the following error.
On my machine is enough space.

```sh
lando start
Starting landoproxyhyperion5000gandalfedition_proxy_1 ...
Starting landoproxyhyperion5000gandalfedition_proxy_1 ... done
Creating network "neos_default" with the default driver
Creating volume "neos_appserver" with default driver
Creating volume "neos_data" with default driver
Creating volume "neos_data_database" with default driver
Pulling appserver (devwithlando/php:7.1-fpm)...
ERROR: failed to register layer: Error processing tar file(exit status 1): write /usr/local/lib/php/extensions/no-debug-non-zts-20160303/soap.so: no space left on device
Pulling appserver (devwithlando/php:7.1-fpm)...
ERROR: failed to register layer: Error processing tar file(exit status 1): write /usr/local/lib/php/extensions/no-debug-non-zts-20160303/soap.so: no space left on device
Pulling appserver (devwithlando/php:7.1-fpm)...
ERROR: failed to register layer: Error processing tar file(exit status 1): write /usr/local/lib/php/extensions/no-debug-non-zts-20160303/soap.so: no space left on device
Pulling appserver (devwithlando/php:7.1-fpm)...
ERROR: failed to register layer: Error processing tar file(exit status 1): write /usr/local/lib/php/extensions/no-debug-non-zts-20160303/redis.so: no space left on device
Pulling appserver (devwithlando/php:7.1-fpm)...
ERROR: failed to register layer: Error processing tar file(exit status 1): write /usr/local/lib/php/extensions/no-debug-non-zts-20160303/redis.so: no space left on device
error:  Error: Error: 1
    at /snapshot/cli/lib/promise.js:56:17
    at runCallback (timers.js:800:20)
    at tryOnImmediate (timers.js:762:5)
    at processImmediate [as _immediateCallback] (timers.js:733:5)
From previous event:
    at rec (/snapshot/cli/lib/promise.js:42:13)
    at /snapshot/cli/lib/promise.js:50:20
    at ontimeout (timers.js:488:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:283:5)
From previous event:
    at /snapshot/cli/lib/promise.js:49:12
    at runCallback (timers.js:800:20)
    at tryOnImmediate (timers.js:762:5)
    at processImmediate [as _immediateCallback] (timers.js:733:5)
```

Lando Version ```v3.0.0-beta.22```

Lando config

```yaml
# .lando.yml
name: neos
recipe: lemp
config:
  webroot: Web
```

What am I doing wrong?

**Comment by serundeputy** [comment]
@psren you might try

What about pruning the networks https://docs.docker.com/engine/reference/commandline/network_prune/:
```bash
$ docker network prune
```
And docker system prune https://docs.docker.com/engine/reference/commandline/system_prune/:
```bash
$ docker system prune
```

**Comment by psren** [comment]
Thanks a lot @serundeputy , ´´´docker system prune``` worked it out for me
