### ISSUE TITLE
Error pulling from docker registry when seemingly logged in to docker.

### ISSUE THREAD

**Issue by audiojak** [lando/lando#474]
Bug Report
==========

Mac 10.12.6
Lando v3.0.0-beta.22
.lando.yml is standard from Drupal 8 template

```
name: test-lightning-lando
recipe: drupal8
config:
  webroot: docroot
```

ran command "lando start"

```
gotCreating network "landoproxyhyperion5000gandalfedition_edge" with driver "bridge"
Pulling proxy (traefik:1.3-alpine)...
ERROR: Get https://registry-1.docker.io/v2/library/traefik/manifests/1.3-alpine: unauthorized: incorrect username or password
Pulling proxy (traefik:1.3-alpine)...
ERROR: Get https://registry-1.docker.io/v2/library/traefik/manifests/1.3-alpine: unauthorized: incorrect username or password
Pulling proxy (traefik:1.3-alpine)...
ERROR: Get https://registry-1.docker.io/v2/library/traefik/manifests/1.3-alpine: unauthorized: incorrect username or password
Pulling proxy (traefik:1.3-alpine)...
ERROR: Get https://registry-1.docker.io/v2/library/traefik/manifests/1.3-alpine: unauthorized: incorrect username or password
Pulling proxy (traefik:1.3-alpine)...
ERROR: Get https://registry-1.docker.io/v2/library/traefik/manifests/1.3-alpine: unauthorized: incorrect username or password
error:  Error: Error: 1
    at /snapshot/cli/lib/promise.js:56:17
    at runCallback (timers.js:800:20)
    at tryOnImmediate (timers.js:762:5)
    at processImmediate [as _immediateCallback] (timers.js:733:5)
From previous event:
    at rec (/snapshot/cli/lib/promise.js:42:13)
    at /snapshot/cli/lib/promise.js:50:20
    at ontimeout (timers.js:488:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:283:5)
From previous event:
    at /snapshot/cli/lib/promise.js:49:12
    at runCallback (timers.js:800:20)
    at tryOnImmediate (timers.js:762:5)
    at processImmediate [as _immediateCallback] (timers.js:733:5)
```
Logged out of docker and was successful: 

```
Pulling proxy (traefik:1.3-alpine)...
Creating landoproxyhyperion5000gandalfedition_proxy_1 ... 
Creating landoproxyhyperion5000gandalfedition_proxy_1 ... done
Creating network "testlightninglando_default" with the default driver
Creating volume "testlightninglando_appserver" with default driver
Creating volume "testlightninglando_data" with default driver
Creating volume "testlightninglando_data_database" with default driver
Pulling appserver (devwithlando/php:7.1-apache)...
Creating testlightninglando_appserver_1 ... 
Creating testlightninglando_database_1 ... 
Creating testlightninglando_database_1
Creating testlightninglando_database_1 ... done

```

etc

I am almost sure that this is a docker problem, not a Lando problem, but I thought I would bring it to your attention. When I was logged in to docker, there seemed to be nothing wrong with my login. It was showing up as logged in via the system tray icon dropdown menu.

**Comment by chrismagneti** [comment]
Same bug on my end. Logging out also solves the issue for me.

**Comment by serundeputy** [comment]
I can not replicate this:

MacOS
```bash
geoff@yep 472 (master) $ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.13.2
BuildVersion:	17C88
```

Docker for Mac:
``bash
geoff@yep 472 (master) $ docker --version
Docker version 17.09.1-ce, build 19e2cf6
```

@audiojak or @chrismagneti are you still having this issue?

**Comment by pirog** [comment]
@audiojak pretty sure this is a docker issue as well. going to close this out since we arent going to do anything on our end and this issue serves as a workaround
