### ISSUE TITLE
Error after updating to hotfix release - beta.24

### ISSUE THREAD

**Issue by danielrose28** [lando/lando#497]
Bug Report
==========

**Tell us about your setup**

What is your lando version and operating system?

`v3.0.0-beta.24 on latest version of macOS High Sierra 10.13.1`

**Tell us about your `.lando.yml`**

```
name: d7contrib
recipe: pantheon
config:
  framework: drupal
  env: dev
  site: d7contrib
  id: 0312e291-3098-4e68-a56d-e63cf6c33348
  xdebug: true
```

**Tell us about the command you were running**

I updated to the latest version, beta.24. I ran `lando poweroff`, downloaded and installed version 24, then ran `lando rebuild`, which returned the error, no matter which lando command I tried.

**Tell us about the error you got**

I got this error after any lando command:
```
error:  Error: EISDIR: illegal operation on a directory, open '/Users/daniel/.lando/services/config/nginx/fastcgi_params'
    at Object.fs.openSync (fs.js:638:18)
    at Object.fs.openSync (pkg/prelude/bootstrap.js:466:32)
    at copyFileSync (/snapshot/cli/node_modules/fs-extra/lib/copy.js:16:16)
    at copySync (/snapshot/cli/node_modules/fs-extra/lib/copy.js:85:7)
    at /snapshot/cli/node_modules/fs-extra/lib/copy.js:91:7
    at Array.forEach (native)
    at Object.copySync (/snapshot/cli/node_modules/fs-extra/lib/copy.js:90:14)
    at moveConfig (/snapshot/cli/plugins/lando-services/lib/services.js:0:0)
    at Object.build (/snapshot/cli/plugins/lando-services/lib/services.js:0:0)
    at nginx (/snapshot/cli/plugins/lando-services/php/php.js:0:0)
    at buildAppserver (/snapshot/cli/plugins/lando-services/php/php.js:0:0)
    at Object.services (/snapshot/cli/plugins/lando-services/php/php.js:0:0)
    at Object.build (/snapshot/cli/plugins/lando-services/lib/services.js:0:0)
    at /snapshot/cli/plugins/lando-services/lib/config.js:0:0
    at isBind (/snapshot/cli/node_modules/lodash/lodash.js:4944:15)
    at baseForOwn (/snapshot/cli/node_modules/lodash/lodash.js:3001:24)
    at index (/snapshot/cli/node_modules/lodash/lodash.js:4913:18)
    at Function.forEach (/snapshot/cli/node_modules/lodash/lodash.js:9359:14)
    at AsyncEvents.<anonymous> (/snapshot/cli/plugins/lando-services/lib/config.js:0:0)
    at AsyncEvents.handle (/snapshot/cli/lib/events.js:0:0)
    at /snapshot/cli/lib/events.js:0:0
From previous event:
    at AsyncEvents.emit (/snapshot/cli/lib/events.js:0:0)
From previous event:
    at instantiate (/snapshot/cli/lib/app.js:0:0)
    at /snapshot/cli/lib/app.js:0:0
From previous event:
    at Object.exports.get (/snapshot/cli/lib/app.js:0:0)
    at AsyncEvents.<anonymous> (/snapshot/cli/plugins/lando-tooling/lib/bootstrap.js:0:0)
    at AsyncEvents.handle (/snapshot/cli/lib/events.js:0:0)
    at /snapshot/cli/lib/events.js:0:0
From previous event:
    at AsyncEvents.emit (/snapshot/cli/lib/events.js:0:0)
    at /snapshot/cli/lib/bootstrap.js:0:0
    at runCallback (timers.js:800:20)
    at tryOnImmediate (timers.js:762:5)
    at processImmediate [as _immediateCallback] (timers.js:733:5)
From previous event:
    at /snapshot/cli/lib/bootstrap.js:0:0
    at bitmask (/snapshot/cli/node_modules/lodash/lodash.js:10067:25)
    at Object.<anonymous> (/snapshot/cli/bin/lando.js:0:0)
    at Module._compile (pkg/prelude/bootstrap.js:1226:22)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (pkg/prelude/bootstrap.js:1281:12)
    at startup (bootstrap_node.js:200:16)
    at bootstrap_node.js:617:3
```

**Tell us generally about your bug**

I tried updating to version 23 earlier in the day and got an error that I reported. Version 24 was then released as a hotfix. Later in the day I attempted to update to version 24 and got this error as reported above. 

This was fixed by running: `rm -rf /Users/daniel/.lando/services/config`, and then `lando rebuild`.

It seems as though there was some residual funkyness from trying to update to version 23 perhaps.

Posting here for the record and for reference in case this happens to anyone else.

Thanks again for the fix @pirog.

**Comment by kleinmp** [comment]
I had the exact same issue after updating from beta version 23 to 24 and the fix posted above of removing the services config file worked for me.  The only difference is that I'm running Mac OS El Capitan 10.11.6.

**Comment by jfmacdonald** [comment]
Same error here with beta 22 on macOS Sierra 10.12.6.

**Comment by alexfinnarn** [comment]
I have the same issue...crossposting.

What I did:
- On lando-v3.0.0-beta.24
- Run "uninstall:command"
- Remove "~/.lando/*"
- Reinstall lando-v3.0.0-beta.24

```bash
$ lando
 Error: EISDIR: illegal operation on a directory, open '~/.lando/services/config/scripts/add-cert.sh'
```

I think https://stackoverflow.com/questions/34959038/npm-stuck-giving-the-same-error-eisdir-illegal-operation-on-a-directory-read-a is my problem, but I followed the most voted on answer with no success. File exists, 777 perms, it is not a directory. 

cache, logs, and services are under "~/.lando" now for me so I know the reinstall created that directory with similar files as before.

**Comment by alexfinnarn** [comment]
`rm -rf /Users/daniel/.lando/services/config` works after install...I do now see that `~/.lando/services/config/scripts/add-cert.sh` was listed as a directory instead of a file, but after deleting the config directory, the file was created as a file.

**Comment by pirog** [comment]
@alexfinnarn i think this issue is only for people who installed our botched beta.23 release before the hotfix beta.24. That said, i'm going to see if there some corrective measures we can take here.
