### ISSUE TITLE
-d option fails on lando init pantheon  (with workaround)

### ISSUE THREAD

**Issue by KenWatts** [lando/lando#584]
v.0.0-beta.31 on Windows 10 Pro

```yml
name: dailymull
recipe: pantheon
config:
  framework: drupal8
  site: dailymull
  id: (withheld)
```

What is your lando version and operating system? **(note that the older your version the less likely we are to reply)**

*Example: v3.0.0-alpha1 on Windows 10 Professional*

**Tell us about your `.lando.yml`**

Paste in the contents of your `.lando.yml` this is **SUPER HELPFUL** for us.

*Example:*

```yml
name: lamp2
recipe: lamp
config:
  php: '5.6'
  webroot: www
  database: mysql
  xdebug: true
  conf:
    server: config/lamp.conf
    database: config/mysql
    php: config/php.ini
```
running lando init pantheon -d tdm

Everything went swimmingly until I selected the site, then:

```
C:\Users\ken\lando>lando init pantheon -d dm
? Choose a Pantheon account ken@krwatts.com
? Which site? dailymull
ERROR: Named volume "dm:/app:rw" is used in service "util" but no declaration was found in the volumes section.
ERROR: Named volume "dm:/app:rw" is used in service "util" but no declaration was found in the volumes section.
ERROR: Named volume "dm:/app:rw" is used in service "util" but no declaration was found in the volumes section.
ERROR: Named volume "dm:/app:rw" is used in service "util" but no declaration was found in the volumes section.
ERROR: Named volume "dm:/app:rw" is used in service "util" but no declaration was found in the volumes section.
error:  Error: Error: 1
    at C:\snapshot\cli\lib\promise.js:0:0
    at runCallback (timers.js:800:20)
    at tryOnImmediate (timers.js:762:5)
    at processImmediate [as _immediateCallback] (timers.js:733:5)
From previous event:
    at rec (C:\snapshot\cli\lib\promise.js:0:0)
    at C:\snapshot\cli\lib\promise.js:0:0
    at ontimeout (timers.js:488:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:283:5)
From previous event:
    at C:\snapshot\cli\lib\promise.js:0:0
    at runCallback (timers.js:800:20)
    at tryOnImmediate (timers.js:762:5)
    at processImmediate [as _immediateCallback] (timers.js:733:5)
```

WORKAROUND

I finally discovered that running init from within the directory (tdm in this case) without the "-d" worked fine.

**Comment by pirog** [comment]
@KenWatts yup, def confirm this is a bug. Pushing a fix that will be in the next release.
