### ISSUE TITLE
Lando init github stops

### ISSUE THREAD

**Issue by ujeshurun** [lando/lando#622]
Bug Report
==========

**My Setup**

v3.0.0-beta.33 on Windows 10 Professional

**NO  `.lando.yml` file created (init command stops before finishing)**

**The command I am running**

``lando init github``

So that I can go through the interactive setup for GitHub. The following is what the console displays:

```
PS C:\User\myuser\Projects\myWordpress> lando init github
? Enter a GitHub token [hidden]
error:  Error: Token authentication requires a token to be set
    at module.exports.__dirname.authenticate (C:\snapshot\cli\node_modules\github\lib\index.js:363:19)
    at Object.choices (C:\snapshot\cli\plugins\lando-core\lib\github.js:0:0)
    at C:\snapshot\cli\node_modules\run-async\index.js:25:25
    at Promise (<anonymous>)
    at module.exports (C:\snapshot\cli\node_modules\run-async\index.js:24:19)
    at exports.fetchAsyncQuestionProperty (C:\snapshot\cli\node_modules\inquirer\lib\utils\utils.js:20:60)
    at tryCatcher (C:\snapshot\cli\node_modules\rx-lite\rx.lite.js:67:31)
    at InnerObserver.Rx.FlatMapObservable.InnerObserver.next (C:\snapshot\cli\node_modules\rx-lite\rx.lite.js:1907:43)
    at InnerObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (C:\snapshot\cli\node_modules\rx-lite\rx.lite.js:1602:31)
    at InnerObserver.tryCatcher (C:\snapshot\cli\node_modules\rx-lite\rx.lite.js:67:31)
    at AutoDetachObserverPrototype.next (C:\snapshot\cli\node_modules\rx-lite\rx.lite.js:6495:51)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (C:\snapshot\cli\node_modules\rx-lite\rx.lite.js:1602:31)
    at InnerObserver.next (C:\snapshot\cli\node_modules\rx-lite\rx.lite.js:2988:65)
    at InnerObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (C:\snapshot\cli\node_modules\rx-lite\rx.lite.js:1602:31)
    at InnerObserver.tryCatcher (C:\snapshot\cli\node_modules\rx-lite\rx.lite.js:67:31)
    at AutoDetachObserverPrototype.next (C:\snapshot\cli\node_modules\rx-lite\rx.lite.js:6495:51)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (C:\snapshot\cli\node_modules\rx-lite\rx.lite.js:1602:31)
    at scheduleItem (C:\snapshot\cli\node_modules\rx-lite\rx.lite.js:2604:16)
    at JustObservable.subscribeCore (C:\snapshot\cli\node_modules\rx-lite\rx.lite.js:2598:9)
    at JustObservable.tryCatcher (C:\snapshot\cli\node_modules\rx-lite\rx.lite.js:67:31)
    at setDisposable (C:\snapshot\cli\node_modules\rx-lite\rx.lite.js:1849:46)
    at JustObservable.Rx.ObservableBase.ObservableBase._subscribe (C:\snapshot\cli\node_modules\rx-lite\rx.lite.js:1864:9)
From previous event:
    at runCallback (timers.js:800:20)
    at tryOnImmediate (timers.js:762:5)
    at processImmediate [as _immediateCallback] (timers.js:733:5)
From previous event:
    at Object.exports.parseToYargs.command.handler (C:\snapshot\cli\lib\tasks.js:0:0)
    at Object.module.exports.self.runCommand (C:\snapshot\cli\node_modules\yargs\lib\command.js:170:22)
    at parseArgs (C:\snapshot\cli\node_modules\yargs\yargs.js:920:28)
    at Object.get [as argv] (C:\snapshot\cli\node_modules\yargs\yargs.js:860:16)
    at C:\snapshot\cli\lib\cli.js:0:0
From previous event:
    at Object.exports.init (C:\snapshot\cli\lib\cli.js:0:0)
    at C:\snapshot\cli\bin\lando.js:0:0
From previous event:
    at Object.<anonymous> (C:\snapshot\cli\bin\lando.js:0:0)
    at Module._compile (pkg/prelude/bootstrap.js:1226:22)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (pkg/prelude/bootstrap.js:1281:12)
    at startup (bootstrap_node.js:200:16)
    at bootstrap_node.js:617:3
```

It always stops at the very same line, " at bootstrap_node.js:617:3". Nothing is created in my root directory. Running the `verbose` command returns the same output.

**I noticed the first line error**
`error:  Error: Token authentication requires a token to be set`
But after searching, I could not figure if this was an issue to solve with Lando or GitHub.

I read this [issue](https://github.com/lando/lando/issues/608), and although his code stops at the very same point, I'm not sure that he experienced the same issue.

Does this bug prevent you from using lando? 
I currently am using Lando for the first time for a specific WordPress project. So this is a big hindrance at the moment.

Any guidance would be greatly appreciated.

**Comment by pirog** [comment]
@ujeshurun looks like you are aren't inputting a valid token. You can always manually `git clone` your site and then `lando init`.
