### ISSUE TITLE
Offline mode doesn't work due to metrics and update check

### ISSUE THREAD

**Issue by dmsmidt** [lando/lando#630]
Bug Report
==========

**v3.0.0-beta.35 on Mac High Sierra**

No lando commands work due to bugs in the way no internet connectivity is handled during internal metrics gathering and the update check.

<img width="1034" alt="screen shot 2018-01-09 at 09 21 52" src="https://user-images.githubusercontent.com/3950877/34711963-7c8b1506-f521-11e7-9781-89a99351543f.png">

```
warn:  getaddrinfo ENOTFOUND api.github.com api.github.com:443
    at module.exports.__dirname.sendError (/Users/dmsmidt/src/lando/node_modules/github/lib/index.js:854:19)
    at /Users/dmsmidt/src/lando/node_modules/github/lib/index.js:865:29
    at callCallback (/Users/dmsmidt/src/lando/node_modules/github/lib/index.js:728:17)
    at ClientRequest.<anonymous> (/Users/dmsmidt/src/lando/node_modules/github/lib/index.js:807:17)
    at ClientRequest.emit (events.js:159:13)
    at TLSSocket.socketErrorListener (_http_client.js:389:9)
    at TLSSocket.emit (events.js:159:13)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at process._tickCallback (internal/process/next_tick.js:152:19)
From previous event:
    at Object.self.(anonymous function).(anonymous function) [as getReleases] (/Users/dmsmidt/src/lando/node_modules/github/lib/index.js:275:40)
    at /Users/dmsmidt/src/lando/lib/update.js:58:27
From previous event:
    at AsyncEvents.<anonymous> (/Users/dmsmidt/src/lando/lib/update.js:36:21)
    at AsyncEvents.handle (/Users/dmsmidt/src/lando/lib/events.js:109:19)
    at /Users/dmsmidt/src/lando/lib/events.js:170:19
    at runCallback (timers.js:773:18)
    at tryOnImmediate (timers.js:734:5)
    at processImmediate [as _immediateCallback] (timers.js:711:5)
From previous event:
    at AsyncEvents.emit (/Users/dmsmidt/src/lando/lib/events.js:161:18)
    at /Users/dmsmidt/src/lando/lib/bootstrap.js:94:23
    at /Users/dmsmidt/src/lando/node_modules/lodash/lodash.js:10067:25
    at Object.<anonymous> (/Users/dmsmidt/src/lando/bin/lando.js:17:1)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Function.Module.runMain (module.js:701:10)
    at startup (bootstrap_node.js:194:16)
    at bootstrap_node.js:618:3
error:  TypeError: Cannot read property 'version' of undefined
    at /Users/dmsmidt/src/lando/lib/update.js:85:35
From previous event:
    at AsyncEvents.<anonymous> (/Users/dmsmidt/src/lando/lib/update.js:84:4)
    at AsyncEvents.handle (/Users/dmsmidt/src/lando/lib/events.js:109:19)
    at /Users/dmsmidt/src/lando/lib/events.js:170:19
    at runCallback (timers.js:773:18)
    at tryOnImmediate (timers.js:734:5)
    at processImmediate [as _immediateCallback] (timers.js:711:5)
From previous event:
    at AsyncEvents.emit (/Users/dmsmidt/src/lando/lib/events.js:161:18)
    at /Users/dmsmidt/src/lando/lib/bootstrap.js:94:23
    at /Users/dmsmidt/src/lando/node_modules/lodash/lodash.js:10067:25
    at Object.<anonymous> (/Users/dmsmidt/src/lando/bin/lando.js:17:1)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Function.Module.runMain (module.js:701:10)
    at startup (bootstrap_node.js:194:16)
    at bootstrap_node.js:618:3
```

**Comment by dmsmidt** [comment]
PR comming up.
