### ISSUE TITLE
Error during lando init github

### ISSUE THREAD

**Issue by andileco** [lando/lando#655]
**What is your lando version and operating system? (note that the older your version the less likely we are to reply)**

Lando v3.0.0-beta.35 on Sierra 10.12.6

**Tell us about your `.lando.yml`**

I am wanting init to create a .lando.yml file for me, so I don't already have one.

**Tell us about the command you were running**

lando init github

**Tell us about the error you got**
```bash
My-MacBook:thename whoami$ lando init github -- -vvvv

verbose: Loading event pre-bootstrap priority 1

verbose: Loading event pre-bootstrap priority 1

info: Bootstrap starting...

debug: Boostrapping with appConfigFilename=.lando.yml, appsRoot=/Users/whoami/Lando, appRegistry=/Users/whoami/.lando/appRegistry.json, cache=true, composeBin=/Applications/Docker.app/Contents/Resources/bin/docker-compose, composeVersion=3.2, configFilename=config.yml, , dockerBin=/Applications/Docker.app/Contents/Resources/bin/docker, dockerBinDir=/Applications/Docker.app/Contents/Resources/bin, engineId=501, engineGid=20, TERM_PROGRAM=Apple_Terminal, SHELL=/bin/bash, TERM=xterm-256color, TMPDIR=/var/folders/fl/59dsgf0s3r35nh68xk2l3r9h0000gn/T/, Apple_PubSub_Socket_Render=/private/tmp/com.apple.launchd.9spKmqe5XG/Render, TERM_PROGRAM_VERSION=388.1.1, OLDPWD=/Users/whoami/Lando, TERM_SESSION_ID=981491CD-9211-4D19-993E-C8D23320833A, USER=whoami, SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.E5BZIAB9Vz/Listeners, __CF_USER_TEXT_ENCODING=0x1F5:0x0:0x0, PATH=/Applications/Docker.app/Contents/Resources/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/DevDesktop/tools, PWD=/Users/whoami/Lando/thename, LANG=en_US.UTF-8, XPC_FLAGS=0x0, XPC_SERVICE_NAME=0, SHLVL=1, HOME=/Users/whoami, LOGNAME=whoami, SECURITYSESSIONID=186a6, _=/usr/local/bin/lando, home=/Users/whoami, isNW=false, logLevel=debug, logLevelConsole=warn, loadPassphraseProtectedKeys=false, node=v8.0.0, type=Darwin, platform=darwin, release=16.7.0, arch=x64, stats=[report=true, url=http://metrics.devwithlando.io], srcRoot=/snapshot/cli, sysConfRoot=/Applications/Lando.app/Contents/MacOS, userConfRoot=/Users/whoami/.lando, version=3.0.0-beta.35, plugins=[lando-core, lando-events, lando-proxy, lando-recipes, lando-services, lando-tooling], mode=cli

silly: It's not particularly silly, is it? I mean, the right leg isn't silly at all and the left leg merely does a forward aerial half turn every alternate step.

verbose: Emitting event pre-bootstrap

debug: Event pre-bootstrap has 2 listeners

debug: Retrieved from file cache with key lando:updates

debug: Retrieved from file cache with key lando:updates

verbose: Trying to load plugins 0=lando-core, 1=lando-events, 2=lando-proxy, 3=lando-recipes, 4=lando-services, 5=lando-tooling

debug: Searching for lando-core plugin in ["/snapshot/cli/node_modules/lando-core/index.js","/snapshot/cli/plugins/lando-core/index.js","/Applications/Lando.app/Contents/MacOS/node_modules/lando-core/index.js","/Applications/Lando.app/Contents/MacOS/plugins/lando-core/index.js","/Users/whoami/.lando/node_modules/lando-core/index.js","/Users/whoami/.lando/plugins/lando-core/index.js"]

debug: Searching for lando-events plugin in ["/snapshot/cli/node_modules/lando-events/index.js","/snapshot/cli/plugins/lando-events/index.js","/Applications/Lando.app/Contents/MacOS/node_modules/lando-events/index.js","/Applications/Lando.app/Contents/MacOS/plugins/lando-events/index.js","/Users/whoami/.lando/node_modules/lando-events/index.js","/Users/whoami/.lando/plugins/lando-events/index.js"]

debug: Searching for lando-proxy plugin in ["/snapshot/cli/node_modules/lando-proxy/index.js","/snapshot/cli/plugins/lando-proxy/index.js","/Applications/Lando.app/Contents/MacOS/node_modules/lando-proxy/index.js","/Applications/Lando.app/Contents/MacOS/plugins/lando-proxy/index.js","/Users/whoami/.lando/node_modules/lando-proxy/index.js","/Users/whoami/.lando/plugins/lando-proxy/index.js"]

debug: Searching for lando-recipes plugin in ["/snapshot/cli/node_modules/lando-recipes/index.js","/snapshot/cli/plugins/lando-recipes/index.js","/Applications/Lando.app/Contents/MacOS/node_modules/lando-recipes/index.js","/Applications/Lando.app/Contents/MacOS/plugins/lando-recipes/index.js","/Users/whoami/.lando/node_modules/lando-recipes/index.js","/Users/whoami/.lando/plugins/lando-recipes/index.js"]

debug: Searching for lando-services plugin in ["/snapshot/cli/node_modules/lando-services/index.js","/snapshot/cli/plugins/lando-services/index.js","/Applications/Lando.app/Contents/MacOS/node_modules/lando-services/index.js","/Applications/Lando.app/Contents/MacOS/plugins/lando-services/index.js","/Users/whoami/.lando/node_modules/lando-services/index.js","/Users/whoami/.lando/plugins/lando-services/index.js"]

debug: Searching for lando-tooling plugin in ["/snapshot/cli/node_modules/lando-tooling/index.js","/snapshot/cli/plugins/lando-tooling/index.js","/Applications/Lando.app/Contents/MacOS/node_modules/lando-tooling/index.js","/Applications/Lando.app/Contents/MacOS/plugins/lando-tooling/index.js","/Users/whoami/.lando/node_modules/lando-tooling/index.js","/Users/whoami/.lando/plugins/lando-tooling/index.js"]

verbose: Loading event post-bootstrap priority 1

verbose: Loading event post-bootstrap priority 5

verbose: Loading event post-bootstrap priority 9

verbose: Loading event post-instantiate-app priority 1

verbose: Loading event post-instantiate-app priority 5

verbose: Loading event post-instantiate-app priority 1

verbose: Loading event post-instantiate-app priority 1

verbose: Loading event post-bootstrap priority 1

verbose: Loading event post-instantiate-app priority 1

verbose: Loading event post-bootstrap priority 5

verbose: Loading event poweroff priority 5

verbose: Loading event post-instantiate-app priority 5

verbose: Loading event post-bootstrap priority 1

verbose: Loading event post-bootstrap priority 5

verbose: Loading event post-bootstrap priority 8

verbose: Loading event post-instantiate-app priority 2

verbose: Loading event post-bootstrap priority 1

verbose: Loading event post-bootstrap priority 5

verbose: Loading event post-bootstrap priority 9

verbose: Loading event task-rebuild-run priority 5

verbose: Loading event post-instantiate-app priority 3

verbose: Loading event post-bootstrap priority 1

verbose: Loading event post-bootstrap priority 5

verbose: Plugin lando-core loaded from /snapshot/cli/plugins/lando-core/index.js

verbose: Plugin lando-events loaded from /snapshot/cli/plugins/lando-events/index.js

verbose: Plugin lando-proxy loaded from /snapshot/cli/plugins/lando-proxy/index.js

verbose: Plugin lando-recipes loaded from /snapshot/cli/plugins/lando-recipes/index.js

verbose: Plugin lando-services loaded from /snapshot/cli/plugins/lando-services/index.js

verbose: Plugin lando-tooling loaded from /snapshot/cli/plugins/lando-tooling/index.js

info: Core plugins loaded

verbose: Emitting event post-bootstrap

debug: Event post-bootstrap has 13 listeners

info: Initializing init framework

info: Initializing events

info: Initializing recipes

info: Initializing services

verbose: Copying scripts config from /snapshot/cli/plugins/lando-services/scripts to /Users/whoami/.lando/services/config/scripts

verbose: Copying helpers config from /snapshot/cli/plugins/lando-services/helpers to /Users/whoami/.lando/services/config/helpers

info: Initializing tooling

verbose: Loading event task-init-answers priority 5

verbose: Loading event task-init-run priority 5

debug: Retrieved from file cache with key init:auth:github:tokens

debug: Cache miss with key init:auth:github:tokens

info: Initializing proxy

verbose: Proxy initialized with config proxy=ON, proxyDash=58086, proxyHttpPort=80, proxyHttpsPort=443, proxyHttpFallbacks=[8000, 8080, 8888, 8008], proxyHttpsFallbacks=[444, 4433, 4444, 4443]

verbose: Loading event task-init-answers priority 5

verbose: Loading event task-init-run priority 1

debug: Retrieved from file cache with key init:auth:pantheon:tokens

verbose: Loading event post-instantiate-app priority 5

verbose: Checking for app config at /Users/whoami/Lando/thename/.lando.yml

verbose: Checking for app config at /Users/whoami/Lando/.lando.yml

verbose: Checking for app config at /Users/whoami/.lando.yml

verbose: Checking for app config at /Users/.lando.yml

verbose: Checking for app config at .lando.yml

verbose: Recipe custom loaded

verbose: Recipe backdrop loaded

verbose: Recipe drupal6 loaded

verbose: Recipe drupal7 loaded

verbose: Recipe drupal8 loaded

verbose: Recipe joomla loaded

verbose: Recipe laravel loaded

verbose: Recipe lamp loaded

verbose: Recipe lemp loaded

verbose: Recipe mean loaded

verbose: Recipe pantheon loaded

verbose: Recipe wordpress loaded

verbose: Init method github loaded

verbose: Init method pantheon loaded

verbose: Service apache loaded

verbose: Service dotnet loaded

verbose: Service elasticsearch loaded

verbose: Service go loaded

verbose: Service nginx loaded

verbose: Service node loaded

verbose: Service mailhog loaded

verbose: Service mariadb loaded

verbose: Service memcached loaded

verbose: Service mssql loaded

verbose: Service mongo loaded

verbose: Service mysql loaded

verbose: Service postgres loaded

verbose: Service php loaded

verbose: Service phpmyadmin loaded

verbose: Service python loaded

verbose: Service redis loaded

verbose: Service ruby loaded

verbose: Service solr loaded

verbose: Service tomcat loaded

verbose: Service varnish loaded

info: Bootstrap completed.

info: Initializing cli

verbose: Emitting event pre-cli-load

debug: Event pre-cli-load has 0 listeners

verbose: Loading cli task config

verbose: Loading cli task destroy

verbose: Loading cli task info

verbose: Loading cli task init

verbose: Loading cli task list

verbose: Loading cli task logs

verbose: Loading cli task poweroff

verbose: Loading cli task rebuild

verbose: Loading cli task restart

verbose: Loading cli task share

verbose: Loading cli task ssh

verbose: Loading cli task start

verbose: Loading cli task stop

verbose: Loading cli task version

verbose: Emitting event task-init-answers

debug: Event task-init-answers has 2 listeners

debug: CLI args _=[init, -vvvv], yes=false, y=false, destination=/Users/whoami/Lando/thename, dest=/Users/whoami/Lando/thename, d=/Users/whoami/Lando/thename, $0=/usr/local/bin/lando /snapshot/cli/bin/lando.js, recipe=undefined, github-auth=undefined, github-auth-token=undefined, github-repo=undefined, pantheon-auth=undefined, pantheon-auth-machine-token=undefined, pantheon-site=undefined, webroot=undefined, name=undefined, method=github

debug: Retrieved from file cache with key init:auth:github:tokens

debug: Cache miss with key init:auth:github:tokens

? Enter a GitHub token [hidden]

debug: Retrieved from file cache with key init:auth:github:tokens

debug: Cache miss with key init:auth:github:tokens

? Which site? myname/the_name

? What recipe do you want to use? drupal8

debug: Retrieved from file cache with key init:auth:pantheon:tokens

? Where is your webroot relative to the init destination? .

verbose: Emitting event task-init-run

debug: Event task-init-run has 2 listeners

verbose: Building the_name with github method

debug: Building the_name with config _=[init, -vvvv], yes=false, y=false, destination=/Users/whoami/Lando/thename, dest=/Users/whoami/Lando/thename, d=/Users/whoami/Lando/thename, $0=/usr/local/bin/lando /snapshot/cli/bin/lando.js, recipe=drupal8, github-auth=770f397031a5cb7cfb06b6fc64938421b1f3e692, github-auth-token=undefined, github-repo=git@github.com:myname/the_name.git, pantheon-auth=undefined, pantheon-auth-machine-token=undefined, pantheon-site=undefined, webroot=., name=the_name, method=github

debug: Retrieved from file cache with key init:auth:github:tokens

debug: Cache miss with key init:auth:github:tokens

verbose: Creating key github.lando.id_rsa for GitHub

debug: Run util service {"version":"3.2","services":{"util":{"image":"devwithlando/util:stable","environment":{"LANDO":"ON","LANDO_HOST_OS":"darwin","LANDO_HOST_UID":"501","LANDO_HOST_GID":"20","LANDO_HOST_IP":"10.0.0.119","LANDO_WEBROOT_USER":"www-data","LANDO_WEBROOT_GROUP":"www-data","LANDO_WEBROOT_UID":"33","LANDO_WEBROOT_GID":"33","LANDO_MOUNT":"/app","COLUMNS":256,"TERM":"xterm"},"command":["tail","-f","/dev/null"],"entrypoint":"/lando-entrypoint.sh","labels":{"io.lando.container":"TRUE","io.lando.service-container":"TRUE"},"volumes":["$LANDO_ENGINE_SCRIPTS_DIR/lando-entrypoint.sh:/lando-entrypoint.sh","$LANDO_ENGINE_SCRIPTS_DIR/user-perms.sh:/user-perms.sh","$LANDO_ENGINE_SCRIPTS_DIR/load-keys.sh:/load-keys.sh","/Users/whoami/Lando/thename:/app:delegated","$LANDO_ENGINE_HOME:/user:delegated"]}}}

verbose: Building compose file at /Users/whoami/.lando/util/util.yml with services. 0=version, 1=services

verbose: Writing ["version","services"] to /Users/whoami/.lando/util/util.yml

debug: Full services for /Users/whoami/.lando/util/util.yml version=3.2, image=devwithlando/util:stable, LANDO=ON, LANDO_HOST_OS=darwin, LANDO_HOST_UID=501, LANDO_HOST_GID=20, LANDO_HOST_IP=10.0.0.119, LANDO_WEBROOT_USER=www-data, LANDO_WEBROOT_GROUP=www-data, LANDO_WEBROOT_UID=33, LANDO_WEBROOT_GID=33, LANDO_MOUNT=/app, COLUMNS=256, TERM=xterm, command=[tail, -f, /dev/null], entrypoint=/lando-entrypoint.sh, io.lando.container=TRUE, io.lando.service-container=TRUE, volumes=[$LANDO_ENGINE_SCRIPTS_DIR/lando-entrypoint.sh:/lando-entrypoint.sh, $LANDO_ENGINE_SCRIPTS_DIR/user-perms.sh:/user-perms.sh, $LANDO_ENGINE_SCRIPTS_DIR/load-keys.sh:/load-keys.sh, /Users/whoami/Lando/thename:/app:delegated, $LANDO_ENGINE_HOME:/user:delegated]

debug: Retrieved from file cache with key engineUp

debug: Cache miss with key engineUp

debug: About to run 0=/Applications/Docker.app/Contents/Resources/bin/docker, 1=info

silly: With pre run opts

verbose: Running exec /Applications/Docker.app/Contents/Resources/bin/docker,info

debug: With env TERM_PROGRAM=Apple_Terminal, SHELL=/bin/bash, TERM=xterm-256color, TMPDIR=/var/folders/fl/59dsgf0s3r35nh68xk2l3r9h0000gn/T/, Apple_PubSub_Socket_Render=/private/tmp/com.apple.launchd.9spKmqe5XG/Render, TERM_PROGRAM_VERSION=388.1.1, OLDPWD=/Users/whoami/Lando, TERM_SESSION_ID=981491CD-9211-4D19-993E-C8D23320833A, USER=whoami, SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.E5BZIAB9Vz/Listeners, __CF_USER_TEXT_ENCODING=0x1F5:0x0:0x0, PATH=/Applications/Docker.app/Contents/Resources/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/DevDesktop/tools, PWD=/Users/whoami/Lando/thename, LANG=en_US.UTF-8, XPC_FLAGS=0x0, XPC_SERVICE_NAME=0, SHLVL=1, HOME=/Users/whoami, LOGNAME=whoami, SECURITYSESSIONID=186a6, _=/usr/local/bin/lando, LANDO_ENGINE_ID=501, LANDO_ENGINE_GID=20, LANDO_ENGINE_HOME=/Users/whoami, LANDO_ENGINE_IP=tcp://127.0.0.1, LANDO_ENGINE_REMOTE_IP=10.0.0.119, LANDO_ENGINE_CONFIG_DIR=/Users/whoami/.lando/services/config, LANDO_ENGINE_SCRIPTS_DIR=/Users/whoami/.lando/services/config/scripts, LANDO_ENGINE_HELPERS_DIR=/Users/whoami/.lando/services/config/helpers

debug: Engine is up.

debug: Cached true with key engineUp for {"persist":false,"ttl":5}

debug: Failed to cache true with key engineUp

verbose: Emitting event pre-engine-start

debug: Event pre-engine-start has 0 listeners

debug: About to run 0=/Applications/Docker.app/Contents/Resources/bin/docker-compose, 1=--project-name, 2=landoinitthe_name, 3=--file, 4=/Users/whoami/.lando/util/util.yml, 5=up, 6=-d, 7=--remove-orphans, 8=util

silly: With pre run opts app=undefined, mode=collect

verbose: Running spawn /Applications/Docker.app/Contents/Resources/bin/docker-compose with args ["--project-name","landoinitthe_name","--file","/Users/whoami/.lando/util/util.yml","up","-d","--remove-orphans","util"]

debug: In mode collect with detached false

debug: With env TERM_PROGRAM=Apple_Terminal, SHELL=/bin/bash, TERM=xterm-256color, TMPDIR=/var/folders/fl/59dsgf0s3r35nh68xk2l3r9h0000gn/T/, Apple_PubSub_Socket_Render=/private/tmp/com.apple.launchd.9spKmqe5XG/Render, TERM_PROGRAM_VERSION=388.1.1, OLDPWD=/Users/whoami/Lando, TERM_SESSION_ID=981491CD-9211-4D19-993E-C8D23320833A, USER=whoami, SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.E5BZIAB9Vz/Listeners, __CF_USER_TEXT_ENCODING=0x1F5:0x0:0x0, PATH=/Applications/Docker.app/Contents/Resources/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/DevDesktop/tools, PWD=/Users/whoami/Lando/thename, LANG=en_US.UTF-8, XPC_FLAGS=0x0, XPC_SERVICE_NAME=0, SHLVL=1, HOME=/Users/whoami, LOGNAME=whoami, SECURITYSESSIONID=186a6, _=/usr/local/bin/lando, LANDO_ENGINE_ID=501, LANDO_ENGINE_GID=20, LANDO_ENGINE_HOME=/Users/whoami, LANDO_ENGINE_IP=tcp://127.0.0.1, LANDO_ENGINE_REMOTE_IP=10.0.0.119, LANDO_ENGINE_CONFIG_DIR=/Users/whoami/.lando/services/config, LANDO_ENGINE_SCRIPTS_DIR=/Users/whoami/.lando/services/config/scripts, LANDO_ENGINE_HELPERS_DIR=/Users/whoami/.lando/services/config/helpers

landoinitthe_namemarketplace_util_1 is up-to-date

verbose: Spawn exited with code: 0

silly: Spawn finished with 

verbose: Emitting event post-engine-start

debug: Event post-engine-start has 0 listeners

debug: Retrieved from memcache with key engineUp

verbose: Emitting event pre-engine-run

debug: Event pre-engine-run has 0 listeners

error:  Error: Error: The container landoinitthe_name_util_1 does not exist!

    at /snapshot/cli/lib/promise.js:0:0

    at runCallback (timers.js:800:20)

    at tryOnImmediate (timers.js:762:5)

    at processImmediate [as _immediateCallback] (timers.js:733:5)

From previous event:

    at rec (/snapshot/cli/lib/promise.js:0:0)

    at /snapshot/cli/lib/promise.js:0:0

    at ontimeout (timers.js:488:11)

    at tryOnTimeout (timers.js:323:5)

    at Timer.listOnTimeout (timers.js:283:5)

From previous event:

    at /snapshot/cli/lib/promise.js:0:0

    at runCallback (timers.js:800:20)

    at tryOnImmediate (timers.js:762:5)

    at processImmediate [as _immediateCallback] (timers.js:733:5)
```
 
**Tell us generally about your bug**

I tried to initiate a new lando app that would be a Drupal 8 site. I ran lando init github (see below)

**Please detail the steps we can take to replicate this bug. Be as detailed as possible.**

1) Created GitHub token, as described in documentation

2) Created a repo on GitHub (https://github.com/myname/the_name.git). At first, I did NOT initiate with a readme

3) mkdir thename && cd thename

3) lando init github

? Enter a GitHub token [hidden]

? Which site? myaccount/thename

? What recipe do you want to use? drupal8

? Where is your webroot relative to the init destination? .

**Could better documentation have prevented this issue? if so what should we change?**

You tell me!

**Does this bug prevent you from using lando?**

Yes

**Comment by serundeputy** [comment]
Thanks for reporting @andileco !

I just ran through a `lando init github` setup with a repo I know to have working code and everything worked as expected.

* Pulled in my code
* Created a `.lando.yml` file for me
* `lando start` produces a working app

> error:  Error: Error: The container landoinitthe_name_util_1 does not exist!

Looks like the container may have crashed?  Just guessing, perhaps try restarting Docker and then try the `lando init github` again?  Make sure your computer meets the minimum specs for lando: https://docs.devwithlando.io/installation/system-requirements.html

**Comment by kgatjens** [comment]
I'm having the same problem.

**Comment by andileco** [comment]
@kgatjens, my issue is I had not downloaded the Drupal code, thinking that Lando would do it... It doesn't.

**Comment by brunomarks7** [comment]
try the following code:

`rm ~/.lando/cache/_.tasks.cache`
