### ISSUE TITLE
Error in compose file, retries should be a number.

### ISSUE THREAD

**Issue by neclimdul** [lando/lando#796]
Bug Report
==========

lando source build on Ubuntu 17.10

`.lando.yml`
```yml
name: laraveltest
recipe: laravel
config:
  webroot: ./public/
  via: nginx
  php: '7.2'
```

Error:
```bash
lando.dev start
Recreating landoproxyhyperion5000gandalfedition_proxy_1 ... 
Recreating landoproxyhyperion5000gandalfedition_proxy_1 ... done
ERROR: The Compose file '/home/neclimdul/.lando/compose/laraveltest/laraveltest-2.yml' is invalid because:
services.database.healthcheck.retries contains an invalid type, it should be a number
ERROR: The Compose file '/home/neclimdul/.lando/compose/laraveltest/laraveltest-2.yml' is invalid because:
services.database.healthcheck.retries contains an invalid type, it should be a number
ERROR: The Compose file '/home/neclimdul/.lando/compose/laraveltest/laraveltest-2.yml' is invalid because:
services.database.healthcheck.retries contains an invalid type, it should be a number
ERROR: The Compose file '/home/neclimdul/.lando/compose/laraveltest/laraveltest-2.yml' is invalid because:
services.database.healthcheck.retries contains an invalid type, it should be a number
ERROR: The Compose file '/home/neclimdul/.lando/compose/laraveltest/laraveltest-2.yml' is invalid because:
services.database.healthcheck.retries contains an invalid type, it should be a number
error: ErrorError: Error
    at /home/neclimdul/Programs/lando/lib/promise.js:55:17
    at runCallback (timers.js:794:20)
    at tryOnImmediate (timers.js:752:5)
    at processImmediate [as _immediateCallback] (timers.js:729:5)
From previous event:
    at rec (/home/neclimdul/Programs/lando/lib/promise.js:41:13)
    at /home/neclimdul/Programs/lando/lib/promise.js:49:20
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)
From previous event:
    at /home/neclimdul/Programs/lando/lib/promise.js:48:12
    at runCallback (timers.js:794:20)
    at tryOnImmediate (timers.js:752:5)
    at processImmediate [as _immediateCallback] (timers.js:729:5)
```

Failure to start because of some internal docker-compose processing error?

**Comment by pirog** [comment]
@neclimdul this doen't happen on OSX, it might be because of the `docker-compose` version you have

**Comment by pirog** [comment]
@neclimdul this doesnt happen for me on ubuntu 14.04 either.

**Comment by neclimdul** [comment]
```bash
$ docker-compose --version
docker-compose version 1.14.0, build c7bdf9e
$ docker --version
Docker version 17.12.0-ce, build c97c6d6
```
