### ISSUE TITLE
Error: Authorization failed. Please check that your machine token is valid. When pulling from Pantheon.

### ISSUE THREAD

**Issue by akanelson** [lando/lando#920]
Bug Report
==========

**Tell us about your setup**

What is your lando version and operating system? 
Lando v3.0.0-beta.40 and v3.0.0-beta.39
MacOS 10.13.3
Docker 18.03.0-ce-mac60 (23751)

**Tell us about your `.lando.yml`**
```yml
name: d7-mda-demo
recipe: pantheon
config:
  framework: drupal
  site: d7-mda-demo
  id: 49d4d30a-f7f6-4bf9-802c-bfa13b011121
```

**Tell us about your `.pantheon.yml`**
```yml
# Put overrides to your pantheon.upstream.yml file here.
# For more information, see: https://pantheon.io/docs/pantheon-yml/
api_version: 1
```

**Tell us about the command you were running**
```bash
lando pull --code=none
```

**Tell us about the error you got**
```bash
lando pull --code=none
error: Error: Authorization failed. Please check that your machine token is valid.Error: Error: Authorization failed. Please check that your machine token is valid.
    at /snapshot/lando/build/cli/lib/promise.js:0:0
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at rec (/snapshot/lando/build/cli/lib/promise.js:0:0)
    at /snapshot/lando/build/cli/lib/promise.js:0:0
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
From previous event:
    at /snapshot/lando/build/cli/lib/promise.js:0:0
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
```

**Tell us generally about your bug**
When running lando pull to get database and files I get a token authorization error against a vanilla Pantheon Drupal 7 installation.
I ran ```landon init pantheon``` and Terminus commands without issues.
All the lando init pantheon wizard worked as expected, I selected my pantheon account, the pantheon website to clone, etc.
I authenticated the Pantheon token a while ago but just in case I created a new token on Pantheon and added it on my machine.
```
1. lando init pantheon
2. lando pull --code=none
```
**Tell us more**
I initially did a clean install of Lando with brew to install the latest version v3.0.0-beta.40
I also tried y rempving and downloading from GitHub the previous .dmg version v3.0.0-beta.39.
Before installing the latest beta.40 version, I had Lando installed, not sure which version, maybe beta.39 and was working fine.
The issue started after uninstalling and installing latest beta.40.

Thanks.

**Comment by akanelson** [comment]
Nevermind, I didn't tell I needed to run ```lando terminus auth:login ...``` command. I only ran ```terminus auth:login```.
Now it's working.
Maybe the documentation is not clear enough on that, mostly because I could run ```lando init pantheon``` with just terminus token authenticated.
