### ISSUE TITLE
Lando init pantheon not working

### ISSUE THREAD

**Issue by serhatozkara** [lando/lando#926]
Bug Report
==========

v3.0.0-beta.39 on MacOS high sierra 10.13.4

```
lando init pantheon
```

At the choose account prompt, this happens:

`error: Cannot set property 'id' of undefinedTypeError: Cannot set property 'id' of undefined
    at /snapshot/lando/build/cli/plugins/lando-recipes/recipes/pantheon/client.js:0:0
    at arrayMap (/snapshot/lando/build/cli/node_modules/lodash/lodash.js:631:23)
    at Function.map (/snapshot/lando/build/cli/node_modules/lodash/lodash.js:9546:14)
    at /snapshot/lando/build/cli/plugins/lando-recipes/recipes/pantheon/client.js:0:0
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at pantheonUserSites (/snapshot/lando/build/cli/plugins/lando-recipes/recipes/pantheon/client.js:0:0)
    at Object.pantheonSites [as getSites] (/snapshot/lando/build/cli/plugins/lando-recipes/recipes/pantheon/client.js:0:0)
    at Object.choices (/snapshot/lando/build/cli/plugins/lando-recipes/recipes/pantheon/init.js:0:0)
    at /snapshot/lando/build/cli/node_modules/run-async/index.js:25:25
    at new Promise (<anonymous>)
    at module.exports (/snapshot/lando/build/cli/node_modules/run-async/index.js:24:19)
    at exports.fetchAsyncQuestionProperty (/snapshot/lando/build/cli/node_modules/inquirer/lib/utils/utils.js:20:60)
    at tryCatcher (/snapshot/lando/build/cli/node_modules/rx-lite/rx.lite.js:67:31)
    at InnerObserver.Rx.FlatMapObservable.InnerObserver.next (/snapshot/lando/build/cli/node_modules/rx-lite/rx.lite.js:1907:43)
    at InnerObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/snapshot/lando/build/cli/node_modules/rx-lite/rx.lite.js:1602:31)
    at InnerObserver.tryCatcher (/snapshot/lando/build/cli/node_modules/rx-lite/rx.lite.js:67:31)
    at AutoDetachObserverPrototype.next (/snapshot/lando/build/cli/node_modules/rx-lite/rx.lite.js:6495:51)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/snapshot/lando/build/cli/node_modules/rx-lite/rx.lite.js:1602:31)
    at InnerObserver.next (/snapshot/lando/build/cli/node_modules/rx-lite/rx.lite.js:2988:65)
    at InnerObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/snapshot/lando/build/cli/node_modules/rx-lite/rx.lite.js:1602:31)
    at InnerObserver.tryCatcher (/snapshot/lando/build/cli/node_modules/rx-lite/rx.lite.js:67:31)
    at AutoDetachObserverPrototype.next (/snapshot/lando/build/cli/node_modules/rx-lite/rx.lite.js:6495:51)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/snapshot/lando/build/cli/node_modules/rx-lite/rx.lite.js:1602:31)
    at scheduleItem (/snapshot/lando/build/cli/node_modules/rx-lite/rx.lite.js:2604:16)
    at JustObservable.subscribeCore (/snapshot/lando/build/cli/node_modules/rx-lite/rx.lite.js:2598:9)
    at JustObservable.tryCatcher (/snapshot/lando/build/cli/node_modules/rx-lite/rx.lite.js:67:31)
    at setDisposable (/snapshot/lando/build/cli/node_modules/rx-lite/rx.lite.js:1849:46)
    at JustObservable.Rx.ObservableBase.ObservableBase._subscribe (/snapshot/lando/build/cli/node_modules/rx-lite/rx.lite.js:1864:9)
    at JustObservable.Rx.Observable.observableProto.subscribe.observableProto.forEach (/snapshot/lando/build/cli/node_modules/rx-lite/rx.lite.js:1736:19)
    at MergeObserver.handleSubscribe (/snapshot/lando/build/cli/node_modules/rx-lite/rx.lite.js:2966:28)`

**Comment by pirog** [comment]
@serhatozkara fixed in dev, will be in beta.41 see #923
