### ISSUE TITLE
Allow more flex on the location of the Docker binary

### ISSUE THREAD

**Issue by legovaer** [lando/lando#935]
I'm currently working on a Docker container with Lando in it for CI/CD purposes with this OS:
`Linux 73eb08178848 4.9.87-linuxkit-aufs #1 SMP Wed Mar 14 15:12:16 UTC 2018 x86_64 Linux`

(Based upon the docker:stable image).

Everything goes fine until I start Lando:

```
error: TypeError: Cannot read property 'toUpperCase' of null
    at isInstalled (/lando/plugins/lando-engine/engine.js:39:15)
    at verifyDaemonInstalled (/lando/plugins/lando-engine/engine.js:54:12)
    at verifyDaemonIsReady (/lando/plugins/lando-engine/engine.js:317:12)
    at Object.list (/lando/plugins/lando-engine/engine.js:371:12)
    at /lando/plugins/lando-app/app.js:765:48
    at runCallback (timers.js:800:20)
From previous event:
    at cleanup (/lando/plugins/lando-app/app.js:764:6)
    at /lando/plugins/lando-app/app.js:819:14
From previous event:
    at Object.start (/lando/plugins/lando-app/app.js:818:6)
    at /lando/plugins/lando-app/tasks/start.js:24:28
From previous event:
    at Object.run (/lando/plugins/lando-app/tasks/start.js:20:8)
    at /lando/lib/cli.js:166:21
From previous event:
    at /lando/lib/cli.js:165:8
From previous event:
    at Object.command.handler (/lando/lib/cli.js:148:6)
    at Object.self.runCommand (/lando/node_modules/yargs/lib/command.js:170:22)
    at parseArgs (/lando/node_modules/yargs/yargs.js:920:28)
    at Object.get [as argv] (/lando/node_modules/yargs/yargs.js:860:16)
    at lando.events.emit.then.then.then (/lando/bin/lando.js:183:7)
    at runCallback (timers.js:800:20)
    at tryOnImmediate (timers.js:762:5)
    at processImmediate [as _immediateCallback] (timers.js:733:5)
From previous event:
    at bootstrap.then.lando (/lando/bin/lando.js:156:4)
From previous event:
    at Object.<anonymous> (/lando/bin/lando.js:74:2)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
    at Function.Module.runMain (module.js:682:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:613:3
```
I checked the code and I noticed that in `plugins/lando-engin/lib/env.js:36` there's this code:

```
exports.getDockerBinPath = function() {
  switch (process.platform) {
    case 'darwin':
      return path.join('/Applications/Docker.app/Contents/Resources', 'bin');
    case 'linux':
      return path.join('/usr/share/lando', 'bin');
    case 'win32':
      var programFiles = process.env.ProgramW6432 || process.env.ProgramFiles;
      return path.join(programFiles + '\\Docker\\Docker\\resources\\bin');
  }
};
```

My docker file exists, but for some reason Lando can't find it?

**Comment by pirog** [comment]
@dustinleblanc this looks familiar...

**Comment by dustinleblanc** [comment]
It definitely looks familiar!

Looking at the erroring code:

```js
// Return whether we have the engine executable in the expected location
      var which = lando.shell.which(DOCKER_EXECUTABLE);
      if (which.toUpperCase() === DOCKER_EXECUTABLE.toUpperCase()) {
        return Promise.resolve(true);
```

This looks like more of the same sort of issue I was looking at with why Lando + Circle 2.0 aren't friends.

My general feels are that I want to get away from relying on the docker executable paths since there are a growing number of ways to install it on Linux, however, I am very aware that my inclination is heavily influenced by a lack of practical experience that went into the design patterns.

Linux is proving to be an interesting target. It's Docker's home turf, and it has the widest variety of ways for Docker to behave, while also being the most performant platform of the bunch. The idea of installing Lando in a container that can then be used in CI/CD is VERY appealing too, so I'd love to have this solidly figured out. It should help with our 'be the best testing tool' aspirations

**Comment by legovaer** [comment]
@dustinleblanc I'm happy to share the Dockerfile so that it can be maintained within the GitHub Lando organisation.

I'm still looking into the issue, but it's hard to debug docker within docker..

**Comment by neclimdul** [comment]
seems like the simple fix to this specific issues would be something like
```
if (which === null) {
  lando.log.error('Docker executable can't be found. <link to how to add it to config>');
  // exit because nothing is going to work.
}
```

A more involved fix might be to refactor to use a node library for talking to docker directly since its just a fancy rest API. That would simplify configuration to "where's the socket/server" which is a lot more simple.

**Comment by pirog** [comment]
the tl;dr on that is we want to try the Docker we ship with first so we can ensure its a version we support, admittedly that is WAY more a Win/OSX thing but falling back to `which docker` seems like a good way to move forward here.

**Comment by pirog** [comment]
Alright, this is in the latest master. should fallback to use `which` if things aren't where we want
