### ISSUE TITLE
Custom services won't register when within the app. 

### ISSUE THREAD

**Issue by scotthooker** [lando/lando#961]
So firstly my plugin is being picked up fine. But my service inside my plugin is not.

`  lando.events.on('post-bootstrap', function (lando) {
    lando.services.add('myservice', require('./lib/myservice')(lando));
  });
`

Despite this I consistently get

`warn: myservice is not a supported service.`

Are there any better docs or examples on implementing a custom service within a custom plugin?

**Comment by scotthooker** [comment]
Ok so after chatting with @pirog on slack did some further playing/hacking/digging.

Custom services *do* work but only when defined within `~/.lando/`

Plugins which define a service or services within the app root do not get registered.

**Comment by scotthooker** [comment]
Closing this for now. As lando is fine. :)

**Comment by scotthooker** [comment]
Ok maybe since #765 was closed in favor of this. I'll reopen.

Essentially plugins can't live within the app. They need to live within .lando/

**Comment by dustinleblanc** [comment]
@pirog is the plan of attack here to allow plugin loading within an app? If so, I think that's supa cool

**Comment by tylerssn** [comment]
@dustinleblanc - as discussed in https://github.com/lando/lando/issues/597, I'd say that [Lando Plugin Anywhere](https://www.npmjs.com/package/lando-plugin-anywhere) is 90% there. If I can remember where I left off on that project, I think one of the outstanding issues I was working on was plugin dependency/loading order. Though, I think Lando's core events mostly made this feature negligible.

I'm happy to accept pull requests for anyone who wants to wrap this package up or simply hand the code over if the Lando team things the logic can be integrated into the core Lando package.

**Comment by tylerssn** [comment]
@scotthooker - does this PR resolve the issue for you [#961](https://github.com/lando/lando/pull/1169)? 

I was unable to create recipes as project-level plugins for the same reason as you are reporting and this seems to have done the trick.

**Comment by scotthooker** [comment]
This looks along the right lines! Will give it a go and test @tylerssn

**Comment by danielrojas08** [comment]
I have a problem similar to this one. Here is what it says:
Unhandled rejection TypeError: Cannot read property 'builder' of undefined
    at Factory.get (/snapshot/lando/build/cli/lib/factory.js:0:0)
    at AsyncEvents.module.exports.app.events.on (/snapshot/lando/build/cli/plugins/lando-recipes/app.js:0:0)
    at AsyncEvents.handle (/snapshot/lando/build/cli/lib/events.js:0:0)
    at emit.Promise.each.fn (/snapshot/lando/build/cli/lib/events.js:0:0)
    at runCallback (timers.js:696:18)
From previous event:
    at AsyncEvents.emit (/snapshot/lando/build/cli/lib/events.js:0:0)
    at module.exports.init.loadPlugins.then (/snapshot/lando/build/cli/lib/app.js:0:0)
From previous event:
    at App.init (/snapshot/lando/build/cli/lib/app.js:0:0)
    at lando.bootstrap.then.lando (/snapshot/lando/build/cli/bin/lando.js:0:0)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
From previous event:
    at Object.<anonymous> (/snapshot/lando/build/cli/bin/lando.js:0:0)
    at Module._compile (pkg/prelude/bootstrap.js:1252:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:711:10)
    at Module.load (internal/modules/cjs/loader.js:610:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:549:12)
    at Function.Module._load (internal/modules/cjs/loader.js:541:3)
    at Function.Module.runMain (pkg/prelude/bootstrap.js:1307:12)
    at startup (internal/bootstrap/node.js:274:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:608:3)

**Comment by tylerssn** [comment]
Danial - you may consider creating a new issue for this.

I'm not one of the Lando experts, but a quick look at the code indicates that "builder" is called on the services. My suggestion is to look at each of your services and it's `type:` property in the `.lando.yml` to make sure the type is supported.

**Comment by danielrose28** [comment]
I think you meant to tag @danielrojas08 :)
